### ISSUE TITLE
Derivative of the saturation enthalpy cair_sat = d(hsat)/dT

### ISSUE THREAD

**Issue by arashsk** [CoolProp/CoolProp#1005]
Calling low-level interface from MATLAB through shared library (DLL) seems not to have this function (cair_sat) available; is that true?
Revisited the documentations and there is little explained about this. Could you please let me know if this function is available and if not, is there any alternative method to calculate this using low-level interface from MATLAB through shared library (DLL)?

**Comment by ibell** [comment]
cair_sat is simply the derivative of humid air enthalpy along saturation curve, so you could evaluate it numerically.

cair_sat probably (almost certainly) isn't exposed, but we could do so if it was very useful for you.

Can you please provide a small standalone example of MATLAB code you are trying to run that doesn't work so I can be sure I know what you mean?

**Comment by arashsk** [comment]
Thanks for your quick reply. 

I'm working on a simulation model for a refrigeration system in Simulink. In part of this model, for a wet coil heat transfer calculation, I have an iterative loop that requires this derivative to be calculated at each iteration. 

The function can be accessed via high-level interface in MATLAB but not with the low-level:

Example in High-Level: (This works fine)
...
c_s = CoolProp.cair_sat(tRefOut)
...

tRefOut: is a temperature in Kelvin

Example in Low-Level: (This doesn't work)
... 
c_s =  calllib('coolprop','cair_sat',tRefOut);
...

Error using calllib
Method was not found.

Error in Cooling_Coil (line 109)
c_s =   calllib('coolprop','cair_sat',tRefOut)

**Comment by ibell** [comment]
Got it.  Right that function is not exported in dll.  I'll fix that
