### ISSUE TITLE
'error: key [Ar] was not found in string_to_index'

### ISSUE THREAD

**Issue by stefann82** [CoolProp/CoolProp#1007]
I can enter N2 for nitrogen, O2 for oxygen, H2O for water, etc. but I get an error when I use 'Ar' as the fluid name for argon. Entering 'argon' works, but 'Ar' throws an error. I get this with the nightly Excel plugin.

Full error:
Initialize failed for backend: "?", fluid: "Ar" fractions "[ 1.0000000000 ]"; error: key [Ar] was not found in string_to_index_map in JSONFluidLibrary : PropsSI("H","T",407.1222222,"P",101325,"Ar")

**Comment by Astrinus** [comment]
Valid aliases for Argon are `argon`, `ARGON`, `R740`, but not `Ar`.
Please see www.coolprop.org/fluid_properties/fluids/Argon.html#aliases

**Comment by ibell** [comment]
Wouldn't be a problem to add this alias. I'll do so.  If you run into other
obvious aliases we are missing, please let me know.
