### ISSUE TITLE
Can't compute densities at the triple point

### ISSUE THREAD

**Issue by dinojr** [CoolProp/CoolProp#1009]
Consider the following:
```
import numpy as np
import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt

fluide="Water"
Ptriple = CP.PropsSI(fluide,'ptriple')
Ttriple = CP.PropsSI(fluide,'Ttriple')

vtripleL = 1/CP.PropsSI('D','P',Ptriple,'Q',0,fluide)
vtripleG = 1/CP.PropsSI('D','P',Ptriple,'Q',1,fluide)
```

It fails with:
`Pressure to PQ_flash [611.655 Pa] must be in range [ 611.658 Pa, 2.2064e+07 Pa] : PropsSI("D","P",611.654667,"Q",0,"Water")`

It seems the test for the pressure in PQ_flash is too conservative. This problem didn't occur in CoolProp4.

**Comment by ibell** [comment]
I confirm:
```
import CoolProp
print CoolProp.__version__
print CoolProp.__gitrevision__
CP = CoolProp.CoolProp
fluide = "Water"
Ptriple = CP.PropsSI(fluide,'ptriple')
vtripleL = 1/CP.PropsSI('D','P',Ptriple,'Q',0,fluide)
vtripleG = 1/CP.PropsSI('D','P',Ptriple,'Q',1,fluide)
```
yields
```
5.1.3dev
50ab96fcd3f43b31c5e446284d453a75638d2c71
Traceback (most recent call last):
  File "C:\Users\Belli\Desktop\tttttt.py", line 7, in <module>
    vtripleL = 1/CP.PropsSI('D','P',Ptriple,'Q',0,fluide)
  File "CoolProp\CoolProp.pyx", line 321, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:38094)
  File "CoolProp\CoolProp.pyx", line 401, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:37876)
  File "CoolProp\CoolProp.pyx", line 290, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:36063)
ValueError: Pressure to PQ_flash [611.655 Pa] must be in range [ 611.658 Pa, 2.2064e+007 Pa] : PropsSI("D","P",611.654667,"Q",0,"Water")
```

**Comment by dinojr** [comment]
There is also a similar problem with the critical point:

```
import numpy as np
import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt

fluide="Water"
Pcritique = CP.PropsSI(fluide,'pcrit')
Tcritique = CP.PropsSI(fluide,'Tcrit')

vcritique= 1/CP.PropsSI('D','P',Pcritique,'T',Tcritique*.99,fluide)
```

yields:
`T=Tcrit; invalid input for other to T_phase_determination_pure_or_pseudopure : PropsSI("D","P",22064000,"T",647.096,"Water")`

**Comment by jowr** [comment]
Hi, why not try this
```Python
import numpy as np
import CoolProp.CoolProp as CP
fluide="Water"
Pcritique = CP.PropsSI(fluide,'pcrit')
Tcritique = CP.PropsSI(fluide,'Tcrit')
vcritique= 1.0/CP.PropsSI('D','P',Pcritique,'T',Tcritique+0.1,fluide)
```

**Comment by dinojr** [comment]
That's exactly what I'm doing at the moment but I thought this behaviour should be reported since their seems to be some inconsistency between, for instance, the value of Tcritique used in CP.PropsSI(fluid,'Tcrit') and the ones used in some internal checks by CP.PropsSI('D').

**Comment by dinojr** [comment]
Thanks. When can we expect this fix to make its way to the pip repository ?

**Comment by ibell** [comment]
Development binaries automatically generated.  See
http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#automatic-installation
(second one)

**Comment by dinojr** [comment]
Thanks, I could install it, and the critical pressure doens't thrown any errors. However, the critical temperature does... See for instance the following:
 `CP.PropsSI("D","P",CP.PropsSI("carbondioxide",'pcrit'),"T",CP.PropsSI("carbondioxide",'Tcrit'),"carbondioxide")`
Sorry for not mentioning earlier that the same problem was occuring with both pressure and temperature.

**Comment by ibell** [comment]
Can you please file a new issue with regards to critical point?

**Comment by dinojr** [comment]
done: https://github.com/CoolProp/CoolProp/issues/1034
