### ISSUE TITLE
Conductivity of Humid Air

### ISSUE THREAD

**Issue by icosrle31** [CoolProp/CoolProp#1013]
Dear Sirs,

I discoved that Cool Prop is developed for humid air also. Behind the state propreties of humid air, in the model I need specific heat, conductivity and viscosity. But, in the example of conductivy, I received strange result. For example:

HAProps('K','T',273.15+T_in,'P',101.325,'R',0.5)

Pressure is in kPa, Tin=24.15.

ans =

     3.853064065755298e-07

I have used version 4.x HA CoolProp.
Please, help, thank you, Igor

**Comment by ibell** [comment]
Thanks for your note

a) 4.x is no longer actively supported, please use v5.1.x
b) You should use the HAPropsSI function in which all inputs/outputs are in
base-SI units (W, m, J, etc.)

**Comment by icosrle31** [comment]
Thank you,
I use MATLAB on Mac, maci64
I have download CoolProp 5.1.2 and copy the folllowing files in working folder: 
CoolPropMATLAB_wrap.mexmaci64
SwigRef.m
CoolPropsetup.m
Example.m

and start example file and receive:
<img width="1440" alt="screen shot 2016-04-07 at 09 55 37" src="https://cloud.githubusercontent.com/assets/18311203/14344367/7188b89e-fca7-11e5-80b7-677eba7d414a.png">

or

**************** INFORMATION ***************
This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell
Invalid MEX-file '/Users/igorkovacevic/KU_Leuven/CoolPropMATLAB_wrap.mexmaci64':
dlopen(/Users/igorkovacevic/KU_Leuven/CoolPropMATLAB_wrap.mexmaci64, 6): Symbol not found:
__ZTISt16invalid_argument
  Referenced from: /Users/igorkovacevic/KU_Leuven/CoolPropMATLAB_wrap.mexmaci64
  Expected in: /Applications/MATLAB_R2015b.app/bin/maci64/libmx.dylib
 in /Users/igorkovacevic/KU_Leuven/CoolPropMATLAB_wrap.mexmaci64

Error in CoolProp.get_global_param_string (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(320,varargin{:});


Error in Example (line 3)
disp([num2str('CoolProp version:'), ' ', num2str(CoolProp.get_global_param_string('version'))]);

In version 5, Humid air database is inside CoolProp, and no separate file?

Thank you,
Igor
 
>>

**Comment by ibell** [comment]
I think you need to read the instructions here: http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#matlab

You don't have the ``+CoolProp`` package.

Also, I recommend starting with a clean directory, just to be sure that you don't have conflicts between old and new files, at least for testing.

And then, when you are setup properly, you would do:
```
CoolProp.HAPropsSI("D","T",300,"P",101325,"R",0.5)
```
for instance

**Comment by icosrle31** [comment]
Dear Ian,

I red few times, and CoolProp works in version 4 or less. Version 5 I can not instal on my Mac. I have tried and different unarchiver. Now, I have instal on CoolProp folder:
<img width="1440" alt="screen shot 2016-04-08 at 10 11 07" src="https://cloud.githubusercontent.com/assets/18311203/14377977/fe084b4c-fd72-11e5-8b5f-f08746eecbc5.png">

and receive in MATLAB the same answer:
<img width="1440" alt="screen shot 2016-04-08 at 10 11 11" src="https://cloud.githubusercontent.com/assets/18311203/14377996/0eb4cf88-fd73-11e5-8bf5-1bda9c2a1290.png">

Do you have any comments? In version 4 it is problem with humid air conductivity (units).

Thank you in advance.
Igor

**Comment by ibell** [comment]
Aha. You are on OSX 10.10, aren't you...  The maci64 uploaded to our
servers only works for 10.9.  One of our users uploaded one for 10.10 :
https://github.com/CoolProp/CoolProp/issues/596 (see the link near the
bottom from pdenis13)

**Comment by icosrle31** [comment]
Thank you very much. This update works with OS 10.11. You should inform about operating system in instructions. 

May I use CoolProp for publishing scientific paper with presented reference on the site?

Thank you for cooperation.
Igor

**Comment by jowr** [comment]
No problem, go ahead publish and use the information from http://coolprop.sourceforge.net/citation.html to reference CoolProp.

**Comment by ibell** [comment]
Can you please try the .mexmaci64 here: http://www.coolprop.dreamhosters.com:8010/unstable/MATLAB/OSX10.10%2B/ ?  I think it should work for you, and this will be automatically generated and kept in sync with the code

**Comment by icosrle31** [comment]
Thank you very  much. We will use this reference.Kind regards,Igor

Date: Mon, 11 Apr 2016 05:53:58 -0700

**Comment by icosrle31** [comment]
It works! I have downloaded all files together. Also, I recognize that this solver works faster than previous one, downloaded from dropbox.Nice work.... Thanks.

Kind regards,Igor
Date: Mon, 11 Apr 2016 21:02:09 -0700

**Comment by ibell** [comment]
Excellent!  Thank you @icosrle31 for the update, and most especially for the comment about the speed.  I bet the other one was built in Debug mode, which for some cases is MUCH slower.
