### ISSUE TITLE
AbstractState.update fails for mixtures containing specific refrigerants using REFPROP backend

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#1023]
EDITED: Issue is more general than I initially thought and not limited to arrays and dictionaries. The problem arises when at least two unique refrigerant mixtures from the list below are accessed and then a previous one is reaccessed: 

    AbstractState s1 = AbstractState.factory("REFPROP", "R445A.MIX");
    AbstractState s2 = AbstractState.factory("REFPROP", "R446A.MIX");
    s1.update(input_pairs.PQ_INPUTS, 100000, 0); // throws exception

Exception carries message: "Could not load these fluids: CARBON DIOXI|R134A|R1234ZE(E)"
(changing depending on what the components are) This occurs only for the following conditions:
- Backend is REFPROP
- Mixture contains a fluid for which the CoolProp and REFPROP name strings differ: isobutane, R1234ze(z), propylene, etc.

Note that this does NOT fail when done in this order:

    AbstractState s1 = AbstractState.factory("REFPROP", "R445A.MIX");
    s1.update(input_pairs.PQ_INPUTS, 100000, 0);
    AbstractState s2 = AbstractState.factory("REFPROP", "R446A.MIX");
    s2.update(input_pairs.PQ_INPUTS, 100000, 0);

The key seems to be going from one state object to the other and back again.

Nightly build of CoolProp. REFPROP 9.12.

**Comment by mapipolo** [comment]
Full list of refrigerants to which this issue applies:
    R406A
    R411A
    R411B
    R413A
    R414A
    R414B
    R419A
    R419B
    R422A
    R422B
    R422C
    R422D
    R422E
    R424A
    R426A
    R428A
    R429A
    R430A
    R432A
    R433A
    R433B
    R433C
    R434A
    R435A
    R436A
    R436B
    R438A
    R439A
    R441A
    R443A
    R444A
    R444B
    R445A
    R446A
    R447A
    R448A
    R450A
    R453A
    R510A
    R511A

**Comment by mapipolo** [comment]
Turning CoolProp's debug level to 10 yields helpful info from REFPROPMixtureBackend.set_REFPROP_fluids:

REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (CARBON DIOXI).
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (CARBON DIOXI.FLD).
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (CARBON DIOXI.fld).
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (CARBON DIOXI.PPF).
k: 4 #endings: 5

The file we're looking for is called "CO2.FLD", and that is in fact what comes back in component_string from the call to SETMIXdll() in REFPROP.dll (ierr also is set to 1 here). Somewhere along the line, "CO2" is being replaced with "CARBON DIOXI".

**Comment by mapipolo** [comment]
I was able to temporarily fix this by making copies of the following NIST .FLD files...
    CO2
    DME
    ISOBUTAN
    IPENTANE
    PROPYLEN
    R1234ZE

... and renaming them to the following:

    CARBON DIOXI
    DIMETHYLETHE
    ISOBUTANE
    ISOPENTANE
    PROPYLENE
    R1234ZE(E)

**Comment by ibell** [comment]
Hmm I will try to look into this issue in the coming days, I will see what
can be done.  I can't guarantee a timeframe, but I will do my best.  It
sounds like a simple bug, really.  Probably long names are getting returned
when short names should.  Your bug report should allow for relatively easy
debugging.

More generally, I am not sure that you are really saving yourself much time
by using your Dictionary to REFPROP instances.  As long as you keep using
the same instance, you will see a benefit in speed.  Otherwise, if you
alternate between two mixtures, each time you switch, SETUPdll will get
called again, which absolutely will kill your speed.  But, if you use one
or another, and not both concurrently, then you should see a benefit.

**Comment by ibell** [comment]
I think I fixed it.  Please let me know.

**Comment by mapipolo** [comment]
Seems to be fixed! Thanks.
