### ISSUE TITLE
Problem with PT_INPUTS update

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#1027]
On the modelica wrapper ExternalMedia, there is an update problem when using the `PT_INPUTS` update:

First run of the update with PT gives partly wrong results:
```C++
		double p=5.0e+5;
		double T=273;
		shared_ptr<CoolProp::AbstractState> state;
		state.reset(CoolProp::AbstractState::factory("HEOS", "Helium"));

		state->clear();
		state->update(CoolProp::PT_INPUTS,p,T);

		std::cout << format("state->hmass() = %0.16e\n",state->hmass());
```
With wrong output:
```
state->hmass() = 7.4308908389366325e+003
```

But if a HmassP (for instance) update is done first:
```C++
		double p=5.0e+5;
		double T=273;
		shared_ptr<CoolProp::AbstractState> state;
		state.reset(CoolProp::AbstractState::factory("HEOS", "Helium"));


		state->update(CoolProp::HmassP_INPUTS,1000,p);
		state->clear();
		state->update(CoolProp::PT_INPUTS,p,T);

		std::cout << format("state->hmass() = %0.16e\n",state->hmass());
```
With correct output:
```
state->hmass() = 1.4245087609712468e+006
```

See https://github.com/CoolProp/ExternalMedia/issues/17

**Comment by ibell** [comment]
Cab you please fill in the numbers where you have variables so I can more
easily test?  Also, what is "wrong results"?  What should they be?

**Comment by JonWel** [comment]
You are right, I completed the first post which should be easier to debug.
Meanwhile I check if the updated CoolProp would work better.

**Comment by jowr** [comment]
Is that for water?

**Comment by JonWel** [comment]
@jowr Sorry, forgot to specify the fluid (Helium here, I try to do a similar test case with water), corrected.

I still have the same result with fresh files (just downloaded).

**Comment by JonWel** [comment]
Testing with Water, P = 5e5, T= 283 (10°C higher to have liquid water).
The call to `PT_INPUTS` crash:
```
The following error was detected at time: 0
solver_rho_Tp was unable to find a solution for T=       283, p=    500000, with
 guess value    234.765
```

But if doing the same `state->update(CoolProp::HmassP_INPUTS,1000,p);` before, the `PT_INPUTS` works and gives:
```C++
hmass = 4.1878603114591177+e004
```

**Comment by ibell** [comment]
If I do this example:
``` c++
    shared_ptr<AbstractState> AS(AbstractState::factory("HEOS","Water"));
    AS->update(PT_INPUTS, 5e5, 283);
    double hh = AS->hmass();
```
I get :
h	41878.603114532954
which seems fine.

**Comment by ibell** [comment]
And if I do:
``` c++
shared_ptr<AbstractState> AS(AbstractState::factory("HEOS","Helium"));
AS->update(PT_INPUTS, 5e5, 273);
double hh = AS->hmass();
```
I get:
hh	1424508.7609712468
which also seems fine.  Can you make a minimal working example .cpp file and attach it to this issue?  I can't replicate your results.

I'm using Xcode(clang) on OSX with tippy development version

**Comment by JonWel** [comment]
@ibell It will be easier to do when the https://github.com/CoolProp/ExternalMedia/issues/18 will be solved as you don't have access to Dymola right now.

Or would it be simple enough for you to call functions from the `ExternalMediaLib.lib` library?

**Comment by ibell** [comment]
I need a standalone example that I can test/debug that demonstrates the
problem.  Otherwise, I have no idea now to replicate the problem and/or
figure out how to fix it.

**Comment by JonWel** [comment]
@ibell With the last updates from the GitHub:
```Bash
git clone https://github.com/CoolProp/ExternalMedia.git ExternalMedia
```

In `ExternalMedia/Projects/Sources/coolpropsolver.cpp`, replace the line `562` by:
```C++
        state->update(CoolProp::PT_INPUTS,p,T);
        std::cout << format("state->hmass() = %0.16e\n",state->hmass());
        state->update(CoolProp::HmassP_INPUTS,1000,p);
        std::cout << format("state->hmass() = %0.16e\n",state->hmass());
        state->clear();
        state->update(CoolProp::PT_INPUTS,p,T);
        std::cout << format("state->hmass() = %0.16e\n",state->hmass());
```

And replace the file `ExternalMedia/Projects/Tests/coolprop_comparisons.cpp` by
http://pastebin.com/2tqNsHCr

Then compile:
```Bash
cd ExternalMedia/Projects/
BuildLib-CMake.bat
```

And run the file `ExternalMedia/Projects/build/Release/main.exe`.

**Comment by JonWel** [comment]
Thanks to the help of @jowr , the problem has been solved.
In the initialisation, I made used of `specify_phase()`, without clearing that state with a `unspecify_phase();` (I thought `clear()` would have done the thing).

Now, the update function gives the expected results.

**Comment by ibell** [comment]
@JonWel - I figured it was something like that, which is why I wanted you to come up with a stripped-down test case.  Glad you and @jowr  were able to sort it out.

phase specification flag is not reset in clear() because otherwise you would need to specify the phase prior to every flash call which would be very annoying.  Especially in the case where you know your inputs are in the gas phase always (compressor, etc.)
