### ISSUE TITLE
Python builder issues

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1033]
@jowr - I resolved most of the issues with python 3.5, but I need your help to unbreak the conda builds for python.  There are random hangs, and timeouts, and I have no idea how to debug.  Its not repeatable!

I know you have put a lot of work into the conda builds.  But what is your opinion about switching to manylinux wheels and giving up on generating conda builds?  That might be a bit more reliable.

I'm hoping to release v6 pretty soon.  I have the viscosity stuff to fix, and then I think that's about it.

**Comment by jowr** [comment]
Yes, let us drop conda, one less thing to maintain...

**Comment by ibell** [comment]
I'll have to figure out this manylinux wheel thing, but I should figure out that and docker anyway, so it's a useful investment in time I think.  Then we say goodbye and good riddance to the conda builds.

**Comment by henningjp** [comment]
How will that affect Windows builds?  Conda is used there, I think.  Not sure anylinux runs on windows.

**Comment by ibell** [comment]
It will have no impact on windows or OSX.  It simply means that for all platforms you will do ``pip install CoolProp``, which will be a binary wheel, rather than dealing with the nightmare that is building conda packages.  That has been a major pain for @jowr and me
