### ISSUE TITLE
Strange behaviour of densities at critical point

### ISSUE THREAD

**Issue by dinojr** [CoolProp/CoolProp#1034]
Consider the following 

```
import numpy as np
import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt

fluid="Water"
Pcritical = CP.PropsSI(fluid,'pcrit')
Tcritical = CP.PropsSI(fluid,'Tcrit')

CP.PropsSI('D','P',Pcritical,'T',Tcritical,fluid)
```
It fails with:
`ValueError: T=Tcrit; invalid input for other to T_phase_determination_pure_or_pseudopure : PropsSI("D","P",22064000,"T",647.096,"Water")`

However
`CP.PropsSI('D','P',Pcritical,'T',0.9*Tcritical,fluid)`
doesn't complain whereas it should, since the density can be anything between that of the gas and that of the liquid.

Finally
`CP.PropsSI('D','P',Pcritical,'Q',0,fluid)` and `CP.PropsSI('D','P',Pcritical,'Q',1,fluid)` correctly give the same density for the gas and liquide phase at the critical point.

**Comment by ibell** [comment]
Are you using the development version?  That should work fine to evaluate PT at the critical point (I thought).  I am 100% sure that evaluating TD at the critical point should work for water.  Perhaps I need to fix PT at the critical point.

**Comment by dinojr** [comment]
I installed with the second method at  http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#automatic-installation. I couldn't find a `CP.__version__ `property to check the version but I only have a CoolProp-5.1.3.dev0.egg-info in /usr/loca/lib/python3.5/dist-packages.

Also what do you mean by evaluating PT or PD ? What should I check ?

**Comment by ibell** [comment]
Hopefully this explains my (poorly described) comment:
``` python
from __future__ import print_function
import numpy as np
import CoolProp
import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt

print('version:', CoolProp.__version__)

fluid = "Water"
Pcritical = CP.PropsSI(fluid,'pcrit')
Tcritical = CP.PropsSI(fluid,'Tcrit')
rhomolar_critical = CP.PropsSI(fluid, 'rhomolar_critical')

print('Using DT:', CP.PropsSI('P','Dmolar',rhomolar_critical,'T',Tcritical,fluid))
print('Using PT:', CP.PropsSI('Dmolar','P',Pcritical,'T',Tcritical,fluid)) 
```
which fails on PT call:
```
version: 5.1.3dev
Using DT: 22064000.0
Traceback (most recent call last):
  File "/Users/ian/Desktop/pooo.py", line 15, in <module>
    print('Using PT:', CP.PropsSI('Dmolar','P',Pcritical,'T',Tcritical,fluid))
  File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:38247)
  File "CoolProp/CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:38029)
  File "CoolProp/CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:36216)
ValueError: T=Tcrit; invalid input for other to T_phase_determination_pure_or_pseudopure : PropsSI("Dmolar","P",22064000,"T",647.096,"Water")
```

**Comment by dinojr** [comment]
Thanks for clarifying it. I've never played with the PT and DT methods. Where can I read about it ?

Also, do you agree that CP.PropsSI('D','P',Pcritical,'T',0.9*Tcritical,fluid) should give an error message ?

**Comment by ibell** [comment]
PT: Pressure/temperature inputs
DT: Density (molar or mass)/temperature inputs

The EOS are all explicit in DT, so that will always be the fastest inputs, as it generally involves no iteration.  You might want to read our paper on CoolProp (http://www.coolprop.org/citation.html), and/or check out the docs here: http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids

Evaluation at pcrit, 0.9*Tcrit should be a valid set of inputs, but based on the way that we deal with the critical temperature/density/pressure, it sometimes causes problems.  Probably I should fix it.

**Comment by dinojr** [comment]
Ian Bell <notifications@github.com> writes:

> You might want to read our paper on CoolProp
> (http://www.coolprop.org/citation.html), and/or check out the docs
> here:
> http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids

will do, thanks.

> Evaluation at pcrit, 0.9*Tcrit should be a valid set of inputs,

as long as you also specify the 'Q' parameter along with it.
