### ISSUE TITLE
Compiler warnings from REFPROP routines

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1037]
Compiling under VS2010 on Windows 10, REFPROP routines are throwing **warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.**  in the following locations:

REFPROP_lib.h(533)
REFPROP_lib.h(536)
REFPROPMixtureBackend.cpp(290)
REFPROPMixtureBackend.cpp(311)
REFPROPMixtureBackend.cpp(367)

And **warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data** at location:
REFPROPMixtureBackend.cpp(369)

**Comment by jowr** [comment]
Are you using the latest version? This line should disable the warnings https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L47

**Comment by henningjp** [comment]
I did a fetch a day or two ago.  I'll merge again tonight after work and see in they are still there.  I'll let you know.

**Comment by henningjp** [comment]
Yep.  It's fixed.  Still a problem with REFPROP_lib.h in externals/REFPROP, but I patched that one as well.

I patched the conversion issue in REFPROPMixtureBackend.cpp as well.  It'll come with my next pull request.
