### ISSUE TITLE
Paratherm oil viscosity

### ISSUE THREAD

**Issue by LORENZOTOCCI** [CoolProp/CoolProp#1040]
Dear Dr. Ian Bell,

I am performing some calculations using Coolprop coupled with Matlab, using Paratherm fluids.
It results, comparing the Coolprop values with the Paratherm datasheets, that the viscosity values in the software show to be off by a factor of 1000.
Are you aware of this?
Is there the possibility to solve this issue?
Alternatively, Is there a way to implement the heat transfer fluid thermodynamic properties in Refprop?

Thanks a lot for your help.

Best regards,
Lorenzo Tocci

**Comment by jowr** [comment]
This one should have been fixed long ago. Could you please post and example and tell us which version of CoolProp you are using? If you tell me what is wrong, i'd love to fix it.

**Comment by jowr** [comment]
I guess what you are saying is that 
http://coolprop.sourceforge.net/_downloads/PNF_fitreport.pdf is off by a factor of 1000 and that http://coolprop.sourceforge.net/_downloads/PNF2_fitreport.pdf is correct?

**Comment by jowr** [comment]
It would be a huge help, if you could check the data in https://github.com/CoolProp/CoolProp/blob/master/dev/incompressible_liquids/CPIncomp/PureFluids.py and file a pull request with your corrections.

**Comment by LORENZOTOCCI** [comment]
Good morning,I used the following high temperature incompressible fluids in my analysis:T66T72TVP1TX22Dow JDow J2Dow QDow Q2PMRPHEPHRPNFPNF2PGLTPBBThe fluids that show to be off by 1000 in the viscosity are PMR, PHE, PHR, PNF, PGLT. It would be a huge help for us if you could fix these. Please find attached the bulletin from the Paratherm website of some of their fluids.In the meantime, I'll check over the code you sent me to see if there are some additional mistakes.Thanks a lot for your help.Best regards,Lorenzo TocciMechanical EngineerEntropea Labs Limited2a Greenwood Road, London, E8 1AB, United KingdomEmail: lorenzo@entropea.comWeb: www.entropea.com 


-------- Original Message --------
Subject: Re: [CoolProp/CoolProp] Paratherm oil viscosity (#1040)

**Comment by ibell** [comment]
@jowr, should we make a plot of Prandtl number v. temperature for all the
incompressibles?  That might help to pick out values that are obviously
off.  And then conductivity v. temperature too, since it only varies by a
factor of 10ish.
