### ISSUE TITLE
HAPropsSI() doesn't appear to be using SI Units

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1043]
Please forgive me if I'm doing something stupid, but it looks to me like HAPropsSI() is using pressure units of kPa (not Pa) and energy units of kJ (not J).  This is inconsistent with SI units and the rest of the CoolProp functions.  I've attached some Mathcad output (as PDF) that I'm testing.  Can someone verify this behavior in Python, or another wrapper?

[HAPropsSI Verification in Mathcad.pdf](https://github.com/CoolProp/CoolProp/files/243959/HAPropsSI.Verification.in.Mathcad.pdf)

**Comment by henningjp** [comment]
Nevermind.  I found it.  The old Mathcad wrapper was calling HAProps(), not HAPropsSI().  I'll fix it.

**Comment by ibell** [comment]
I figured it was something along those lines...  Glad to hear there isn't
anything to fix.
