### ISSUE TITLE
Problem with MITSW in Matlab wrapper

### ISSUE THREAD

**Issue by tjcrone** [CoolProp/CoolProp#1046]
I'm trying to use this code for high T-P seawater properties, but there seems to be a problem with MITSW in the Matlab wrapper:

num2str(CoolProp.PropsSI('C', 'P', 22e6, 'T', 273+300, 'MITSW'))
Warning: Initialize failed for backend: "?", fluid: "MITSW" fractions "[
1.0000000000 ]"; error: key [MITSW] was not found in string_to_index_map in
JSONFluidLibrary 
Error using CoolProp_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolProp_wrap(313,varargin{:});

This fluid does seem to have a json file (dev/incompressible_liquids/json/MITSW.json), but is it not included somewhere where it needs to be?

Thanks,
Tim

**Comment by ibell** [comment]
Hi Tim, it's an incompressible fluid, so your fluid string should read
"INCOMP::MITSW"
