### ISSUE TITLE
apply_simple_mixing_rule should be implemented for HEOS instances

### ISSUE THREAD

**Issue by ianhbell** [CoolProp/CoolProp#1049]

**Comment by calla80** [comment]
I'm using coolprop on Matlab, and I ve problems in creating a user defined mixture:

With this:

addpath('C:\Users\Claudia\Documents\MATLAB\Main')
CAS_He = CoolProp.get_fluid_param_string('Helium','CAS');
CAS_Xe = CoolProp.get_fluid_param_string('Xenon','CAS');
CoolProp.apply_simple_mixing_rule(CAS_He,CAS_Xe,'linear');

I got this error:
Warning: function AbstractState_apply_simple_mixing_rule requires at least 4 arguments 
Error using CoolPropMATLAB_wrap
Fatal error.
Error in CoolProp.apply_simple_mixing_rule (line 2)
      [varargout{1:nargout}] = CoolPropMATLAB_wrap(219,self, varargin{:});
Error in mixture_G (line 8)
CoolProp.apply_simple_mixing_rule(CAS_He,CAS_Xe,'linear');


How can I solve this problem?
