### ISSUE TITLE
Decouple buildbot master configuration and main repo

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1052]
@jowr - having spent almost all day in fits and starts trying to get the MathCAD builder working, I have been getting frustrated with the amount of time you have have to wait between a push modifying a builder in the master config and the build actually firing.

What do you think about putting the buildbot server configuration in its own repository apart from the main code.  That way, pushes to the master config don't fire all the builds, which is extremely annoying when trying to debug/add builders.

**Comment by jowr** [comment]
I tend to work with the configuration file on the server without using git. Once I have the correct configuration, I edit my local file, commit and push. The I reset the server file to the repository version and everything is in sync again. The workflow would be:

1. SSH to server and play with configuration file.
2. Run `./scripts/buildbot.sh reconfig` on server to activate changes, **ignore** git warnings.
3. Repeat 1. and 2. until you are happy, then copy server file to local repo.
4. Commit and push local repo.
5. Run `git reset HEAD dev/buildbot/master/master.cfg` on server.
6. Run `./scripts/buildbot.sh reconfig` on server, make sure there are **no** warnings from git.

Do you think that you could work this way too?

**Comment by ibell** [comment]
@jowr - yes I suppose this is a viable solution, but I'm not a fan of / good at using terminal based text editors (vi, nano, etc.).  I guess if I found a good SFTP tool with text editor integration, that might be possible to solve all my problems and we could leave things as is.

**Comment by ibell** [comment]
Cyberduck+Sublime Text seems to do the job actually.

**Comment by thorade** [comment]
Long time ago I used WinSCP to do something similar:
https://winscp.net/eng/docs/screenshots
