### ISSUE TITLE
Integrate manylinux wheel builder with docker repo

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1061]
Shouldn't we integrate https://github.com/CoolProp/CoolProp/tree/master/wrappers/Python/manylinux with https://github.com/CoolProp/Dockerfiles and https://hub.docker.com/u/coolprop/ ?

**Comment by ibell** [comment]
Good idea! I'm not familiar with all that, in fact just getting my docker
image up and running was a bit of a challenge, but I welcome you to look
into it.

**Comment by jowr** [comment]
I figured it was something along these lines... I'll see when I can do it.
