### ISSUE TITLE
Mathcad wrapper not working

### ISSUE THREAD

**Issue by rllthomas** [CoolProp/CoolProp#1063]
The Mathcad Prime wrapper works in Prime 3.1, however the current nightly (5.1.3dev) Mathcad 15 compiled wrapper from SourceForge does not.  The 4.2.5 compiled wrapper does.  I tried compiling 5.1.2 however I received several LNK 2019 errors.  Not being a developer I didn't pursue further.

**Comment by henningjp** [comment]
Just tested it; it works fine here.  Make sure you are testing it against the example `.xmcdz` file in that same directory, not the `.xmcd` file, which is out of date and uses the old version 4.x function names.  Also, copy the `CoolProp_EN.xml` file to your `C:\Program Files (x86)\Mathcad\Mathcad 15\doc\funcdoc` directory and the correct, version 5.x, function names will come up in the **Insert Function** panel of the Mathcad 15 interface.

@ibell, this outdated `.xmcd` file needs to go away...

**Comment by rllthomas** [comment]
Well there you have it, I was using the .xmcd file.  Sorry to waste your time.

Rich

**Comment by henningjp** [comment]
Also, development on the Mathcad wrapper was non-existent after version 4.x, so getting it to work in the version 5.x repos will be difficult as the compile instructions are incorrect.  All the CoolProp function names changed and the Mathcad wrapper didn't keep up......until now.  5.1.3dev is going to get released as version 6.0 very shortly (days).

**Comment by henningjp** [comment]
@ibell, I'll let you close this when that `.xmcd` file goes away on SourceForge.  :smirk:

**Comment by ibell** [comment]
Soon, soon, tonight I hope...

**Comment by ibell** [comment]
Cleaned up!
