### ISSUE TITLE
update externals

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1065]
While getting ready for v6, shouldn't we update the external code as well? Any objections anyone? I'll start looking into it in a branch.

**Comment by ibell** [comment]
Well, that does seem to have some problems.  I'm releasing v6 and then we
can dig into this some more.

**Comment by jowr** [comment]
Alright, I am going to have a second look later.

**Comment by ibell** [comment]
I've bumped most of these, though there seem to have been some pretty major API changes in msgpack-c, so leaving that off for now.

**Comment by jowr** [comment]
Great!
