### ISSUE TITLE
Implement PT solver for two-phase inputs

### ISSUE THREAD

**Issue by jwalk1** [CoolProp/CoolProp#1066]
Is there a lower limit temperature threshold? I am trying to simulate LNG temperatures. 

ValueError: Bad phase to solver_rho_Tp_SRK : PropsSI("CP0MASS","T",115,"P",100000,"Methane[0.95]&Ethane[0.05]")

``` python
import pandas as pd
from CoolProp.CoolProp import PropsSI

temp = (115, 130, 145, 160, 175, 190, 205, 220, 235, 250, 265, 280, 295, 310)

list = []

for i in temp:

	an= PropsSI('CP0MASS','T',i,'P', 100e3,'Methane[0.95]&Ethane[0.05]')
	list.append(an)

df = pd.DataFrame(list)

pd.DataFrame.to_csv(df, "C....output.csv")

print df
```

**Comment by ibell** [comment]
Couple of comments:
1) Do the higher temperatures work? I think they should.
2) In python, its not a good idea to call your variable list, since that is a python function, and that could have unintended side-effects....

**Comment by jwalk1** [comment]
Thanks for the reply. Yes, the higher temperatures work. I could not find a PropsSI function that calcs dew point?

**Comment by ibell** [comment]
How about
``` python
PropsSI("T","P",100e3,"Q",1,"Methane[0.95]&Ethane[0.5]")
```
Q is vapor quality (0: bubble, 1: dew)

**Comment by jwalk1** [comment]
Thank you for the reply. 

So, the dew temperature is 166K for this mix. However, this should not affect the calculation of enthalpy. I have other software that calculates this property in the liquid phase. Is there a built-in threshold where the calculation fails?

**Comment by ibell** [comment]
The problem is with CoolProp.  We currently have no support for PT inputs
that are in two-phase region, and we don't error out properly.  For this,
you will need to use REFPROP.

**Comment by ibell** [comment]
Got it working!  This script
```
from CoolProp.CoolProp import PropsSI
import matplotlib.pyplot as plt, numpy as np
temp = np.linspace(100,400,1000)
x,y=[],[]
mix = 'Methane[0.5]&Ethane[0.5]'
for T in temp:
    try:
        y.append(PropsSI('D','T',T,'P', 100e3,mix))
        x.append(T)
    except BaseException as BE:
        print BE
plt.plot(x,y,'o-')
plt.axvline(PropsSI('T','Q',1,'P', 100e3,mix),dashes = [2,2]) # Dewpoint
plt.axvline(PropsSI('T','Q',0,'P', 100e3,mix),dashes = [2,2]) # Bubblepoint
plt.ylabel('D (kg/m3)')
plt.xlabel('T (K)')
plt.show()
```
now yields
![meth_](https://cloud.githubusercontent.com/assets/1859947/19631779/64b5bfb0-995d-11e6-96b9-1214a8be2f6e.png)

with no failures
