### ISSUE TITLE
Implement correlation tor thermal conductivity of methanol

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1067]

**Comment by Hans-Herbert** [comment]
Hello,
i am using the software CoolProp with much success. I have noticed, that the thermal conductivity for the fluid methanol is missing. Therefore i made the proposal to implement the model (equations) of E.A. Sykioti, M.J. Assael, M.L. Huber and R.A. Perkins (Reference Correlation of the Thermal Conductivity of Methanol from thr Tripel Point to 660 K and up to 245 MPa, J. Phys. Chem. Ref. Data 42, 043101 (2013)) in CoolProp.

I have tested that model in python. It produces axact values for the thermal conductivity.

Hans-Herbert

**Comment by ibell** [comment]
I will do so.  It should be pretty straightforward since it follows the same/similar form as other papers on thermal conductivity.

**Comment by Hans-Herbert** [comment]
Thank you very much.

**Comment by ibell** [comment]
I might implement this today, we shall see.
