### ISSUE TITLE
Air: ValueError: Inputs in Brent do not bracket the root

### ISSUE THREAD

**Issue by jjfPCSI1** [CoolProp/CoolProp#107]
This instruction is working well with CoolProp4 but not with CoolProp5. Any explanation ?

<pre>
>>> from CoolProp.CoolProp import *
>>> PropsSI("D","P",6500000,"S",4894.530733,"Air")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp.pyx", line 158, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:7149)
  File "CoolProp.pyx", line 180, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:6948)
  File "CoolProp.pyx", line 145, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:6542)
ValueError: Inputs in Brent [59.749000,2001.000000] do not bracket the root.  Function values are [-157.954073,-2.999992] : PropsSI("D","P",6500000,"S",4894.530733,"Air")
</pre>

**Comment by L4student** [comment]
Dear Ian @ibell 

I am getting the same error as reported in this issue, which is invoked at the dew point calculation [=`HEOS.update(CP.PT_INPUTS, P, T)`] while computing chemical potential of methane. The `P, T` values for which it's failing are the maximum allowed pressure for methane (=`1000 MPa`) and `318 K`. This `1000 MPa` pressure value is estimated using 'P_max' string input in `PropsSI` at the same temperature. I am using the maximum allowed pressure to find the maximum allowable density of methane, which I assume will be for the maximum allowed pressure for methane (@ `1000 MPa`). If I change the gas to 'CO2' and keep the measured values to be same then I don't get this error. 

`ValueError: Inputs in Brent [4787.840987,34206.787162] do not bracket the root.  Function values are [-0.988841,-0.126030]`

I am not sure what I am doing wrong, but the only place I can think where I might be going wrong is the way I am estimating the maximum fluid density. I am trying to replicate the maximum fluid density from a 'refprop' command where it is computed as `refprop.limitx(x, htype='EOS', t=T, D=0, p=0)['Dmax']`. I didn't find an analogous command in `CoolProp` to estimate the maximum fluid density, so I am using the following commands to find maximum fluid density:

```
#------ maximum pressure allowed for CH4
p_max = CP.CoolProp.PropsSI('P_max', 'CH4')
    
#------ calculate maximum density
d = CP.CoolProp.PropsSI('Dmolar', 'T', 318, 'P', p_max, 'CH4')
```

 I would appreciate your help in figuring out if I am doing something wrong.
