### ISSUE TITLE
Expose chemical potential to python interface

### ISSUE THREAD

**Issue by davideziviani** [CoolProp/CoolProp#1073]
Hey, I think this is similar to #1072 . I was trying to retrieve the chemical potential but I bumped into AttributeError inside AbstractState. This happens also if "REFPROP" is used instead of "HEOS"

HEOS = CoolProp.AbstractState("HEOS", "Methane&Ethane")
HEOS.set_mole_fractions([0.2,0.8])
HEOS.update(CoolProp.PQ_INPUTS, 101325, 1)
HEOS.saturated_liquid_keyed_output(CoolProp.iDmolar)
HEOS.saturated_liquid_keyed_output(CoolProp.iGmolar)
HEOS.saturated_vapor_keyed_output(CoolProp.iDmolar)
HEOS.mole_fractions_liquid()
HEOS.mole_fractions_vapor()
HEOS.chemical_potential(0)
HEOS.gibbsmass()

**Comment by ibell** [comment]
So for you, they all work except for chemical_potential?

**Comment by davideziviani** [comment]
HEOS.gibbsmass() does not work either as you pointed out. 

This works:
REFPROP = CoolProp.AbstractState('REFPROP','water&ammonia')
REFPROP.keyed_output(CoolProp.iGmass)
REFPROP.keyed_output(CoolProp.iGmolar)

**Comment by ibell** [comment]
But not with the HEOS backend, though, right?

**Comment by davideziviani** [comment]
Just checked with HEOS backend:

HEOS.gibbsmass()   does not work
HEOS.keyed_output(CoolProp.iGmass) works

**Comment by ibell** [comment]
And you get a real value?  In my testing both seemed broken, I always got
nan

**Comment by davideziviani** [comment]
I get -59587.029992 J/kg

**Comment by davideziviani** [comment]
I am running still CP 5.1.3dev

**Comment by ibell** [comment]
Okie dokie, I'll fix these issues in the next few days...

**Comment by davideziviani** [comment]
ok thanks! I will go ahead and check if somethings else wrong. Enjoy over there!

**Comment by L4student** [comment]
Hello. Can you please describe what is the command/syntax to calculate chemical potential in python interface of CoolProp?

**Comment by davideziviani** [comment]
Hello! It is quite straight forward by using the low-level interface. You can find the documentation [here](http://www.coolprop.org/_static/doxygen/html/class_cool_prop_1_1_abstract_state.html)

Code example:
```python
import CoolProp 
# A mixture of methane and ethane
HEOS = CoolProp.AbstractState("HEOS", "Methane&Ethane")
# Set the mole fractions of the mixture
HEOS.set_mole_fractions([0.2,0.8])
# Do the dewpoint calculation
HEOS.update(CoolProp.PQ_INPUTS, 101325, 1)
mu_Methane =  HEOS.chemical_potential(0)
mu_Ethane =  HEOS.chemical_potential(1)
```

**Comment by L4student** [comment]
Thank you very much @davideziviani .
Before asking here, I searched and came across that link, but didn't understand how to call that in python.

**Comment by ibell** [comment]
Thanks @davideziviani !

@L4student : It is good to document what you *have* tried because then people might be more inclined to help you if you have clearly made an effort.

**Comment by L4student** [comment]
@ibell : Thanks for your advice. I will keep that in mind from next time.

**Comment by L4student** [comment]
Hello guys: 
I was not sure about the `PQ_inputs` in the code, so I came across [this link](http://www.coolprop.org/_static/doxygen/html/namespace_cool_prop.html#a58e7d98861406dedb48e07f551a61efb) that describes them. I am not exactly sure what the parameter `Q` stands for. The given link says it's a `Molar quality`, which I assume meant to say `Molar quantity`. However, even then, I searched for this term and it seems like google's top recommendation suggests it's molecular weight as shown below.

> Molar quantity is often convenient to express an extensive quantity (e.g., volume, enthalpy, heat capacity, etc.) as the actual value divided by the amount of substance (number of moles). The resulting quantity is called molar volume, molar enthalpy, etc.

The value considered for `Q` in the code is `1`, which could possibly be the number of moles, but it's not clear based on above definition and also because there are two components in the mixture.

**Comment by ibell** [comment]
The vapor quality is the ratio of the number of moles in the vapor phase to the total number of moles in a mixture (at VLE, for instance).  Therefore, the saturated liquid has a vapor quality of 0, and the saturated vapor has a vapor quality of 1.

**Comment by L4student** [comment]
Thank you, @ibell .
