### ISSUE TITLE
SMath wrapper: CoolProp_get_parameter_information_string always returns long description

### ISSUE THREAD

**Issue by mikekaganski** [CoolProp/CoolProp#1077]
I have upgraded to 6.0.0, and now my SMath wrapper function CoolProp_get_parameter_information_string(Param,Output) gives always only long description.
Before, it used to give the result dependent on Output string: "full", "short", "IO" and "unit".

I do have a SMath file with saved calculations showing that it was different at one point.
[CoolProp_demo.sm.zip](https://github.com/CoolProp/CoolProp/files/274540/CoolProp_demo.sm.zip)

The history for src/CoolPropLib.cpp tells that commit 763d4ceb11da081df6653dec29d54e4ba1ff2cc2 changed this, so that Output isn't input/output anymore, but only output. Before, the value passed through it, was used as column key.

Coudn't that be reverted, and #974 be corrected in a different way?

**Comment by ibell** [comment]
@jowr Please make a PR reverting this change so that this function is able to return any of the desired parameters
