### ISSUE TITLE
CoolProp Online down

### ISSUE THREAD

**Issue by bilderbuchi** [CoolProp/CoolProp#1078]
Coolprop Online at http://ibell.pythonanywhere.com/ has been "temporarily down for maintenance" for quite some time (the [page in the docs](http://coolprop.sourceforge.net/online/index.html) asks users to report any problems).

**Comment by ibell** [comment]
Thanks for the report.  I'll see about firing it back up.

On Fri, May 20, 2016 at 2:46 PM, Christoph Buchner <notifications@github.com

**Comment by ibell** [comment]
I haven't forgotten, but I cannot for the life of me get this working...

**Comment by floweh** [comment]
Too bad :/ Could you update the info on the webpage please?

**Comment by ibell** [comment]
How to update web2py safely: https://www.pythonanywhere.com/forums/topic/881/#id_post_6624

**Comment by ibell** [comment]
See also: http://web2py.com/books/default/chapter/29/13#Deploying-on-PythonAnywhere

**Comment by ibell** [comment]
http://www.ridgesolutions.ie/index.php/2013/02/20/web2py-make-your-app-the-default-web-application/

**Comment by ibell** [comment]
And we're back up (finally)!

**Comment by ibell** [comment]
Closed by c938bb378f08e1c83d68b8090aab2eb9033933ae

**Comment by ibell** [comment]
closed by c938bb378f08e1c83d68b8090aab2eb9033933ae

**Comment by bilderbuchi** [comment]
Thanks!

**Comment by bilderbuchi** [comment]
@ibell Coolprop online seems to be down again - I get "Internal error" when visiting https://ibell.pythonanywhere.com/

**Comment by ibell** [comment]
Confirmed.  Didn't know that anybody was actually using the service :)

**Comment by bilderbuchi** [comment]
It's very useful to quickly look up fluid properties at some defined point, without having to fire up a Python console and look up the proper coolprop syntax (again) 👍  
I guess every 6 months or so I am using it for just that. :-)

**Comment by ibell** [comment]
Turns out the sessions logs filled up the 2 GB capacity.  Removing them got
things going again. Also removed the errors

>
