### ISSUE TITLE
Build infrastructure down

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1082]
It looks like we have some problems with the buildbots. This might be related to the new SSH keys on the buildbot master. We should consult the local logs on the slaves.

**Comment by ibell** [comment]
Did you have to do any additional magic to get the slaves back up?

**Comment by jowr** [comment]
Nope, add the ssh keys (to make the upload work) and restart the slaves (to make them reconnect).

**Comment by ibell** [comment]
We're back up though I didn't do anything....
