### ISSUE TITLE
Mixture with R1234ze

### ISSUE THREAD

**Issue by dizzux** [CoolProp/CoolProp#1083]
Hi,

I want to do a mixture with R1234ze, Is it necessary to have REFPROP
I work with Excel . 
My error message is : 
Initialize failed for backend: "HEOS", fluid: "R32&R125&R134a&R1234yf&R1234ze" fractions "[ 0.2600000000, 0.2600000000, 0.2100000000, 0.2000000000, 0.0700000000 ]"; error: key [R1234ze] was not found in string_to_index_map in JSONFluidLibrary : PropsSI("T","P",101325000,"Q",0,"HEOS::R32[0.26]&R125[0.26]&R134a[0.21]&R1234yf[0.2]&R1234ze[0.07]")

Thanks for your answers!!

**Comment by jowr** [comment]
Please have a look at the docs: http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids 

You have to decide whether you want R1234ze(E) or R1234ze(Z). For mixtures, please also read http://www.coolprop.org/fluid_properties/Mixtures.html , which is especially useful for fluids with unknown binary interaction parameters.

**Comment by ibell** [comment]
@jowr  is right, you need to specify the correct isomer, either R1234ze(E) or R1234ze(Z).  Yes, we only have a few binaries with R1234ze isomers, due to a lack of experimental data.
