### ISSUE TITLE
Acentric factor for n-dodecane

### ISSUE THREAD

**Issue by awehrfritz** [CoolProp/CoolProp#1084]
The value for the acentric factor of n-dodecane is 0.17033484 in CoolProp. I'm wondering if there is a reference for this value. The NIST database [1] reports 0.574.

I used this python code to obtain the value in CoolProp:
`import CoolProp as CP`
`nC12H26 = CP.AbstractState('HEOS', 'n-Dodecane')`
`print("Acentric factor [-]: %.8g" % (nC12H26.acentric_factor()))`

[1] http://webbook.nist.gov/cgi/fluid.cgi?P=0.1&TLow=300&THigh=600&TInc=1&Applet=on&Digits=5&ID=C112403&Action=Load&Type=IsoBar&TUnit=K&PUnit=MPa&DUnit=mol%2Fl&HUnit=kJ%2Fmol&WUnit=m%2Fs&VisUnit=uPa*s&STUnit=N%2Fm&RefState=DEF

**Comment by ibell** [comment]
In this case, the NIST Chemistry Webbook is incorrect.  I will follow up with the relevant people tomorrow.  I checked all the other fluids in CoolProp, and the acentric factors agree with the relevant EOS to within 1%.

You can quickly check yourself.  The acentric factor is defined by: https://en.wikipedia.org/wiki/Acentric_factor

And a python script to check all the fluids in CoolProp is:
```
import math,CoolProp
CP = CoolProp.CoolProp

for fluid in CoolProp.__fluids__:
    Tc = CP.PropsSI('Tcrit',fluid)
    Tt = CP.PropsSI('Ttriple',fluid)
    pc = CP.PropsSI('pcrit',fluid)
    acentric = CP.PropsSI('acentric',fluid)
    if 0.7*Tc > Tt:
        p = CP.PropsSI('P','T',0.7*Tc,'Q',0,fluid)
        acentric_p = -math.log10(p/pc)-1
        if abs(acentric/acentric_p -1) > 0.001:
            print fluid, acentric, acentric_p
```

**Comment by awehrfritz** [comment]
You script (using the high-level interface) actually shows that the acentric factor for `n-Dodecane` is correct and agrees with the NIST value (0.574).
That still leaves the question where the value obtained via the low-level interface comes from.

Here is a slightly modified version of your script that also prints the acentric factors obtained from the low-level interface:

```python
import CoolProp as CP
import math

for fluid in CP.__fluids__:
    AS = CP.AbstractState('HEOS', fluid)

    Tc = CP.CoolProp.PropsSI('Tcrit', fluid)
    Tt = CP.CoolProp.PropsSI('Ttriple', fluid)
    pc = CP.CoolProp.PropsSI('pcrit', fluid)
    acentric = CP.CoolProp.PropsSI('acentric', fluid)
    acentric_AS = AS.acentric_factor()
    if 0.7*Tc > Tt:
        p = CP.CoolProp.PropsSI('P','T',0.7*Tc,'Q',0,fluid)
        acentric_p = -math.log10(p/pc)-1
        if (abs(acentric/acentric_p - 1) > 0.001) or \
            (abs(acentric/acentric_AS - 1) > 0.001):
            print '%s:' % fluid
            print '  %f' % acentric
            print '  %f' % acentric_p
            print '  %f' % acentric_AS
```

**Comment by ibell** [comment]
Was just a typo in the end.  Should be fixed now.
