### ISSUE TITLE
Release tags in the git repository?

### ISSUE THREAD

**Issue by awehrfritz** [CoolProp/CoolProp#1085]
It appears that CoolProp 6.0.0 and even 6.0.1 has been released (judging by the binary packages on http://www.coolprop.dreamhosters.com/binaries/Python/ and the version numbers in the source files).

However, the respective tags in the git repositories are missing. I would appreciate if you could add them.

Thanks!

**Comment by jowr** [comment]
Thanks for the heads up. We  normally tag the versions and I am sure that we can also do so for 6.0.0. Please note that you are referring to the development binaries. You should *not* use that server to get the Python files, the builds get updated each time we change the code and there is no guarantee that the code stable. Please use PyPI and pip to install CoolProp for Python.

**Comment by awehrfritz** [comment]
Thanks for the quick response.

I'm building CoolProp from source (as a shared library) and hence have been using git to get the source code. I like to use released versions, but for the latest two releases the git tags are missing. So currently, I'm resorting to git master to get the features from v6.0.

**Comment by jowr** [comment]
There is only one tag missing and that is v6.0. The master branch has already moved to v6.0.1, but that has not been released yet.
In Python, you can get the git revision of the currently installed version of CoolProp:
```Python
import CoolProp
print(CoolProp.__version__)
print(CoolProp.__gitrevision__)
```
This yields `u'6.0.0'` and `u'df13df7756aa9352c56ef6f8d631365be590533c'` for the latest binaries on PyPI. Please use that revision until I have tagged the sources properly.

**Comment by jowr** [comment]
By the way, you can also checkout the release branch...

**Comment by jowr** [comment]
I tagged the repo.

**Comment by awehrfritz** [comment]
Thanks for resolving this issue so quickly!

And thanks for the hint regarding the release branch.
