### ISSUE TITLE
First partial derivative

### ISSUE THREAD

**Issue by adexcoca987** [CoolProp/CoolProp#1088]
Hi,

In the current version of coolprop, is the first partial derivative functional for the following thermodynamics properties: Viscosity, conductivity and Prandtel ? I tried with high level interface using the following input handle but didn't work:

dv_fh3=CoolProp.PropsSI('d(V)/d(H)|P','P',p_evap,'H',h_evpf(3),'Ethanol');
dK_fh3=CoolProp.PropsSI('d(L)/d(H)|P','P',p_evap,'H',h_evpf(3),'Ethanol');
dPr_fh3=CoolProp.PropsSI('d(PRANDTL)/d(H)|P','P',p_evap,'H',h_evpf(3),'Ethanol');

The following error poops up:

Warning: input to get_dT_drho[viscosity] is invalid 
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(315,varargin{:});
 
Thank you,

**Comment by ibell** [comment]
Correct, partial derivatives of transport properties are not available, you
will have to evaluate them numerically.  You can only use this method to
evaluate thermodynamic derivatives.

**Comment by adexcoca987** [comment]
Thank you. Do you have any suggestion for numerical evaluation?

**Comment by ibell** [comment]
https://en.wikipedia.org/wiki/Finite_difference :)
