### ISSUE TITLE
Some files are missed in 6.0.0 source zip on sourceforge

### ISSUE THREAD

**Issue by ChenYuChih** [CoolProp/CoolProp#1089]
Hello,

Recently I tried to compile the latest release(6.0.0) of coolprop. But I found that some needed files, for example "mixture_departure_functions_JSON.h" & "mixture_binary_pairs_JSON.h", are missed. I went back to check previous version(5.1.2) and those files could be searched. Could they be included in next release? Thank you!

Best Regards,
ChenYuChih

**Comment by ibell** [comment]
Good point.  I will fix that, not sure what happened there, probably
manifest got messed up...

**Comment by ibell** [comment]
I see them in the file here: http://www.coolprop.dreamhosters.com/binaries/source/

What file exactly are you referring to?

**Comment by ChenYuChih** [comment]
I  download the source zip file from sourceforge

https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/source/CoolProp_sources.zip/download

Are they not the same?

**Comment by ChenYuChih** [comment]
Well, I downloaded the file you provided and can compile it without any error message, thanks a lot! 

But it's really different from the one on sourceforge, why?

Best Regards,
ChenYuChih

**Comment by jowr** [comment]
There are two things here: 
 - The sources in the zip on SourceForge are v5.1.3dev, not 6.0.0
 - The default download still points to v5.1.1

**Comment by jowr** [comment]
The logs of the release script tell us that the header generation failed for v6.0.0, which aborts the processing and skips the upload of a new zip file.

**Comment by ChenYuChih** [comment]
Got it. Thanks for reply.

ChenYuChih

**Comment by jowr** [comment]
Could you please check if the new file has all the files you need? 
https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/source/

**Comment by ChenYuChih** [comment]
Well,
https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/source/
still is not the same as
http://www.coolprop.dreamhosters.com/binaries/source/
Seems some paths are changed?

And now the sourceforge one shows lots of "undefined reference" error while linking(compiling no problem).

The dreamhosters one is good. No errors at all

Please check if there's something wrong again.

Thanks,
ChenYuChih

**Comment by jowr** [comment]
Sorry, but you have to be a little more specific. The file works for me and that is why I asked you to confirm it. 

Please clear your browser cache, download the file and try again. BTW, which wrapper are you trying to build? I only compiled the static library and that seems to be all fine. I you still have problems, it would be nice if you could share some more details with me.

**Comment by ChenYuChih** [comment]
OK, after comparison, I found that https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/source/
has some more extra files.(CPfilepaths, CPnumerics, CPstrings, CubicBackend, GeneralizedCubic & CubicsLibrary) 

Is this file v6.0.1 trunk?

I added them into my compiling list and everything goes fine.

Thanks jowr!

Best Regards,
ChenYuChih

**Comment by jowr** [comment]
Hi, this should be v6.0.0, I generated the package from a fresh git clone. I am happy to hear that it works for you, please reopen this issue in case there are more problems.
