### ISSUE TITLE
C# SWIG based wrapper missing namespace

### ISSUE THREAD

**Issue by sepptruetsch** [CoolProp/CoolProp#1090]
Could it be possible to generate the .cs files with proper namespace like CoolProp? SWIG has an option to define this by using the -namespace flag.

Would greatly appreciate this as the current state clutters the global namespace and makes using the CoolProp library unnecessary complicated as IntelliSense can't help.

Thanks!

**Comment by jowr** [comment]
Would you mind making the changes and file a pull request? 
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/what-is-a-good-git-workflow/

**Comment by ibell** [comment]
Actually, this was already available, but not documented, so I added the documentation (see above link)
