### ISSUE TITLE
A problem with set_reference_stateD()

### ISSUE THREAD

**Issue by mikekaganski** [CoolProp/CoolProp#1091]
I don't seem to be able to use set_reference_stateD().
Doing something like
set_reference_stateD("Propane",273.15,45.4445335538396,200000,-6.6808880966272)
returns true, but following calculations give unchanged result (depending on set_reference_stateS() called previously).
Calling set_reference_stateS("Propane", "DEF") before and set_reference_stateS("Propane", "RESET") after only gives DEF reference.

Dependence of the calculations on set_reference_stateS() proves that following calculations do pick up changed refstate.

Looking into src/CoolProp.cpp shows some immediate description inconsistency (that still does not explain the failure): both include/CoolProp.h and src/CoolProp.cpp contain comments stating that h0 and s0 params are molar-specific, but the code shows that they are treated as mass-specific. Still, compensating for that gives nothing (actually, the code I cited above is J/kg and J/kg/K). The names h0 and s0 themselves imply mass. Also, hardcoded gas constant value 8.314472 is used, unlike HEOS.gas_constant() used in set_reference_stateS (that is defined in modules as 8.3144621).

Furhter, comparing set_reference_stateS and set_reference_stateD, I see that set_reference_stateS calls set_fluid_enthalpy_entropy_offset(), that in turn calls EOS().alpha0.EnthalpyEntropyOffset.set() (just like set_reference_stateD does), but also makes some further processing. So, I tried to use set_reference_stateS("Propane", "RESET") after the set_reference_stateD(), to force library to do all the necessary post-processing. But to no result.

It seems that set_reference_stateD works with some other object than set_reference_stateS, maybe because set_reference_stateD gets the object using CoolProp::HelmholtzEOSMixtureBackend HEOS(std::vector<std::string>(1, Ref)), while set_fluid_enthalpy_entropy_offset uses string_to_index_map.find(fluid) and fluid_map.find().

Do I do a mistake, or is it some bug?

**Comment by mikekaganski** [comment]
By the way, it seems that the comment in include/CoolProp.h about "RESET" Reference State name is misleading. It states:
""RESET"         | Remove the offset"
but its handling in set_reference_stateS() doesn't remove any offset, just calls
set_fluid_enthalpy_entropy_offset(fluid, 0, 0, "RESET");
and set_fluid_enthalpy_entropy_offset calls EOS().alpha0.EnthalpyEntropyOffset.set(0,0,"RESET"). There, if enabled == false, then these zeros are set, and enable becomes true, otherwise these zeroes are "added" to current values, and enabled is set to true again. So, "RESET" seems more like "assure that current refstate is active (if for some strange reason something went wrong)".

**Comment by ibell** [comment]
Interesting on all fronts.  I will investigate.

**Comment by ibell** [comment]
@mikekaganski there were a few bugs in there, and now all inputs are molar for consistency.  Hope this resolves all your issues.  Reopen if not...
