### ISSUE TITLE
BORLAND BUILDER C++ link coolprop

### ISSUE THREAD

**Issue by vsotofrances** [CoolProp/CoolProp#1092]
Linking the coolprop library with Borland Builder. SOLVED.
I have been trying to use CoolProp with an upgraded version of a refrigeration software of our own.
It was compiled in Borland Builder. I finally found one solution.

STEPS:
* STEP(1)
From SourceForge I downloaded the compiler version of the library ( shared library).
Windows 32bits **__stdcall**
https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/shared_library/Windows/32bit__stdcall/
Now we have **CoolProp.dll** with us.
https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/shared_library/Windows
Now we have **CoolPropLib.h** (to make C like calls)

* STEP(2)
Follow the instructions from:
[1] http://bcbjournal.org/articles/vol4/0012/Using_Visual_C_DLLs_with_CBuilder.htm
(note IMPDEF, and IMPLIB are Borland utilities)
IMPDEF my.def CoolProp.dll
Change the names in my.def as [1] indicates to get: 
[my.def](https://github.com/CoolProp/CoolProp/files/295829/my.txt)

* STEP(3)
Then create a lib file as follows:
IMPLIB my.lib my.def
to get 
[my.lib](https://github.com/CoolProp/CoolProp/files/295832/my.lib.txt)

* STEP(4)
In the Borland Project add to the project my.lib ( this will load the CoolProp.dll at starting your program).

* STEP(5)
Modify CoolPropLib.h in line 41 as follows:
```
/*    #      define EXPORT_CODE extern "C" __declspec(dllexport) */
    \#      define EXPORT_CODE extern "C" __declspec(dllimport)
```

Thats all. TEST IT.

Use this simple main program to test it:
```//---------------------------------------------------------------------------

#pragma hdrstop
#define COOLPROP_LIB
#include "CoolPropLib.h"
#include <iostream>
//---------------------------------------------------------------------------

#pragma argsused
int main(int argc, char* argv[])
{
    std::cout << PropsSI("T","P",101325,"Q",0,"Water") << std::endl;
    return 1;
}
//---------------------------------------------------------------------------```

**Comment by ibell** [comment]
Could you please copy-paste your snippet here?  I will show you how to fix
it and add some documentation for other users to show how to call the
shared library.

**Comment by vsotofrances** [comment]
Ian I am Victor. I wrote you an email yesterday. I was trying to explain how it worked for me with Borland and I succeed in linking and using CoolProp.

Sorry, by "snippet " what do you mean.

**Comment by ibell** [comment]
Stupid question, but why Borland?  There are so many nice free C++ development tools out there...

**Comment by ibell** [comment]
Some more comments:

You shouldn't modify CoolPropLib.h, you should instead make your snippet look like:
```
#pragma hdrstop
#define EXPORT_CODE extern "C" __declspec(dllimport)
#define CONVENTION __stdcall
#include "CoolPropLib.h"
#include <iostream>
//---------------------------------------------------------------------------

#pragma argsused
int main(int argc, char* argv[])
{
    std::cout << PropsSI("T","P",101325,"Q",0,"Water") << std::endl;
    return 1;
}
```

**Comment by vsotofrances** [comment]
It was because we have an * old*  development made in Borland and we want 
to upgrade it ....just for maintenance purposes.

The software is going to be downloaded free of charge,....when we have 
ready the download web site I will tell you.

 I will include of course  the license of CoolProp.

The site is going to be managed by Atecyr, a non-profit association of air 
conditioning and refrigeration in Spain.

Now we are migrating to open and libre development C++ tools and 
refactoring all our infrastructure. 
We are only three people and teachers at UPV so things take time.






El viernes, 3 de junio de 2016 5:28:06 (CEST), Ian Bell 
<notifications@github.com> escribió:
> Stupid question, but why Borland?  There are so many nice free 
> C++ development tools out there...
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/CoolProp/CoolProp/issues/1092#issuecomment-223482348


-- 
Enviado con Dekko desde mi dispositivo Ubuntu

**Comment by ibell** [comment]
Makes sense to me!  

I will try to find a nice way to update the docs for C/C++ calling the shared library.  I don't have Borland, so I can't check that part, but I can check calling a 32-bit DLL from C
