### ISSUE TITLE
CoolProp Speed MATLAB vs Python

### ISSUE THREAD

**Issue by khoopes** [CoolProp/CoolProp#1095]
I am trying to speed up my matlab code by implementing the low level interface to coolprop. With how the analysis code I am writing works, I can only evaluate a state at a time, I cannot pass a list of states to coolprop to be evaluated and get a list of properties back.

I have modified the low level code example here: http://www.coolprop.org/coolprop/wrappers/MATLAB/ to switch from 10000 points at once to a for loop to loop over the 10000 points

	%% Calling low-level interface from MATLAB through shared library (DLL)
	%%
	%% Originally developed by Edo Macchi, modified by Ian Bell
	%%
	%% December 2015
	clear
	clc

	path_to_lib = '/work/CoolProp/libs/shared'; %specify path to coolprop shared library
	path_to_include= '/work/CoolProp/include'; %specify path to coolprop's include folder

	% Loading shared library
	if ~libisloaded('coolprop') %checking whether library is already loaded
		addpath(path_to_lib)
		addpath(path_to_include)
		libname = 'libCoolProp' % OSX and linux
		if ispc
			libname = 'CoolProp'
		end
		loadlibrary(libname,'CoolPropLib.h','includepath',path_to_include,'alias','coolprop'); % loading library with alias coolprop
		disp('loaded CoolProp shared library.')
		disp('loaded these functions: ')
		libfunctions coolprop
	end

	buffer_size = 1000;
	ierr = 0;
	b = (1:1:buffer_size);
	herr= char(b);

	%Selecting backend and fluid
	backend = 'HEOS';
	fluid = 'co2';
	[handle, sh] = calllib('coolprop','AbstractState_factory',backend,fluid,ierr,herr,buffer_size);

	num_points = 10000;
	P_range = linspace(25e6,25e6,num_points)';
	T_range = linspace(800,800,num_points);

	tic;
	for j = 1:num_points
		
		length=1;
		
		input1 = P_range(j);
		input2 = T_range(j);
		[input_pair,sip] = calllib('coolprop','get_input_pair_index','PT_INPUTS');

		
		%Creating input and output pointers
		input1Ptr = libpointer('doublePtr',input1);
		input2Ptr = libpointer('doublePtr',input2);
		TPtr = libpointer('doublePtr',zeros(length,1));
		pPtr = libpointer('doublePtr',zeros(length,1));
		rhomolarPtr = libpointer('doublePtr',zeros(length,1));
		hmolarPtr = libpointer('doublePtr',zeros(length,1));
		smolarPtr = libpointer('doublePtr',zeros(length,1));
		
		calllib('coolprop','AbstractState_update_and_common_out',handle,input_pair,input1Ptr,input2Ptr,length,TPtr,pPtr,rhomolarPtr,hmolarPtr,smolarPtr,ierr,herr,buffer_size);
		
		
		
		T=get(TPtr,'Value');
		p=get(pPtr,'Value');
		rhomolar=get(rhomolarPtr,'Value');
		hmolar=get(hmolarPtr,'Value');
		smolar=get(smolarPtr,'Value');
	end
	dt = toc;
	fprintf('CoolProp Lowlevel: %d us/call\n', (dt*1e6/num_points));

	tic
	for j = 1:num_points
	 [T,P,D,h,s] = refpropm('TPDHS','T',T_range(j),'P',P_range(j)/1000,'co2');
	end
	dt = toc;

	fprintf('Refpropm: %d us/call\n', (dt*1e6/num_points));
	return

That returns: 
CoolProp Lowlevel: 4.887257e+02 us/call
Refpropm: 2.781679e+02 us/call

I am confused by this since when I do a similar test in Python, it is much faster:

	import CoolProp
	import time
	import CoolProp.CoolProp as CP

	N = 10000

	t0 = time.time()
	AS = CoolProp.AbstractState('TTSE&HEOS','CO2')
	for k in range(0,N):
		AS.update(CoolProp.PT_INPUTS, 25e6, 800)
		AS.rhomolar()
		AS.hmolar()
		AS.smolar()
		AS.T()
	t1 = time.time()

	print 'Low Level CoolProp with table Executed in %g [us/call]' % ((t1-t0)/N*1e6)

	t0 = time.time()
	AS = CoolProp.AbstractState('HEOS','CO2')
	for k in range(0,N):
		AS.update(CoolProp.PT_INPUTS, 25e6, 800)
		AS.rhomolar()
		AS.hmolar()
		AS.smolar()
		AS.T()
	t1 = time.time()

	print 'Low Level CoolProp Executed in %g [us/call]' % ((t1-t0)/N*1e6)

	t0 = time.time()
	AS = CoolProp.AbstractState('REFPROP','CO2')
	for k in range(0,N):
		AS.update(CoolProp.PT_INPUTS, 25e6, 800)
		AS.rhomolar()
		AS.hmolar()
		AS.smolar()
		AS.T()
	t1 = time.time()

	print 'Low Level REFPROP Executed in %g [us/call]' % ((t1-t0)/N*1e6)
which returns

Low Level CoolProp with table Executed in 62 [us/call]
Low Level CoolProp Executed in 21.9 [us/call]
Low Level REFPROP Executed in 16.3 [us/call]

Am I implementing the low level matlab script incorrectly, or is the python low level interface just that much faster?

Thanks,

**Comment by JonWel** [comment]
I think you can make the matlab code a bit faster by putting part of it out of the loop:
```matlab
    length=1;
    input1 = P_range(j);
    input2 = T_range(j);
    %Creating input and output pointers
    input1Ptr = libpointer('doublePtr',input1);
    input2Ptr = libpointer('doublePtr',input2);
    TPtr = libpointer('doublePtr',zeros(length,1));
    pPtr = libpointer('doublePtr',zeros(length,1));
    rhomolarPtr = libpointer('doublePtr',zeros(length,1));
    hmolarPtr = libpointer('doublePtr',zeros(length,1));
    smolarPtr = libpointer('doublePtr',zeros(length,1));
```
Some values depends on `i` and `j`, but they could either be set by vectorial operations (if possible) before the loop, or in an other loop (you want to time CollProp, not Matlab, even if this could be interesting to also have the time of the overhead of the usage trough matlab).

After that, I would try to wrap the commands in a function. This may help matlab's compiler to optimise the commands inside the function a bit better (usually, you have a first call of the function that is slow as compiling, and the second that is faster as already compiled).
Or even better, to wrap it into a mex.

I'll look into your code a bit deeper later.

**Comment by JonWel** [comment]
I see that you use the [AbstractState_update_and_common_out](https://github.com/CoolProp/CoolProp/blob/master/src/CoolPropLib.cpp#L566) function, which has already an internal for loop.

So this would definitely be faster to use that feature instead of using matlab to execute the loop.

I did not test yet as not having matlab set up for CoolProp yet, but I would try something like that (not that I did not copy the beginning and the end of your example, but they are still needed of course)

```matlab
num_points = 10000;
P_range = linspace(25e6,25e6,num_points)';
T_range = linspace(800,800,num_points);
tic;
[input_pair,sip] = calllib('coolprop','get_input_pair_index','PT_INPUTS');

%Creating input and output pointers
input1Ptr = libpointer('doublePtr',P_range);
input2Ptr = libpointer('doublePtr',T_range);
TPtr = libpointer('doublePtr',zeros(num_points,1));
pPtr = libpointer('doublePtr',zeros(num_points,1));
rhomolarPtr = libpointer('doublePtr',zeros(num_points,1));
hmolarPtr = libpointer('doublePtr',zeros(num_points,1));
smolarPtr = libpointer('doublePtr',zeros(num_points,1));
preProcessingTime = toc;
tic;
calllib('coolprop','AbstractState_update_and_common_out',handle,input_pair,input1Ptr,input2Ptr,length,TPtr,pPtr,rhomolarPtr,hmolarPtr,smolarPtr,ierr,herr,buffer_size);
dt = toc;
tic;
T=get(TPtr,'Value');
p=get(pPtr,'Value');
rhomolar=get(rhomolarPtr,'Value');
hmolar=get(hmolarPtr,'Value');
smolar=get(smolarPtr,'Value');
postProcessingTime = toc;
```
I think something similar to this should give way faster results (if it works, didn't checked yet)

**Comment by ibell** [comment]
@JonWel is right, you should pass arrays of inputs to these methods.  Should be faster than iterating.

**Comment by ibell** [comment]
And @JonWel is correct that retrieval of the appropriate constants should be done outside your call to the function.

**Comment by khoopes** [comment]
I agree that passing arrays would be faster, but my application requires that I get fluid properties one at a time. Essentially I am dividing a section of tubing into many elements, each downstream element is dependent on what happens upstream so my only thought is to run through the pipe element by element from inlet to outlet one element at a time. 

I created a function wrapper that moves more of the initialization out of the for loop. There are two functions. CP_lowlevelstartup.m and CPprop_PT.m here they are

	function CPstate = CP_lowLevelStartup(backend,fluid)
	if ~libisloaded('coolprop') %checking whether library is already loaded
		path_to_lib = '/work/CoolProp/libs/shared'; %specify path to coolprop shared library
		path_to_include= '/work/CoolProp/include'; %specify path to coolprop's include folder
		addpath(path_to_lib)
		addpath(path_to_include)
		libname = 'CoolProp';
		loadlibrary(libname,'CoolPropLib.h','includepath',path_to_include,'alias','coolprop'); % loading library with alias coolprop
		disp('loaded CoolProp shared library.')
		disp('loaded these functions: ')
		libfunctions coolprop
	end

	buffer_size = 1000;
	ierr = 0;
	b = (1:1:buffer_size);
	herr= char(b);

	%Selecting backend and fluid
	[handle, ~] = calllib('coolprop','AbstractState_factory',backend,fluid,ierr,herr,buffer_size);


	%select input pair
	[CPstate.input_pair,~] = calllib('coolprop','get_input_pair_index','PT_INPUTS');

	%create input pointers
	CPstate.input1Ptr = libpointer('doublePtr',0);
	CPstate.input2Ptr = libpointer('doublePtr',0);

	%create output
	outputs=zeros(5,1);

	%Choosing parameters to compute
	[outputs(1,1), ~] = calllib('coolprop','get_param_index','Dmass');
	[outputs(2,1), ~] = calllib('coolprop','get_param_index','Hmass');
	[outputs(3,1), ~] = calllib('coolprop','get_param_index','Prandtl');
	[outputs(4,1), ~] = calllib('coolprop','get_param_index','conductivity');
	[outputs(5,1), ~] = calllib('coolprop','get_param_index','viscosity');

	%Creating ouput pointers
	CPstate.out1Ptr = libpointer('doublePtr',zeros(1,1));
	CPstate.out2Ptr = libpointer('doublePtr',zeros(1,1));
	CPstate.out3Ptr = libpointer('doublePtr',zeros(1,1));
	CPstate.out4Ptr = libpointer('doublePtr',zeros(1,1));
	CPstate.out5Ptr = libpointer('doublePtr',zeros(1,1));

	CPstate.outputs = outputs;

	CPstate.handle = handle;
	CPstate.ierr = ierr;
	CPstate.b = b;
	CPstate.herr = herr;
	CPstate.buffer_size = buffer_size;

	end

and here is the other one

	function [D,h,Pr,k,mu] = CPprop_PT(CPstate,P,T)

	handle = CPstate.handle;
	ierr = CPstate.ierr;
	%b = CPstate.b;
	herr = CPstate.herr;
	buffer_size = CPstate.buffer_size;

	set(CPstate.input1Ptr,'Value',P);
	set(CPstate.input2Ptr,'Value',T);

	calllib('coolprop','AbstractState_update_and_5_out',handle,CPstate.input_pair,CPstate.input1Ptr,CPstate.input2Ptr,1,CPstate.outputs,CPstate.out1Ptr,CPstate.out2Ptr,CPstate.out3Ptr,CPstate.out4Ptr,CPstate.out5Ptr,ierr,herr,buffer_size);

	D = get(CPstate.out1Ptr,'Value');
	h = get(CPstate.out2Ptr,'Value');
	Pr = get(CPstate.out3Ptr,'Value');
	k = get(CPstate.out4Ptr,'Value');
	mu =get(CPstate.out5Ptr,'Value');

	end


And here is a test script to run it against refprop.

	clear
	clc
	close all

	CPstate = CP_lowLevelStartup('HEOS','co2');

	num_points = 10000;

	P = linspace(23.99e6,23.99e6,num_points);
	T = linspace(convert.C2K(581)-50,convert.C2K(581),num_points);

	tic
	for j=1:length(P)

		[D,h,Pr,k,mu] = CPprop_PT(CPstate,P(j),T(j));
		Dsave(j)  =D;
		hsave(j) = h;
		Prsave(j) = Pr;
		ksave(j) = k;
		musave(j) = mu;
		

			
	end
	dt = toc;
	fprintf('Coolprop Low Level: %g [us/call]\n',dt/num_points*1e6)

	tic
	for j=1:length(P)
		[D,h,Pr,k,mu] = refpropm('DH^LV','T',T(j),'P',P(j)/1000,'co2');
		DsaveR(j)  =D;
		hsaveR(j) = h;
		PrsaveR(j) = Pr;
		ksaveR(j) = k;
		musaveR(j) = mu;
	end
	dt =  toc;
	fprintf('refprop.m: %g [us/call]\n',dt/num_points*1e6)

	plot(T,Dsave,'ro');
	hold on
	plot(T,DsaveR,'kd');
	xlabel('Temperature [K]');
	ylabel('Density [kg/m^3');
	grid on

When I run this I get,

Coolprop Low Level: 308.756 [us/call]
refprop.m: 307.336 [us/call]

Interesting that they are so close in execution time. Both are still a lot slower than Python though. I guess what I am getting at is for my application where I have to do one property lookup at a time, is there anyway to shave more time off matlab or should I switch to python to get the speed boost?

Thanks,

**Comment by JonWel** [comment]
@khoopes When I test your first code on my computer, I get:
CoolProp Lowlevel: 3.469534e+02 us/call

When I test the one I suggested, I get:
CoolProp Lowlevel: 3.047318e+01 us/call

Which is better and closer to your results in Python.

However, I understand that you need the loop on Matlab's side as the computations you will need will not be known since the beginning and depend on the precedent ones computed.

A remark on this:
```matlab
for j=1:length(P)
    [D,h,Pr,k,mu] = CPprop_PT(CPstate,P(j),T(j));
    Dsave(j)  =D;
    hsave(j) = h;
    Prsave(j) = Pr;
    ksave(j) = k;
    musave(j) = mu;
end
```
I don't see any initialisation of the `save` vectors. This is usually a bad practice, as, not knowing the final size since the beginning, it will resize the vector at each iterations, thus consuming a lot of the time.
Maybe you could try your code again, but with pre initialised arrays.

I'm going to make a test with Julia (syntax is a bit closer to the Matlab's one), theses loop seems quite slow to me.

**Comment by JonWel** [comment]
In Julia, when I make the loop in a script, I have 262.22113429999996 µs/call
But If I make it in a function, I have 87.9850717 µs/call
Which is still higher than the python example you had (but maybe this is not that quick on my computer either).

Here is the code I made in Julia to test:
```Julia
using CoolProp

function CPprop_PT(handle::Int,INPUTS::Int, input1::LinSpace{Float64}, input2::LinSpace{Float64}, outputs_index::AbstractArray{Int64,1},outputs::AbstractArray{Float64,2}, num_points::Int64)
  for k = 1:num_points
    AbstractState_update(handle,INPUTS, input1[k],input1[k])
    for l = 1:5
      outputs[l,k] = AbstractState_keyed_output(handle,outputs_index[l])
    end
  end
end

num_points = 10000
backend = "HEOS"
fluid = "co2"

P = linspace(23.99e6,23.99e6,num_points)
T = linspace(581-273.15-50,581-273.15,num_points)

INPUTS = get_input_pair_index("PT_INPUTS")

#Choosing parameters to compute
outputs_index=Array(Int,5);
outputs_index[1] = get_param_index("Dmass")
outputs_index[2] = get_param_index("Hmass")
outputs_index[3] = get_param_index("Prandtl")
outputs_index[4] = get_param_index("conductivity")
outputs_index[5] = get_param_index("viscosity")

outputs=Array(Float64,5,num_points);

handle = AbstractState_factory(backend,fluid)

tic()
CPprop_PT(handle,INPUTS, P, T, outputs_index,outputs, num_points)
t = toc()

println("time = ", t/num_points*1e6, " µs/call")

AbstractState_free(handle)
```
It may be faster with `AbstractState_update_and_5_out` but I did not implement it yet.

What you may try is to compile your matlab code in a mex, this allows way faster execution of loop, and would remove the overhead of the for loop you seem to experience.

**Comment by JonWel** [comment]
@khoopes  Now python tests:
```python
import time
import CoolProp
from numpy import linspace, empty

num_points = 10000

backend = "HEOS"
fluid = "co2"
P = linspace(23.99e6,23.99e6,num_points)
T = linspace(581-273.15-50,581-273.15,num_points)

outputs= empty([5,num_points])


t0 = time.time()
AS = CoolProp.AbstractState(backend ,fluid )
for k in range(0,num_points):
    AS.update(CoolProp.PT_INPUTS, P[k], T[k])
    outputs[0,k] = AS.rhomass()
    outputs[1,k] = AS.hmass()
    outputs[2,k] = AS.Prandtl()
    outputs[3,k] = AS.conductivity()
    outputs[4,k] = AS.viscosity()
t1 = time.time()

print('Low Level CoolProp Executed in %g [us/call]' % ((t1-t0)/num_points*1e6))
```
and the time:
```Python
Low Level CoolProp Executed in 85.4085 [us/call]
```

So now we have coherent results :)

The thing is that sometimes you compared with the tabular backend, and sometimes without, this makes a huge difference.

Here are numbers with tabular backends (so adding `TTSE&` to the backend):

Python:
```Python
Low Level CoolProp Executed in 3.80037 [us/call]
```
Julia:
```Julia
lapsed time: 0.096817438 seconds
time for loop = 9.681743800000001 µs/call
elapsed time: 0.093927756 seconds
time function loop = 9.3927756 µs/call
elapsed time: 0.004466488 seconds
time update and common out = 0.4466488 µs/call
elapsed time: 0.010744763 seconds
time update and 5 out = 1.0744763 µs/call
```
Matlab:
```Matlab
CoolProp for loop: 2.848689e+02 us/call
CoolProp function for loop: 2.994868e+02 us/call
CoolProp update and 5 out: 6.577930e-01 us/call
```

So, you have it:
Matlab's for loop are what takes all your time.
If you need something faster:
1: Use MEX to make the loop faster. The discussion in issue #946 may help.
2: Use Python, speed is excellent and functionalities are complete.
3: Use Julia, the syntax is similar to Matlab, and their loop are quite honest. But not all functions are there.

And don't forget to use the tabular backend when you need the best speed (with slightly lower precision)

**Comment by ibell** [comment]
Thanks @JonWel for the comprehensive study!

**Comment by khoopes** [comment]
This is great, thank you for your work on it. I think I will be moving to python, that speed increase is to great to pass up.

**Comment by ibell** [comment]
I guess we can close this issue now, right?
