### ISSUE TITLE
README.rst.txt at SourceForge is outdated

### ISSUE THREAD

**Issue by mikekaganski** [CoolProp/CoolProp#1105]
At https://sourceforge.net/projects/coolprop/files/CoolProp/, there is  README.rst.txt, that still says that current is version 5.

I suppose it should be made a little more neutral, not mentioning any versions, to remove necessity to keep an eye on it.

**Comment by ibell** [comment]
Want to make a pull request with an update?

**Comment by mikekaganski** [comment]
It's at the root level of SF, so I didn't think I'm able to. But now that you mention it, I'll look at where it is located in the source tree.

**Comment by ibell** [comment]
Actually, I have no idea where that is in the repo, perhaps it isn't under
source control anymore...

**Comment by mikekaganski** [comment]
OK, then, I'll download it, update and then attach here, is this OK?

**Comment by ibell** [comment]
Yup, sounds good.

**Comment by mikekaganski** [comment]
[README.rst.txt](https://github.com/CoolProp/CoolProp/files/301725/README.rst.txt)

**Comment by jowr** [comment]
I updated the root README.rst.txt (it is not in the repository).
