### ISSUE TITLE
ValueError: _phase is unknown

### ISSUE THREAD

**Issue by gilbertsmink** [CoolProp/CoolProp#1119]
The second part in the following code does not work for me:
p = 2e5 gives "ValueError: _phase is unknown"

Or shouldn't I use the combination D and UMASS as input properties?

```
fluid = 'Hydrogen'
m = 1
T = 20+273

p = 1e5
u = CP.PropsSI('UMASS', 'P', p, 'T', T, fluid)
D = CP.PropsSI('D', 'P', p, 'T', T, fluid)
h = CP.PropsSI('HMASS', 'P', p, 'T', T, fluid)
# below does not work
p = CP.PropsSI('P', 'D', D, 'UMASS', u, fluid)

p = 2e5
u = CP.PropsSI('UMASS', 'P', p, 'T', T, fluid)
D = CP.PropsSI('D', 'P', p, 'T', T, fluid)
h = CP.PropsSI('HMASS', 'P', p, 'T', T, fluid)
# below does not work
p = CP.PropsSI('P', 'D', D, 'UMASS', u, fluid)
```

**Comment by ibell** [comment]
That combination should be fine, but hydrogen is a nasty fluid.  The
consistency plots look pretty much fine:
http://www.coolprop.org/dev/fluid_properties/fluids/Hydrogen.html#consistency-plots
.  Where is that UD input located?

**Comment by gilbertsmink** [comment]
Im trying to model the emptying of a tube trailer, filled with Hydrogen:

Might be I am making a essential thinking mistake in this way of solving?

```
##
T_tube = 20+273                                                         # [K] initial tubetrailer temperature
M_tube = 720                                                            # [kg] initial tubetrailer capacity
p_tube = 25.0e6                                                         # [Pa] initial tubetrailer pressure
D_tube = CP.PropsSI('D', 'P', p_tube, 'T', T_tube, fluid)               # [kg/m3] initial tubetrailer density
V_tube = M_tube / D_tube                                                # [m3] constant tube trailer volume  
# U_tube = M_tube * CP.PropsSI('UMASS', 'P', p_tube, 'T', T_tube, fluid)  # [J/kg] initial tubetrailer internal enerhy
s_tube = CP.PropsSI('SMASS', 'P', p_tube, 'T', T_tube, fluid) 
S_tube = s_tube*M_tube

#
p_min = 2.0e6               # [Pa] minimum tubetrailer pressure
m_flow = -250/3600          # [kg/s] massflow

t = 0                       # [s] initial time
dt = 1                      # [s] time step
p = []
T = []
while(p_tube > p_min):
    # internal variables
    D_tube = M_tube/V_tube
    
    p_tube = CP.PropsSI('P', 'D', D_tube, 'SMASS', S_tube/M_tube, fluid)
    T_tube = CP.PropsSI('T', 'D', D_tube, 'SMASS', S_tube/M_tube, fluid)
    p.append(p_tube)
    T.append(T_tube)
    
    # Step
    M_tube = M_tube + dt*(m_flow)

plt.plot(p)
```

**Comment by gilbertsmink** [comment]
It does not work for other fluids either:

`ValueError: _phase is unknown : PropsSI("P","D",29.95419348,"SMASS",2926.057204,"Air")`

**Comment by gilbertsmink** [comment]
This is an better example:

`import time
from numpy import *
from pylab import *
from matplotlib import *
import CoolProp.CoolProp as CP

fluid = 'Air'
T_0 = 20 + 273              # [K] ambient temperature

##
def kWh(J):
    return J*1e-3/3600

def compress(p_i, T_i, p_o, N, n_is):
    # p_i = pressure at inlet
    # T_i = Temperature at inlet
    # p_o = pressure at outlet
    # N = number of compression stages
    
    # inlet state
    h_i = CP.PropsSI('HMASS','P',p_i,'T',T_i,fluid)
    s_i = CP.PropsSI('SMASS','P',p_i,'T',T_i,fluid)
    
    # set the first stage its start condition to the inlet condition of the total process
    h_ni = h_i
    T_ni = T_i
    s_ni = s_i     
    
    #
    w_c = 0                 
    
    for n in range(1,N+1):
        # pressure level of stage
        p_n = p_i + (p_o-p_i)*(n/N)
        
        # isentropic compression
        s_no_is = s_ni
        h_no_is = CP.PropsSI('HMASS','P',p_n,'SMASS',s_no_is,fluid)
        
        # isentropic efficiency
        h_no = h_ni + (h_no_is - h_ni)/n_is
        s_no = CP.PropsSI('SMASS','P',p_n,'HMASS',h_no_is,fluid)
        T_no = CP.PropsSI('T','P',p_n,'HMASS',h_no,fluid)
        
        # stage after intercool (dont do this after the last stage)
        T_ni = T_i
        s_ni = CP.PropsSI('SMASS','P',p_n,'T',T_ni,fluid)
        
        # add compression work of current stage
        w_c += h_no - h_ni
    
    
    # outlet state
    s_o = s_no
    h_o = h_no
    T_o = T_no
    # return
    return ({
        'inlet': { 'T': T_i, 'p': p_i, 'h': h_i, 's': s_i },
        'outlet': { 'T': T_o,'p': p_o,'h': h_o,'s': s_o },
        'work': { 'w': w_c, }
    })

##
T_tube = 20+273                                                         # [K] initial tubetrailer temperature
M_tube = 720                                                            # [kg] initial tubetrailer capacity
p_tube = 2.50e6                                                         # [Pa] initial tubetrailer pressure
D_tube = CP.PropsSI('D', 'P', p_tube, 'T', T_tube, fluid)               # [kg/m3] initial tubetrailer density
print(D_tube)
V_tube = M_tube / D_tube                                                # [m3] constant tube trailer volume  
# U_tube = M_tube * CP.PropsSI('UMASS', 'P', p_tube, 'T', T_tube, fluid)  # [J/kg] initial tubetrailer internal enerhy
s_tube = CP.PropsSI('SMASS', 'P', p_tube, 'T', T_tube, fluid) 
S_tube = s_tube*M_tube

#
p_min = 2.0e6               # [Pa] minimum tubetrailer pressure
m_flow = -250/3600          # [kg/s] massflow

t = 0                       # [s] initial time
dt = 1                      # [s] time step
p = []
T = []
while(p_tube > p_min):
    # internal variables
    D_tube = M_tube/V_tube
    
    p_tube = CP.PropsSI('P', 'D', D_tube, 'SMASS', S_tube/M_tube, fluid)
    T_tube = CP.PropsSI('T', 'D', D_tube, 'SMASS', S_tube/M_tube, fluid)
    p.append(p_tube)
    T.append(T_tube)
    
    # Step
    M_tube = M_tube + dt*(m_flow)

plt.plot(p)

##
t = 0
dt = 1
p = []
T = []
while(p_tube > 2.0e6):
    
    # TODO: check if temperature remains nearly constant??
    
    h_tube = CP.PropsSI('HMASS', 'D', M_tube/V_tube, 'T', T_0, fluid)
    p_tube = CP.PropsSI('P', 'D', M_tube/V_tube, 'T', T_0, fluid)
    # T_tube = CP.PropsSI('T', 'D', M_tube/V_tube, 'UMASS', U_tube/M_tube, fluid)
    p.append(p_tube)
    # T.append(T_tube)
    
    # U_tube = U_tube - dt*(m*h_tube)
    M_tube = M_tube - dt*(m)
    
##
fluid = 'Hydrogen'
dm = 0.2
dt = 1
m = 1
T = 20+273

p = 1e5
u = CP.PropsSI('UMASS', 'P', p, 'T', T, fluid)
U = m*U
D = CP.PropsSI('D', 'P', p, 'T', T, fluid)
V = 1/D
h = CP.PropsSI('HMASS', 'P', p, 'T', T, fluid)
# below does not work
p = CP.PropsSI('P', 'D', D, 'UMASS', u, fluid)

for i in [1,2,3,4]:
    m2 = m - i*dm
    D2 = m2/V
    
    U2 = U - dm*(h-u)
    u2 = U2/m2
    p2 = CP.PropsSI('P', 'D', D2, 'UMASS', u2, fluid)
    T2 = CP.PropsSI('T', 'D', D2, 'UMASS', u2, fluid)
    h = CP.PropsSI('HMASS', 'P', p2, 'T', T2, fluid)
    print(m2, D2, p2, T2)
    
##
fluid = 'Nitrogen'
V = 28
p1 = 20e6
T1 = 300
rho1 = CP.PropsSI('D', 'T', T1, 'P', p1, fluid)
m1 = rho1*V
s1 = CP.PropsSI('SMASS', 'T', T1, 'P', p1, fluid)

m_flow = 15
t_stop = 150
m_out = m_flow * t_stop

# 2.
m2 = m1 - m_out
rho2 = m2/V

# 2a - isothermal expansion
T2a = T1
p2a = CP.PropsSI('P', 'T', T2a, 'D', rho2, fluid)

# 2b - isentropic expansion
s2b = s1
p2b = CP.PropsSI('P', 'SMASS', s2b, 'D', rho2, fluid)
T2b = CP.PropsSI('T', 'SMASS', s2b, 'D', rho2, fluid)
`

Gives error:
`ValueError: _phase is unknown : PropsSI("P","SMASS",5163.007484,"D",132.1800545,"Nitrogen")`

**Comment by gilbertsmink** [comment]
It works when I use:

`HEOS = CP.AbstractState("HEOS", "Hydrogen")`

However, I cannot find what HEOS is? Just lower-level programming?

**Comment by JonWel** [comment]
I just made some test with the last version from the GitHub:

```Julia
julia> using CoolProp

julia> PropsSI("P", "D", PropsSI("D", "P", 1e5, "T", 20+273, "Hydrogen"), "UMASS
", PropsSI("UMASS", "P", 1e5, "T", 20+273, "Hydrogen"), "Hydrogen")
100000.0

julia> PropsSI("P", "D", PropsSI("D", "P", 2e5, "T", 20+273, "Hydrogen"), "UMASS
", PropsSI("UMASS", "P", 2e5, "T", 20+273, "Hydrogen"), "Hydrogen")
199999.99999999997

julia> PropsSI("P","SMASS",5163.007484,"D",132.1800545,"Nitrogen")
8.60473718327026e6
```
So it seems the problem has been solved. Which version are you using?

The `"HEOS"` in
```Python
HEOS = CP.AbstractState("HEOS", "Hydrogen")
```
means `Helmholtz equation of state`, which is a model for the thermodynamic properties used by CoolProp. http://www.coolprop.org/develop/backends.html#backends
