### ISSUE TITLE
Allow state generation from backend_name() return values

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1120]
Currently, the output of `AbstractState::backend_name()` cannot be used with `AbstractState::factory`. That should be changed to allow for a simple implementation of a copy operation for the state objects.

**Comment by ibell** [comment]
Yes, I have added copy functions to a few backends thus far for my needs,
and I had been thinking about making the copy() function mandatory for all
backends.  As part of that I think I would make the backend name a static
method if I can, so it can be queried in AbstractState::factory.

**Comment by jowr** [comment]
I already fixed this, just waiting for the tests to finish...

**Comment by jowr** [comment]
But, yes, please go ahead and improve things with static variables or even enumerations.
