### ISSUE TITLE
Calculate density with PropsSi in Javascript

### ISSUE THREAD

**Issue by e-lead** [CoolProp/CoolProp#1122]
Hi, 
i just want to calculate the density of water with the PropsSi function. I do it like this:
 var density = cool.PropsSI('D', 'P', val.p1 * 100000, 'T', val.t + 273.15, 'Water');
It works fine but the strange thing is, it is not working with val.t = 0°C or  2, 4 ,5,6.
If val.t is 3,7,8 it is working.
What is my mistake?

Greets

**Comment by ibell** [comment]
Very strange.  What is val.p1?

**Comment by e-lead** [comment]
In this case 2.
I tryed with 1, then only 2°C does not work. 
If val.p1 = 3, then 5,6,7 not working.
Got really no clue. 
Is there no documentation for the accepted inputs for this function?

**Comment by ibell** [comment]
1 and 3 bar work fine on python for your inputs (see below), but it seems not in javascript.  What version of the javascript wrapper are you using?

``` python
import CoolProp.CoolProp as CP
for p in [1e5, 3e5]:
    for T_C in [0,1,2,3,4,5,6]:
        print CP.PropsSI('D','T',T_C+273.15,'P',p,'Water')
```
```
999.842411384
999.901168384
999.942338557
999.966504341
999.974213537
999.965982083
999.942296539
999.944141701
1000.00215288
1000.04260991
1000.06609358
1000.07315015
1000.06429415
1000.04001082
```

**Comment by ibell** [comment]
Also, check out this: http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function

**Comment by e-lead** [comment]
I downloaded the precompiled binary from sourceforge but i got no idea which version it is.
Is it working with the new one?

**Comment by ibell** [comment]
Could you try your js code with 6.0.0 and report back?

**Comment by e-lead** [comment]
This version is throwing an error when i load the file
![unbenannt](https://cloud.githubusercontent.com/assets/17468386/16037257/fbdaf57c-321f-11e6-9066-983eb826c9cf.png)

**Comment by e-lead** [comment]
Hi do you got an idea how to fix the problem?

**Comment by ibell** [comment]
Did you try with 6.0.0.0 yet?  Or better yet, 6.0.1dev?

**Comment by e-lead** [comment]
I downloaded the .js and the .mem file from here: http://www.coolprop.org/coolprop/wrappers/Javascript/index.html
But now i get an exception when calling the function

![unbenannt](https://cloud.githubusercontent.com/assets/17468386/16069167/a5855228-32cc-11e6-8a95-11d18e7f4df5.png)

**Comment by e-lead** [comment]
I downloaded the .js and the .mem file from here: http://www.coolprop.org/coolprop/wrappers/Javascript/index.html
But now i get an exception when calling the function


![](https://cloud.githubusercontent.com/assets/17468386/16069167/a5855228-32cc-11e6-8a95-11d18e7f4df5.png)

**Comment by ibell** [comment]
What inputs cause this exception to be thrown?

Exactly which .js file did you download?

**Comment by e-lead** [comment]
I downloaded these files:https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/Javascript/
It has to be the version 6.0.0
I included the .js file on my node server, like this : var cool = require('./vendor/coolprop.js');
The exception is thrown directly when starting the server. At this time i´m not calling any function. the server just crash.

PS: thank you very much for help and  sorrry for the inconvenience this may cause.

**Comment by ibell** [comment]
I've not run our coolprop.js in node.js before.  Can you try the sample
index.html and check whether that works?  If not, we can try to debug why
you get an exception right at load.

**Comment by e-lead** [comment]
Ok I think the main problem is the .js file.
I downloaded these files: https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/Javascript/
and uses at it is and the browser throws the same exception (coolprop.js:1 Uncaught 6993824 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.)

**Comment by JonWel** [comment]
@e-lead I just downloaded the [same files](https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/Javascript/), and the html file works correctly for me with Firefox on W7 64bit and Ubuntu 16.04 64bit.

(I downloaded the 3 files than opened the `index.html` with the Firefox browser. With internet explorer 11, the page load, but doesn't seems to compute the values)

Could you have some specific javascript configuration?

**Comment by e-lead** [comment]
Hi, now the new files are working. But there are the same problems. In some cases the density cannot be calculate, specially for Water. For example: p = 200000 PA and t = 273.15 K.This is acceptable, because of the phase change but it also not working with t= 275.15K.

**Comment by JonWel** [comment]
That's in deed strange.
When I use the index.html sheet, it computes the density with  p = 200000 PA and t = 273.15 K (rho = 999.8932825012488 kg/m³), but in deed not with t= 275.15K (the sheet is not updated when I push the button).
(I manually added water in the index.html).

**Comment by ibell** [comment]
What's the melting pressure for water at 200 kPa?

**Comment by ibell** [comment]
Sorry, stupid question...

**Comment by ibell** [comment]
Is there any error in the JS console?

**Comment by e-lead** [comment]
Same error message: "coolprop.js:1 Uncaught 7121720 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch."

**Comment by e-lead** [comment]
hi just found out that it is not working with 275.15K but with 275.16K. It is very strange but maybe it helps on finding the error.

**Comment by ibell** [comment]
It might be that an internal error should have been caught, but for some reason isn't being caught. I made a change in the build script, perhaps this will fix your issue.  Give it some time to re-build.

**Comment by ibell** [comment]
For interest, 
``` python
import CoolProp
CP = CoolProp.CoolProp
AS = CoolProp.AbstractState('HEOS',"Water")
Tm = AS.melting_line(CP.iT, CP.iP, 200000)
print(Tm)
print(CP.PropsSI('D','P',200000,'T',275.15,'Water'))
```
yields
```
273.145186453
999.992479992
```
So all temps above 273.145.... should work.

**Comment by ibell** [comment]
Any update with the new js code?

**Comment by e-lead** [comment]
Did you update the precompiled binaries?

**Comment by JonWel** [comment]
@e-lead [this](https://sourceforge.net/projects/coolprop/files/CoolProp/nightly/Javascript/) one should have been updated.

**Comment by e-lead** [comment]
Hi thank you very very much. It works very well.
