### ISSUE TITLE
Exception when using low-level set_mass_fraction method with Python wrapper

### ISSUE THREAD

**Issue by rbozinoski** [CoolProp/CoolProp#1126]
I am getting the following error when trying to use the low lever Python abstract state method to set the mass fraction. I am able to use the set_mole_fractions method without any trouble. Am I doing something incorrectly?

     In[72]: CP.__version__
     Out[72]: u'6.0.0'

      In[73]: fluid  = CP.AbstractState('HEOS','hydrogen')

      In[74]: fluid.set_mole_fractions([1])

      In[75]: fluid.set_mass_fractions([1])
      Traceback (most recent call last):

         File "<ipython-input-75-4d5f06656bc1>", line 1, in <module>
            fluid.set_mass_fractions([1])

         File "CoolProp/AbstractState.pyx", line 99, in     CoolProp.CoolProp.AbstractState.set_mass_fractions (CoolProp/CoolProp.cpp:17507)

         File "CoolProp/AbstractState.pyx", line 101, in CoolProp.CoolProp.AbstractState.set_mass_fractions (CoolProp/CoolProp.cpp:17445)

        ValueError: std::exception

**Comment by ibell** [comment]
Try the development version... (http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#automatic-installation - link 2)

This
``` python
import CoolProp
import CoolProp.CoolProp as CP
print CoolProp.__version__
print CoolProp.__gitrevision__
fluid  = CP.AbstractState('HEOS','hydrogen')
fluid.set_mole_fractions([1])
fluid.set_mass_fractions([1])
``` 
gives
```
6.0.1dev
e9477e7079404d2ae4f3241b3250a5bde2903183
```

**Comment by rbozinoski** [comment]
Hey perfect thanks Ian that fixed it.
