### ISSUE TITLE
REFPROP backend returns inf for quality method in Python

### ISSUE THREAD

**Issue by rbozinoski** [CoolProp/CoolProp#1128]
I noticed that when using the refprop backend, the quality is always returned as *inf* when in the two-phase region:

    In [65]: fluid = CP.AbstractState('HEOS','hydrogen')

    In [66]: fluid.set_mole_fractions([0])

    In [67]: fluid.update(CP.QT_INPUTS,0.5,28)

    In [68]: fluid.Q()
    Out[68]: 0.5
 
    In [69]: fluid = CP.AbstractState('REFPROP','hydrogen')

    In [70]: fluid.set_mole_fractions([0])

    In [71]: fluid.update(CP.QT_INPUTS,0.5,28)

    In [72]: fluid.Q()
    Out[72]: inf

    In [73]: CP.__gitrevision__
    Out[73]: u'84f7eff3638072177a5177cc30550766c9818856'

    In [74]: CP.__version__
    Out[74]: u'6.0.1dev'

Am I doing something wrong?

**Comment by JonWel** [comment]
Why do you set the mole fraction to 0?
To me, it looks like you ask the property of void, thus `Inf` is not that crazy.

**Comment by rbozinoski** [comment]
Sorry bad example. I was playing around with different inputs. When I switch the mole fractions to 1 I still get the same *inf* output:

    In [52]: fluid.set_mole_fractions([1])
    In [53]: fluid.get_mole_fractions()
    Out[53]: [1.0]
    
    In [54]: fluid.update(CP.QT_INPUTS,0.9,28)

    In [55]: fluid.Q()
    Out[55]: inf

    In [56]: fluid.p()
    Out[56]: 573590.4279844585

    In [55]: fluid.Q()
    Out[55]: inf

    In [56]: fluid.p()
    Out[56]: 573590.4279844585

    In [57]: fluid.rhomass()
    Out[57]: 7.730101705465516

I also tried different inputs to update which seems to work:

    In [58]: fluid.update(CP.DmassT_INPUTS,7.7301017054656,28)

    In [59]: fluid.p()
    Out[59]: 573590.4279844585

    In [60]: fluid.Q()
    Out[60]: 0.8999999999999888

    In [61]: fluid.T()
    Out[61]: 28.0

**Comment by JonWel** [comment]
The value of `Q` is in deed changed to `Inf` [in the code](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L1606).

@ibell What do you think of changing [this line](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L1550) to:
```C++
_Q = value1;q = value1; _T = value2;
```
Or maybe more clean to change all the instances of `_Q` in the [`QT_INPUTS` part of the switch case](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L1539) by `q`, so when doing `_Q = q` after the switch case, the value is correct?

**Comment by ibell** [comment]
Yes I think that would be a fine resolution to change the line to 
``` c++
_Q = value1; q = value1; _T = value2;
```
Same fix for PQ I guess as well :)

**Comment by ibell** [comment]
PR?

**Comment by JonWel** [comment]
It wouldn't be cleaner to use the `q` in the switch case as for the other cases?
(I tested and it works too, as the `_Q` is send as input to refprop each times, and not as a global variable)

I'll do a PR with this one and #1130 in the same time.

**Comment by ibell** [comment]
Yeah ok, maybe you are right about using ``q``.  It's up to you.  Seems either would do the job.
