### ISSUE TITLE
REFPROP backend returns ValueError for saturated liquid and inf for saturated vapor properties

### ISSUE THREAD

**Issue by rbozinoski** [CoolProp/CoolProp#1130]
This might be related to my other ticket (#1128 ) but just in case it's not I'm creating another one here. When using the refprop backend I am getting the following when trying to get the saturated densities:

    In [87]: CP.__version__
    Out[87]: u'6.0.1dev'

    In [88]: CP.__gitrevision__
    Out[88]: u'5eba323c093767717a664c48eed0f4ff5d4d9e3f'

    In [89]: fluid = CP.AbstractState('REFPROP','hydrogen')

    In [90]: fluid.set_mole_fractions([1])

    In [91]: fluid.update(CP.DmassT_INPUTS,7.7301017054656,28)

    In [92]: fluid.Q()
    Out[92]: 0.8999999999999888

    In [95]: fluid.saturated_vapor_keyed_output(CP.iDmass)
    Out[95]: inf

    In [96]: fluid.saturated_liquid_keyed_output(CP.iDmass)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-96-9dad56aae42d> in <module>()
    ----> 1 fluid.saturated_liquid_keyed_output(CP.iDmass)

    CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.saturated_liquid_keyed_output   (CoolProp/CoolProp.cpp:20881)()

    CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.saturated_liquid_keyed_output (CoolProp/CoolProp.cpp:20819)()

    ValueError: The saturated liquid state has not been set.

**Comment by JonWel** [comment]
Issue confirmed:

There are two things here:
```C++
CoolPropDbl REFPROPMixtureBackend::calc_saturated_liquid_keyed_output(parameters key) {
    if ((key == iDmolar) && _rhoLmolar) return _rhoLmolar;
    throw ValueError("The saturated liquid state has not been set.");
    return _HUGE;
}
CoolPropDbl REFPROPMixtureBackend::calc_saturated_vapor_keyed_output(parameters key) {
    if ((key == iDmolar) && _rhoVmolar) return _rhoVmolar;
    ValueError("The saturated vapor state has not been set.");
    return _HUGE;
}
```
- The function only works for `iDmolar`, and you are calling with `iDmass`. That however should be easy enough to add that possibility.

- The reaction should have been identical for both call, however the `throw` is missing for the `vapor` version.

**Comment by JonWel** [comment]
@ibell What about this?
```C++
CoolPropDbl REFPROPMixtureBackend::calc_saturated_liquid_keyed_output(parameters key) {
    if (_rhoLmolar) {
        if (key == iDmolar) {
            return _rhoLmolar;
        }
        else if (key == iDmass) {
            return (double)_rhoLmolar*(double)_molar_mass;
        }
        else {
            throw ValueError("Invalid key.");
            return _HUGE;
        }
    }
    throw ValueError("The saturated liquid state has not been set.");
    return _HUGE;
}
CoolPropDbl REFPROPMixtureBackend::calc_saturated_vapor_keyed_output(parameters key) {
    if (_rhoVmolar) {
        if (key == iDmolar) {
            return _rhoVmolar;
        }
        else if (key == iDmass) {
            return (double)_rhoVmolar*(double)_molar_mass;
        }
        else {
            throw ValueError("Invalid key.");
            return _HUGE;
        }
    }
    throw ValueError("The saturated vapor state has not been set.");
    return _HUGE;
}
```
Here is what my test code get:
```C++
    shared_ptr<CoolProp::AbstractState> h(CoolProp::AbstractState::factory("REFPROP", "hydrogen"));
    h->update(CoolProp::DmassT_INPUTS, 7.7301017054656, 28);
    std::cout << "q: " << h->Q() << std::endl;
    std::cout << "Dv: " << h->saturated_vapor_keyed_output(CoolProp::iDmass) << std::endl;
    std::cout << "Dl: " << h->saturated_liquid_keyed_output(CoolProp::iDmass) << std::endl;

q: 0.9
Dv: 7.04892
Dl: 59.3393
```

**Comment by ibell** [comment]
I think that should be ok.  The fundamental difference between REFPROP and CoolProp on this point is that REFPROP doesn't calculate/cache much for the saturated liquid and vapor state (only density).  Let's add Dmass/Dmolar, and give a better error message.
