### ISSUE TITLE
Export specify_phase in the shared library

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#1133]
I would like to export the function `specify_phase()` and `unspecify_phase()` in the shared library.

The `unspecify_phase()` is quite straightforward.

For the `specify_phase()`, I see different possibilities.

1. Two functions `specify_phase_liquid()` and `specify_phase_gas()`.
2. One function, `specify_phase("string")`, with an internal switch case to call the `specify_phase(CoolProp::iphase_liquid)` or `specify_phase(CoolProp::iphase_gas)`.
3. One function, `specify_phase(double param)`, which would call directly `specify_phase(static_cast<CoolProp::parameters>(param))`.
4. ?

Which solution would be preferred?
For me the first solution would be easier to use, the second has some overhead with the switch case, and the third needs to get the `param` value first.

Rem: the arguments are simplified here, of course the library functions would have at least the complete `(const long handle, long *errcode, char *message_buffer, const long buffer_length)` inputs.

**Comment by ibell** [comment]
I think number 2 is best, I believe there is a string->enum conversion for the phase enumeration too, which should make that part of the code a one-liner.

**Comment by JonWel** [comment]
So If i undestand correctly:
```C++
specify_phase(CoolProp::PhaseInformation.index_map.find(string))
```

This solution has in deed the advantage to allows to specify all the different phase keywords:
https://github.com/CoolProp/CoolProp/blob/master/src/DataStructures.cpp#L331

I'll prepare some PR.

**Comment by ibell** [comment]
There is also the get_phase_index function, that's probably what you should
be using...

**Comment by JonWel** [comment]
Yes, I realised that the precedent code was not working and found the `get_phase_index`.
I'm testing the function and if the results are good, the PR will follow (with some other changes).
