### ISSUE TITLE
Nonsensical results for mistaken inputs with INCOMP fluids

### ISSUE THREAD

**Issue by ericksonla** [CoolProp/CoolProp#1137]
I noticed today that CoolProp returns nonsensical results for incompressible fluids if you forget to include a concentration:
```
>>> PropsSI('T_freeze','T',298.,'P',1e5,'INCOMP::MAM')
-10128.932359691884
```

This isn't exactly a bug per say because they're bad inputs, but it would be nice if it would throw an error instead of returning a meaningless result.

**Comment by ibell** [comment]
Agreed.  @jowr?

**Comment by ibell** [comment]
@jowr - can you help with this one?  I tried a couple of things to make this work, but it seemed much more complicated than necessary.  Hopefully there might be an easy resolution.

**Comment by jowr** [comment]
The problem is not the missing fraction as it defaults to 1.0. What is missing is the check of the fractions when calling `T_freeze`. 

```Python
import CoolProp.CoolProp as CP
CP.PropsSI('T_freeze','T',298.,'P',1e5,'INCOMP::MAM')
CP.PropsSI('T_freeze','T',298.,'P',1e5,'INCOMP::MAM[1.0]')
CP.PropsSI('D','T',298.,'P',1e5,'INCOMP::MAM')
```
