### ISSUE TITLE
Invalid Key error when using REFPROP backend to calculate saturated vapor/liquid properties

### ISSUE THREAD

**Issue by rbozinoski** [CoolProp/CoolProp#1147]
Good morning guys,

This might be related to a closed ticket of mine from a month ago #1130. In any case I get an **Invalid Key** error when I try to get certain saturated properties when using the REFPROP backend:

    In [59]: CoolProp.__version__
    Out[59]: u'6.0.1dev'

    In [60]: CoolProp.__gitrevision__
    Out[60]: u'2315c274c8bb2f11c129ebf01e6fc73fb66acfd9'

    In [61]: fluid = CP.AbstractState('REFPROP','hydrogen')

    In [62]: fluid.set_mole_fractions([1.0])

    In [63]: fluid.update(CP.QT_INPUTS,0.5,25)

    In [64]: fluid.saturated_liquid_keyed_output(CP.iDmass)
    Out[64]: 64.70147983780066

    In [65]: fluid.saturated_liquid_keyed_output(CP.iHmass)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-65-e8017e8440c4> in <module>()
    ----> 1 fluid.saturated_liquid_keyed_output(CP.iHmass)

    CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.saturated_liquid_keyed_output (CoolProp/CoolProp.cpp:20881)()

    CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.saturated_liquid_keyed_output (CoolProp/CoolProp.cpp:20819)()

    ValueError: Invalid key.

**Comment by ibell** [comment]
Sadly REFPROP only calculates the co-existing phase densities and molar compositions, so that is all that is available to you.  On the other hand, once you know the density and the temperature, a flash calculation should go smoothly.

**Comment by rbozinoski** [comment]
I feel silly. I don't know why I didn't think about that myself. Thanks again for the quick response.
