### ISSUE TITLE
Need to override Excel DLL default location

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1149]
The .xlam VB code seems to require that the CoolProp.DLL is in C:\CoolProp.  Can this be changed at the user level?  Our users (including me) do not have write access to the C:\ drive as it is security hardened per NIST guidelines.  Is there a way to edit the .xlam file outside of Excel and get it to look for the DLL somewhere else?

**Comment by ibell** [comment]
You can always move the dll and update the path in the xlam.  That's
totally doable.

**Comment by henningjp** [comment]
How do I update the xlam without loading it into Excel?  When I do, a series of infinite popups tells me that it can't find C:\CoolProp\CoolProp_x64.dll.  I can't clear these in order to get to the VBA editor.

**Comment by JonWel** [comment]
@henningjp Did you tried pushing a long time (around 7 seconds) on the `Enter` key?
In my case, the loop is not infinite (just very long).

**Comment by henningjp** [comment]
@JonWel Thanks!  That did it.  Patience _IS_ a virtue!

**Comment by henningjp** [comment]
Maybe we need instructions on the Excel page about how to install at a different location other than C:\CoolProp.  Maybe I'm just Excel challenged.

**Comment by ibell** [comment]
It's not just you.  Want to file a PR with update to Excel docs?  I can
tidy up if need be.

P.S. Any updates on IF97?

**Comment by henningjp** [comment]
Already on it. Updating the Excel example sheet as well.  Ideally, I'd like to grab a user set table environment variable so the user can specify an alternate location for the DLL.

After the push on getting 6.0.0, I had to take a break to keep the wife happy. :smirk: I have some travel coming up, but will get back to IF97 in late August.
