### ISSUE TITLE
IF97 backend: Wrong results for cvmass

### ISSUE THREAD

**Issue by spinnau** [CoolProp/CoolProp#1150]
Using the IF97 backend in CoolProp 6.0.0 to calculate the specific isochoric heat gives wrong results:

```python
>>> PropsSI('Cvmass', 'T', 20+273.15, 'P', 1e5, 'IF97::water')
3723.23084013141

>>> PropsSI('Cvmass', 'T', 20+273.15, 'P', 1e5, 'HEOS::water')
4156.68620992575
```

**Comment by JonWel** [comment]
I confirm:
```Julia
julia> PropsSI("Cvmass", "T", 20+273.15, "P", 1e5, "IF97::water")
3723.23084013141

julia> PropsSI("Cvmass", "T", 20+273.15, "P", 1e5, "HEOS::water")
4156.6862099227

julia> PropsSI("Cvmass", "T", 20+273.15, "P", 1e5, "REFPROP::water")
4156.6862099425925
```

**Comment by ibell** [comment]
Interesting.  I'll investigate.

**Comment by henningjp** [comment]
Investigating as well, but my Mathcad license ran out. :angry:   I was sure I checked these before 6.0.0 released and verified against IAPWS-95.  Once I get my license back I can look into it as well.

**Comment by henningjp** [comment]
Well, the IF97 docs don't list verification values for Cv; only Cp.  That's how it got missed.

Problem only appears to be in **Region 1**.  The other regions check out against EOS and my own implementation of IF97.  I assume there are no typos in the coefficients, or the other functions would be hosed up in **Region 1** as well; has to be in the cvmass function.

Looking at [http://www.iapws.org/relguide/IF97-Rev.pdf](http://www.iapws.org/relguide/IF97-Rev.pdf) , there is a residual term added to the evaluation of cpmass(T,P).  The CoolProp/IF97 code for **Region 1** is using the generic region function, however, and it subtracts the residual from cpmass(T,P).

        double cvmass(double T, double p)
        {
            double tau = T_star/T, PI = p/p_star;
            return cpmass(T,p) - R*pow(1 + PI*dgammar_dPI(T,p) - tau*PI*d2gammar_dPIdTAU(T,p),2)/(1-PI*PI*d2gammar_dPI2(T, p));
        }

Actually, it looks like the generic template function is the **Region 2** formulation and **Region 1** is not over-riding the generic region equation.  I can't work on it until next week, but if you want to leave this open, I'll look into it, test it, and put in a PR.
