### ISSUE TITLE
PropsSI failure when finding pressure with T&Q inputs for water

### ISSUE THREAD

**Issue by stephen-young** [CoolProp/CoolProp#1153]
I have ran into some stability issues with the numerical solver for saturation water vapour pressure of water using PropsSI in MATLAB. I am a simulation where I evaluate the saturation vapour pressure of water multiple times and I will occasionally run into a temperature that will cause the PropsSI solver to crash. If I run the following code the PropSI function will fail 10 to 20 times:

```
numCalls = 1e5;
numCoolPropFailures = 0;
 
for i = 1:1:numCalls
   
    %try random temperature between 278.15 and 298.15
    temp = 278.15 + (298.15-278.15)*rand;
 
    try
        satVapPressure = CoolProp.PropsSI('P', 'T', temp, 'Q', 1, 'water');
        
    catch
        display(num2str(temp, 20),'The temp that stumped coolprop')
        numCoolPropFailures = numCoolPropFailures + 1;        
    end
        
end
 
display(numCoolPropFailures)
```

When the solver fails it generates the following error:

```
Warning: Maxwell solver did not converge after 30 iterations;
rhoL: 55369.60300408319 rhoV: 1.142950457436838 error:
4.86258e-009 dvL/vL: -6.34408e-015 dvV/vV: -9.71377e-015 pL:
2809.96 pV: 2809.96
 
> In CoolProp.PropsSI (line 2)
  In CoolPropTester (line 22) 

The temp that stumped coolprop =

296.14344172016945
```

The only workaround I have been able to find is rounding the temperature value to two decimal places. If I run the following code, it will result in zero errors:

```
NUM_DECIMALS = 2;
numCalls = 1e5;
numCoolPropFailures = 0;
 
for i = 1:1:numCalls
   
    %try random temperature between 278.15 and 298.15
    temp = 278.15 + (298.15-278.15)*rand;
    
    %round temperature to 2 decimal places
    temp = round(temp, NUM_DECIMALS);
 
    try
        satVapPressure = CoolProp.PropsSI('P', 'T', temp, 'Q', 1, 'water');
        
    catch
        display(num2str(temp, 20),'The temp that stumped coolprop')
        numCoolPropFailures = numCoolPropFailures + 1;        
    end
        
end
 
display(numCoolPropFailures)
```

Is there any reason why this is occurring? Why can’t the solver handle the full double precision values for temperature? Is this just numerical instability in the solver?

**Comment by JonWel** [comment]
I can't replicate with the shared library  on Windows 7 64bit:
```Julia
PropsSI("P", "T", 296.14344172016945, "Q", 1, "water")
2809.956121069202
```
If I set a high debug level, I have:
```Julia
julia> CoolProp.set_debug_level(100)

julia> PropsSI("P", "T", 296.14344172016945, "Q", 1, "water")
M:\Path\CoolProp\src\CoolProp.cpp:106: backend extracted. backend: ?
. fluid: water
AbstractState::factory(?,[ water ])
AbstractState::factory(HEOS,[ water ])
successfully set up state
M:\Path\CoolProp\src\Backends\Helmholtz\HelmholtzEOSMixtureBackend.cpp (1199): update called with (1: (QT_INPUTS), 1, 296.143)
[Maxwell] ancillaries T: 296.1434417201694 rhoL: 55359.7871027615 rhoV: 1.144443651036447 pL: -386698 pV: 2813.62
[Maxwell] starting T: 296.1434417201694 rhoL: 55369.6 rhoV: 1.14444 pL: 2813.62 pV: 2813.62
[Maxwell] rhoL: 55369.6030040955 rhoV: 1.142952398887017 error: 1.65917e-06 dvL/vL: 1.66749e-09 dvV/vV: 0.00130474 pL: 2813.62 pV: 2813.62
[Maxwell] rhoL: 55369.6030040929 rhoV: 1.142950457440685 error: 2.3027e-08 dvL/vL: 4.69475e-14 dvV/vV: 1.69863e-06 pL: 2809.96 pV: 2809.96
[Maxwell] rhoL: 55369.60300409453 rhoV: 1.142950457437429 error: 2.43815e-08 dvL/vL: -2.94338e-14 dvV/vV: 2.84888e-12 pL: 2809.96 pV: 2809.96
[Maxwell] rhoL: 55369.60300409626 rhoV: 1.142950457437472 error: 2.15122e-08 dvL/vL: -3.11691e-14 dvV/vV: -3.77489e-14 pL: 2809.96 pV: 2809.96
[Maxwell] rhoL: 55369.60300409473 rhoV: 1.142950457437448 error: 1.49873e-08 dvL/vL: 2.7501e-14 dvV/vV: 2.10216e-14 pL: 2809.96 pV: 2809.96
[Maxwell] pL: 2809.96 pV: 2809.96
AbstractState: keyed_output called for P
_PropsSI will return 2809.96
2809.956121069202
```
I tried CoolProp 6.0.0 and the development version.
I didn't tried yet the Matlab wrapper.

**Comment by stephen-young** [comment]
I am running Windows 7 64-bit with MATLAB R2015b 64-bit.

`fprintf('CoolProp version: %s\n', CoolProp.get_global_param_string('version'));
CoolProp version: 5.1.1
>> CoolProp.PropsSI('P', 'T', 296.14344172016945, 'Q', 1, 'water')
Warning: Maxwell solver did not converge after 30 iterations;  rhoL: 55369.60300408319 rhoV: 1.142950457436838 error:
4.86258e-009 dvL/vL: -6.34408e-015 dvV/vV: -9.71377e-015 pL: 2809.96 pV: 2809.96
 
> In CoolProp.PropsSI (line 2) 
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(246,varargin{:});`

Could it be because I am using an older version of CoolProp?

**Comment by ibell** [comment]
Yes probably it's because of old version.  Please update and report back

**Comment by stephen-young** [comment]
Ok. I updated my version of CoolProp and ran my tester function above without my work around and it didn't result in any failures.

Thanks for the help.
