### ISSUE TITLE
Setting Reference State - MATLAB

### ISSUE THREAD

**Issue by fchuahy** [CoolProp/CoolProp#1155]
I am trying to set the reference state of CoolProp with CoolProp.set_reference_stateD to match the reference state of Cantera so I can get the same absolute number for enthalpy and entropy.

But it doesnt seem to do anything to the reference state when I run the command

The reason I have to do this is because I have not been able to figure out why one of the properties is not converging, I get the message "Warning: phase envelope must be built"

Y_exh = strcat('O2[',nf_O2,']&N2[',nf_N2,']&CO2[',nf_CO2,']&H2O[',nf_H2O,']&CH4[',nf_UHC,']&CO[',nf_CO,']');
htest = CoolProp.PropsSI('H','P',P_BDC,'S',s_BDC,Y_exh);

I tried manually creating the mixture, by finding the H for each species and then averaging and I get the following error 
"Warning: unable to solve 1phase PY flash with Tmin=216.592, Tmax=3000 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Smolar [322.989 J/mol/K] is above the maximum value of 230.20098669 J/mol/K " for **CO2** which I did not have before with CANTERA.

So if I could use both libraries it would be great.

Thanks 

Flavio

**Comment by ibell** [comment]
Yup I think setting reference state for mixtures doesn't work.  It's not very trivial to set reference state for mixtures like it is for pure fluids.  There are a number of ways of doing setting the reference state for mixtures.  

Also, PS inputs currently only work when the phase envelope has already been constructed, which means you MUST use the low-level interface.

**Comment by fchuahy** [comment]
When I set a composition for a mixture it has to be in molar fractions right? and the default output is in mass basis?

**Comment by ibell** [comment]
Yes compositions are molar in this case.  The molar/mass specificness of
the property depends on your output string:
http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function

But for your case you need to use the low-level interface :
http://www.coolprop.org/coolprop/LowLevelAPI.html , build a phase envelope,
then do your call.  That should work.

In general, mixtures are hard, and REFPROP is much better than CoolProp
with mixtures.

**Comment by fchuahy** [comment]
Thanks,

I figured out a way to get around that.. My problem now is I cant get the enthalpy change (two different Temps) in EES, to match the one coming from CoolProp, is there a way to get ideal gas EOS from Coolprop?

Flavio

**Comment by ibell** [comment]
You could evaluate properties at a very low density ? That should give you
the ideal-gas enthalpy.  Even better would be to evaluate the contributions
to the enthalpy that arise from only the ideal-gas part of the Helmholtz
energy
