### ISSUE TITLE
update known hosts for SSH on OSX-slave

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1157]
The OSX slave does not like the buildbot master RSA host key:
```
The fingerprint for the RSA key sent by the remote host is
d0:d6:f8:bd:36:4e:fb:b2:4d:96:3c:e2:07:fa:e2:17.
Please contact your system administrator.
Add correct host key in /Users/Ian/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/Ian/.ssh/known_hosts:5
```

Didn't you update those keys a few weeks ago?

**Comment by jowr** [comment]
This makes the sphinx builds fail and keeps me from closing #1045 .

**Comment by ibell** [comment]
I'll try to resolve today.  I didn't fix before because I was waiting on
the plotting fix.

**Comment by ibell** [comment]
And we're back in business.  Sorry for the monumental delay.  In the end it only took a few seconds.
