### ISSUE TITLE
Export set_config_string(key,val)

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#1160]
I'm looking to export [set_config_string](https://github.com/CoolProp/CoolProp/blob/master/src/Configuration.cpp#L73), but as I understand, `Configuration.h` is not loaded for the shared library.

My first idea to export was to add this in the `CoolPropLib`:
```C++
EXPORT_CODE void CONVENTION set_config_string(const char * key, const char * val) {
    try {
        CoolProp::set_config_string(CoolProp::config_string_to_key(std::string(key)), std::string(val));
    }
    catch (std::exception &e) { CoolProp::set_error_string(e.what()); }
    catch (...) { CoolProp::set_error_string("Undefined error"); }
}
```
And it would also need to add `config_string_to_key` to the CoolProp namespace (in the `Configuration.h` file).

**Comment by ibell** [comment]
That seems pretty much correct to me!  Looking forward to your PR
