### ISSUE TITLE
Not erroring if T < Tmin and p > ptriple

### ISSUE THREAD

**Issue by GloriaVictis** [CoolProp/CoolProp#1165]
We are currently using the CoolProp (6.0.0) wrapper for Python in order to obtain thermodynamic properties of some fluids.
After some investigation, we discovered that PropSI function retrieves an output outside the limits imposed by the EOS. These values are misleading, since normally the fluid changes its phase (liquid -> Solid or liquid -> superfluid).

For example:
`CP.PropsSI("Nitrogen", "T_min")`
Yields 63.151 K

Now, if we query for the density of nitrogen at T = 50 K and P = 100000 Pa:
`CP.PropsSI("Dmass", "T", 50, "P", 100000, "Nitrogen")`
Yields 919.350093811 kg/m3, which does not reflect the reality, since N2 @ 50 K and 1 bar is in solid phase, where the density is around 250 kg/m3.

Is this already implemented in some other way?
To my understanding, CoolProp should have an error beyond the minimum and maximum limits. 

Many thanks in advance for your time and help.

**Comment by ibell** [comment]
The idea was supposed to be that if T > Tmin and p < psatmin, that should be fine, but in your case, this should be an error.  We don't have a sublimation curve for Argon, which would be required to avoid this issue otherwise.  Are you aware of a sublimation curve for Nitrogen?
