### ISSUE TITLE
Thermodynamic Properties of R1233zd(E)

### ISSUE THREAD

**Issue by RamonBanz** [CoolProp/CoolProp#1166]
Dear CoolProp developer

I am an assistant from the Lucerne School of Engineering and Architecture. We have a heat pump research project. Within this project we use Refprop and CoolProp to calculate the heat pump process with Matlab®. The fluid of interest is R1233zd(E).

Refprop and CoolProp use the same coefficients and exponents for the equation of state (literature reverence for both programs: Mondejar M.E. (2015)). We have found a big difference between Refprop and CoolProp of about 16 % by calculating the ideal-gas heat capacity cp0 (see Table below). Can you please give us a hint where this big difference may come from? Which model is correct?

|Temperature|cp0 CoolProp|cp0 Refprop|Difference between Refprop and CoolProp|
|----------------------|---------------------|---------------------|----------------------------------------|
| [K]	|[ J/kg/K]|[ J/kg/K]|[%]|
|	200	|	513.0286127	|	604.6403031	|	-15.1514363	|
|	210	|	531.5439702	|	629.3329743	|	-15.53851587	|
|	220	|	549.1311671	|	652.6043322	|	-15.85542113	|
|	230	|	565.8770614	|	674.54486	|	-16.10979567	|
|	240	|	581.8787141	|	695.2609077	|	-16.30786261	|
|	250	|	597.2358344	|	714.865409	|	-16.45478619	|
|	260	|	612.0454211	|	733.4713258	|	-16.55496274	|
|	270	|	626.3981523	|	751.1872043	|	-16.6122441	|
|	280	|	640.3761355	|	768.1143345	|	-16.63010223	|
|	290	|	654.0516957	|	784.345107	|	-16.61174528	|
|	300	|	667.4869333	|	799.962242	|	-16.56019519	|
|	310	|	680.7338359	|	815.0386414	|	-16.47833596	|
|	320	|	693.8347711	|	829.6376664	|	-16.36894042	|
|	330	|	706.8232269	|	843.813696	|	-16.23468188	|
|	340	|	719.7246941	|	857.6128537	|	-16.07813584	|
|	350	|	732.5576159	|	871.0738218	|	-15.90177577	|
|	360	|	745.3343456	|	884.2286846	|	-15.70796576	|
|	370	|	758.0620755	|	897.1037601	|	-15.49895239	|
|	380	|	770.7437091	|	909.7203926	|	-15.27686	|
|	390	|	783.3786609	|	922.0956888	|	-15.0436695	|

Literature reverence of Refprop and CoolProp: Mondejar, M.E., McLinden, M.O., Lemmon, E.W., "Thermodynamic Properties of Trans-1-chloro-3,3,3-trifluoropropene (R1233zd(E)): Vapor Pressure, p-rho-T Data, Speed of Sound Measurements and Equation of State," to be submitted to J. Chem. Eng. Data, 2015.

Thanks for your help.
Best Regards

Ramon Banz

Hochschule Luzern
Technik & Architektur

Maschinentechnik 
CC Thermische Energiesysteme & Verfahrenstechnik
Ramon Banz
BSc FHZ in Maschinentechnik
Wissenschaftlicher Assistent

T direkt +41 41 349 3258
ramon.banz@hslu.ch

Technikumstrasse 21, CH-6048 Horw
T +41 41 349 33 11, F +41 41 349 39 60
www.hslu.ch/tevt

**Comment by ibell** [comment]
This is BAD and I will definitely figure out which is correct and correct
the one that is not correct.

Couple of questions:
a) I don't remember, do they provide a cp0 equation in the paper? If so,
which resource does it agree with?
b) What version of REFPROP do you use?

**Comment by RamonBanz** [comment]
Dear ibell

Thank you for checking this. 

a.) You will find the ideal-gas heat capacity cp0 equation in the paper on page 9 (2485). The equation of cp0 needs the Coefficients and Exponents of the Equation of State in Table7 on page 10 (2486). Do you ned the equation and the exponents?

b.) We use REFPROP Version 9.1 with the newest fluid file (see link bellow).
Link: http://www.boulder.nist.gov/div838/theory/refprop/R1233ZDE.FLD

Thanks for your help.
 Best Regards

Ramon Banz

Hochschule Luzern
 Technik & Architektur

Maschinentechnik 
 CC Thermische Energiesysteme & Verfahrenstechnik
 Ramon Banz
 BSc FHZ in Maschinentechnik
 Wissenschaftlicher Assistent

T direkt +41 41 349 3258
ramon.banz@hslu.ch

Technikumstrasse 21, CH-6048 Horw
 T +41 41 349 33 11, F +41 41 349 39 60
www.hslu.ch/tevt

**Comment by ibell** [comment]
Well that's embarrassing.  The order of coefficients for cp0 were backwards.
