### ISSUE TITLE
Issue with PropsSI on Methane-Ethane mixtures

### ISSUE THREAD

**Issue by johnpmay** [CoolProp/CoolProp#1169]
I am running into solver errors when trying to calculate properties of a Methane-Ethane mixture
`PropsSI("Q","T",162,"P",139828.5,"Ethane[.18]&Methane[.82]")`
gives
 `Bad phase to solver_rho_Tp_SRK`
at lower temperatures (T=100) I get: 
`Inputs in Brent [19191.697830,27721.341310] do not bracket the root.  Function values are [96604.303175,375.014897]`

Is this a known issue? Is there anything I can do to mitigate this (we need the properties at T=95 e.g.)?

**Comment by ibell** [comment]
In CoolProp, it is not possible to evaluate TP inputs for mixtures that are
two-phase :(  It's on the list of things to do, but the development of
CoolProp occurs in my free time, of which I don't have much.

**Comment by ibell** [comment]
See also #1066

**Comment by ibell** [comment]
Fixed!
```
import CoolProp.CoolProp as CP
print CP.PropsSI("Q","T",162,"P",139828.5,"Ethane[.18]&Methane[.82]")
```
yields
```
0.993269255775
```
