### ISSUE TITLE
Potential Issue with Latest Coolprop (6) and Refprop Version 9.1.2.17 in Excel10 and Julia 4.6 64 bit (?)

### ISSUE THREAD

**Issue by TimHarvey2** [CoolProp/CoolProp#1171]
I have two computers running windows 10 64 bit, one with Office 2010 64 bit and the other Office 2010 32 bit. In Excel I use any CoolProp function with a "REFPROP:: 'any Fluid' " Excel crashes on both 64 and 32 bit versions. The problem is fixed by reverting to REFPROP 9.1 version. In Julia the Problem is a bit more complex as it only occurs on one of the two computers Julia crashes with any REFPROP Fluid in higher and lower level interface and using PyCall Package. I may have an other issue on that computer as I have to activate the CoolProp.xlam every time I start Excel. I have tried reinstalling excel but it does not fix the issue.

**Comment by ibell** [comment]
What function call do you try for REFPROP?

**Comment by TimHarvey2** [comment]
At Moment I have only tried a couple PRopsSI using  Viscosity, Density and Cvmass but I will try a few more as well. The initial functions I was testing were from Issue 1150 but I have tried changing pressure and temperature and fluid as well as viscosity and density all with same result. the "REFPROP::"Fluid'" reference seems to be the problem.

**Comment by ibell** [comment]
I use 9.12 without a problem, so it must be something to do with your
configuration on your computer.  Perhaps you are missing the Intel runtime
libraries which is not allowing the DLL to load.  Please email me at
ian.bell@nist.gov and I can send you new DLL.

**Comment by TimHarvey2** [comment]
Thanks for offer I will send email. However the problem seems to be due to having installed version of Refprop in C:\Program files (x86)\REFRPOP, and a copy in C:\Program files\REFPROP for excel when I only have an uninstalled copy of REFPROP in C:\Program files\REFPROP the "REFPROP::"Fluid'" works ok but when I only have two copies of REFPROP or just the one installed copy in C:\Program files (x86)\REFRPOP than the "REFPROP::"Fluid'" call from PropsSI crashes excel. This has only occured since I installed Julia (and uninstalled Julia) and I now also have the issue on both computers that the Coolprop.xlam has to be reloaded each time I run Excel. I can probably sort this eventually with some research..  As this occurred on two separate compucters it seems to be something that occurred during the julia installation. I guess the issue can be closed

**Comment by ibell** [comment]
Yes this is the classic path nightmare of REFPROP.  Some more info here: http://www.coolprop.org/dev/coolprop/REFPROP.html#path-issues
