### ISSUE TITLE
Impose phase for REFPROP in low-level interface

### ISSUE THREAD

**Issue by LSkogland** [CoolProp/CoolProp#1175]
Hi!

I am trying to use Coolprop in C# to calculate z and speed of sound with a given composition and at a given temperature and pressure. Under some conditions I get the error above. The composition I am using is a gas, so that it makes no difference to me that the liquid density is not calculable. But when I get this error all properties are inaccessible. Any other way of calculating just the properties I want? 

Below is an example of what I am trying to do (which fails). If you adjust the pressure to 1000 psi it works fine.

`var as3 = AbstractState.factory("REFPROP", "Nitrogen&CO2&Methane&Ethane&Propane&Butane&Pentane&Hexane&Heptane&ipentane&isobutan");
            var z3 = new DoubleVector(new[] { 0.02583, 0.01502, 0.69085, 0.13016, 0.06007, 0.02003, 0.01001, 0.00243, 0.00054, 0.01502, 0.03004});
            as3.set_mole_fractions(z3);
            try
            { 
                as3.update(input_pairs.PT_INPUTS, 6894.757293*1300, 302.15);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            Console.Write("Z:" + " " + as3.keyed_output(parameters.iZ) + " " + "\n");
            Console.Write("Speed of sound:" + " " + as3.keyed_output(parameters.ispeed_sound) + " " + "\n");
            Console.Write("Gas density:" + " " + as3.keyed_output(parameters.iDmass) + " " + "\n");`

**Comment by jowr** [comment]
Hi, to me this looks like an error that gets returned all the way from REFPROP. It might help to calculate the phase envelope before the actual flash calculation. 
See: http://www.boulder.nist.gov/div838/theory/refprop/Frequently_asked_questions.htm#ConvergenceFailures
and: http://www.boulder.nist.gov/div838/theory/refprop/Frequently_asked_questions.htm#SaturationStates

You might to contact NIST for more information.

**Comment by jowr** [comment]
I do not think that this is related to CoolProp. @ianhbell might be able to help with REFPROP.

**Comment by LSkogland** [comment]
Thank you so much for responding and trying to help.

When I run the same composition, temperature and pressure in refprop it
does give me the answers I need. In the link it suggests to add '<' or '>'
to the pressure, but as it is a double in the update function, I don't see
how to do this using coolprop. Any suggestions?

Lisbeth

**Comment by ibell** [comment]
There is currently no way in CoolProp to tell REFPROP you want the liquid
or vapor solution from the high-level interface.  But I have thought about
adding that capability for a long time.  It would be useful for me as well
in my day job.  If I can find time this weekend, I'll try to figure out how
to get this working this weekend.

**Comment by ibell** [comment]
Now, if you call specify_phase for REFPROP backend, that works, and I imagine it should fix this problem :)

**Comment by LSkogland** [comment]
Hi

Checked this now and it works beautifully. Thank you so much for putting in
the time to make this work.

However I have a bit of a new problem now. The outputs I need are
compressibility factor, speed of sound, cpmolar / cvmolar and gas density
(iDmass). All work just fine except the last one which now gives me the
following error:
"calc_helmholtzmolar is not implemented for this backend" which is wierd
because this was working before. The version I was using of coolprop was a
bit old, it´s dated April 7 of this year. Any idea why this suddenly
doesn´t work anymore?

Lisbeth

**Comment by ibell** [comment]
I have no idea why CoolProp tries to call calc_helmholtzmolar() function.  Can you provide your code please?

**Comment by LSkogland** [comment]
Sure. I was just testing some compositions... her it goes:

            var as3 = AbstractState.factory("REFPROP",
"Nitrogen&CO2&Methane&Ethane&Propane&Butane&Pentane&Hexane&Heptane&ipentane&isobutan");
            var z3 = new DoubleVector(new[] { 0.02583, 0.01502, 0.69085,
0.13016, 0.06007, 0.02003, 0.01001, 0.00243, 0.00054, 0.01502, 0.03004});
            as3.specify_phase(phases.iphase_gas);
            as3.set_mole_fractions(z3);
            try
            {
                as3.update(input_pairs.PT_INPUTS, 6894.757293*1000, 302.15);
                Console.Write("Z:" + " " + as3.keyed_output(parameters.iZ)
+ " " + "\n");
                Console.Write("Speed of sound:" + " " +
as3.keyed_output(parameters.ispeed_sound) + " " + "\n");
                Console.Write("Cp/cv:" + (as3.cpmolar() / as3.cvmolar()) +
" " + "\n");
                Console.Write("Gas density:" + " " +
as3.keyed_output(parameters.iDmass) + " " + "\n");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

Lisbeth

**Comment by LSkogland** [comment]
Hi again

In addition to the error message about calling calc_helmholtzmolar()
function it seems all the other numbers I´m getting are wrong.
If I run the following:

            var propssi = CoolProp.PropsSI("SPEED_OF_SOUND", "T", 273.15,
"P", 6894.757293 * 3439,
"REFPROP::Nitrogen[0.02583]&CO2[0.01502]&Methane[0.69085]&Ethane[0.13016]&Propane[0.06007]&Butane[0.02003]&Pentane[0.01001]&Hexane[0.00243]&Heptane[0.00054]&ipentane[0.01502]&isobutan[0.03004]");
            Console.Write("Speed of sound is " +propssi + " " + "\n");
            var as3 = AbstractState.factory("REFPROP",
"Nitrogen&CO2&Methane&Ethane&Propane&Butane&Pentane&Hexane&Heptane&ipentane&isobutan");
            var z3 = new DoubleVector(new[] { 0.02583, 0.01502, 0.69085,
0.13016, 0.06007, 0.02003, 0.01001, 0.00243, 0.00054, 0.01502, 0.03004});
            as3.specify_phase(phases.iphase_gas);

            as3.set_mole_fractions(z3);
            try
            {
                as3.update(input_pairs.PT_INPUTS, 6894.757293* 3439,
0+273.15);
                Console.Write("Pressure is " + 6894.757293 * 3439 + " " +
"\n");
                Console.Write("Temperature is " + (0 + 273.15) + " " +
"\n");
                Console.Write("Z:" + " " + as3.keyed_output(parameters.iZ)
+ " " + "\n");
                Console.Write("Speed of sound:" + " " +
as3.keyed_output(parameters.ispeed_sound) + " " + "\n");
                Console.Write("Cp/cv:" + (as3.cpmolar() / as3.cvmolar()) +
" " + "\n");
                Console.Write("Gas density:" + " " +
as3.keyed_output(parameters.iDmass) + " " + "\n");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

I get the following result:
Speed of sound is 682.676285966758
Pressure is 23711070.330627
Temperature is 273.15
Z: 4.89848771422388E-09
Speed of sound: 0.0905425659478742
Cp/cv:1.81518009360442
calc_helmholtzmolar is not implemented for this backend

Now the speed of sound should be identical. Could it be that the enum with
the list of outputs has been altered so that it´s calling other functions
than expected?

Lisbeth


On Mon, Aug 8, 2016 at 5:37 PM, Lisbeth Skogland <lisbeth.skogland@gmail.com
> wrote:

> Sure. I was just testing some compositions... her it goes:
>
>             var as3 = AbstractState.factory("REFPROP",
> "Nitrogen&CO2&Methane&Ethane&Propane&Butane&Pentane&Hexane&
> Heptane&ipentane&isobutan");
>             var z3 = new DoubleVector(new[] { 0.02583, 0.01502, 0.69085,
> 0.13016, 0.06007, 0.02003, 0.01001, 0.00243, 0.00054, 0.01502, 0.03004});
>             as3.specify_phase(phases.iphase_gas);
>             as3.set_mole_fractions(z3);
>             try
>             {
>                 as3.update(input_pairs.PT_INPUTS, 6894.757293*1000,
> 302.15);
>                 Console.Write("Z:" + " " + as3.keyed_output(parameters.iZ)
> + " " + "\n");
>                 Console.Write("Speed of sound:" + " " +
> as3.keyed_output(parameters.ispeed_sound) + " " + "\n");
>                 Console.Write("Cp/cv:" + (as3.cpmolar() / as3.cvmolar()) +
> " " + "\n");
>                 Console.Write("Gas density:" + " " +
> as3.keyed_output(parameters.iDmass) + " " + "\n");
>             }
>             catch (Exception e)
>             {
>                 Console.WriteLine(e.Message);
>             }
>
> Lisbeth
>

**Comment by LSkogland** [comment]
Hi

Sorry I took up your time with this last request. After downloading the
latest dev build, instead of building it myself, it all works as it should.
Must have done something wrong building.

Again thank you very much for getting this feature in place.

Lisbeth

**Comment by ibell** [comment]
Good to hear!  If you do a complete build yourself, it should give you the
same results.  You can see the steps we did to build the version you
downloaded:
http://www.coolprop.dreamhosters.com:8010/builders/Csharp-windows/builds/1659
