### ISSUE TITLE
Android Wrapper Undefined Reference error with latest ndk

### ISSUE THREAD

**Issue by ArslQ** [CoolProp/CoolProp#1178]
Greetings,
I have been trying to compile the android wrapper by following the instructions [here](http://www.coolprop.org/dev/coolprop/wrappers/Android/index.html) but it ends up with a bunch of Undefined Reference errors when compiling the Shared Library libCoolProp.so 

![snip](https://cloud.githubusercontent.com/assets/8383295/17457770/90345fb4-5c1a-11e6-9e7b-a53d95348997.PNG)

I am using the latest version of ndk and [this ](http://tdm-gcc.tdragon.net/) for MinGW on a Windows 7 x86 machine. Please help out. Thank you

**Comment by ArslQ** [comment]
Update: it works with ndk version 10e but gives the above error with the latest version

**Comment by ibell** [comment]
Sorry, but I don't have any ability to debug android builds.  @sabatind contributed the Android stuff, and perhaps he can give you some help.

**Comment by ArslQ** [comment]
The issue only appears when using the latest version of the ndk the library compiles fine with the older 10e version. Maybe google changed something that needs an update in the wrapper

**Comment by ibell** [comment]
Can you file a bug with them?  This doesn't look like a CoolProp issue.

**Comment by ArslQ** [comment]
I dont know what they have changed causing this error maybe they've made changes to the way android.mk file is structured or deprecated any function. I don't know much about ndk so I can't be of much help with this. I recommend that you add it to the wrapper instructions page to compile the library using ndk version 10e until a fix for the latest version is found

**Comment by ibell** [comment]
1) I will update the docs to recommend 10e.  
2) Can you please contact Google and ask about changes to NDK between 10e and 12e?  Or google around?

**Comment by ArslQ** [comment]
Found the NDK Revision History https://developer.android.com/ndk/downloads/revision_history.html
I hope this helps
