### ISSUE TITLE
CoolProp add-in for Excel not working on re-opened files

### ISSUE THREAD

**Issue by Arzista** [CoolProp/CoolProp#1180]
Hie everyone !

So, everything is in the title, i have an issue CoolProp on Excel when i re-opened a file with CoolProp's equations in it. They simply don't work.

Some more details, I work on Microsoft Office 2013 and use CoolProp version 6.0.0. (had the issue with the previous version to) running from the folder "C:\CoolProp\".
How the issue works : 
1) I creat a new Excel file, instal the CoolProp add-in, use some CoolProp equations, works fine.
2) Save and close the Excel file
3) Re-open the file, and tadaah... CoolProp's functions don't work anymore, and in the cells, i have equations like : ='C:\CoolProp\CoolProp.xlam'!PropsSI("Dmass";"T";298,15;"P";101325;"HEOS::Nitrogen")

What happens in stage 3) is it seem's that the add-in don't stay instaled, but if i go to the "File\Option\Add-ins" pannel on Excel, i can see the add-in listed in the "Activated Add-in" and with the right path ("C:\CoolProp\CoolProp.xlam").
Then if i click on the "Go..." button, CoolProp is cheked, and if i then click on the "Browser..." button, and direct excel to the exact same file, Excel tells me that this file already exist and asks if want to replace it. If i say yes, everything works fine again!

So, why i think it's a CoolProp and not an Excel issue? Because i have over add-ins not comming from microsoft that work just fine.

I looked every-where for answers but didn't find anything on this issue. I hope some-one here can help me.
I think I gave you every informations i have, but if you have any further questions, i'll be glade to answer.

Thank you in advance !

**Comment by henningjp** [comment]
This isn't happening for me (Office 2016 running on Widows 10), although it did the very first time, but not after I reloaded the Add-in.  Note that there is a new Excel add-in and example sheet in the nightly folder.  There's a new README file there on Github as well..  Try using \<Alt\>\<Ctrl\>\<Shift\>F9 when you get the error.  This will recalculate the worksheet, forcing an update of all the links.

I also edited all the formulas, taking the quoted full path out of the equation.  Something like...

> =PropsSI("Dmass","T",298,"P",101325,"Nitrogen")

...and then saving the file.  Note that HEOS: isn't needed, as it is the default.

**Comment by ibell** [comment]
My experience as well has been that you might need to uncheck the CoolProp add-in, close Excel, re-open Excel, Browse for the CoolProp add-in, select it, overwrite the old one.  You might also therefore also need to update the links - Excel is quite annoying in terms of how it handles add-in paths.  Check out the README that @henningjp refers to.

**Comment by Arzista** [comment]
Thanks guys for yours anwers.

Unfortunetaly, none of those solutions works. The readme file did give me some hint and i was able to completely remove CoolProp from excel and reinstal it, but i still have my issue (even with a reboot of the computer between the two.

However, @ibell 's uncheck/check method does reactivate every formulas on a file, so i managed to do a simple macro to do just this, which allows me to do it much quicker.
For the time beeing, this will do the trick, but it did not arrange the issue at the source.

I will ask on an Excel forum to see if this is really a coolprop issue or not, i'll keep you posted. In the mean time, if you have other ideas, i'll try them.

**Comment by ibell** [comment]
Ok, I think I get how to fix this now.  The key seems to be to put the xlam in one of the places that Excel likes.  So for me the protocol was:
a) In Excel, determine the location of the CoolProp xlam that it wants to load by going to Addins menu
b) Move the xlam somewhere else temporarily
c) In Excel, uncheck the CoolProp add-in - it might have already warned about the addin not being in the right place
d) Restart Excel. Check that the addin has been removed, or at least the path is not the old path to CoolProp
e) Determine the trusted directory for addins by going to File->Options...->Trust Center->Trust Center Settings...->Trusted Locations . Note the add-ins directory.  Put your CoolProp.xlam in that directory
f) In Excel, add the add-in for CoolProp again by checking it and browsing to the correct location
g) Restart Excel, add-in should still be there.

Any testers want to have a go with this?  It seems to work for me in Excel 2016.

**Comment by Arzista** [comment]
Hello! Thank you for not forgetting me.
Well, I tried your method but unfortunately... it didn't make it.
Even by putting the x64.dll file with it (and changing the .xlam macros to modify the dll paths).
I've tried something similar before by adding the "C:\CoolProp" folder at a secure location for Excel, it didn't do it either.
I think I'll just try to reinstall Excel at this point. Since it was working one day and not working the over, maybe it's just a bad update. It's the 2013 version by the way.
Thanks anyway.
If you find something else in the same time, i'll take it ; )

**Comment by Arzista** [comment]
Well, that's it guys, it's working again.
The solution : reinstalling Excel.
I've got to admit, I find it a bit disappointing, but at least it's working. Still don't know how it started and why it only affected CoolProp though.
Thank you all for your help ! Hope this can help somebody one day.
(do i have to put the topic as "solved" or something?)

**Comment by ibell** [comment]
Good to hear!! @jowr is working on our infrastructure for installing Excel add-in automatically.

**Comment by kaz4ikeda** [comment]
I solved this problem by unblocking the automatic prohibition of the downloaded internet file. Just check the unblock checkbox in the file property window. (It may be a button in Windows 7.)
![image](https://user-images.githubusercontent.com/26346697/42223761-80ff2538-7f13-11e8-9a38-0c1e50bb3968.png)

**Comment by ibell** [comment]
Thanks for the information about this.  Can you please update the
documentation with a short note about this:
https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/Excel/index.rst
?

**Comment by kaz4ikeda** [comment]
I tried: #1714 
Please check it out.

**Comment by chris-hampel-CA** [comment]
Hello all, 

@Arzista 's issue is also occurring with me still in 2022. If I open a new file that has coolprop references, Excel automatically changes the cell input to have the file directory listed before the PropSI call. 

For simple excel files, it is easy enough to manually delete the directory string; the PropsSI call then works. However, with much larger files, this is not an appropriate solution. 

I've read about two success from the thread. One by checking the unblock box under security preferences and the second is to reinstall Excel. For the first one, I do not see where this unblock option is. Where is it? I do not see the option when opening properties on the file. Also does this fix only apply to downloaded files? For the second option, I have not tried this yet, but am trying to make it my last resort option. Has a more robust solution to this issue come about over the past few years?

Thank you.

**Comment by kaz4ikeda** [comment]
The file to be unblocked is CoolProp.xlam. The place of it is diplayed in the string before the PropSI function which is automatically appended by Excel. If the unblock check box is not shown in the property window, the file has already become a trusted one. Sorry, I don't know other work arounds.

**Comment by chris-hampel-CA** [comment]
The unblock option appears for downloaded files. I checked this box for a downloaded file but the same issue still appeared. I also un-installed and re-installed Excel, and the same issue appears. 

The Coolprop plug-in was still installed even after the Excel re-install. I am curious if this issue is related to the manner by which I installed the plug-in. I recall having some confusion around the automatic install option versus the manual one. Does anyone kow the best way to do this?

**Comment by Fralopez** [comment]
I tried to use the Excel add-in to produce some calculation sheet to be used in my company. If I send a file to another colleague he sees the installation address of my xlam file in the formula. If at that point he updates the formulas and sends the file back to me, the same thing happens for me. This way though, especially if there are a lot of formulas calling CoolProp, it becomes unmanageable.
We could not solve even moving the xlam file to a shared folder, because Excel wants it in a specific folder.
Has anyone had similar problems? Any ideas on how to solve it?
I remember that a few years ago this problem was not there, because I had already happened to share Excel files that called CoolProp functions.

**Comment by kaz4ikeda** [comment]
I use Excel add-in (not limited to CoolProp) with the following practice:
- Use default add-in folder: "C:\Users\_username_\AppData\Roaming\Microsoft\AddIns".
- If the add-in location is not the default one, exit Excel app once after deleting the add-in in the add-in dialogue and restart Excel and register the add-in again. (Excel fails to register the add-in without restarting.)
- Re-link the xlam file in another environment using "Edit Links" button under Data ribbon. (Add-in functions are linked to the xlam file by its full-path name.)

**Comment by henningjp** [comment]
@Fralopez  Unfortunately, this is a quirk with excel for all Excel add-ins, not just CoolProp. The xla/xlam is installed to Excel’s add-in directory in the user’s profile.  Excel needs this full path to find the file in the user’s roaming profile the next time the file is opened.  When another user opens the file, their profile path is different (starts with C:\users\$UserName\AppData…) and the file can’t be found.  I’ve researched this for years and there is no simple solution.

There are a number of work around solutions out there, 
1. Install the macro on a shared network location (read-only).
2. Edit all links, replacing the path string with blank. Can replace all at once, but has to be done every time a worksheet is shared.
3. Add an auto run function that performs the second solution when it detects a new worksheet is opened.

There are many forums on the web with many frustrated Excel users on this very issue and no simple or easy solutions.

**Comment by julia-hartig** [comment]
@henningjp Do you have more details about the third workaround solution you mentioned (an auto run function for link path replacement)? I would like to implement something similar and I imagine someone else has already built a macro for this purpose.

**Comment by henningjp** [comment]
Sorry I don't. I found it on an internet forum (should have provided a link) but that was back in February.  My browser history and memory are long gone.  I have not implemented it myself.
