### ISSUE TITLE
Infinity return on certain arguments

### ISSUE THREAD

**Issue by erlen07** [CoolProp/CoolProp#1181]
Infinity is returned on the following input using Mathematica:
u = PropsSI["U", "D", 10., "Q", 1., "Water"]
p = PropsSI["P", "S", 5000., "H", 2500*10^3, "Ammonia"], although higher (7000) and lower (4000) values for S do work.

**Comment by ibell** [comment]
First one works fine in development version.

**Comment by ibell** [comment]
For the second one, your temperature is above the maximum temperature of the EOS.
