### ISSUE TITLE
Humid Air density validation

### ISSUE THREAD

**Issue by drsombra** [CoolProp/CoolProp#1207]
I am trying to validate humid air calculations and I would be thankful for any help with the issue.
While CoolProp calculations and data from ASHRAE RP-1485 are essentially identical, humid air density from Refprop is different, with the difference as high as 6% at some conditions. 
If I could get any comments or thoughts why there is this discrepancy in density, it would be very helpful.
I also would like to add my appreciation for absolutely great work with CoolProp.

**Comment by ibell** [comment]
My first guess is that you are actually retrieving the mixture density in
kg_ha/m^3 rather than kg_da/m^3 - the joys of units in psychrometry.  Can
you clarify with some numbers exactly what you are seeing?  In principle
HAPropsSI and REFPROP should agree quite closely, and certainly not off by
6%.

**Comment by drsombra** [comment]
Here the data from ASHRAE RP-1485, (Psychrometric Properties of Moist Air at 0C and Above, Saturated air at 101.325 kPa)
T =  80 deg C,  
Ws =  0.5529261  kgw/kg_da,
Vda =  1.8809 m3/kgda

CoolProp calculations agree with these data quite well, I am using calls like:
CoolProp.HAPropsSI('Vda', 'T', T, 'P', P, 'RH' , 1)

Next, I am calculating molar fraction of water to use it with Refprop from 
psi_w = CoolProp.HAPropsSI('psi_w', 'T', T, 'P', P, 'RH' , 1) 
psi_w = 0.4706
and my molar composition for humid air is: 
nitrogen  =  0.41354 
argon = 0.00487 
oxygen = 0.11096 
water = 0.47063

with REFPROP I am getting Vda  = 1.993453, difference is about 6%
The code for MATLAB is below.
Code produces output: 
T, K	Omega	DMASS_DA	DMASS_HA
ASHRAE
353.150000	0.552926	1.880900	1.211197
COOLPROP
353.150000	0.552926	1.880912	1.211205
RefProp
353.150000	0.552937	1.993453	1.283675

Thank you

--------------------------------------------------------------------------
% molar mass Air - g/mol
MM_air   = 28.96546; 
MM_water = 18.015268;
% ASHRAE RP-1485 – Final Report 
% Psychrometric Properties of Moist Air at 0C and Above
% Saturated air at 101.325 kPa
ASHRAE = [ 80     0.5529261     1.8809    1541.765    4.6511 ];
     
T = 273.15+ASHRAE(1);
P = 101325.0; 
% Humidity Ratio, kg water/kg dry air
Omega = ASHRAE(2);
V_DA = ASHRAE(3);
% HS = ASHRAE(4);
% SS = ASHRAE(5);
V_HA = V_DA/(1+Omega);
% CoolProp
% Water mass fraction, kg water/kg dry air
Omega_C = CoolProp.HAPropsSI('Omega', 'T', T, 'P', P, 'RH' , 1);
% Water mole fraction, mol water/mol humid air
psi_w = CoolProp.HAPropsSI('psi_w', 'T', T, 'P', P, 'RH' , 1);
% Mixture volume per unit dry air
V_DA_C = CoolProp.HAPropsSI('Vda', 'T', T, 'P', P, 'RH' , 1);
% Mixture volume per unit humid air
V_HA_C = CoolProp.HAPropsSI('Vha', 'T', T, 'P', P, 'RH' , 1);

% Refprop
% dry air used in Refprop:  0.7812 nitrogen, 0.0092 argon, and 0.2096 oxygen on a mole basis
FM_DA = [0.7812 0.0092 0.2096];
% mole fractions for humid air, mol component/mol humid air
FM_HA = [(1-psi_w)*FM_DA   psi_w];
% density, kg/m^3
DMASS_HA_R = refpropm('D<', 'T', T, 'P', P/1000, 'nitrogen', 'argon', 'oxygen','water', FM_HA);
% density of dry air, kg/m^3
DMASS_DA_R = DMASS_HA_R./(1+Omega_C);
% Water mole fraction, mol water/mol dry air
psi_da = 1./(1./psi_w-1);
Omega_R = MM_water/MM_air*psi_da;
fprintf(1,'%s\t%s\t%s\t%s\n','T, K', 'Omega', 'DMASS_DA', 'DMASS_HA');
fprintf(1,'ASHRAE\n');
fprintf(1,'%f\t%f\t%f\t%f\n',T, Omega, V_DA, V_HA);
fprintf(1,'COOLPROP\n');
fprintf(1,'%f\t%f\t%f\t%f\n',T, Omega_C, V_DA_C, V_HA_C);
fprintf(1,'RefProp\n');
fprintf(1,'%f\t%f\t%f\t%f\n',T, Omega_R, 1./DMASS_DA_R, 1./DMASS_HA_R);

**Comment by mikekaganski** [comment]
Unsure if that's relevant, but:
http://www.boulder.nist.gov/div838/theory/refprop/Frequently_asked_questions.htm#HumidAir

> Although version 9.1 allows mixtures of nitrogen, argon, oxygen, and water as a consequence from the addition of the new natural gas mixture model, calculations for moist air have not been tested yet. It is likely that calculated values are reasonable, however, Refprop may not return results because the saturation routines may fail.

Also note that you take properties of saturater air; and in both ASHRAE and CoolProp, "air" is a pseudo-gas, not "Air.mix" that is defined in CoolProp identically to REFPROP's (see https://github.com/CoolProp/CoolProp/blob/master/dev/mixtures/predefined_mixtures.json). So, having slightly different models, calculations near saturation point may give more significant differences than in other regions.

**Comment by ibell** [comment]
First thing that jumps out at me is that you should perhaps be doing a
dewpoint call, so giving P and Q =1 to refpropm, since that is the
definition of RH=1. Otherwise I'll have to do some debugging to see what is
going on here.  Thanks for the clear example, I should be able to decipher
what is going on.  I suspect it is a logical mistake in your code, but I
could be wrong.

**Comment by ibell** [comment]
That was the problem.  You needed to do a dewpoint calculation.  In python:
``` python
import CoolProp, numpy as np
CP = CoolProp.CoolProp

# molar mass Air - g/mol
MM_air = 28.96546; 
MM_water = 18.015268;
# ASHRAE RP-1485 - Final Report 
# Psychrometric Properties of Moist Air at 0C and Above
# Saturated air at 101.325 kPa
ASHRAE = [80, 0.5529261, 1.8809, 1541.765, 4.6511 ]

T = 273.15+ASHRAE[0];
P = 101325.0; 
# Humidity Ratio, kg water/kg dry air
Omega = ASHRAE[1];
V_DA = ASHRAE[2];
# HS = ASHRAE[3];
# SS = ASHRAE[4];
V_HA = V_DA/(1+Omega);
# CoolProp
# Water mass fraction, kg water/kg dry air
Omega_C = CP.HAPropsSI('Omega', 'T', T, 'P', P, 'RH' , 1);
# Water mole fraction, mol water/mol humid air
psi_w = CP.HAPropsSI('psi_w', 'T', T, 'P', P, 'RH' , 1);
# Mixture volume per unit dry air
V_DA_C = CP.HAPropsSI('Vda', 'T', T, 'P', P, 'RH' , 1);
# Mixture volume per unit humid air
V_HA_C = CP.HAPropsSI('Vha', 'T', T, 'P', P, 'RH' , 1);

# dry air used in Refprop: 0.7812 nitrogen, 0.0092 argon, and 0.2096 oxygen on a mole basis
FM_DA = np.array([0.7812, 0.0092, 0.2096]);
# mole fractions for humid air, mol component/mol humid air
FM_HA = np.r_[(1-psi_w)*FM_DA, psi_w];
# density, kg/m^3

# Refprop
AS = CP.AbstractState("REFPROP","NITROGEN&ARGON&OXYGEN&WATER")
AS.set_mole_fractions(FM_HA)
AS.update(CP.PQ_INPUTS, P, 1)
DMASS_HA_R = AS.rhomass()

# density of dry air, kg/m^3
DMASS_DA_R = DMASS_HA_R/(1+Omega_C);
# Water mole fraction, mol water/mol dry air
psi_da = 1./(1./psi_w-1);
Omega_R = MM_water/MM_air*psi_da;
print('%s\t%s\t%s\t%s' % ('T, K', 'Omega', 'DMASS_DA', 'DMASS_HA'));
print('ASHRAE');
print('%f\t%f\t%f\t%f' % (T, Omega, V_DA, V_HA));
print('COOLPROP');
print('%f\t%f\t%f\t%f' % (T, Omega_C, V_DA_C, V_HA_C));
print('RefProp');
print('%f\t%f\t%f\t%f' % (T, Omega_R, 1/DMASS_DA_R, 1/DMASS_HA_R));
```
yields
```
T, K	Omega	DMASS_DA	DMASS_HA
ASHRAE
353.150000	0.552926	1.880900	1.211197
COOLPROP
353.150000	0.552926	1.880912	1.211205
RefProp
353.150000	0.552937	1.884474	1.213499
```

So all is well with the universe :)

**Comment by drsombra** [comment]
Ian, thank you. 
These two calls in Matlab give different results:
`refpropm('D<', 'T', T, 'Q', 1, 'nitrogen', 'argon', 'oxygen','water', [0.4135 0.0049 0.1110 0.4706])`
and
`CoolProp.PropsSI('DMASS', 'T', T,'Q',1,'REFPROP::nitrogen[0.4135]&argon[0.0049]&oxygen[0.111]&water[0.4706]')`
yielding
0.8181 and 0.6194
My REFPROP version is 9.1. I guess it is the bug in refpropm.m ?
Thanks again

**Comment by ibell** [comment]
My guess is your are right that it is a bug in refprop/refpropm.  What if
you drop the < from D<?  That should yield exactly the same behavior.

**Comment by drsombra** [comment]
`D<` and `D` give  the same result

**Comment by ibell** [comment]
Does refpropm call SATTP or QTFLSH?  They might yield slightly different
results since this is an open-phase-envelope mixture I think

**Comment by drsombra** [comment]
both `D<` and `D` make calls to
`calllib('refprop','TQFLSHdll',...)`
in refpropm

**Comment by ibell** [comment]
That basically makes sense, but I am surprised that TQFLSH and SATTP (what
CoolProp calls) would give different answers, I'll investigate!

**Comment by drsombra** [comment]
refpropm reads substances fractions as MASS fractions, not molar ones.
sorry for wasting everybody's time

**Comment by ibell** [comment]
Yup you're right, I should have known that.
