### ISSUE TITLE
Vapour QT_INPUT with VTPR

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#1215]
Seems something went wrong somewhere:

```Julia
AS = AbstractState_factory("VTPR", "Ethane&Ethanol")
AbstractState_set_fractions(AS,[0.5,0.5])
AbstractState_update(AS, "QT_INPUTS", 1, 300)
```
Yields:
```
CoolProp: Error: p is not a valid number
```

None of the vapour saturation data are computed (but the liquid one works fine).
It was working fine yesterday.

**Comment by ibell** [comment]
You can thank my attempts at caching temperature and mole fractions in
UNIFAQ.  Clearly that was half-baked and not successful.  You could comment
out the check at the beginning of set_temperature and set_mole_fractions
functions.  I'll revert/fix tonight.
