### ISSUE TITLE
Peng-Robinson issue with Hydrogen

### ISSUE THREAD

**Issue by rbozinoski** [CoolProp/CoolProp#1217]
I just noticed something funny when using the PR cubic backend with pure hydrogen. This doesn't seem to be a problem with using the SRK backend or when I have a mixture of hydrogen and methane. I seem to only get a **Value Error** message when trying to update the PR abstract state object for hydrogen.

~~~~~
In [3]: import CoolProp as CP

In [4]: CP.__version__
Out[4]: u'6.0.1dev'

In [5]: CP.__gitrevision__
Out[5]: u'79fb9a6933ef7f1072e82d683508f754cb1e7471'

In [6]: AS = CP.AbstractState("PR", "Hydrogen")

In [7]: AS.set_mole_fractions([1.0])

In [8]: AS.update(CP.PT_INPUTS, 101325, 300)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-ecdb4bb6723a> in <module>()
----> 1 AS.update(CP.PT_INPUTS, 101325, 300)

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17654)()

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17546)()

ValueError: rhomolar is less than zero

In [9]: AS = CP.AbstractState("PR", "Methane&Hydrogen")

In [10]: AS.set_mole_fractions([0.50,0.5])

In [11]: AS.update(CP.PT_INPUTS, 101325, 300)

In [12]: AS.rhomolar()
Out[12]: 40.646764985994196

In [13]:

**Comment by ibell** [comment]
Interesting.  I'll investigate.

**Comment by Mauxdelaire** [comment]
I've got the same issue when I input high pressure to found a fugacity. (ex: PR  equation of state with 800 bar, 290K and a nitrogen/oxygen mix)

Maybe the PR code have rounded some expression so the rhomolar became 0.
 That is curious for your low pressure mixed. (In your case Rho_molar equals approximatly 0.025.)

**Comment by ibell** [comment]
Can you please provide a runnable set of code demonstrating the problem?

**Comment by Mauxdelaire** [comment]
import CoolProp.CoolProp as CP
import CoolProp

AS = CP.AbstractState("PR", "Nitrogen&Ethanol") 
T= 500
P = 80000000
z = [1,0]
AS.set_mole_fractions(z)

AS.update(CoolProp.PT_INPUTS, P, T)
print("The partial fugacity of the Species 1 is:", AS.fugacity(0)/100000, "bar")
print("The partial fugacity coefficient of the Species 1:", AS.fugacity_coefficient(0))

Traceback (most recent call last):

  File "<ipython-input-365-abc8d17f5ec9>", line 10, in <module>
    AS.update(CoolProp.PT_INPUTS, P, T)

  File "CoolProp/AbstractState.pyx", line 81, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:16429)

  File "CoolProp/AbstractState.pyx", line 83, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:16318)

ValueError: Cubic has three roots, but phase not imposed and guess density not provided

Note:
The same happen with with SRK EOS in that case and when I impose the phase : 
AS.specify_phase(CoolProp.iphase_gas) I get this issue:
ValueError: rhomolar is less than zero

To impose the density keeps the issue.


HEOS seems to work:

Out:
The partial fugacity of the Species 1 is: 1229.7197219693262 bar
The partial fugacity coefficient of the Species 1: 1.5371496524616577

Thank you.

**Comment by ibell** [comment]
Wait, specifying the phase doesn't fix this?  It definitely should, can you
please show your code with the phase specified?

**Comment by Mauxdelaire** [comment]
import CoolProp.CoolProp as CP
import CoolProp


AS = CP.AbstractState("PR", "Nitrogen&Ethanol") 
T= 500
P = 80000000
z = [1,0]
AS.set_mole_fractions(z)

AS.specify_phase(CoolProp.iphase_gas)

AS.update(CoolProp.PT_INPUTS, P, T)


print("The partial fugacity of the Species 1 is:", AS.fugacity(0))
print("The partial fugacity of the Species 2:", AS.fugacity_coefficient(0))

Traceback (most recent call last):

  File "<ipython-input-541-52ee67163d23>", line 13, in <module>
    AS.update(CoolProp.PT_INPUTS, P, T)

  File "CoolProp/AbstractState.pyx", line 81, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:16429)

  File "CoolProp/AbstractState.pyx", line 83, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:16318)

ValueError: rhomolar is less than zero

**Comment by ibell** [comment]
With the same code, I get:
```
The partial fugacity of the Species 1 is: 112229222.05119768
The partial fugacity of the Species 2: 1.4028652756399693
```

What version of CoolProp do you use?  I use version 6.2.1

**Comment by Mauxdelaire** [comment]
I'm running the 6.0.0
I will check for an update, thank you!

**Comment by ibell** [comment]
Yes, it should work with 6.2.x
