### ISSUE TITLE
States at boiling and condesation line

### ISSUE THREAD

**Issue by erlen07** [CoolProp/CoolProp#1224]
The following requests do not work, although the physical results exist:
PropsSI["T", "H", 10^6, "Q", 0, "Water"]
PropsSI["P", "S", 3*10^3, "Q", 0, "Water"]
PropsSI["T", "D", 1, "Q", 1, "Water"]

**Comment by ibell** [comment]
The last one should work (what error do you get?), but the others just aren't implemented.  They are not all that common, and besides, you can always just interpolate to find them.  Also, there are multiple solutions for some fluids, which make them difficult to handle for some fluids

**Comment by erlen07** [comment]
Hello Ian,

thank you for your quick reply!

I get the same result on all three inquiries, see below.

I draw phase diagrams e.g. T-s diagrams with isobars, isenthalps and isochores and these curves may change direction more or less abruptly at transitions from subcooled to saturated to superheated. That is why I wanted to withdraw such values at the boiling and condensation point.

Kind regards
Georg


[cid:image001.png@01D20827.15E06560]

Von: Ian Bell [mailto:notifications@github.com]
Gesendet: Montag, 05. September 2016 21:24
An: CoolProp/CoolProp
Cc: Aichinger Georg; Author
Betreff: Re: [CoolProp/CoolProp] States at boiling and condesation line (#1224)


The last one should work (what error do you get?), but the others just aren't implemented. They are not all that common, and besides, you can always just interpolate to find them. Also, there are multiple solutions for some fluids, which make them difficult to handle for some fluids

**Comment by ibell** [comment]
I cannot see your images.  Please add them in the github web interface.

**Comment by ibell** [comment]
The last one works for me, and the other two are not implemented:
``` python
In [1]: import CoolProp

In [2]: CoolProp.CoolProp.PropsSI('T','D',1,'Q',1,'Water')
Out[2]: 389.30789792149545

In [3]: CoolProp.__version__
Out[3]: u'6.1.1dev'

In [4]: CoolProp.__gitrevision__
Out[4]: u'722f4bf5de4812d1081129b0d5db3309551fe4fc'
```
