### ISSUE TITLE
Entropy reference states

### ISSUE THREAD

**Issue by fchuahy** [CoolProp/CoolProp#1225]
Ok,

So I need to do some entropy balances using CoolProp. These involve Fluids is several phases, non-mixed, just changing phase or reacting inside the control volume.

for example: Water and n-Dodecane go into a Reformer, and come out as Syngas (H2+CO+Ch4+Inerts)

I need to find the entropy destruction of the Reformer.

I am struggling with how to make sure all the entropies are in the same reference state so I can perform the balance. 

This might be stupid question, but with enthalpy you can correct the state by just doing : hform+ h - h(Tref)... Is there a way of instead of setting a different reference state, I can just correct them to the same state? 

Thanks

**Comment by ibell** [comment]
Do you want to change the entropy of the pure fluids?  If so, you want the
set_reference_state() function.  What language are you calling CoolProp
from?  Currently it is not supported to change the reference state of
mixtures.

**Comment by fchuahy** [comment]
Since my system is reacting and I am using pure fluids, to do an entropy balance in the reformer I need all of the entropies to be based on the same reference state. However since you cant change the reference state for a mixture I have to "shift" the values. 

I wanted to know how to "correct" the values, like its done for enthalpy Example: hform + h(T) - h(Tref), puts all enthalpies on the same reference.

For entropy I cant seem to make it work with : s0 (std enthalpy) + s(T,P) - s(T,Pref)

Can you suggest a way to accomplish what I am describing?

Thanks

**Comment by ibell** [comment]
Sorry, this isn't really a CoolProp question, I'm going to go ahead and close it.
