### ISSUE TITLE
Wrong maximum temperature for biofuels

### ISSUE THREAD

**Issue by ghobold** [CoolProp/CoolProp#1228]
Just wanted to report that Coolprop has the wrong temperature limits for biofuels (MethylLinoleate, MethylLinolenate, MethylOleate, MethylPalmitate, MethylStearate,), reporting it as 1000K, whereas the reference paper states that the maximum temperature should be 700K (the EoS shows awful results near to the critical point).

Additionally, while D5's paper does not report any temperature limit, I would suggest limiting it to the critical point because the EoS is cubic and also yields terrible results near the critical point from the supercritical side.

` CoolProp.PropsSI('Tmax', 'P', 1e6, 'T', 300, 'METHYLLINOLEATE')

ans =

        1000

 CoolProp.PropsSI('Tmax', 'P', 1e6, 'T', 300, 'METHYLOLEATE')

ans =

        1000

 CoolProp.PropsSI('Tmax', 'P', 1e6, 'T', 300, 'METHYLPALMITATE')

ans =

        1000

 CoolProp.PropsSI('Tmax', 'P', 1e6, 'T', 300, 'METHYLSTEARATE')

ans =

        1000

 CoolProp.PropsSI('Tmax', 'P', 1e6, 'T', 300, 'METHYLLINOLENATE')

ans =

        1000`

**Comment by ibell** [comment]
In this case we set the maximum temps to be consistent with REFPROP, so I'm inclined to leave them as they are.  The EOS should still be yielding reasonable values up to 1000 K.

For D5, it is most definitely not a cubic EOS (it's a multiparameter Helmholtz-energy-explicit EOS), and seeing as how D5 is a popular fluid for Organic Rankine Cycles, using Tc as Tmax means no supercritical cycles.

Thanks for the report, but I think it is best to leave it as is.
