### ISSUE TITLE
Bigger temperature range for mixtures

### ISSUE THREAD

**Issue by rjrg1989** [CoolProp/CoolProp#1231]
I need to obtain the table of properties for MEG at different concentrations but a wider range of temperatures ( at 50% until 150°C)
Is that possible?

**Comment by ibell** [comment]
@jowr?  I think the answer might be no, seeing as we have fit polynomial
curves to the data, and who knows what they would do when extrapolating.

**Comment by rjrg1989** [comment]
I know but I was just wondering if it was possible to get data in a wider range. Thx anyway :)
