### ISSUE TITLE
VTPR components with one group

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#1232]
For components with only one group like Water, Methanol, Ethane I get the error:
```
interaction parameters for UNIFAQ not yet set
```
Thrown because:
```
(this->interaction.size() == 0)
```
in [UNIFAQ.cpp](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/UNIFAQ.cpp#L124)

**Comment by ibell** [comment]
I'm not sure I understand, can you show an example?  Is it for pure fluids
only or mixtures? Should be easy to fix I think.

**Comment by JonWel** [comment]
I got this with pure fluid when doing a PT update.

**Comment by ibell** [comment]
That makes sense, I was only ever looking at mixtures with VTPR.  Can you
provide a failing example? Helps a lot with debugging...

**Comment by JonWel** [comment]
```julia
julia> using CoolProp

julia> set_config_string("VTPR_UNIFAQ_PATH","/path/UNIFAQ/")
""

julia> PropsSI("D", "P", 1e5, "T", 200,"PR::Water")
894.6692243691074

julia> PropsSI("D", "P", 1e5, "T", 200,"VTPR::Water")
ERROR: CoolProp: interaction parameters for UNIFAQ not yet set : PropsSI("D","P",100000,"T",200,"VTPR::Water")
 in error at error.jl:22
 in PropsSI at /home/johndoe/.julia/v0.4/CoolProp/src/CoolProp.jl:36
```
Or in low level:
```julia
julia> AS = AbstractState_factory("VTPR","Ethane")
0

julia> AbstractState_update(AS,"PT_INPUTS",1e5,200)
ERROR: CoolProp: Error: interaction parameters for UNIFAQ not yet set
 in AbstractState_update at /home/johndoe/.julia/v0.4/CoolProp/src/CoolProp.jl:220
 in AbstractState_update at /home/johndoe/.julia/v0.4/CoolProp/src/CoolProp.jl:230
```

**Comment by ibell** [comment]
Merci!  I'll investigate.

**Comment by JonWel** [comment]
Shouldn't `gE_R` simply be 0 for all pure fluids?
(lnGamma being the same as the pure component one).

I could add a condition on `is_pure_or_pseudopure` in that function to send 0 for pure fluids.

**Comment by ibell** [comment]
Hmm yes i think you are right.  Go for it and if it seems wrong we can undo
it later.
