### ISSUE TITLE
Excel 2016 Add-In Updates

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1235]
Figured out all the bits to get add-in to stably load

Set config string prototype:
```
Public Declare Function set_config_string Lib "C:\CoolProp\CoolProp.dll" Alias "_set_config_string@8" (ByVal key As String, ByVal value As String) As Long
```
Add-in ThisWorkbook open:
```
Private Sub Workbook_Open()
    Dim retval As Double
    retval = Module1.set_config_string("ALTERNATIVE_REFPROP_PATH", "c:\\Program Files (x86)\\REFPROP\\")
End Sub
```

**Comment by jowr** [comment]
What about creating an installer that puts the add-in into the user's AppData directory? Such a thing can be installed without admin rights and automatically activates the add-in... I volunteer to create an installer based in InnoScript. 

I  addition, what about setting an environment variable `COOLPROP_PATH` that contains the location of the dll and the Excel files?

**Comment by ibell** [comment]
Yup, that sounds like a great idea, though the comment above is in particular to get REFPROP to work with Excel via CoolProp.

On windows, your idea is a good one.  Is that really true that the addin in the AppData directory are automatically loaded?  If so, I should recommend that instead of the ProgramFiles directory recommended by Excel

**Comment by jowr** [comment]
I start working on it today. The add-ins are not automatically loaded, but I can make the installer load it for you. I think the important part is about the permissions, it seems that there are many users that cannot access the root directory in C: and we could circumvent this issue by installing into a user folder.

**Comment by ibell** [comment]
Yes that sounds good to me!  We need to have a way to set the REFPROP path as well, I'm going to figure that out.

**Comment by jowr** [comment]
Is this solved?

**Comment by ibell** [comment]
Not quite yet.  I have a couple of more pressing issues on my plate at the
moment.  My hope is to finish up the two small issues with Excel so that we
can enable REFPROP through CoolProp in Excel on OSX.  And then release
6.1(finally).  Any concerns on that front?

**Comment by jowr** [comment]
No concerns, but we should clean some of the docs and remove the old EES installer before you trigger the final build.

**Comment by ibell** [comment]
Umm... I had to make the release today because of some work issues.  But we
can do whatever is needed for the next release.
