### ISSUE TITLE
EES wrapper stopped working

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1236]
After updating EES, the wrapper does not seem to work anymore. A reinstall did not help and I get weird error messages. Is this a know issue or should I try to gather some more details and log files?

**Comment by ibell** [comment]
There was a report about this from one guy at ULg (I think) - maybe @JonWel ?  The answer I recall was to contact Sandy Klein for an update that fixed the bug.

**Comment by JonWel** [comment]
Hi,
That wasn't me (I never tried the integration to EES), so I fear I can't help much.

**Comment by davideziviani** [comment]
It works for me on EES Pro Academic V10.131-3D

**Comment by ibell** [comment]
I found the email from a guy at ULg.  Upgrading to version 10.092 fixed the problem for him.  What version are you on?  I think we can close this bug...

**Comment by jowr** [comment]
OK, I'll try to grab an update - I am on 10.091.

**Comment by davideziviani** [comment]
I have just upgraded from 10.131 to 10.134 and still it works fine. I think you can close it.

**Comment by jowr** [comment]
Hm, I have no idea what is going on. I also tried to reinstall the add-in...
![ees_error](https://cloud.githubusercontent.com/assets/769593/18890559/f0963cc8-8501-11e6-9cc5-658def692dbe.JPG)
![ees_version](https://cloud.githubusercontent.com/assets/769593/18890564/f36a41e2-8501-11e6-84fc-c2573e39f7cd.JPG)

**Comment by jowr** [comment]
What a pain, it was my virus scanner, sorry for the noise.

**Comment by davideziviani** [comment]
awesome! glad to see it was not CoolProp causing the issue
