### ISSUE TITLE
Create an installer for selected Windows wrappers

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1237]
It is time for aproper installer for Windows. During the installation, one should be able to selcet what is installed. At the moment, I think about these files:

- [x] Excel add-in, including 32bit and 64bit libraries and add-in activation
- [x] The standard shared libraries (dlls)
- [ ] Update the docs

What about the EES wrapper? Should that be included?

**Comment by ibell** [comment]
How about the GUI?  
MATLAB wrapper?

I think that covers perhaps 90% of the users according to sourceforge.  For python, it is trivial to pip install, so that's the route to go.

**Comment by jowr** [comment]
OK, moved to https://github.com/CoolProp/WindowsInstaller/issues/1, https://github.com/CoolProp/WindowsInstaller/issues/2, https://github.com/CoolProp/WindowsInstaller/issues/3 and https://github.com/CoolProp/WindowsInstaller/issues/4. Start with the Excel add-in.

**Comment by jowr** [comment]
Could anyone working on #1235 or #1180 please confirm that the new installer at https://www.dropbox.com/s/3ictop9myo82fl8/CoolProp_Excel_v6.0.exe?dl=0 works? @ibell @henningjp

**Comment by ibell** [comment]
Looking very nice, but doesn't work for me in Excel 2010.  I get the error:

"The most recent error number is 53. It's message text is: File not found: CoolProp_xls_std.dll"

**Comment by jowr** [comment]
That surprises me. Could it be, that you unchecked the PATH option during installation? Could you please check your environment variables and report back whether the installation folder `C:\Users\ibell\AppData\Roaming\Microsoft\AddIns\CoolProp` occurs there? It should be the last entry in your personal PATH, not the system-wide one.

**Comment by ibell** [comment]
Yeah I'll look tonight.

**Comment by ibell** [comment]
It's there, but I think my PATH is too long.  All tolled, my PATH variable is 2597 characters long at the command prompt. (From ``set PATH > path.log``)

**Comment by ibell** [comment]
Now I'm confused.  It appears to work.  Perhaps I needed a reboot of my computer?

**Comment by jowr** [comment]
Hm, I'll have it tested on a freshly installed virtual machine.

**Comment by jowr** [comment]
The shiny and fully automated build is now uploaded to http://www.coolprop.dreamhosters.com/binaries/MicrosoftExcel/ - use that one for further testing.

**Comment by jowr** [comment]
I forgot to announce the ENV changes to the system. It should work properly now.

**Comment by jowr** [comment]
I consider this done. The installer installs shared libraries (stdcall, cdecl, x64) in a local folder and adds this folder to the PATH. The Excel add-ins (xla and xlam) are installed in the correct folders (the Office version is detected at install time) and they are also activated. 

The only thing missing is the documentation...

**Comment by ibell** [comment]
Perhaps you want to an announcement on the mailing list and see if we can get some beta testers in the wild?

**Comment by davideziviani** [comment]
I tried the installer on my Win10 x64 and I got "The most recent error number is 53. It's message text is: File not found: CoolProp_xls_std.dll". I had to go with standard folder C:\CoolProp to make it work. Perhaps I tested a older version ?

**Comment by jowr** [comment]
Did you remove **all** traces of the old add-in? You should also use the new Excel files since the old ones had the absolute paths hardcoded in them. When you install the new package, you get an example file on your desktop and that is the file you should test.

**Comment by jowr** [comment]
The latest binaries can be found in the [nightly builds](https://sourceforge.net/projects/coolprop/files/CoolProp/nightly/MicrosoftExcel/) or on the [buildbot server](http://www.coolprop.dreamhosters.com/binaries/MicrosoftExcel/).

**Comment by davideziviani** [comment]
I will try this nightly built version. I am using a new laptop, so I have installed only CoolProp for Python before trying the binary for Excel. I will try again and let you know.

**Comment by jowr** [comment]
Any news? I have tried it on three different machines and it worked, please report back if you can find any bugs.

**Comment by davideziviani** [comment]
yes! All worked well for both Win7 and Win10 machines. I had to remove the old excel files reboot and make a clean install.

**Comment by jowr** [comment]
Great, thanks for the swift response. Now I "only" have to update the docs...

**Comment by ibell** [comment]
Can you please put back the xlam in the binaries folder for us non-windows users?  Perhaps in a sub-folder?  

Also, shouldn't the installer be tagged with the full release version, as in 6.0.1 rather than 6.0?

**Comment by jowr** [comment]
The binaries are uploaded to http://www.coolprop.dreamhosters.com/binaries/installer/ and the xlam file is back in the MicrosoftExcel folder. We still have to check the docs at http://www.coolprop.dreamhosters.com/binaries/sphinx/ after the next nightly build.

**Comment by ibell** [comment]
Thanks very much!
