### ISSUE TITLE
calc_first_partial_deriv in two phase for tabular backend

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#1238]
[calc_first_partial_deriv](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L602) is only defined for [using_single_phase_table](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L603), thus two phase points are not available.

This is required to make the equivalent to the derivatives [`drhodh_constp`](https://github.com/CoolProp/CoolProp-museum/blob/master/CoolProp/CPState.cpp#L1772) and [`drhodp_consth`](https://github.com/CoolProp/CoolProp-museum/blob/master/CoolProp/CPState.cpp#L2064) that where done for [tabular](https://github.com/CoolProp/CoolProp-museum/blob/master/CoolProp/TTSE.cpp#L2826) in `CoolProp 4` and are needed for https://github.com/CoolProp/ExternalMedia/issues/20 .

I don't really know how I could do this. Tabular backend are a bit opaque to me right now. For instance, there is a [SinglePhaseGriddedTableData](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.h#L429), but how about two phase?
Is there a paper covering that area I could use?

**Comment by jowr** [comment]
Could this be a misunderstanding? To my knowledge, [TTSETwoPhaseTableClass::evaluate_sat_derivative](https://github.com/CoolProp/CoolProp-museum/blob/master/CoolProp/TTSE.cpp#L2826) is a derivative **along** the saturation curve and not inside the two-phase region.

**Comment by jowr** [comment]
Is this the answer? [Two-phase derivatives](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L654) and [saturation derivatives](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L641) seem to be implemented.

**Comment by JonWel** [comment]
> is a derivative along the saturation curve

I'm not really used to these derivatives as did not have to use them yet. So it's possible that I do not express it in the best way.

In the [original ExternalMedia code](https://github.com/modelica/ExternalMedia/blob/master/Projects/Sources/coolpropsolver.cpp#L239), there is a need for some derivatives:
```C++
properties->ddhp = state->drhodh_constp();
properties->ddph = state->drhodp_consth();
```
These function names are not present in the newer version of CoolProp. Thus, I tried to find [equivalent functions to do the job](https://github.com/CoolProp/ExternalMedia/blob/master/Projects/Sources/coolpropsolver.cpp#L246):
```C++
properties->ddhp = state->first_partial_deriv(CoolProp::iDmass, CoolProp::iHmass, CoolProp::iP);
properties->ddph = state->first_partial_deriv(CoolProp::iDmass, CoolProp::iP, CoolProp::iHmass);
```
These two lines are also called in two phase region when neither `twophase_derivsmoothing_xend` and `rho_smoothing_xend` have a (positive) value.

For now, this way to call them works for HEOS in both pure and two phase, it do not need to be on the saturation curve to execute without error.
This also works for tabular backend on pure phase, but not in two phase, hence my issue.

Looking at your link on [Two-phase derivatives](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L654), I think this is the main missing part of the solution. What would remain is to call that function from [TabularBackend::calc_first_partial_deriv](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L602) instead of [throwing an error](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L637).

I'll have to check this, but it looks like the solution. Thanks @jowr

**Comment by ibell** [comment]
I think that this is working for the tabular backends if I am not mistaken,
the thing that is not working is the use of the splined derivatives with
the tabular backends.  But a test or two to be sure wouldn't be the end of
the world

**Comment by ibell** [comment]
This is definitely already working, but #870 is still an issue:

![test_two_phase_tabular](https://cloud.githubusercontent.com/assets/1859947/20201699/38c943ea-a777-11e6-98ea-784f73e23126.png)

from 
``` python
import numpy as np
import CoolProp
import matplotlib.pyplot as plt

AS = CoolProp.AbstractState('HEOS','Water')

# Saturated liquid
AS.update(CoolProp.PQ_INPUTS, 101325, 0)
Ts = AS.T()
h_fg = AS.saturated_vapor_keyed_output(CoolProp.iHmass) - AS.saturated_liquid_keyed_output(CoolProp.iHmass)
cl = AS.cpmass()

# Subcooled liquid
x, y = [], []
for T in np.linspace(Ts - 30, Ts - 0.1, 1000):
    AS.update(CoolProp.PT_INPUTS, 101325, T)
    x.append(-cl*(Ts-T)/h_fg)
    y.append(AS.first_partial_deriv(CoolProp.iDmass, CoolProp.iHmass, CoolProp.iP))
plt.plot(x, y, label = 'Subcooled')

# Two-phase derivatives (splined)
x, y1 = [], []
for Q in np.linspace(0, 0.3, 1000):
    AS.update(CoolProp.PQ_INPUTS, 101325, Q)
    x.append(AS.Q())
    y1.append(AS.first_two_phase_deriv_splined(CoolProp.iDmass, CoolProp.iHmass, CoolProp.iP, 0.3))
plt.plot(x, y1, label = 'Two-phase (splined)')

# Two-phase derivatives (normal)
x, y1 = [], []
for Q in np.linspace(0.0, 0.6, 1000):
    AS.update(CoolProp.PQ_INPUTS, 101325, Q)
    x.append(AS.Q())
    y1.append(AS.first_two_phase_deriv(CoolProp.iDmass, CoolProp.iHmass, CoolProp.iP))
plt.plot(x, y1, label = 'Two-phase')

AS = CoolProp.AbstractState('TTSE&HEOS','Water')
# Two-phase derivatives (normal, tabular)
x, y1 = [], []
for Q in np.linspace(0.0, 0.6, 1000):
    AS.update(CoolProp.PQ_INPUTS, 101325, Q)
    x.append(AS.Q())
    y1.append(AS.first_two_phase_deriv(CoolProp.iDmass, CoolProp.iHmass, CoolProp.iP))
plt.plot(x, y1, label = 'Two-phase (tabular)', lw = 4)

plt.title(r'$d\rho/dh|p$')
plt.xlabel('vapor quality (-)')
plt.ylabel(r'$d\rho/dh|p$')
plt.ylim(-0.005, 0.005)
plt.legend(loc='best')
plt.savefig('test_two_phase_tabular.png')
plt.show()
```

**Comment by JonWel** [comment]
Ok, I did not knew the derivative functionalities where separated for the two areas as the `first_partial_deriv` seemed to work in twophase for EOS (I was expecting to use this same function that would internally call the single phase and the two phase routines depending on the area).

So I'll just add one `else if (state->phase() == CoolProp::iphase_twophase)` to execute the `first_two_phase_deriv` and the issue will be solved on the ExternalMedia side.

Thanks for your help.
