### ISSUE TITLE
CoolProp on Mac OSX

### ISSUE THREAD

**Issue by squoilin** [CoolProp/CoolProp#1243]
Msg from Mathias Möller, TU Delft

Dear Sylvain,

I am trying to integrate CoolProp into my project FDBB (https://gitlab.com/mmoelle1/FDBB).

While working under Mac OSX I found two ‘inconsistencies’ in the current checkout from github

1) CMakeLists.txt, lines 156-158

CMake considers Mac OSX as UNIX system but the variable CMAKE_DL_LIBRARY is not defined by default.
Line 157 thus tries to use the macro findREQUIRED, which is of course not available.

2) CMakeLists.txt, lines 311-312

The compiler flag ‘-stdlib=libstdc++’ works fine for clang/clang++ (the default compiler) but not if gcc/g++ is installed, e.g., from macports, homebrew, etc. IMHO, checking for the CMAKE_SYSTEM_NAME is not sufficient but a sub-check for the C/C++ compiler would be required.

**Comment by ibell** [comment]
Hi @squoilin - can you please get Matthias to file pull requests against these bugs?  They are corner cases that I haven't run into before and don't know how to resolve.

**Comment by ibell** [comment]
Bump - any update?

**Comment by mmoelle1** [comment]
Sorry for my late reply. This is the original poster.

In the CMakeLists.txt file lines 157-159 you try to find the CMAKE_DL_LIBS under Unix
`if(UNIX)
    find_package (${CMAKE_DL_LIBS} REQUIRED)
endif()`
On Mac, these libs do not exists and that command is basically trying to find an empty package. The error message is
`CMake Warning at build/external/CoolProp/CoolProp-src/CMakeLists.txt:158 (find_package):
  By not providing "FindREQUIRED.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "REQUIRED",
  but CMake did not find one.

  Could not find a package configuration file provided by "REQUIRED" with any
  of the following names:

    REQUIREDConfig.cmake
    required-config.cmake

  Add the installation prefix of "REQUIRED" to CMAKE_PREFIX_PATH or set
  "REQUIRED_DIR" to a directory containing one of the above files.  If
  "REQUIRED" provides a separate development package or SDK, be sure it has
  been installed.`

I suggest that you either exclude this for APPLE
`if(UNIX AND NOT APPLE)
    find_package (${CMAKE_DL_LIBS} REQUIRED)
endif()`
or, maybe more elegantly, check for the existence of that variable
`if(CMAKE_DL_LIBS)
    find_package (${CMAKE_DL_LIBS} REQUIRED)
endif()`

**Comment by ibell** [comment]
Thanks for your PR - I was always super confused about this REQUIRED warning you show above and had no idea where it was coming from.  Thanks for clarifying what was the actual cause of the warning.  It never seemed to hurt anything, so I didn't worry about it too much.

**Comment by ibell** [comment]
Closed by #1261
