### ISSUE TITLE
REFPROP::ammonia[0.6]&dme[0.4] mixture convergence problem

### ISSUE THREAD

**Issue by krestenks** [CoolProp/CoolProp#1245]
Hi,

I am trying to do some calculations on R723, using CoolProp v6.0.0 and REFPROP v9.1,

It seems that there are some problems with convergence on the dew point curves for calculation of density and enthalpy. 

Matlab code to reproduce the issue and a graph shoving the output is attached here:
[R723_error.zip](https://github.com/CoolProp/CoolProp/files/497303/R723_error.zip)

If i try the same mixture directly in REFPROP i am unable to reproduce the problem.

Best regards
Kresten

**Comment by ibell** [comment]
That has to do with phase envelope construction.  You have to use the low
level interface and call the build_phase_envelope function after
constructing the AbstractState instance.  But really this is a REFPROP
problem, not a CoolProp problem
