### ISSUE TITLE
Python wrappers broken

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1247]
@jowr - the python wrappers are broken now on buildbot - I think that was caused by the modifications to the python stuff you were working on.  Can you investigate?

**Comment by jowr** [comment]
It should build again, but the problem is that the cmake that ships with the CoolProp/manylinux docker image is too old...

**Comment by ibell** [comment]
I'm pretty sure I remember updating something somewhere to add a modern cmake to the docker image.  Maybe not the most recent cmake ever, but recent enough... Perhaps you just need to freshen the docker images?

**Comment by jowr** [comment]
Yes, see https://github.com/CoolProp/Dockerfiles/commit/421daca6897c87fa23254018c6a0bcc9b48dc70f

**Comment by ibell** [comment]
Almost there...

**Comment by ibell** [comment]
Thanks!
