### ISSUE TITLE
IF97 Error in CoolProp Wrapping for SMath

### ISSUE THREAD

**Issue by Novice77** [CoolProp/CoolProp#1249]
Thank you for IF97 implementation of CoolProp efforts.
I've tested IF97 function of CoolProp in SMath.
Please, refer to attached test file for the results.

Thank you

M.S. Lee
[IF97_question.pdf](https://github.com/CoolProp/CoolProp/files/505043/IF97_question.pdf)

**Comment by mikekaganski** [comment]
Well... thank you for sharing your results.

**Comment by henningjp** [comment]
The saturation props are implemented directly in IF97, but don't pass through yet to the CoolProp interface.  I've started on coding and plan on implementing it soon.

**Comment by ibell** [comment]
Perhaps @Novice77 could help you?

**Comment by Novice77** [comment]
Dear Mr. Kaganski,

Thank you very much for your work.
I think it will be greate to support for IF97 in CoolProp!

Best regards,

MyeongSoo Lee

2016-10-03 2:23 GMT+09:00 Mike Kaganski <notifications@github.com>:

**Comment by Novice77** [comment]
Very Sorry!
I'm a novice for programming, but I could test and share the results.

**Comment by henningjp** [comment]
@Novice77 Saturation properties have been implemented (today) in the IF97 Backend.  Those functions should be working now in your SMath wrapper.  Give the dev version a day or so to update before you try it.  Let us know.

Viscosity and Thermal Conductivity not yet implemented in IF97 or the Backend.  They are on the list.

- [x] Saturation Properties (_PQ and QT Inputs_)
- [ ] IF97 (IAPWS) Viscosity
- [ ] IF97 (IAPWS) Thermal Conductivity

**Comment by henningjp** [comment]
P.R. #1397 addresses this issue.  Verification document attached as PDF.

NOTE: Attached IF97 test document shows that function CoolProp_saturation_ancillary() will not accept ANY backend strings, even HEOS.

[IF97 Resolved.pdf](https://github.com/CoolProp/CoolProp/files/721226/IF97.Resolved.pdf)

**Comment by henningjp** [comment]
I messed up the syntax in PR #1397.  This issue can be closed.

**Comment by henningjp** [comment]
@ibell , @Novice77 Bump.  I think this issue can be closed.
