### ISSUE TITLE
cannot compile with visual studio 14

### ISSUE THREAD

**Issue by chchen85** [CoolProp/CoolProp#1251]
Hi Ian,

Just re-post the issue in the link you provided. Following are the error messages I got in the visual studio 14.  It seems there are missing several head files. 

Severity	Code	Description	Project	File	Line	Column	Suppression State
Error	MSB6006	"cmd.exe" exited with code 1.	generate_headers	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	5	
Error	C1083	Cannot open include file: 'all_cubics_JSON.h': No such file or directory	CoolProp	C:\Users\Chao\Documents\GitHub\CoolProp\src\Backends\Cubics\CubicsLibrary.cpp	4	1	
Error	C1083	Cannot open include file: 'Eigen/Core': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\src\backends\helmholtz\MixtureDerivatives.h	17	1	
Error	C1083	Cannot open include file: 'Eigen/Core': No such file or directory	CoolProp	C:\Users\Chao\Documents\GitHub\CoolProp\src\ODEIntegrators.cpp	3	1	
Error	C1083	Cannot open include file: 'externals/REFPROP-headers/REFPROP_lib.h': No such file or directory	CoolProp	C:\Users\Chao\Documents\GitHub\CoolProp\src\Backends\REFPROP\REFPROPMixtureBackend.cpp	24	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	C:\Users\Chao\Documents\GitHub\CoolProp\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	C:\Users\Chao\Documents\GitHub\CoolProp\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1	
Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	CoolProp	c:\users\chao\documents\github\coolprop\include\CPstrings.h	13	1

**Comment by ibell** [comment]
Please list ALL the steps that you did to get to this point.  I use this
compiler with CoolProp without problems.

**Comment by chchen85** [comment]
Here are the steps i did:
1. Use CMake to generate visual studio solution files. I use the default settings.
    Specify the generator for this project : Visual Studio 14 2015
    Use default native compilers; selected
2. After the 1st step, it will pop up a message to choose some value and update the configuration and generate build files.
   In this step I tried several values, either COOLPROP_SHARED_LIBRARY or COOLPROP_STATIC_LIBRARY

3.  Then I use the visual studio to open the CoolProp solution solution files to compile, and the give the above error messages.

Hope this clarify the steps.

**Comment by ibell** [comment]
Yeah, don't use the graphical interface for cmake, follow our command line instructions.  What are you trying to build?

**Comment by jowr** [comment]
Please use the command line as @ibell suggests. Both @JonWel and me have successfully compiled CoolProp with Visual Studio 2015.
Please reopen the issue if you encouter any problems with the command line builds.

**Comment by JonWel** [comment]
@chchen85 Don't forgot to check the [common wrapper prerequisites](http://www.coolprop.org/coolprop/wrappers/index.html#common-wrapper-prerequisites) before following the instruction for the [shared library](http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#windows) or the [static one](http://www.coolprop.org/coolprop/wrappers/StaticLibrary/index.html#static-library) if you need that one.
