### ISSUE TITLE
thermodynamics

### ISSUE THREAD

**Issue by iurisegtovich** [CoolProp/CoolProp#1256]
hi
i was just conducting a review on github projects based on the keyword thermodynamics, and your repository does not show up because the only similar word that appears in your title and ~~readme file~~ **description** is "thermophysical".
so i guessed you might want to add the word thermodynamics in your ~~readme file~~ **description** text or as a tag/keyword in the bottom of the readme file so that your repository gets even more exposure

**Comment by thorade** [comment]
github recently introduced topics:
https://github.com/blog/2309-introducing-topics
I added two topics: fluid-properties and thermodynamics
https://github.com/search?q=topic:thermodynamics
