### ISSUE TITLE
Methanol-water mixture: strange results

### ISSUE THREAD

**Issue by khrovath** [CoolProp/CoolProp#1259]
Hello,

First of all, thank you for this wonderful library. I use it in high performance liquid chromatography. I was happy to see that now methanol-water mixtures are defined in the library. Probably I did something wrong, but when I calculate e.g. the density of 50:50 mixture I got strange results (I use Python wrapper):
```
>>> CP.PropsSI('D', 'T', 293, 'P', 1e5, 'water[0.5]&methanol[0.5]')
1400.6899753824314
>>> CP.PropsSI('D', 'T', 293, 'P', 1e5, 'methanol[0.5]&water[0.5]')
723.5891247046371
```
Neither results are good. Why the two results are different? Did I do something wrong?

Thank you for your answer in advance.

Best regards,
Krisztian

**Comment by ibell** [comment]
Indeed.  Those are very(!) odd results, I agree.  I'll investigate.

**Comment by JonWel** [comment]
With the shared library compiled some days ago I get:
```Julia
julia> using CoolProp

julia> PropsSI("D", "T", 293, "P", 1e5, "water[0.5]&methanol[0.5]")
ERROR: CoolProp: PT_INPUTS are two-phase, not yet supported : PropsSI("D","T",293,"P",100000,"water[0.5]&methanol[0.5]")
 in PropsSI(::String, ::String, ::Int64, ::String, ::Float64, ::String) at /home/johndoe/.julia/v0.5/CoolProp/src/CoolProp.jl:36

julia> PropsSI("D", "T", 293, "P", 1e5, "methanol[0.5]&water[0.5]")
ERROR: CoolProp: PT_INPUTS are two-phase, not yet supported : PropsSI("D","T",293,"P",100000,"methanol[0.5]&water[0.5]")
 in PropsSI(::String, ::String, ::Int64, ::String, ::Float64, ::String) at /home/johndoe/.julia/v0.5/CoolProp/src/CoolProp.jl:36
```

Is this really in the two-phase area? If yes, I think it's a known limitation of CoolProp (but should give similar message to mine, not giving wrong results)

Which version of CoolProp do you use?

**Comment by ibell** [comment]
If @JonWel is right, these are two-phase inputs, in which case see #1066 .  Hopefully I will get to that this weekend.

**Comment by khrovath** [comment]
Thank you for your answers and your work. 

I am using 6.0.0, upgraded by pip from a previous version (5.x).

Yes, you are right. 20°C and 1bar is liquid phase definitely. I checked with a larger temperature (493K), and it worked like a charm.

**Comment by ibell** [comment]
I implemented the two-phase solver.  The single-phase PT solver is still not super reliable.

This script
```
from CoolProp.CoolProp import PropsSI
import matplotlib.pyplot as plt, numpy as np
temp = np.linspace(240, 500, 100)
x,y=[],[]
mix = 'Methanol[0.5]&Water[0.5]'
for T in temp:
    try:
        y.append(PropsSI('D','T',T,'P', 1e5,mix))
        x.append(T)
    except BaseException as BE:
        print BE
plt.plot(x,y,'o-')
plt.axvline(PropsSI('T','Q',1,'P', 1e5,mix),dashes = [2,2]) # Dewpoint
plt.axvline(PropsSI('T','Q',0,'P', 1e5,mix),dashes = [2,2]) # Bubblepoint
plt.ylabel('D (kg/m3)')
plt.xlabel('T (K)')
plt.savefig('methanol_water.png')
plt.show()
```
yields
![methanol_water](https://cloud.githubusercontent.com/assets/1859947/19631838/daa53d2c-995d-11e6-9d31-7586e484b5e1.png)

So mostly working, aside from a small number of failures.  Water mixtures are hard...
