### ISSUE TITLE
Javascript using localhost does not work

### ISSUE THREAD

**Issue by Froudd** [CoolProp/CoolProp#1263]
I copy the source code of the example from http://coolprop.sourceforge.net/jscript/index.html and run it using MVS using a localhost and I get the following error in the consol (in Chrome and a very similar error in Firefox):

_run() called, but dependencies remain, so not running
GET http://localhost:16818/coolprop.js.mem 404 (Not Found)
Uncaught could not load memory initializer coolprop.js.mem
still waiting on run dependencies:
dependency: memory initializer
dependency: al coolprop.js.mem_

If I click on Calculate I get:

_Uncaught TypeError: Module.PropsSI is not a function_

Can somebody help me ? I want to be able to use CoolProp with a simple javascript code.
Thank you

**Comment by ibell** [comment]
Looks like you didn't download the coolprop.js.mem file (we asychronously
load the .mem module)

**Comment by Froudd** [comment]
Thank you for the quick answer.

I actually do have the coolprop.js.mem in my folder:
![capture](https://cloud.githubusercontent.com/assets/22819030/19377391/46934b0c-91e6-11e6-9563-ae353aa29bea.PNG)
I think the problem may be how to load it correctly. I just download the .mem file from https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/Javascript/ and drag it into the MVS project.

I am new to html and javascript, should I use another way to load the .mem file ?

**Comment by ibell** [comment]
To make sure you are doing things properly, put index.html, coolprop.js, and coolprop.js.mem in the same directory, and open index.html in your browser.  The rest of the details are not related to coolprop.

**Comment by ibell** [comment]
I see the same problem when I run a quick-and-dirty python webserver.  I'll see if I can figure out what is going on.  It should work...

**Comment by ibell** [comment]
Aha: problem is ``index.html`` - still tries to pull from coolprop.  Change this line:
```
<script src="http://www.coolprop.sourceforge.net/jscript/coolprop.js"></script>
```
to
```
<script src="coolprop.js"></script>
```
and that should do it.
