### ISSUE TITLE
Problem with calc_isolines()

### ISSUE THREAD

**Issue by shabdaly** [CoolProp/CoolProp#1265]
When I try the following example:
    
I get a load of error messages that appear to say that some root-finding process is not converging. A dump of the error messages I get are in the attached file.

```
import CoolProp
from CoolProp.Plots import PropertyPlot
plot = PropertyPlot('R290', 'ph')
plot.calc_isolines()
plot.show()
```
I'm using version 6.0.0, installed in Anaconda Python Distribution.

[dump.txt](https://github.com/CoolProp/CoolProp/files/528107/dump.txt)

**Comment by ibell** [comment]
@jowr ?

Some failures are to be expected, but I would think that most would succeed.  What does your figure look like?

**Comment by jowr** [comment]
I would assume that the plot looks fine. Given that we calculate a lot of lines, the number of errors might be acceptable.

**Comment by mayersre** [comment]
Hi, I tried to look into this but just faced another issue when I tried to use the GUI to test the plot.
Python 3.4.3 CP 6.0.0 

plot=PropertyPlot('R290', 'ph', unit_system='EUR', tp_limits='ACHP', axis=self.ax )

results in TypeError: __init__() got an unexpected keyword argument 'axis'

Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "/home/mayers/git/GUI/cpgui_diagram.py", line 160, in RG1_StringVar_Callback
    plot=PropertyPlot('R290', 'ph', unit_system='EUR', tp_limits='ACHP', axis=self.ax )
  File "/home/mayers/PyEnv/GUI/lib/python3.4/site-packages/CoolProp/Plots/Plots.py", line 74, in __init__
    super(PropertyPlot, self).__init__(fluid_name, graph_type, **kwargs)
  File "/home/mayers/PyEnv/GUI/lib/python3.4/site-packages/CoolProp/Plots/Common.py", line 613, in __init__
    Base2DObject.__init__(self, graph_type[1], graph_type[0], state, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'

**Comment by mayersre** [comment]
Sorry, was just confused with the **kwargs, it's an arg

**Comment by mayersre** [comment]
above 10² kPa the Plot on the dewline side consists mostly of one horizontal and one vertical line

**Comment by ibell** [comment]
Can we please see some pictures?  That's in the end what is this is all
about.

**Comment by mayersre** [comment]
![plot-r290](https://cloud.githubusercontent.com/assets/8641143/19716790/ee6b42fa-9b5d-11e6-894a-de4f26829085.png)

**Comment by mayersre** [comment]
from cut/paste code above

**Comment by mayersre** [comment]
And this one from same code, just changing Propane to r134a

![plot-r134a](https://cloud.githubusercontent.com/assets/8641143/19716875/47144280-9b5e-11e6-885f-f63990be640e.png)

**Comment by ibell** [comment]
@jowr - any idea what is up here?  I note the comment about fixing the
phase envelope in the error log...
