### ISSUE TITLE
Peaks at thermal conductivity

### ISSUE THREAD

**Issue by TheTinka** [CoolProp/CoolProp#1275]
Hello,
I am looking for the thermal conductivity of isobutane. If I plot some points for the wet steam region I get some strange looking peaks. Are they realistic or is this some kind of bug?

Thanks in advance!

![conductivity](https://cloud.githubusercontent.com/assets/22595315/19475139/d8fe3980-9532-11e6-82fd-c1c58bbdf814.jpeg)

```Python
import matplotlib.pyplot as plt
import numpy as np
from CoolProp.CoolProp import PropsSI

con = ([])
hu = PropsSI('H', 'P', 15e5, 'Q', 0, 'IsoButane')
ho = PropsSI('H', 'P', 15e5, 'Q', 1, 'IsoButane')
h = np.linspace(hu, ho, 500)
for i in h:
    con = np.append(con, PropsSI('conductivity', 'P', 15e5, 'H', i, 'IsoButane'))
plt.plot(h, con)
plt.show()
```

**Comment by jowr** [comment]
You should be very careful with transport properties in the two-phase region. Please consider not to use them... You might also be interested in this old issue: https://github.com/ibell/coolprop/issues/25

**Comment by ibell** [comment]
Yes, @jowr is right.  You should not evaluate two-phase transport properties in this manner.  You can understand it this way: vapor liquid equilibrium is the formed of two phases - a liquid phase and a vapor phase in equilibrium.  You could stick a probe into the mixture to measure each of the phases individually, but there are many averaging schemes to give you a "bulk" mixture property.
