### ISSUE TITLE
Predefined mixture components

### ISSUE THREAD

**Issue by emoehr** [CoolProp/CoolProp#1278]
Hello
Is it possible to get components names of the predefined mixtures (*.mix)? I can get a list of mole fractions of the components but can't figure out what they refer to.

**Comment by ibell** [comment]
Well, here is one way using the low-level interface in python:
```
import CoolProp
for mix in CoolProp.CoolProp.get_global_param_string('predefined_mixtures').split(','):
    try:
        AS = CoolProp.AbstractState('HEOS', mix)
        print mix, AS.fluid_names()
    except: pass
```
Only caveat is that the mixture has to be loadable (has to have interaction parameters available for each binary pair).

Also, you could just look at the JSON files: https://github.com/CoolProp/CoolProp/blob/master/dev/mixtures/predefined_mixtures.json

**Comment by emoehr** [comment]
Thanks for your hint. Fluid_names() doesn't seem to work for predefined mixtures:

import CoolProp as CP
AS = CP.AbstractState('HEOS', 'Air.mix')
AS.fluid_names()

AttributeError: 'CoolProp.CoolProp.AbstractState' object has no attribute 'fluid_names'

But as you mentioned I can get it from the JSON file. 

Another question. I'm calculating partial condensation of mixtures and I use REFPROP interface for that.  It seems to work fine and I get new mole fractions for vapor part if the fluid is in a two-phase state (0<Q<1). To do the same with predefined mixtures I have to use HEOS Abstract state. For PT_INPUT corresponding to a two-phase state I get an error:

AS = CP.AbstractState("HEOS", 'Air.mix')
AS.update(CP.PT_INPUTS,1e5,80)

ValueError: Bad phase to solver_rho_Tp_SRK

Do I have to create a REFPROP object (with corresponding components and mole_fractions) if I want to calculate condensation in this case?

Also Vapor quality for a predefined mixture at any PT_INPUTS is Q = -1. What does this mean? And what mean vapor quality Q = 998?

thank you in advance!

**Comment by ibell** [comment]
1) You should upgrade to 6.1.0, that should fix most of these issues.
There are probably still issues with PT flash for mixtures
2) For Q, if Q is in 0 <= Q <= 1, it is two-phase, otherwise, it Q is
undefined for homogeneous phases
3) Do you mean that Q is -1 even when your inputs are two-phase with
predefined mixture?  I find that hard to believe.  Can you please show some
sample code?

**Comment by emoehr** [comment]
1) Yes, I still have 6.0.0, will do upgrade next.
2) ok, just wondered because outside the tho-phase Q is either -1 or 998. I thought may be you distinguish liquid and vapor in this way.
3) No, in the two-phase Q is always between 0 and 1. There it works perfectly fine.
Overall a great Thanks for a wonderful code. It is a pleasure to work with it!

**Comment by ibell** [comment]
If this is a major problem for you, let me know and I can make the mole fractions accessible to you.

**Comment by emoehr** [comment]
This is not a problem now. I just made a copy of a .json file and then create a REFPROP mixture with a corresponding list of fluids and mole fractions. It works perfectly fine in this way.

**Comment by ibell** [comment]
Ok, if it works for you, it works for me.
