### ISSUE TITLE
Add phase specification to high-level interface

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1279]
In the high-level interface there is currently no way to specify the phase of the fluid, which is problematic to say the least.  For instance, just like in refprop, maybe we should allow '<' or '>' to specify liquid or vapor phase respectively.

@jowr - what do you think?  I think this would be useful.

**Comment by henningjp** [comment]
@ibell, I think the beauty of the PropsSI function is its simplicity for high-level interfaces (Excel, MATLAB, Mathcad, etc.).  The '<' and '>' in the REFPROP GUI really specify the upper or lower root when the function is multi-valued, it doesn't really specify phase, and it would require a string parser on the value parameters, which is, I think what the REFPROP interface does.  Most calls to PropsSI are expecting a numeric value.  Placing the '<' and '>' strings on the key (i.e. ">T" or "<T") would be simple enough to parse out, but would be inconsistent with the REFPROP GUI.  Under the hood, the REFPROP flash calculations take an additional parameter (kph or something like that) that allows specification of the upper or lower root.

Perhaps an additional function, PropsSIph("Outkey", "Inkey1", val1, "Inkey2", val2, "fluid", phase).  phase could be a enumerated phase values, which might be hard to translate to the wrappers, or a phase string ("Liquid", "Gas", "Supercritical", etc.).  Unfortunately, most of the wrappers won't allow over-rides, so I think there would have to be a separate function.

**Comment by ibell** [comment]
You are probably right that > or < is not the right solution, but it sure
is simple :) From that standpoint, I might argue for it.

But another (better?) alternative might be to add a phase specification to
one, but only one, of the input variable specifications.  Thus you could do

PropsSI("D","T|liquid",373.15,"P","Water")

or something like that.  The strings would map to phase specification
flags. I like that better than making and supporting yet another high-level
interface function.  Supporting that behaviour ought to be pretty nice
actually.

**Comment by henningjp** [comment]
Yes, I like that better.  Also, it would be dead simple to check for the pipe symbol on th input key strings and parse off the phase string from the input key before any of the processing starts and set iphase accordingly.  This would translate up to all the high-level wrappers, and allows for all six phase strings; not just liquid "<" and vapor ">".

**Comment by ibell** [comment]
Want to implement it?  I think you have the necessary skills and experience
:)

**Comment by henningjp** [comment]
I'll take a crack at it.

**Comment by ibell** [comment]
@henningjp - any progress on this guy?

**Comment by henningjp** [comment]
Little by little.  Time is in short supply.

**Comment by henningjp** [comment]
Yes, I can probably nail it down this weekend.  Was having issues because the strings are passed in as const and I need to modify them.  I think I have it sorted.

**Comment by henningjp** [comment]
OK, @ibell ,
I'm parsing the input key strings beautifully in PropsSI() and calling State->specify_phase() with the stripped off phase, way before the call to update().  However if I do the timing study from the [Low-Level Interface example](http://www.coolprop.org/dev/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface), using a DmolarT input, there is no appreciable difference between calling PropsSI with and without an imposed phase.  Any thoughts?
- Is State->unspecify_phase() getting called somewhere that I don't see and overwriting the phase that I set?
- Is it possible that the overhead in the High-Level interface is overwhelming any phase specification benefit?
```python
In [1]: # Without a phase imposed
In [2]: %timeit CP.PropsSI('H','D',1e-6,'T',300,'Water')
50.2 µs ± 758 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In[3] # With a phase imposed
In[4] %timeit CP.PropsSI('H','D',1e-6,'T|gas',300,'Water')
50.1 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
The standard deviation goes down, but the change in timing is within the standard deviation.

**Comment by henningjp** [comment]
@ibell , So this is interesting.  On my Windows 10 machine running Anaconda Python 3.6, there no longer appears to be any benefit to specifying phase using the Low-Level Interface.

```python
# PHASE NOT IMPOSED
In [1]: HEOS.specify_phase(CoolProp.iphase_not_imposed)

In[2]: %timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.32 µs ± 16.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [3]: %timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.32 µs ± 31.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.33 µs ± 9.63 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

# GAS PHASE IMPOSED
In [5]: HEOS.specify_phase(CoolProp.iphase_gas)

In [6]: %timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.29 µs ± 29 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [7]: %timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.31 µs ± 21.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [8]: %timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.3 µs ± 24.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

As well, the PropsSI() routine takes over 10X longer(!) than the Low-Level call to update, so even the 6% improvement seen before in the Low-Level Interface by specifying phase, would be only 0.6% improvement using the High-Level PropsSI() call.

Am I doing something wrong here, or is specifying phase in PropsSI() just not worth implementing?

**Comment by ibell** [comment]
The specification of the phase has a two-part benefit:
1) In some cases, (e.g., for TP inputs) the phase specification helps to
get guess values more easily.  If TD is provided, DON'T ever do the
saturation state call.
2) Also, sometimes, the phase specification is totally necessary, for
instance if you provide a T,P state that corresponds to saturation state,
and you can specify whether you want the liquid or gas solution
(particularly important for REFPROP)

I would stay it is still needed in PropsSI!

**Comment by henningjp** [comment]
OK.  Two PRs this week.  One to update the PropsSI code and one to update the Docs on how to specify phase using the high-level interface.

It still looks like something changed after 6.1.0 on the low-level update timing.
```python
# CoolProp 6.1.0 on Python 2.7
CoolProp.__version__
Out[2]: u'6.1.0'

HEOS = CoolProp.AbstractState("HEOS", "Water")

%timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
The slowest run took 4931.94 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.16 µs per loop

HEOS.specify_phase(CoolProp.iphase_gas)

%timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
100000 loops, best of 3: 6.26 µs per loop
```
Timing improves in CoolProp 6.1.0 by ~20% when phase is specified.  Using the most recent nightly buld (6.1.1dev), it does not:
```python
# CoolProp 6.1.1dev on Python 2.7
CoolProp.__version__
Out[2]: u'6.1.1dev'

HEOS = CoolProp.AbstractState("HEOS", "Water")

%timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
The slowest run took 8.40 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.19 µs per loop

HEOS.specify_phase(CoolProp.iphase_gas)

%timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
The slowest run took 4.88 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.19 µs per loop
```

The good news is that, even though the timing doesn't change in 6.1.1dev when phase is imposed, on Python 3.6, the timing on both cases is faster than 6.1.0 with phase specified (either Python 2.7 or 3.6).

```python
# CoolProp 6.1.1dev on Python 3.6
HEOS = CoolProp.AbstractState("HEOS", "Water")

%timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.32 µs ± 27.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

HEOS.specify_phase(CoolProp.iphase_gas)

%timeit HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300)
4.33 µs ± 28.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Might need to update the low-level docs as well, since it makes a case for specifying phase being faster.  Per your comment above, that's not the only reason for doing it.
