### ISSUE TITLE
Enthalpy for air in kJ/kg

### ISSUE THREAD

**Issue by poulmack** [CoolProp/CoolProp#1291]
Hi,

I have a tabulated value of h=290.16 kJ/kg for T=290 K based in Thermodynamics of Cengel.
I entered the code: h= PropsSI("Hmass","T",290,"P",101325,"Air"), and I have 416 kJ/kg.

Do you know what is wrong with the code or something that I need to consider.

Thanks.

**Comment by jowr** [comment]
Could this be related to https://github.com/CoolProp/CoolProp/blob/master/FAQ.md ?

**Comment by ibell** [comment]
Yes, that is 100% the problem.  I tried to reply to this issue, but for some reason github didn't post my message.

**Comment by ibell** [comment]
See https://github.com/CoolProp/CoolProp/blob/master/FAQ.md .  Never
compare absolute enthalpies, always differences.

**Comment by poulmack** [comment]
It is weird because sometimes is necessary to have the enthalpy for a specific point (T, P), not always the difference.
Thank you anyway.

**Comment by ibell** [comment]
The point is that you always need to consider whether two literature
sources use the same reference state for enthalpy and entropy.  If they do
not, you should not be comparing the values directly to each other.  If
they do, you should be able to compare them directly.  We have as much as
possible tried to use the same reference state as for NIST REFPROP.
