### ISSUE TITLE
HAPropsSI H, p, W lookups not working past 5.0.0

### ISSUE THREAD

**Issue by milesabarr** [CoolProp/CoolProp#1298]
I am working in Python 2.7, and the following code will not work for CoolProp past version 5.0.0 (I have tried 5.1.2, 6.0.0, and the current development version, which I think is 6.1.1):

```
from CoolProp.CoolProp import HAPropsSI

W1 = 0.05
T1 = 400.0
p1 = 18e5
R1 = HAPropsSI("R", "T", T1, "P", p1, "W", W1)
h1 = HAPropsSI("H", "T", T1, "P", p1, "W", W1)

h2 = h1 - 10000
R2 = HAPropsSI("R", "H", h2, "P", p1, "W", W1)
```

**Comment by milesabarr** [comment]
``

**Comment by ibell** [comment]
Umm, is this still a problem?  The issue is now closed..

**Comment by milesabarr** [comment]
Hah, I didn't mean to close it? I wonder how that happened.

**Comment by ibell** [comment]
What error do you get?

**Comment by milesabarr** [comment]
When I run that exact code in the console I get:

Traceback (most recent call last):

  File "<ipython-input-2-b0d2ad80f734>", line 10, in <module>
    R2 = HAPropsSI("R", "H", h2, "P", p1, "W", W1)

  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4954)

  File "CoolProp\HumidAirProp.pyx", line 47, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:3582)

ValueError: Inputs in Brent [150.000000,350.000000] do not bracket the root.  Function values are [-1.000000,-0.675160] :: inputs were:"R","H",2.5197399766069371e+05,"P",1.8000000000000000e+06,"W",5.0000000000000003e-02

**Comment by ibell** [comment]
Why must everyone insist on such horrible inputs in the psychrometric routines ? :)

**Comment by milesabarr** [comment]
Would you advise different inputs when doing 1D CFD + heat transfer of humid air? P-h is a must (or P-u), then I use constant W until water starts to condense (R=1), at which point I switch to P-h-R.

**Comment by ibell** [comment]
The point is only that the model is based on T(drybulb), psi_w as independent variables, and you have provided only one that can be trivially converted to the independent variables. I'll fix this though.
