### ISSUE TITLE
Android Wrapper

### ISSUE THREAD

**Issue by ARASHKASHANI** [CoolProp/CoolProp#1314]
Hi,

I want to use CoolProp on Android Studio and followed the stepped for using Android Wrapper as explained here:  " http://www.coolprop.org/dev/coolprop/wrappers/Android/index.html ".

I installed 7zip, MinGW, git and cmake as instructed and added them to the path.

when I try to execute:

cmake .. -DCOOLPROP_ANDROID_MODULE=ON -DNDK_PATH=~/Downloads/android-ndk-r13b

from the command line, I receive this Error message:

-- COOLPROP_INSTALL_PREFIX=C:/Users/arash/Desktop/CoolProp/install_root
-- CoolProp version: 6.1.1dev
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindSWIG.cmake:75 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:968 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "C:/Users/arash/Desktop/CoolProp/build/CMakeFiles/CMakeOutput.log".

I have no idea what SWIG is? Do you have any fix for this?

**Comment by ibell** [comment]
You can get swig here: http://www.swig.org/download.html .  Download,
expand the zip, put the files somewhere like c:/swig, then add that
directory to your path.  Sorry I had forgotten about the swig dependency

FYI, there is possibly a compatibility problem with the r13b SDK, you might
need to use version 10

**Comment by ARASHKASHANI** [comment]
Thanks for your prompt reply. I downloaded swig and added to my system path. I also downloaded android-ndk-r10e, now when I try to run the first command from cmd:

" cmake .. -DCOOLPROP_ANDROID_MODULE=ON -G "MinGW Makefiles" -DNDK_PATH=c:/Downloads/android-ndk-r10e "

I get this error:

" CMake Error: The source directory "C:/Users/arash" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI. "

note:  android-ndk-r10e is saved in c:\Downloads folder on my system

**Comment by ibell** [comment]
The .. says that the root of CoolProp is one directory up, make sure that
path is correct.  That command assumes you are in the build directory
relative to CMakeLists.txt

**Comment by ARASHKASHANI** [comment]
Thanks again, I think I finally managed to do it.

here are a suggestions for the Android Wrapper webpage to avoid confusion.

1- add comment that you need to install Anaconda (python 2.7) and not version 3.0
2- download SWIG from swig website and add it the path. Note: there are two options for download. windows user should download swig for windows which includes a pre-built executable.
3- for windows users, the command "cmake .. -DCOOLPROP_ANDROID_MODULE=ON -G "MinGW Makefiles" -DNDK_PATH=c:/Downloads/android-ndk-r10e" should replace "cmake .. -DCOOLPROP_ANDROID_MODULE=ON -DNDK_PATH=~/Downloads/android-ndk-r10e"

I hope my comments are helpful

**Comment by ibell** [comment]
1) What didn't work for you when you were using python 3.x?  That's a bug that we need to fix.
2) I'll update the docs
3) Also, good catch, I'll add a check to compilation and also a note to the docs.

Do you know how to do pull requests on github?  I'd be happy to have you update the docs and get  credit for that.

**Comment by ARASHKASHANI** [comment]
I don't remember. There was an error complaining about python version, so I uninstalled version 3. I finally managed to compile and make java and .so files; but cmake issued some warnings. I still have problems using the compiled files in Android Studio.

I am trying to implement the Android version of StateCalc using the Coolprop engine.

I'll post the warnings I received with cmake and other problems faced in Android Studio to see if you have a dlfix for it. It could be helpful for others who are going the same path.

Ps- as you said there were compability issues with  android-ndk-13b.

**Comment by ARASHKASHANI** [comment]
list of warnings in cmake:

C:\CoolProp\include\Configuration.h(83) : Warning 503: Can't wrap 'operator bool' unless renamed to a valid identifier.
C:\CoolProp\include\Configuration.h(85) : Warning 503: Can't wrap 'operator double' unless renamed to a valid identifier.
C:\CoolProp\include\Configuration.h(87) : Warning 503: Can't wrap 'operator std::string' unless renamed to a valid identifier.
C:\CoolProp\include\Configuration.h(107) : Warning 516: Overloaded method CoolProp::ConfigurationItem::ConfigurationItem(configuration
_keys,std::string const &) ignored,
C:\CoolProp\include\Configuration.h(103) : Warning 516: using CoolProp::ConfigurationItem::ConfigurationItem(configuration_keys,char c
onst *) instead.



C:/Downloads/android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/src/chrono.cpp:125:2: warning: #warning According to unistd.h, there
is no monotonic clock on this system so we are falling back to std::system_clock (which may not be monotonic, and therefore may not be
 conforming). [-Wcpp]
 #warning According to unistd.h, there is no monotonic clock on this system so \

C:/Downloads/android-ndk-r10e/sources/cxx-stl/llvm-libc++/../llvm-libc++abi/libcxxabi/src/cxa_handlers.cpp:105:24: warning: '__cxa_new
_handler' initialized and declared 'extern' [enabled by default]
 extern "C" new_handler __cxa_new_handler = 0;
                        ^


* I don't see the java package folder  build\com\example\myprogram in CoolProp\build folder. However there is a CoolProp folder within build that contains .java files. I copied these files to my android project.

* I also created the jniLibs folder in main folder, and then copied armeabi that has .so library.

when I try to compile the android project it crashes and gives me this message:

"installation failed with message INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=113. it is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!"

reinstalling the application doesn't help though. it almost crashes instantly when I press the Run button in AStudio.

**Comment by ibell** [comment]
Perhaps @sabatind can comment here?  I'm not an android developer...

**Comment by ibell** [comment]
See updated docs: efeef8e286671c3556a705317635a7ddd87ac12c

**Comment by ARASHKASHANI** [comment]
ok, I could finally make it run under Linux. the only problem is the .so library is compiled for arm architecture. Is there any way I can compile that for intel so that I can use the Android Emulator ?

**Comment by ibell** [comment]
No idea.  Did you have to do anything special to get it working on linux?

**Comment by ARASHKASHANI** [comment]
No I just followed the instructions and it worked when the phone is connected to the pc ( it doesn't work on emulator with linux). I couldn't figure out why it crashes constantly on windows.

**Comment by ibell** [comment]
I'm going to close this issue for now...
