### ISSUE TITLE
Loading HMX.BNC through the DLL yields weird behavior

### ISSUE THREAD

**Issue by ianhbell** [CoolProp/CoolProp#1317]
- [ ] The ``OVERWRITE_DEPARTURE_FUNCTIONS`` flag seems to be ignored
- [ ] You have to unload the DLL to have it use the new departure functions set in set_departure_functions

Some caching problem probably.

**Comment by ibell** [comment]
Closed by d5ab63ea299fc35a8706792139888033bff0a3da
