### ISSUE TITLE
Figure out problem with linux wheels

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1324]
@jowr - if you had some time to look into this issue I would appreciate it.  For the last release, 6.1.0, the upload of python binaries to pypi failed, causing #1309.  If you look at the log, you see that it rejected this file: 
```
---------------------------------------------------
Detected full release, uploading the python binaries to pypi
---------------------------------------------------
Uploading distributions to https://pypi.python.org/pypi
Uploading CoolProp-6.1.0-cp27-cp27m-linux_i686.manylinux1__i686.whl
HTTPError: 400 Client Error: Binary wheel for an unsupported platform
~/buildbot/CoolProp.git/dev/buildbot/master
~/buildbot/server-master/public_html ~/buildbot/CoolProp.git/dev/buildbot/master
```

Full log here: http://www.coolprop.dreamhosters.com:8010/builders/release%20version/builds/26/steps/MasterShellCommand/logs/stdio

**Comment by jowr** [comment]
I have no idea. Just tried to have a quick look, but cannot find anything that looks wrong.

**Comment by ibell** [comment]
Yeah, these pip/pypi guys are CONSTANTLY changing things, so its a perpetually moving target.  Perhaps we need to update pip on the linux builder?  Maybe we might want to try to upload to the test pypi server: https://testpypi.python.org/pypi to double check what is going on.

**Comment by ibell** [comment]
This seems to be the problem: https://github.com/pypa/manylinux/issues/66 .  Can you perhaps try to update the docker container for future builds?

**Comment by ibell** [comment]
Aha, only the i686 builds are a problem, the 64-bit builds seem fine.  Can you perhaps kill them?  I think that should solve this problem

**Comment by jowr** [comment]
I can try, but I think I updated the docker containers recently

**Comment by ibell** [comment]
Hmm, I guess killing the 32-bit builds might not be the end of the world.  If you could confirm that the builds can be uploaded to testpypi, we can keep them I guess.  I think auditwheel is not renaming them properly.  I guess we could fix that...

**Comment by ibell** [comment]
I couldn't figure out how to do that, otherwise I would have tried myself.

**Comment by ibell** [comment]
Thank you @jowr - seems like everything is good again!
