### ISSUE TITLE
Mathcad Wrapper Error Messages

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1326]
### Mathcad Wrapper Enhancements Needed
- [ ] Need to catch thrown exceptions, scan the error, and generate a _proper_ Mathcad error message that will pop-up in the Mathcad (15 and Prime) interfaces; instead of just returning no result.  Possible error messages:
    - Temperature Out of Range
    - Pressure Out of Range
    - Inputs Out of Range
    - Input Pair Unimplemented
    - Output Variable Unimplemented
    - Convergence Failure

**Comment by ibell** [comment]
Umm..  That might be a hard problem.  Can you not just spit out the exception message from CoolProp?  At one point the idea was to make the exception families in CoolProp each have their own unique identifier (so they could be interrogated like you describe), and we made some progress on that, but never took it to its logical conclusion.

**Comment by henningjp** [comment]
No.  Error messages have to be registered when the DLL loads.  They are not dynamic.
It's not a problem, though.  I did this for the IF97 wrapper, but need to implement it for the CoolProp wrapper.  This was just a placeholder issue for me.  No worries.
