### ISSUE TITLE
PropsSI failure - Mach number for two phase N2

### ISSUE THREAD

**Issue by iainwaugh** [CoolProp/CoolProp#1332]
When running for Mach number for Nitrogen in the two phase region PropsSI bombs out, using the Python interface and CoolProp 6.1.0 installed using pip on Ubuntu 14.04.

ValueError: PropsSI failed ungracefully :: inputs were:"A","P",3.7076644980269094e+05,"H",-9.2855308140264679e+04,"N2"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

Mach number is not so important in this part of the two phase region for what I'm doing but it would be great if it doesn't bomb out.

CoolProp is awesome, keep up the good work. Thanks

**Comment by ibell** [comment]
Short answer: speed of sound is not defined for two-phase states, but this looks like a failure of a flash routine, not a speed-of-sound issue.

Longer answer: if you care about speed at all, you should be using the low-level interface

**Comment by iainwaugh** [comment]
Thanks for the quick reply. The Mach number returns without failure in other parts of the two-phase region. What then is the physical meaning of this number, if the Mach number is not defined in the two-phase region? 

For working out the speed of sound of the gaseous part of a two phase flow (and therefore whether it is close to choking), would there be a better function call to make? Computational speed is not important for this application if that helps.

**Comment by ibell** [comment]
Umm, not sure what to say here.  There are all kinds of ways of thinking about speed of sound in two-phase mixtures, but the general answer is any kind of mixture speed of sound will always be a sort of vapor-quality weighted speed of sound.  Actually in a two-phase mixture each phase (liquid and vapor) has a unique speed of sound.  Probably we should error out if the state is two-phase and a speed of sound is desired.  In any case, the problem you are having doesn't have a clear answer, so I am going to close this issue.
