### ISSUE TITLE
Dymola with CoolProp and RefProp

### ISSUE THREAD

**Issue by sgomezalaez** [CoolProp/CoolProp#1344]
Good afternoon,
I am trying to connect RefProp with CoolProp in Dymola. To do that, I am using ExternalMedia, which allows me to use FluidProp (with its library  and RefProp) and CoolProp (with its database). However, my purpose is to connect RefProp with CoolProp. Is it possible? What should I write in that case? Thank you in advance.

**Comment by ibell** [comment]
Umm...  Not sure I understand.  It's entirely possible to use REFPROP through ExternalMedia, or at least I know it **was** possible.  Have you tried to file an issue against ExternalMedia repo?  And perhaps search the ExternalMedia samples for REFPROP?

@jowr? @JonWel?

**Comment by sgomezalaez** [comment]
I know it is possible to use RefProp through ExternalMedia, and I have managed to do so by using the command the following command:
  
_extends ExternalMedia.Media.FluidPropMedium(mediumName="Heptane", libraryName="FluidProp.RefProp", substanceNames={"n-Heptane"});_


With this command I use the FluidProp library (StanMix):
  _extends ExternalMedia.Media.FluidPropMedium(mediumName="Heptane", libraryName="FluidProp.StanMix", substanceNames={"n-Heptane"});_

And with this last one, I use CoolProp:
_extends ExternalMedia.Media.CoolPropMedium(mediumName="n-Heptane",
  substanceNames={"n-Heptane|enable_TTSE=1"},
  ThermoStates=Modelica.Media.Interfaces.PartialMedium.Choices.IndependentVariables.ph);_
 
My question is: is it possible to use the command ExternalMedia.Media.CoolPropMedium to use the library of RefProp? If it's possible, how can I do that? Thank you very much.

**Comment by JonWel** [comment]
Which version of ExternalMedia are you using?
I think the release version using `CoolProp 4` do not have this ability, but the [development one](https://github.com/CoolProp/ExternalMedia) using current CoolProp version should be able to call RefProp if you specify `libraryName="REFPROP"` (and that CoolProp can call REFPROP without any need to specify it's path).

Be aware that the rhosmoothing options do not currently work with tabular backend in this ExternalMedia version.

If you have issues with [this specific ExternalMedia](https://github.com/CoolProp/ExternalMedia) version (the one of the GitHub), don't hesitate to fill an issue directly in [it's GitHub](https://github.com/CoolProp/ExternalMedia/issues).

**Comment by ibell** [comment]
This issue pertains to ExternalMedia, not CoolProp, and the issues should be filed there.
