### ISSUE TITLE
Linking CoolProp with a MEX file

### ISSUE THREAD

**Issue by badkoubeh** [CoolProp/CoolProp#1349]
Hello Ian,

I am going to generate a mex file from my MATLAB code to reduce run time and I use CoolProp MATLAB wrapper in my code. MATLAB constantly gives me an error while converting my code to mex because of using CoolProp. My question is how I can generate a mex file from my code in MATLAB. In other words, just wondering how I can use the original CoolProp C++ codes in my MATLAB codes.

Thank you for your help in advance.

Babak

**Comment by ibell** [comment]
Short answer, compile CoolProp into a static library, link with your Mex
source.  It will be painful though since you need to make lots of things
match.

Long answer, don't use MATLAB, use python.  Sooooooo much better
integration with c/c++.

**Comment by ibell** [comment]
Bump.

**Comment by JonWel** [comment]
@badkoubeh [This Matlab Help](http://de.mathworks.com/help/simulink/slref/coder.ceval.html) and the issue #946 may be of some help to create your MEX file.

**Comment by badkoubeh** [comment]
@JonWel Thank you so much for your comment. I had gave up creating the MEX file but it may be worth trying that again.

**Comment by thorade** [comment]
@badkoubeh Is this still an issue? Did you find a solution that you want to share?

Closing for now, because I think no action from the developers is currently required.
