### ISSUE TITLE
splined properties, _fluid_type and _phase not cleared in AbstractState.h

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1354]
Is there a reason for not adding the splined quantities to the clear() function in the AbstractState.h? I am talking about the changes made in af3107ed by @mikekaganski that set the splined properties and `_fluid_type` and `_phase` in the constructor instead of adding them to `clear()`.

I would propose to make `_rhospline`, `_dsplinedp` and `_dsplinedh` a CachedElement instead of a bool to handle the speed issue and duplicate calculations discussed in #870.

**Comment by ibell** [comment]
Yes this sounds fine with me.  The specified phase should not be reset
though...

**Comment by ibell** [comment]
Go ahead and do this one, it's all yours...
