### ISSUE TITLE
SMath Wrapper refactoring

### ISSUE THREAD

**Issue by dcprojects** [CoolProp/CoolProp#1355]
- [x] upgrade to SMath.Math.IPluginLowLevelEvaluationFast interface;

- [x] add Test folder to store test files;

- [x] code indent;

- [x] review of descriptions in Dynamic Assistant;

- [x] README.md listing available functions;

**Comment by ibell** [comment]
Are you going to do these things?  A PR would of course be appreciated.

**Comment by dcprojects** [comment]
Yes, I'll make a pull request in days.

**Comment by ibell** [comment]
Hmm...  Seems your changes are not backwards compatible: http://www.coolprop.dreamhosters.com:8010/builders/SMath/builds/1058/steps/shell_1/logs/stdio

**Comment by ibell** [comment]
Can you perhaps figure out how to make them backwards compatible?  I can also update my SMath Studio on the build server...

**Comment by dcprojects** [comment]
Currently this code should compile in the latest 2 major relases of SMath Studio and more than 20 minor builds before them (precisely I can compile it from SS 0.98.5973); my suggestion is to update the program on the Build Server.

**Comment by ibell** [comment]
I updated SMath on the build server, works now.
