### ISSUE TITLE
Mixtures in Excel using CoolProp

### ISSUE THREAD

**Issue by IvanCroSk** [CoolProp/CoolProp#1356]
Hi all,

I have one challenge with using CoolProp in Excel 2016, also im very new in the programming so dont have knowledge concerning codes and programming.
I have downloaded the newest version using windows installer (https://sourceforge.net/projects/coolprop/files/CoolProp/6.1.0/Installers/) and everything is working perfect but when i want to calculate mixtures like R407F, R407A, R448A, R449A and other i receive warning. 
For example if i want to calculate density of R407F at some pressure and enthalpy (subcooled liquid):
=Props("D";"P";(EP4*$BX$3);"H";ES4;"HEOS::R407F.mix")
I get this warning:
phase envelope must be built to carry out HSU_P_flash for mixture : PropsSI("D","P",1729632.458,"H",247881.136,"HEOS::R407F.mix")

I have searced on the internet but what i understand i need to build phase envelope somehow :) but not sure how this could be done. 
Also i have try couple times to reinstall CoolProp but didnt achieve anything.

Do you know how or if i can solve this and use CoolProp for mixtures? Is it possible just to add some code lines in xlam file or i need to have new dll file?

Btw this tool is very impressive and we can do everything with this, especially in which im interesting and this is energy analysis, but refrigeration is changing almost on daily basis and there is a lot of new refrigerants.

Thank you very much in advance.

Best regards,
Ivan

**Comment by ibell** [comment]
Ivan,

The bad news is that PH inputs are not supported in the high-level
interface for mixtures (currently).  You will need to either use REFPROP,
or to use the low-level interface and construct a phase envelope.  And that
means you can't use Microsoft Excel, which only allows you to use the
high-level interface.  Python does enable that capability though...
