### ISSUE TITLE
Wrong Entalphy for r1233zd

### ISSUE THREAD

**Issue by janbergland** [CoolProp/CoolProp#1364]
I´m a new user of coolprop inside mathcad. 
When learning and testing different fluids values for some fluids seems correct and some not. I searched old issues and found that SES36 gave wrong Entalphy . For me it still does (around 15% difference). 
A new fluid, r1233zd, also differs
![skarmklipp](https://cloud.githubusercontent.com/assets/24297794/20799832/b686b7f0-b7e3-11e6-8e25-36bb4145b0cd.PNG)
**test** is in refprop and graphics from Honeywell = 262,35 kJ/kg and **test2**=439,95 kJ/kg

I also tested r134a without remarks. 

Are there any selected properties that are harder to calculate? Or do the values differ around 10-15% ?
What accuracy can I expect? It´s good to know when we design processes.

**Comment by ibell** [comment]
See question #1 in the FAQ: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by janbergland** [comment]
Thanx. 
So if I add a constant, offsett the output value, then I can use them. 
Is it the same offsett value for all entalphy calculations or is it variable depending on other parameters?

**Comment by ibell** [comment]
It's a constant offset.  Basically, never compare the enthalpy between two
libraries at a given T,p, always compare the difference in enthalpy between
two state points.  You can also change the reference state:
http://www.coolprop.org/dev/coolprop/HighLevelAPI.html#reference-states
