### ISSUE TITLE
segmentation fault when calling get_global_param_string("REFPROP_version") from Python

### ISSUE THREAD

**Issue by bremme** [CoolProp/CoolProp#1368]
I wanted to get the available REFPROP version by calling `get_global_param_string("REFPROP_version")`. When REFPROP is installed this return the installed version (e.g. 9.1) as expected. But when REFPROP is not installed I get a `segmentation fault`.  I'm using the CoolProp Python wrapper (version 6.1.0) which I installed using pip.

The python code which gives me the `segmentation fault` is:

```python
import CoolProp.CoolProp as cp

cp.get_global_param_string("REFPROP_version")
```

The full output I get in my shell is:

```shell
Good news: It is possible to use REFPROP on your system! However, the library 
could not be loaded. Please make sure that REFPROP is available on your system.

Neither found in current location nor found in system PATH.
If you already obtained a copy of REFPROP from http://www.nist.gov/srd/, 
add location of REFPROP to the PATH environment variable or your library path.

In case you do not use Windows, have a look at https://github.com/jowr/librefprop.so 
to find instructions on how to compile your own version of the REFPROP library.

ALTERNATIVE_REFPROP_PATH: 
[1]    6491 segmentation fault  python test.py
```

I quickly tested if it would make any difference if I do set the `ALTERNATIVE_REFPROP_PATH`, but it didn't, I still got the `segmentation fault`.

Let me know if there is anything more I can do to help solve this issue.

**Comment by ibell** [comment]
That will be a one-liner to fix, basically it should check if the SETUPdll
function is a null pointer, and if it is, not evaluate it.

**Comment by bremme** [comment]
I have not really looked at the `C++` CoolProp sources before but I guess you mean to check for a nullptr just before line 244 of REFPROPMixtureBackend.cpp:

```c++
SETUPdll(&N, fluids, hmx, default_reference_state,
            &ierr, herr,
            10000, // Length of component_string (see PASS_FTN.for from REFPROP)
            refpropcharlength, // Length of path_HMX_BNC
            lengthofreference, // Length of reference
            errormessagelength // Length of error message
            );
```

Do you want me to make a pull request for this, or perhaps its faster if you or one of the other main developers fixes this small bug?

**Comment by ibell** [comment]
I can fix it, but a PR would be awesome.  Just throw a ValueError with the
right comment if SETUPdll == NULL
