### ISSUE TITLE
cair_sat(T) is not documented properly

### ISSUE THREAD

**Issue by DANA-Laboratory** [CoolProp/CoolProp#1379]
It takes me hours to find that `cair_sat()` calculates "Cp" on a constant saturation line, but `hapropssi("Cp")` do it on a constant mole fraction of water, and the results are not the same. IMO it needs more enlightenment, maybe a more clear name, adding comments, tests, or examples help.

**Comment by ibell** [comment]
If you wanted to file a pull request to add docs for cair_sat function, I would be happy for you to do that.

**Comment by DANA-Laboratory** [comment]
Is it pressure independent? or there is a valid range for pressure.

**Comment by ibell** [comment]
Excellent question.  Almost certainly its taken at one atmosphere
