### ISSUE TITLE
Calling acentric factor in cubic equation

### ISSUE THREAD

**Issue by Hans-Herbert** [CoolProp/CoolProp#1380]
I am using the version 6.1.0. I have here a simple example to get the acentric factor from the data of a cubic equation:

import CoolProp.CoolProp as CP, json
fake_fluids = [
                   {
                     "CAS": "109-66-0",
                     "Tc": 469.70,
                     "Tc_units": "K",
                     "acentric": 0.252,
                     "aliases": [
                     ],
                     "molemass": 0.07215,
                     "molemass_units": "kg/mol",
                     "name": "NC5H12",
                     "pc": 3370000.0,
                     "pc_units": "Pa"
                   }
               ]
 
CP.add_fluids_as_JSON("PR", json.dumps(fake_fluids))
fluid = 'PR::NC5H12'
omega  = CP.PropsSI(fluid,'acentric')

The last statement leads to a loop without end. Can someone help me?

Kind regards, Hans-Herbert

**Comment by ibell** [comment]
First please update to the development version.  Do you see the same hang?

**Comment by Hans-Herbert** [comment]
Dear Ian,
I have no knowledge about Pip in Python. For the installation of the develpment version of CoolProp I need the msi-file for Python3.3. The best place is here: https://sourceforge.net/projects/coolprop/files/CoolProp/
Regards, Hans-Herbert

**Comment by ibell** [comment]
You should learn about and use pip - use the second one here:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation

**Comment by Hans-Herbert** [comment]
Hello Ian,
I have tried the automatic installation under Python34. I used the DOS-shell with the long pip install command. But I got the following error message:
error: Microsoft Visual C++ 10.0 is required <unable to find vcvarsall.bat>
I must notice that I have installed Microsoft Visual C++ 2015. Is there a difference?
Regards, Hans-Herbert
