### ISSUE TITLE
Calling acentric factor with cubic equation

### ISSUE THREAD

**Issue by Hans-Herbert** [CoolProp/CoolProp#1381]
Dear Ian,
I think I have erased the old issue. To test the version 6.1.1dev I used the pip command in the DOS-shell for the automatic installation. I got the following error message:
error: Microsoft Visual C++ 10.0 is required <unable to find vcarsall.bat>
I have installed Microsoft Visual C++ 2015. Is there a difference?
Regards, Hans-Herbert

**Comment by Hans-Herbert** [comment]
Hello,
I have successfull installed CoolProp 6.1.1dev with pip and Microsoft Visual Studio 2010. The acentric factor, which is set in the cubic eos, is now zero. There is no hanging of the program, but the value is wrong.
Regards, Hans-Herbert

**Comment by ibell** [comment]
For one, if you run the command given in the documentation
```
pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp
```
that should require no visual studio version to be present.  It uses a precompiled version from the development server.
