### ISSUE TITLE
Errors using CoolProp in Anaconda Sypder

### ISSUE THREAD

**Issue by fwitte** [CoolProp/CoolProp#1386]
Hello,

i am using Spyder 3.0.2 with Python 3.5.2 64bits, Qt 5.6.0, PyQt5 5.6 on Linux and installed CoolProp 6.1.0 via `pip3 install CoolProp`.

Performing
```
from CoolProp.CoolProp import PropsSI
print(PropsSI('T', 'H', 350000, 'P', 1e5, 'H2O'))
```
in the linux terminal works fine, while in the IPython console i get the following error:
```
Exception ignored in: 'CoolProp.CoolProp.iterable'
NameError: name '_numpy_supported' is not defined
Exception ignored in: 'CoolProp.CoolProp.iterable'
NameError: name '_numpy_supported' is not defined
Exception ignored in: 'CoolProp.CoolProp.iterable'
NameError: name '_numpy_supported' is not defined
Traceback (most recent call last):

  File "<ipython-input-4-92e078c81cc6>", line 1, in <module>
    runfile('/home/francesco/Link to Kraftwerkssimulation/Prozesse.py', wdir='/home/francesco/Link to Kraftwerkssimulation')

  File "/home/francesco/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/francesco/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/francesco/Link to Kraftwerkssimulation/Prozesse.py", line 14, in <module>
    print(PropsSI('T', 'H', 350000, 'P', 1e5, 'H2O'))

  File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:41716)

  File "CoolProp/CoolProp.pyx", line 351, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:40719)

NameError: name '_numpy_supported' is not defined
```
I get another error performing
```
import CoolProp
HEOS = CoolProp.AbstractState('HEOS','Water')
HEOS.update(CoolProp.PQ_INPUTS, 101325, 0)
print(HEOS.T())
```
with the IPython console:
```
Traceback (most recent call last):

  File "<ipython-input-7-92e078c81cc6>", line 1, in <module>
    runfile('/home/francesco/Link to Kraftwerkssimulation/Prozesse.py', wdir='/home/francesco/Link to Kraftwerkssimulation')

  File "/home/francesco/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/francesco/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/francesco/Link to Kraftwerkssimulation/Prozesse.py", line 13, in <module>
    import CoolProp

  File "CoolProp/CoolProp.pyx", line 12, in init CoolProp.CoolProp (CoolProp/CoolProp.cpp:54654)

SystemError: Parent module '' not loaded, cannot perform relative import
```
Is there anybody who has come across the same or similar problems, or knows how to fix this?

Thank you very much, greetings from germany
Francesco

**Comment by ibell** [comment]
You should install numpy using your package manager.  It should fail more
elegantly than this, but that should fix this issue.

**Comment by fwitte** [comment]
Thank you for your fast help, unfortunately I have it installed already. For now I will use the terminal to run my code, but still I have no idea why this shouldn't work with Spyder (plus it is more comfortable just pressing F5 to run the code).

**Comment by fwitte** [comment]
I found that Spyder used an old version of numpy. After updating it, the first error does not occur anymore, but running
```
from CoolProp.CoolProp import PropsSI
print(PropsSI('T', 'H', 350000, 'P', 1e5, 'H2O'))
```
results in the same error as above.
`SystemError: Parent module '' not loaded, cannot perform relative import`

**Comment by ibell** [comment]
Hmm.  Can you run your script from the console without spyder without a problem?  I've not had problems like this before, but I wasn't running your combination of programs/platforms/etc.

**Comment by fwitte** [comment]
Yes, that does work. There must be an error while importing the package in Spyder, this weekend I will try to find a solution for that. But maybe there is somebody who came across a similar problem?
Btw. I forgot to mention, I work on Ubuntu 16.04.
Have a nice weekend!

**Comment by thorade** [comment]
Does the problem persist? Did you find a solution?
Closing for now, feel free to reopen.

Here is how most of my Coolprop scripts start. 
Can you run this from the terminal and from spyder and compae the output?
```python
import sys
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

import CoolProp as CP
from CoolProp.CoolProp import PropsSI

# Check the versions
print("      python: {}".format(sys.version))
print("       numpy: {}".format(np.__version__))
print("  matplotlib: {}".format(matplotlib.__version__))
print("    CoolProp: {}".format(CP.__version__))
print("CoolProp git: {}".format(CP.__gitrevision__))

# Now comes the real script...
```

When installing packages on Linux, you will frequently have problems because some packages are installed using the OS package manager, some are installed using pip, some are installed for python2, some installed for python3.
Also read this:
https://docs.python.org/3/installing/
https://docs.python.org/3/installing/#work-with-multiple-versions-of-python-installed-in-parallel

**Comment by fwitte** [comment]
Thanks for your reply, unfortunately I have not found a lot of time to work on this issue, also excuse me for my late answer. In the terminal the code yields:
```
python: 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
       numpy: 1.11.2
  matplotlib: 1.5.3
    CoolProp: 6.1.0
CoolProp git: 7864c2614ce5a0ef972386ee7f39859f0d3f8038
```
In spyder it is the same issue as before:
```
Traceback (most recent call last):

  File "<ipython-input-2-3a5bc37eb6c7>", line 1, in <module>
    runfile('/home/francesco/untitled.py', wdir='/home/francesco')

  File "/home/francesco/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/home/francesco/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/francesco/untitled.py", line 6, in <module>
    import CoolProp as CP

  File "CoolProp/CoolProp.pyx", line 12, in init CoolProp.CoolProp (CoolProp/CoolProp.cpp:54654)

SystemError: Parent module '' not loaded, cannot perform relative import
```
Running the code without the coolprop part results in:
```
python: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
       numpy: 1.11.2
  matplotlib: 1.5.3
```
If I find a solution for my problem, I will post it here. Thanks for your effords, have a nice week.

**Comment by thorade** [comment]
Well, the solution is in the printed result: From the terminal, you are using a different python executable than from spyder (default versus Anaconda custom)

As you are using Python 3.5, you can find out even more about your python executable by running:
```python
from shutil import which
print(which("python"))
```
