### ISSUE TITLE
install error on raspberry pi

### ISSUE THREAD

**Issue by ericksonla** [CoolProp/CoolProp#1387]
I attemped to install CoolProp on a Raspberry Pi 3 (Raspian Jessie) using `pip install CoolProp`. The build failed with the following log:

```
CoolProp/CoolProp.cpp:4:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ce2oI8/CoolProp/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Dp_7du-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-Ce2oI8/CoolProp
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

Any suggestions?

**Comment by ericksonla** [comment]
Well that was quick. The cleanup error was a red herring and the `fatal error: Python.h: No such file or directory` was the real problem. Installing the python dev files and libraries did the trick via `sudo apt-get install python-dev`.

**Comment by ibell** [comment]
How long did it take to compile?  My recollection is that it took quite a
long time.  You could also consider cross-compilation for ARM from linux,
but if it works, no need to do anything too creative.

Ian

**Comment by ericksonla** [comment]
I found the solution and started the build about 5 minutes after I posted the issue and posted the solution as soon as it finished building. According to timestamps on my posts, that would make it about 25 minutes.

**Comment by ibell** [comment]
Cool, yes that was my experience too.  Very slow!  Glad you got it working though.
