### ISSUE TITLE
CoolProp doesn't run on AWS linux server

### ISSUE THREAD

**Issue by ca12ca34** [CoolProp/CoolProp#1388]
CoolProp builds successfully, but matlab doesnt recognize the functions are there

Error: Undefined function 'CoolPropMATLAB_wrap' for input arguments of type 'double'.
          Error Stack: PropsSI (line 2)
                       CoolPropTest (line 17)

[build_log_1_10_17.pdf](https://github.com/CoolProp/CoolProp/files/705038/build_log_1_10_17.pdf)

**Comment by ibell** [comment]
I updated the outputted module.  This might do it: 6e5c6950551e9e1946d41082b15d62e93918832d

You'll need to wait a little bit for the files to get updated on the server

**Comment by ibell** [comment]
Have you had a chance to try with my update?  I think it should fix this issue.

**Comment by ibell** [comment]
Bump.
