### ISSUE TITLE
REFPROP :: No command for calling the Latent Heat of Vaporization?

### ISSUE THREAD

**Issue by sethseth2** [CoolProp/CoolProp#1392]
I can't seem to figure out the proper way to call the Latent Heat of Vaporization through REFPROP. I know REFPROP calculates it, but yeah.

Also, is there a place that has more extensive documentation on all of the commands available to CoolProp?
I have only found the parameter table, but I had to learn from a random example how to get the saturation temperature. It would be nice if someone could point me to a compiled list of commands that PropsSI can do (along with the other stuff as well).

Thanks in advance,
Seth

**Comment by ibell** [comment]
Well, there is no command for latent of vaporization directly, but it is just the difference in enthalpy between vapor and liquid, so it's pretty easy to calculate.  Are you using the high-level or low-level interface to CoolProp?

We have the table for the PropsSI function(http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function) and pretty comprehensive examples for the most commonly needed things.  Have you seen the examples for each of the interfaces?  You might want to read the documentation a bit more deeply, or detailed updates to the docs would also be appreciated (and welcomed)

**Comment by sethseth2** [comment]
right so what T values do you use to let coolprop know youre referring to the boiling zone?  i obviously couldnt use enthalpy at boiling temp - enthalpy at boiling temp. I'm using the high level interface, though i might try to learn the low level soon. 
I've seen that table you linked. Some of the examples aren't labeled too well, and some commands are missing (like latent heat of vaporization) so i wasnt sure if there was more or not. 

-------- Original message --------From: Ian Bell <notifications@github.com> Date: 1/17/17  8:24 PM  (GMT-08:00) To: CoolProp/CoolProp <CoolProp@noreply.github.com> Cc: sethseth2 <seth.m.hilliard1@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CoolProp/CoolProp] REFPROP :: No command for calling the Latent
  Heat of Vaporization? (#1392) 
Well, there is no command for latent of vaporization directly, but it is just the difference in enthalpy between vapor and liquid, so it's pretty easy to calculate.  Are you using the high-level or low-level interface to CoolProp?
We have the table for the PropsSI function(http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function) and pretty comprehensive examples for the most commonly needed things.  Have you seen the examples for each of the interfaces?  You might want to read the documentation a bit more deeply, or detailed updates to the docs would also be appreciated (and welcomed)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CoolProp/CoolProp","title":"CoolProp/CoolProp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CoolProp/CoolProp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ibell in #1392: Well, there is no command for latent of vaporization directly, but it is just the difference in enthalpy between vapor and liquid, so it's pretty easy to calculate.  Are you using the high-level or low-level interface to CoolProp?\r\n\r\nWe have the table for the PropsSI function(http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function) and pretty comprehensive examples for the most commonly needed things.  Have you seen the examples for each of the interfaces?  You might want to read the documentation a bit more deeply, or detailed updates to the docs would also be appreciated (and welcomed)"}],"action":{"name":"View Issue","url":"https://github.com/CoolProp/CoolProp/issues/1392#issuecomment-273379528"}}}

**Comment by ibell** [comment]
Can you please detail which examples are not well labeled and I will fix it?

The latent heat is a function of saturation temperature, and the temperature can be between the triple point temperature and the critical point temperature.

**Comment by henningjp** [comment]
@sethseth2 Maybe this will help.  Materials will boil (vaporize) at any temperature between the triple and critical point provided the pressure is at the saturation pressure.  Saturation pressure versus temperature is the saturation curve.  Below is the saturation curve for water, which will boil anywhere along this curve; even at room temperature if the pressure is low enough.

![saturation curve](https://cloud.githubusercontent.com/assets/17114032/22164312/abcb10f0-df24-11e6-84f9-63abc3c8d656.PNG)

At any temperature, say 550K, on this curve, you can calculate the saturation pressure, P, with:

    P = PropsSI( "P", "T", 550.0, "Q", 0, "REFPROP::Water")  = 6.177E6    {Pa}

Using inputs of T and vapor quality, Q, returns values along the saturation curve.  In this case, Q can be 0 or 1, and CoopProp (REFPROP) will return the same pressure.  

At any saturation point along this curve, your fluid (in this case water) can exist in two states, Vapor (Q = 1) or Liquid (Q = 0).  The enthalpy of the vapor is higher than the enthalpy of the liquid by the ``heat of vaporization``.  To calculate these values at any **_temp_** along the saturation curve, you can use:

    H_vapor  = PropsSI("H", "T", temp, "Q", 1, "REFPROP::Water")  
    H_liquid = PropsSI("H", "T", temp, "Q", 0, "REFPROP::Water")
    dHvap    = H_vapor  -  H_liquid 

Hope this helps.

**Comment by sethseth2** [comment]
@henningjp thanks a ton, that helps a lot. I had no idea that "Q" was referring to the state of the fluid. So just to clarify, if I know the pressure of the system I can use CoolProp to find the saturation temperature by using `T = PropsSI( "T", "P", 300.0, "Q", 0, "REFPROP::Water") = whatever {K}?` and then use T as my argument for the enthalpy calculation? (so instead of where you wrote temp, I would write T)

**Comment by henningjp** [comment]
@sethseth2  Right.  That will work.

But, if you already know the saturation pressure, you can call for the saturation Enthalpy directly using the saturation pressure (pval) and vapor quality (1 or 0) as well:

    h_vapor  = PropsSI("H", "P", pval, "Q", 1, "REFPROP::Water")
    h_liquid = PropsSI("H", "P", pval, "Q", 0, "REFPROP::Water")
    dHvap    = H_vapor - H_liquid

No need to calculate the saturation temperature unless you need it for something else.

**Comment by sethseth2** [comment]
oh awesome, that makes sense. You've been a ton of help, thanks a lot!

**Comment by henningjp** [comment]
Can you close this issue?
