### ISSUE TITLE
feature-request: reference_state-setting directly in AbstractState

### ISSUE THREAD

**Issue by tobias-loew** [CoolProp/CoolProp#1398]
Currently reference-states can only be set using static calls. This is problematic in a multi-threaded environment. Thus non-static functions set_reference_state[D|S] in AbstractState would be handy.

**Comment by ibell** [comment]
Good idea!  Feel free to fire off a pull request.  I'm no longer actively developing CoolProp (https://groups.google.com/forum/#!topic/coolprop-users/uyhIMHmaoko) but you have the necessary skills to figure that out!  I can accept your pull request when it's ready.

In general, setting the reference states at the beginning before you fork threads is the right approach, and should in general be thread-safe.
