### ISSUE TITLE
Labview wrapper calculates SES36 props wrong

### ISSUE THREAD

**Issue by alihankaya** [CoolProp/CoolProp#1401]
Dear all,
I've realized that there is a big discrepancy between the Solvay values (http://www.solvay.com/en/binaries/SOLKATHERM-SES36-Product-Information-180412.pdf) and the values that I get via Labview wrapper I downloaded on 25/01/2017. The problem is in enthalpy and entropy calculations. They are much lower. For example:

T=100 °C, Q=0, input=TQ and I get: 
Enthalpy=107.527 kJ/kg (311.440 kJ/kg in the datasheet)
Entropy=0.2796 kJ/kgK (1.3364 kJ/kgK in the datasheet)

The same behavior is observable in higher and lower temperatures as well. I saw that a similar problem existed for other wrappers (https://github.com/CoolProp/CoolProp/issues/842). I'd be very happy if you could enlighten me about this issue. 

Thank you and kind regards,
Alihan

**Comment by ibell** [comment]
See FAQ: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md point
number 1

But, you should know that there is in general a fairly large difference in
latent heat between Solvay's model and CoolProp's model.  Without more
experiments it is hard to know which model is actually correct.

**Comment by thorade** [comment]
I extended the FAQ to also mention reference states

**Comment by alihankaya** [comment]
Thank you for your reply!
