### ISSUE TITLE
Cannot Import CoolProp in Spyder 3.0.0

### ISSUE THREAD

**Issue by khdang178** [CoolProp/CoolProp#1404]
Hello,

I've downloaded and installed CoolProp 6.1.0 for Python 3.5, but could not import it in Spyder 3.0.0

The error is 
![coolprop_error](https://cloud.githubusercontent.com/assets/7884391/22353245/94c9c02c-e3ed-11e6-938d-5239de12f00e.PNG)

Could anyone please help me with this issue?

Many thanks

**Comment by thorade** [comment]
How did you download and install it? 
It works for me by just runnning 
`pip install --upgrade coolprop` 
or alternatively 
`python -m pip install --upgrade coolprop` 
from a python enabled command prompt.
Closing for now, fell free to reopen if the problem persists.
