### ISSUE TITLE
StateContainer print fails

### ISSUE THREAD

**Issue by d-e-t** [CoolProp/CoolProp#1406]
Trying to run the StateContainer example from the SimpleCycles documentation at:
http://www.coolprop.org/apidoc/CoolProp.Plots.SimpleCycles.html#CoolProp.Plots.SimpleCycles.StatePoint

`print(cycle_states) `
fails with 
TypeError: __str__ returned non-string (type bytes)

**Comment by jowr** [comment]
That looks like a Python v2 vs v3 issue. Which Python version and distribution are you using?

**Comment by jowr** [comment]
Hi, does `print(str(cycle_states))` work for you?

**Comment by d-e-t** [comment]
`print(str(cycle_states))` fails with the same error.

I'm using Python 3.5.2 with the Anaconda 4.2.0 (64-bit) distribution.  Sorry for not responding earlier...

**Comment by kj1976a** [comment]
hello, same problem for me 
configuration
mac os 10.10
conda 4.3.15
python 3.5

**Comment by kj1976a** [comment]
hi, 
i'm still trying to figure out what's wrong ... 
weirdly enough if i take the __str__ method from StateContainer, reproduce it and apply it to cycle_states, i get an output ...

**Comment by kj1976a** [comment]
i also installed python 2.7 via anaconda and coolprop 6.0.1 
this time the example works like a charm

**Comment by ibell** [comment]
I'm sure the problem is quite easy to fix.  Sounds like a simple python2/3
compatibility problem.

**Comment by d-e-t** [comment]
This works fine for me with python2.7

**Comment by ibell** [comment]
Yes, the issue is with python 3.x

**Comment by thorade** [comment]
I have a rather radical opinion on these Py2 versus 3 issues: 
- Python 3 is better, and it is the future. 
- Python 3 is more powerful, and more strict (in a helpful way).
- All (new) code should be developed and tested on Python 3.
- Backporting Py3 code to Py2 is easier than the other way round: just write clean Py3 code and then make it work in Py2 by importing from future
    - http://python-future.org/quickstart.html#to-convert-existing-python-3-code
    - https://www.digitalocean.com/community/tutorials/how-to-port-python-2-code-to-python-3
    - http://python-future.org/compatible_idioms.html

One of the major changes between Python 2 and 3 was that in Py3 all strings are utf-8, and to me it seems to be the cleanest solution to add `from __future__ import unicode_literals` to all files and then change the code until it works.

**Comment by henningjp** [comment]
In addition to the fact that Python 2.7 requires VC9 on Windows, which has become all but extinct.

**Comment by ibell** [comment]
Add to that that VC9 doesn't support C++11; that's been holding me back
from a number of things that I'd like to do in the guts of CoolProp.
