### ISSUE TITLE
Mixture Calculation Confuse

### ISSUE THREAD

**Issue by learnweierstrass** [CoolProp/CoolProp#1409]
if we want to get the  enthaly of LiBr atT=333.15K, P=3703.05299Pa at equilibrium state, we first get the massfraction of the solution(lots of empirical formulae) w=0.548982, but we can't put w straight into the PropsSI like this CoolProp.PropsSI('H','T',333.15,'P',3703.05299,'INCOMP::LiBr[w]')

the only way is CoolProp.PropsSI('H','T',333.15,'P',3703.05299,'INCOMP::LiBr[0.548982]')
often in the iteration process, we cannot type in 0.548982 in the iteration everytime. how can we solve this problem? @ibell

**Comment by learnweierstrass** [comment]
The question has been solved.  the string catenating method should be applied.
Sorry to disturb you

**Comment by thorade** [comment]
@learnweierstrass No need to say sorry, filing an issue is not considered a disturbance.
It would be great if you could add the solution you found to help others,
and please close your issues once you feel a solution has been found
(this time I will close it for you).
