### ISSUE TITLE
MATLAB - Nitrous Oxide Enthalpys Appear to Call Heat of Vaporization

### ISSUE THREAD

**Issue by BStricklin** [CoolProp/CoolProp#1410]
When CoolProp.PropsSI is used in MATLAB to call for the enthalpy properties of nitrous oxide, the function returns the heat of vaporization multiplied by the quality. That is the program

Tcrit = 184.6839;
Hl = CoolProp.PropsSI('H','T',Tcrit,'Q',0,fluid)
Hg = CoolProp.PropsSI('H','T',Tcrit,'Q',1,fluid)

will yield an Hl value of -2.8324*10^-6 and an Hg value of 3.7428*10^5. I believe this is a mistake in the code where the enthalpy of the liquid was not added to the final value and thus you only get the heat of vaporization.

**Comment by ibell** [comment]
Hi! In general it is helpful if you provide runnable code.  I don't know
what is in the fluid variable.

In general, there is nothing wrong here.  Here is my output:

Hl: -0.03289509945
Hg: 374281.644699
hfg: 374281.677594

Below is my python code:

from __future__ import print_function
import CoolProp.CoolProp as CP

Tcrit = 184.6839;
fluid = 'N2O'
Hl = CP.PropsSI('H','T',Tcrit,'Q',0,fluid) # Saturated liquid enthalpy
Hg = CP.PropsSI('H','T',Tcrit,'Q',1,fluid) # Saturated vapor enthalpy
print('Hl:', Hl)
print('Hg:', Hg)
print('hfg:', Hg-Hl)

**Comment by BStricklin** [comment]
Hi Ian, forgive me for forgetting to include 

fluid = 'N2O'

As for the output, your code is supposed to give enthalpy, not just heat of vaporization, correct? If that's the case, then according to the tables I've seen the output should yield

Hl: -470
Hg: -95.4
Hfg: 375

If I have misinterpreted something here then I apologize, but please let me know. Thank you

**Comment by ibell** [comment]
Ah, yes, the classic reference state question: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

Also, all inputs/outputs in PropsSI are BASE SI (J, kg, mol, Pa, etc.).  Please always provide units.
