### ISSUE TITLE
trouble cloning repo recursively (cannot find commit hash in 'externals/Eigen')

### ISSUE THREAD

**Issue by hennink** [CoolProp/CoolProp#1411]
I'm trying to follow [these instructions](http://www.coolprop.org/coolprop/wrappers/FORTRAN/index.html#fortran) for the Fortran wrapper, but I'm running into difficulties.

First, I get an error when cloning the CoolProp repository recursively:

```
$ git clone https://github.com/CoolProp/CoolProp --recursive
... 
<lots of output>
...
Submodule path 'externals/rapidjson/thirdparty/gtest': checked out '0476e154db5fab1721c2a0f32abf4aa773679b52'
Unable to checkout 'cc4a1cdf9e2545c488d3d4074d71a896134cda10' in submodule path 'externals/Eigen'
```

Then, after the steps

```
mkdir build && cd build
mkdir gccstatic && cd gccstatic
cmake ../..  -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_EXTERNC_LIBRARY=ON -DCMAKE_VERBOSE_MAKEFILE=ON
cmake --build .
```

I get:

```
...
<lost of output>
...
/home/aldohennink/CoolProp/include/Helmholtz.h:7:22: fatal error: Eigen/Core: No such file or directory
 #include "Eigen/Core"
                      ^
compilation terminated.
gmake[2]: *** [CMakeFiles/CoolProp.dir/src/AbstractState.cpp.o] Error 1
gmake[2]: Leaving directory `/home/aldohennink/CoolProp/build/gccstatic'
gmake[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
gmake[1]: Leaving directory `/home/aldohennink/CoolProp/build/gccstatic'
gmake: *** [all] Error 2
```

In case it's relevant, here is my specific situation:
* My Fortran code has to be compiled with Intel's ifort (16.0.3), not gfortran.
* I have both Intel's icc and icpc compilers (version 16.0.3) and GNU's gfortran and g++ and gcc (version 4.8.3).
* I have "CentOS Linux release 7.1.1503 (Core)".

**Comment by ibell** [comment]
Yes, I have noticed this too with another project I work on.  What we need
to do is to bump the revision for Eigen, which should fix this.  Do you
know how to do that and file a PR for that?

**Comment by hennink** [comment]
No, I'm afraid I don't know what it means to 'bump a revision' or 'file a PR', sorry.

**Comment by henningjp** [comment]
Hmmm.  I'd like to know how to do this.  Can you post?  Good topic for the Wiki.

**Comment by otbu** [comment]
I managed to get it working. The .gitmodules files will need to manually edited. This is one solution at least.

    [submodule "externals/Eigen"]
        path = externals/Eigen
        url = https://github.com/RLovelett/eigen.git
        branch = branches/3.3

I chose the "branches/3.3" branch. Perhaps master is better? This can be done for the other submodules as well (not sure if necessary).

Then i did:

    $ git submodule update --init --remote

I got all the submodules checked out.

Before all this, you can reset submodules in externals subdir with (maybe good to do if you previously had problems):

    $ git submodule deinit --all --force

Hope it works.

**Comment by thorade** [comment]
@hennink 
bump a revision means changing the version number and nothing else, so that other tools think an update is available and try to install it
file a PR means to create a Pull Request on github
https://github.com/CoolProp/CoolProp/pulls
https://help.github.com/articles/about-pull-requests/

And as the wiki was mentioned, it is here:
https://github.com/CoolProp/CoolProp/wiki

**Comment by ibell** [comment]
In the general case it means going into the Eigen external, doing a git
pull, and committing the updated commit for the external in the main repo.
In this case, someone, either Eigen or the github mirror, have caused a
divergence in the tree.  I've corrected it this time, and hopefully they
don't do that again...

**Comment by ibell** [comment]
Ok, I fixed it by reverting Eigen back to the release candidate (3.3.2).
Seems to work ok now again.

**Comment by hennink** [comment]
Thank you @ibell, @otbu, @thorade for your quick help with this!
