### ISSUE TITLE
Lots of compiler warnings: C4018: '<' : signed/unsigned mismatch in various files

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1413]
Still getting lots of these when compiling with VS2010 on Windows...
![cp warnings](https://cloud.githubusercontent.com/assets/17114032/22635164/13336184-ebff-11e6-8b15-7fb77d364202.PNG)

...and one serious looking warning from eigen?  ``NullaryFunctors.h``.

**Comment by ibell** [comment]
These are all really just warnings...  But if you wanted to come in and
clean them up, you'd get no argument from me...

**Comment by henningjp** [comment]
That should get most of them.  If there are any left, I'll tweak 'em.  It was just messy, that's all.

**Comment by JonWel** [comment]
@henningjp Tell me if there are any more of C4018 in the cubic side.
(The compilers I'm mainly using do not show me this warning).

**Comment by ibell** [comment]
P.S. The Eigen warning is just that - a warning.  I haven't figured out how to squelch it.

**Comment by henningjp** [comment]
@JonWel All good.  One warning left in MixtureParameters.cpp.  I'll poke at that one later, not urgent.
