### ISSUE TITLE
Inputs for calling vapor quality from REFPROP? [Python]

### ISSUE THREAD

**Issue by sethseth2** [CoolProp/CoolProp#1417]
Hello!

Simple question; I am unsure what inputs I need to call the vapor quality of Nitrogen from REFPROP in the middle of the boiling process. I am using the High-Level Interface.

I have liquid Nitrogen flowing through a tube and am interested in the heat transfer process while it is boiling. I know CoolProp can call the vapor quality using
 `PropsSI( 'Q' , something something, REFPROP::Nitrogen)` 
but I am unsure of what that 'something something' should be. I'm assuming it needs at least the pressure and the boiling temperature, but my current code assumes a constant pressure throughout the tube. What should I use to retrieve the vapor quality at a certain distance from where it started to boil? 

Anyway, I looked around through the documentation and could not find this information. Any help would be appreciated!

(Note: It would be nice if the arguments necessary for each input was listed on the Table of string inputs to PropsSI functions High Level documentation page! I've had to ask a couple of similar questions here.)

**Comment by sethseth2** [comment]
I'm using Python by the way!

**Comment by henningjp** [comment]
@sethseth2 I think this is not really a CoolProp or REFPROP issue.  You have everything you need.  As we talked before (#1392), at a fixed pressure, you are at a fixed boiling point on the saturation curve,  What changes during boiling is enthalpy (**_not temperature_**) as the fluid is converted from liquid to vapor.  So, as you add heat to your liquid at the boiling point (Q=0), some of the liquid will be converted to vapor, until you reach a vapor quality of 1.0.   You can do this calculation knowing the enthalpy of each state and the total enthalpy of the fluid (with the amount of heat input to the system).  This is just a mass/energy balance on your system:
```
H = H.liquid  + H.input

       ( H      -  H.liquid )     ( H   -  H.liquid )
Qual = ---------------------  =  --------------------
       ( H.vapor - H.liquid)         H.latent
```
Once you enter enough heat that H = H.liquid, you are at a vapor quality of 1.0 and your temperature will start rising again as you heat up just vapor.  You can do this in your program without calling CoolProp/REFPROP at all.  However, REFPROP will do the flash calculation for you using your known constant Pressure or Temperature (**_not both_**) and the amount of enthalpy that has been added to the system at any point.  Let's say you are boiling liquid nitrogen at 100K and add 30000 J/kg of heat to the system.
```
>>> Hliq = CP.PropsSI("H","T",100,"Q",0,"REFPROP::Nitrogen")
>>> Hinput = 30000
>>> H = Hliq + Hinput
>>> CP.PropsSI("Q","T",100,"H",H,"REFPROP::Nitrogen")
```
I believe REFPROP supports input pairs of "T" and "H".  The CoolProp HEOS backend does not, but it does support "P"/"H" input pairs, so you just need to find the saturation pressure at T=100K.
```
>>> Psat = CP.PropsSI("P","T",100,"Q",0,"Nitrogen")
>>> Hliq = CP.PropsSI("H","T",100,"Q",0,"Nitrogen")
>>> print Hliq
-73209.1352719
>>> Hinput = 30000
>>> H = Hliq + Hinput
>>> Q = CP.PropsSI("Q","P",Psat,"H",H,"Nitrogen")
>>> print Q
0.1863638048
```

Again, you don't really need to call the fluid libraries as this is a linear interpolation between the liquid and vapor enthalpy.

**Comment by ibell** [comment]
@henningjp did a very nice job of explaining how CoolProp handles this, so I'm going to close the issue.  Feel free to reopen if necessary.

**Comment by sethseth2** [comment]
@henningjp its not exactly a CoolProp/REFPROP issue, but the knowledge that I can use H&T/H&P as input pairs was something that I did not know, nor could I find in the documentation (so I guess its a CoolProp documentation issue, is there a place specific for those?).

I also didn't realize that the vapor quality was just interpolation in REFPROP; I thought they used something more sophisticated. Thanks for the information.
