### ISSUE TITLE
UNIFAQ -> UNIFAC

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1421]
@JonWel I came to a sudden realization yesterday that I had always been mis-spelling UNIFAC.  Throughout CoolProp, I spell it as UNIFAQ, and all instances should be changed to UNIFAC for consistency.  In your next iteration of VTPR, could you make that change?

**Comment by JonWel** [comment]
Yes, I noticed it too and was already planing to change it.
I'll do it soon.
(It puzzled me at a moment as I was also using UNIFAQ in my report ^^; I guess it was a mix with UNIQUAC)
