### ISSUE TITLE
Nonsensical Vapor Quality allowed as Input Value

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1424]
The backends are allowing inputs of Q < 0 and Q > 1, which results in obscure error messages like "_rhomolar is less than zero..._" or returns a nonsensical value that is extrapolated outside the vapor dome.   I can fix it, either by:

- [ ] Setting _Q = min( max(value, 0), 1),  _- might be confusing to the user that this "clipping" is occurring_
- [x] Just set an error condition if this occurs
- [ ] Leave it alone, because there is some purpose to this that I am unaware of....

Anyone have a preference?  Obviously, users should know better, but....

**Comment by henningjp** [comment]
No comments, so I picked one.  Updating HEOS and IF97 backends.  Don't know if REFPROP handles this already.

**Comment by ibell** [comment]
Sorry, I think the right approach is to not allow qualities outside [0,1]
and throw exception if you get one.

**Comment by henningjp** [comment]
That's what I did in PR #1428.
