### ISSUE TITLE
Excel wrapper instructions for Mac OS X El Capitan don't work

### ISSUE THREAD

**Issue by alchemyst** [CoolProp/CoolProp#1430]
[The instructions](http://www.coolprop.org/dev/coolprop/wrappers/Excel/index.html#pre-compiled-binaries-for-osx) for installing the Excel wrapper in Mac OS X do not work for Excel 2016 under Mac OS X El Capitan 10.11.

I have been able to track the reason for this to the combination of two issues:

* Sandboxing 
* [SIP](https://support.apple.com/kb/TA24723?locale=en_US) blocks the setting of any environment variable which starts with `DYLD_`.

The particular issue with the instructions is the part where you set `DYLD_LIBRARY_PATH`. This is silently ignored when SIP is enabled.

```
$ ~ launchctl setenv DYLD_LIBRARY_PATH "/Users/${USER}/Library/Group Containers/UBF8T346G9.Office"
$  ~ launchctl getenv DYLD_LIBRARY_PATH
```

This issue is also referenced [here](https://github.com/soumith/cudnn.torch/issues/111) and [here](https://github.com/oracle/node-oracledb/issues/231).

**Comment by ibell** [comment]
Argh...  Are you able to modify the instructions to get them working on
10.11?  They work on 10.10.  I think the blocking of DLYD_* variable
setting in a .plist is a new "feature" in 10.11.  Otherwise, how are we
meant to set environment variables in 10.11?

**Comment by alchemyst** [comment]
I have tried every workaround listed in the threads I posted to no avail. Editing Excel's info.plist rendered it unable to run. Every other way of setting these environment variables seems to fail silently. I have not tried disabling SIP, but I think few people will be willing to.

--
This message may contain unintentional errors, as it was typed on a phone

**Comment by ibell** [comment]
Funny, I seem to recall that they worked for me on 10.11.  I can check
tomorrow.  Did you do as recommended with the startup .plist?

My reading suggests that setting DYLD_* environment variables is not
blocked with SIP, but protected executables ignore DYLD_* variables.  A
small distinction, but important nonetheless.

**Comment by alchemyst** [comment]
Here is the output of some commands to verify that everything is in the right place.

```
$ uname -a
Darwin aphrodite.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64

$ file /Applications/Microsoft\ Excel.app/Contents/MacOS/Microsoft\ Excel
/Applications/Microsoft Excel.app/Contents/MacOS/Microsoft Excel: Mach-O 64-bit executable x86_64
$ cat ~/Library/LaunchAgents/my.startup.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>my.startup</string>
<key>ProgramArguments</key>
<array>
  <string>sh</string>
  <string>-c</string>
  <string>launchctl setenv DYLD_LIBRARY_PATH "/Users/alchemyst/Library/Group Containers/UBF8T346G9.Office"</string>
</array>
<key>RunAtLoad</key>
<true/>
</dict>
</plist>
$ file ~/Library/Group\ Containers/UBF8T346G9.Office/libCoolProp.dylib
/Users/alchemyst/Library/Group Containers/UBF8T346G9.Office/libCoolProp.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by ibell** [comment]
Yeah, seems correct - when you run "env" at the shell, what are the
contents of DYLD_LIBRARY_PATH?

**Comment by alchemyst** [comment]
It is not set. I use zsh, but it is not set in any of my shells. I have also verified that it is not set in Excel by using this VBA function and `=ENV("DYLD_LIBRARY_PATH")` in cell A1.

```
Public Function Env(Value As Variant) As String
    Env = Environ(Value)
End Function
```

**Comment by alchemyst** [comment]
Also, notice this:

```
$ launchctl setenv DYLD_LIBRARY_PATH "/Users/${USER}/Library/Group Containers/UBF8T346G9.Office"
$ launchctl getenv DYLD_LIBRARY_PATH  # empty output
$ launchctl setenv DYLDLIBRARYPATH "/Users/${USER}/Library/Group Containers/UBF8T346G9.Office" # Same kind of thing, but no underscores
$ launchctl getenv DYLDLIBRARYPATH # works fine
/Users/alchemyst/Library/Group Containers/UBF8T346G9.Office
```

After running this sequence of commands in my terminal and restarting Excel, I am able to retrieve the contents of "DYLDLIBRARYPATH" using the test spreadsheet. I have also edited the startup.plist and obtained similar results. I appear to be following all the right steps, but it appears that "DYLD_*" is simply not being set when I call setenv. The result is the same if I do it as root.

**Comment by alchemyst** [comment]
I have upgraded to Sierra (MacOS 10.13.3) and can confirm that the situation is the same.

**Comment by ibell** [comment]
Can you contact Apple directly?

**Comment by alchemyst** [comment]
I am not sure what the channels would be for doing that. I am not a registered developer.

**Comment by alchemyst** [comment]
I have however crafted a [StackOverflow question](http://stackoverflow.com/questions/43121458/setting-dyld-library-path-on-mac-os-x-sierra-coolprop) in the mean time.

**Comment by alchemyst** [comment]
We have a partial solution to the problem from TheDarkKnight on the StackOverflow question. If we follow all the same instructions in terms of copying the files and so on, but not the creation of the plist file, we can access coolprop functions if we start Excel with the following command from the terminal:

    DYLD_LIBRARY_PATH="/Users/${USER}/Library/Group Containers/UBF8T346G9.Office" /Applications/Microsoft\ Excel.app/Contents/MacOS/Microsoft\ Excel

So at least this allows us to use CoolProp in Excel on the Mac, although it is not optimal as we can't use this when for instance double clicking on a spreadsheet from Finder.

**Comment by ibell** [comment]
Check out this information: http://stackoverflow.com/questions/39109886/word-2016-vba-add-in-for-mac#comment73528878_39109886 .  Can someone try this out and let me know if that works for you?

**Comment by alchemyst** [comment]
I did this:

    mv /Users/${USER}/Library/Group\ Containers/UBF8T346G9.Office/libCoolProp.dylib /Users/${USER}/Library/Group\ Containers/UBF8T346G9.Office/User\ Content.localized/Add-Ins.localized

Then I started a fresh instance of Excel via Spotlight and got error 53 when evaluating `=Props1SI("Tcrit";"Water")` in A1. 

It still works when defining `DYLD_LIBRARY_PATH` appropriately as per my previous comment. So for now I am using that method. I'm not sure whether the plug-in needs to reference the dylib in a particular location for this to work, but it doesn't seem to work simply by putting it that folder.

**Comment by ibell** [comment]
Yeah, I think the paths in the addin itself needs to be modified to point
to the dylib.  Annoying, but necessary I believe

**Comment by ibell** [comment]
Boy, that sure is yucky.  I see the point of sandboxing, but it is very irritating.

**Comment by alchemyst** [comment]
Yeah, it gets even worse. I spent yesterday trying to come up with a working set of install instructions for my students, but it appears as though you cannot edit .xlam files successfully on the macOS version of Excel. I can start Excel and edit the code I mentioned above to include the full path, but there appears to be no way to save (see the screenshot below with no save option in the VB Editor).

![no save option in vb editor](https://cloud.githubusercontent.com/assets/236588/25310919/e72c1c3c-27f1-11e7-97c7-083e246287bd.png)

So I can change the code, and CoolProp will work fine for that session, but as soon as I close Excel and open it again, the changes disappear. So we're back to being unable to make a single change once which will allow CoolProp to work.

So these are the instructions which I have come up with which appear to be usable for a non-technical audience who knows how to run a Python program:

1. Execute install_coolprop_excel.py  This will download and install all the files you need
2. Unzip the "Excel with CoolProp.app.zip" file and double click it. This should open MS Excel
3. Open a new blank spreadsheet
4. In the menu, select _Tools|Excel Add-ins..._
5. Click Browse
6. In the window that comes up, press ⌘⇧G and type `~/Library/Group Containers/UBF8T346G9.Office`
7. Select the file `CoolProp.xlam`
8. Press OK
9. To test that this has worked, type the formula `=Props1SI("Water";"Tcrit")`. The answer should be 647.096
10. Once this is done, you should also be able to open the TestExcel.xlsx file on your desktop which contains more demonstrations.

*Note* you will have to launch Excel using the "Excel with CoolProp" application in order to use CoolProp every time you need it.

The Python program basically downloads the current versions of the .xlam, the .dylib, and TestExcel.xls, placing them in `~/Library/Group Containers/UBF8T346G9.Office/`, `~/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized` and `~/Desktop` respectively. I had hoped to automate the process of updating the .xlam only to find that the VBA code is stored in some wierd binary blob which I have no way of modifying. My students have a lot of difficulty navigating SourceForge, since they often click on the "Need the latest version? Click here" message at the top and download the wrong thing.

The application was generated with Automator and just calls a shell script to launch Excel using the code

    DYLD_LIBRARY_PATH="/Users/$USER/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Add-Ins.localized" /Applications/Microsoft\ Excel.app/Contents/MacOS/Microsoft\ Excel

[install_coolprop_excel.py.zip](https://github.com/CoolProp/CoolProp/files/949463/install_coolprop_excel.py.zip)

[Excel with CoolProp.app.zip](https://github.com/CoolProp/CoolProp/files/949464/Excel.with.CoolProp.app.zip)

**Comment by davidtkearns** [comment]
alchemyst's guide above works well. Only one little point - the test function is:
=Props1SI("Water","Tcrit") (with a comma)
not
=Props1SI("Water";"Tcrit") (with a semicolon)

**Comment by alchemyst** [comment]
@davidtkearns Thanks for the comment. Just a note that the test function should use the separator which is set up for your region. I would love to use commas in my Excel on Mac, but it is linked to the fact that I have selected "South Africa" as my region and I cannot change it!

**Comment by davidtkearns** [comment]
@alchemyst TIL commas don’t always separate arguments in Excel functions
