### ISSUE TITLE
CO2 error near saturation curve

### ISSUE THREAD

**Issue by uqtredd1** [CoolProp/CoolProp#1431]
I've been encountering some errors when updating the CO2 state very close to the saturation curve (CoolProp 6.1.0). One such set of inputs which recreates the error is given by:

>fluid = CP.AbstractState("HEOS","CO2")
>fluid.update(CP.PT_INPUTS,6.86825e+06 ,301)

Produces:

  File "CoolProp/AbstractState.pyx", line 90, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17930)
  File "CoolProp/AbstractState.pyx", line 92, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:17822)
ValueError: Saturation pressure [6.86826e+06 Pa] corresponding to T [301 K] is within 1e-4 % of given p [6.86825e+06 Pa]

Why is this a problem? Any quick fixes to circumvent? Thanks in advance.

**Comment by henningjp** [comment]
That close to the saturation curve, it assumes that you are actually **_on_** the saturation curve, at which point there are two solutions; one for the liquid state and one for the vapor state.  Once you get "close enough" to the saturation curve, switch to the PQ input pair for the state you are after; liquid (Q = 0) or vapor (Q = 1).

**Comment by uqtredd1** [comment]
I thought it must be something along those lines. I added an exception to catch when it gets close to saturation and switches the input type. A bit messy, but it works. Thanks for the suggestion.
