### ISSUE TITLE
Submodules Error

### ISSUE THREAD

**Issue by DGSEM** [CoolProp/CoolProp#1441]
Hello,
we are trying to include CoolProp via ExternalProject_Add (CMake) in our Code Framework.  This worked fine until some weeks ago.

Now we are getting a Submodule Error Message for the external module Eigen:

`...
Cloning into 'externals/Eigen'...
fatal: reference is not a tree: cc4a1cdf9e2545c488d3d4074d71a896134cda10...
`

I spent some work on it and I think it's a dependency problem, but did not find a solution yet. Does someone else has this problem? Perhaps we are doing something wrong. Operating System is Ubuntu 14.04/16.04 with e.g. Coolprop v6.x.

Regards

**Comment by ibell** [comment]
Yeah, they messed up the commit history in the git clone of the mercurial
repository.  I ran into the same problem.  Here are some possible
resolutions:
1) Do a git pull inside your Eigen folder within your git repo
2) Update (force it) all the submodules within CoolProp
3) Remove the CoolProp submodule from your project, commit, re-add it.

It should be fixable, I use CoolProp in a number of other projects as a
submodule.

**Comment by ibell** [comment]
Bump.

**Comment by thorade** [comment]
Can this be closed?
Or is there a rapidjson problem now?

**Comment by thorade** [comment]
Works for me, but only with a FRESH clone

**Comment by ibell** [comment]
Yes, the key is the fresh clone.
