### ISSUE TITLE
CoolProp in matlab for supercritical co2

### ISSUE THREAD

**Issue by JieZhuUCI1sad** [CoolProp/CoolProp#1444]
Does anyone have experiences using coolprop or refprop to call supercritical properties in matlab? I need to do simulations using supercritical CO2 but it always gives me an error when I call the properties using supercritical temperature or pressure.

**Comment by ibell** [comment]
Please show an example that didn't work along with the error message.  It
should work fine!

**Comment by JieZhuUCI1sad** [comment]
Hi ibell! Thanks for responding. Below is my error when I use temperature above critical temperature to call the properties.
>> refpropm('P','T',999.15,'Q',0,'water')
Error using refpropm (line 464)
[TQFLSH error 271] temperature input to
temperature-quality flash is greater than
critical temperature; T =  999.15 K, Tcrit =
647.10 K.

**Comment by JieZhuUCI1sad** [comment]
I have downloaded the 3 m files from NIST and added the path

**Comment by ibell** [comment]
Well, there's your problem - you called a temperature of 999 K, which is
well above the critical temperature. 'Q',0 says you want a vapor quality of
zero (saturated liquid).

**Comment by jowr** [comment]
I will close this for now, please reopen if necessary. Please do not use this place to report REFPROP errors - it seems like your problem is not related to CoolProp.
