### ISSUE TITLE
how to calculate pseudocritical temperature?

### ISSUE THREAD

**Issue by zhenhaochu** [CoolProp/CoolProp#1445]
Dear: pseudocritical temperature is the temperature of working fluid when the specific heat shows its maximum value, how to calculate it in coolprop?

**Comment by ibell** [comment]
Umm, shouldn't that always be at the critical point?  Cp diverges towards infinity at the critical point.  Otherwise, you could use a bounded optimization to call the Cp function and find the maximum.  That is not built into CoolProp.
