### ISSUE TITLE
View errors

### ISSUE THREAD

**Issue by Scott2209** [CoolProp/CoolProp#1447]
My typical way of getting data from Matlab is via the Windows library via a line of code that looks like this:
calllib('coolprop', 'AbstractState_update_and_5_out', handle, inputpairnumber, input1(:), input2(:), elements, outputnum, pt.one, pt.two, pt.three, pt.four, pt.five, ierr, herr, elements);

This works well, except sometimes I find myself operating outside the limits for the EOS (e.g. for incompressible brines) and get bogus values coming back.

My understanding is that "ierr" and "herr" provide information on errors, but I don't know what to do with these.  Would anyone have an example of how to read, and possibly interpret, "ierr" and "herr"?

**Comment by ibell** [comment]
ierr and herr in the parallel evaluation functions are more to do with whether the sizes of input arguments and output arrays/string are valid.  If you get an error, your best bet is to put those values back into PropsSI function, then get the error string like normal.

**Comment by Scott2209** [comment]
Maybe my question would have been better phrased as "is there a way to know if/when I have an error when using AbstractState_update_and_5_out?" 

It appears that the PropsSI returns an output of type double, what is the normal way to get an error string from PropsSI?

**Comment by ibell** [comment]
Well PropsSI throws errors if you use the normal interface.  Or returns an
invalid number of infinity indicating an error
