### ISSUE TITLE
Too large composition vector for REFPROP

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1452]
The REFPROP backend always returns a composition vector with 20 entries. This vector should be reduced to match the actual number of components.

**Comment by jowr** [comment]
I think this is fixed with 25f00a54341dcd5ac0c6a76756d7ea1c72441c79 , but we might want to rethink the use of CoolPropDbl variables...

**Comment by ibell** [comment]
I had to pad out the mole fractions due to REFPROP writing into entries in
the vector all the way to index 19 in the new beta of version 10.  This was
a bug that has been fixed, but it is nonetheless safer to pass 20-length
arrays all the time.  And then truncate as needed.
