### ISSUE TITLE
Does coolprop support openmp?

### ISSUE THREAD

**Issue by zhenhaochu** [CoolProp/CoolProp#1456]
Does coolprop support openmp?

**Comment by ibell** [comment]
Not natively, no, but I have had success using C++11 threading, as CoolProp is internally thread-safe if you use the AbstractState classes.  Creating the classes might take a small amount of time though.

You could wrap calls at the high level into an openmp block.  I don't know if that would work, but its worth a shot.

**Comment by zhenhaochu** [comment]
I just call coolprop API in a parallel for cycle，but it seems does't work！

**Comment by ibell** [comment]
Can you please provide more detail - working example code, error messages, etc.?  Otherwise no way to help...

**Comment by zhenhaochu** [comment]
yeah, today i found the error is caused by .dll library download from sourceforge.net. I recompile coolprop
dll library in my own computer, it works! But when using the new version dll library in openmp, something warning message shown, i don't know why, but the properties calculate is right! 
Here below is my simple test code and run result!
#include <stdio.h>


#include "CoolProp_lib.h"


int main(int argc, char *argv[])
{
    int i;
    double H;
    CoolPropdllinit();
#pragma omp parallel for private(H)
    for(i = 0; i < 10; i++)
    {
        H = 0.0;
        H = PropsSIdll("H", "P", 1000000.0, "T", 500.0, "CO2");
        printf("i = %d H = %lf\n", i, H);
    }
    CloseCoolPropdll();
}
run result!
Unable to load fluid [1-Butene] due to error: Cannot load fluid [1-Butene:106-98-9] because it is already in library; consider enabling the config boolean variable OVERWRITE_FLUIDS
i = 3 H = 692381.288848
i = 4 H = 692381.288848
i = 5 H = 692381.288848
i = 8 H = 692381.288848
i = 9 H = 692381.288848
i = 0 H = 692381.288848
i = 1 H = 692381.288848
i = 2 H = 692381.288848
i = 6 H = 692381.288848
i = 7 H = 692381.288848

VS2010 project will send to your email!

**Comment by zhenhaochu** [comment]
Dear, I can't send email to ian.h.bell@gmail.com !

**Comment by ibell** [comment]
Can you please post your entire code using OpenMP?  The best would be if
you made a cmake project that makes use of CoolProp, something along the
lines of https://github.com/CoolProp/simple_cmake_example .  You'll want to
build CoolProp to a shared library instead of a static library.

Ian

**Comment by zhenhaochu** [comment]
OK，I will try！

**Comment by zhenhaochu** [comment]
Does this right?
https://github.com/zhenhaochu/CoolProp_openmp_test

**Comment by ibell** [comment]
You're close to getting it to compile - you need to add CoolProp as a
submodule in externals/CoolProp

But I've experimented, and I can't figure out how to get OpenMP to work
with CoolProp, neither with the low-level nor the high-level interface.

**Comment by zhenhaochu** [comment]
You can't compile the project? on my own computer, I compile right, but run result wrong! See README!

**Comment by zhenhaochu** [comment]
I think the main reason is coolprop memory allocate logic error!

**Comment by zhenhaochu** [comment]
Any problem with you?

**Comment by ibell** [comment]
I don't actively develop CoolProp anymore, I did try your example, and I
tried a couple of other ideas (using the low-level interface) and I wasn't
able to get any of them to work.  It seems like OpenMP doesn't work with
CoolProp.  I know that C++11 threads DO work though, I have used C++
threads in a couple of other projects.  So you could make a couple of
AbstractState instances, one per thread, and evaluate in parallel threads.
That's a pretty advanced topic though...

**Comment by zhenhaochu** [comment]
Can you give me some example about using CoolProp with c++11 threading?

**Comment by ibell** [comment]
Well, I can't give you a simple example.  As I said, its a rather advanced
topic.  When I did it, I called CoolProp through the NISTfit package, as in
this fitting tool that is under active development:
https://github.com/usnistgov/phifit .  There are a couple of layers there
that you need to get comfortable with unfortunately.

Basically, each thread owns an AbstractState instance; each instance is
threadsafe.

**Comment by zhenhaochu** [comment]
OK， Thank you very much！

**Comment by zhenhaochu** [comment]
I think I find one reason! Maybe the key problem is  global variable library defined in FluidLibrary.h. Since each threads will execute function get_library() defined in FluidLibrary.cpp, if the first thread execute this function, global variable library is empty, it enter into function load(), at the same time, second thread also execute function get_library(), global variable library still empty, error happened. since function load() execute not only once! What should I do with this situation?

**Comment by ibell** [comment]
It's quite complicated.  I sent you a pull request on your repository with
what I was able to get working.  It's not currently faster though...

**Comment by zhenhaochu** [comment]
It did worked! Thanks.

**Comment by thorade** [comment]
Closing for now, feel free to re-open if there are further comments/questions.
People will still find this issue when searching for e.g. OpenMP.
