### ISSUE TITLE
Humid air calculations when dry bulb is above freezing but wet bulb is below freezing

### ISSUE THREAD

**Issue by inamdarharshad** [CoolProp/CoolProp#1465]
I give the following inputs to CoolProp:
DBT = 40 °F = 277,59 K
WBT = 30 °F = 272,04 K
p_baro = 14,7 psia = 101325 Pa

I get the following outputs:
w = 0,001478 kg wv/kg da
DPT = 262,22 K = 12,32 °F

These values match those calculated in EES.

I read the ASHRAE Handbook 2013 Fundamentals Chapter 1 Psychrometrics:
it is recommended that equations 34 - 37 be used to calculate humidity ratio using dry bulb and wet bulb temperatures. Equations 34-35 are for when temperatures are above freezing, and equations 36-37 are for when temperatures are below freezing.

If I use equations 36-37, I get the above values. If I use equations 34-35 I get:
w = 0,0012 kg wv/kg da
Tdp = 8,32 °F

I'm trying to understand why the values obtained when using equations for „below freezing“ conditions give values closest to those that CoolProp calculates. It could also be that the ASHRAE Handbook equations were developed using old data for thermodynamic properties of saturated liquid and vapor whereas RP–1485 uses the most updated IAPWS data.

**Comment by henningjp** [comment]
Looking at the code, the switch in CoolProp is based on the wet bulb temperature (Twb).  If Twb > 273.16, then HAPropsSI calculates properties at the saturation pressure and Twb (using IF97 for water).  If Twb < 273.16, then it calculates the sublimation pressure and properties for ice.  I haven't looked at the ASHRAE Handbook, but I suspect this is what is going on.  Your Twb above is just below freezing, so the evaluation of the equations for below freezing seem to make sense.

**Comment by inamdarharshad** [comment]
I attach an Excel workbook here with a comparison of humidity properties calculated using different calculators. The difference could be because the ASHRAE equations are from Hyland and Wexler (1983) and do not account for the enhancement factor.

**Comment by inamdarharshad** [comment]
ASHRAE 213 is being developed to establish moist air property calculations. This standard is based on the outcomes of ASHRAE RP 1485, and is expected to provide equations/methods to accurately calculate moist air properties. The standard is expected to be applicable for:
(1) Pressures : 70 to 110 kPa (10 to 16 psia)
(2) Temperatures : –60 to 90 °C (–80 to 200 °F)
(3) Relative humidities : 0 to 100%

**Comment by CalebBell** [comment]
Is there a public copy of ASHRAE 213 anywhere?

**Comment by inamdarharshad** [comment]
It is a proposed standard, and is being developed. Dr. Vikrant Aute from the University of Maryland is one of the authors working on it. It could take 6 months more to be published.

**Comment by CalebBell** [comment]
Thanks for the information! I appreciate it.

**Comment by ibell** [comment]
I suspect this is fixed now, my tests show zero failures with humid air code currently for all valid input pairs
