### ISSUE TITLE
REFPROP from Mathcad Wrapper Fails with Memory Violation

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1470]
So from the Excel Add-in DLL, I can call the CoolProp functions with the REFPROP backend with no problems.  Thus I feel that REFPROP is properly installed and locatable by CoolProp.

However, the Mathcad Add-in DLL (which I wrote) fails with a memory violation error and totally screws up Windows to the point that I have to reboot.   Do the Mathad DLL and the installed REFPROP.dll have to have the same calling convention (__stdcall or __cdecl) and/or the same bit-ness ?   The Mathcad 15 DLL is 32-bit, but I'm not sure what calling convention is set in the cmake script, because I don't force it on the build.  I'll have to look and see what the make file is doing.  How do I tell what calling convention the 32-bit REFPROP.dll is compiled with?  How can I tell if it's really calling the 32-bit REFPROP.dll and not the REFPRP64.dll?

**Comment by henningjp** [comment]
I haven't tested Mathcad Prime yet, which is 64-bit.  But I'll post the results when I do.

**Comment by jowr** [comment]
Generally speaking, the software (Mathcad) should refuse to load a shared library of the wrong bitness. Different shared libraries do not have to have the same calling conventions, you mix and match freely as long as you explicitly specify the calling conventions.

Have you tried running a static code analysis or using a very picky compiler setting with, for example, clang/llvm?

**Comment by henningjp** [comment]
Mathcad Prime gives a different error but still fails to call REFPROP.

@jowr - I'll Google those terms and see what it is I need to do.... :grinning:

**Comment by henningjp** [comment]
Here's more info from two different systems.  On one, REFPROP backend runs fine through CoolProp PropsSI() calls.  On the other, the first call to REFPROP backend gives a serious windows memory violation.  

REFPROP Calls: | Run fine! | Windows Memory Violation
-----------------|------------|-------------------------------
OS: | Windows 10 (Home Edition) | Windows 7 Enterprise (SP1)
CoolProp | 6.1.1dev (local build) | 6.1.1dev (SF binary)
REFPROP | 9.1.1 | 9.1
Fortran Runtime | (none installed) | Intel Composer 2017 Runtime Libs

I haven't tried either system with @jowr new REFPROP path mods.  That's next...

**Comment by ibell** [comment]
The fortran runtimes MUST match between the DLL for fortran and what is
installed;  this is why 9.1.1 statically links the fortran runtimes rather
than dynamically linking, which is fraught with all kinds of issues like
what you have here.  I suspect that is the cause, and if you updated to
9.1.1 on the failing one, the problem would go away.

**Comment by henningjp** [comment]
Hmm,  I suspected as much.  May take awhile to get 9.1.1 on that machine, but I'll work on it.  In the mean time, I can uninstall the runtime library completely and test.  THAT I can do pretty quickly this week.

So, even though the runtime lib is statically linked, it doesn't ignore what's installed on the machine?  Doesn't seem right, but I'll check it out this week.  At least now I have a lead to go investigate.

**Comment by henningjp** [comment]
@ibell , That did it!  I removed the Intel Composer 2017 Runtime Libs and Mathcad calls the REFPROP library just fine on the Windows 7 machine.  So, this begs some questions:

1. If the runtime libs are linked in statically to the REFPROP.dll, why does it care what runtimes are installed on the machine?
2. Why does the Excel Add-in not suffer from this problem, even when the 2017 runtimes are installed?

The answers may be unknown, but it makes one scratch one's head...

I'll get 9.1.1 installed and see where that takes us.  I'll close this for now, but may updated it later with the new information.  This should probably be documented somewhere.

**Comment by ibell** [comment]
This is why you statically link runtimes - there is no Intel runtime to
dynamically link against!  Removing this family of error

**Comment by henningjp** [comment]
Uh huh.  And REFPROP **_IS_** statically linked as you say, so why is this happening?  It shouldn't care if the runtimes are in the path on the machine - it has its own copies linked in statically.

**Comment by ibell** [comment]
But 9.1 DOESN'T statically link the Intel runtimes, and requires runtime
dynamic linkage against the Intel runtime on your computer.  Hence the
cause of this bug.

**Comment by henningjp** [comment]
:snail:  ...and the last tumbler clicks into place!

Ok, I understand now.   Thanks!  This will help with some of my other projects.
