### ISSUE TITLE
Error when trying to apply simple mixing rule

### ISSUE THREAD

**Issue by raphaeltimbo** [CoolProp/CoolProp#1471]
I am trying the following code:
```
cas1 = CP.get_fluid_param_string('Nitrogen', 'CAS')
cas2 = CP.get_fluid_param_string('R134a', 'CAS')
CP.apply_simple_mixing_rule(cas1, cas2, 'linear')
```
getting the following error message:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-823c10cc943f> in <module>()
----> 1 CP.apply_simple_mixing_rule(cas1, cas2, 'linear')

CoolProp/CoolProp.pyx in CoolProp.CoolProp.apply_simple_mixing_rule (CoolProp/CoolProp.cpp:41281)()

CoolProp/CoolProp.pyx in CoolProp.CoolProp.apply_simple_mixing_rule (CoolProp/CoolProp.cpp:41178)()

RuntimeError: Could not match the binary pair [811-97-2,811-97-2] - for now this is an error.

```
This same code was working on python 3.5.2 with CoolProp 6.1. 
It is strange that the binary pair showing corresponds only to the R134a  CAS number.

Running:
python 3.6.1
ubuntu 16.04
CoolProp: 6.1.1dev

**Comment by ibell** [comment]
Pull the newest code, I fixed this bug.

**Comment by raphaeltimbo** [comment]
Ok. It is working.
Had to clone and install using:
```
# Check out the sources for CoolProp
git clone https://github.com/CoolProp/CoolProp --recursive
# Move into the folder you just created
cd CoolProp/wrappers/Python
# Start the installation
sudo python setup.py install
```

Before I was using:
`pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp`

Thanks again @ibell !

**Comment by ibell** [comment]
What version of python do you use?  If 3.6, that might explain why your pip
install from dreamhosters didn't work.  That usually works for me, but you
should always try again before giving up.

**Comment by raphaeltimbo** [comment]
I am using 3.6. 
Yes, I think the problem was pip. Updated everything and now it is working.

**Comment by ibell** [comment]
Good, glad to hear.
