### ISSUE TITLE
installing coolprop

### ISSUE THREAD

**Issue by dennnnnis** [CoolProp/CoolProp#1472]
Hi all, i am struggling with installing coolprop, my excel is 2016 version.
once i installed it, it worked. but when i re-open the excel and try it again, it didn't work..

i read some one here that has a same problem, and got the problem solved by re-installing the excel instead. well, i tried it. it still doesn't work. 

could some one help me?  very much thank you in advance.

**Comment by ibell** [comment]
How did you install the adddin?

**Comment by dennnnnis** [comment]
Hi Ian, thank you for your email.

I installed it like what the testexcel told me to.
this testexcel is working, but my working book is always showing "#NAME?"

this working book also showing numbers (just like as the coolprop is
working) whenever i started my workbook without klik on "enable editing".
but right after I klik "enable editing" it will show me "#NAME?".

Im really are just a begginer, in this coolprop things and also for
computer things, so i am sorry for my stupid question..

Thanks and best regards,

Dennis

**Comment by jowr** [comment]
Did you manually install the add-in or did you use the installer?

**Comment by dennnnnis** [comment]
I manually installed it..

**Comment by ibell** [comment]
Please use the installer - that will be much more stable, and fixes a lot
of bugs like what you see here.

**Comment by ibell** [comment]
Bump.  Any update?

**Comment by thorade** [comment]
Closing this issue, as there has been no feedback from the original poster for more than two weeks.
OP can still comment, answer and/or re-open.

**Comment by dennnnnis** [comment]
halo guys, really sorry for a long time hiding without any update. i had to work on site on remote area without any connection.

I already uninstall the coolprop, i want to start all over again from scratch. do you guys have a proper link to download it? 

thank you again for replying my issue.

**Comment by thorade** [comment]
Instructions for installing the Excel interface are here:
http://www.coolprop.org/coolprop/wrappers/Excel/index.html#excel
I have not used that interface, but you should try to follow those steps.
If you encounter problems, please also state version and bitness of your OS, Office and Coolprop.
If everything just works, please also report that back and close the issue, thanks.

For other wrapping interfaces, see here:
http://www.coolprop.org/coolprop/wrappers/index.html

**Comment by dennnnnis** [comment]
ok. thanks a lot! 
i will come back after trying.
