### ISSUE TITLE
Installing New Releases

### ISSUE THREAD

**Issue by Knightroglycerin** [CoolProp/CoolProp#1473]
Hi everyone,

I tried installing the nightly release from 2017-04-10 (second link on the page https://sourceforge.net/projects/coolprop/files/CoolProp/nightly/Python/). After unpacking the file, I have a folder named CoolProp-6.1.1.dev0-cp33-cp33m-win32. Where should I put it to use CoolProp? I have Python 3.6 running on Mac OS Sierra. Also, I don't have very much programming experience, so a more detailed explanation of where to put it would be nice.

Thanks,
Knightroglycerin

**Comment by ibell** [comment]
What you should do is to open a terminal (on windows, press the windows
key, then type "cmd", press enter).  Then copy-paste the second command
from the terminal:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation

Please show the entire output from that command.

**Comment by Knightroglycerin** [comment]
Here is the command I pasted into Terminal: pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp

Here is the entire output pasted onto a word document. Again, it appears to not have installed correctly, as seen from the very end of the code:
[CoolPropReinstall.docx](https://github.com/CoolProp/CoolProp/files/924099/CoolPropReinstall.docx)

Unfortunately, CoolProp still is not running in Python 3.6. It displays "No module named CoolProp" if I attempt to run it. However, I used the command "pip install --user CoolProp" in a previous attempt and Terminal said CoolProp was successfully installed; the red error message at the end did not show up (though CoolProp still did not run in Python). Is there any analogous way to do "pip install --user" with the nightly releases? I want to see if this will work before I try anything else.

**Comment by jowr** [comment]
Hi, what about `pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ --user -U --force-reinstall CoolProp`? It looks like the uninstall step fails - You might want to run `pip uninstall coolprop` or even `sudo pip uninstall coolprop` *a couple of times* before you try to reinstall using the first link.

**Comment by Knightroglycerin** [comment]
Thanks, I tried uninstalling CoolProp, and here is Terminal's output. 
[CoolPropUninstall.docx](https://github.com/CoolProp/CoolProp/files/924819/CoolPropUninstall.docx)
After I said yes to uninstall, Terminal said "Successfully uninstalled CoolProp-6.1.0". I tried to uninstall it again but Terminal said CoolProp wasn't installed, so I assumed it was a clean uninstall.

I used the code you posted above to reinstall CoolProp; here is Terminal's output. 
[CoolPropReinstall2.docx](https://github.com/CoolProp/CoolProp/files/924820/CoolPropReinstall2.docx)

However, CoolProp it still does not work in Python 3.6. I tried running this program...
import CoolProp
from CoolProp.Plots import PropertyPlot
plot = PropertyPlot('R290', 'ph')
plot.calc_isolines()
plot.show()
...and this is the output:
  File "/Users/JohnDoe/Documents/PythonPrograms/PropertyPlot.py", line 1, in <module>
    import CoolProp
ModuleNotFoundError: No module named 'CoolProp'

This has been a problem for some time now. I've tried installing CoolProp before but it would never run on Python 3.6. It would always give the same error message. I'm considering trying Anaconda or some other program to see if it would work better.

**Comment by ibell** [comment]
Yes, that is because your pip install command pulled the version for python
2.7, which seems to be the default python on your system.  When you do
"python --version", what do you get?  I get:

(py36) Ians-Mac-mini:~ ian$ python --version

Python 3.6.0 :: Continuum Analytics, Inc.


How did you try to run those commands you show?


I would 100% recommend to use the anaconda installation.  That should get
you up and running very quickly.

**Comment by ibell** [comment]
@jowr - the python 3.6 wheels are not building on OSX due to a missing conda environment for python 3.6: http://www.coolprop.dreamhosters.com:8010/builders/Python-binaries-osx-64bit-py36/builds/10 .  I don't have access to your machine; can you please add this environment?

**Comment by Knightroglycerin** [comment]
Yep, my Python version is Python 2.7.10. 

To run the commands, I opened up the Python IDLE, selected "New File", copied and pasted the commands from the CoolProp website, and saved it. Then, I opened it and used "Run module". If this is incorrect, please let me know. 

Also, I went to the Anaconda page and for Mac OS, there is a Graphical Installer and a Command Line Installer. Should I install both of them, or should I install just one? Also, do I need to have Python installed to use Anaconda? If I don't need it I might just uninstall it.

Again, thanks for all your help.

**Comment by ibell** [comment]
Leave whatever is on your computer, run the graphical installer for anaconda with python 3.6.  It installs everything in one separate directory (usually in your home directory), which you can easily delete later if need be.

If you pip install for python 2.7, that installs CoolProp for python 2.7, which is not the same thing as version 3.6.  You need to install for the version you want to use.  I know its confusing, took me  a long time to get comfortable with it all.

If you are new to python, you might want to consider using spyder once you have anaconda installed.

Once you have anaconda installed, the process should be much more smooth, especially once @jowr gets the wheels building for OSX for python 3.6

**Comment by Knightroglycerin** [comment]
Thank you! If I have the CoolProp version for Python 2.7, do I have to reinstall CoolProp for Python 3.6? If so, how should I do so?

**Comment by ibell** [comment]
How do you have both python 2.7 and 3.6 on your computer?  This get super
tricky when both are installed.  Dealing with multiple versions of python
is only really viable with anaconda - please install that first.

In answer to your question, yes you must install CoolProp for each version
separately.

**Comment by Knightroglycerin** [comment]
At first, I didn't know Python was already installed on my computer, so I went to the Python website and downloaded 3.6. Only later did I find out that 2.7 is installed by default.

Okay, so I just downloaded Anaconda and updated Spyder. If I need to reinstall CoolProp for Python 3.6, how should I go about doing so?

**Comment by ibell** [comment]
pip will require you to build it yourself (though it should happen
automatically).  You should do the same command as before.  That will
hopefully work.  Please provide the full log of your attempts at the
terminal.

On Sun, Apr 16, 2017 at 10:11 PM, Knightroglycerin <notifications@github.com

**Comment by Knightroglycerin** [comment]
Thanks! First, I entered "pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ --user -U --force-reinstall CoolProp".

Unfortunately, this is the result: 
[CoolPropError2.docx](https://github.com/CoolProp/CoolProp/files/924945/CoolPropError2.docx)

**Comment by Knightroglycerin** [comment]
Also, I attempted to uninstall CoolProp again, but Terminal now responds "Cannot uninstall requirement CoolProp, not installed"

**Comment by ibell** [comment]
Try again?  Just a read timeout

**Comment by Knightroglycerin** [comment]
Trying it a third time. Sorry it's taking so long; usually my school's internet is pretty good but somehow it's just being really slow.

**Comment by Knightroglycerin** [comment]
I'm probably going to just try again tomorrow because the read keeps timing out at around 70%. Hopefully I get better luck then.

**Comment by Knightroglycerin** [comment]
Okay, I have some good news and bad news. After trying to install the nightly releases multiple times, the installation always timed out at around 68-70% with a similar error message to what I posted above. Then, I just tried "pip install --user CoolProp", which was successful. Interestingly, CoolProp installed much more quickly this time (in a matter of seconds, whereas the previous attempt timed out after a few minutes). Terminal's output is posted below.
[CoolPropReinstallSuccess.docx](https://github.com/CoolProp/CoolProp/files/926842/CoolPropReinstallSuccess.docx)

And guess what, CoolProp is finally running in Anaconda! I tried obtaining the p-h and t-s diagrams and it worked reasonably well. However, this version of CoolProp runs into problems at the boundaries of the diagrams and returns truncated graphs. 

This program:
import CoolProp
from CoolProp.Plots import PropertyPlot
plot = PropertyPlot('R134a', 'ts')
plot.calc_isolines()
plot.show()

Returns the following: 
[CoolPropPlotError.docx](https://github.com/CoolProp/CoolProp/files/926843/CoolPropPlotError.docx)

The p-h diagram of R-290 looks even more truncated; I can post that too if needed.

I am quite happy that CoolProp is working now, but is there any way that this problem can be fixed? Perhaps the newer releases will help, if the internet here would cooperate.

**Comment by ibell** [comment]
Your pip installed a very old version (6.0.0) of CoolProp - why?  I don't
understand why it didn't pull the newer sources and build against them...
Hopefully @jowr can get the binary builder operational again very soon.

Can you try to add --user to the set of flags you passed to the development
server install?

**Comment by Knightroglycerin** [comment]
I already included --user in the nightly releases install; the install code I used was: pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ **--user** -U --force-reinstall CoolProp

For some reason, the installment is very slow and it always times out at 68-70% (corresponding to 7.9-8.0 MB).

**Comment by Knightroglycerin** [comment]
I tried moving around the tags and altering the installation command a bit to see if it would install correctly. The command "pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ --user --force-reinstall CoolProp (this does not have -U), which produced basically the same error message as above.

The command "pip install --user -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ CoolProp" also produces the same error message. 

Well, if nothing else works, I guess I might have to stick with my MatLAB version of CoolProp (which works very well, but I want to be able to make the property plots in Python because they are helpful for projects). Maybe the binary builder you mentioned above might help when it's finished; I'll just have to wait and see what happens. Please let me know what else I could try, and again, thank you for all your help with this problem.

**Comment by ibell** [comment]
Once @jowr gets that binary builder working again, it will be trivial...  I'm feeling bad for you, so I built a one-off python 3.6 wheel for OSX

Unzip the attached zip, then in the same directory as the .whl file, do 
```
pip install CoolProp-6.1.1.dev0-cp36-cp36m-macosx_10_7_x86_64.whl 
```

[CoolProp-6.1.1.dev0-cp36-cp36m-macosx_10_7_x86_64.whl.zip](https://github.com/CoolProp/CoolProp/files/927380/CoolProp-6.1.1.dev0-cp36-cp36m-macosx_10_7_x86_64.whl.zip)

**Comment by Knightroglycerin** [comment]
Wow, thank you so much! I wish I could like your above comment more than once.

I'm really sorry to keep bothering you about this, but how exactly do I install it in the same directory? I've unzipped it but I'm not sure how to install it. I just opened Terminal, put in the above command, and it didn't work (error message below). I assume that wasn't how I'm supposed to do it so it was an error.
[CoolPropReinstall3.docx](https://github.com/CoolProp/CoolProp/files/927410/CoolPropReinstall3.docx)

**Comment by ibell** [comment]
You need to change the working directory in terminal to the location of the
whl file (Google how to do that).  Then run my command.

**Comment by Knightroglycerin** [comment]
I definitely should have Googled that myself, it was one of the first results on the page. But anyways, I did as you said and the CoolProp is now successfully running in Anaconda/Spyder!

Again, thank you so much for all your help. This actually came just in time for one of my final projects, and I'm really grateful for you helping me through this problem.

Also, if you happen to be the Dr. Ian Bell who worked on CoolProp, thank you for creating such an amazing program. It's already been incredibly helpful in my Thermodynamics class and it's one of the only free fluid libraries out there with such a wide range of features. I'll definitely stick around to see what's to come, and keep up the good work!

Take care,
Knightroglycerin

**Comment by ibell** [comment]
Yup, I am that Dr. Ian Bell, glad you were able to get this working.

**Comment by jowr** [comment]
My bad, I forgot to activate the Python 3.6 builder. It should be triggered by all future commits.

**Comment by ibell** [comment]
Yay! Thanks @jowr

**Comment by Knightroglycerin** [comment]
Don't worry about it! Dr. Bell helped me install CoolProp and it appears to be running fine so far.
