### ISSUE TITLE
some error messages when source CoolProp.R

### ISSUE THREAD

**Issue by AntonioCarrilloAndres** [CoolProp/CoolProp#1475]
Hello, I am using CoolProp with R 3.3.2 on Win64. I get these messages :

> dyn.load(paste("CoolProp", .Platform$dynlib.ext, sep=""))
>source(CoolProp.R)

in method for ‘copyToR’ with signature ‘"_p_CoolProp::SimpleState"’: no definition for class “_p_CoolProp::SimpleState”
in method for ‘copyToR’ with signature ‘"_p_CoolProp::CriticalState"’: no definition for class “_p_CoolProp::CriticalState”
in method for ‘copyToR’ with signature ‘"_p_CoolProp::SsatSimpleState"’: no definition for class “_p_CoolProp::SsatSimpleState”

-----

CoolProp seems to work fine, but maybe there is something wrong with the R wrapper...

Thank you

**Comment by ibell** [comment]
Nothing wrong, just swig doesn't know how to wrap some classes, those are just warnings...
