### ISSUE TITLE
Urgent: Issue with Cubic EOS

### ISSUE THREAD

**Issue by spmuppar** [CoolProp/CoolProp#1482]
I'm facing problems with the Cubic EoS, 
It is perfectly running for the first command, and failing in all next commands..

-> from CoolProp.CoolProp import PropsSI
-> PropsSI('UMASS', 'T', 336.543, 'DMASS', 1.304, "PR::Oxygen")
371621.8597497555
-> PropsSI('UMASS', 'T', 336.543, 'DMASS', 1.304, "PR::Oxygen")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:46474)
  File "CoolProp/CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:46262)
  File "CoolProp/CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:44436)
ValueError: For now, we don't support T [336.543 K] below Ttriple [inf K] : PropsSI("UMASS","T",336.543,"DMASS",1.304,"PR::Oxygen")

Again, if I exit the terminal and open a new one, and load coolprop.. the same thing repeats
I tried installing the 6.1.1 version, different OS.. no use.. 

Please help me, I have a deadline..

**Comment by ibell** [comment]
I can replicate.  I'll investigate.

**Comment by spmuppar** [comment]
Many thanks Bell.

**Comment by ibell** [comment]
Cannot replicate error in C++...

**Comment by spmuppar** [comment]
I use CoolProp in python..

**Comment by ibell** [comment]
I know, I'm on the hunt now...

**Comment by ibell** [comment]
What OS/ python version do you use?  I have a workaround.

**Comment by spmuppar** [comment]
Ubuntu 16.04
Python 2.7.12

**Comment by spmuppar** [comment]
Are you able to replicate the error ?

**Comment by ibell** [comment]
Ugh, I thought I could make a binary wheel for you, but thats not possible
for ubuntu.

**Comment by ibell** [comment]
Yes, in python, but not in C++, which is where the problem lies.

**Comment by ibell** [comment]
How did you install coolprop?

**Comment by spmuppar** [comment]
pip install coolprop, 

As it was giving me this error, 

I also tried 6.1.1 
python setup.py build, install..

**Comment by ibell** [comment]
Interesting... in python 3 I get a segfault..

**Comment by spmuppar** [comment]
I really appreciate your time Bell, 
Let me try.

**Comment by ibell** [comment]
I also tried with the low-level interface, same problem.  I have no
explanation.

**Comment by spmuppar** [comment]
Sorry, but I can't understand this..

$ cmake .. -DCMAKE_BUILD_TYPE=Release

-- COOLPROP_INSTALL_PREFIX=/home/administrator/Downloads/CoolProp-master/install_root
-- CoolProp version: 6.1.1dev
CMake Error at CMakeLists.txt:17 (add_subdirectory):
  The source directory

    /home/administrator/Downloads/CoolProp-master/externals/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:21 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/home/administrator/Downloads/CoolProp-master/wrappers/Python/pybind11/build/CMakeFiles/CMakeOutput.log".

**Comment by ibell** [comment]
where are you running that command?

**Comment by ibell** [comment]
can you do a "pwd" in the terminal?

**Comment by spmuppar** [comment]
/home/administrator/Downloads/CoolProp-master/wrappers/Python/pybind11/build

**Comment by ibell** [comment]
Ok, that's the right location.  But you needed to have done a recursive git
clone rather than downloading the zip.

I.e., do

git clone --recursive https://github.com/coolprop/coolprop

then

cd coolprop/wrappers/python/pybind11

and follow my instructions from that location

**Comment by spmuppar** [comment]
Thanks, 
Will do now

**Comment by ibell** [comment]
If you did a git clone, you might just need to do a

git submodule update --init

**Comment by spmuppar** [comment]
administrator@JPDesktop:~/Downloads/coolprop/wrappers/Python/pybind11/build$ sudo cmake --build .
Scanning dependencies of target CoolProp
[  2%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/SpeedTest.cpp.o
[  4%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Ice.cpp.o
[  6%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CPstrings.cpp.o
[  9%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CPnumerics.cpp.o
[ 11%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CPfilepaths.cpp.o
[ 13%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolPropTools.cpp.o
[ 15%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/PolyMath.cpp.o
[ 18%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/AbstractState.cpp.o
[ 20%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolProp.cpp.o
/home/administrator/Downloads/coolprop/src/CoolProp.cpp:64:105: fatal error: gitrevision.h: No such file or directory
compilation terminated.
CMakeFiles/CoolProp.dir/build.make:254: recipe for target 'CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolProp.cpp.o' failed
make[2]: *** [CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolProp.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CoolProp.dir/all' failed
make[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ibell** [comment]
oops,sorry about that.  in the dev/ folder inside coolprop, do

python generate_headers.py

**Comment by spmuppar** [comment]
I did, 
same error..

[  2%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolProp.cpp.o
/home/administrator/Downloads/coolprop/src/CoolProp.cpp:64:105: fatal error: gitrevision.h: No such file or directory
compilation terminated.
CMakeFiles/CoolProp.dir/build.make:254: recipe for target 'CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolProp.cpp.o' failed
make[2]: *** [CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolProp.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CoolProp.dir/all' failed
make[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I deleted the build folder, ( to remove the CMake cache files..) and then tried again.. 
same error..

**Comment by spmuppar** [comment]
For your reference, 
administrator@JPDesktop:~/Downloads/coolprop/dev$ sudo python generate_headers.py 
cpversion.h is up to date
version written to hidden file: /home/administrator/Downloads/coolprop/.version for use in builders that don't use git repo
git version 2.7.4
git is accessible at the command line
all_fluids_JSON.h is up to date
all_incompressibles_JSON.h is up to date
mixture_departure_functions_JSON.h is up to date
mixture_binary_pairs_JSON.h is up to date
predefined_mixtures_JSON.h is up to date
all_cubics_JSON.h is up to date
cubic_fluids_schema_JSON.h is up to date

**Comment by ibell** [comment]
what was the output from the header generation script?

**Comment by ibell** [comment]
Don't know why gitrevision.h wasn't generated...  Put this as gitrevision.h
in your include directory:

//Generated by the generate_headers.py script on 2017-04-24 22:26:45.770072


std::string gitrevision = "cc38d3cd01cb957891bfc08489e0a0b24095cc82";

**Comment by spmuppar** [comment]
correct me if I'm wrong, 

I just created a file named gitrevision.h in the include folder that has only the line 
`std::string` gitrevision = "cc38d3cd01cb957891bfc08489e0a0b24095cc82"; `

**Comment by ibell** [comment]
That should do it.

**Comment by spmuppar** [comment]
Please excuse my ..., 
should I run generate_headers.py once again and do as before or 
directly build in the pybind folder..

**Comment by ibell** [comment]
back to the pybind11 folder...

**Comment by ibell** [comment]
Normally, things *just work*, but I have no idea how to fix the cython
wrapper, hence all this runaround...

**Comment by spmuppar** [comment]
The build was successful, 

import sys
sys.path.insert(0,r'/home/administrator/Downloads/CoolProp-master/wrappers/Python/pybind11/build//')
from CoolProp.CoolProp import PropsSI
PropsSI('UMASS', 'T', 345, 'DMASS', 112, "PR::Oxygen")
364135.57526185765
PropsSI('UMASS', 'T', 345, 'DMASS', 112, "PR::Oxygen")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:46474)
  File "CoolProp/CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:46262)
  File "CoolProp/CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:44436)
ValueError: For now, we don't support T [345 K] below Ttriple [inf K] : PropsSI("UMASS","T",345,"DMASS",112,"PR::Oxygen")

**Comment by ibell** [comment]
Can you do a:

import CoolProp
print(CoolProp.__file__)

after the insert?

**Comment by ibell** [comment]
So like:

import sys
sys.path.insert(0,
r'/Users/ian/Code/coolprop/wrappers/python/pybind11/build_bnd11/Debug')
import CoolProp as CP

import CoolProp
print(CoolProp.__file__)

CP.set_debug_level(10)
print(CP.PropsSI("UMASS", "T", 336.543, "DMASS", 1.304, "PR::Oxygen"))
print(CP.PropsSI("UMASS", "T", 336.543, "DMASS", 1.304, "PR::Oxygen"))

**Comment by ibell** [comment]
It is somehow still getting your pip installed CoolProp

**Comment by spmuppar** [comment]
import CoolProp
print(CoolProp.__file__)
/home/administrator/anaconda2/lib/python2.7/site-packages/CoolProp/__init__.pyc

>>> print(PropsSI("UMASS", "T", 336.543, "DMASS", 1.304, "PR::Oxygen"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:46474)
  File "CoolProp/CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:46262)
  File "CoolProp/CoolProp.pyx", line 297, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:44436)
ValueError: For now, we don't support T [336.543 K] below Ttriple [inf K] : PropsSI("UMASS","T",336.543,"DMASS",1.304,"PR::Oxygen")

**Comment by spmuppar** [comment]
>>> CoolProp.__version__
u'6.1.1dev'

**Comment by spmuppar** [comment]
import CoolProp
u'6.1.1dev'

**Comment by ibell** [comment]
Yes, it is still not finding your pybind11 pyd.

Can you please
a) send a list of the files in the build directory
b) show your full testing script

**Comment by ibell** [comment]
Also, if you open a python prompt in your build directory and do:

import CoolProp
print(CoolProp.__file__)

what do you get?

**Comment by spmuppar** [comment]
I assumed build directory here is the pybind11/build 

tried to import coolprop
got Segmentation fault(core dumped)

**Comment by ibell** [comment]
What are the contents of that folder?

**Comment by spmuppar** [comment]
CMakeCache.txt  CMakeFiles  cmake_install.cmake  _CoolProp  CoolProp.so  Makefile  pybind11

**Comment by ibell** [comment]
Hmm.. Seems to have built....

**Comment by ibell** [comment]
Rewinding this thread, do you have to use PR backend?  Why not use HEOS
instead?

**Comment by spmuppar** [comment]
FYR,
administrator@JPDesktop:~/Downloads/coolprop/wrappers/Python/pybind11/build$ sudo cmake --build .
[  2%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/CoolProp.cpp.o
[  4%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Configuration.cpp.o
[  6%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/HumidAirProp.cpp.o
[  9%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/DataStructures.cpp.o
[ 11%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Solvers.cpp.o
[ 13%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/ODEIntegrators.cpp.o
[ 15%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Helmholtz.cpp.o
[ 18%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/MatrixMath.cpp.o
[ 20%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Cubics/CubicBackend.cpp.o
[ 22%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Cubics/UNIFAC.cpp.o
[ 25%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Cubics/UNIFACLibrary.cpp.o
[ 27%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Cubics/CubicsLibrary.cpp.o
[ 29%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Cubics/VTPRBackend.cpp.o
[ 31%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Cubics/GeneralizedCubic.cpp.o
[ 34%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/IF97/IF97Backend.cpp.o
[ 36%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/VLERoutines.cpp.o
[ 38%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/HelmholtzEOSBackend.cpp.o
[ 40%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/TransportRoutines.cpp.o
[ 43%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/HelmholtzEOSMixtureBackend.cpp.o
[ 45%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/MixtureParameters.cpp.o
[ 47%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/FlashRoutines.cpp.o
[ 50%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/PhaseEnvelopeRoutines.cpp.o
[ 52%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/ReducingFunctions.cpp.o
[ 54%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/MixtureDerivatives.cpp.o
[ 56%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/Fluids/FluidLibrary.cpp.o
[ 59%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Helmholtz/Fluids/Ancillaries.cpp.o
[ 61%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/REFPROP/REFPROPMixtureBackend.cpp.o
[ 63%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/REFPROP/REFPROPBackend.cpp.o
[ 65%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Incompressible/IncompressibleLibrary.cpp.o
[ 68%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Incompressible/IncompressibleBackend.cpp.o
[ 70%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Incompressible/IncompressibleFluid.cpp.o
[ 72%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Tabular/BicubicBackend.cpp.o
[ 75%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Tabular/TabularBackends.cpp.o
[ 77%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/Backends/Tabular/TTSEBackend.cpp.o
[ 79%] Building CXX object CMakeFiles/CoolProp.dir/home/administrator/Downloads/coolprop/src/pybind11_interface.cxx.o
[ 81%] Linking CXX shared module CoolProp.so
[100%] Built target CoolProp

**Comment by spmuppar** [comment]
So, we have a CFD code, 
I'm working to compare the cubic EOS, HEOS, REFPROP for the simulations in the transcritical regime..
To observe their accuracies, uncertainties..

I thought I can use your cubic EOS.. instead of coding a PR..EOS..

**Comment by ibell** [comment]
Yes, in principle that should be fine.  I have absolutely no idea why you
are seeing the failures you are.  Today, it seems like CoolProp is just
very unhappy.

**Comment by spmuppar** [comment]
just wondering, if you were able to overcome the error by the above said procedure...
If so, I can redo again..

**Comment by ibell** [comment]
Yes, it worked for me, but on OSX, I didn't test on linux.

**Comment by spmuppar** [comment]
I'll remove and reinstall from the dev version

Just to check, 
Should I do the above said build process before running python setup.py build.. ?

**Comment by ibell** [comment]
You should NOT run python setup.py build.  This is an alternative
solution.  There is some weird and hard-to-debug problem with the cubics
that I need to dig into.  Unless you can get the pybind11 wrapper working,
I think you're stuck for now :/

**Comment by ibell** [comment]
Seg fault for me too on xubuntu.  I think I'm out of ideas for today...

**Comment by ibell** [comment]
P.S. I fixed the generate_headers.py script, there was a path bug that I
hadn't seen before.

**Comment by spmuppar** [comment]
Thank you so much for kind assistance bell, 
Can't ask for any more time.. (but please, ping me if incase you resolved.. it..)
Good Night, 

Sai.

**Comment by JonWel** [comment]
@spmuppar Hi, for CFD application, I would look on lower level calls (the low level interface interface, and direct C++ access).

@ibell I was thinking about suggesting calls from the shared library, but I got a strange result.

When I use the cubic functions from Julia, calling the shared library, this work nicely:
```julia
julia> using CoolProp

julia> PropsSI("UMASS", "T", 336.543, "DMASS", 1.304, "PR::Oxygen")
371621.8597497555

julia> PropsSI("UMASS", "T", 336.543, "DMASS", 1.304, "PR::Oxygen")
371621.8597497555
```

But with python, calling the same library:
```python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> CoolProp = cdll.LoadLibrary('/usr/lib/x86_64-linux-gnu/julia/CoolProp.so')
>>> PropsSI = CoolProp.PropsSI
>>> PropsSI.restype = c_double
>>> PropsSI(c_char_p("UMASS"), c_char_p("T"),c_double(336.543),c_char_p("DMASS"),c_double(1.304),c_char_p("PR::Oxygen"))
371621.85975
>>> PropsSI(c_char_p("UMASS"), c_char_p("T"),c_double(336.543),c_char_p("DMASS"),c_double(1.304),c_char_p("PR::Oxygen"))
inf
```
```Python
>>> import ctypes
>>> lib = ctypes.cdll.LoadLibrary("/usr/lib/x86_64-linux-gnu/julia/CoolProp.so")
>>> PropsSI = lib.PropsSI
>>> PropsSI.argtypes = (ctypes.c_char_p, ctypes.c_char_p, ctypes.c_double, ctypes.c_char_p, ctypes.c_double, ctypes.c_char_p)
>>> PropsSI.restype = ctypes.c_double
>>> PropsSI(b"UMASS", b"T", 336.543, b"DMASS", 1.304, ctypes.create_string_buffer("PR::Oxygen", 10))
371621.8597497555
>>> PropsSI(b"UMASS", b"T", 336.543, b"DMASS", 1.304, ctypes.create_string_buffer("PR::Oxygen", 10))
inf
```
But wit HEOS, this work without problems:
```Python
>>> PropsSI(b"UMASS", b"T", 336.543, b"DMASS", 1.304, ctypes.create_string_buffer("Oxygen", 10))
218997.43672292016
>>> PropsSI(b"UMASS", b"T", 336.543, b"DMASS", 1.304, ctypes.create_string_buffer("Oxygen", 10))
218997.43672292016
```

This is really strange for me as it is the exact same library....

(test made using self compiled shared library from this morning, with default settings, on Ubuntu gnome 64 bit 16.10)

**Comment by ibell** [comment]
Yes, it is VERY strange, and I have thus far not been able to figure out
why he sees this behavior.

**Comment by spmuppar** [comment]
@JonWel Yes, I realized now..
Changed platform to C++

**Comment by JonWel** [comment]
@spmuppar I have some examples I uses as test [here](https://github.com/CoolProp/ExternalMedia/blob/master/Projects/Tests/coolprop_comparisons.cpp).
(I think there are other test files more suitable, but at least it is already of some help)

**Comment by spmuppar** [comment]
@JonWel 
Thank you so much.!!

**Comment by jowr** [comment]
I guess this was solved
