### ISSUE TITLE
Viscosity of liquid refrigerant

### ISSUE THREAD

**Issue by Eztarok** [CoolProp/CoolProp#1487]
Hello,

do you plan to add a function to get the dynamic viscosity of liquid refrigerant ? Right now, only the viscosity of gaseous refrigerant can be calculated.

Thanks!

**Comment by ibell** [comment]
That's not true - the viscosity correlations for the refrigerants are valid
in liquid and vapor phases. Can you share an input that doesn't work in the
liquid phase?

**Comment by Eztarok** [comment]
I used the PropsSI function with the parameter "viscosity". For example :

CoolProp.PropsSI('V','T',300,'P',1E6,'R410A')
1.3315828737632539e-05

Using Refprop with Excel :
Viscosity($A$1;"TP"; "SI";300;1)*0.000001
1.35E-05
Viscosity("R410A";"Tliq"; "SI";300)*0.000001
1.15E-04

I think I missed something....

**Comment by ibell** [comment]
What's the "problem" here?

The viscosity models for mixtures in CoolProp are ONLY approximate.  For
better viscosity models, you need REFPROP.

**Comment by Eztarok** [comment]
The problem is the viscosity from CoolProp refers to the vapor phase. (~1.35E-05). Is there any way to get the viscosity of liquid phase ?

**Comment by henningjp** [comment]
Your T,P state point is in the vapor phase.  If you provide a T,P state point in the liquid phase you will get the liquid viscosity.  If you want the values at a saturation temperature (like you did with REFPROP), provide inputs of "T" and "Q"; where "Q" is vapor quality at 1 for vapor and 0 for liquid.  This is the state point on the saturation curve.

**Comment by Eztarok** [comment]
Thank you henningjp, that's what I missed ! ;)
