### ISSUE TITLE
apply_simple_mixing rule in matlab

### ISSUE THREAD

**Issue by calla80** [CoolProp/CoolProp#1496]
I'm using coolprop on Matlab, and I ve problems in creating a user defined mixture:

With this:

addpath('C:\Users\Claudia\Documents\MATLAB\Main')
CAS_He = CoolProp.get_fluid_param_string('Helium','CAS');
CAS_Xe = CoolProp.get_fluid_param_string('Xenon','CAS');
CoolProp.apply_simple_mixing_rule(CAS_He,CAS_Xe,'linear');

I got this error:
Warning: function AbstractState_apply_simple_mixing_rule requires at least 4 arguments
Error using CoolPropMATLAB_wrap
Fatal error.
Error in CoolProp.apply_simple_mixing_rule (line 2)
[varargout{1:nargout}] = CoolPropMATLAB_wrap(219,self, varargin{:});
Error in mixture_G (line 8)
CoolProp.apply_simple_mixing_rule(CAS_He,CAS_Xe,'linear');

How can I solve this problem?

**Comment by ibell** [comment]
Well you could use python :). Where it works perfectly!

But seriously, I don't know why this is happening

**Comment by calla80** [comment]
:-( unfortunately I need to use coolprop with matlab...
but If I look at the apply_simple_mixing_rule code it seems to require four arguments as follow:

 function varargout = apply_simple_mixing_rule(self,varargin)
      [varargout{1:nargout}] = CoolPropMATLAB_wrap(219, self, varargin{:});

whats' "self"?

**Comment by ibell** [comment]
Hmm its calling the method on AbstractState rather than the global call.
Is your installation messed up?  That seems wrong...  Never tried that in
MATLAB before...

**Comment by calla80** [comment]
It seems that apply_simple_mixing_rule method is only included in AbstractState ... I tried to add the fourth argument as  CoolProp.apply_simple_mixing_rule('AbstractState',CAS_He,CAS_Xe,'linear') but even if it runs when I write  CoolProp.PropsSI('Dmass','T',300,'P',101325,'Helium[0.5]&Xenon[0.5]')
I get this:
Warning: Initialize failed for backend: "?", fluid: "Helium&Xenon" fractions "[ 0.5000000000, 0.5000000000 ]"; error: Could not
match the binary pair [7440-59-7,7440-63-3] - for now this is an error._

**Comment by ibell** [comment]
Have you see #1497 ? That is a better solution.
