### ISSUE TITLE
[Discussion] Deprecating the current MATLAB wrapper in favor of MATLAB->python calls

### ISSUE THREAD

**Issue by Dev-iL** [CoolProp/CoolProp#1497]
Hi everybody!
Let me start by saying that you've done an amazing job with the tool! It's really easy to use and provides a lot of useful information!

I have stumbled upon CoolProp several days ago, and was initially happy to learn that there was a MATLAB interface implemented. However, upon further investigation, I noticed that the MATLAB interface is problematic in some regards:
 - It doesn't (easily?) allow vectorized evaluation (#701).
 - It doesn't contain a proper build-script for generating `.mex` ([example](https://github.com/kyamagu/mexopencv/blob/master/%2Bmexopencv/make.m)), which means that one cannot even attempt to fix the interface, and must instead rely on the precompiled binaries from sourceforge. (Am I missing something? There's no `MATLABBuilder.m` anywhere...).

For these reasons, and seeing how the python interface of CoolProp is well-maintained and highly advocated, I've been experimenting with the [MATLAB->Python interface](https://www.mathworks.com/help/matlab/getting-started-with-python.html) (introduced in **R2014b**) - and the results are very promising!

For the users - it requires an "inconvenience" of installing python and some libraries (`numpy`, `CoolProp` and dependencies), but it also means almost instant access to the full functionality of CoolProp from MATLAB. For the developers - one less headache.

Therefore, I highly recommend considering making these the official guidelines (at least for recent MATLAB versions) and updating the library accordingly. I will submit a PR if needed.

----
Here's a demonstration (tested on R2017a and R2015b, with Anaconda3+python 3.6.1):
```matlab
function props = CoolPropsWrapper(varargin)
% CoolPropsWrapper is a MATLAB wrapper for the python binding of CoolProps.
%   The purpose of this wrapper is to allow vectorized evaluation from MATLAB.
%{
 INPUTS:
 varargin{1} - a *cell array of char arrays* representing the desired outputs, according to:
    http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function
 varargin{2} - A *char array* representing the meaning of the next input vector.
 varargin{3} - Some row vector of doubles.
 varargin{4} - A *char array* representing the meaning of the next input vector.
 varargin{5} - Some row vector of doubles.
 varargin{6} - a *char array* representing the fluid name, according to:
    http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids
  Specifying a mixture is possible, but requires additional steps as shown in:
    http://www.coolprop.org/fluid_properties/Mixtures.html
%}
%% Handling inputs:
if nargin == 0
  varargin = cell(6,1);
  varargin{1} = {'V','D'};
  varargin{2} = 'T';
  varargin{3} = 200:10:6000;
  varargin{4} = 'P';
  varargin{5} = 5000:100:20000;
  varargin{6} = 'Argon';
end
%% Importing the python module:
np = py.importlib.import_module('numpy');
CP = py.importlib.import_module('CoolProp.CoolProp');
%% Generating inputs:
[XX,YY] = meshgrid(varargin{3}, varargin{5}); 
inputs = {py.list(varargin{1}), varargin{2}, np.ravel(XX(:).'), ...
                                varargin{4}, np.ravel(YY(:).'), ...
                                varargin{6}};
%% Calling PropsSI, converting python output to MATLAB and reshaping: 
props = reshape(matpy.nparray2mat(CP.PropsSI(inputs{:})), [size(XX) inputs{1}.length]);
```

Where `matpy`<sup><sub>[1](https://www.mathworks.com/matlabcentral/answers/157347-convert-python-numpy-array-to-double#comment_373119)</sub></sup> is:
```matlab
classdef matpy
  
  methods (Access = public, Static = true)
    
    function result = mat2nparray( matarray )
      %mat2nparray Convert a Matlab array into an nparray
      %   Convert an n-dimensional Matlab array into an equivalent nparray
      data_size = size(matarray);
      if length(data_size)==1
        % 1-D vectors are trivial
        result = py.numpy.array(matarray);
      elseif length(data_size)==2
        % A transpose operation is required either in Matlab, or in Python due
        % to the difference between row major and column major ordering
        transpose = matarray';
        % Pass the array to Python as a vector, and then reshape to the correct
        % size
        result = py.numpy.reshape(transpose(:)', int32(data_size));
      else
        % For an n-dimensional array, transpose the first two dimensions to
        % sort the storage ordering issue
        transpose = permute(matarray,[length(data_size):-1:1]);
        % Pass it to python, and then reshape to the python style of matrix
        % sizing
        result = py.numpy.reshape(transpose(:)', int32(fliplr(size(transpose))));
      end
    end
    
    function result = nparray2mat( nparray )
      %nparray2mat Convert an nparray from numpy to a Matlab array
      %   Convert an n-dimensional nparray into an equivalent Matlab array
      data_size = cellfun(@int64,cell(nparray.shape));
      if any(numel(data_size) == [0,1])
        % This is a simple operation
        result = double(py.array.array('d', py.numpy.nditer(nparray)));
      elseif numel(data_size)==2
        % order='F' is used to get data in column-major order (as in Fortran
        % 'F' and Matlab)
        result = reshape(double(py.array.array('d', ...
          py.numpy.nditer(nparray, pyargs('order', 'F')))), ...
          data_size);
      else
        % For multidimensional arrays more manipulation is required
        % First recover in python order (C contiguous order)
        result = double(py.array.array('d', ...
          py.numpy.nditer(nparray, pyargs('order', 'C'))));
        % Switch the order of the dimensions (as Python views this in the
        % opposite order to Matlab) and reshape to the corresponding C-like
        % array
        result = reshape(result,fliplr(data_size));
        % Now transpose rows and columns of the 2D sub-arrays to arrive at the
        % correct Matlab structuring
        result = permute(result,[length(data_size):-1:1]);
      end
    end
  end
end
```

**Comment by ibell** [comment]
I'm 100% in support of this change.  Can you please do some timing tests with the low-level interface between the swig wrapper and the python interface?  I would be especially interested to hear about a density call as a function of T and p.  I would not cry at all about saying goodbye to swig for matlab.

One question - what if you have multiple copies of python installed on your computer?  Is that a problem?  That is a common case with Anaconda or virtualenv.

**Comment by Dev-iL** [comment]
@ibell I'm happy to hear that my idea makes sense!

Regarding multiple python versions - the default version of python that is chosen is, I believe, the first `python.exe` found on your `PATH`. This can be modified via the [`pyversion` command](https://www.mathworks.com/help/matlab/ref/pyversion.html) (within its limitations):
```matlab
>> pyversion

       version: '2.7'
    executable: 'E:\Anaconda\Python27\python.EXE'
       library: 'E:\Anaconda\Python27\python27.dll'
          home: 'E:\Anaconda\Python27'
      isloaded: 0

>> pyversion E:\Anaconda3\python.exe
>> pyversion

       version: '3.6'
    executable: 'E:\Serious\Anaconda3\python.exe'
       library: 'E:\Serious\Anaconda3\python36.dll'
          home: 'E:\Serious\Anaconda3'
      isloaded: 0
```
(note that I'm using python 3.6, even though it isn't [officially supported](https://www.mathworks.com/help/matlab/matlab_external/system-and-configuration-requirements.html#buialof-38 "As of the time of writing, this points to the R2017a documentations") by even the most current version of MATLAB - it's not a problem for our purposes).

----------
As for the benchmark - I won't be able to do this before the coming Monday. 

Also, I'd appreciate if you could provide me with the code you'd like to test on the swig side. I'm assuming it will be very similar to [the example](http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#calling-low-level-interface-through-dll), yet I am somewhat reluctant to study this interface for the sole purpose of creating a benchmark.

**Comment by ibell** [comment]
*Ping* The sooner this is working, the better!

**Comment by Dev-iL** [comment]
I finally found the time to do a limited benchmark - **for ~90k input points, results indicate a 2.4% difference in runtime in favor of the low level interface**. Considering the benefits in functionality and simplicity - I wouldn't think twice.

My system is: Win7 x64, 32GB @ 1600, Intel i7-3770 CPU @ 3.40GHz.

Here's the benchmarking code:
```matlab
%
% By Dev-iL, 28/05/2017
%
function WrapperBenchmark
%% Inputs
IN = cell(6,1);  
IN{1} = {'V'};
IN{2} = 'T';
IN{3} = 200:10:6000;
IN{4} = 'P';
IN{5} = 5000:100:20000;
IN{6} = 'Argon';

% Configuring inputs:    
T = IN{3};
P = IN{5};
[TT,PP] = meshgrid(T,P);
TT = TT(:).'; PP = PP(:).';
len = numel(TT);
%% Initialization:
  initCoolPropDLL();
%% Configuring low-level wrapper:
  % Configuring input style:
  [hIP,~] = calllib('coolprop','get_input_pair_index','PT_INPUTS');
  
  % Choosing parameters to compute:
  [outputs, ~] = calllib('coolprop','get_param_index','V');
  
  % Selecting backend and fluid:
  buffer_size = 1000;
  ierr = 0;
  b = (1:1:buffer_size);
  herr = char(b);
  backend = 'HEOS';
  fluid = IN{6};
  [hAS, ~] = calllib('coolprop','AbstractState_factory',...
                     backend, fluid, ierr, herr, buffer_size); 
  
  % Configuring pointers:
  in1Ptr = libpointer('doublePtr',PP);
  in2Ptr = libpointer('doublePtr',TT);
  out1Ptr = libpointer('doublePtr', zeros(len,1));
  
%% Configuring python wrapper:
  inputs = {py.list(IN{1}), IN{2}, py.numpy.ravel(TT), ...
                            IN{4}, py.numpy.ravel(PP), ...
                            IN{6}};
%% Evaluating & getting output as MATLAB array(s):
% Low-level:
calllib('coolprop','AbstractState_update_and_1_out',hAS,hIP,in1Ptr,in2Ptr,...
        len, outputs, out1Ptr, ierr, herr, buffer_size); 
OUT_dll = get(out1Ptr, 'Value'); 
  
% Python:
OUT_py = matpy.nparray2mat(py.CoolProp.CoolProp.PropsSI(inputs{:})).';

%% Equality test:
fprintf(1, 'Absolute sum of residuals between python and low-level: %d\n', sum(abs(OUT_dll(:) - OUT_py(:))) );

%% Comparative benchmark:
t = [timeit(@eval_ll,1), timeit(@eval_py,1)];
fprintf(1, 'Runtime in seconds [lowlev py]: %s\n', mat2str(t,5) );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Helper functions:
function out = eval_ll
  calllib('coolprop','AbstractState_update_and_1_out',hAS,hIP,in1Ptr,in2Ptr,...
        len, outputs, out1Ptr, ierr, herr, buffer_size); 
  out = get(out1Ptr, 'Value'); 
end

function out = eval_py
out = matpy.nparray2mat(py.CoolProp.CoolProp.PropsSI(inputs{:})).';
end

end


function initCoolPropDLL()

path_to_lib = 'F:\Anaconda3\Lib\site-packages\CoolProp\libs\shared'; %specify path to coolprop shared library
path_to_include= 'F:\Anaconda3\Lib\site-packages\CoolProp\include'; %specify path to coolprop's include folder

% Loading shared library
if ~libisloaded('coolprop') %checking whether library is already loaded
    addpath(path_to_lib)
    addpath(path_to_include)    
    if ispc
        libname = 'CoolProp';
    else
        libname = 'libCoolProp'; % OSX and linux
    end
    loadlibrary(libname,'CoolPropLib.h','includepath',path_to_include,'alias','coolprop'); % loading library with alias coolprop
    disp('loaded CoolProp shared library.')
    disp('loaded these functions: ')
    libfunctions coolprop
end

end
```

**Comment by ibell** [comment]
Well, that seems fairly conclusive.  Thank you very much for running these tests.

**Comment by Dev-iL** [comment]
@ibell Should I organize this and submit a PR?

**Comment by ibell** [comment]
Bump!  Looking forward to this, and to learning from this experience to
apply the same thing to the REFPROP wrapper

**Comment by Dev-iL** [comment]
@ibell Sorry for the delay! I finally found the time to work on this. Please see https://github.com/Dev-iL/CoolProp/commit/097b1c96f5c8e6fd67df4f75b2a7729acb3485de . If you have any comments or questions at this stage, please let me know. I'll create a PR in a few days.

**Comment by jowr** [comment]
This looks very promising - thanks! May I ask you to create the documentation in rst instead of md? We use Sphinx to generate the docs and I am not sure it can handle md files.

**Comment by Dev-iL** [comment]
@jowr Sure, no problem. Let me look into that (completely unfamiliar with that).

**Comment by ibell** [comment]
Yes, sphinx cannot handle markdown; it's RST only.  I would prefer to not
totally remove the MEX stuff as someone might need that later on.  But
other than that, I am very appreciative of the work you have done on the
python interface for MATLAB; it looks great.  I'm keen to get this
finalized as soon as possible so that we can drop our builds for MATLAB
from the build matrix.

**Comment by Dev-iL** [comment]
@ibell @jowr Alright gentlemen, so how do we proceed? 

Regarding the MEX stuff - I still don't fully understand why there is a difference between the [SourceForge](https://sourceforge.net/projects/coolprop/files/CoolProp/nightly/MATLAB/) and the [GitHub ](https://github.com/CoolProp/CoolProp/tree/master/wrappers/MATLAB) versions of the code. As I mentioned in my very first comment above, the GitHub version is missing some files (as far as I can tell) that are required to build the `.mex**` files from a clean clone of the repository. Which led me to the conclusion that these files were there mostly for documentation purposes. However, I too was not 100% comfortable with deleting working code, so moving forward, I suggest we make a `legacy` (or `v1` etc.)  folder inside the MATLAB wrapper, and move both the old code and the last prebuilt `.mex` files (from SF) into it for posterity.

Let us decide on an acceptable course of action and move on.

P.S. I have a small difficulty with the `.rst` where I couldn't quite get the desired formatting. Something with the indentation of a numbered list wasn't working, would be great if any of you could help me sort this out.

**Comment by jowr** [comment]
Maybe it helps to look at the exisiting docs? A numbered list is used here (http://coolprop.sourceforge.net/develop/buildbot.html) and the code is located in this rst file (https://github.com/CoolProp/CoolProp/blob/master/Web/develop/buildbot.rst). 

The GitHub version only contains code. I would guess that the files you refer to are the ones generated by SWIG and since they are generated automatically, they should be under version control. I would opt for removing that legacy stuff. If people really need it, they should go with the older release that contains thos files. The next version (6.1.1 or 6.2) should not include these files since we are interested in getting rid of the MATLAB builders.

**Comment by ibell** [comment]
More like dying to get rid of the MATLAB builders, but otherwise @jowr is
right on.

As a REFPROP developer, I'm curious to see how much difficulty we will run
into with the less technologically-savvy MATLAB users having to also get
python working on their computer.  I suspect there will be some issues and
resistance.  But we shall see.

I'll add some docs about working with conda environments + MATLAB after the
main PR is done.

**Comment by jowr** [comment]
Good to see #1543 coming along. Is it possible to use the state class through Python? If not, we might want to mention http://coolprop.sourceforge.net/coolprop/wrappers/MATLAB/index.html#calling-low-level-interface-through-dll in the MATLAB docs.

**Comment by Dev-iL** [comment]
@jowr I don't understand your question - would you please elaborate? What is the "state class" that you mentioned? If you provide some python code I can test it in (or adapt it to) MATLAB.

**Comment by jowr** [comment]
For example here: http://coolprop.sourceforge.net/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface

**Comment by Dev-iL** [comment]
@jowr It work w/o any problems (tested on MATLAB R2017a where Strings (`"..."`) are supported).

```matlab
CoolProp = py.importlib.import_module('CoolProp.CoolProp');
HEOS = CoolProp.AbstractState('HEOS', 'Water');

HEOS.update(CoolProp.DmolarT_INPUTS, 1e-6, 300);
HEOS.specify_phase(CoolProp.iphase_gas);
HEOS.specify_phase(CoolProp.iphase_unknown);

HEOS = CoolProp.AbstractState('HEOS', 'Methane&Ethane');
HEOS.set_mole_fractions([0.2,0.8]);
HEOS.update(CoolProp.PQ_INPUTS, 101325, 1);
disp(HEOS.saturated_liquid_keyed_output(CoolProp.iDmolar));
disp(HEOS.saturated_vapor_keyed_output(CoolProp.iDmolar));
disp(HEOS.mole_fractions_liquid());
disp(HEOS.mole_fractions_vapor());
```
Yields:
```none
   1.8275e+04

   69.5031

  Python list with no properties.

    [0.006106791218188617, 0.9938932087818113]

  Python list with no properties.

    [0.2, 0.8]
```

Moreover, it also works also with String inputs (introduced in R2016b), i.e.:
```matlab
HEOS = CoolProp.AbstractState("HEOS", "Water");
```

**Comment by jowr** [comment]
Thanks for trying, this is super relevant and should be added to the docs! Great job!

**Comment by jowr** [comment]
To me, #1543 looks good. @ibell, any more comments? Guess we have to update the buildbots accordingly (swig wrapper, matlab builder, ?)
