### ISSUE TITLE
bug?: ValueError: Saturation pressure is within 1e-4 % of given p

### ISSUE THREAD

**Issue by norihiro-w** [CoolProp/CoolProp#1498]
Hi, the following command  
```python
CP.PropsSI("Phase", 'P', 5677200.0, 'T', 545.15, 'Water')
```
outputs error
```
ValueError: Saturation pressure [5.6772e+06 Pa] corresponding to T [545.15 K] is within 1e-4 % of given p [5.6772e+06 Pa] : PropsSI("Phase","P",5677200,"T",545.15,"Water")
```
what's wrong here?

**Comment by ibell** [comment]
Not an error exactly....   If you are at saturation temperature and
pressure, there are two possible answers, liquid and vapor, and CoolProp
doesn't allow you to do that, giving an error.  You could try to specify
the phase, that should get rid of this exception.

**Comment by norihiro-w** [comment]
thanks for the quick reply! i thought the function should returns "two-phase" at that condition. Is setting "Q" a correct way to specify the phase? sorry for stupid questions...

**Comment by ibell** [comment]
Well, you have PQ and QT as options if you know one of T or P and you are
at saturation.  Otherwise you can use the specify_phase function in low
level interface

**Comment by norihiro-w** [comment]
thanks
