### ISSUE TITLE
Example of flash calculation for mixture in two phase region

### ISSUE THREAD

**Issue by AntonBaluev** [CoolProp/CoolProp#1500]
Hello,
Is there any example of PT flash calculation for mixture?
Inputs: feed mixture (fluid names) with mole fractions, pressure and temperature.
Output: phases in equilibrium, mole fractions of each phases.
Regards,
Anton.

**Comment by ibell** [comment]
This is as close as you are going to get:
http://www.coolprop.org/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface
.  Substitute PT for QT, and there you go...  You might get failures, in
which case you will need REFPROP.

**Comment by thorade** [comment]
Closing for now, please reopen if there are further questions.
