### ISSUE TITLE
Building Documentation

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1501]
Several issues here when trying to build the documentation:

1. Should the [instructions](http://www.coolprop.org/develop/documentation.html) (minus step 0. for mac OS) work on Windows using Anaconda?  Has this been done?  I got it to work, sort of, but with much jumping through hoops and it doesn't all build correctly.  I had to fetch many 64-bit versions of the requisite modules and install the wheel files manually.  There's still some weird error at the beginning of the build about matplotlib calls being out of order.

2. There is a serious problem with converting the fluid_properties/mixtures.rst file.  This one is not just me.  Check out the [mixtures page](http://www.coolprop.org/dev/fluid_properties/Mixtures.html) on the CoolProp/dev documentation.  Something going wrong here in the ipython examples and this happens throughout the picture.  @ibell made a commit to this .rst file in the offending area some time back, but I don't think this is causing the errors.  ipython seems to think that binary pair data for 'Helium' and 'Xenon' already exist; yet when I run these scripts manually in Anaconda, they run fine.

3. Another error occurs that floods the stdout with messages and I can't capture where it is coming from.  It looks, though, like an example is trying to generate plots and it is calling flash routines with input parameters that are out of bounds.  See sample message below:

    c:\program files\anaconda2\lib\site-packages\CoolProp\Plots\Common.py:622: UserWarning: An error occurred for inputs 210905.712095, 3269.231633 with index (206L,): HmolarSmolar: [HSFLSH error 200] h-s inputs are two-phase or out of bounds, iterative routine is not available to find a solution.   

    You have to do a clean build (make clean html) to get these error message to print.

4. Lots of errors for missing .csv and tag files that it can't find as well as a couple of include files.

5. Oh yeah, and : **WARNING: logo file '_static/CoolPropLogo.png' does not exist**  This is easy to fix, but shouldn't it be in _static/  on the repository?

**Comment by henningjp** [comment]
Python 2.7, by the way....

**Comment by jowr** [comment]
Hi and thanks for looking into this. A good starting point to build the docs is the [buildbot configuration file](https://github.com/CoolProp/CoolProp/blob/master/dev/buildbot/master/master.cfg#L392).  These are the steps that are executed on the buildbot that creates the documentation. Before doxygen and sphinx are called, the script located at [`Web/scripts/__init__.py`](https://github.com/CoolProp/CoolProp/blob/master/Web/scripts/__init__.py), which also calls a number of scripts listed at [lines 106 through 109](https://github.com/CoolProp/CoolProp/blob/master/Web/scripts/__init__.py#L106-L109)

**Comment by henningjp** [comment]
So, these lines worry me:

```
    if 'win' in platform.lower():
          raise ValueError("The docs cannot be build on a Windows machine, we rely on rsync...")
```
Is this a show stopper?

**Comment by jowr** [comment]
Not really, we included it since we use rsync to publish the docs. You should still be able to build then docs.

**Comment by henningjp** [comment]
@jowr Thanks!  This helps.  I'm getting there slowly.  I'll close this with a PR that updates the documentation page for building on 64-bit Windows.

**Comment by henningjp** [comment]
@jowr It took all summer, but I think I have it sorted.  I can build **_most_** of the web docs from Windows under Anaconda.  I'm not sure it's possible to get **pdfnup** running under Windows Anaconda.  However, that only holds up the incompressible verification sheets.  PR coming today that will update the instructions on the [Documentation](http://www.coolprop.org/develop/documentation.html) web page.  I'll need you and @ibell to look it over to make sure I haven't overly complicated things.

Two questions for my own education:

1. The top section on the [Documentation](http://www.coolprop.org/develop/documentation.html) web page has a "Step 0" that starts off with "0. On a Mac system,....".  Was the whole section intended to be for Mac use, or just step 0?  Step 0 looks like it was thrown in as an afterthought.
2. Is the buildbot a Mac system where the official coolprop pages get built?

Thanks!

**Comment by jowr** [comment]
Yes, the docs are currently built on a Mac, before that it was a Linux machine thus the addition of point "0."
