### ISSUE TITLE
Dear Please help.

### ISSUE THREAD

**Issue by MarioKrstovic** [CoolProp/CoolProp#1505]
I am Mario Krstovic PhD student at Strathclyde. I  just started using CoolProp and installed it according the instructions (at least I believe so), and hope that my question is not too stupid. When I use function for example density as function of pressure and temperature , sat liquid or sat vapour it works. Simple example: = CoolProp.PropsSI('D', 'T',Temp, 'P', P_Pressure, fluid_type) it works, but unfortunately when I try  to determine Critical temperature, pressure, Prantl number it does not work.  For example, when  if I type: CoolProp.PropsSI('Tcrit', 'CO2') it says:Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(202,'_wrap_PropsSI',varargin{:}); It looks like I should install this wrapper how to do it? I was trying to find functions given through documentation. Thank you for your assistance,

 Kind regards

**Comment by thorade** [comment]
It would be easier to help you, if you mark code as code and use a meanigful title (you can still edit your issue, there are buttons for formatting). Use line breaks and paragraphs. Also, you should describe how to reproduce your error, by stating what wrapper language you use, what CoolProp version you use, link to the instructions you have followed, what operating system you use, and so on. Make it as easy as possible to help you.

From the error message you have shown, it seems you are using the Matlab wrapper. There are a couple of open issues for this wrapper, have you read them? 
https://github.com/CoolProp/CoolProp/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20matlab
Especially, you should read #1497, where it is shown how to use the Matlab->Python nterface (and then, interface CoolProp via Python). Maybe that solution could work for you, too?

**Comment by henningjp** [comment]
@MarioKrstovic - PropsSI needs all of the parameters.  Put T and P back in the call.  Their values are ignored for trivial properties like Tcrit.  Or, instead, use Props1SI, which only requires the two parameters you specified.  Pretty sure this is the problem.  Please close this issue if it does.

**Comment by MarioKrstovic** [comment]
Dear Jeff Henning and  Matthis Thorade,

Thank you for your answers it is working now, I needed to put all the parameters in and i have not  been using the function right as you explained me. 
Kind regards,

Mario Krstovic
