### ISSUE TITLE
Using Coolprop in Matlab with symbol type argument

### ISSUE THREAD

**Issue by everlastingorchid** [CoolProp/CoolProp#1508]
Hi

I successfully installed CoolProp for Matlab using the following instructions.
http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#matlab

Using CoolProp from the command line is not a problem. The problem occurs when using the command in the solve function. It gives a fatal error.
Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(316,varargin{:});
The error occurs at this line of code
T01==CoolProp.PropsSI('T','S',s1,'H',h01,fluid)
In this expression h01 is of the symbol type, also of type 'double'.

Is there a way to work around this issue?

Thank you

**Comment by ibell** [comment]
Yes, use fsolve, not solve.

**Comment by everlastingorchid** [comment]
The system of equations is fully determined. By using fsolve I would have to state a starting value for each variable. That's why I opted for a symbolic solver. What would your advice be in this case?

**Comment by ibell** [comment]
Simply put, you can't use solve with CoolProp.  It's not a symbolic
object.  Use fsolve :(

On Thu, Jun 15, 2017 at 8:25 AM, everlastingorchid <notifications@github.com

**Comment by everlastingorchid** [comment]
Thank you for your time :)
