### ISSUE TITLE
Temperature to QT_flash

### ISSUE THREAD

**Issue by nnc6** [CoolProp/CoolProp#1519]
Hi, I'm building a chart with all the properties of refrigerants (r290 and r404a for now) to make all the calculation I need for my work. 
When I'm trying to calculate properties above a certain temperature I'm getting this error "temperature to Qt_flash [347.15K] must be in range [199.9, 345.27 K] : propSI("P", "T", 347.15,"Q",1,"R404A")". How can I solve?

**Comment by ibell** [comment]
You are above the maximum condensing temperature for R404A, so there is no
possibility to carry out this calculation.

**Comment by nnc6** [comment]
Wtf you're right! I was so focused on discharge temperatures that I didn't realized they could be above biphase region... Thanks a lot for your reply!
