### ISSUE TITLE
How using Refprop predefined mix refrigerant with coolprop interface ?

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#1520]
Hello,

The coolprop interface allows to use Refprop refrigerants.
Example : CP.PropsSI('D','T',300,'P',101325,'REFPROP::R32').
This calling is possible cause the file R32.FLD exists in the folder ".../REFPROP/fluids"

Is Coolprop able to call predefined Refprop refrigerant mixture in the .MIX files (for example R452B.MIX) contained in the folder ".../REFPROP/mixture" ?

**Comment by ibell** [comment]
Yes, that should work fine, with something like REFPROP::R410A.MIX as the fluid name.  If not, that's a bug. 

On non-windows, watch out for the case sensitivity of the mixture name
