### ISSUE TITLE
Error using CoolPropMATLAB_wrap

### ISSUE THREAD

**Issue by Alicque** [CoolProp/CoolProp#1522]
Hi! I've started using CoolProp few days ago, I've wrote down in my Matlab code this line:

Gas='nitrogen';
T_gas1=1123;%+(30*(i-1)); %Hot gases temperature [K]
P_gas=1.01325e5; %Gases mean pressure (1atm) [Pa]

rho_g= CoolProp.PropsSI('D','T',T_gas1,'P',P_gas,gas);
mu_g= CoolProp.PropsSI('V','T',T_gas1,'P',P_gas,gas);
k_g= CoolProp.PropsSI('L','T',T_gas1,'P',P_gas,gas);
cp_g= CoolProp.PropsSI('C','T',T_gas1,'P',P_gas,gas);

but when I try to run it I get this error:

Failure in function PropsSI.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(202,'_wrap_PropsSI',varargin{:});

Anyone could help?
With similar previous line it works just fine..

Thanks a lot!

**Comment by ibell** [comment]
There must be more to that error than what you posted - can you please post
the entire output?  Also good would be a screenshot.

Please also see https://github.com/CoolProp/CoolProp/issues/1497 - that's
the new recommendation for MATLAB interfacing

**Comment by Alicque** [comment]
I have just solve it! There was an error in the vector which resulted in a T= 0 K, so pretty comprehensible that it didn't work out!!
Thanks a lot for you time and help!

**Comment by thorade** [comment]
Closing this issue, as it seems to be solved.
