### ISSUE TITLE
recieve range of feasible values for enthalpy in 1phase PY flash

### ISSUE THREAD

**Issue by fwitte** [CoolProp/CoolProp#1526]
Hello everybody,
I use CoolProp for calculating fluid properties within a newton algorithm. In the solving process it happens quite often that values for enthalpy exceed the limits (both directions). I found a non satisfying workaround (slows down the solving process), thus I wondered if it is possible to get the lower and upper bound for the enthalpy at a given pressure. For example:

`PropsSI("T","H",100000,"P",2000,"air")`
results in
`ValueError: unable to solve 1phase PY flash with Tmin=59,75, Tmax=3000 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Hmolar [2896,55 J/mol] is below the minimum value of 5373,71242625 J/mol`

In order to make my solving process faster I would like to set H=2896,55 J/mol / PropsSI('M','air')

I am working with CoolProp 6.1.0 in python 3.5.2.

Thanks and have a nice day!

**Comment by thorade** [comment]
Just an idea: The underlying equation of state really uses D and T as inputs, so that input should always work and not use iterations. PT then has to iterate one variable, PH has to iteratively find two variables. Can you use PT instead of PH?

To find the feasible range, you could try to calculate H=H(D,T) or H=H(P,T) or H=H(P,D), with min and max values for P,D and T, these might be easier to estimate.

**Comment by fwitte** [comment]
Hey thorade,
I am very sorry my answer is this late. I had to do some other stuff and somehow forgot about this. My system of equations has massflows, pressure and enthalpy as variables. Thus I would need to make a lot of changes in my program. Is it not possible to calculate the maximum/minimum value just like CoolProp does, when throwing this exception?
Thank you and have a nice weekend!

**Comment by thorade** [comment]
I do not know how CoolProp does it, but for a given P you should be able to calculate Hmax as:
```
Tmax = 3000
Hmax = PropsSI("H","T",Tmax,"P",2000,"air")
```

**Comment by fwitte** [comment]
Solution works for me, thanks for your help! Have a nice day!

**Comment by rddaz2013** [comment]
> ValueError: unable to solve 1phase PY flash with Tmin=59,75, Tmax=3000 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Hmolar [2896,55 J/mol] is below the minimum value of 5373,71242625 J/mol

air at 60K -> mostly liquid so - no flash ? 
60K ~ "Tripelpunkttemperatur"
