### ISSUE TITLE
Buildbot slaves need reconfiguration

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1529]
@jowr - the buildslaves all need to be deleted so that they can get clean a checkout and resolve the issues with rapidjson.  I think I've sorted out mine, but all yours need to be deleted completely

**Comment by jowr** [comment]
Working on it

**Comment by ibell** [comment]
We are mostly back up, except for these two builds that need to be deleted so they can do a fresh checkout to fix the super annoying issue with rapidjson:
```
shared_library-linux-32bit 
shared_library-linux-64bit
```

**Comment by ibell** [comment]
Also, any idea why the grid is not showing recent builds even though they are mostly working?

**Comment by ibell** [comment]
Same problem with:
```
Fortran-executable-linux-32bit-GCC-ExternC
Fortran-executable-linux-64bit-GCC-ExternC
```
They too need a delete and allow to re-clone

**Comment by jowr** [comment]
The recloning cannot solve this as the builders have moved to a brand new (and faster) Linux server. I'll have a look.

**Comment by jowr** [comment]
we should be up and running again

**Comment by ibell** [comment]
Thank you very much!  I was considering buying another build machine and
grabbing the other slaves; glad to see I don't need to.  I'll get the linux
one up and running again soon.
