### ISSUE TITLE
Linux slave dead

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1531]
@jowr - my linux virtual is kaput.  I guess I'll have to rebuild it, I'm thinking about not adding the matlab back to it, in that case I could put all of it in a docker container, which could be appealing.  What do you think?

**Comment by jowr** [comment]
Good idea, but you should not install proprietary software with a license in a container that you upload to docker hub.

**Comment by ibell** [comment]
Yup, I'm aware of that issue - we are pushing people to use MATLAB via python, in which case ALL the MATLAB horribleness in the builders will go away, finally.  So long as python works, MATLAB will too.

**Comment by ibell** [comment]
Oh well, I think we can live with this since the things being built by the linux slave were already pretty much deprecated.  The OSX slave would capture the *nix build failures mostly I think.
