### ISSUE TITLE
Matlab Wrapper - Mixture Syntax

### ISSUE THREAD

**Issue by jgilsoto** [CoolProp/CoolProp#1534]
Hello,
I tried to compile the matlab wrapper for the last version of CoolProp, 6.1.0
The point is that I cannot calculate properties for a mixture using the proposed syntax:
nitrogen[0.78]&oxygen[0.21]&argon[0.01]
Could you please propose a code for this mixture to run?
Thank you in advance.

**Comment by ibell** [comment]
Can you please post the entire call you tried and the error message you
received?

**Comment by jgilsoto** [comment]
Hello Ian,
I have reviewed my compilation and think I have a bit of a mess here. I will try to explain:
My aim was to compile the matlab wrapper in a Linux 32 bit platform (which i think is not available on any of the distros). So I downloaded the latest stable version 6.1.0 and dive into the matlab wrapper directory. In the readme it states:

To build the mex files on windows, you should enter these commands at the command prompt:

git clone https://github.com/ibell/coolprop coolprop-code
cd coolprop-code/wrappers/MATLAB
matlab -r MATLABBuilder.m

So I downloaded coolprop-code from https://github.com/ibell/coolprop and compile the matlab wrapper present on that distribution. By doing that, I did compile the old 4.2.6 coolprop version. I understand that mixture syntax is not available in such an old version.

The not working matlab instruction in case of 4.2.6 wrapper is:

T_in=PropsSI('T','P',PressureValue,'Q',0, 'nitrogen[0.72]&oxygen[0.21]&argon[0.07]');

I found a different Matlab wrapper distribution in version 6.0 including a windows pre-compiled wrapper, CoolPropMATLAB_wrap.mexwXX,  and a +CoolProp directory containing different m files.

In the case of 6.0 pre-compiled wrapper, the mixture syntax is working using the following instruction:

T_in=CoolProp.PropsSI('T','P',PressureValue,'Q',0, 'nitrogen[0.72]&oxygen[0.21]&argon[0.07]');

The problem using this approach is that I cannot compile CoolPropMATLAB_wrap.mexwXX on my own, because the instructions to do that are not available.

The last thing I have tried to do is to adapt the old 4.2.6 MATLABBuilder.m to be able to files Props.c, PropsSi.cpp and HAProps.cpp. The problem is that I cannot compile any of the files on ../../src directory. I feel I miss plenty of external references. On the other hand, I am a bit lost because the only working wrapper I have found (version 6.0) has different structure, including one and only wrapper and a libary directory +CoolProp.

I have also taken a look to:
http://www.coolprop.org/dev/coolprop/wrappers/MATLAB/index.html#id5
but I think that the instructions are too sophisticated for me. 

Any help on this topic will be appreciated, thanks!

**Comment by jgilsoto** [comment]
Hello,
By the way, the error I obtain using 4.2.6 wrapper in matlab is:

Error using PropsSI
CoolProp Error: CoolProp error: Your fluid name
[nitrogen[0.72]&oxygen[0.21]&argon[0.07]] is not a CoolProp fluid, a
REFPROP fluid, a brine or a liquid

Regards,

**Comment by ibell** [comment]
All of that is deprecated.  The only interface for MATLAB that will be actively supported going forward is that of calling CoolProp via python from MATLAB.
