### ISSUE TITLE
ERRO: 'division by zero' when call dll(v6.10) from vc2015

### ISSUE THREAD

**Issue by gas0189** [CoolProp/CoolProp#1536]
![default](https://user-images.githubusercontent.com/23023534/29311397-71097a8e-81e4-11e7-8719-a04f232678b5.png)

I use vc2015 and CoolProp.dll (v6.10, download from https://sourceforge.net/projects/coolprop/files/CoolProp/6.1.0/shared_library/Windows/32bit__stdcall/)
Got the error 'division by zero',
when I called the code:  '**double Twx = HAPropsSI("Twb", "Tdb", 291.42, "H", 45076.0, "P", 101325);**'

but call this is OK:  **HAPropsSI("Twb", "Tdb", 300.15, "H", 55615.0, "P", 101325)**    (=292.65)

and in python, both lines is OK:
>>> from CoolProp.HumidAirProp import HAPropsSI
>>> HAPropsSI("Twb", "Tdb", 291.42, "H", 45076.0, "P", 101325)
289.20909872654454
>>> HAPropsSI("Twb", "Tdb", 300.15, "H", 55615.0, "P", 101325)
292.6499704221468

Is there some data point that can't be calculated with dll. Why?
How can I fix it?
Help, please!

**Comment by ibell** [comment]
From what language are you calling? C++?  Why are you not using the 64-bit version?

**Comment by gas0189** [comment]
@ibell 
My project is 32-bit, so need 32-bit dll.
I use C++.

**Comment by ibell** [comment]
Hmm, that is odd.  The floating-point error flags are reset when the
function HAPropsSI is called, so no floating-point errors should be able to
be bubbled up.  We used to see similar things in languages calling the DLL,
but I thought we had resolved all these issues.  Can you please make a
stripped down C++ file that is runnable and demonstrates this error?
Ideally, the smallest amount of code that will demonstrate this error.
Probably the result is fine, and the division by zero is only for an
intermediate calculation.  Which is why python works fine.

**Comment by gas0189** [comment]
@ibell 
I make a stripped down C++ file:

**mylib.h**

#define DLL_API __declspec(dllexport)
#define CALLTYPE __cdecl  // __stdcall had the same error.

extern "C" DLL_API int CALLTYPE foo(void);


**mylib.cpp**

#include "CoolPropLib.h"

#pragma comment(lib, "CoolProp.lib") 

DLL_API int CALLTYPE foo(void)
{
	double Twx1 = HAPropsSI("Twb", "Tdb", 300.15, "H", 55615.0, "P", 101325);  // ok.
	double Twx2 = HAPropsSI("Twb", "Tdb", 291.42, "H", 45076.0, "P", 101325);  // divison by zero.
	return 0;
}

**build and get: mylib.dll**

when I call mylib.dll from demo_from_vc.exe (no gui, build with vc2015 c++/32bit), both lines is ok.
when I call mylib.dll from **demo_from_delph.exe (GUI app, build with XE8, delphi/32bit)**, the second line error.

**Comment by jowr** [comment]
Delphi is very sensitive towards these errors. It could be that the internal floating point error register has to be reset somewhere. C++ and Python do not throw errors as long as the DLL call itself does not fail. Delphi on the other hand throws an error as soon as it encounters a floating point error during execution - regardless of whether this error/exception gets caught internally. 

You can avoid this by setting exception masks for the FPU (Floating Point Unit):
http://docwiki.embarcadero.com/Libraries/Berlin/en/System.Math.SetExceptionMask
https://stackoverflow.com/questions/34777301/disable-floating-point-exceptions-during-a-single-function
https://stackoverflow.com/questions/19187479/masking-floating-point-exceptions-with-set8087cw-setmxcsr-and-twebbrowser
http://digital.ni.com/public.nsf/allkb/E6A73825E57FCD9F862570DD005E594F

**Comment by gas0189** [comment]
@jowr 
Thanks. Let me check and try.
