### ISSUE TITLE
Support of IF97

### ISSUE THREAD

**Issue by alkanism** [CoolProp/CoolProp#1537]
Congratulations to all those who have participated in the development of this Cool project.
I was thrilled to see that water/steam properties are covered with it as well and decided to give it a try, but I am very disappointed that the current version is far from being useful for that purpose.

The functions in CoolProp available through "IF97::Water" are far from being adequate. Perhaps those missing functionalities can be achieved via the REFPROP interface but that defeats the purpose of using CoolProp.

I understand that this is a monumental effort and I don't expect any miracles here, but I wanted to furnish these deficiencies to the developers' attention in any case.

Ismail Alkan

Here are some of the missing functions and errors I found in CoolProp, when compared with IAPWS-IF97...

The following pair of inputs are not yet supported in "IF97::Water" but should be available:
T, V as inputs
T, H as inputs
P, V as inputs
T, Q as inputs
There are perhaps others as well, but haven't checked them yet.

The following call gives "Pressure out of Range" error for super-critical pressures although it should return a value for D:
PropsSI("D", "P", p, "T", T, "IF97::Water")

The following calculations are a little off from the IF97 equivalent:
conductivity for given P and T 
Is the conductivity formula based on 2011 update of IF97?

The following properties are missing in CoolProp for "IF97::Water"
Fugacity (Pa) for given P and T
Refractive Index (dimensionless) for given P, T, and Wavelength in meters 
Laplace Constant (m) for given T
Static Dielectric Constant (dimensionless) for given P and T
Ionic Product (dimensionless) for given P and T

The following are the differences between IAPWS-IF97 and CoolProp :
Description;IAPWS-IF97;CoolProp 
Minimum Pressure, Pa ;458.625;611.6548
Maximum Pressure, MPa;110.317;1000
Minimum Temperature, K;269.261;273.16
Region 5 Pmax, MPa;10;N/A
Region 5 Tmax, K;2273.15;N/A

**Comment by ibell** [comment]
CoolProp is a volunteer project; if you identify a limitation or problem, you are welcome to propose a fix as well via pull request. All the code is up on github.  Your contribution would be appreciated.

I wonder what version of CoolProp you are using, since some things you mention have already been fixed, like TQ.  TH is problematic, because it is multi-valued, and less common, so we don't implement it.  Usually, if you know T you know p, and PH is well behaved.  TD and PD should also have been implemented in the most recent version of CoolProp I think.

@henningjp is our IF97 master right now, I got the code started and he has carried the torch.

**Comment by alkanism** [comment]
Yes I understand. And as I mentioned above, I admire the project. I wish I had time to contribute, but between my daily job and an open source project, I really don't have much more time at hand currently. Hopefully in the future.

I don't know if the Excel sample provided uses the latest version of the DLL. I tried replacing it from the current nightly builds but it didn't work. Maybe the Excel sample needs an update.

**Comment by henningjp** [comment]
@alkanism I think you will find most of what you were looking for in version 6.2.  Please see the [IF97 documentation](http://www.coolprop.org/dev/fluid_properties/IF97.html) for info.

**Comment by alkanism** [comment]
Thanks for the update.
Where can I find the compiled binaries with these new updates?
I downloaded the 6.2 installer but it still installed binaries from April 2018.

**Comment by henningjp** [comment]
Try the [6.2.1 installer](https://sourceforge.net/projects/coolprop/files/CoolProp/6.2.1/Installers/).

If that fails you can try the [manual installation proces](http://www.coolprop.org/coolprop/wrappers/Excel/index.html#excel)s.
