### ISSUE TITLE
How to use CoolProp.AbstractState in Matlab?

### ISSUE THREAD

**Issue by TianbiaoHe** [CoolProp/CoolProp#1538]
Hi,

I am trying to use CoolProp.AbstractState in Matlab, but it fails. Is it different when using CoolProp.AbstractState in Matlab and in Python? If it is different, would you like to show me how to use it in Matlab? Thank you very much.

Best Regards,

**Comment by ibell** [comment]
What does "it fails" mean?  Error message and/or screenshot would be
helpful to debug.  In general, use of the AbstractState is similar to
python.  Soon, the use of the AbstractState will ONLY be available in the
python->Matlab interface.  Can you run the MATLAB example:
http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#example-code ?

**Comment by jowr** [comment]
This one has been solved in #1497 and it will be possible in the next release of CoolProp

**Comment by ibell** [comment]
Please see #1543
