### ISSUE TITLE
IF97 backend gives bad input_pair for PQ_INPUTS

### ISSUE THREAD

**Issue by absvm** [CoolProp/CoolProp#1540]
Hi all,

When I try to use PQ_INPUTS with the IF97 backend, it gives me a bad input pair error. I am unsing version 6.1.0.

I am using it through the low level interface in C#:

IF97.update(input_pairs.PQ_INPUTS, 6073000, 0.5); // 60.73 bar, 50%
Error: bad input_pair

From what I can see in the code, PQ should be supported. 

Am I overlooking something? 

rgds,

Arjan

**Comment by ibell** [comment]
Yes, you need to use the development version, those inputs were not
available in v6.1.

**Comment by ibell** [comment]
Please update to the nightly build, and this should be repaired I believe.

**Comment by absvm** [comment]
Will do. Thank you for the effort!

**Comment by henningjp** [comment]
@absvm  Is this issue resolved?  Did you get the nightly build of 6.1.1dev?

**Comment by absvm** [comment]
@henningjp Hi, sorry for the late reply.  Yes, this has been resolved in the 6.1.1 nightly.

Thanks for checking.

**Comment by henningjp** [comment]
OK, I'll close it.
