### ISSUE TITLE
Python inherit form AbstractState

### ISSUE THREAD

**Issue by romarro** [CoolProp/CoolProp#1545]
It is possible to inherit form AbstractState? I have done the following in python 2.7:
```
from CoolProp import AbstractState

class Refrigerant(AbstractState):
    def __init__(self, refrName):
        super(self.__class__, self).__init__("HEOS",refrName)


if __name__ == '__main__':
    tst = Refrigerant('R134a')
```
and I get the error:
TypeError: __cinit__() takes exactly 2 positional arguments (1 given)

**Comment by raphaeltimbo** [comment]
It is possible, but I recommend taking a look at this stackoverflow question: [cant-override-init-of-class-from-cython-extension](https://stackoverflow.com/questions/18260095/cant-override-init-of-class-from-cython-extension).

What I did in my case was the following:

```
from CoolProp import AbstractState

class Refrigerant(AbstractState):
    def __init__(self, backend, refrName):
        self.backend = backend
        self.refrName = refrName
    
    @classmethod
    def create(cls, refrName, backend="HEOS"):
        return cls(backend, refrName)
        
    
if __name__ == '__main__':
    tst = Refrigerant.create('R134a')
```

**Comment by romarro** [comment]
Thanks. The stackoverflow thread is very helpful.
