### ISSUE TITLE
Dev Docs for Mixtures Failing

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1548]
The /dev/ documentation for mixtures is failing (both for my doc builds and the official http://www.coolprop.org/dev/fluid_properties/Mixtures.html page).
![ipython error](https://user-images.githubusercontent.com/17114032/30240712-9825a18e-9543-11e7-9f19-8a779841ef9f.PNG)

It looks to me like the ipython instance of CoolProp already thinks that the Helium/Xenon mixture has been added, so when the script shows an example of creating a new mixture, it fails.  This does NOT happen on the official 6.1.0 release documentation page.  It doesn't happen when issuing these commands from a fresh python or Jupyter iPython window either.  I've poked around at it, but am now at a loss as to what is going on.  It seems to me that this page should be creating a fresh instance of CoolProp, but apparently it's not.

If you have any ideas, I can work on it, but right now I'm stumped.  I don't know if it's an environment issue or something that has crept in with 6.1.1dev.

**Comment by ibell** [comment]
It's a "fix" to the code for binary interaction parameters in 6.1.1dev.  Not sure what a brilliant resolution to this is, but I'll make it work.  Basically, the same Ipython interpreter session is kept active for the entire build, so if you try to load to things that have side-effects in multiple shells, you run into troubles.

**Comment by henningjp** [comment]
I think I may have it working.  A simple variable change from CP to CP1 seemed to make it work in the first block.  Not sure why.  (Is there another file that give a mixture example and processes before this one?)  The second block needs tweaked now as the He/Xe mixture is already added.  I'll test it and add it into PR #1547 with the other documentation changes.  

I'm also looking at reload() as well.  My thought is that that should re-run __init__.py and clear the mixture list back to default, but I haven't got this working yet.

**Comment by henningjp** [comment]
@ibell - Ok, I obviously don't know what I'm doing, but here's a clue:

If I edit ``Web\Fluid_Properties\Mixtures.rst`` and then do a partial build of the docs with 
```
  make html
```
It fixes the errors; Mixtures.rst creates a new entry for He/Xe mixture right off the bat with no errors.  In this case it is only rebuilding the files that have changed and it runs much faster than the full doc build.  Mixtures.rst is run through sphinx with very little else.  However, if I wipe out the _build directory first and do a complete rebuild with 
```
  make clean html
```
The errors come back.

Seems to me that either:
1. Some other file in the docs is setting the He/Xe mixture before Mixture.rst can get to it (I can't find any instance of this), or....
2. The makefile is running Mixture.rst through sphinx twice and creating a conflict for itself (I can't find a double instance of Mixture in the doctree), or...
3. I really, **_really_** don't know what I'm doing.

**Comment by ibell** [comment]
Maybe this is something to fiddle with:
https://ipython.org/ipython-doc/dev/config/extensions/autoreload.html ?  Or
we could explicitly turn on overwriting by setting the configuration
variable?

**Comment by ibell** [comment]
Another thought: https://stackoverflow.com/a/22934273/1360263

**Comment by henningjp** [comment]
Good thoughts.  I'll poke around at it tonight.  

The ``autoreload`` looks like it will reload the module before _every single call_ to the module functions, wiping out any parameters we've set.  Not desirable.  ``%reset`` has some promise, if it exists in our iPython kernel, and if resetting CP causes the module to actually reload when imported.  I'll test it out tonight.

Explicitly turning on the overwrite flag might work if we can hide it.  The `@suppress` decorator might work to explicitly set the configuration variable without it showing up in the html.  I've not used this before, but I'll test that as well.

If I come up with something, I'll add it to PR #1547 .

These are patches, but don't address the root cause.  Do you know if sphinx actually parses and runs each RST file twice; maybe in order to establish the doctree or something?

**Comment by ibell** [comment]
I think the core issue is that the same IPython interpreter is used for the
entire build, or maybe it is just the given RST file, I can't quite make
that out.  In any case the key seems to be %reset ("%reset -f" seems to
totally reset the interpreter without asking, including unloading all
modules; wish I knew about that before):

In [*1*]: *import* *CoolProp*


In [*2*]: CoolProp.__version__

Out[*2*]: u'6.1.1dev'


In [*3*]: %reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [*4*]: CoolProp.__version__

---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-4-e3995ca82471> in <module>()

----> 1 CoolProp.__version__


NameError: name 'CoolProp' is not defined

**Comment by henningjp** [comment]
Nope.  %reset clears the variable ``CoolProp`` that references the module, but does not unload the module or reset the interaction parameters when the module is loaded again.  They are still there.

I think I have it working by explicitly setting the OVERWRITE config variable ahead of everything, and using the @suppress decorator to hide it from the sphinx output.  More testing needed.

**Comment by ibell** [comment]
Hmm, I didn't realize it didn't reload.  Argh.

**Comment by henningjp** [comment]
So, setting the OVERWRITE flag (suppressed) and then setting the mixing rule to ``linear`` works.  However, the next call to PropsSI('Dmass',.... fails with the following error:

    ValueError: One stationary point (not good) for T=300,p=101325,z=[ 0.949711803067, 0.0502881969327 ] : PropsSI("Dmass","T",300,"P",101325,"Helium[0.5]&Xenon[0.5]")

This is odd, so I checked the binary interaction parameters that are getting set when the mixing rule is overwritten.  All looks normal, except for:
```
In [8]: CP.get_mixture_binary_pair_data(CAS_He, CAS_Xe, 'gammaT')
Out[8]: u'5.624992107975534'

In [9]: CP.get_mixture_binary_pair_data(CAS_He, CAS_Xe, 'gammaV')
Out[9]: u'1.00001688881475'
```
These are **_not_** the gamma values that are set when the mixing pair is created from scratch.  They apparently don't work and the default values should be:
```
In [6]: CP.get_mixture_binary_pair_data(CAS_He, CAS_Xe, 'gammaT')
Out[6]: u'3.800862464859313'

In [7]: CP.get_mixture_binary_pair_data(CAS_He, CAS_Xe, 'gammaV')
Out[7]: u'1.048787574261067'
```
I updated these values to the defaults in the ipython block, but PropsSI still throws the same ``One stationary point`` error.  This comes from HelmholtsEOSMixtureBackend and is returned by the dRhodp solver.  Something is really clobbered here.

**Comment by henningjp** [comment]
@ibell & @jowr Some of this stuff isn't working the way it's supposed to.  The latest iPython isn't supported any longer on Python 2.7, so I'm going to try a Python 3.5 environment.  What's the buildbot running?

**Comment by jowr** [comment]
Which buildbot? The one for the docs runs Python 2.7 on Mac OS.

**Comment by henningjp** [comment]
Thanks, @jowr , I'm sticking with Python 2.7.

It looks like the only way I have found fix the errors above in the Mixtures.rst file is to 
1. run a clean build: ``make clean html``
2. make an insignificant change in the Mixtures.rst file: ``touch fluid_properties/Mixtures.rst``
3. run an update build: ``make html``

I even tried following up the full sphinx-build in the Makefile with a sphinx-build of just the fluid_properties/Mixtures.rst file, to no avail.  I thought this would clear the environment, but it still corrupts the iPython environment and gives the ``One Stationary point`` errors mentioned above.  I have to get clear out of the make environment in order to get a clean load of the CoolProp module and update the build of the Mixtures.rst file.

Can the buildbot scripts that build the docs be configured to do this?
```
    make clean html
    touch fluid_properties/Mixtures.rst  #or something to cause Mixtures.rst to update
    make html
```

**Comment by ibell** [comment]
That is exceptionally weird.  I have no idea how that could happen, but
I'll look into it.  Does this happen in a normal python/ipython shell that
is not part of the docs?

**Comment by henningjp** [comment]
No.  It doesn't happen outside of the sphinx build.  (See last paragraph of my last post.)

I've tracked it down to the High Level Interface page.  A section was added in the DEV docs on _**Adding Fluids**_.  The iPython example extracts properties for Water and then  demonstrates how to set the OVERWRITE config variable and overwrites the water properties with the copy of the data.  

I suspect an indexing problem when the props get written in `add_fluids_as_JSON()`.  Xenon is the next entry after Water and the last entry in the list.  `JSONFluidLibrary::add_one` is supposed to delete the existing entry if it exists and then add the new entry to the end of the list.  I think there's an indexing problem here and it is overwriting Xenon instead.

**Comment by henningjp** [comment]
So I can verify that this **_does_** happen outside of the sphinx build, **_IF_** you overwrite a JSON fluid entry first:
```
In [4]: CP.get_fluid_param_string("Xenon", "CAS")
Out[4]: u'7440-63-3'

In [5]: CP.set_config_bool(CP.OVERWRITE_FLUIDS, True)

In [6]: jj = CP.get_fluid_param_string("Water", "JSON")

In [7]: CP.add_fluids_as_JSON("HEOS", jj)

In [8]: CP.set_config_bool(CP.OVERWRITE_FLUIDS, False)

In [9]: CP.get_fluid_param_string("Xenon", "CAS")
Out[9]: u'7732-18-5'
```
Xenon now has the CAS number for water.

**Comment by henningjp** [comment]
So here's what I think is going on in `JSONFluidLibrary::add_one`.  The initialized fluids list looks like this:

Fluid Name     | Index
----------------|-------
1-Butene | 0
... | i
trans-2-Butene | 119
Water | 120
Xenon | 121

Map size = 122 (elements)

If a new fluid is added, the add_one routine (lines 270-274) checks the size, and adds a new entry with the map size as the index.  Since indexing starts at zero, size is one larger than the last index, this works:
```cpp
        // Get the next index for this fluid
        index = fluid_map.size();
        
        // Add index->fluid mapping
        fluid_map[index] = fluid;
```

**_However, when Water is updated_** (or any fluid for that matter), **_its entry in the list is deleted_**, but the following entries in the list are not re-indexed, so the table looks now like this:

Fluid Name     | Index
----------------|-------
1-Butene | 0
... | i
trans-2-Butene | 119
Xenon | 121

Map size = 121

Now the map **[]** operator does not behave like an array and add to the end of the list;  instead, `fluid_map[index]` will look through the map for the index provided and replace that entry.  Only if it doesn't find the entry, will it add a new entry to the end of the list.  In this case, Xenon's index has not been updated, so `fluid_map[index]` is equivalent to `fluid_map[size=121]` and when the entry for Water is added back in, it finds an entry with that index in the map (Xenon, 121) and replaces it.

Two possible solutions:
1. Don't remove a fluid that is being overwritten.  Just set the appropriate index and allow it to be overwritten in place.  It may be a bit tricky to set the right index in all the maps that have to be updated.
2. Leave everything the same, but instead of setting `index = fluid_map.size()`, look for the largest index in the map, `index_max`, and set `index = index_max + 1` before adding the fluid.  This will create a new entry at the end of the list with the next largest index number and index numbers in the table will have gaps.  I don't know if this will cause problems elsewhere.

Thoughts?  Modifying this myself makes me nervous as it may have unexpected side-effects and I'm not set up to test this easily.  Perhaps the JSON architect should do this?

**Comment by ibell** [comment]
Interesting, that's definitely a bug; I should have noticed this before.
I'm not totally sure what the right approach is here.  I think the proper
approach is to swap out the entity in the map with the new EOS, but not
update the index.  Do you want to take a first crack at this and make a PR
and we can think about what you've done?

In general, I'm not sure whether I have done something smart or stupid in
the logic that I used to load fluids.  If there are no fluids loaded yet,
adding a fluid doesn't load the default set of fluids.  That has caused me
some annoying issues.

**Comment by henningjp** [comment]
Yes I'll take a crack at it.  I think I know what to do, but the best place to test is python and I am having trouble compiling the python wrapper locally.  Give me some time to work through it; VC version conflicts.  I'll let my docs PR sit until we get this sorted out.

**Comment by ibell** [comment]
Great!  For python compilation, you can get incremental rebuilds if you
tell python to use cmake, something like:

python setup.py install cmake=vc9,64

if I remember correctly should result in a static library being
incrementally rebuilt and then linked into the cython module.  Which would
be much faster than a full rebuild

**Comment by henningjp** [comment]
Yes, that works, and the static build is successful, but then it gets to
```
running build_ext
building 'CoolProp.CoolProp' extension
files removed.
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
```
and CoolProp won't import under Python.
```
Import Error: cannot import name '_constants'
```

**Comment by ibell** [comment]
Hmm, that doesn't seem right.  Can you send me the complete build log?

**Comment by henningjp** [comment]
Attached is the output from the build.  Is there another log file I should attach?
[CPPython.txt](https://github.com/CoolProp/CoolProp/files/1348597/CPPython.txt)
[CMakeOutput.log](https://github.com/CoolProp/CoolProp/files/1348598/CMakeOutput.log)

**Comment by henningjp** [comment]
@ibell , I need a little help here.  Apparently, different combinations of Python version, VS2010, and bitness do really bad things.  
- python 3.6, VS2010, and 64-bit fails looking for VC++ 14
- python 2.7, VS2010, and 32-bit gets linker errors (x86 but expects x64)
- python 2.7, VS2010, and 64-bit gets lots of errors trying to use "Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe and link.exe"

What should I be using here?  Are there pre-requisites that aren't in the docs?  I just want to get a python wrapper built on Windows 10/Anaconda/VS2010.

**Comment by ibell** [comment]
Short answer: you can't just use whatever version of visual studio you
want, it MUST match the python executable.

For python 2.7, that is VS2008 (ancient, yes).  For 3.6, that's visual
studio 2015.  The express version of visual studio 2015 is what I use all
day long, which is free for all uses (as I understand it).

**Comment by henningjp** [comment]
OK. That explains a lot. That should be spelled out in the docs.  They currently say:

- If you want to build 64-bit extensions [...] You will require Visual Studio 2008 Professional for python 2.x, and Visual Studio **_2010_** Professional for python 3.x. Otherwise you can select Visual Studio version freely.

This is a little ambiguous.  I took it to mean "_at least_" that version not "_exactly_".  And **_2010_** should clearly be **_2015_** per your last comment.  I'll make the attempt at both.  Thanks!

**Comment by henningjp** [comment]
🙌  Success!   I get it now, and I see that the python doc page is just out of date.  Thanks for you patience @ibell .   I got it to work with **VS2015 Community** on Python 3.6.  Installed and running!

Now to fix our bug...
