### ISSUE TITLE
Documentation for Joule Inversion curve

### ISSUE THREAD

**Issue by Larry1957** [CoolProp/CoolProp#1555]
With reference to the documentation page http://www.coolprop.org/fluid_properties/PurePseudoPure.html#ideal-curves, and in particular to the Joule Inversion curve, I suspect that the formula expressing the partial derivative of Z with respect to T at constant v might be incorrect as the T term at denominator should be squared.  
![image](https://user-images.githubusercontent.com/31284832/30952716-42801152-a429-11e7-85b3-6d0f7de13978.png)
An inspection into the Joule Inversion curve generation Phyton code (although I am not expert) reinforced me this doubt.
Thanks

**Comment by ibell** [comment]
I think this should do it
