### ISSUE TITLE
Slight issue with PropsSIZ in EES CoolProp.LIB

### ISSUE THREAD

**Issue by arattner1** [CoolProp/CoolProp#1561]
I think the f$ string command needs to be modified in PropsSIZ to add the 'SI' tail:
f$ = fluid$||'~'||output$||'~'||input1$||'~'||input2$||'~'||'SI'

Awesome code! Can I join your fan club?

**Comment by ibell** [comment]
Huh?  I'm not quite sure what you are talking about :)  I don't think you
need to append SI to any of the function calls.

Sadly I can't use EES any more, can you provide a bit more info?

**Comment by arattner1** [comment]
Hi Ian,

Thanks for the message.

I tried to run the PropsSIZ function in EES. When I made a call like:

  * T = PropsSIZ('T', 'P', 201325, 'Q', 1, a$, 2,x[1..2])*1[K]

I got this error message: "fluid[Propane&isobutane~T~p~Q] length[4] not 
5 elements long"

I changed the line in the CoolProp.LIB to read:

  *      f$ = fluid$||'~'||output$||'~'||input1$||'~'||input2$||'~'||'SI'

like it does in the propssi function. Then my EES program ran without error.


Best wishes,
Alex

**Comment by ibell** [comment]
Hmm.. Can you file a pull request with this update?

**Comment by arattner1** [comment]
Ok, it's on the todo list (may take a couple days).

Best,
Alex

**Comment by ibell** [comment]
Closed by #1566
