### ISSUE TITLE
Adding New Generation of R404a Alternatives as Fluids (R448a, R449a,..)

### ISSUE THREAD

**Issue by lenam91** [CoolProp/CoolProp#1564]
Hey is it possible to Add Fluids like R407A, R407F, R448A, R449A in the Coolprop library? Or is ther any possibility to do it on my own, as we know these are just HFO-Blends with a Mixtures value given by companies like TEGA (https://www.tega.de/uploads/downloads/R_449A_Opteon_XP40_PDB_Spezifikation.pdf)

Thanks already!

**Comment by henningjp** [comment]
To add them as fluids, you would need the equations of state.  REFPROP uses advanced mixing rules for these near azeotropic mixtures.  I believe these are more advanced than what is in CoolProp.  See http://www.schiessl.pl/assets/zdjecia/Czynniki%20III/R449A/W%C5%82a%C5%9Bciwo%C5%9Bci%20termodynamiczne%20R449A%20EN.pdf

**Comment by henningjp** [comment]
See #1553

**Comment by ibell** [comment]
Someone (one of my colleagues) could develop a pseudo-pure fluid equation of state for these mixtures like was done for R404A, R410A, etc..  Until that is done, you are stuck using the binary interaction parameters and the full mixture code.  The code for mixtures is not very robust sadly, so you will probably need to use NIST REFPROP for the mixture calculations.

**Comment by lxh3251335** [comment]
predefined mixture fluids include R448a.mix and R449a.mix.  You can  use

**Comment by thorade** [comment]
Here is the list of included pure and pseudo-pure fluids:
http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids
For the mentioned blends, a pseudo-pure equation could be developed.
I am closing this issue for now; once such an equations exists and is published (the difficult part), these should be added to the pseudo-pures (the easy part).
