### ISSUE TITLE
error 53 on excel for Mac

### ISSUE THREAD

**Issue by vt18** [CoolProp/CoolProp#1575]
Hey,
I need to setup CoolProp for one of my classes. Since I am a student I am not really familiar with handling in the terminal, so I am asking you for help.

I followed the Instructions on [coolprop.org](http://www.coolprop.org/coolprop/wrappers/Excel/index.html) to install the Excelwrapper but at the end of the installation error 53 comes up.

I am running Excel 15.39 on MacOS 10.13. So I tried to use the 64bit version of CoolProp but the error occurs, using the 32 bit version the same error occurs.

Would be great If somebody could try to help me.

Best Regards

**Comment by ibell** [comment]
Have you followed all these instructions too :
https://github.com/CoolProp/CoolProp/issues/989 ?

How about using python instead of Excel to call CoolProp?  That works
seamlessly; Excel 2016 is exceptionally difficult on OSX to get working due
to sandboxing.

**Comment by vt18** [comment]
yes, i followed all these instructions and it is still not finding the .dylab

**Comment by ibell** [comment]
Where did you get the shared library from?  If I remember correctly, you
need a STDCALL DLL for Excel, which may or may not be what you have.

**Comment by ibell** [comment]
Now I am remembering that on 10.13, it ignores the setting of
DYLD_LIBRARY_PATH in launch agents.  I have honestly no idea what to try
next.  I think the approach of using python is the right one, it will suit
you going forwards.

**Comment by vt18** [comment]
Thank you for your help.

I am not sure if I am able to use python.
I think the best way is now to install Excel on a Windows partition of my Mac

**Comment by ibell** [comment]
Perhaps so, but learning python will be a much better long-term solution :)
I'm happy to answer any questions you might have.
