### ISSUE TITLE
Unable to use CoolProp with JavaScript

### ISSUE THREAD

**Issue by JuanmaDonado** [CoolProp/CoolProp#1577]
Hi, I've been trying to use the JS wrapper, but when including the coolprop.js file I get the following error:
`coolprop.js:1 Failed to load file:///C:/Users/Juanma/Desktop/CoolPropJS/coolprop.js.mem: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
xhrLoad @ coolprop.js:1
coolprop.js:18 Uncaught could not load memory initializer coolprop.js.mem`

I have the coolprop.js.mem in the same folder as the index and coolprop.js, but I can't get it to load.

**Comment by ibell** [comment]
You need to run this within a webserver I do believe to get it to work
properly.  That should avoid the cross-origin error I think.

**Comment by JuanmaDonado** [comment]
That worked. Thanks!

**Comment by ibell** [comment]
Please go ahead and close the issue as it is now resolved.
