### ISSUE TITLE
Buildbot update

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1582]
I recently updated my OSX builder and the old config seems to be incompatible with the new workers :-( . We might want to update the master and the master configuration accordingly.

**Comment by ibell** [comment]
What version of buildbot is your new slave running?  Did you upgrade to
0.9?  Feel free to make whatever changes are needed?

**Comment by jowr** [comment]
OK, I'll look into this. Sounds also like a good opportunity to move some of the build logic from buildbot to CMake...

**Comment by ibell** [comment]
I 100% support moving whatever we can from buildbot to cmake - it's soooo much easier to debug cmake than buildbot config

**Comment by ibell** [comment]
I think you need to roll back to buildbot 0.8.12 unless we upgrade the entire buildbot network up to 0.9.x  I suspect that's the root of this issue and why all your slaves are dead.

**Comment by ibell** [comment]
Ok, not all your slaves, but at least the OSX one...

**Comment by ibell** [comment]
This is ok now...
