### ISSUE TITLE
Joule–Thomson coefficient for humid air

### ISSUE THREAD

**Issue by dkhazov** [CoolProp/CoolProp#1583]
Dear All,

Is there any possibility to calculate the Joule–Thomson coefficient for humid air by using CoolProp?

For dry air it is not a problem (just by definition):
```python
import CoolProp.CoolProp as CP
p=101325. # Pa
T=300.0 # K
muAir=CP.PropsSI('d(T)/d(P)|H','P',p,'T',T,'Air')
```
or 
```python
alpha=CP.PropsSI('isobaric_expansion_coefficient','P',p,'T',T,'Air')
rho=CP.PropsSI('D','P',p,'T',T,'Air')
Cp=CP.PropsSI('C','P',p,'T',T,'Air')
V=1./rho
muAir=V/Cp*(alpha*T-1.)
```

**Comment by thorade** [comment]
Here is the table of available properties for humid air:
http://www.coolprop.org/fluid_properties/HumidAir.html#table-of-inputs-outputs-to-hapropssi
Joule-Thomson is not there, as well as most other derivatives.
You should be able to do numerical derivatives, though.

**Comment by ibell** [comment]
That is correct - the Joule-Thomson coefficient is not currently
implemented for humid air.  If you wanted to work out the analytic
derivative, I'd welcome it, but I don't think it would be very trivial to
do so.  For now, as Matthis says, a numerical derivative is your best bet.

**Comment by thorade** [comment]
Closing for now, as these derivatives will not be implemented in the near future.
If youneed help with numerical derivatives, or if you want to work on analytical drivatives yourself, please reopen!
