### ISSUE TITLE
Freezing Point

### ISSUE THREAD

**Issue by 11718pauld** [CoolProp/CoolProp#1585]
Using Matlab+Coolprop, how to calculate freezing point of water at different pressures?
Please provide the syntax.

`CoolProp.PropsSI('T_FREEZE', 'P', 5e6, 'WATER')`
Returns an error,
`Error using CoolPropMATLAB_wrap
Fatal error.
Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] =
  CoolPropMATLAB_wrap(345,varargin{:});
Error in aa (line 2)
CoolProp.PropsSI('T_FREEZE', 'P', 5e6, 'WATER') `

**Comment by ibell** [comment]
You have to use the low-level interface:
http://www.coolprop.org/apidoc/CoolProp.CoolProp.html?highlight=melting#CoolProp.CoolProp.AbstractState.melting_line

See also
http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#example-code

**Comment by ibell** [comment]
``T_FREEZE`` is only intended for incompressible fluids and brines

**Comment by thorade** [comment]
@11718pauld As Ian said, many pure fluids have a melting line correlation implemented. As melting and freezing happens at the same temperature, you want to use that!

Also note that in the future it is recommended to use the MAtlab-> Python interface for calling Coolprop:
https://github.com/CoolProp/CoolProp/issues/1497
