### ISSUE TITLE
Update msgpack

### ISSUE THREAD

**Issue by xoviat** [CoolProp/CoolProp#1586]
Would you mind updating msgpack to a more recent version? I ran into compilation errors when attempting to build with a newer version.

**Comment by ibell** [comment]
I don't see what the main issue is because we have msgpack pinned to a
particular commit of msgpack. Can you please
a) describe what exactly the problem was
b) provide a pull request with the updated submodule if necessary

**Comment by xoviat** [comment]
The issue is that you cannot pin dependencies with vcpkg. You always get the latest version of the library, no matter what. msgpack has updated their API, which has some incompatibilities with the current use.

**Comment by ibell** [comment]
What is vcpkg?

**Comment by xoviat** [comment]
It's Microsoft's VC++ package manager. @nitrogene wanted to add coolprop to the packages list.

**Comment by ibell** [comment]
I see - I can see that would be useful.  It's pretty stupid that it
automatically pulls the most current version of all the dependencies.  What
were they thinking?

In any case, if you wanted to file a PR with updated msgpack commit and any
fixes required for CoolProp, fire away

**Comment by xoviat** [comment]
Will do.
