### ISSUE TITLE
Coolprop in Python

### ISSUE THREAD

**Issue by NAFIERFANI** [CoolProp/CoolProp#1588]
Hi all 
I am trying to install CoolProp for Python 3.6 , not successful 
This is part of message : 

\__init__.py", line 16, in <module>
    from .CoolProp import AbstractState
ImportError: DLL load failed: %1 is not a valid Win32 application.

my win is 64 !!!
I would appreciate it if you could help me out , thanks

**Comment by ibell** [comment]
How did you install CoolProp?  Maybe move to another folder?

**Comment by NAFIERFANI** [comment]
I used this link
"pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ --user -U --force-reinstall CoolProp"

and it was successful 

I installed the python in c:\program files\python36

after running the commend two folder are created in c:\user\..\AppData\Roaming\Python\Python36\site-packages

IS there any straight forward way to run coolprop?I really need it

**Comment by ibell** [comment]
You should probably consider using the Anaconda package manager:
https://www.anaconda.com/download/#macos

Then run your pip command you ran, and you should be in business.

**Comment by henningjp** [comment]
A few things come to mind.
1. Later versions of windows require admin privileges to access folders under "C:\program files".  In "all user" installations, you have to open python in a window that was opened with admin privileges or your install will fail (sometimes with or without error messages).  You might try a "user" install.
2. Which Python are you using?  I've had success with exactly what you're doing using Anaconda Python 2.7 and 3.6 (user level install).
3. Do you need the nightly build of coolprop?  You can get the release version with a simple ``pip install CoolProp`` at the Python prompt.

**Comment by henningjp** [comment]
Hmm, this may be the problem.  In your pip install of CoolProp you used the ``--user`` switch.  This puts CoolProp under the user's AppData directory where it assumes Python is installed.  I'd try either leaving off the --user switch or re-installing Python as a "user" install and letting it install in the AppData directory (that's where mine is).

**Comment by NAFIERFANI** [comment]
-I re installed Python 3.63 in User folder again (Win64
-Installed Anaconda 
-used the pip command again and got the same error 
ImportError: DLL load failed: %1 is not a valid Win32 application


My win is 64 but I do not know why it says  "ImportError: DLL load failed: %1 is not a valid Win32 application"

Can you please send me a command that you use

**Comment by ibell** [comment]
Anaconda *is* your python.  Make sure you add conda and python to the path
when you install anaconda.  It could be helpful to see the results of the
pip install for debugging purposes

**Comment by NAFIERFANI** [comment]
C:\Users\--\AppData\Local\Programs\Python\Python36

C:\Users\--\AppData\Local\Continuum\anaconda3

that's where I installed them 
what do you mean by "Make sure you add conda and python to the path"?
I checked Anaconda and pip is installed !!
Sorry I am Mechanical Engineer, do not know much about software

Thanks for your help

**Comment by ibell** [comment]
The point is that you should remove the python that you manually installed,
and then also uninstall anaconda.  Then only install anaconda, and at that
time, add that python and conda to the path.  Then install coolprop with pip

**Comment by NAFIERFANI** [comment]
ok, now I just have Anaconda 
Can explain what "add that python and conda to the path" means?

**Comment by Dev-iL** [comment]
@NAFIERFANI Please take a look [here](https://superuser.com/questions/284342/).

**Comment by henningjp** [comment]
My Anaconda installation added python and conda to the path automatically.  Open a cmd prompt (i.e. DOS window) and at the prompt type ``python``.  This should take you into the python environment, noted by a python prompt (>>>).  If yes, type exit() to get out of the environment, python is in your path.  If not, you need to add python to the path (add python to your PATH environment variable).

If python works then type ``conda list``.  This will show you all the python modules that python has loaded.  If not, you need to put conda in your path (add the path to conda to your PATH environment variable).

I have a vague recollection of the Anaconda install asking if I wanted to put python in the path, but there were lots of warnings why it was a bad idea, blah, blah, blah.  You need to do it anyway.  If not, you'll have to put the path to the python executable in your PATH environment variable.  See the link that @Dev-iL posted above.

**Comment by NAFIERFANI** [comment]
@ibell @henningjp @Dev-iL  
you are all Brilliant ... It's working now 
Thanks for being patient with me

**Comment by henningjp** [comment]
Glad it's working!
