### ISSUE TITLE
Calculate state of the air with the internal energy and the density

### ISSUE THREAD

**Issue by JocelynMbenoun** [CoolProp/CoolProp#1593]
Dear GitHub association, 

I am a student in electromechanical engineering.
I am trying to compute the state of the air with coolprop. I know the internal energy u and the density of the fluid. The error messages are: 
```
Warning: _phase is unknown  > In CoolProp.PropsSI (line 2)  Error using CoolPropMATLAB_wrap Fatal error.  Error in CoolProp.PropsSI (line 2)   [varargout{1:max(1,nargout)}] =   CoolPropMATLAB_wrap(313,varargin{:});Fin de la discussion
```

I tried different values, but without success.  For example, u = 3.35e5 J/kg and density = 1.2 kg/m^3 or u = 3.65e5 J/kg and density = 1.87 kg/m^3

Could you help me figure out how to solve this problem? 

Thank you for your help.

Greetings, 

Jocelyn Mbenoun

**Comment by ibell** [comment]
Hmm, you might just be getting unlucky:
http://www.coolprop.org/fluid_properties/fluids/Air.html#consistency-plots
That figure looks basically fine.  What version of CoolProp do you use?

**Comment by thorade** [comment]
Does it work if density is very different from critical density?
The consistency plot is showing some failures for densities close to critical density, independent of the value for the internal energy.

**Comment by JocelynMbenoun** [comment]
We are using the 5.1.2 version of CoolProp.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Ian Bell <notifications@github.com>
Envoyé : Thursday, November 16, 2017 5:45:57 AM
À : CoolProp/CoolProp
Cc : JocelynMbenoun; Author
Objet : Re: [CoolProp/CoolProp] Calculate state of the air with the internal energy and the density (#1593)

Hmm, you might just be getting unlucky:
http://www.coolprop.org/fluid_properties/fluids/Air.html#consistency-plots
That figure looks basically fine. What version of CoolProp do you use?

**Comment by ibell** [comment]
Definitely upgrade to 6.1, the flash routines should be MUCH more
reliable.  4.1.2 is quite old now.

**Comment by JocelynMbenoun** [comment]
Thank you ! I will try again after downloading it.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Ian Bell <notifications@github.com>
Envoyé : Friday, November 17, 2017 7:37:48 AM
À : CoolProp/CoolProp
Cc : JocelynMbenoun; Author
Objet : Re: [CoolProp/CoolProp] Calculate state of the air with the internal energy and the density (#1593)

Definitely upgrade to 6.1, the flash routines should be MUCH more
reliable. 4.1.2 is quite old now.

**Comment by ibell** [comment]
Closed due to lack of input; please reopen if needed
