### ISSUE TITLE
Incorrect value for specific enthalpy for D2O

### ISSUE THREAD

**Issue by absvm** [CoolProp/CoolProp#1597]
Hi,

I am getting a strange value for the enthalpy of heavy water, it seems completely out of range, compared to that of water. See C# code fragment below, which produces the following output:

h H2O at p=2.3222 bar, 398.15K: 2713.09931049405 kJ/kg
h D2O at p=2.3222 bar, 398.15K: 100.011978517658 kJ/kg

Am I overlooking something or is this value indeed incorrect?

I am using 6.1.1dev. 

thnx

Arjan

```
           double T_K = 273.15 + 125 ; // 125C
            double p = 2.3222; // bar

            double p_Pa;
            p_Pa = p * 1E5;

            CoolProp.set_reference_stateS("Water", "DEF");
            CoolProp.set_reference_stateS("HeavyWater", "DEF");

            double h0 = CoolProp.PropsSI("H", "P", p_Pa, "T", T_K, "HEOS::Water");
            Debug.WriteLine(String.Format("h H2O at p={0} bar, {1}K: {2} kJ/kg", p, T_K, h0 / 1000));

            h0 = CoolProp.PropsSI("H", "P", p_Pa, "T", T_K, "HEOS::HeavyWater");
            Debug.WriteLine(String.Format("h D2O at p={0} bar, {1}K: {2} kJ/kg", p , T_K, h0 / 1000));
```

**Comment by ibell** [comment]
How about setting the reference state to something useful like NBP?
Otherwise, if the default reference states are not the same (I believe they
are in fact not the same for ordinary and heavy water according to
CoolProp's implementation), the enthalpies should not be similar.

On Sun, Nov 19, 2017 at 6:33 AM, Arjan van Mulukom <notifications@github.com

**Comment by jowr** [comment]
Please read: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by ibell** [comment]
This problem is actually a bit more interesting.  What you have here is a jump from liquid (water) to vapor (heavy water) phase, which you can see by comparing the densities:

``` python
import CoolProp.CoolProp as CP
T_K = 273.15+125
p = 2.3222
p_Pa = 2.3222e5

CP.set_reference_state("Water", "NBP");
CP.set_reference_state("HeavyWater", "NBP");

h0 = CP.PropsSI("H", "P", p_Pa, "T", T_K, "HEOS::Water");
rho0 = CP.PropsSI("D", "P", p_Pa, "T", T_K, "HEOS::Water");
print("h H2O at p={0} bar, {1} K: {2} kJ/kg, {3} kg/m^3".format(p, T_K, h0/1000, rho0));

h0 = CP.PropsSI("H", "P", p_Pa, "T", T_K, "HEOS::HeavyWater");
rho0 = CP.PropsSI("D", "P", p_Pa, "T", T_K, "HEOS::HeavyWater");
print("h D2O at p={0} bar, {1} K: {2} kJ/kg, {3} kg/m^3".format(p, T_K, h0/1000, rho0));

print(CP.PropsSI("H", "P", 101325, "Q", 0, "HEOS::Water"))
print(CP.PropsSI("H", "P", 101325, "Q", 0, "HEOS::HeavyWater"))
```
yielding
```
h H2O at p=2.3222 bar, 398.15 K: 2294.0415774 kJ/kg, 1.2985529212 kg/m^3
h D2O at p=2.3222 bar, 398.15 K: 98.5914882068 kJ/kg, 1041.4729232 kg/m^3
-2.48539718423e-10
1.72633316586e-11
```

**Comment by absvm** [comment]
Thanks. Sorry for missing that part about the reference states in the FAQ. Happy to have good values now.
