### ISSUE TITLE
First partial derivative in LabVIEW

### ISSUE THREAD

**Issue by rohracker** [CoolProp/CoolProp#1598]
Hi

For a refrigeration cycle I successfully used CoolProp in LabVIEW to calculate the enthalpie for each change in state and to plot the corresponding log p-h-diagram.
Now I want to identify the failure of the enthalpie with the partial derivative also in LabVIEW. Therefor I tested it in MATLAB, and now I want to transfer the calculation in LabVIEW.
I allready downloaded the shared liberay (CoolProp.dll) and the C++ header file to implemente it in LabVIEW (Tools --> Import --> DLL). Now I can use the VIs in LabVIEW. Unfortunaly, I think, the inputs and outputs of these VIs are not in there original data type any more, so that the VIs doesn't work correctly. 
Did you allready make some experience with such problems and do you have a solution for implementing the partial derivative of the enthalpie in LabVIEW?

Thank you very much in advance.

Maurice

**Comment by ibell** [comment]
Well, if you can call PropsSI, you can always add the necessary string for
the derivative you need to the Labview interface.  Everything is
open-source and modifiable.

Can you please provide some more information about the problems you are
seeing?

**Comment by rohracker** [comment]
By now I can call PropsSI and calculate some properties, also the first parial derivative. The only problem is, that the error 1097 is occurring.

**Comment by ibell** [comment]
What is error 1097?  What inputs did you give to get this output?  Please
show a screenshot of your call to PropsSI

**Comment by ibell** [comment]
Bump

**Comment by ibell** [comment]
Closing due to lack of input, please open if want to revisit this issue
