### ISSUE TITLE
PropSI("Smolar",....failed ungracefully

### ISSUE THREAD

**Issue by torbjornp** [CoolProp/CoolProp#1599]
PropsSI() failed with the following error:

  self.data['sMix [J/(mol*K)]']   = PropsSI('Smolar',  'T', self.temp, 'P', press_pa, mix)
  File "CoolProp/CoolProp.pyx", line 328, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:36859)
  File "CoolProp/CoolProp.pyx", line 408, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:36644)
  File "CoolProp/CoolProp.pyx", line 299, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:34893)
ValueError: PropsSI failed ungracefully :: inputs were:"Smolar","T",4.2314999999999998e+02,"P",1.0132500000000000e+05,"HEOS::O2[0.0]&CO2[0.25]&H2O[0.0]&N2[0.0]&CO[0.65]&H2[0.1]"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

Regards,
-Torbjørn.

**Comment by henningjp** [comment]
Can you take some of those components out that are zero?  Even just to see if you get an answer. I’ve seen the mixture. solver get overloaded with too many components, even if some of them are zero.

Also, make sure there are binary interaction parameters for every pair of components in your mixture.  I think there should be, because these are common components, but worth a check.

**Comment by ibell** [comment]
I think Jeff is right about this one.  Zero mole fractions are impossible
in the ideal gas contribution, which is needed for the molar entropy

**Comment by torbjornp** [comment]
Ok - thanks. I tried removing the zero components. This time the viscosity model failed, but I can live with that. 
ValueError: Viscosity model is not available for this fluid : PropsSI("V","T",423.15,"P",101325,"HEOS::CO2[0.291]&N2[0.009]&CO[0.65]&H2[0.05]")

**Comment by henningjp** [comment]
@ibell Just a thought, PropsSI parses out the mixture string into components and mole fractions; can't the parser be modified to leave any "zero" fraction components out of the mixture list?

**Comment by ibell** [comment]
Yes, that is an excellent idea (but only easy to do in the high-level
interface).  Can you please file an issue about this?

**Comment by henningjp** [comment]
Opened issue #1603 as an enhancement.  I'll work on it.  Closing this issue.
