### ISSUE TITLE
Error when compiling/linking CoolProp in C++

### ISSUE THREAD

**Issue by Haasrobertgmxnet** [CoolProp/CoolProp#1600]
1. Building a static lib I got these ld errors:
...`getFunctionPointer(char const*, DLLNameManglingStyle)': ... undefined link/ref to `dlsym'
...`load_REFPROP(std::string&, std::string const&)': ... undefined link/ref to dlopen'
...`CoolProp::REFPROPMixtureBackend::~REFPROPMixtureBackend()':  ... undefined link/ref to `dlclose'
Occurence: In REFPROPMixtureBackend.cpp(.o) of libCoolProp.a

2. Building a shared object lib I got these ld errors:
libCoolProp.so: ... undefined link/ref to `dlclose'
libCoolProp.so: ... undefined link/ref to `dlsym'
libCoolProp.so: ... undefined link/ref to `dlopen'

3. In the cases 1 and 2 the following adjustments had been used:
Build command: g++ -std=c++11 -Wall -O2 -o example -I/usr/local/CoolProp/6.1.0/CoolProp/include -L/usr/local/CoolProp/6.1.0/CoolProp/build example.cpp -lCoolProp
Operating system: Ubuntu 14.04 as Windows subsystem for Linux (Windows 10)
Compiler version: GNU Compiler g++ 4.8.4
CoolProp version: 6.1.0
Source code of the example file:
`#include <iostream>
#include "CoolProp.h"

int main(){
   double T{293.15};
   double P{1e5};
   //double res{0.0};
   double res{CoolProp::PropsSI("D", "T", T, "P", P, "Water")};
   std::cout << "Density: " << res << std::endl;
}`
Does anyone know this problem and occasionally could provide a solution? Thanks in advance!

**Comment by ibell** [comment]
You need to link to the dynamic library library in Linux with -ldl.  How
did you build your dynamic/static libraries?

Also you might want to consider using using Cmake.  See the example here:
https://github.com/CoolProp/simple_cmake_example

**Comment by Haasrobertgmxnet** [comment]
Hello Ian Bell,

 

as in http://www.coolprop.org/dev/coolprop/wrappers/StaticLibrary/index.html#static-library

I have used:

 

# Check out the sources for CoolProp
git clone https://github.com/CoolProp/CoolProp --recursive
# Move into the folder you just created
cd CoolProp
# Make a build folder
mkdir -p build && cd build
# Build the makefile using CMake
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON
# Make the static library
cmake --build .

 

for the static library with the following results:

Windows 7/10: Build of the static lib: fine. Builds using the static lib: also fine.

Windows subsystem for linux: Build of the static lib: without reporting errors/warnings. Builds using the static lib: with errors and interrupting build process.

 

For the ahared libraryI used "cmake .. -DCOOLPROP_SHARED_LIBRARY=ON" instead of "cmake .. -DCOOLPROP_STATIC_LIBRARY=ON".

 

At the moment I probably could use a workaround producing grid data in Windows 10 and then packing them into an unordered_map in C++.

 

Robert

 

 

Gesendet: Freitag, 24. November 2017 um 19:29 Uhr
Von: "Ian Bell" <notifications@github.com>
An: CoolProp/CoolProp <CoolProp@noreply.github.com>
Cc: Haasrobertgmxnet <Haasrobert@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [CoolProp/CoolProp] Error when compiling/linking CoolProp in C++ (#1600)

You need to link to the dynamic library library in Linux with -ldl. How
did you build your dynamic/static libraries?

Also you might want to consider using using Cmake. See the example here:
https://github.com/CoolProp/simple_cmake_example

**Comment by jowr** [comment]
It looks like you are missing the dynamic linker. Have you tried adding `${CMAKE_DL_LIBS}` to the linked libraries? Find an example here: https://github.com/CoolProp/CoolProp/commit/c1e0f1259545e6e740bd700eb99885abeff9eb82

**Comment by ibell** [comment]
@jowr is right - that's a manifestation of the same issue that I mention.

**Comment by Haasrobertgmxnet** [comment]
Using this fix I got the following:

 

I) Building static library:

 

1) Insert blank line and "target_link_libraries (${LIB_NAME} ${CMAKE_DL_LIBS})" in CMakeLists.txt

2) rm -rf build/* and cd build

3) cmake .. -DCOOLPROP_STATIC_LIBRARY=ON
4) Make the static library
5) cmake --build .

6) changing to project dir

7) g++ -std=c++11 -Wall -O2 -o example -I/usr/local/CoolProp/6.1.0/CoolProp/include -L/usr/local/CoolProp/6.1.0/CoolProp/build example.cpp -lCoolProp

.. with result: 

/usr/local/CoolProp/6.1.0/CoolProp/build/libCoolProp.a(REFPROPMixtureBackend.cpp.o): In Funktion `getFunctionPointer(char const*, DLLNameManglingStyle)':
REFPROPMixtureBackend.cpp:(.text+0x16e): Nicht definierter Verweis auf `dlsym'


/usr/local/CoolProp/6.1.0/CoolProp/build/libCoolProp.a(REFPROPMixtureBackend.cpp.o): In Funktion `load_REFPROP(std::string&, std::string const&)':
REFPROPMixtureBackend.cpp:(.text+0xd0b): Nicht definierter Verweis auf `dlopen'


/usr/local/CoolProp/6.1.0/CoolProp/build/libCoolProp.a(REFPROPMixtureBackend.cpp.o): In Funktion `CoolProp::REFPROPMixtureBackend::~REFPROPMixtureBackend()':
REFPROPMixtureBackend.cpp:(.text+0x1aab): Nicht definierter Verweis auf `dlclose'


collect2: error: ld returned 1 exit status


 

II) Building so library:

 


1) Insert blank line and "target_link_libraries (${LIB_NAME} ${CMAKE_DL_LIBS})" in CMakeLists.txt

2) rm -rf build/* and cd build

3) cmake .. -DCOOLPROP_SHARED_LIBRARY=ON
4) Make the static library
5) cmake --build .

6) changing to project dir

7) g++ -std=c++11 -Wall -O2 -o example -I/usr/local/CoolProp/6.1.0/CoolProp/include -L/usr/local/CoolProp/6.1.0/CoolProp/build example.cpp -lCoolProp  ... No errors

8) Running ./example

..../example: error while loading shared libraries: libCoolProp.so.6: cannot open shared object file: No such file or directory

 

Code of example.cpp :

 


#include <iostream>
#include "CoolProp.h"

int main(){
   double T{293.15};
   double P{1e5};
   double res{CoolProp::PropsSI("D", "T", T, "P", P, "Water")};
   std::cout << "Density: " << res << std::endl;
}


 

Robert

 



Gesendet: Montag, 27. November 2017 um 03:34 Uhr
Von: "Ian Bell" <notifications@github.com>
An: CoolProp/CoolProp <CoolProp@noreply.github.com>
Cc: Haasrobertgmxnet <Haasrobert@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [CoolProp/CoolProp] Error when compiling/linking CoolProp in C++ (#1600)

@jowr is right - that's a manifestation of the same issue that I mention.

**Comment by ibell** [comment]
For a static library, starting in the root of the CoolProp repo:
```
mkdir build
cd build
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON
cmake --build .
nano example.cpp # put in your file
g++ -std=c++11 -Wall -O2 -o example -I../include -L. example.cpp -lCoolProp
-ldl
```
Works just fine for me.

With the DLL option, also starting in the root of the CoolProp repo:
```
mkdir build
cd build
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON
cmake --build .
nano example.cpp # put in your file
g++ -std=c++11 -Wall -O2 -o example -I../include -L. example.cpp -lCoolProp
-ldl
```
builds, but I too get the same error:
```
ian@ian-ThinkPad-X220:~/Code/CoolProp/wdll$ ./example
./example: error while loading shared libraries: libCoolProp.so.6: cannot
open shared object file: No such file or directory
```
But really, you should configure CoolProp as a cmake dependency, much
cleaner.  See for instance  https://github.com/CoolProp/simple_cmake_example

**Comment by ibell** [comment]
Evidently, the problem is that the g++ only follows the first symbolic
link, and not all the way to the libCoolProp.so.6.1.1dev

```
ian@ian-ThinkPad-X220:~/Code/CoolProp/wdll$ ldd example
    linux-vdso.so.1 =>  (0x00007ffed85f0000)
    libCoolProp.so.6 => not found
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f78b5645000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007f78b52bd000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
(0x00007f78b50a6000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f78b4cdf000)
    /lib64/ld-linux-x86-64.so.2 (0x000055c693440000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f78b49d4000)
```
@jowr it is something funny with the symbolic linking magic you added. Any
idea?

**Comment by ddydai** [comment]
A same problem is in SUSE Leap42.3 following "instance https://github.com/CoolProp/simple_cmake_example"
would anyone help me?
........
...
[ 97%] Building CXX object CMakeFiles/main.dir/mycode.cpp.o
[100%] Linking CXX executable main
CoolProp/libCoolProp.a(REFPROPMixtureBackend.cpp.o)：在函数‘getFunctionPointer(char const*, DLLNameManglingStyle)’中：
REFPROPMixtureBackend.cpp:(.text+0x214)：对‘dlsym’未定义的引用
CoolProp/libCoolProp.a(REFPROPMixtureBackend.cpp.o)：在函数‘load_REFPROP(std::string&, std::string const&, std::string const&)’中：
REFPROPMixtureBackend.cpp:(.text+0xf79)：对‘dlopen’未定义的引用
REFPROPMixtureBackend.cpp:(.text+0xfa5)：对‘dlerror’未定义的引用
CoolProp/libCoolProp.a(REFPROPMixtureBackend.cpp.o)：在函数‘unload_REFPROP(std::string&)’中：
REFPROPMixtureBackend.cpp:(.text+0x124d)：对‘dlclose’未定义的引用
REFPROPMixtureBackend.cpp:(.text+0x1263)：对‘dlerror’未定义的引用
CoolProp/libCoolProp.a(REFPROPMixtureBackend.cpp.o)：在函数‘CoolProp::REFPROPMixtureBackend::~REFPROPMixtureBackend()’中：
REFPROPMixtureBackend.cpp:(.text+0x1d55)：对‘dlclose’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/main.dir/build.make:95: recipe for target 'main' failed
gmake[2]: *** [main] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/main.dir/all' failed
gmake[1]: *** [CMakeFiles/main.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
gmake: *** [all] Error 2
daiyq:~/simple_cmake_example/build #

**Comment by ibell** [comment]
Please do no hijack issues - you had a different issue that should have
been reported at https://github.com/CoolProp/simple_cmake_example.
Nonetheless I have fixed the issues with the CMakeLists.txt - see the other
repo

**Comment by Haasrobertgmxnet** [comment]
Just a question: Is the issue "Error when compiling/linking CoolProp in C++ #1600" still open, or moved, or closed yet? And how is the current state?

**Comment by jowr** [comment]
There are quite a few issues here: 

- Please use the correct header: `CoolPropLib.h`, not `CoolProp.h`
- Please make yourself familiar with dynamic linking on the Linux platform

The problem boils down to the missing installation of the dynamic libraries. The linking works because you specify an additional path, execution fails because the path information is not available at runtime. 


### Get the sources: 
```shell
git clone --recursive https://github.com/coolprop/coolprop CoolProp.tmp.git
mkdir build_static
mkdir build_dynamic
mkdir build_main
cat <<EOF > build_main/main.cpp
#include <iostream>
#include "CoolPropLib.h"
int main(){
    double T{293.15};
    double P{1e5};
    //double res{0.0};
    double res{PropsSI("D", "T", T, "P", P, "Water")};
    std::cout << "Density: " << res << std::endl;
}

EOF
```

### Compile the libraries
```shell
pushd build_static
cmake ../CoolProp.tmp.git -DCOOLPROP_STATIC_LIBRARY=ON 
cmake --build .
popd
pushd build_dynamic
cmake ../CoolProp.tmp.git -DCOOLPROP_SHARED_LIBRARY=ON 
cmake --build .
popd
```

### Test the code
```shell
pushd build_main
g++ -std=c++11 -Wall -O2 -o main -I../CoolProp.tmp.git/include -L../build_static main.cpp -lCoolProp -ldl
./main # work just fine!
rm main
g++ -std=c++11 -Wall -O2 -o main -DCOOLPROP_LIB -I../CoolProp.tmp.git/include main.cpp ../build_dynamic/libCoolProp.so -ldl
LD_LIBRARY_PATH=`pwd`/../build_dynamic ./main # work just fine!
popd
```
