### ISSUE TITLE
ValueError: HAProps failed ungracefully with inputs: "W","T",2.7852603934336025e+02,"P",1.0132500000000000e+05,"H",1.4114309647910737e+04

### ISSUE THREAD

**Issue by ranhamku** [CoolProp/CoolProp#1601]
I try to run a cycle test of heat pump:
'''This code is for Direct Expansion in Heating Mode'''

from Cycle import DXCycleClass
from convert_units import F2K

#Instantiate the class
Cycle=DXCycleClass()

#--------------------------------------
# Cycle parameters
#--------------------------------------
Cycle.Verbosity = 0 #the idea here is to have different levels of debug output
Cycle.ImposedVariable = 'Subcooling' #or it could be 'Charge'
Cycle.DT_sc_target = 7.0
#Cycle.Charge_target = 3.3 #uncomment for use with imposed charge
Cycle.Mode='HP'
Cycle.Ref='R410A'
Cycle.Backend='TTSE&HEOS' #Backend for refrigerant properties calculation: 'HEOS','TTSE&HEOS','BICUBIC&HEOS','REFPROP','SRK','PR'

#--------------------------------------
#       Compressor parameters
#--------------------------------------
#A few 3 ton cooling capacity compressor maps
M=[217.3163128,5.094492028,-0.593170311,4.38E-02,-2.14E-02,1.04E-02,7.90E-05,-5.73E-05,1.79E-04,-8.08E-05]
P=[-561.3615705,-15.62601841,46.92506685,-0.217949552,0.435062616,-0.442400826,2.25E-04,2.37E-03,-3.32E-03,2.50E-03]

params={
        'M':M,
        'P':P,
        'Ref':Cycle.Ref,        #refrigerant
        'Backend':Cycle.Backend, #Backend for refrigerant properties calculation
        'fp':0.0, #Fraction of electrical power lost as heat to ambient #shell heat loss
        'Vdot_ratio': 1.0, #Displacement Scale factor #up- or downsize compressor
        'Verbosity': 0, # How verbose should the debugging statements be [0 to 10]
        }

Cycle.Compressor.Update(**params)

#--------------------------------------
# Condenser parameters
#--------------------------------------
Cycle.Condenser.Fins.Tubes.NTubes_per_bank=32
Cycle.Condenser.Fins.Tubes.Nbank=3
Cycle.Condenser.Fins.Tubes.Ncircuits=6
Cycle.Condenser.Fins.Tubes.Ltube=0.452
Cycle.Condenser.Fins.Tubes.OD=0.009525
Cycle.Condenser.Fins.Tubes.ID=0.0089154
Cycle.Condenser.Fins.Tubes.Pl=0.0254
Cycle.Condenser.Fins.Tubes.Pt=0.0219964

Cycle.Condenser.Fins.Fins.FPI=14.5
Cycle.Condenser.Fins.Fins.Pd=0.001
Cycle.Condenser.Fins.Fins.xf=0.001
Cycle.Condenser.Fins.Fins.t=0.00011
Cycle.Condenser.Fins.Fins.k_fin=237

Cycle.Condenser.Fins.Air.Vdot_ha=0.5663
Cycle.Condenser.Fins.Air.Tmean=F2K(70)
Cycle.Condenser.Fins.Air.Tdb=F2K(70)
Cycle.Condenser.Fins.Air.p=101325                                               #Condenser Air Pressure in Pa
Cycle.Condenser.Fins.Air.RH=0.51
Cycle.Condenser.Fins.Air.RHmean=0.51
Cycle.Condenser.Fins.Air.FanPower=438

Cycle.Condenser.FinsType = 'WavyLouveredFins'        #WavyLouveredFins, HerringboneFins, PlainFins
Cycle.Condenser.Ref=Cycle.Ref
Cycle.Condenser.Backend=Cycle.Backend
Cycle.Condenser.Verbosity=0

#--------------------------------------
# Evaporator parameters
#--------------------------------------
Cycle.Evaporator.Fins.Tubes.NTubes_per_bank=41 #number of tubes per bank=row
Cycle.Evaporator.Fins.Tubes.Nbank=1 #number of banks/rows
Cycle.Evaporator.Fins.Tubes.Ncircuits=5
Cycle.Evaporator.Fins.Tubes.Ltube=2.286
Cycle.Evaporator.Fins.Tubes.OD=0.007
Cycle.Evaporator.Fins.Tubes.ID=0.0063904
Cycle.Evaporator.Fins.Tubes.Pl=0.0191 #distance between center of tubes in flow direction
Cycle.Evaporator.Fins.Tubes.Pt=0.0222 #distance between center of tubes orthogonal to flow direction
Cycle.Evaporator.Fins.Fins.FPI=25   #Number of fins per inch
Cycle.Evaporator.Fins.Fins.Pd=0.001 #2* amplitude of wavy fin
Cycle.Evaporator.Fins.Fins.xf=0.001 #1/2 period of fin
Cycle.Evaporator.Fins.Fins.t=0.00011    #Thickness of fin material
Cycle.Evaporator.Fins.Fins.k_fin=237    #Thermal conductivity of fin material

Cycle.Evaporator.Fins.Air.Vdot_ha=1.7934 #rated volumetric flowrate
Cycle.Evaporator.Fins.Air.Tmean=F2K(47)
Cycle.Evaporator.Fins.Air.Tdb=F2K(47)
Cycle.Evaporator.Fins.Air.p=101325                                              #Evaporator Air pressure in Pa
Cycle.Evaporator.Fins.Air.RH=0.51
Cycle.Evaporator.Fins.Air.RHmean=0.51
Cycle.Evaporator.Fins.Air.FanPower=160

Cycle.Evaporator.FinsType = 'WavyLouveredFins'        #WavyLouveredFins, HerringboneFins, PlainFins
Cycle.Evaporator.Ref=Cycle.Ref
Cycle.Evaporator.Backend=Cycle.Backend
Cycle.Evaporator.Verbosity=0
Cycle.Evaporator.DT_sh=5

# ----------------------------------
# Line Set parameters
# ----------------------------------
params={
        'L':7.6,
        'k_tube':0.19,
        't_insul':0.02,
        'k_insul':0.036,
        'T_air':297,
        'Ref': Cycle.Ref,
        'Backend': Cycle.Backend,
        'h_air':6,
        }

Cycle.LineSetSupply.Update(**params)
Cycle.LineSetReturn.Update(**params)
Cycle.LineSetSupply.OD=0.01905
Cycle.LineSetSupply.ID=0.017526
Cycle.LineSetReturn.OD=0.009525
Cycle.LineSetReturn.ID=0.007986

#Now solve
from time import time
t1=time()
Cycle.PreconditionedSolve()

#Outputs
print: 'Took '+str(time()-t1)+' seconds to run Cycle model'
print: 'Cycle coefficient of system performance is '+str(Cycle.COSP)
print: 'Cycle refrigerant charge is '+str(Cycle.Charge)+' kg'

and then I got the error:
ValueError: HAProps failed ungracefully with inputs: "W","T",2.7852603934336025e+02,"P",1.0132500000000000e+05,"H",1.4114309647910737e+04

my python version is 3.6.1 |Anaconda 4.4.0(64-bit)
could anyone please tell me what's wrong with it?

**Comment by davideziviani** [comment]
Yes. I had that problem before. I downgraded CoolProp to v6.1. That did the trick on having more stable humid air properties. I use ACHP on daily basis and I did not have anymore issues. If I run your T,P,H inputs with HAPropsSI, I get:

w = 0.003518012539053808

**Comment by ranhamku** [comment]
@davideziviani 
thank you for the advise, I'll try to use CoolProp V6.1

**Comment by ranhamku** [comment]
@davideziviani sorry for the interruption, but could you please tell me the range of three inputs of T,P,H? Cause I want to run the cycleTest on my machine learning algorithm, and I want to know the range of the input value. Could you please tell me about that? And another question, if i modify the three inputs in the cycleTest within the range, can I get an optimal COP? Thanks a lot

**Comment by ibell** [comment]
Closed by 1c6497a92f37a36f98448455dd32968fe1d6c564
