### ISSUE TITLE
hmass() gives strange result after calling update() with PQ_INPUTS in specific case

### ISSUE THREAD

**Issue by absvm** [CoolProp/CoolProp#1602]
In a very specific case (see code below) it happens that hmass() returns an strange value.

This happens when update(input_pairs.PQ_INPUTS,..) is called after a call to specify_phase(phases.iphase_liquid). It's as if the reference state gets invalidated. 

Iphase_liquid may be an invalid state for PQ_INPUTS, which may be causing the trouble, but I'd expect an exception or some other sign that something is failing....

Code in C#:

`            CoolProp.set_reference_stateS("D2O", "NBP");
            AbstractState HEOS = AbstractState.factory("HEOS", "D2O");

            double p_Pa = 15E5;

            //HEOS.update(input_pairs.PQ_INPUTS, p_Pa, 0.5);
            //double t_satp = HEOS.T();

            double T_K = 400;

            HEOS.update(input_pairs.PT_INPUTS, p_Pa, T_K);
            double h0 = HEOS.hmass() / 1000; // in kJ/kg

            Console.WriteLine(String.Format("hmass() D2O (ref NBP) at p={0:G4} bar, {1:G4}K: {2:G4} kJ/kg", p_Pa/1E5, T_K, h0));

            // this call to specify_phase() happens somewhere in my code
            HEOS.specify_phase(phases.iphase_liquid);

            // test hmass
            HEOS.update(input_pairs.PT_INPUTS, p_Pa, T_K);
            h0 = HEOS.hmass() / 1000; // in kJ/kg

            // hmass() value is still at NBP reference
            Console.WriteLine(String.Format("hmass() after calling specify_phase(phases.iphase_liquid) {0:G4}", h0));

            // call to get saturation temp
            HEOS.update(input_pairs.PQ_INPUTS, p_Pa, 0);
            double t_satp = HEOS.T();

            // now hmass() value is off
            HEOS.update(input_pairs.PT_INPUTS, p_Pa, T_K);
            h0 = HEOS.hmass() / 1000; // in kJ/kg

            Console.WriteLine(String.Format("hmass() after calling T() with PQ_INPUTS {0:G4}", h0));`

which yields the following output:

hmass() D2O (ref NBP) at p=15 bar, 400K: 107.1 kJ/kg
hmass() after calling specify_phase(phases.iphase_liquid) 107.1
hmass() after calling T() with PQ_INPUTS -1361

**Comment by ibell** [comment]
Odd.  As a workaround, you can always call AS.unspecify_phase()

**Comment by henningjp** [comment]
This is a bug.

The update() call with PQ_INPUTS (on saturation curve) sets the internal ``_phase`` to ``iphase_twophase``.  Coming back to the update() call with PT_INPUTS, the imposed phase is still liquid, but it is assumed that ``_phase`` has already set to the imposed phase (but it's been changed).

Easy fix.  Patch on its way...
