### ISSUE TITLE
Humid air propterties in excel

### ISSUE THREAD

**Issue by RasmusAM** [CoolProp/CoolProp#1617]
Hi

I am currently working on an Excel sheet for ventilation engineering calculations. I want to utilize CoolProp for this, however it seems there are some areas that the humid air properties cant' be found.

![image](https://user-images.githubusercontent.com/34379310/33777402-f7048bf0-dc44-11e7-9f57-e8575a0a0ab0.png)

As shown on the image above, it works fine in some areas, but in others not at all.. I have tried the same function i Mathcad Prime, and that works flawlessly. I suspect the Excel wrapper to be corrupted somehow.. The wrapper is installed using the installer.

Kind regards
Rasmus

**Comment by ibell** [comment]
Is it somehow an issue with the old comma versus semicolon problem in
Excel?  That would be my guess if it works properly in MathCAD.  Are you
sure you are using exactly the same version of CoolProp in both tools?

**Comment by RasmusAM** [comment]
Hi ibell

Thank you for your fast reply :)

I don't know why, but I just tried the program on another computer, and there everything worked as it should. Apperantly, that some files were not placed in AppData\Roaming\CoolProp folder for some reason. After copying them to the "faulty" computer everything seems to be working!
