### ISSUE TITLE
Excel and Python wrapper, HAPropsSI problem with P_w input

### ISSUE THREAD

**Issue by sodynamic** [CoolProp/CoolProp#1618]
the function used in Excel is very simple, like
=HAPropsSI("R","P",90000,"T",320,"P_w",7720)

which generates an error
"The most recent error number is 6. Its message text is: 溢出"

The chinese word here means overflow. And if you change the partial pressure of the water a little bit, it works very well, like
=HAPropsSI("R","P",90000,"T",320,"P_w",7710)
it generates the result 0.727597, which seems to be correct.

I try this command using Excel 2016 x64, and I also try this command using Python 3.5.4. An error pops up again, like

_import CoolProp.CoolProp as CP
CP.HAPropsSI("R","P",90000,"T",320,"P_w",7710)_
0.7275974704670822
_CP.HAPropsSI("R","P",90000,"T",320,"P_w",7720)_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:5201)
  File "CoolProp\HumidAirProp.pyx", line 49, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:3891)
ValueError: HAProps failed ungracefully with inputs: "R","P",9.0000000000000000e+04,"T",3.2000000000000000e+02,"P_w",7.7200000000000000e+03

Can anyone give me some suggestion please? Thanks a lot!

**Comment by ibell** [comment]
Closed by 1c6497a92f37a36f98448455dd32968fe1d6c564
