### ISSUE TITLE
CoolProp Function PropsSI/PhaseSI

### ISSUE THREAD

**Issue by Haasrobertgmxnet** [CoolProp/CoolProp#1627]
Does anyone know which values will returned by the function `PropsSI('Phase',...)`? As far as I could see from Documentation it is 0 for the liquid phase ans 6 (and why?) for the mixed phase. How about the vapour/gas phase?

**Comment by henningjp** [comment]
From DataStructures.h:

```C++
/// These are constants for the phases of the fluid
enum phases{iphase_liquid, ///< Subcritical liquid 
            iphase_supercritical, ///< Supercritical (p > pc, T > Tc)
            iphase_supercritical_gas, ///< Supercritical gas (p < pc, T > Tc)
            iphase_supercritical_liquid, ///< Supercritical liquid (p > pc, T < Tc)
            iphase_critical_point, ///< At the critical point
            iphase_gas, ///< Subcritical gas
            iphase_twophase, ///< Twophase
            iphase_unknown, ///< Unknown phase
            iphase_not_imposed}; ///< Phase is not imposed

```
They are enumerated from 0 to 8, sequentially.

**Comment by ibell** [comment]
How are you calling CoolProp?  From Excel?  There is also the PhaseSI
function that returns the phase as a string, see:
http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function

If using other environments (e.g., Python), you can extract the value of
each of the phase flags programatically.  You should not in general count
on the order of the enumerated values being stable.

**Comment by Haasrobertgmxnet** [comment]
I call it from C++ using this style: "CoolProp::PropsSI("D", "T", T, "P", p, FluidName);"

 

 

Gesendet: Donnerstag, 04. Januar 2018 um 16:26 Uhr
Von: "Ian Bell" <notifications@github.com>
An: CoolProp/CoolProp <CoolProp@noreply.github.com>
Cc: Haasrobertgmxnet <Haasrobert@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [CoolProp/CoolProp] CoolProp Function PropsSI/PhaseSI (#1627)

How are you calling CoolProp? From Excel? There is also the PhaseSI
function that returns the phase as a string, see:
http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function

If using other environments (e.g., Python), you can extract the value of
each of the phase flags programatically. You should not in general count
on the order of the enumerated values being stable.

**Comment by ibell** [comment]
Ah - C++, good, that is easy for integration with CoolProp. In that case,
you should probably always be using the low-level interface (
http://www.coolprop.org/coolprop/LowLevelAPI.html).  That will allow you to
get the phase enumeration directly without translation.

Best,
Ian
