### ISSUE TITLE
PhaseSI gives empty String

### ISSUE THREAD

**Issue by somniumAeternam** [CoolProp/CoolProp#1631]
The following PhaseSI call gives a empty str in Python, where it should be 'twophase':

```python
In: PhaseSI("T",270.3895839,"P",264626.0542,"R134a")
Out: ''
```
To check, here are the values with  slightly other pressures:
```python
In: PhaseSI("T",270.3895839,"P",264627,"R134a")
Out: 'liquid'
```
```python
In: PhaseSI("T",270.3895839,"P",264625,"R134a")
Out: 'gas'
```

The same call with PropsSI raises an error:
```python
In: PropsSI('Phase', "T",270.3895839,"P",264626.0542,"R134a")
ValueError                                Traceback (most recent call last)
<ipython-input-9-ee13f0b9fd26> in <module>()
----> 1 PropsSI('Phase', "T",270.3895839,"P",264626.0542,"R134a")

CoolProp/CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:36859)()

CoolProp/CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:36644)()

CoolProp/CoolProp.pyx in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:34849)()

ValueError: Saturation pressure [264626 Pa] corresponding to T [270.39 K] is within 1e-4 % of given p [264626 Pa] : PropsSI("Phase","T",270.3895839,"P",264626.0542,"R134a")
```

I'm using CoolProp 6.1 with Python 3.5 on Windows 7. Is the pair T and P generally bad for determining the Phase?

**Comment by somniumAeternam** [comment]
That makes sense. But the PhaseSI call should return 'twophase', no?

**Comment by ibell** [comment]
Hmm. Good question.  I would vote that it should return the error from the
PropsSI call because it is not possible to diambiguate the phase when you
are *very close* to the saturation curve.

**Comment by henningjp** [comment]
I think the key here is the definition of two-phase. Since CoolProp considers the two-phase region to be _exclusively_ between the liquid and vapor saturation curves themselves, the state point could be either liquid (Q=0), two-phase (0 > Q > 1), or gas (Q=1); however, with only T and P inputs it can't be determined.

**Comment by ibell** [comment]
That is very close to being spot-on. Saturated liquid (Q=0) and vapor (Q=1) are still considered to be two-phase states.  Nonetheless, you cannot disambiguate saturated from very-nearly-saturated states with T&P inputs.

**Comment by somniumAeternam** [comment]
I think, the best way to overcome this, is to raise the same error as in PropsSI and don't return an empty string. In that way, everybody sees directly, if something is wrong.

**Comment by ibell** [comment]
Agreed.  That definitely makes the most sense in python, not sure in other
environments

**Comment by henningjp** [comment]
@ibell What if PhaseSI just returned "unknown" when PropsSI fails, since that's what it really is, instead of a blank string.  Maybe even tagged with the e.msg() string that came from PropsSI(), if it's not empty.

**Comment by ibell** [comment]
I think I like the solution of @henningjp .  Want to put this together?  I think you have the necessary expertise.
