### ISSUE TITLE
Issue with MATLAB wrapper

### ISSUE THREAD

**Issue by Larry1957** [CoolProp/CoolProp#1632]
After having followed the instructions to install the CoolProp MATLAB wrapper (from last night build), when trying from the MATLAB command prompt 

>> CoolProp.PropsSI('T','P',101325,'Q',0,'Water') I am receiving

Warning: function AbstractState_d4alphar_dDelta3_dTau takes at most 1 arguments 
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(345,varargin{:});

I am running MATLAB R.2015a under 32-bit Windows.

What is wrong?   Thanks for your help

**Comment by ibell** [comment]
Could you please show the setup of your files in your CoolProp
installation?  Where did you get the MATLAB files from?  Development server
or sourceforge?

**Comment by Larry1957** [comment]
Thnaks a lot Ian.
I am using MATLAB made available on a Company server.  I launch the MATLAB 
script  which then execute at a certain point my own specific startup in 
my local directory 'C:\Users\....\Documents\MATLAB'.

As part of the installation I created and populated  the sub-direcotry and 
added to the path with proper MATLAB addpath('...')
C:\Users\....\Documents\MATLAB\msin


TMATS contains other tools (not controlleld by me)

the  main subdirectory contains



which I suppose contains what it should.   These files  are the results of 
the expansion of a .Z file and all the other files have been downloaded 
from the SOURCE FORGE site.

I remarked that the CoolPropsetup.m  does only contain 

Is this a problem?

Thanks for your support

Best Regards

Lorenzo MOTTER

**Comment by ibell** [comment]
I'm not sure if you tried to attach images to your email response.  If so,
can you try again in the web interface?  I can't see any of things that I
assume are pictures.

**Comment by Larry1957** [comment]
I've updated my comment with uploaded images.
basically I remarked that the CoolPropsetup.m file contains just a comment line; maybe this is the cause of the problem?

**Comment by Larry1957** [comment]
FOUND and solved the issue.  I downloaded again from SourceForge the file CoolPropMATLAB_wrap.mexw32 (the 32 bit MATLAB wrapper) and found that its size was different from the ones I previously downloaded ((3,592,704 bytes against the former (3,845,120 bytes).
With the ne wdownloaded wrapper the CoolProp MATLAB interface appears to work.  
Thanks for your support!

**Comment by ibell** [comment]
Weird, but glad to hear you sorted out your issue.  Can you please close
the issue?

**Comment by Larry1957** [comment]
Issue is closed.
Thnaks
