### ISSUE TITLE
PHP wrapper on windows by using XAMPP

### ISSUE THREAD

**Issue by faulesWalross** [CoolProp/CoolProp#1635]
Hi guys,

I'm using CoolProp by Excel since 10 months and it works perfectly. Now I wanted to try it by PHP using the Apache Server by XAMPP. I copied the CoolProp.dll from sourceforge/shared_library to the ext-folder (because in sourceforge/PHP is only a linux file) and the CoolProp.php to my project. Also put the line extension=CoolProp to the php.ini.

When running phpinfo I can't see, that the DLL is loaded and by testing a CoolProp-Function I get this reponse:

Fatal error: Uncaught Error: Call to undefined function dl() in C:\xampp\htdocs\Testprojekt\CoolProp.php:16 Stack trace: #0 C:\xampp\htdocs\Testprojekt\testCoolProp.php(2): require() #1 {main} thrown in C:\xampp\htdocs\Testprojekt\CoolProp.php on line 16

Do you have any idea what I'm doing wrong?

I would be very thankful for your support.
Please excuse my english...

![grafik](https://user-images.githubusercontent.com/32844565/35217998-636d5b96-ff6d-11e7-8ae3-900f9dcbb99b.png)

**Comment by jowr** [comment]
The dynamic linking functions are disabled by default, see http://php.net/manual/en/function.dl.php - you might have to leave safe mode. I suspect that this is a PHP configuration problem...

**Comment by ibell** [comment]
In addition, I don't think you want the "normal" shared library for
windows, you want the PHP shared library, which we only currently provide
for linux:
https://sourceforge.net/projects/coolprop/files/CoolProp/6.1.0/PHP/Linux/
.  But you could build your own, which you would have to do:
http://www.coolprop.org/coolprop/wrappers/PHP/index.html#user-compiled-binaries
.  The instructions there are for linux, but its more or less the same for
windows.  You could use one of the express compilers from microsoft (e.g.,
Visual Studio 2015).

**Comment by faulesWalross** [comment]
Hi Jorrit and Ian,

thanks for your quick response. If I am right, the safe mode is removed since PHP 5.40 and also SWIG seems not to be compatible with PHP version later than 5.60. I'm using PHP 7 (actually I try to learn it self-educated).

I think I'm far away from being able to build my own PHP-DLL. First of all I will learn PHP and a little HTML, later I can try to build DLLs by using Visual Studios and SWIG. If I manage that I will let you know.

Do I have close that issue?

Thanks for your great work.
Mirko

**Comment by ibell** [comment]
According to the docs, PHP 7 should work:
http://www.swig.org/Doc3.0/Php.html (Often you will hit the ancient docs
for SWIG version 1.3, though I'm not totally sure why).  I think there are
quite a few people that use PHP + SWIG, so I suspect it would work well.
I'm not sure how well all this would work on windows, but anything you
learn would be welcomed to be shared back with CoolProp folks.

**Comment by ibell** [comment]
Closing for now, let us know if you want to revisit this point
