### ISSUE TITLE
Mixtures in Python using CoolProp

### ISSUE THREAD

**Issue by adrianycchan** [CoolProp/CoolProp#1637]
Hi all,

I am currently trying to run coolprop with a mixtures of R245fa and R601a at different concentrations, however,  I keep getting the same error every time I run it:
ValueError: phase envelope must be built to carry out HSU_P_flash for mixture :
PropsSI("T","H",197289.2121,"P",781143.5208,"HEOS::R245fa[0.5]&R601a[0.5]").
My code works perfectly fine when running for pure fluids, however, once a mixture is inputted it returns the above error.

I'm not sure how to build a phase envelope and is there any way to solve this with CoolProp for mixtures by adding additional code?

**Comment by ibell** [comment]
What language are you calling CoolProp from?  The construction of phase
envelopes is only available in the low-level interface.

Also, the routines in general are not very robust for mixtures.  For more
robust mixture calculations, you will either need to write the routines
yourself or use NIST REFPROP :)

**Comment by davideziviani** [comment]
Adrian, as I replied in your email, quick workaround is to replace high-level interface with low-level interface: 

import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt

HEOS = CP.AbstractState('REFPROP','R245fa&IPENTANE')

# Biuld and visualize phase envelopes
for x0 in [0.02, 0.2, 0.4, 0.6, 0.8, 0.98]:
    HEOS.set_mole_fractions([x0, 1 - x0])
    try:
        HEOS.build_phase_envelope("dummy")
        PE = HEOS.get_phase_envelope_data()
        plt.plot(PE.T, PE.p, '-')
    except ValueError as VE:
        print(VE)

plt.xlabel('Temperature [K]')
plt.ylabel('Pressure [Pa]')
plt.yscale('log')
plt.show()

# Set the mole fraction of interest
HEOS.set_mole_fractions([0.5, 0.5])

# Example PQ inputs
HEOS.update(CP.PQ_INPUTS, 781143.5208,0)
T = HEOS.T()
h = HEOS.hmass()

print 'Temperature',T,'[K]'


# Example Hmass-P inputs
HEOS.update(CP.HmassP_INPUTS, 197289.2121, 781143.5208)

print 'Temperature',HEOS.T(),'[K]'

**Comment by davideIMI** [comment]
Hello, I have the same problem as adrianycchan. I know I have to do a phase envelop in low level interface to fix it but I am not sure how to do it. Could you please send me the working example you mentioned. I am using VB.NET but I am confident that I could translate the same code from Python if I have an example. Thanks very much.

**Comment by ibell** [comment]
Please see my comments in #1897
