### ISSUE TITLE
[MATLAB/Python] Error using REFPROP backend when calling Python low-level interface from MATLAB

### ISSUE THREAD

**Issue by stephen-young** [CoolProp/CoolProp#1641]
For some context see the following discussion in the [Google Group](https://groups.google.com/forum/#!topic/coolprop-users/LEMKlfHcjdw).

REFPROP back-end is not working when calling the Python low-level interface from MATLAB but when I call the low-level interface from the dll it works fine.

Running the following code:

```
path_to_lib = './CoolProp/libs/shared'; %specify path to coolprop shared library
path_to_include= './CoolProp/include'; %specify path to coolprop's include folder

% Loading shared library
if ~libisloaded('coolprop') %checking whether library is already loaded
    addpath(path_to_lib)
    addpath(path_to_include)
    libname = 'libCoolProp' % OSX and linux
    if ispc
        libname = 'CoolProp'
    end
    loadlibrary(libname,'CoolPropLib.h','includepath',path_to_include,'alias','coolprop'); % loading library with alias coolprop
    disp('loaded CoolProp shared library.')
    disp('loaded these functions: ')
    libfunctions coolprop
end

buffer_size = 1000;
ierr = 0;
b = (1:1:buffer_size);
herr= char(b);

%Selecting backend and fluid
backend = 'REFPROP';
fluid = 'water';
[AS, sAS] = calllib('coolprop','AbstractState_factory',backend,fluid,ierr,herr,buffer_size);
AS2 = py.CoolProp.AbstractState(backend, fluid);
```
Will produce the following error:

```
Error using AbstractState>CoolProp.CoolProp.AbstractState.__cinit__ (CoolProp\CoolProp.cpp:11143) (line 32)
Python Error: ValueError: Could not load these fluids: water
```
I have the following REFPROP directories added to Windows' path variable:
C:\Program Files (x86)\REFPROP
C:\Program Files (x86)\REFPROP\fluids
C:\Program Files (x86)\REFPROP\mixtures

and WATER.FLD is present in the fluids directory.

My PC has the following stats:
OS: Windows 7 64-bit,
CPU: Intel Core i7-4600U CPU @ 2.10GHz 2.70GHz
RAM: 8GB
MATLAB Version: 2015b 64-bit
Python Version: 3.4 64-bit
Python CoolProp Version: 6.1.0

Any help would be much appreciated.

**Comment by ibell** [comment]
I take it you are using REFPROP 9.1 or 9.1.1?  REFPROP defaults to look for
fluid files in c:\Program Files\REFPROP, but not in c:\Program Files
(x86)\REFPROP, so there are three solutions, any of which should work:

1) Provide an absolute path for the fluid name, like C:\Program Files
(x86)\REFPROP\Fluids\WATER.FLD
2) Set the configuration variable ALTERNATIVE_REFPROP_PATH (see
http://www.coolprop.org/coolprop/Configuration.html )
3) Copy C:\Program Files (x86)\REFPROP to c:\Program Files\REFPROP

Also, you need not add the fluids or mixture files to the PATH, the PATH is
only needed to find REFPROP DLL in the first place.

This is an example of an excellent bug report, I'll cite it in other issues
people open.

**Comment by stephen-young** [comment]
The dll version of REFPROP is 9.1. I implemented options 2 and 3 and it works now. 

Thanks!
