### ISSUE TITLE
Mistake in function "inline_label" in CoolProp/Plots/Common.py

### ISSUE THREAD

**Issue by xaumex** [CoolProp/CoolProp#1644]
Hi,
There is a little mistake in function "inline_label" in CoolProp/Plots/Common.py

Line 1123 is 
--        if y is not None: y = dimx.to_SI(y)
and it should be
++        if y is not None: y = dimy.to_SI(y)

And line 1126 is
--        y = dimx.from_SI(y)
and it should be
++        y = dimy.from_SI(y)

**Comment by ibell** [comment]
Can you figure out how to make a pull request?  Please see https://github.com/CoolProp/CoolProp/wiki/Contributing%3A-git-development-workflow

**Comment by xaumex** [comment]
I was able to do a pull request #1656

**Comment by xaumex** [comment]
The merge of pull request closes this issue
