### ISSUE TITLE
Parsing of Mixtures depends on LOCALE 

### ISSUE THREAD

**Issue by dcore94** [CoolProp/CoolProp#1647]
I noticed that coolprop uses _strtod_ for parsing the mixtures string. Unfortunately strtod (on linux, the OS I'm working on) is locale dependent as per specifcation.
This means that the protocol for expressing mixtures fails on a machine with Italian locale in parsing  
HEOS::CO2[0]&METHANE[0.93]&PROPANE[0.02]&NITROGEN[0.04]&ETHANE[0.01]
with a strange message "p is not a valid number". I suspect because all fractions are coerced to 0.000.
It expects rather something like:
HEOS::CO2[0]&METHANE[0,93]&PROPANE[0,02]&NITROGEN[0,04]&ETHANE[0,01]
or using e notation (i. e. 93e-2).
I think that since the mixture string should be considered an independent protocol, it would be nice if coolprop could use a locale independent transformation from string to double.

**Comment by ibell** [comment]
Hmm....  Interesting/good point.  As a USA person, I have never really
worried about this, but you are probably right.  Want to file a PR fixing
this?

**Comment by dcore94** [comment]
> Hmm....  Interesting/good point.  As a USA person, I have never really
worried about this, but you are probably right.  Want to file a PR fixing
this?
Would love to do so but in this moment only the idea of setting up the build environment is too time consuming for my very tight schedule.
I could just point to @tknopp 's work [1] which could be used for inspiration ...
Thanks for the attention anyway.
[1] [https://gist.github.com/tknopp/9271244](https://gist.github.com/tknopp/9271244)

**Comment by ibell** [comment]
That looks quite helpful, thanks for reporting that.  I should probably
stick to a European locale when I am writing code in order to ensure that I
don't annoy my European friends with my encoding assumptions.

**Comment by dcore94** [comment]
> That looks quite helpful, thanks for reporting that.  I should probably
stick to a European locale when I am writing code in order to ensure that I
don't annoy my European friends with my encoding assumptions.

Don't worry. I simply think that all those things are hard to catch at first. And, IMO, the mistake is in the operating systems which make the wrong assumption that things like float parsing depend on users' preferences. There should be one only official representation for numbers at OS level. The rest is presentation and should be left to application UIs.

**Comment by ibell** [comment]
This was pretty interesting actually. See the solution in the linked PR.  Will that work for you?

**Comment by ibell** [comment]
Slight change in plan: ac84d0ddaf44ea13fa07472250daf7fb674ffdf0

**Comment by dcore94** [comment]
That's great. Thanks.
