### ISSUE TITLE
Refprop's corresponding functions for pressure, density, and chemical potential in CoolProp 

### ISSUE THREAD

**Issue by L4student** [CoolProp/CoolProp#1651]
There is a python code that uses `refprop`, but I am not sure how it was installed. Could someone please help translate three functions used in that code form `refprop` to their corresponding functions in `CoolProp`?

```
import refprop
refprop.press(T, float(d), x)['p']
refprop.limitx(x, htype='EOS', t=T, D=0, p=0)['Dmax']
refprop.chempot(T, float(d), x)['u']
```

**Comment by ibell** [comment]
These are all included in the low-level interface: http://www.coolprop.org/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface

Does that help?
