### ISSUE TITLE
Problem with saturated vapor internal energy calculations with quality/density inputs

### ISSUE THREAD

**Issue by gpsimms** [CoolProp/CoolProp#1652]
I have tested and found this to be a problem for at least water and R134a.

When calling for internal energy and giving quality and density as an input, the output is not incorrect.

e.g.

```
>> CoolProp.PropsSI('U','Q',.3,'T',373,'Water')

ans =

   1.0447e+06

>> CoolProp.PropsSI('D','Q',.3,'T',373,'Water')

ans =

    1.9811

>> CoolProp.PropsSI('U','Q',.3,'D',ans,'Water')

ans =

   4.1843e+05

```

Thanks!

**Comment by ibell** [comment]
I'll resolve this this weekend.

P.S. Please use code formatting to make your issues look nicer (click the < > button in the editing toolbar)

**Comment by gpsimms** [comment]
I fixed the format.  Thanks again for the time.

greg
