### ISSUE TITLE
Version 6.1 with Python 3.6.1 Anaconda (64-bit)

### ISSUE THREAD

**Issue by rddaz2013** [CoolProp/CoolProp#1654]
The normal way..

```
 pip install coolprop -> gives only 6.0.0 

 pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp
 -> python extension gives (*...so file) an error if imported 
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c15bcbf8c84c> in <module>()
      1 import numpy as np
      2 import math
----> 3 from CoolProp.CoolProp import PropsSI
      4 from __future__ import print_function
      5 import CoolProp.CoolProp as CP

~/anaconda3/lib/python3.6/site-packages/CoolProp/__init__.py in <module>()
     14     quit()
     15 
---> 16 from .CoolProp import AbstractState
     17 from . import CoolProp
     18 from . import HumidAirProp

ImportError: /home/rened/anaconda3/lib/python3.6/site-packages/CoolProp/CoolProp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE
```

only working install with...
conda install -c bryanwweber coolprop

**Comment by ibell** [comment]
What version of OS do you have?  I use this method on *nix all the time.

**Comment by rddaz2013** [comment]
This error was on Ubuntu 16.04.3 LTS 64-Bit. 
other Win7 installation of coolprop over pip works well.

**Comment by ibell** [comment]
I use ubuntu all the time, and don't usually run into problems, but it can
sometimes be tricky.  Have you tried to install libgcc:
https://github.com/usnistgov/ChebTools#prerequisites ?

**Comment by thorade** [comment]
To be absolutely sure you use the correpsonding pip for your python, could you please also try 
`python -m pip ...`
from the Anaconda prompt.

https://docs.python.org/3/installing/#work-with-multiple-versions-of-python-installed-in-parallel

**Comment by ibell** [comment]
And/or you can provide the absolute path to pip executable

**Comment by rddaz2013** [comment]
from Ubuntu 16.04.3 LTS 64-Bit
`pip --version
pip 9.0.1 from /home/rened/anaconda3/lib/python3.6/site-packages (python 3.6)
`

`
python -m pip --version
pip 9.0.1 from /home/rened/anaconda3/lib/python3.6/site-packages (python 3.6)
`

**Comment by rddaz2013** [comment]
from WIN10

```
pip --version
pip 9.0.1 from F:\Anaconda3\lib\site-packages (python 3.6)
```

```
python -m pip --version
pip 9.0.1 from F:\Anaconda3\lib\site-packages (python 3.6)

```

**Comment by thorade** [comment]
That looks both good 👍  
so the error is elsewhere 😞

**Comment by thorade** [comment]
I added this ticket to Milestone 6.2, because the new release will include a Py36 package (and a source release as fallback).

**Comment by henningjp** [comment]
I have the same problem under Python 3.6 on Win10.  Standard pip install only gives me 6.0.0.  It’s like there’s no build wheel for 6.1.0 on Python 3.6....

If I want 6.1.0, I have to build my own from that git release tag.  Grabbing the nightly 6.1.1dev build works fine, though.

**Comment by thorade** [comment]
@henningjp Your error is different: 
There is no py36 package for Coolprop, so py36 tries to install from source. 
But there also is no source package for Coolprop 6.1, only for Coolprop 6.0. 
So py36 tries to install 6.0 and fails.

The real soultion would be to publish a py36 package, either for Coolprop 6.1 or even better for 6.2.
To be safe for the future (e.g. py37 will be released in summer), a source package should be included!!

Until then, the recommended workaround is to use the nightly builds, and that should just work. 
It does work for me, on Windows 10, but the issue described here is that it failed on Ubuntu 16.04.

**Comment by ibell** [comment]
Python 3.6 binary wheels are now being built on all platforms, and should be pip installable as of version 6.2
