### ISSUE TITLE
install fail with python 3.6 in anaconda for win10

### ISSUE THREAD

**Issue by foodish** [CoolProp/CoolProp#1661]
I tried to install coolprop using "pip install coolprop" without success.
$ python --version
Python 3.6.0 :: Anaconda custom (64-bit)
Windows10，64-bit

The related infomation:
>   CoolProp.obj : warning LNK4197: ▒▒▒ָ▒▒▒▒▒▒▒▒PyInit_CoolProp▒▒▒▒ʹ▒õ▒һ▒▒▒淶
      ▒▒▒ڴ▒▒▒▒▒ build\temp.win-amd64-3.6\Release\CoolProp\CoolProp.cp36-win_amd64.lib ▒Ͷ▒▒▒ build\temp.win-amd64-3.6\Release\CoolProp\CoolProp.cp36-win_amd64.exp
    ▒▒▒▒▒▒▒ɴ▒▒▒
    ▒▒▒▒ɴ▒▒▒▒▒▒▒▒
    LINK : fatal error LNK1158: ▒޷▒▒▒▒С▒rc.exe▒▒
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    ----------------------------------------
Command "D:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Lenovo.pc\\AppData\\Local\\Temp\\pip-build-qo35w0og\\coolprop\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Lenovo.pc\AppData\Local\Temp\pip-5z417rw5-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Lenovo.pc\AppData\Local\Temp\pip-build-qo35w0og\coolprop\

**Comment by henningjp** [comment]
Instead, grab the nightly build following the instructions at http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#python. This works for me on 3.6.

**Comment by ibell** [comment]
The compiler has to match on windows - so you actually need 2015, not 2017.
It's very annoying.  At least you don't use python 2.7, for which you need
visual studio 2008.

I'll totally help you get this working, but your better bet might be to use
the pip install from the build server.

**Comment by foodish** [comment]
@ibell 

I will try it with visual studio 2015.

Thank you!

**Comment by thorade** [comment]
related: #1654, #1604 and
https://github.com/CoolProp/CoolProp/issues/1309#issuecomment-334102589

@foodish As stated above, the easiest way for now would be to use the version from the development server as described here:
http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#python

**Comment by foodish** [comment]
@thorade @henningjp @ibell 
Thanks for all of you！ I tried to download and install the 6.1.1 cp36 in this page （http://www.coolprop.dreamhosters.com/binaries/Python/）and installed successly finally.
Now I can `import CoolProp` in my script.
