### ISSUE TITLE
Mixture modeling in python throwing errors

### ISSUE THREAD

**Issue by L4student** [CoolProp/CoolProp#1667]
I was trying to use the mixture modeling in python interface as per the first method described in [this](http://www.coolprop.org/fluid_properties/Mixtures.html) CoolProp documentation, but it throws two different errors on two different runs as follows:

```
import CoolProp.CoolProp as CP

CAS_He = CP.get_fluid_param_string('Helium','CAS')
CAS_Xe = CP.get_fluid_param_string('Xe','CAS')
CP.apply_simple_mixing_rule(CAS_He, CAS_Xe, 'linear')
CP.PropsSI('Dmass','T',300,'P',101325,'Helium[0.5]&Xenon[0.5]')
```

On first running the above code, I get the following error:
```
  File "<ipython-input-1-ca7e8527e1c4>", line 6, in <module>
    CP.PropsSI('Dmass','T',300,'P',101325,'Helium[0.5]&Xenon[0.5]')

  File "CoolProp\CoolProp.pyx", line 335, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:44221)

  File "CoolProp\CoolProp.pyx", line 415, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:44009)

  File "CoolProp\CoolProp.pyx", line 304, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:42223)

ValueError: bad locale name : PropsSI("Dmass","T",300,"P",101325,"Helium[0.5]&Xenon[0.5]")
```

On subsequent runs, without clearing the current session, it throws the following error:
```
  File "<ipython-input-4-ca7e8527e1c4>", line 5, in <module>
    CP.apply_simple_mixing_rule(CAS_He, CAS_Xe, 'linear')

  File "CoolProp\CoolProp.pyx", line 276, in CoolProp.CoolProp.apply_simple_mixing_rule (CoolProp\CoolProp.cpp:41623)

  File "CoolProp\CoolProp.pyx", line 280, in CoolProp.CoolProp.apply_simple_mixing_rule (CoolProp\CoolProp.cpp:41523)

RuntimeError: CAS pair(7440-59-7,7440-63-3) already in binary interaction map; considering enabling configuration key OVERWRITE_BINARY_INTERACTION
```

**Comment by ibell** [comment]
Hmm..  Some questions for you:
1) What language do you use on your computer?  It doesn't seem to have the en_US locale installed, which was my new solution for string parsing.  But that doesn't seem to be a universal solution.  Darn.
2) The second error is caused by missing interaction parameters.  There's nothing that can be done about that in CoolProp currently.

**Comment by L4student** [comment]
> What language do you use on your computer? It doesn't seem to have the en_US locale installed, which was my new solution for string parsing. But that doesn't seem to be a universal solution. Darn.

English. 

> The second error is caused by the fact that the parameters are already there, as the error suggests, you need to set the appropriate configuration flag.

I was trying to replicate the example provided in the CoolProp documentation I shared, which didn't suggest setting any configuration flag. I am sorry, but I didn't change anything.

**Comment by ibell** [comment]
Ok, I just pushed a fix that I think should resolve this - you might need
to wait for a half hour or so for the builds to fire.

**Comment by L4student** [comment]
Thanks. Would I need to install using pip or using dev version you pointed once (the 2nd option in the link you shared previously)?

**Comment by ibell** [comment]
Yes, precisely

**Comment by L4student** [comment]
Thanks, it's working now.

**Comment by L4student** [comment]
@ibell It was working alright, but suddenly I am getting the following error at `CP.CoolProp.apply_simple_mixing_rule(CAS_A, CAS_B, 'linear')`, where `CAS_A`, and `CAS_B` are defined as given in [this](http://www.coolprop.org/fluid_properties/Mixtures.html) document page. I think I am getting this error if I run the same code twice or if the mixture modeling is invoked more than once without closing the python IDE. I searched for this error and I see another issue #1548 that brought up this issue, but I am not sure if that issue is similar to my issue. 
  ```
File "CoolProp/CoolProp.pyx", line 276, in CoolProp.CoolProp.apply_simple_mixing_rule

  File "CoolProp/CoolProp.pyx", line 280, in CoolProp.CoolProp.apply_simple_mixing_rule

RuntimeError: CAS pair(124-38-9,74-82-8) already in binary interaction map; considering enabling configuration key OVERWRITE_BINARY_INTERACTION
```
The above error statement is included in [this](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Helmholtz/MixtureParameters.cpp) code, but it's not easy for me to understand what's happening here. Perhaps I could use some flag to get rid of this error, in which case I am not sure how that flag is given.

I am using mixture modeling at multiple places in a code, so I have defined few functions in the main code where I am computing mixture properties more than once. Running the code gives the above error.

**Comment by ibell** [comment]
You have two options - either only call apply_simple_mixing_rule at the
beginning of your code, near where you do the imports, or set the
OVERWRITE_BINARY_INTERACTION configuration variable to true:
http://www.coolprop.org/coolprop/Configuration.html

**Comment by L4student** [comment]
@ibell Thank you!
