### ISSUE TITLE
Linking without cmake on osx (Undefined symbols for architecture x86_64)

### ISSUE THREAD

**Issue by veeshy** [CoolProp/CoolProp#1670]
I want to link the CoolProp shared lib on OSX to a cpp program that is not built with cmake. I've successfully linked the shared lib on ubuntu but am struggling on osx. I've also successfully built a simple test of CoolProp using cmake and -DCOOLPROP_MY_MAIN=/path/to/my/test.cpp. Now I want to link and compile by hand:

` mpicxx \-o test t.cpp -L../build -lCoolProp -I../include -I../externals/cppformat -Wl,-rpath,../build -ldl`

and I get an error:

> Undefined symbols for architecture x86_64:
>   "CoolProp::PropsSI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
>       _main in t-d845a9.o
> ld: symbol(s) not found for architecture x86_64
> clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)

Any chance anyone knows what I'm missing on OSX? (the same command works in ubuntu 16)

**Comment by veeshy** [comment]
Comments on what math is being implemented in compute value will serve us well but not required for this PR, perhaps open an issue ticket so we can get to that?

**Comment by ibell** [comment]
1) Is this a question of the standard library that your code linked
against?  That is frequently the source of problems on OSX that manifest in
a manner like this.  Can you please provide the complete build log from
your build of the static library?
2) What is the question with regards to the "math"?  Have you had a chance
to look through the documentation at www.coolprop.org?

**Comment by veeshy** [comment]
1) I think my question is, is there anything unique to do on OSX when linking CoolProps shared library? 

> cmake .. -DCOOLPROP_SHARED_LIBRARY=ON > first_cmd.txt

[first_cmd.txt](https://github.com/CoolProp/CoolProp/files/1817942/first_cmd.txt)

> cmake --build . > built_step.txt

[built_step.txt](https://github.com/CoolProp/CoolProp/files/1817943/built_step.txt)

> mpicxx \-o test t.cpp -L../build -lCoolProp -I../include -I../externals/cppformat -Wl,-rpath,../build -ldl

[compile_test.txt](https://github.com/CoolProp/CoolProp/files/1817950/compile_test.txt)

2) The math part was an accidental msg, sorry about that, it's deleted on the issue thread at the least.

**Comment by veeshy** [comment]
Ah, you were spot on with the std lib linking!  -stdlib=libstdc++ solved the issue. Thank you very much!!

**Comment by ibell** [comment]
Also, in general, it is wise to build all the bits and pieces with the same
compiler chain, that removes a lot of these funny issues with standard
libraries, etc.

Good to hear you got it working!
