### ISSUE TITLE
make with libc++ instead of libstdc++ on osx?

### ISSUE THREAD

**Issue by veeshy** [CoolProp/CoolProp#1671]
Is it possible to compile CoolProps with libc++ instead of libstdc++? I tried setting two flags:

> -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -DCMAKE_CXX_FLAGS=-stdlib=libc++

but libstdc++ still is whats linked according to `otool -L libCoolProp.dylib`, 

The flag seems to make it to the ./CMakeFiles/CoolProp.dir/link.txt file, but both libs are on that line. 

> ./CMakeFiles/CoolProp.dir/link.txt:/opt/moose/mpich-3.2/clang-5.0.0/bin/mpicxx -stdlib=libc++ -dynamiclib -Wl,-headerpad_max_install_names  -stdlib=libstdc++  ...

**Comment by ibell** [comment]
Are you building a shared library or static library of CoolProp?  In principle either is possible, but given the choice I *always* go for a static library.  

In any case, the standard library is hardcoded on OSX: https://github.com/CoolProp/CoolProp/blob/master/CMakeLists.txt#L402-L406 .  You could remove those lines as a temporary fix, or we could add a cmake flag to change the behavior. Pull request welcomed!

**Comment by veeshy** [comment]
Awesome, thanks for pointing me to that, works like a charm!
