### ISSUE TITLE
Python Wrapper: "AbstractState object has no attribute 'density'", but PropSI calculate density

### ISSUE THREAD

**Issue by JulianAssmann** [CoolProp/CoolProp#1683]
I'm working with the Python Wrapper for CoolProp and want to get the density and Prandtl number of hydrogen. When I'm working with the low level wrapper and try to get these values, I get the error "'CoolProp.CoolProp.AbstractState' object has no attribute 'density'":

```
HEOS = cp.AbstractState('HEOS', fluid)
HEOS.update(cp.PT_INPUTS, pressure, temperature)
density = HEOS.density()
prandtl = HEOS.prandtl()
```

but when I'm doing the same thing with PropSI it works perfectly:

```
density = cp.PropsSI('D', 'P', pressure, 'T', temperature, fluid)
prandtl = cp.PropsSI('PRANDTL', 'P', pressure, 'T', temperature, fluid)
```

It's the same for HEOS and REFPROP (9.1)

I'm using CoolProp version 6.1.0

**Comment by jowr** [comment]
You can find the available functions here: https://github.com/CoolProp/CoolProp/blob/master/wrappers/Python/CoolProp/AbstractState.pxd#L100

For your case, it would be:
```Python
density = HEOS.rhomass()
prandtl = HEOS.Prandtl()
```
