### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#1685]
This is related to #894 
What license is that? Seems to be the MIT license!?
If it is any of the OSI certified licenses, then I would recommend reformatting (or: deleting and recreating) the file such that github automatically recognizes the license and displays it in the repo overview.

https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/
https://blog.github.com/2017-11-03-search-repositories-by-license/
https://opensource.org/licenses
https://choosealicense.com/appendix/

**Comment by henningjp** [comment]
This same LICENSE file is detected on the CoolProp/IF97 repository.  The only difference is a slight modification on the first line (Copyright notice) that doesn't quite fit the format.  That may be all that needs to be modified.

**Comment by thorade** [comment]
Maybe the checker tool has been updated?
PR #1686 changes the file to a form that is recognized,
the easiest way is to use the web interface to delete and re-add the file, 
using the github template for the license text.

**Comment by thorade** [comment]
The next commit to the master should trigger the detection script.

**Comment by henningjp** [comment]
Push made.  LICENSE still not recognized.  Time delay?  Is the LICENES_CLA.txt interfering with the detection of LICENSE?  IF97 doesn't have a CLA and the LICENSE (old version) is detected just fine.  Grabbing at straws.  I can't find any issues on Github to this effect.

**Comment by thorade** [comment]
@jowr Is the LICENSE_CLA.txt still necessary or can it be deleted? 
There is the CLA Assistant now
https://cla-assistant.io/

**Comment by henningjp** [comment]
Can we delete it temporarily and see if that's what's causing the issue?

**Comment by thorade** [comment]
I forked the repo and deleted it and then it worked.

Jeff Henning <notifications@github.com> schrieb am Di., 17. Apr. 2018,
16:35:

**Comment by jowr** [comment]
Go ahead and remove it. I think cla-assistant uses this gist https://gist.github.com/2e853c95357d39c5479a4e75b549a5dc
