### ISSUE TITLE
PropSI function with vector inputs

### ISSUE THREAD

**Issue by jamarav** [CoolProp/CoolProp#1689]
Hi everybody!

I have the following question. I am implementing in R a small code for analysis of compressors in refrigeration.
The question is: Is it possible to use a Coolprop function for calculating properties working with vectors? 
I need to calculate the properties for a large number of points and the calculation time is excessive if I calculate point by point. An example of what I need would be the following:

vector_Pressure = PropsSI(Output = 'P', Name1 = 'T', Prop1 = c(275.5, 285.5), Name2 = 'Q', Prop2 = c(1, 1), FluidName = 'R410A')

Thanks in advance

**Comment by jamarav** [comment]
Thanks you very much ibell. I'm not familiar with the phayton wrapper. Is this option available with PropsSI function? Could you give me an example to understand the use?

Thanks you in advance

**Comment by ibell** [comment]
Please check out the docs at www.coolprop.org.  All the examples there are
in Python.

**Comment by thorade** [comment]
@jamarav Here is an example of vectorized PropsSI in Python,
check the line in the "get the values" block:


```python
# load some bits and pieces
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

import CoolProp as CP
from CoolProp.CoolProp import PropsSI

# Check: CoolProp version
print(CP.__version__)
print(CP.__gitrevision__)

# Constants
eps = 1e-9
kilo = 1e3
Mega = 1e6
golden = (1 + 5 ** 0.5) / 2
nPoints = 1000
width = 12.5

# Set FluidName
FluidName = 'Propane'

# Triple and critical data
T_crt = PropsSI('TCRIT',FluidName)
T_trp = PropsSI('TTRIPLE',FluidName)
p_crt = PropsSI('PCRIT',FluidName)
p_trp = PropsSI('PTRIPLE',FluidName)

# Get the values
T_sat = np.linspace(T_trp, T_crt, num=nPoints)
p_sat = CP.CoolProp.PropsSI('P','T',T_sat,'Q',0,FluidName)

# Do the plotting
plt.figure(figsize=(width,width/golden))
plt.plot(T_sat, p_sat, color='blue')
#plt.yscale('log')
plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
plt.grid(b=True, linestyle=':')
plt.minorticks_on()
plt.xlabel('Temperature in K')
plt.ylabel('Pressure in Pa')
plt.show()
```

**Comment by thorade** [comment]
Once your problem is solved, you should close this issue. You can still comment and/or reopen.

If you have a nice little example for calling python from R with vectorized PropsSI, you can also post it here to help future users!

**Comment by jamarav** [comment]
Good Morning. The final solution that I have used is to make a small script in python to execute the PropsSI function thus allowing the introduction of vectors as inputs and outputs. In my R sript I used the reticulate library for the communication of R with python. The code would be the following:

python script:

`import CoolProp.CoolProp as CP
def myPropsSI(outputs, input1name, input1values, input2name, input2values, fluid):
    res = CP.PropsSI(outputs, input1name, input1values, input2name, input2values, fluid)
    return (res)`

R script:

`  library(reticulate)
  py_run_file('sources/PropsSI_Python.py')
  Pevap<-py$myPropsSI(outputs = 'P', input1name = 'T', input1values = vector_Tevap_r, input2name = 'Q', input2values = 1, fluid = Fluid)`

The data structure in the R scrip is the same that use R. The library reticulate does the data structure change R/python (inputs function myPropsSI) and python/R (outputs function myPropsSI) automatically.

This is a valid solution for using PropsSI in R with vector inputs and outputs.

**Comment by ibell** [comment]
Nice solution! Would you like to add that to the docs for R: https://github.com/CoolProp/CoolProp/edit/master/Web/coolprop/wrappers/R/index.rst ?  Would be very useful for other users!  In python, you might also want to consider direct argument forwarding, a la:
```python
import CoolProp.CoolProp as CP
def myPropsSI(*args):
    return CP.PropsSI(*args)
```
But actually I'm not sure if you need any of that, because I think you might be able to do:
``` python
from CoolProp.CoolProp import PropsSI
```

**Comment by ibell** [comment]
Or maybe you want to forward keyword arguments:
```python
import CoolProp.CoolProp as CP
def myPropsSI(**kwargs):
    return CP.PropsSI(**kwargs)
```

**Comment by ajw36** [comment]
Is anybody able to advise on whether it's possible to make use of the low-level AbstractState class in python with a vector of inputs (i.e., similar to the PropsSI example from @thorade above)? If so, please could you give an example. Many thanks.

**Comment by ibell** [comment]
That is correct, it is not possible to use the low-level interface to do
this.  I've long thought about it, but never decided on a clean
interface that was powerful enough and simple enough.

>

**Comment by thorade** [comment]
@ajw36 You could maybe try to use NumPy vectorize:
https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html
to build a vectorized wrapper around it.

**Comment by goldkronsohn** [comment]
@ibell is there an update about the possibility to use NumPy-vectors in low-level interface?

**Comment by ibell** [comment]
You definitely can in python or anything that can call python

**Comment by GLardner** [comment]
I've been shown how to do it on the Smath forum, by vectorizing the CoolProp functions. 

I'm getting old; I should have figured that out/remembered that myself.
