### ISSUE TITLE
Got Negative Prandtl

### ISSUE THREAD

**Issue by jfeng08** [CoolProp/CoolProp#1692]
We have CoolProp installed on CentOS 7.x 64-bit.

We got some strange results with fluid R744:

1. CO2->update(PT_INPUTS, 7341050, 303.914325231)
2. densityMass = CO2->rhomass() = 394.811829759
3. CO2->update(DmassT_INPUTS, 394.811829759, 303.914325231)
4. Prandtl = CO2->Prandtl() = -33836.6320842

If we run the exactly same conditions in REFPROP for VB, the Prandtl = 46.6378561823931

Please advise.

**Comment by ibell** [comment]
Too close to saturation state with PT inputs

```python
import CoolProp.CoolProp as CP

print(CP.get_global_param_string('version'))

print('High level interface ok /w TD inputs!:')
print(CP.PropsSI('Prandtl','T',303.914325231,'Dmass',394.811829759,'CO2'))

print('High level interface not ok /w PT inputs!:')
print(CP.PropsSI('Prandtl','T',303.914325231,'P',7341050,'CO2'))
```
yields
```
6.1.1dev
High level interface ok /w TD inputs!:
49.44659938848485
High level interface not ok /w PT inputs!:
Traceback (most recent call last):
  File "/Users/ian/Desktop/junk2.py", line 9, in <module>
    print(CP.PropsSI('Prandtl','T',303.914325231,'P',7341050,'CO2'))
  File "CoolProp/CoolProp.pyx", line 335, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 415, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 304, in CoolProp.CoolProp.__Props_err2
ValueError: Saturation pressure [7.34105e+06 Pa] corresponding to T [303.914 K] is within 1e-4 % of given p [7.34105e+06 Pa] : PropsSI("Prandtl","T",303.9143252,"P",7341050,"CO2")
```

**Comment by ibell** [comment]
Basically, you cannot define a PT state point when you are AT saturation, which is why you get this error.  If you were to specify the phase, it would work ok:

```python
import CoolProp.CoolProp as CP

print(CP.get_global_param_string('version'))

CO2 = CP.AbstractState('HEOS','CO2')
CO2.specify_phase(CP.iphase_gas)
CO2.update(CP.PT_INPUTS, 7341050, 303.914325231)
print(CO2.rhomass())
CO2.update(CP.DmassT_INPUTS, CO2.rhomass(), 303.914325231)
print(CO2.Prandtl())
```
yielding
```
6.1.1dev
394.8118307240104
49.446602808111386
```

**Comment by jfeng08** [comment]
Is there a way in CoolProp to determine the phase of CO2 bases on pressure and temperature?

**Comment by henningjp** [comment]
From the high level interface:
CP.PhaseSI('T',303,'P',7341050,'CO2')

Note, however, that if it returns a blank string '' (v6.1.0) or 'unknown' (v6.1.1dev), then your T/P point is on the saturation curve and phase can't be determined (it's either saturated liquid, two phase, or saturated vapor).

**Comment by jfeng08** [comment]
Yes, but the low level interface phase() does not work.

**Comment by ibell** [comment]
What output do you get from phase? You should get an integer corresponding to the enumeration of the phase indices

**Comment by jfeng08** [comment]
Here is what I got:
Fatal error: Uncaught exception 'Exception' with message 'This backend does not implement calc_phase function' in .../CoolProp.php:1293
CoolProp.php(1293): abstractstate_phase(Resource id #28)

**Comment by ibell** [comment]
Yes, that is because REFPROP has no notion of phase like CoolProp does.
You would have to apply the logic of
http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function to
figure out the phase.
