### ISSUE TITLE
Review and Update Declare statements

### ISSUE THREAD

**Issue by fisherboy101** [CoolProp/CoolProp#1694]
1. Downloaded the .zip from: https://sourceforge.net/projects/coolprop/files/CoolProp/6.1.0/shared_library/Windows/64bit/

2. Extracted to the same folder location (currently in 'Downloads' - just troubleshooting at the moment)

3. Excel -> Add-Ins -> Selected Add-In from the extracted folder: C:\Users\****my_PC*****\Downloads\CoolProp_sources\CoolProp.sources\wrappers\Excel

4. I get the error below, within a VBA popup, upon hitting 'ok' after Add-In location is selected:

"
Compile error:

The code in this project must be updated for use on a64-bit systems.
Please review and update Declare statements and then mark them with the PtrSafe attribute.
"

-------------------------------------------------------------
Computer:
Windows 10
64-bit
Running Excel 2016 
-------------------------------------------------------------

I'm really not sure what's going on here.
Would any one be able to offer a quick flow path to get this working?

Thanks in advance,
Stephen

<img width="341" alt="ptrsafe" src="https://user-images.githubusercontent.com/19900591/39963192-c54814fc-5619-11e8-9c13-9f1af2022304.PNG">
<img width="467" alt="download" src="https://user-images.githubusercontent.com/19900591/39963193-c576d4d6-5619-11e8-8446-60605e05a3d8.PNG">

**Comment by ibell** [comment]
Try the installer:
http://www.coolprop.org/dev/coolprop/wrappers/Installers/index.html#installers
. That should fix things I hope.

**Comment by fisherboy101** [comment]
You are a life saver - thanks a ton!

**Comment by ibell** [comment]
Actually, the hope was that someone would take that snippet and put it into
the docs, which is why I left this issue open...

**Comment by ibell** [comment]
Sorry, my bad, I was thinking about a different issue.  This one can indeed
be closed.
