### ISSUE TITLE
InChI key for 1233zd(E)

### ISSUE THREAD

**Issue by ianhbell** [CoolProp/CoolProp#1696]
@wandadars - I think the InChI for R-1233zd(E) should be "InChI=1S/C3H2ClF3/c4-2-1-3(5,6)7/h1-2H/b2-1+" instead of "InChI=1S/C3H2ClF3/c4-2-1-3(5,6)7/h1-2H".  Otherwise all the InChI keys match those in TRC's TDE database.

Wikipedia agrees: https://en.wikipedia.org/wiki/1-Chloro-3,3,3-trifluoropropene

Thanks for your work updating the keys!

**Comment by wandadars** [comment]
Here's a reference for R-1233zd(E): https://www.agas.co.uk/products-services/refrigerants/products/low-gwp-alternatives/r1233zd-e/

The SDS link(on the left side of the page) opens up the following data sheet.
https://jr.chemwatch.net/cwws/MaterialService.svc/GetMsdsByExternalUrl?cwn=58-9708&ui=304607&di=18480&ts=636626078756976144&v=&hc=C18EA2DE9ADF2C78709B08F3E023AA38&cn=139&ln=340700&msdsformat=1

This page lists the CAS number as: 102687-65-0

**Comment by Myoldmopar** [comment]
I just have to say, I'd vote this issue as the most obfuscated issue title on Github if there was such a competition.

**Comment by ibell** [comment]
I could add the R- to the fluid name if you want to make it even more
obfuscated :)

**Comment by Myoldmopar** [comment]
Haha I say not necessary; I like the random numbers showing up!  Also, sorry to sidetrack this conversation for my own giggles...

**Comment by ibell** [comment]
@wandadars The confusion is totally understandable.  It is confusing because you have an identifier for the mixture of the stereoisomers R-1233zd(E) and R-1233zd(Z), and individual identifiers for each compound by itself.  Therefore, three CAS #, and three InChI.  

The wikipedia page (https://en.wikipedia.org/wiki/1-Chloro-3,3,3-trifluoropropene) gives three identifiers as well (as it should), but the one that we want in particular is that of the (E) isomer.

Hope that clears things up a little bit.

**Comment by wandadars** [comment]
Just to make sure I make the correct change here. The fluid in the database is R1233zd(E), so we want the InChi keys for the (E) isomer.

Mixture of (E) and (Z): CAS 2730-43-0
https://pubchem.ncbi.nlm.nih.gov/compound/5709018#section=Names-and-Identifiers
InChI=1S/C3H2ClF3/c4-2-1-3(5,6)7/h1-2H/b2-1+

(Z) isomer: CAS 99728-16-2 
https://pubchem.ncbi.nlm.nih.gov/compound/11658298#section=Names-and-Identifiers
InChI=1S/C3H2ClF3/c4-2-1-3(5,6)7/h1-2H/b2-1-

(E) isomer: CAS 102687-65-0 
https://pubchem.ncbi.nlm.nih.gov/compound/2779022#section=Names-and-Identifiers
InChI=1S/C3H2ClF3/c4-2-1-3(5,6)7/h1-2H

Contents of R1233zd(E).json:
"INCHI_STRING": "InChI=1S/C3H2ClF3/c4-2-1-3(5,6)7/h1-2H"

It appears that the entry for the (E) isomer on pubchem using the CAS number from that wikipedia page, matches what we have in the JSON file.

**Comment by wandadars** [comment]
@ianhbell Bumping this to see if we can resolve this issue.

**Comment by ibell** [comment]
I think I was wrong, and it seems like TDE is incorrect.
