### ISSUE TITLE
Pip Install problem with Ubuntu 18.04 and Python 3.6.3

### ISSUE THREAD

**Issue by Myoldmopar** [CoolProp/CoolProp#1699]
### Description

Main Storyline:

> Our story opens on a developer (EL) trying to engage in development on an existing open source project that utilizes CoolProp.  This development team uses Mac with Python 3, and Travis (running Ubuntu 14.04).

Developer enters stage left:

> Let me just sit down at my Ubuntu 18.04 machine and start working on this new project.  I will:
 - [X] clone the repository,
 - [X] create a Python virtual environment, from 3.6.3 (the latest Python), and install project dependencies with pip

A small gasp from the developer as an error message appears from the pip installation step...

> What?  A compiler error from the C code behind CoolProp?  Lemme check some things...
 - It's downloading CoolProp 6.0, which isn't the latest, but still pretty new.
 - PyPi shows 6.1.0 is available though, that's weird.  We'll I'll keep looking
 
A new terminal window appears as the developer's heart rate increases.

> Let me just try the same steps but from a Python 2.7 virtual environment....it worked!  The unit tests for the program don't pass, but the pip installation works, I wonder why!

Alas, the development project requires Python 3, so reverting to 2.7 here isn't an option for this developer.  Time to keep looking at options:

> Getting the 6.0 version from PyPi is failing, so I'll change the requirements file to download from the repository directly at tag 6.1.0 to see if the problem is fixed in 6.1.0:
 - FAIL!?  Couldn't do a full recursive git clone because externals/eigen removed a SHA that is required at the CoolProp 6.1.0 tag??

> Let's try getting the daily repo state in the requirements file:
 - FAIL!?  Couldn't execute setup.py egg_info because the setup.py file is missing?
 
> OK let's get down to business.  Why can't I get CoolProp 6.1.0 from PyPi.  Let me look close at the versions available on PyPi.  The files available at:
 https://pypi.org/project/CoolProp/#files

> show Python 2.7 and *gasp* Python 3.5 support for version 6.1.0.  

The developer wonders for half a second before trying the final working step

> Let me pyenv version 3.5, and try to pip install from 3.5.4.  

IT WORKED

> Now, I can work on this development project on my Ubuntu 18.04 machine, with Python 3.5.4, and successfully run tests and develop code.  Whew.

*Bows*

OK, so in summary, I can't install CoolProp through Pip on my Ubuntu 18.04 machine when I use the latest Python (3.6.3).  Installing on older versions of Ubuntu works, installing on other OS's works, and using Python 3.5 works.
Not sure if you can just rebuild your packages to say that 3.6 is supported with your wheels, then when I pip install, it should match up and give me CoolProp 6.1.0 binaries and be good to go.

Let me know if I can be of any more assistance.  Or if you'd like to read the full screenplay.

### Steps to Reproduce

- Install Ubuntu 18.04
- Use latest Python 3.6.3
- Try to pip install coolprop

**Expected behavior:** CoolProp 6.1.0 is installed successfully through normal Pip operation

**Actual behavior:** Pip provides CoolProp 6.0.0, and then install fails to build.

### Versions

**CoolProp Version:** Trying to use 6.1.0
**Operating System and Version:** Ubuntu 18.04
**Access Method:** Python

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
Hehe ! I like your message, sorry for the frustration though.  All your
problems are fixable, thankfully.

1) You should try the second pip install command here:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation
.  Works perfectly in python 3.6.x on all platforms.  We haven't yet
released version 6.2, which will make all these annoying issues go away
because the right wheels will be on PYPI.
2) For the git stuff, you'll have to do a full clean clone of your
superproject as well as CoolProp because the remote location changed for
Eigen.  That should fix the Eigen submodule issue.
3) You should also have been able to install from source once you got your
Eigen issue resolved by doing python setup.py install in wrappers/Python

Please post back if you get all that working.  I use Ubuntu 18.04 and
python 3.6.x and I assure you it *can* work perfectly.

**Comment by thorade** [comment]
related: #1654, #1604 and https://github.com/CoolProp/CoolProp/issues/1309#issuecomment-334102589

**Comment by ibell** [comment]
Bump - any update?

**Comment by jowr** [comment]
Can this be closed? I guess it will be fixed with the next release (v6.2 - #1604 ) , wouldn't it?

**Comment by thorade** [comment]
Yes, and also there is no point in keeping it open if the original person does not respond anymore.
Closing now, OP can still reopen, anyone can still comment or open new issues.
