### ISSUE TITLE
Inconsistency in incompressible backend when getting fluid name()

### ISSUE THREAD

**Issue by romarro** [CoolProp/CoolProp#1707]
### Description

For the incompressible backend when used with low level API AbstractState the __name()__ method do not returns the name of the fluid (or mixture), it returns the description of the fluid as defined in the table http://www.coolprop.org/fluid_properties/Incompressibles.html

### Steps to Reproduce

**Expected behavior:** 
`
import CoolProp as fld

water = fld.AbstractState("INCOMP","Water")
water.name() -> 'Water'

aeg = fld.AbstractState("INCOMP", "AEG")
aeg.name() -> 'AEG'
`

**Actual behavior:** 
`
water = fld.AbstractState("INCOMP","Water")
water.name() -> 'Fit of EOS from 1 bar to 100 bar'

aeg = fld.AbstractState("INCOMP", "AEG")
aeg.name() ->'ASHRAE, Ethylene Glycol'
`
### Versions

**CoolProp Version:** 6.1dev0  
**Operating System and Version:** Windows  
**Access Method:** Python3.6

### Additional Information

As a side note, maybe a description method should be userfull

**Comment by ibell** [comment]
Agreed, that's definitely a bug.  @jowr Any chance you could look into this one?
