### ISSUE TITLE
calc_phase missing for REFPROP backend.

### ISSUE THREAD

**Issue by techdragon** [CoolProp/CoolProp#1708]
### Description

The REFPROP backend is missing the calc_phase routines to handle returning 'nice' phase labels.

### Steps to Reproduce

1. Try to invoke PhaseSI with a REFPROP based chemical.

**Expected behavior:** Phase is printed like it would be for a HEOS based chemical.

**Actual behavior:** `This backend does not implement calc_phase function : PropsSI("Phase","P",101325,"T",473.15,"REFPROP::Water")`

### Versions

**CoolProp Version:** 6.0.0
**Operating System and Version:** macOS Sierra
**Access Method:** Python Wrapper 

### Additional Information

```
ValueError                                
Traceback (most recent call last)
<ipython-input-7-89a39232f1af> in <module>()
----> 1 PHASE_TABLE[PropsSI("Phase", "P", 101325, "T", 473.15, "REFPROP::Water")]
CoolProp/CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:36859)()
CoolProp/CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:36644)()
CoolProp/CoolProp.pyx in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:34849)()
ValueError: This backend does not implement calc_phase function : PropsSI("Phase","P",101325,"T",473.15,"REFPROP::Water")
```

**Comment by ibell** [comment]
Older versions of REFPROP do not have the notion of a pretty-printing phase
like coolprop does, so I'm not sure what we can do here.  REFPROP version
10 does though, so we could implement it for version 10 and up

**Comment by techdragon** [comment]
Implementing it for version 10 and up, and producing some form of NotImplemented error seems perfectly fine to me.

**Comment by ibell** [comment]
Can somebody please mark this issue as feature request?

**Comment by henningjp** [comment]
@ibell  This is actually quite easy.  ``PhaseSI()`` is backend independent, it just calls ``PropsSI("Phase",.....)`` using the requested backend and then queries `` _phase`` to create the "pretty printing" phase string.  

I've added code to REFPROPMixtureBackend.update() to set the ``_phase`` variable based on what REFPROP returns as quality (which is how REFPROP determines phase).  All the backends just return ``_phase`` from ``calc_phase()``, so I've implemented same for the REFPROP backend.  Then PhaseSI() works for REFPROP fluids.  It's all good.

The difficulty is in CoolProp's definition of phases vs. REFPROP's.  CoolProp considers the saturation curves, which are literally either liquid (Q=0) or vapor/gas (Q=1) to be 'two phase'.  REFPROP has separate definitions of 'saturated liquid' and 'saturated vapor'.  So....

1. Translate values of Q=1/Q=0 to ``iphase_twophase``?  or....
2. Create new phases enumerations for ``iphase_saturated_liquid`` and ``iphase_saturated_vapor`` to be used only for returning ``_phase`` values from REFPROP? 

Also, REFPROP doesn't have a "Q" value defining exactly at the critical point (CoolProp has ``iphase_critical_point``), but this may not be necessary as REFPROP just returns "supercritical" there.

I defer to the BDFL.  :smiley:

**Comment by ibell** [comment]
For pure fluids, this can indeed be pretty easy to implement, I would propose to determine whether the state is supercritical based on temperature first, then determine if the density is above or below the critical density.  

Those are the easy points.  I would be fine ignoring the possibility of being AT the critical point, and focus on whether you are saturated (Q==1 or Q==0) for the subcritical points.  A PR implementing this would be welcome!
