### ISSUE TITLE
static library coolprop cygwin

### ISSUE THREAD

**Issue by Scarface03** [CoolProp/CoolProp#1711]
When I try to build static library of Coolprop for Windows in cygwin for fortran as explained here: http://www.coolprop.org/dev/coolprop/wrappers/FORTRAN/index.html 
cygwin writes: "cmake ../.. -G "MinGW Makefiles" -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_EXTERNC_LIBRARY=ON -DCMAKE_VERBOSE_MAKEFILE=ON
CMake Error: Could not create named generator MinGW Makefiles

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  KDevelop3                    = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files."

How can I solve the problem?

**Comment by ibell** [comment]
Hello!  To build the static library, you need the MinGW compiler stack, not
cygwin.  They are similar, but different animals.  With MinGW it should
just work.  Did you see the instructions about MinGW here:
http://www.coolprop.org/coolprop/wrappers/FORTRAN/index.html#compilers ?

**Comment by ibell** [comment]
Well, I suppose you could use cygwin, but on windows, we only test with mingw.  For now, closing due to lack of input.  Feel free to re-open.
