### ISSUE TITLE
PropSI function with vector inputs in the specification of the thermodynamic variables states

### ISSUE THREAD

**Issue by jamarav** [CoolProp/CoolProp#1712]
Hi everybody!

A few months ago I open a new issue about the use of PropsSI function with vector inputs in the R wrapper #1689. The issue was closed and now my R script works correctly.
Now I want to improve the script with the following change.
I need to introduce the variables states as a vector too. My script calculate the vapor compression cycle and I have some points with SH=0 K and others different from 0 K.
For instance, I would need the following instruction:
```
vector_input2name<-c(Q, Q, P, Q, P, P, Q)
py$myPropsSI(outputs = 'H, D', input1name = 'T', input1values = vector_Tevap_r, input2name = vector_input2name, input2values = input2values, fluid = Fluid)
```

The code above is based on the communication R/Python (#1689)

The main objective is to use in the same instruction the calculation of the points in saturated conditions (state variables: T, Q=1) an the others with SH different from 0K (state variables: T, P)

I run the code above and I have the following errors:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: expected bytes, list found

> Detailed traceback: 
>   File "<string>", line 4, in myPropsSI
>   File "CoolProp\CoolProp.pyx", line 335, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:47040)
>   File "CoolProp\CoolProp.pyx", line 404, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:46718)
>   File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string (CoolProp\CoolProp.cpp:56745)
```
Any solution?

Thanks in advance

**Comment by ibell** [comment]
Sorry, but the input variables are not allowed to be vectors.  You'll have to loop over them, which should hopefully not incur too much of a speed penalty.  Certainly the speed of doing saturation property calls will be much slower than the calling overhead to PropsSI.
