### ISSUE TITLE
Use RefProp via CoolProp High-Level-Interface by linking RefProp statically

### ISSUE THREAD

**Issue by DGSEM** [CoolProp/CoolProp#1713]
Is there an easy way to use Refprop via Coolprop High-Level-Interface by linking RefProp statically?

Regards

**Comment by ibell** [comment]
I'm afraid the answer is definitely not.  REFPROP is a shared library that
must be compiled as such.  With some work, I am sure you could statically
link REFPROP into your application, but that doesn't avoid the file loading
from files issues required for REFPROP.  At that point, I don't really see
the benefit.  That's one of the benefits of CoolProp - the whole library
can be statically linked, with no access to the filesystem.
