### ISSUE TITLE
Could not load properties from Refprop in EES

### ISSUE THREAD

**Issue by chienfm** [CoolProp/CoolProp#1715]
### Description
Hello, 

I have installed the coolprop v6.1 and EES 9.2. When querying the properties of refrigerant in coolprop, the function works well. But when querying the properties from Refprop (v9.0), EES shows error
>Initialize failed for backend: "REFPROP", fluid: "WATER" fractions "[ 1.0000000000 ]"; error: Could not load these fluids: WATER : PropsSI("D","P",101325,"T",300,"REFPROP::WATER").

However, the wrapper is working well in python when querying the properties from REFPROP. Could you please give me any recommendation?

Thank you!
Nguyen.

### Steps to Reproduce

1. Install REFPROP, add Path.
2. Install EES
3. Install Coolprop v6.1.0 wrapper for EES.
4. In EES, the command `D = PropsSI('D','P',101325,'T',300,'Water')` is fine. However, the command `D = PropsSI('D','P',101325,'T',300,'REFPROP::Water')` gets error as I demonstrated above.
5. Install wrapper for python using pip. In python, the above command works fine.

### Versions

**CoolProp Version:** 6.1.0  
**Operating System and Version:** Windows 10  
**Access Method:** EES wrapper.

**Comment by ibell** [comment]
Did you read the instructions page for REFPROP completely:
http://www.coolprop.org/coolprop/REFPROP.html ?  For REFPROP 9.1, you need
to copy the folder from c:\Program Files (x86)\REFPROP to c:\Program
Files\REFPROP.  There was a bug in REFPROP that it didn't also look in the
c:\Program Files (x86)\REFPROP folder for fluid files

**Comment by chienfm** [comment]
Dear Dr. Ibell,

Thank you so much for your answers and I'm sorry for my late reply. Now I can run the sample file for EES and returns the value from Refprop. However, the function does not work completely. This PropSI function call Tcrit works fine but the other such as:
`T_crit_refprop = PropsSI('Tcrit','P',100,'Q',0,'REFPROP::R410A')` returns value
 but
`T_refprop = PropsSI('T','P',100000,'Q',0,'REFPROP::R410A')` return error "An unresolvable error was encountered while trying to access COOLPROP_EES.    Check to ensure that the inputs to this external routine are correct."

Could you give me any recommendation?

Thank you so much!

Regards,
Nguyen Chien.

**Comment by ibell** [comment]
How about T_refprop = PropsSI('T','P',101325,'Q',0,'REFPROP::WATER') ?
That's always my first test.  What do you get with that call if you use
CoolProp instead? Does it work?

**Comment by chienfm** [comment]
Thank you for your reply.

The function `T_refprop = PropsSI('T','P',101325,'Q',0,'REFPROP::WATER') ` also returns the same error "An unresolvable error was encountered while trying to access COOLPROP_EES. Check to ensure that the inputs to this external routine are correct." 

But `T_refprop = PropsSI('Tcrit','P',101325,'Q',0,'REFPROP::WATER')` returns value (647.1).

**Comment by chienfm** [comment]
Finally, the wrapper is now working with CoolProp version 5.08.

**Comment by ibell** [comment]
Weird.  That makes no sense since the EES code hasn't been modified in like
forever

**Comment by chienfm** [comment]
I have no idea. Also, for using CoolProp.Lib for EES versions older than 9.478, I slightly modified some lines as in attachment.

Thank you so much!

[CoolPropLib _modified.txt](https://github.com/CoolProp/CoolProp/files/2434728/CoolPropLib._modified.txt)
