### ISSUE TITLE
Enthalpy out of range for IF97 in Region 5

### ISSUE THREAD

**Issue by sodynamic** [CoolProp/CoolProp#1716]
### Description

The following code tries to caculate temperature with pressure and enthalpy as inputs.  It seems that if the steam is in Region 5, which means the temperature is higher than 1073.15 K, an "Enthalpy out of range" error will pop up.  Is this a limitation for current developing version?  
### Steps to Reproduce
```
from CoolProp.CoolProp import PropsSI

P_init = 1000000
T_init = 1100
H_init = PropsSI("H","P",P_init,"T",T_init,"IF97::Water")
print("H_init is", H_init)
T_final = PropsSI("T","P",P_init,"H",H_init,"IF97::Water")
print("T_final is", T_final)
S_final = PropsSI("S","P",P_init,"H",H_init,"IF97::Water")
print("S_final is", S_final)
```

**Expected behavior:** [What you expect to happen]
No error

**Actual behavior:** [What actually happens]
 "Enthalpy out of range" error will pop up when T_init is larger than 1073.15.

### Versions
**CoolProp Version:** [CoolProp version you are using]  
6.1.1.dev0
**Operating System and Version:** [OS you are running CoolProp on]  
Windows 7, x64
**Access Method:** [How you are accessing CoolProp (i.e. Python, other wrapper, direct C++ calls, etc.)]  
pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp

**Comment by henningjp** [comment]
The first function call works and calculates H_init properly.  The second function call does not  and returns your error.

It's a limitation of IAPWS-IF97, which fits the Gibbs free energy in Region 5 (above 1073.15K and below 50 MPA) as a function of temperature and pressure only.  The reverse functions of (p,h) and (p,s) do not yet exist, as they do in regions 1, 2, and 3.  So the reverse functions are limited to T < 1073.15K.  As a workaround you can write a Newton-Raphson routine to solve h(T,p) backwards for T(p,h), but this defeats the purpose of the fast IF97 functions.  Sorry.

**Comment by sodynamic** [comment]
@henningjp , thank you for your reply! Actually, I am using Newton_Raphson routine to solve the problem. It is a pity for lack of reverse function in region 5. However, it is still a great tool for my current study. I really appreciate your guys' work!
