### ISSUE TITLE
Coolprop cannot work on local JS

### ISSUE THREAD

**Issue by BingHung** [CoolProp/CoolProp#1717]
I followed the descriptions from the website http://www.coolprop.org/coolprop/wrappers/Javascript/index.html#javascript
and download three files from the links below
https://sourceforge.net/projects/coolprop/files/CoolProp/nightly/Javascript/
I run html file on localhost (chrome browser), when i click calculate and nothing happened !
can someone teach me how to deal with that. thanks 

note : it works on official example links but not mine

**Comment by ibell** [comment]
You need to run a minimal webserver.  If you have access to Python,
something like this would work:

python -m SimpleHTTPServer 8000
