### ISSUE TITLE
is there an enum or list for all fluidname for propsı fluidname property

### ISSUE THREAD

**Issue by orhantopdag** [CoolProp/CoolProp#1718]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**CoolProp Version:** [CoolProp version you are using]  
**Operating System and Version:** [OS you are running CoolProp on]  
**Access Method:** [How you are accessing CoolProp (i.e. Python, other wrapper, direct C++ calls, etc.)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
I responded to the mailing list issue, I think that resolves this question.
