### ISSUE TITLE
C:\Microsoft.Cpp.Default.props file missing

### ISSUE THREAD

**Issue by ChristianOL** [CoolProp/CoolProp#1722]
### Description

I am trying to create a static library of CoolProp to use in a C++ program/compiler like Dev C++. When i use the cmake command I get an error about a missing file to create the project: "C:\Microsoft.Cpp.Default.props"

Project "C:\Cloud\OneDrive\Test\build\CMakeFiles\3.12.0\VCTargetsPath.vcxproj" en nodo 1 (destinos predeterminados).
    C:\Cloud\OneDrive\Test\build\CMakeFiles\3.12.0\VCTargetsPath.vcxproj(14,2): error MSB4019: No se encuentra el proyecto importado "C:\Microsoft.Cpp.Default.props". Asegúrese de que la ruta de acceso de la declaración <Import> es correcta y de que el archivo se encuentra en el disco.

### Steps to Reproduce

1. Open cmd change to build folder and run "cmake"
2. It starts to compile and several errors appear, this being the first. 

**CoolProp Version:** current files at https://github.com/CoolProp/CoolProp
**Operating System and Version:** Windows 10 Home 
**Access Method:** cmd to create library 

### Additional Information
I guess it has to do with my software versions, i looked for similar files in my pc "Microsoft.Cpp.Default.props" and found nothing. 
I looked for directories of MSBuild at registry and there is nothing related. 

Any suggestions? or workaround? thanks.

**Comment by ChristianOL** [comment]
Hello,
It corrected after installing Visual Studio Community 2017. I was following this steps to install CoolProp of the webpage: http://www.coolprop.org/coolprop/wrappers/StaticLibrary/index.html#static-library

# Check out the sources for CoolProp
git clone https://github.com/CoolProp/CoolProp --recursive
# Move into the folder you just created
cd CoolProp
# Make a build folder
mkdir -p build && cd build
# Build the makefile using CMake
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON
# Make the static library
cmake --build . 

It worked fine up to the "cmake .. -DCOOLPROP_STATIC_LIBRARY=ON".
I got a different error when compiling the last command "cmake --build". I guess i will open a new doubt about it afterwards. 

Thanks!

**Comment by ibell** [comment]
Ah, of course, now I see.  You had overlooked setting the generator to
cmake.  If you had posted the full log from the command line it would have
been obvious that's what the problem was.  That's why you should always
post the entire set of commands you ran and output you got when you open an
issue.  The more info we have (even if it doesn't seem important to you),
the better.

**Comment by hansingjunitra** [comment]
I am trying to install canvas (npm install canvas) but I encounter the error :
"C:\Program Files (x86)\MSBuild\12.0\Microsoft.Cpp.Default.props" was n
ot found. Confirm that the path in the <Import> declaration is correct, and that the file exists on dis
k.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\HansingJ\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HansingJ\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HansingJ\Documents\GitHub\ghShot\node_modules\gc-profiler
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN myapp@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gc-profiler@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gc-profiler@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HansingJ\AppData\Roaming\npm-cache\_logs\2019-06-21T06_38_43_457Z-debug.log

 I checked my MSBuild folder, but Microsoft.Cpp.Default.props is not there. I have tried repairing my microsoft build tools. 

Any suggestions? thanks
