### ISSUE TITLE
High-Level Interface and twophase approximations

### ISSUE THREAD

**Issue by DGSEM** [CoolProp/CoolProp#1725]
Dear coolprop community,

There are only few references about the approximation in the two-phase region. What models/assumptions (e.g. HEM) are used with the High Level interface? 

I am interested in quantities like A, CVMASS, d(P)/d(UMASS)|DMASS and d(P)/d(UMASS)|DMASS.

Regards

**Comment by ibell** [comment]
The derivatives are evaluated as though the state were single-phase (as is
described in the docs).  Same story for speed of sound and cv. Maybe you
are right that we should do something different for speed of sound and cv.
Recommendation?
