### ISSUE TITLE
Problem with the data for R717

### ISSUE THREAD

**Issue by AndreaStachel** [CoolProp/CoolProp#1728]
I found a problem with the data for R717 and wanted to ask if anyone else has the problem:
For entropy and enthalpy data, CoolProp gives me different values than in the literature. For example, the enthalpy of PropsSI("H"; "T";223; "Q";1;R717) is 1534.34 kJ/kg according to Coolprop but 1391.2 kJ/kg according to my other sources. R717 also has entropy deviations. For example, the entropy for PropsSI("S"; "T";223; "Q";1;R717) according to Coolprop 6.911 kJ/kgK but according to my other sources 6.440 kJ/kgK.
Is it just me, or has anyone else noticed?

**Comment by jowr** [comment]
I am afraid that it is just you ;-) 

See https://github.com/CoolProp/CoolProp/blob/master/FAQ.md
