### ISSUE TITLE
Install Broken Link to C++ Compiler

### ISSUE THREAD

**Issue by alexatrebound** [CoolProp/CoolProp#1729]
Attempted to install via pip command and [settings>package>available packages] with the following error.

`    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools`

The link provided is not found.

**Comment by ibell** [comment]
I'm afraid that I'm still in the dark as to what you are talking about.
Can you please provide some command line output of what commands you ran
and/or screenshots? I can't make sense of what issue you are running into.

**Comment by henningjp** [comment]
@alexatrebound , I believe this is the error message that comes up if trying to compile (not pip install) CoolProp under Python 3.5 or 3.6 (I've run into it myself).  Python wants very specific versions of C++ ( see the documentation for [Wrapper Common Prerequisites](http://www.coolprop.org/dev/coolprop/wrappers/index.html#wrapper-common-prereqs), specifically for Windows ).  Unfortunately, that error message link for where to get the recommended version of Microsoft Visual C++ comes from Python/Cython and the CoolProp community cannot change it.  There are some links on the [documentation page](http://www.coolprop.org/dev/coolprop/wrappers/index.html#wrapper-common-prereqs) for where to get various versions of MS Visual C++ versions.

If you are just doing a pip install, the installation should _not_ be looking for a compiler.  Please check the [documentation for installing the python wrapper](http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#python).

**Comment by ibell** [comment]
Ah, if you are just trying to install via pip, try the second one here:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation
.  That should install the wheel with no compilation on all modern python
versions

**Comment by alexatrebound** [comment]
Gotcha - thanks for the feedback @henningjp and @ibell !
