### ISSUE TITLE
c++ compiler website

### ISSUE THREAD

**Issue by bdechesne** [CoolProp/CoolProp#1735]
when installing CoolProp using pip without a C++ compiler, an error is displayed in the prompt advising to go to a webpage to get MS Visual C++ Build Tools. This webpage does not exist anymore.

**Comment by henningjp** [comment]
Please see issue #1729.

**Comment by thorade** [comment]
I think that broken link should be updated from:
http://landinghub.visualstudio.com/visual-cpp-build-tools
to this working link:
https://visualstudio.microsoft.com/visual-cpp-build-tools/
Or, people can just install correct version of Visual Studio.

**Comment by thorade** [comment]
The error message is not generated by Coolprop, but by setuptools:
https://github.com/pypa/setuptools/issues/1394
