### ISSUE TITLE
CoolProp cannot be installed on Python 3.6.1

### ISSUE THREAD

**Issue by Peymn** [CoolProp/CoolProp#1739]
I want to install CoolProp 6.1 (or even older versions) in Python 3.6.1. 
I use a Spyder 3.1.4 under win64.
When I run the "CoolProp-6.1.0.win-amd64-py3.5.exe"  (or 3.6 from the nightly release) it says that Python 3.5 (or 36) is required.  And when I want to install the wheel using pip, "could not find a version that satisfies the requirement" appears on the screen.
It seems that the CoolProp couldn't find Python while I have it now.

I need your help to fix this problem.

**Comment by Peymn** [comment]
Thank you ibell.
The error when I run the pip in anaconda prompt is shown in this image
![pip](https://user-images.githubusercontent.com/43807792/46399648-2e477900-c705-11e8-9a19-5ffd4c606cd9.jpg)

**Comment by ibell** [comment]
1) What version of python is in use?  You can't mix and match, if you have
python 3.6, the python 3.6 wheel is what you need.
2) Try the version that pip will pull from the server. Second one here:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation.
That should install the correct wheel for your python and arch.

**Comment by Peymn** [comment]
My Python version is 3.6.1 and I want to install CoolProp for this version, definitely. The other attempts was just for checking.
I downloaded from this link: 
http://www.coolprop.dreamhosters.com/binaries/Python/CoolProp-6.1.1.dev0-cp36-cp36m-win_amd64.whl
I think this is what I need for my Python at windows 64. Am I wrong?

**Comment by ibell** [comment]
Can you please try to use the second link here:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation
?  That is usually the most reliable.

Also, why 3.6.1?  Why not a more up-to-date release in the 3.6 series?

**Comment by Peymn** [comment]
I used "pip install CoolProp". 
This time after downloading and a series of copying, it was failed with error code 1 in "...\pip-install-viitd5vz\CoolProp\"
As thisimage:
![py](https://user-images.githubusercontent.com/43807792/46402532-d745a200-c70c-11e8-8d89-8c82bdc04f23.jpg)

**Comment by ibell** [comment]
THE SECOND ONE, not pip install CoolProp.  Do:

pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com
--find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U
--force-reinstall CoolProp

**Comment by Peymn** [comment]
Thank you ibell. This one worked.
You were really helpful.  :+1: 
Sorry for making you yelling at me with your capital letters :smiley: 
I appreciated you for your patience in solving my problem.

Kind regards

**Comment by ibell** [comment]
I was starting to get frustrated after it took four tries to get you to run
that command, but I'm glad you got it sorted out :)

**Comment by ibell** [comment]
Go ahead and close this issue if you are satisfied
