### ISSUE TITLE
Error in the calculation of the fundamental derivative of gas dynamics

### ISSUE THREAD

**Issue by arubino** [CoolProp/CoolProp#1740]
### Description

I get the following error when trying to obtain the fundamental derivative of gas dynamics:

> ValueError: This input [48: "fundamental_derivative_of_gas_dynamics"] is not valid for keyed_output : PropsSI("fundamental_derivative_of_gas_dynamics","T",466.875,"P",678650,"MM")

### Versions

**CoolProp Version:**  6.0.0
**Operating System and Version:** Ubuntu 14.04 LTS
**Access Method:** Python (2.7.6 and 3.4.3 )

Please, let me know if more info is needed.

**Comment by ibell** [comment]
Any particular reason you are using version 6.0?  Why not 6.1?

**Comment by arubino** [comment]
Upgrading to 6.1 fixed the issue. Many thanks!
