### ISSUE TITLE
Wrapper for OCTAVE-4.x.x 32 bit for Windows

### ISSUE THREAD

**Issue by galtieri** [CoolProp/CoolProp#1741]
While the wrapper for OCTAVE-4.2.1 operates correctly,
some problems (warnings) start to appear with OCTAVE-4.2.2 but the library is any way built.
The problems become severe with OCTAVE-4.4.x and the library is no more built.
The cause is the wrapper for Octave that uses deprecated Octave types or functions, moreover, some functions and members class have been renamed.
The errors are:
1)
...\CoolProp\build\CoolPropOCTAVE_wrap.cxx: In static member function 'static bool octave_swig_type::dispatch_global_op(const string&, const octave_value_list&, octave_value&)':
...\CoolProp\build\CoolPropOCTAVE_wrap.cxx:1718:18: error: 'class octave_function' has no member named 'do_multi_index_op'; did you mean 'do_index_op'?
       ret = fcn->do_multi_index_op(1, args)(0);
                  ^~~~~~~~~~~~~~~~~
                  do_index_op
2)
...\CoolProp\build\CoolPropOCTAVE_wrap.cxx: In function 'void SWIG_Octave_LinkGlobalValue(std::__cxx11::string)':
...\CoolProp\build\CoolPropOCTAVE_wrap.cxx:2274:3: error: 'symbol_table' has not been declared
   symbol_table::mark_global(name);
   ^~~~~~~~~~~~
3)
...\CoolProp\build\CoolPropOCTAVE_wrap.cxx: In function 'octave_value_list FCoolProp(const octave_value_list&, int)':
...\CoolProp\build\CoolPropOCTAVE_wrap.cxx:26233:3: error: 'octave_exit' was not declared in this scope
   octave_exit = ::_Exit;
   ^~~~~~~~~~~
4)
...\CoolProp\build\CoolPropOCTAVE_wrap.cxx:26269:54: error: cannot call member function 'octave_function* octave::call_stack::current() const' without object
     octave_function *me = octave_call_stack::current();
                                                      ^
I ask if the wrapper for Octave could be updated to the new Octave version 4.4.1 .

**Comment by ibell** [comment]
This error comes from the swig part, not CoolProp.  Have you tried to
upgrade swig, and/or what version of swig do you use?

**Comment by galtieri** [comment]
swigwin-3.0.12

**Comment by ibell** [comment]
Hmmm... That's pretty up-to-date...  Not sure what to recommend at this
point.  Touch base with the swig development team?  Not sure how active the
octave support is right now.  This page says they support 4.2, but make no
mention of 4.4: http://www.swig.org/Doc3.0/Octave.html

**Comment by galtieri** [comment]
Solved.
After compiling swig 4 (but it is still under development) and after a lot of warning, finally, I've successfully built the CoolProp library for Octave 4.4.1 .
Thanks "ibell" for the hint about swig.

**Comment by ibell** [comment]
Good to hear, thanks for the feedback.

**Comment by ibell** [comment]
If you like, you could put it up on server somewhere and post a link, but
in general we don't provide any binaries that are not generated by our
build system, there are too many versions of octave to support all of them
because the binaries are not backwards compatible...  For that reason,
people need to build their own oct files in general.

**Comment by galtieri** [comment]
The compiled CoolProp library linked to Octave win32 version 4.4.1 or 5.1.0 is [here](https://sourceforge.net/projects/coolpropforoctavebinarie/files/).
