### ISSUE TITLE
r404a JT valve error

### ISSUE THREAD

**Issue by timms1030** [CoolProp/CoolProp#1742]
So I am using DWSIM to simulate my refrigeration cycle, I have r404a coming out of the condenser at 290 psi and 110F, it then drops across a JT valve.  This process works fine as long as the pressure is below 44.1 psig, if the pressure goes above that then an error occurs.  The developer has said that this is a coolprops issue.  Any ideas on fixing this or workarounds?

**Comment by ibell** [comment]
What error do you get from CoolProp?

Also, please provide your inputs in SI units.

**Comment by timms1030** [comment]
The error that DWSIM gives says that two phase is not currently allowed, when asking the DWSIM developer he says that this is a limitation of CoolProp.

The inlet to the valve is:
20 barg and 43.333C
The outlet of the valve works fine until the outlet pressure goes above 3.04 barg

Thanks for your help.

Cheers,

Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by ibell** [comment]
That makes sense - you can't have two-phase inputs with PT as inputs for
pure fluids; with PY inputs near or at saturation you don't know if you
have liquid or vapor.

**Comment by timms1030** [comment]
I suppose the thing that is most confusing for me is that the system is fine with the inputs (and gives accurate results) when the pressure out of the valve is lower.  Also, this is operating like a pretty standard refrigeration cycle, so I’m not sure why the property package would be limited at higher pressures (i.e. higher evaporator temperatures) considering R404a is used in situations like this all of the time.

And the outlet of the valve is expected to be two phase, and is at lower pressures and temperatures.  Maybe I am just misunderstanding what you are saying.

Thanks for the help

Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by ibell** [comment]
For a pure fluid, if you specify T and P which correspond to a saturation
state (T and p are not independent for saturation), it is not possible to
determine whether you have saturated liquid, saturated vapor, or somewhere
in between.  Think about these diagrams for instance:
https://en.wikipedia.org/wiki/Phase_diagram#3-dimensional_diagrams .
That's why your inputs are invalid.

**Comment by timms1030** [comment]
I am not specifying both T and P, I am only specifying the pressure out of the valve, the inlet is set by the condenser and ambient conditions

Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by ibell** [comment]
So then in DWSIM, the inputs to the valve are two-phase, which is where
CoolProp dies.  Can you give me the exact error that DWSIM throws you from
CoolProp?

**Comment by timms1030** [comment]
No, the inlet to the valve is a subcooled liquid.  Also, if it was two phase it would have been two phase with lower valve outlet pressures and thus would still not make sense, but that is beside the point.

I have attached a sample file that can be used to show the issue.

Once again thanks for the help,

Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by ibell** [comment]
But it must be the case that though the valve is *supposed* to be
subcooled, that the inputs, in this case, are actually super close to the
phase boundary.  I'm not sure how this is handled in DWSIM, but this is the
origin of your problem.

**Comment by timms1030** [comment]
It is 3C subcooled so yes it is relatively close to the boundary, but once again why does it work sometime and not others?

Not trying to argue, just trying to understand.

Cheers

Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by ibell** [comment]
Is there anything more? A screenshot could be helpful.

**Comment by timms1030** [comment]
Pretty much all it says, here is the simulation not converged with an outlet pressure of 44.2 psig


[cid:image004.jpg@01D46150.DB979790]


Here is the simulation converged with an outlet pressure of 44.1 psig


[cid:image005.jpg@01D46150.DB979790]

Thanks again for all of the help!

Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by ibell** [comment]
I'm afraid you'll have to attach the images in the web interface...

**Comment by timms1030** [comment]
[TXV Issues.docx](https://github.com/CoolProp/CoolProp/files/2470076/TXV.Issues.docx)

**Comment by ibell** [comment]
Can you get any more verbose debugging from DWSIM?  The error is clear, but
I don't understand yet precisely which call to CoolProp results in this
error, which is what I need to know to be able to understand whether this
is a bug in DWSIM or CoolProp.

**Comment by timms1030** [comment]
Daniel,

Can you help at all with the actual error that is happening in this simulation?  This is referencing ticket #206 that I posted on Oct 3rd.

Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by ibell** [comment]
I don't think you successfully forwarded this to him...

**Comment by timms1030** [comment]
Here is his response:


This is the call that originates the error message:

CoolProp.PropsSI("C", "T", 261.27485142655985, "P", 411591.9808, "R404A")

Error message: 'Two-phase inputs not supported for pseudo-pure for now'.


Scott Timms
Sales Engineer
[cid:image001.jpg@01D41CEC.7635BD80]
G&D Chillers, Inc.
760 Bailey Hill Rd.
Eugene, Oregon 97402
o 800 555 0973
f  541 345 8835
c 713 492 1547
G&D Chillers.com<http://www.gdchillers.com/> | Facebook<https://www.facebook.com/gdchillers/> | Twitter<https://twitter.com/gdchillers> | Instagram<https://www.instagram.com/gdchillers>
How to Install a Chiller<http://gdchillers.com/installation-videos/how-to-install-a-chiller> / Portable Chiller<http://gdchillers.com/installation-videos/how-to-install-a-portable-chiller>
Frequently Asked Questions<http://gdchillers.com/faq>

**Comment by DanWBR** [comment]
@timms1030 I'm here. :-)
@ibell so this error means that at the specified T/P the fluid is in a VLE condition?

**Comment by ibell** [comment]
Correct.  And for a pseudo-pure fluid, that is not allowed, since the EOS
is only valid at saturation or in homogeneous phases
