### ISSUE TITLE
Add fluids to CoolProp if you are using matlab

### ISSUE THREAD

**Issue by guidoffrate** [CoolProp/CoolProp#1752]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**CoolProp Version:** [CoolProp version you are using]  
**Operating System and Version:** [OS you are running CoolProp on]  
**Access Method:** [How you are accessing CoolProp (i.e. Python, other wrapper, direct C++ calls, etc.)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by guidoffrate** [comment]
Hi, i'm trying to add fluid to coolprop using the JSON file. I would like to use the PR or the SRK backend, so i'm trying to add the fake_fluid json file that is provided as an example somewhere.
 I'm using coolprop on matlab, so i used the function:
CoolProp.add_fluids_as_JSON('PR','custom_fluid.json')
with the following answer (that i interpreted as a success):
ans = logical 1
 Unfortunately, when i try to use the coolprop functions as usual i receive the following:
 "Warning: Initialize failed for backend: "PR", fluid: "custom_fluid" fractions "[ 1.0000000000 ]"; error: Fluid identifier [custom_fluid] was not found in CubicsLibrary "
So the question is: what the proper procedure to add a json file to Coolprop if you are using matlab?

**Comment by guidoffrate** [comment]
Thank you for the quick response. My feedebacks are:
1) your code does not work. with python 3.6 used on matlab, as shown:

pyversion

       version: '3.7'
    executable: 'C:\Users\+++\Anaconda3\python.exe'
       library: 'C:\Users\+++\Anaconda3\python37.dll'
          home: 'C:\Users\+++\Anaconda3'
      isloaded: 1

The following error is issued:

No appropriate method, property, or field 'read' for class
'py._io.TextIOWrapper'.

I don't know if this what you feared saying ("I'm not sure if the open function can be imported like this")

2) i managed to read the json on matlab. Using the the following:

fname = 'fake_fluid.json';
val = jsondecode(fileread(fname));

The content is loaded as a structure. When i tried the code provided in Coolprop for matlab, which is:

CoolProp.add_fluids_as_JSON('PR',struct)

It issued the following error:

Warning: in method 'add_fluids_as_JSON', argument 2 of type 'std::string const
&' 
> In CoolProp.add_fluids_as_JSON (line 2)

So what i'm wondering is: what do you mean when you say to pass the content of the JSON file to the function? in which format it is expected to be provided to the function, as the problem could actually be the struct format, so i miss just an intermediate step in which a translation is performed.

Thank you in advance.

**Comment by ibell** [comment]
Just pass the string of the JSON, not the matlab JSON structure

**Comment by guidoffrate** [comment]
Just done, with:

>> CoolProp.add_fluids_as_JSON('PR','[{"CAS": "000-0-00", "Tc": 400.0, "Tc_units": "K", "acentric": 0.1, "aliases": "FAKEFLUID", "molemass": 0.04, "molemass_units": "kg/mol", "name": "FAKEFLUID", "pc": 4000000.0, "pc_units": "Pa"}]')

The answer now is:

ans =

  logical

   1

From this is hould be able to use the fluid as always done? It apperas no: if i use:

CoolProp.PropsSI('T','P',10^5,'Q',0.5,'PR::FAKEFLUID')

I get:

Warning: Initialize failed for backend: "PR", fluid: "FAKEFLUID" fractions "[
1.0000000000 ]"; error: Fluid identifier [FAKEFLUID] was not found in
CubicsLibrary 
> In CoolProp.PropsSI (line 2) 

What i'm missing?
Thank you so much for your time, you are very kind.

**Comment by ibell** [comment]
Can you try this example in Python directly?  I wonder if for some reason
there is something funny with the lifetime of Python objects in
matlab/Python interface.  Another idea would be to call

CoolProp.set_debug_level(100)

before your calls.  You should get a lot of output to the terminal, which
might help to debug what is happening.

**Comment by ibell** [comment]
Closing due to lack of feedback. Feel free to re-open

**Comment by alex-s-v** [comment]
Hello, I use Python 3.7.6 and CoolProp installed from pip. Get the same issue:
```
Traceback (most recent call last):
  File "add_fluid_test.py", line 19, in <module>
    T = CP.PropsSI("T", "P", 101325, "Q", 0,"PR::trichloroethylene")
  File "CoolProp/CoolProp.pyx", line 347, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 427, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 314, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "PR", fluid: "trichloroethylene" fractions "[ 1.0000000000 ]"; error: Fluid identifier [trichloroethylene] was not found in CubicsLibrary : PropsSI("T","P",101325,"Q",0,"PR::trichloroethylene")
```
```
import json
import CoolProp.CoolProp as CP


flud_data = {
    'CAS': '79-01-6',
    'Tc': 571.0,
    'Tc_units': 'K',
    'acentric': 0.217,
    'aliases': ['TCE'],
    'molemass': 0.131387,
    'molemass_units': 'kg/mol',
    'name': 'trichloroethylene',
    'pc': 4910000.0,
    'pc_units': 'Pa'
}

CP.add_fluids_as_JSON("PR", json.dumps([flud_data]))
CP.PropsSI("T", "P", 101325, "Q", 0,"PR::trichloroethylene")
```

**Comment by alex-s-v** [comment]
Ok, I've figured out the problem. The name of the fluid must be in all caps in JSON fluid description, or it will not work. I don't know is it a bug or is it a feature, but it is slightly annoying.

**Comment by ibell** [comment]
Bug, not feature.  This had annoyed me too, but not yet enough to fix it.
Want to fix this?  It's a one line fix in C++

**Comment by alex-s-v** [comment]
Is it good enough to add `upper` function around `val.name` on the 54 and 59 lines inside [CubicsLibrary.cpp](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/CubicsLibrary.cpp#L54)? I'm not very good at C++, the last time I used it was about 5 years ago :grimacing:.

**Comment by ibell** [comment]
That would fix it, but a better fix would be to remove the uppercasing in this function: https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/CubicsLibrary.cpp#L75

**Comment by alex-s-v** [comment]
I thought about it, but if some madman creates a mixture with name in camelcase it will ruin it all, or I'm mistaken?
