### ISSUE TITLE
Build AbstractState object from stored tabular data

### ISSUE THREAD

**Issue by fwitte** [CoolProp/CoolProp#1758]
Hi everybody,

I am using CoolProp for thermal process simulation and have a lot of `CoolProp.CoolProp.PropsSI`-function calls. Especially in combustion processes this slows down calculation speed remarkably, thus I would like to use the tabular data interpolation backend instead of HEOS for speeding up my calculations.

My problem here is, that the build of the AbstractState object takes up a relatively long time (in regard to calculation time), thus building it prior to every call of my python script is not favorable. I would rather like to re-import the tabular data already stored in the ~/.CoolProp folder and pass the data to an AbstractState object, thus skipping the build.

Is there already a way of doing this? I tried to dig into the source-code, but could not figure out the correct "entry point". If this feature is not implemented (and there is actual speed up by reading the tabular data), I would also like to try implementing it! Maybe someone can help me where to start!

Have a nice sunday!

Francesco

**Example**

```
import CoolProp as CP
import time

tmp = time.time()
CP.AbstractState('BICUBIC&HEOS', 'H2O')
CP.AbstractState('BICUBIC&HEOS', 'CO2')
CP.AbstractState('BICUBIC&HEOS', 'N2')
CP.AbstractState('BICUBIC&HEOS', 'Ar')
CP.AbstractState('BICUBIC&HEOS', 'CH4')
CP.AbstractState('BICUBIC&HEOS', 'O2')
print(time.time() - tmp)

>>> 1.6265525817871094
```
A simple process calculation often only requires about 2 to 5 seconds, especially while dimensioning a process one would typically make lots of single calculation fiddling around with design parameters.

**Python**
Python 3.6.5

**CoolProp**
Version: 6.2.2.dev0

**Comment by jowr** [comment]
Hi, I think you do not use the AbstractState as it was intended. You should only create one state object per fluid/species and then reuse that object everywhere in your code. 

The tables do not get built each time. What you experience is the time it takes to *read* the pre-built tables from your harddisk.

```Python
import numpy as np
import random
import CoolProp.CoolProp as CP
import time

random.seed("coolprop_test")
p = 101325 # 1 atmosphere
T = np.random.uniform(120,400,10000) + 273.15 # Random points from 120 to 400 deg C, gas phase only

# Make sure the objects exist and create tables if needed
normal_state = CP.AbstractState("HEOS", "H2O")
tabular_state = CP.AbstractState("BICUBIC&HEOS", "H2O")

# Measure execution speed
results = {}

tmp = time.time()
for Ti in T:
    rho = CP.PropsSI("Dmass", "P", p, "T", Ti, "H2O")
results["1. PropsSI"] = time.time() - tmp

tmp = time.time()
for Ti in T:
    normal_state.update(CP.PT_INPUTS, p, Ti)
    rho = normal_state.keyed_output(CP.iDmass)
results["2. HEOS"] = time.time() - tmp

tmp = time.time()
for Ti in T:
    tabular_state.update(CP.PT_INPUTS, p, Ti)
    rho = normal_state.keyed_output(CP.iDmass)
results["3. Tables"] = time.time() - tmp

#for k in sorted(results):
#    print("{0} : {1} ms".format(k, results[k]*1e3))
#print("\nDo NOT do this!")
tmp = time.time()
for Ti in T:
    normal_state = CP.AbstractState("HEOS", "H2O")
    normal_state.update(CP.PT_INPUTS, p, Ti)
    rho = normal_state.keyed_output(CP.iDmass)
results["4. HEOS (create state)"] = time.time() - tmp

tmp = time.time()
for Ti in T:
    tabular_state = CP.AbstractState("BICUBIC&HEOS", "H2O")
    tabular_state.update(CP.PT_INPUTS, p, Ti)
    rho = normal_state.keyed_output(CP.iDmass)
results["5. Tables (create state)"] = time.time() - tmp

for k in sorted(results):
    print("{0} : {1} ms".format(k, results[k]*1e3))
```
```
1. PropsSI : 3076.99990273 ms
2. HEOS : 295.000076294 ms
3. Tables : 9.0000629425 ms
4. HEOS (create state) : 2993.99995804 ms
5. Tables (create state) : 2770.99990845 ms
```
