### ISSUE TITLE
Memory leak in Mathematica interface

### ISSUE THREAD

**Issue by szhorvat** [CoolProp/CoolProp#1759]
I noticed the following issue after someone asked [a question that relates to the CoolProp Mathematica interface on the Mathematica StackExchange](https://mathematica.stackexchange.com/q/185797/12).

The functions in the wrapper take string arguments from Mathematica:

https://github.com/CoolProp/CoolProp/blob/master/wrappers/Mathematica/CoolPropMathematica.cpp#L47

Such strings must be freed manually after use with `libData->UTF8String_disown`. See the *String Arguments* section here:

https://reference.wolfram.com/language/LibraryLink/tutorial/InteractionWithMathematica.html

Currently they are not freed, i.e. there is a memory leak.

**Comment by ibell** [comment]
Grumble, grumble... Why do these people not tell us when they have problems
like this?

Can you manage a pull request to fix this? I don't have access to
Mathematica to test currently.

**Comment by szhorvat** [comment]
PR sent.

If you'd like to make the Mathematica interface self-contained, and complete with pre-compiled binaries, I can help with this. Just send me an email. It is possible to compile Mathematica libraries without having access to Mathematica itself.

**Comment by szhorvat** [comment]
I made a few more improvements, not in the above PR. Let me know if there is any interest. Some things don't quite work as described in the documentation (e.g. `PhaseSI` does not return an empty string on error) so I don't want to continue yet.

![image](https://user-images.githubusercontent.com/1212871/48704960-36497280-ebf8-11e8-8c51-2812cbfe1542.png)

**Comment by szhorvat** [comment]
@ibell So I take it you are not interested in further improvements some of which I showed above?  The current interface is so basic it can hardly be called an interface, and the example notebook is confusing (why unload the functions at all?)  I would say one can hardly use it without already having some familiarity with LibraryLink.

**Comment by szhorvat** [comment]
Could you please send me a (private) email about this?
