### ISSUE TITLE
Android Wrapper error at 6.2.0 and 6.2.2dev

### ISSUE THREAD

**Issue by Werkeng** [CoolProp/CoolProp#1760]
Hello!
I have a problem with Andriod Wrapper compiling. After calling "cmake --build ." it goes till REFPROPMixtureBackend.cpp and stops after that with error. Please see shell output in attachment.
I'm facing with this problem at 6.2.0 and 6.2.2dev versions.
Version 6.1.0 has no such problem (except for some warnings). I could be wrong but version 6.1.1dev also did not have such problem.
I use Windows 10, 64bit.
Can it be fixed in the future? Should I give you some additional information about this error?

Thank you very much.
[CMAKE_BUILD_COOLPROP_621.txt](https://github.com/CoolProp/CoolProp/files/2572254/CMAKE_BUILD_COOLPROP_621.txt)

**Comment by ibell** [comment]
Weird.  I can't see why any changes to CoolProp would cause Android builds
to fail.  Can you please do clean builds with complete logs for 6.1.0,
6.1.1dev and 6.2.2dev?  Maybe that would give some idea what is going on.

**Comment by ibell** [comment]
Maybe this is related to updating a submodule between 6.1 and 6.2.2?.  I
note that in one case, you built from a git repo, and in the other, you
built from a source zip -- can you do the same in both cases?.  Perhaps
that is the reason for the issue?  Do you have any other output in another
file in your build folder?  There are some log files that I don't usually
check, but maybe this time they are instructive.

**Comment by ibell** [comment]
Closing due to lack of feedback.  Feel free to re-open
