### ISSUE TITLE
IF97 Documentation Page Error

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1762]
### Description

New documentation page for IF97 backend (fluid_properties/IF97.html) is missing from documentation at http://www.coolprop.org.

### Steps to Reproduce

1. Error 403 when browsing to http://www.coolprop.org/fluid_properties/IF97.html
2. Page displays ok on the dev branch http://www.coolprop.org/dev/fluid_properties/IF97.html
3. Page displayed ok on the dev branch when release was 6.1.0.

**Expected behavior:** Page should have been promoted from the 6.1.1.dev branch after release of 6.2.0.

**Actual behavior:** 403 error thrown by SourceForge host.  Looks like the links to the page were updated in the site map, but the page itself didn't make it.

### Versions

**CoolProp Version:** Occuring post 6.2 release  
**Operating System and Version:** n/a  
**Access Method:** n/a  

### Additional Information

```
An error has been encountered in accessing this page.

1. Server: www.coolprop.org 
2. URL path: /fluid_properties/IF97.html 
3. Error notes: NONE 
4. Error type: 403 
5. Request method: GET 
6. Request query string: NONE 
7. Time: 2018-11-23 11:53:03 UTC (1542973983)
```

**Comment by ibell** [comment]
@jowr - can you specially move over this file?  I don't think I have the ability to push this file currently.

**Comment by henningjp** [comment]
Thanks @jowr !

**Comment by henningjp** [comment]
Well, it was there.  Something automated must be clobbering it.

**Comment by jowr** [comment]
This is super weird, how can a single page disappear when a folder is rsync'ed? What else is missing? @ibell , where should I copy the file from? Guess the release build binaries have been purged long ago assuming that everything went well.

**Comment by ibell** [comment]
Agreed, what is going on? I guess a temporary copy from binaries/sphinx
should do it, but I can't explain this bizarre behavior that we see.

**Comment by henningjp** [comment]
I can only think that there is some master list/script that I didn't know to add it to when I created it.  However it looks as though it just reads everything in the tree.  It copies just fine to the dev/docs on the server, and it appears to be the only page that didn't make it to the release docs.  Since it is probably the only new page added, I suspect it was not added correctly to some list the rsync uses, or the page generator doesn't snag it.  Interestingly, it IS in the menu tree, so when that tree gets build it knows that the page exists.

**Comment by ibell** [comment]
The weird thing is the sphinx build in the buildbot server includes the
files properly:
http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/fluid_properties/IF97.html

P.S. Want to add a link to IF97 to the main page of CoolProp docs?

**Comment by ibell** [comment]
The buildbot server puts its output here: http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/ and that has the link and the correct IF97 page.  I think maybe @jowr needs to update the rsync job that copies over to sourceforge?

**Comment by jowr** [comment]
I am going to prepare a new release due to #1777 - How can we make sure that everything goes well this time? By the way, I have no idea why the dev section is not updated. Those pages should be updated on a nightly basis... I'll investigate.

**Comment by jowr** [comment]
I think I fixed everything, but there is this message from the website builder that bothers me:
```
Ignoring indexes: https://pypi.python.org/simple
Processing ./dist/CoolProp-6.2.2.dev0-cp27-cp27m-macosx_10_5_x86_64.whl
Installing collected packages: CoolProp

Successfully installed CoolProp-5.1.3.dev0
Cleaning up...
```

@ibell Do you have any idea what is going on? That is your machine and maybe you can have a look at the local folders. It might help to run `pip uninstall coolprop` a couple of times.

**Comment by jowr** [comment]
Please note that the gitrevision is correct which means that the new package is used.

**Comment by ibell** [comment]
> I think I fixed everything, but there is this message from the website builder that bothers me:
> 
> ```
> Ignoring indexes: https://pypi.python.org/simple
> Processing ./dist/CoolProp-6.2.2.dev0-cp27-cp27m-macosx_10_5_x86_64.whl
> Installing collected packages: CoolProp
> 
> Successfully installed CoolProp-5.1.3.dev0
> Cleaning up...
> ```
> @ibell Do you have any idea what is going on? That is your machine and maybe you can have a look at the local folders. It might help to run `pip uninstall coolprop` a couple of times.

Indeed, there were a whole, whole lot of CoolProp versions.  Should we consider to run the process inside a pristine environment with conda or virtualenv?  Would avoid this issue.  I can do so.

**Comment by ibell** [comment]
FYI I am in the process of upgrading my build machine, so it is currently offline, but should be back later on tonight my time

**Comment by jowr** [comment]
I just downgraded my builder from XCode 10 to XCode 9.4 and now all builds work like they should without any problems, but I guess we are prepared next time someone has problems building on OSX.

I uploaded new docs to the dev folder and as soon as your machine is back, I am going to release 6.2.2.

**Comment by ibell** [comment]
Upgraded to 10.14, machine very unhappy.  How do you downgrade to Xcode 9.4?

**Comment by jowr** [comment]
- Remove all traces of XCode and the command line tools from /Library/Develop
- Download Command Line Tools for 9.4 (OSX 10.13) from http://developer.apple.com/download/more
- Install command line tools
