### ISSUE TITLE
Mathcad 15 binary builds dropped as of version 6.2

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1763]
### Description

**_Mathcad 15_** binary builds missing from recent SourceForge folders.

### Steps to Reproduce
**_Mathcad15_** folders missing on SourceForge from
1. 6.2.0
2. 6.2.1
3. Nightly Build

**Expected behavior:** **_Mathcad Prime_** is the new re-designed version of Mathcad by PTC; however, the legacy version, **_Mathcad 15_**, is still supported by PTC (maintenance release just issued to support Windows 10) and used by a large number of dedicated users.  Both **_Mathcad15_** and **_MathcadPrime_** folders should still be in these releases and the Nightly Build.  Updates are still being made to both of the Mathcad wrappers.

**Actual behavior:** Looks like **_Mathcad15_** was dropped from the build list at 6.2.0.  Can we re-instate these please?

### Versions

**CoolProp Version:** 6.2.x  
**Operating System and Version:** Windows  
**Access Method:** Binaries from SourceForge  

### Additional Information

**_Mathcad 15_** will continue to be supported through at least Mathcad Prime 6.0 (They are on version 5.0 now).  I will definitely flag the CoolProp core development team when Mathcad 15 is finally unsupported by PTC.

**Comment by ibell** [comment]
I think the issue was I couldn't get access to MathCAD 15 to build the interface, so I figured that nobody would mind too much, and I didn't want to hold up the release.  Are there actually users of MathCAD 15 of CoolProp?

**Comment by henningjp** [comment]
It hasn't changed since 6.1.0 (It's just a link with the Mathcad 15 lib instead of the Prime lib) and those were compiled and downloaded regularly from SourceForge by users for both versions of Mathcad.  
![coolprop downloads](https://user-images.githubusercontent.com/17114032/49074812-7bc2fc80-f203-11e8-98d9-a6fb74d33819.png)

It just looks like the Mathcad 15 compile was commented out of the buildbot config file in commit 9f8ca20206d94ec2081cd338528b88d32db15a10 (**_Move Slaves to DTU_**).  It doesn't say why.
```
    # # ***************
    # # Build the MathCAD 15 dll
    # # ***************
    # factory.addStep(ShellCommand(command=' '.join(["cmake", "../..", 
    #   "-DCOOLPROP_MATHCAD15_MODULE=ON","-G", '"Visual Studio 10 2010"', '-DCOOLPROP_MATHCAD15_ROOT="C:/Program Files (x86)/Mathcad/Mathcad 15"']),
    #                              workdir= working_folder+'/mathcad15',
    #                              haltOnFailure = True))
    # factory.addStep(ShellCommand(command=["cmake", "--build", ".", "--target", "install", "--config", "Release"], workdir = working_folder+'/mathcad15', haltOnFailure = True))
```
Maybe for reason.

I have the capability of creating these binaries.  If there's some way I can help let me know.

**Comment by jowr** [comment]
The issue is that none of us has a Mathcad license. As far as I can see, the only free version of Mathcad is PTC Mathcad Prime 4.0.

- Is PTC Mathcad Prime 4.0 sufficient to build the wrappers?
- Is there any other way of getting hold of the headers etc needed to build the wrapper?

**Comment by henningjp** [comment]
* Prime links to a 64-bit library and Mathcad 15 links to a different 32-bit library.
* The .h headers (and wrapper code) are identical.
* @ibell had the 32-bit add-in library for Mathcad 15 some time ago and that's what the 6.1.0 script was linking to for Mathcad 15.  

I'll e-mail you and @ibell

**Comment by henningjp** [comment]
@ibell Here's the link to the [free trial version of Mathcad 15](https://www.ptc.com/en/products/mathcad/free-trial) from PTC.  It's a full version that will stop working after 30 days, however the buildbot only needs access to the mcaduser.lib and mcadincl.h files to build the wrapper, and they will be installed in the proper locations.   I can verify the binaries from here.  Thanks.

**Comment by ibell** [comment]
It's gotta be @jowr to do this since he is the only one with access to the
slave

**Comment by henningjp** [comment]
I'll look at it tonight.  Thanks.

**Comment by jowr** [comment]
Great, maybe we can fix #1756 and #1754 and release v6.2.2. Guess we should develop a habit of making more frequent releases...

**Comment by henningjp** [comment]
@jowr If I send you the Mathcad 15 binaries for 6.2.0 and 6.2.1, can you upload those manually to SourceForge?  Does it work that way?

**Comment by henningjp** [comment]
@jowr - I know you guys are busy, but can we at least backfill the Mathcad 15 binary for 6.2.1  on SourceForge so there's a more current release until 6.2.2 is pushed?

**Comment by ibell** [comment]
The blocking issue for 6.2.x is that we are awaiting a repair of the incompressible fluid documentation generation.  We've migrated doc generation to Python 3.x, which broke the incompressible scripts, and I looked into it, but could not figure out how to repair them.  @jowr  needs to look into it, then we can release 6.2.2, or perhaps 6.3 since I have updated a number of the EOS.

**Comment by keygen-maker** [comment]
Mathcad Lisence Key is part of a larger product development system developed by PTC and is often used for many analytical handling points in process engineering systems.
Stanely
keygenbro.com

**Comment by khansa608** [comment]
Mathcad Serial Key is part of the PTC’s most advanced hardware development system, and is often used for many touch-ups within the engineering process. Collaborate with other PTC solutions that support product development, including Creo Elements / Pro, Windchill, and Creo Elements View. 
Jessica
patchhere.com
