### ISSUE TITLE
Fix links to coolprop.org

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1772]
I guess @Rod-Persky stopped paying for coolprop.org and it has been hijacked by some domain-parking service. We should update the docs and everything else to point to http://coolprop.sourceforge.net instead. I already fixed the project settings on GitHub.

**Comment by ibell** [comment]
That's not good!  Is there anything we can do about this?  I think this is
partly my fault since rod sent me the info at one point, but the date
seemed so far away...

**Comment by Rod-Persky** [comment]
Sorted, sorry!

**Comment by Rod-Persky** [comment]
Actually Sourceforge changed their IP and I think someone managed to squat that, I've updated it based on the VHOST guide.

**Comment by ibell** [comment]
@Rod-Persky Thanks very much for sorting this out. Could you add Jorrit and I to the account (I think I'm already on it) so that in the future we will get reminded about re-upping the payment?

**Comment by jowr** [comment]
Great, thank you for the swift action!
