### ISSUE TITLE
void fraction calculation

### ISSUE THREAD

**Issue by hermez19** [CoolProp/CoolProp#1774]
Ok so I'm new using CoolProp, I'm trying to calculate de derivative of void fraction respect to pressure at constant temperature. I'm using Zivi correlation, and forward difference to do this. But I have a question. Could CoolProp evaluate void fraction and then can use a user derivative to achieve a result? I'm not sure of the manual results. Thanks very much

**Comment by henningjp** [comment]
Sorry, I misread void fraction.  However, this physics still holds.  T cannot be held constant while varying P and maintain a liquid/vapor mixture.

**Comment by hermez19** [comment]
It's not vapor fraction is void fraction; and in a thesis they present this equation: 
![image](https://user-images.githubusercontent.com/45673916/50389698-702bfe00-06fb-11e9-96a3-bc3926dd4a2c.png) And I assume that is at constant temperature

**Comment by hermez19** [comment]
Ok, maybe is another properties held constant, maybe density. but the question is if there is a way to do a void fraction derivative in CoolProp

**Comment by henningjp** [comment]
Probably not.  If pressure is varying, you are probably condensing/boiling and temperature is varying along the saturation curve.

**Comment by hermez19** [comment]
Mmm, Ok I'll check another way to solve the equation. Thanks

**Comment by ibell** [comment]
Well void-fraction (not the vapor fraction) is by definition not an equilibrium property.  Therefore, with Zivi you can calculate the derivative of the void fraction, but what precisely are you holding constant?

**Comment by hermez19** [comment]
Well, In the thesis they don't specific the constant property, but I assume that is Temperature, because is about modelling a DX evaporator.

**Comment by ibell** [comment]
I think you should check out Matthis Thorade's paper relating to the
derivatives of the vapor fraction, which has direct analogs to your
problem: https://link.springer.com/article/10.1007/s12665-013-2394-z

**Comment by ibell** [comment]
I think we'll close this issue because its a bit out-of-scope for CoolProp.
