### ISSUE TITLE
Tmin function cannot be evaluated at 0.0 concentration for incomp fluids

### ISSUE THREAD

**Issue by murenrb** [CoolProp/CoolProp#1775]
### Description

PropSI is throwing an error at a concentration of 0.0. This error doesn't occur in version 6.0.0. 

Error is:
Initialize failed for backend: "INCOMP", fluid: "" fractions ""; error: key [] was not found in string_to_index_map in JSONIncompressibleLibrary : PropsSI("Tmin","T",298,"P",100000,"INCOMP::MKA[0.0]")

### Steps to Reproduce

Running this code in console will reproduce the error in version 6.2.1
from CoolProp.CoolProp import PropsSI
PropsSI("Tmin","T",298,"P",100000,"INCOMP::MKA[0.0]")

**Comment by henningjp** [comment]
This was patched recently with PR #1765.  If you grab the nightly build version, this function should work correctly.

**Comment by murenrb** [comment]
Great!
