### ISSUE TITLE
Building from the PyPI sdist on Python 3.7 results in compilation errors on macOS

### ISSUE THREAD

**Issue by bryanwweber** [CoolProp/CoolProp#1777]
### Description

After downloading the sdist of 6.2.1 from PyPI (BTW, there is no tag nor release on GH for 6.2.1), trying to build the package using Python 3.7 by running

    MACOSX_DEPLOYMENT_TARGET=10.9 python setup.py install

results in

```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/bryan/miniconda3/include -arch x86_64 -I/Users/bryan/miniconda3/include -arch x86_64 -I. -I./include -I./src -I./externals/Eigen -I./externals/fmtlib -I./externals/msgpack-c/include -I/Users/bryan/miniconda3/include/python3.7m -c CoolProp/CoolProp.cpp -o build/temp.macosx-10.7-x86_64-3.7/CoolProp/CoolProp.o
CoolProp/CoolProp.cpp:65531:21: error: no member named 'exc_type' in '_ts'
    *type = tstate->exc_type;
            ~~~~~~  ^
CoolProp/CoolProp.cpp:65532:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
    *value = tstate->exc_value;
                     ^~~~~~~~~
                     curexc_value
/Users/bryan/miniconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
CoolProp/CoolProp.cpp:65533:19: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
    *tb = tstate->exc_traceback;
                  ^~~~~~~~~~~~~
                  curexc_traceback
/Users/bryan/miniconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
...
```
(output truncated for space).

I can successfully build the same commit from a git checkout of the source tree and using Cython, so I presume the problem has something to do with not using Cython in the sdist. Is there a reason not to include the *.pyx files in the sdist?

### Versions

**CoolProp Version:** 6.2.1
**Operating System and Version:** macOS 10.14.2 Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0

P.S. 
Not setting the `MACOSX_DEPLOYMENT_TARGET` results in

```
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
CoolProp/CoolProp.cpp:487:10: fatal error: 'string' file not found
```
but I think that's expected.

**Comment by bryanwweber** [comment]
I'm working on building a conda package, so I need to use the sdist because the library has to be compiled with the Anaconda compilers. The sdist actually [includes the `.build_without_cython` file](https://github.com/CoolProp/CoolProp/blob/de465e1cf6755d23231f289c6f7c24fd58eca465/wrappers/Python/pypi/prepare_pypi.py#L17), suggesting that disabling Cython (or at least not including the pyx files in favor of the generated cpp) is purposeful. If I remove that file and install Cython, then build, the output I get is

```
Cython version:  0.29.2
Cython will be used; cy_ext is pyx
Traceback (most recent call last):
  File "setup.py", line 324, in <module>
    ext_modules = cythonize(ext_modules, compiler_directives = cython_directives)
  File "/Users/bryan/miniconda3/envs/comps/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
    aliases=aliases)
  File "/Users/bryan/miniconda3/envs/comps/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/Users/bryan/miniconda3/envs/comps/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
    raise ValueError(error_msg)
ValueError: 'CoolProp/CoolProp.pyx' doesn't match any files
```

Actually, it appears that the same error occurs for Windows and Linux as well (see [macOS](https://travis-ci.org/conda-forge/coolprop-feedstock/jobs/460457096#L3222), [Windows](https://ci.appveyor.com/project/conda-forge/coolprop-feedstock/builds/20597581/job/74fbb4aj4exfboqg#L646) and [Linux](https://circleci.com/gh/conda-forge/coolprop-feedstock/34)). Maybe the code generation of the CPP file has gone wrong? It seems this has been fixed in Cython 0.29 and greater, see https://github.com/cython/cython/pull/2607. I'll try to localize which version of Cython works here.

Thank you for your time!

**Comment by danilomendesdias** [comment]
@bryanwweber that was fixed at conda-forge: https://github.com/conda-forge/coolprop-feedstock/pull/4

**Comment by ibell** [comment]
Can somebody please make a PR for the CoolProp docs for python that explain how to use the conda package?  Thanks, that would be great.

**Comment by bryanwweber** [comment]
@danilomendesdias As I said over on the conda-forge PR, I think that only built for Python 3.6, not 3.7, so would not have encountered this issue.

@ibell It seems like the problematic version of Cython is 0.26.x and earlier; I built the sdist using Cython 0.27.2 and the compilation problem was resolved. The cpp files in the sdist indicate that they were built with Cython 0.26, and the pyx files are not included at all (there are pxd files though). If you could release a new sdist built with a more recent version of Cython, that would be extremely helpful! If not, I understand that releases can be a lot of work :smile: Thanks for all your effort on CoolProp!

I'll make a PR for the docs!

**Comment by ibell** [comment]
@jowr - any chance you can bump Cython on OSX-IPU-worker and fire off a tiny bugfix release?  That should resolve this issue for Python 3.7

**Comment by xhochy** [comment]
A cython update should be sufficient for the Python 3.7 support. From experience, it is best to simply use the latest release of Cython to build the C-files as Cython is only a build-time and not a runtime dependency. Thus there is normally no benefit in supporting old Cython releases.

**Comment by jowr** [comment]
I can do that. How can we test the files prior to making a new release?

**Comment by jowr** [comment]
OK, I updated cython from 0.26-py27_0 to 0.29.2-py27h0a44026_0 and I am going to make a new release as soon as #1762 is fixed as it covers some problems with the release procedure.

**Comment by jowr** [comment]
@bryanwweber The reason why you need `MACOSX_DEPLOYMENT_TARGET=10.9` is that your system does not support libstdc++, which was removed completely from XCode 10 (OSX 10.14). We use a default value of `-mmacosx-version-min=10.6`, which is basically the same as setting `MACOSX_DEPLOYMENT_TARGET=10.6` and your variable overrides our settings. 

I would suggest that we modify our default settings to `-mmacosx-version-min=10.9` as mentioned in #1778 .

**Comment by bryanwweber** [comment]
@jowr Yup, I thought the `MACOSX_DEPLOYMENT_TARGET` was a known thing. Incidentally, if you specify to build the Python wrapper with CMake, the default deployment target is 10.5. I'm not sure what your recommendation is regarding using CMake in the build process, but since the code is there, I thought I would mention it.

As for testing it, I would be happy to do that if you let me know when (and where) a nightly build is available!

**Comment by jowr** [comment]
Sorry for all the mess, but none of us is a professional programmer or a mac user...

The CMake code for the python wrappers is pretty deprecated and should be cleaned up or removed completely. 

You are more than welcome to try the very latest binaries using:
```
pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com:8010/unstable/Python/ -U --force-reinstall CoolProp
```

**Comment by jowr** [comment]
You have to scroll down to the bottom of this page http://www.coolprop.dreamhosters.com:8010/unstable/Python/

**Comment by ibell** [comment]
I believe this should be the one: 
http://www.coolprop.dreamhosters.com:8010/unstable/Python/CoolProp-6.2.2.dev0.tar.gz

**Comment by ibell** [comment]
And I think there is a command-line flag that forces pip to build from source: https://pip.pypa.io/en/stable/reference/pip_install/#install-no-binary 

This should be combined with the command from @jowr to yield:

```
pip install -no-binary -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com:8010/unstable/Python/ -U --force-reinstall CoolProp
```

**Comment by ibell** [comment]
I think...

**Comment by bryanwweber** [comment]
I can confirm the sdist that @ibell linked to (6.2.2.dev0) compiles on macOS, so presumably it should also work on Linux and Windows. Thanks for your quick attention! I will let you close this issue once the new release is made.

**Comment by ibell** [comment]
A+ Thanks for the feedback
