### ISSUE TITLE
Coverity gone?

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1788]
@jowr - Does coverity still exist?  The badge on the main page seems to be dead, and I can't track down where our builds might be.

**Comment by jowr** [comment]
It automatically pulls and builds the coverity branch. The branch is updated on a nightly basis. I'll have a look.

**Comment by ibell** [comment]
Right, but I don't think coverity scan exists at all anymore.  I can't see any reference to the product that we used before online.

**Comment by ibell** [comment]
That makes sense, I hadn't landed on that page.  So its a wait-and-see then.  I'm not holding my breath, but I think they had commercial users as well, so perhaps there is a bit of an impetus to get it back online from the people giving them money.

**Comment by jowr** [comment]
Coverity is back: https://scan.coverity.com/projects/coolprop
