### ISSUE TITLE
osx compile issues linking 

### ISSUE THREAD

**Issue by veeshy** [CoolProp/CoolProp#1790]
### Description

CoolProp stopped compiling at linking stage. 

### Steps to Reproduce

`cmake .. -DCOOLPROP_SHARED_LIBRARY=ON -DDARWIN_USE_LIBCPP=ON`

I get

[cp_err.txt](https://github.com/CoolProp/CoolProp/files/2757448/cp_err.txt)

I am able to compile with 9edec452df4f52f7d1b4cea77a22d74239e884a0 but not at fe7c8f180546861c28a2868dc22b7f75812046f2. Xcode 10.1 on 10.13 and 10.14 sees this issue.

Glancing at the cmake changes, I don't quite see what the big difference is other than nodefaultlibs flag. I tried removing that flag (w/o knowing much what it does..) and I can compile but my dependent libraries segfault when trying to use coolprop so I'm guessing it's important.

**Comment by ibell** [comment]
@jowr and I have been trying to nail down the right compiler flags for OSX for newer compilers, and I thought we had resolved all the issues, but evidently not.  What if you don't turn on ``DARWIN_USE_LIBCPP``?

**Comment by ibell** [comment]
Another useful bit of data would be if you could run ``otool -L librefprop.dylib`` (change name if needed), it will tell what libraries your library is linked against.

**Comment by veeshy** [comment]
CP compiles when DARWIN_USE_LIBCPP is not provided, however my library that links CP uses libc++ so I need CP with DARWIN_USE_LIBCPP. 

Turns out, when I removed the nodefaultlibs, I forgot to clean my dependent lib.. so CP compiles then is happy with my dependent library.

**Comment by ibell** [comment]
Hopefully @jowr can add some input here, but I also use OSX 10.14, and I have now gotten builds running fine (Python at least, which tends to be the trickiest to get working.  Is there a reason you don't statically link CoolProp? Static linkage avoids one family of linking errors, and you avoid runtime discovery of dynamic libraries, which has a whole other set of problems.

**Comment by veeshy** [comment]
I've got no good reason for using the dylib over static. I tried static coolprop and it works fine with no CMake edits. Thanks for that question. I'm happy closing this if you didn't have this issue using a typical osx compiler stack.

**Comment by jowr** [comment]
Did you delete the CMake cache? It looks like some old settings might get in your way.

You should **not** use those `DARWIN_USE_LIBCPP` switches unless really necessary. Your compiler selects the correct version automatically.

**Comment by veeshy** [comment]
Not using DARWIN_USE_LIBCPP lets me compile the shared lib too and works with my dependent lib. 

Seems worth it to warn or error when that flag is used?

**Comment by ibell** [comment]
Could do, but the flag is not documented, so most people wouldn't ever use it, I think.

**Comment by jowr** [comment]
I agree with @ibell. Once the recent changes are merged this should become a "no-issue". I close it now, please feel free to reopen, if you have any problems.
