### ISSUE TITLE
Wrong values ​​for r123

### ISSUE THREAD

**Issue by kaasio** [CoolProp/CoolProp#1796]
I´m a new user of coolprop inside matlab.

I know, Enthalpy and entropy are relative properties! You should always compare enthalpy differences rather than absolute values ​​of enthalpy or entropy.

I need to set reference values ​​through (set_reference_stateS).. however I have no idea how to do this set_reference_stateS anyone can help?

`FF = 'R123'

PropsSI('H', 'T', 383.15, 'Q', 1, FF)

ans =

   4.5903e+04`

**Comment by ibell** [comment]
Did you read this section of the docs: http://www.coolprop.org/coolprop/HighLevelAPI.html#reference-states ?

What version of CoolProp do you use?

**Comment by kaasio** [comment]
Hi,
As I'm a beginner, I can only use through matlab the  CoolProp version: 4.2.3

**Comment by ibell** [comment]
So you are running in version 6.2 in MATLAB now? Good news.

**Comment by kaasio** [comment]
no, I just managed to use it in version 4.2.5 =/

![capturar](https://user-images.githubusercontent.com/4822180/52180849-d95a6300-27c9-11e9-9f6e-f4c6213f8a68.PNG)

**Comment by kaasio** [comment]
Are these the files required for version 6.2?
![capturar](https://user-images.githubusercontent.com/4822180/52207066-06a32180-285b-11e9-97b9-6c3c9e41abbe.PNG)

When I import the command import py.CoolProp.CoolProp.PropsSI and I enter with PropsSI ('H', 'T', 383.15, 'Q', 1, 'R123') for example, I have the error :
Arguments to IMPORT must either end with ".*" or else specify a fully qualified class name: "py.CoolProp.CoolProp.PropsSI" fails
this test.

**Comment by kaasio** [comment]
I was able to use nava version with the last tip that gave. however when entered with

[v,e] = pyversion; system([e,' -m pip install --user -U CoolProp'])
import py.CoolProp.CoolProp.PropsSI

PropsSI('T','P',101325,'Q',0,'Water')


but in the initial entries I get the error..

Arguments to IMPORT must either end with ".*" or else specify a fully qualified class name: "py.CoolProp.CoolProp.PropsSI" fails this test.

after a few tries it runs perfectly, I can not identify the problem

**Comment by ibell** [comment]
I think you want to do in general:
``` matlab
py.CoolProp.CoolProp.PropsSI('T','P',101325,'Q',0,'Water')
```
 (without the import).  i seem to recall MATLAB changed their documentation.  Does that work reliably?

**Comment by kaasio** [comment]
With this command Without the import it worked perfectly and reliably.
thank you very much!

**Comment by ibell** [comment]
Good, I will fix the docs.

**Comment by jowr** [comment]
I guess this is solved
