### ISSUE TITLE
Error in enthalpy calculation for REFPROP::hydrogen

### ISSUE THREAD

**Issue by pdenboef** [CoolProp/CoolProp#1799]
### Description

For hydrogen, calculating the enthalpy from the internal energy and the density yields different values when using the HEOS routine and the REFPROP routine. 

### Steps to Reproduce

Open a Python interpreter (I used version 3.6).
Execute the following commands:

`from CoolProp.CoolProp import PropsSI`
`print(PropsSI('H', 'U', 2000000, 'D', 40, 'hydrogen')`
`print(PropsSI('H', 'U', 2000000, 'D', 40, 'REFPROP::hydrogen')`

**Expected behavior:**

`3447490.2318012617`
`3447490.2318012617`

**Actual behavior:** 

`3447490.2318012617`
`23781.053083347873`

The values are inequal. The first value, evaluated using HEOS, is correct.

### Versions

**CoolProp Version:** 6.2.1
**REFPROP Version**: 9.1.1.11
**Operating System and Version:** Windows 10 (64 bit)
**Access Method:** Python 3.6

**Comment by ibell** [comment]
Please see FAQ number 1: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md#usage .  Enthalpy and entropy are relative properties.
