### ISSUE TITLE
Fortran wrapper windows

### ISSUE THREAD

**Issue by rogerbar** [CoolProp/CoolProp#1800]
### Description

Following the istruction on coolprop.org website (http://www.coolprop.org/coolprop/wrappers/FORTRAN/index.html#fortran), i tried to compile (with MinGW) the examplef.for file on windows, with shared libraries method, after putting in the same folder the shared libraries (downloaded from https://sourceforge.net/projects/coolprop/files/CoolProp/6.2.1/shared_library/Windows/64bit/) I get the errore message "undefined reference to `propssi_' "

It seems like, even if the compiler can find the libraries, doesn't recognize the propssi call. I remember I got the same error message while using the fortran wrapper on linux, but in that case, if I remember correctly, I wasn't giving the correct library path with the command "LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH". On windows this is supposed to be unnecessary, so which can the problem be?

### Steps to Reproduce

1. Have all the common wrappers presequisite
2. Download shared libraries from https://sourceforge.net/projects/coolprop/files/CoolProp/6.2.1/shared_library/Windows/64bit/
3. Compile "gfortran -g -o examplef.for -L. -lCoolProp

**Expected behavior:** compiling
**Actual behavior:** "undefined reference to `propssi_' "

### Versions

**CoolProp Version:** 6.2.1
**Operating System and Version:** Windows 10 64bit
**Access Method:** Fortran

**Comment by ibell** [comment]
You need to build the shared library of CoolProp yourself, otherwise the binaries are not compatible if you take the MSVC-compiled shared library from the website and try to link against it from gfortran.  

You could, at first, try to use the libCoolProp.dll and libCoolProp.a files from https://sourceforge.net/projects/coolprop/files/CoolProp/6.2.1/shared_library/Windows/64bit/ , which were compiled with mingw suite, but no guarantee that will work.

**Comment by rogerbar** [comment]
I compiled my own libraries, I got the files **libCoolProp.dll** and **libCoolProp.dll.a** (everything seemed to work fine).
But I still got the same error: _undefined reference to `propssi_'_
Any idea on why this happens?

**Comment by ibell** [comment]
Not easy to know without more information.  Can you please post complete shell output for all steps of your attempted build?

**Comment by rogerbar** [comment]
The three files attached are the steps I follow to get the .dll libraries (from http://www.coolprop.org/dev/coolprop/wrappers/SharedLibrary/index.html#shared-library)

[build.txt](https://github.com/CoolProp/CoolProp/files/2916810/build.txt)
[download sources.txt](https://github.com/CoolProp/CoolProp/files/2916811/download.sources.txt)
[generate build file.txt](https://github.com/CoolProp/CoolProp/files/2916812/generate.build.file.txt)

**Comment by ibell** [comment]
That all seems fine. How about the same thing for your fortran build?  For future reference, its easier if you just put it all in the issue in set of triple backticks.

**Comment by rogerbar** [comment]
I am not sure I understood what you asked. Did you ask the compiling process and the error I get? If yes, this is it:
_gfortran ./examplef.for -L. -lCoolProp
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Antonio\AppData\Local\Temp\ccs0ewIr.o:examplef.for:(.text+0x213): undefined reference to `propssi_'
collect2.exe: error: ld returned 1 exit status_

**Comment by ibell** [comment]
I went back in and looked how this is handled in in our testing system(http://www.coolprop.dreamhosters.com:8010/builders/Fortran-executable-windows-2-GCC-ExternC/builds/90), and it looks like one little thing is missing.  On the build system, we do the following steps:
```
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON -DCOOLPROP_EXTERNC_LIBRARY=ON -DFORCE_BITNESS_64=ON -G "MinGW Makefiles"
cmake --build .
gfortran -c -Wall cpinterface.f90 cool_fortran_bind.f90 -m64
gcc -o main cpinterface.o cool_fortran_bind.o libCoolProp.a -lstdc++ -lgfortran -m64
```

So, now that I remember, I think the ``-DCOOLPROP_EXTERNC_LIBRARY=ON `` might be necessary, and in fact that is mentioned in the docs: http://www.coolprop.org/coolprop/wrappers/FORTRAN/index.html#build-static-library-of-coolprop

**Comment by rogerbar** [comment]
So, to generate the build file I used
`cmake .. -DCOOLPROP_EXTERNC_LIBRARY=ON -DCOOLPROP_SHARED_LIBRARY=ON -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release`
and then the build, but I still get the same error :/

**Comment by ibell** [comment]
@jowr - any idea? I'm blanking since I don't use fortran basically ever.

**Comment by henningjp** [comment]
Is it a decorator mismatch? Sometimes, depending on the interface flag set on the compiler, there will be one or two underscores on the function name.  If the Fortran and C aren’t using the same, the linker won’t find the function name as it’s missing, or has an extra underscore on the interface name.  Just a thought.

**Comment by rogerbar** [comment]
The CoolProp libraries call inside the _example.for_ file is
`call propssi(Output, Name1, Prop1, Name2, Prop2, Ref, outVal)`
and returns the error
`c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Antonio\AppData\Local\Temp\ccYIiB8U.o:examplef.for:(.text+0x213): undefined reference to `propssi_'
collect2.exe: error: ld returned 1 exit status`

Changing the call to
`call propssi_(Output, Name1, Prop1, Name2, Prop2, Ref, outVal)`
the error becomes
`$ gfortran examplef.for -L. -lCoolProp
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: C:\Users\Antonio\AppData\Local\Temp\ccxwxXke.o:examplef.for:(.text+0x213): undefined reference to `propssi__'
collect2.exe: error: ld returned 1 exit status`

The new error is with two underscores, so maybe something should be changed before compiling the libraries?

**Comment by henningjp** [comment]
Yeah, the compiler adds the underscore decorator.  That shouldn’t be done in the source.  The compilers have to be using the same convention. This is probably taken care of properly in the cmake script.  It was just a thought for @ibell.  I know I’ve gotten these kinds of errors if they don’t match.

**Comment by ibell** [comment]
The best thing would be to make a small CMake project to link everything
together reliably, but at the moment, I don't have any windows-based
machines easily accessible for testing this.  In the end, it's a 10-line or
so CMake script.  I could do this in linux or OSX and then we'd have to
assume that everything is going to work on windows.  But I could try that.
Let's see.

**Comment by ibell** [comment]
Tested this on linux, should work in MinGW I believe: https://github.com/CoolProp/coolprop_fortran77.

**Comment by rogerbar** [comment]
Should I download the .zip file and put all the files in the CoolProp folder (downloaded with `git clone https://github.com/CoolProp/CoolProp --recursive`) and then try to compile the libraries in a new folder called build with
`Antonio@DESKTOP-8GHP8C3 /c/Users/Antonio/Desktop/CoolProp/build
$ cmake .. -DCOOLPROP_SHARED_LIBRARY=ON -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 8.2.0
-- Check for working Fortran compiler: C:/MinGW/bin/gfortran.exe
-- Check for working Fortran compiler: C:/MinGW/bin/gfortran.exe  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether C:/MinGW/bin/gfortran.exe supports Fortran 90
-- Checking whether C:/MinGW/bin/gfortran.exe supports Fortran 90 -- yes
CMake Error at CMakeLists.txt:7 (add_subdirectory):
  The source directory

    C:/Users/Antonio/Desktop/CoolProp/externals/coolprop

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "C:/Users/Antonio/Desktop/CoolProp/build/CMakeFiles/CMakeOutput.log".`

There is a problem with the new CMakeLists.txt file, but I couldn't find it. 
Why does this error happens?
(P.S. thank you for the support)

**Comment by ibell** [comment]
Nope, you should run precisely the commands that I put in the readme.  This
is how you should structure your project in general.  (I think you might
need to CD into coolprop_fortran77 instead of coolprop_fortran)

**Comment by rogerbar** [comment]
Now I got an error from the build, which is the same error I got before. 
Attached the console output.
[log.txt](https://github.com/CoolProp/CoolProp/files/2950034/log.txt)

**Comment by ibell** [comment]
Do you ave to use FORTRAN 77 standard? That's more than 40 years ago. If you use FORTRAN 2003, the cpinterface should work seamlessly.  Getting FORTRAN to play nicely with others is always a challenge.

**Comment by ibell** [comment]
Is it possible to see what symbols have been output in the DLL?  You can use a tool like dependency walker to see what symbols have been output: http://www.dependencywalker.com/.  Weird that it works fine on linux, but not with mingw, which is basically the same thing in a lot of respects.

**Comment by rogerbar** [comment]
I have to use FORTRAN 77 because I have a  FORTRAN 77 code, which is quite complex, and I'm just adding the CoolProp libraries to it.

Attached you can see the dependency walker output. The strangething is that the call should be propssi_ and the error I get is "undefined reference to propssi_", which is exaxctly as it should be...
![dependency](https://user-images.githubusercontent.com/47272892/54118630-c3a51280-43f3-11e9-9d49-ba8786576b85.png)

**Comment by ibell** [comment]
Are you intending to build for 32-bit or not?   You ended up with stdcall name mangling which says you did a 32-bit compilation.  If you want to guarantee a 64-bit build, you can pass this flag to cmake build command https://github.com/CoolProp/CoolProp/blob/master/CMakeLists.txt#L51-L53 .  I just assumed it was 64-bit because everything is nowadays.

**Comment by rogerbar** [comment]
My intentions are to build for 64-bit.
So should I change 
`option (FORCE_BITNESS_64
       "Force a 64bit build regardless of the host"
OFF)`
to
`option (FORCE_BITNESS_64
       "Force a 64bit build regardless of the host"
OFF)`

?

**Comment by ibell** [comment]
No, you should pass it at the command line, as you did with
CMAKE_BUILD_TYPE, for instance, something like -DFORCE_BITNESS_64=ON .  I
think the MINGW you have installed is 32-bit only.  What compiler do you
use for your FORTRAN77 code?

**Comment by rogerbar** [comment]
I checked, and the compiler I use is MinGW 32 bit, even if my OS is 64 bit.
I tried to compile the libraries in the standard way (from [http://www.coolprop.org/dev/coolprop/wrappers/SharedLibrary/index.html#shared-library](url)), but with 32 bit options. I still get the same error.

Any advice?

**Comment by ibell** [comment]
Have you tried to specify one of the calling conventions: http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#user-compiled-binaries ?  Probably you want the one that reads -DCOOLPROP_CDECL_LIBRARY=ON.  Your dependency walker output says you had a stdcall calling convention.

**Comment by rogerbar** [comment]
Ok, it worked.
The problem was that I was compiling 64bit libraries but, even if my pc has a 64bit processor, MinGW is 32bit. So with the standard procedure for 32bit "`cdecl`" call it works (following the steps on [CoolProp shared libraries](http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#user-compiled-binaries))

Thank you very much for the support.

**Comment by ibell** [comment]
Ok, good to hear!
