### ISSUE TITLE
Issue with javascript Wrapper

### ISSUE THREAD

**Issue by Froudd** [CoolProp/CoolProp#1801]
### Description

When I try the html-Javascript example, I get two errors: 
1- abort("No WebAssemlby support found. Build with -s WASM=0 to target Javascript instead.")
2- Object doesn't support property or method 'PropsSI' (using Edge) or Module.PropsSI is not a function (Firefox and Chroms)

### Steps to Reproduce

1. Either go to 'http://coolprop.sourceforge.net/jscript/index.html' or download and launch locally the html file from 'https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/Javascript/index.html'
2. Enter value and click on Calculate

**Expected behavior:**
The example used to work fine.

**CoolProp Version:**"http://www.coolprop.sourceforge.net/jscript/coolprop.js"

![javascriptwrapperissue](https://user-images.githubusercontent.com/22819030/53083554-7245e980-34ff-11e9-9c0a-6c922ff6897c.png)

**Comment by ibell** [comment]
Yeah, we're having problems with js.  At the very least, you'll need to
host the files locally, and can't run the html file directly.  I use this
as a simple hosting in Python (
https://docs.python.org/3.6/library/http.server.html?highlight=http%20server#module-http.server
bottom of page):

python -m http.server 8000 --bind 127.0.0.1

**Comment by Froudd** [comment]
Thank you for your quick reply.

All the best
