### ISSUE TITLE
Why has 0.3 degC diff between CoolProp.HumidAirProp and Daikin Psychrometric Diagram When calculating Twb with Tdb&RH&Bar.

### ISSUE THREAD

**Issue by gas0189** [CoolProp/CoolProp#1808]
```
>>> from CoolProp.HumidAirProp import HAPropsSI
>>> HAPropsSI('Twb','P',101325,'Tdb',273.15,'R',0.365)-273.15
-3.84217185513387
```

**Twb = -3.84 degC**, when using CoolProp.

But **Twb = -3.5 degC**, when using _Daikin Psychrometric Diagram_. 
There is **10% diff** between them.

<img width="579" alt="搜狗截图20190314220831" src="https://user-images.githubusercontent.com/23023534/54363973-fd517400-46a6-11e9-935d-9be46975d7fd.png">

And [CoolProp](https://sourceforge.net/projects/coolprop/) mentioned :

> In addition, calculations for Humid Air Properties based on **ASHRAE RP-1485** are provided.

Does anyone use the LibHuAirProp which also based on **ASHRAE RP-1485**?
And can you give me the Twb result calculated by LibHuAirProp.
So, maybe we can find the answer. 

THANKS!

**Comment by ibell** [comment]
Without knowing what model was implemented in Daikin software, my guess is that the numbers in CoolProp are more correct.  It is common to make some simplifying assumptions for humid air near atmospheric conditions and I bet their numbers are shifted as a result.  Can you find some documentation on their modeling approach?

**Comment by gas0189** [comment]
Sorry, I have nothing about the Daikin modeling approach.
I just use that software as my tool.

I think it can proof CoolProp is right if having the same result with LibHuAirProp lib.

**Comment by ibell** [comment]
You can do calculations with LibHuAir here: https://web1.hszg.de/thermo_fpc/index.php

**Comment by gas0189** [comment]
@ibell ， Thanks.

With [the LibHuAir online calculator](https://web1.hszg.de/thermo_fpc/index.php),
![搜狗截图20190315110753](https://user-images.githubusercontent.com/23023534/54405801-9ff30c80-4712-11e9-8fc4-95a921d1bf82.jpg)

With the CoolProp,
```
>>> from CoolProp.HumidAirProp import HAPropsSI
>>> HAPropsSI('R', 'Tdb', 273.15, 'W', 1.4/1000, 'P', 101325) * 100 
37.08060804640256
>>> HAPropsSI('Twb', 'Tdb', 273.15, 'W', 1.4/1000, 'P', 101325) - 273.15 
-3.80481321822964 
>>> HAPropsSI('R', 'Tdb', 273.15, 'Twb', 273.15-3.805, 'P', 101325) * 100
37.077702408199734
```

I know that **CoolProp has the same results as LibHuAir**.

With the Daikin software,
![搜狗截图20190315111520](https://user-images.githubusercontent.com/23023534/54406061-a1710480-4713-11e9-9deb-4011d1f88f05.jpg)

**Comment by ibell** [comment]
Can we close this issue now?

**Comment by gas0189** [comment]
ok

2019-03-19 


舒国安
13515604873



发件人：Ian Bell <notifications@github.com>
发送时间：2019-03-19 11:54
主题：Re: [CoolProp/CoolProp] Why has 0.3 degC diff between CoolProp.HumidAirProp and Daikin Psychrometric Diagram When calculating Twb with Tdb&RH&Bar. (#1808)
收件人："CoolProp/CoolProp"<CoolProp@noreply.github.com>
抄送："gas0189"<gas0189@163.com>,"Author"<author@noreply.github.com>

Can we close this issue now?
