### ISSUE TITLE
Humid air properties above 388 K

### ISSUE THREAD

**Issue by gusbonolo** [CoolProp/CoolProp#1811]
Dear developers,

I`m using CoolProp high-level functions through Scilab and a problem emerged. According to the web site the properties of humid air are valid within -143.15 and 350 °C. However, the solutions for temperature close to the limits do not make sense. For instance, when the pressure is 101.33kPa and the temperature is 200K, the calculated enthalpy is -73574. On the other end, when the temperature is above 390K the enthalpy value also becomes negative. I hope you could help me figure out what is happening. 

Best regards,
Gustavo Bonolo de Campos

**Operating System and Version:** Windows 10 
**Access Method:** Scilab wrapper

**Comment by ibell** [comment]
Can you please show the inputs and outputs from your code?  Without that
it's hard to guess what you did

**Comment by gusbonolo** [comment]
Sure, the following image shows the enthalpy becomes negative for temperature above 390K. I tried using both libraries available (CoolProp and libCoolProp.

![image](https://user-images.githubusercontent.com/48517712/55240160-7f5da300-5238-11e9-8f1e-52570b36b013.png)

**Comment by ibell** [comment]
Do the humidity ratios you get make sense?  Somehow I doubt it.

**Comment by jowr** [comment]
```
// In MoleFractionWater
p_ws = 179638.08455660721 | double
W = -10.380389368117866 | double
// afterwards
psi_w = 1.0637340314232848 | double
HumidAir::HumidityRatio returned | -10.380389368117852 | double
```

**Comment by ibell** [comment]
Something about a negative humidity ratio seems a bit fishy to me :)

**Comment by jowr** [comment]
I guess it should throw an error since p_ws * RH is greater than p.
