### ISSUE TITLE
REFPROP specific heat calculations fail for REFPROP::R407A.MIX under certain conditions

### ISSUE THREAD

**Issue by dshen109** [CoolProp/CoolProp#1812]
### Description

Calculating specific heat fails for the REFPROP R407A mixtures and returns a negative value when close to saturated liquid state. 

### Steps to Reproduce
```
In [25]: PropsSI("C", "H", 239967.95, "T", 300.19, "REFPROP::R407A.MIX")                                                                                                                                    
Out[25]: 1533.910355451634

In [26]: PropsSI("C", "H", 239967.95, "T", 300.18, "REFPROP::R407A.MIX")                                                                                                                                    
Out[26]: -110974350.3437588


In [34]: PropsSI("P", "H", 239967.95, "T", 300.18, "REFPROP::R407A.MIX")                                                                                                                                    
Out[34]: 1322524.8827676931

In [35]: PropsSI("P", "H", 239967.95, "T", 300.19, "REFPROP::R407A.MIX")                                                                                                                                    
Out[35]: 1345070.5217287987

```

Changing the temperature input by 0.01 causes the specific heat to become negative. This discontinuous behavior is not shown when other properties are requested.

### Versions

**CoolProp Version:** [v6.2.1]  
**Operating System and Version:** [Ubuntu 16.04]  
**Access Method:** [iPython]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
My guess, though it's hard to know without more debugging, is that REFPROP has jumped to the other density root.  TH inputs (among a few others) are annoying in that it is possible to have multiple density solutions for a TH pair.  This is why I have always avoided TH inputs, and why they are not implemented in CoolProp.  PH inputs do not show this "feature" and I would recommend that you do calculations with PH as inputs if possible.

REFPROP allows you to specify which density root you want, but that ability is not exposed in the CoolProp wrapper.  We could add that ability if that was something that you could not find an alternative solution for.

**Comment by dshen109** [comment]
@ibell thanks, that's good to know. Do you know of any literature that describes which inputs have multiple roots (like TH) and which ones do not (like PH)?

**Comment by ibell** [comment]
Nope, I'm afraid I don't know of any reference in particular that describes
this.  To my knowledge, the functions in REFPROP that require a density
specification are TU and TH, and no others. See for instance
https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ABFLSHdll,
where it hints that only TE and TH inputs require the kr flag
