### ISSUE TITLE
Version 6.3

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1816]
I think a release of 6.3 is warranted, since I added a new refrigerant and updated some fluid EOS.

Also, this bug is rather serious: #1815 

One think that I think I would ideally like to see for this release is a tutorial on how to add incompressible fluids to CoolProp.  I've had a couple of people ask me about that recently, and I have to admit that I couldn't figure out what all the steps are.  @jowr do you think you could add that to the docs?  Don't have to go too crazy, just a short demo for a fluid with a simple set of data.

**Comment by jowr** [comment]
I can write the documentation, but it is not going to happen next week. I suggest to schedule this issue for v6.3.1 since it is only a change in the documentation.

**Comment by ibell** [comment]
Sorry, I hadn't meant to imply that we should delay 6.3 based on the docs for the incompressible fluid addition, only that it would be nice to have them at some point.  Don't sweat it.

**Comment by ibell** [comment]
See b5c79169b51a11bcaad68974d0d7f451adf1a7d3

**Comment by jowr** [comment]
Since #1754 does not depend on the release process, shouldn't we just release v6.3.0?

**Comment by ibell** [comment]
Agreed.  Fire when ready.

**Comment by jowr** [comment]
Things left to do:
- [ ] Fix Humid air examples #1820 
- [ ] Modify release checklist in docs (and fix GitHub API calls)
- [ ] Handle Python 2.7 builds - they probably fail due to the new incompressible scripts
