### ISSUE TITLE
Humid air example fails due to new limits

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1820]
The recently introduced limits for the HAPropsSi cause the examples to fail ungracefully. This should be fixed be fore we release 6.3.0.

**Comment by ibell** [comment]
I guess this also borks the verification code: http://www.coolprop.org/dev/fluid_properties/HumidAir.html#verification-script ?

**Comment by jowr** [comment]
Are you aware of the fact that 30% of the calls in the verification script yield "NaN" or a difference in psi_w larger than 1e-8?

**Comment by ibell** [comment]
:( no I didn't know that.  Is that before the fixes to the boundaries?

**Comment by jowr** [comment]
v6.2.1 yields 24% with errors or large deviations, after adding the limits we reached 31%.

**Comment by ibell** [comment]
How about 6.3 without the limit fix?  I thought that was 100% success rate?

**Comment by ibell** [comment]
I pushed a fix to the limits function (max and min were flipped for the
default), but some issues remain.  When I disable limits checking, I get
zero failures again.

**Comment by jowr** [comment]
Two things: 

- There is a branch for this issue with many fixes. Please do not edit the master. 

- I am not sure what you mean with success rate. As far as I can see you only check for exceptions and not for faulty results. That is where the problem is. 

As I said, I checked v6.2.1, which is without the limits and it also yields over 20% percent of wrong results. 

Neither the branch “issues/1820” nor v6.2.1 produce any exceptions.

**Comment by ibell** [comment]
Argh, sorry, I didn't realize there was a branch for this issue, should
have looked into that.  I'll work on the branch in the future.

But on the question of the verification script, I'm rather confused.  I
added a check in the script to throw exceptions (in Python) when the value
is not a valid number.  That still throws no exceptions for me...

**Comment by jowr** [comment]
You can check the CPP example in the “dev/tickets” folder. There is a counter for faulty results that are neither NAN nor exceptions.

**Comment by ibell** [comment]
Indeed I see what you mean.  Boy these tests take forever ...

**Comment by ibell** [comment]
All fixed.   Tests are faster now too.
