### ISSUE TITLE
CoolProp unable to load REFPROP (v10) mixtures on Windows 10

### ISSUE THREAD

**Issue by shanknatesh** [CoolProp/CoolProp#1835]
### Description

When calling REFPROP mixture (R404.mix), I obtain the following error:

`ValueError: Initialize failed for backend: "REFPROP", fluid: "R404.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R404.MIX : PropsSI("T","P",1597271.854,"Q",0,"REFPROP::R404.MIX")`

### Versions

**CoolProp Version:** 6.3.0
**Operating System and Version:** Windows 10  
**Access Method:** Python

**Comment by ianhbell** [comment]
Please show your entire code that you used to reproduce this error.  Did you set the path for REFPROP? http://www.coolprop.org/coolprop/REFPROP.html#path-issues

**Comment by shanknatesh** [comment]
`import CoolProp.CoolProp as CP
from CoolProp.CoolProp import PropsSI
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH,'c:\\Program Files (x86)\\REFPROP\\')
CP.get_global_param_string("REFPROP_version")
REFG = 'REFPROP::R404.MIX'
# test REFPROP first
h = PropsSI('H', 'P', 1e5, 'T', 288, REFG)`

`ValueError                                Traceback (most recent call last)
<ipython-input-1-40069acc5838> in <module>
      4 CP.get_global_param_string("REFPROP_version")
      5 REFG = 'REFPROP::R404.MIX'
----> 6 h = PropsSI('H', 'P', 1e5, 'T', 288, REFG)

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.__Props_err2()

ValueError: Initialize failed for backend: "REFPROP", fluid: "R404.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R404.MIX : PropsSI("H","P",100000,"T",288,"REFPROP::R404.MIX")`

Yes, I set path for REFPROP. The mixtures are located in "C:\Program Files (x86)\REFPROP\MIXTURES".

**Comment by ianhbell** [comment]
I cleaned up the formatting of your issue, checking the preview can be helpful to see what it will look like.

What does this return: ``print(CP.get_global_param_string("REFPROP_version"))``

**Comment by ianhbell** [comment]
What version of CoolProp do you use?

**Comment by shanknatesh** [comment]
> I cleaned up the formatting of your issue, checking the preview can be helpful to see what it will look like.
> 
> What does this return: `print(CP.get_global_param_string("REFPROP_version"))`

`CP.get_global_param_string("REFPROP_version")`

`n/a`

It is weird because it was outputting '10.0' before.

**Comment by shanknatesh** [comment]
> What version of CoolProp do you use?

v6.3.0.

**Comment by ianhbell** [comment]
Do you get any additional shell output?  If REFPROP doesn't load properly, there should be stuff printed to the console.

I use REFPROP via CoolProp/Python all the time.

**Comment by shanknatesh** [comment]
```
ValueError                                Traceback (most recent call last)
<ipython-input-8-5cba4867f7e8> in <module>
      7 REFG = 'R404.MIX'
      8 # test REFPROP first
----> 9 h = PropsSI('H', 'P', 1e5, 'T', 288, REFG)

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.__Props_err2()

ValueError: Initialize failed for backend: "?", fluid: "R404.MIX" fractions "[ 1.0000000000 ]"; error: key [R404.MIX] was not found in string_to_index_map in JSONFluidLibrary : PropsSI("H","P",100000,"T",288,"R404.MIX")

```

**Comment by ianhbell** [comment]
Yes, that is now calling the internal routines of CoolProp, which is probably not what you want...

**Comment by shanknatesh** [comment]
Does CoolProp need to know the location of the MIXTURES and FLUIDS folders?

**Comment by ianhbell** [comment]
In theory, no, the location of the REFPROP root should suffice.

**Comment by ianhbell** [comment]
It's a typo....  Should be R404A.MIX, not R404.MIX.
