### ISSUE TITLE
Problem: ZERO speed of sound error in two-phase region along isentrope for co2 (carbon dioxide)

### ISSUE THREAD

**Issue by ragnar2015** [CoolProp/CoolProp#1836]
PROBLEM: ZERO speed of sound error in two-phase region along isentrope for co2 (carbon dioxide)

Coolprop 6.3 (latest download of Excel dll and xlam) run on Windows 7 and latest Excel 365.

A test case observation:

Looking at expansion of initially supercritical CO2 (at 4500 psia and T=150F) along an isentrope into the saturated side of the vapor dome. Once inside the vapor dome, CoolProp computes odd two-phase behavior including zero values of speed of sound.

At supercritical state with P=4500 psia (31,026,420 Pascal) and T=150F (338.7056K). 
Entropy=1290.973 J/kg-K (or 0.30834 btu/lbm-R)
Here CoolProp speed of sound "A" = 1759.74 ft/s

Dropping P_psia by 100 psi increments while holding entropy constant, values of Ts and A are generated by CoolProp thusly:
Ts_degF = PropsSI("T","P",P_psia*6894.76,"S",1290.973,gas)*1.8-459.67
A_fps   = PropsSI("A","P",P_psia*6894.76,"S",1290.973,gas)*3.2808

A plot of A vs P shows A smoothly decreasing until about 1000 psia then 
the speed of sound "A_fps" changes quickly below P=1000 psia (P decrement then changed to 10 psi).

Note the ZERO values computed at P = 950, 940, 930, 920 psia. 
Then A_fps quickly increases again.

Here are some values:
p = psia
Ts = deg F
A_fps = ft/s

P        Ts         A_fps   Phase_index    Phase
1500 97.74  1069.2  1    supercritical
1400 95.04  1024.9  1    supercritical
1300 92.18  975.2   1    supercritical
1200 89.13  919.4   1    supercritical
1100 85.83  855.6   3    supercritical_liquid
1000 82.18  764.1   0    liquid
990	 81.64  727.2   6    two_phase
980  80.84  629.5   6    two_phase
970	 80.03  487.5   6    two_phase
960	 79.22  279.8   6    two_phase
950	 78.40  0.0     6    two_phase   <NOTE ZERO speed of sound
940	 77.57  0.0     6    two_phase
930	 76.73  0.0     6    two_phase
920	 75.89  0.0     6    two_phase
910	 75.03  183.6   6    two_phase
900	 74.17  402.6   6    two_phase
890	 73.30  581.0   6    two_phase
880	 72.43  751.3   6    two_phase
870	 71.54  920.0   6    two_phase
860	 70.65  1088.2  6    two_phase

![image](https://user-images.githubusercontent.com/11840318/60044701-f3b9ae00-9690-11e9-9684-836a112e859f.png)

Question:  Is this expected behavior? 

Zero speed of sound is not expected nor the dramatic drop then increase in two-phase dome as pressure is dropped at constant entropy.

Plots (not shown) of enthalpy and temperature at each pressure and constant entropy are continuous and well behaved curves.

Thanks in advance...

**Comment by ibell** [comment]
There are two speed of sound, one for the liquid, another for the vapor,
and various methods for handling speed of sound for mixtures (e.g. section
3.3 of
https://pdfs.semanticscholar.org/24ce/579326561e02fa23b1517504e5b083767a7d.pdf).
CoolProp doesn't do anything brilliant, it just evaluates the homogeneous
speed of sound in the two-phase region. That's only one possible answer to
the question of what the speed of sound of the mixture.

P.S. You're more likely to get a response if you do your calculations in SI
units.

**Comment by ragnar2015** [comment]
Ian, thanks for your reply.  I can easily repost in SI. Do you prefer an edit to this #1836 issue (with the long "edit" block" or close this one and pull a new issue number?

**Comment by ragnar2015** [comment]
PROBLEM: ZERO speed of sound error in two-phase region along isentrope for co2 (carbon dioxide)
Original post converted to SI units.

Coolprop 6.3 (latest download of Excel dll and xlam) run on Windows 7 and latest Excel 365.

A test case observation:

Looking at expansion of initially supercritical CO2 (at 31MPa and T=339K) along an isentrope into the saturated side of the vapor dome. Once inside the vapor dome, CoolProp computes odd two-phase behavior including zero values of speed of sound.

At a supercritical state with P=31MPa and T=339 deg K.
Entropy= 1292.875 J/kg-K  . Here CoolProp speed of sound "A" = 535.06 M/s

A plot of sound of speed (m/s) vs pressure (kPa) at constant entropy=1292.875 J/kg-K was generated and posted below.

Pressure "P_pascal" was decremented by 1MPa deltas while holding entropy constant until the left side of the two-phase dome was approached. Then the pressure delta was reduced for more detail within the vapor dome.

Values of A were generated by CoolProp thusly:
s_si = 1292.875  	# (J/kg-K)
A_mps   = PropsSI("A","P",P_pascal,"S",s_si,gas)     # (M/S) speed of sound

The attached plot of CO2 speed of sound "A" vs P shows "A" smoothly decreasing until about 6850 kPa then the speed of sound "A_mps" changes quickly below P=6850 kPa (P decrement then changed to 68.9476 kPa).

Note that ZERO values are computed at these representative pressures:
6574.2096 kPA
6505.262 kPA
6436.3144 kPA
6367.3668 kPA

Then A_mps quickly spikes upward then downward..

![image](https://user-images.githubusercontent.com/11840318/60105345-2915d880-9731-11e9-9209-83290572cc14.png)

Question: Is this expected behavior?

Zero speed of sound is not expected nor the dramatic fluctuations in two-phase dome as pressure is dropped at constant entropy.

Plots (not shown) of enthalpy and temperature at each pressure and constant entropy are continuous and well behaved curves.

Thanks in advance...

**Comment by ibell** [comment]
Did you read my former message?  How do you want to define two phase speed
of sound?  There are multiple definitions

**Comment by ragnar2015** [comment]
I did read your post but not the journal paper just yet (I will). The key issue to tackle first is why zero values for co2 speed of sound were returned for a narrow range of pressure at constant entropy (that was within the dome). Might be some algorithm issue. I looked at the REFPROP saturation table for CO2 in the problematic pressure range and the liquid and vapor values of speed of sound look reasonable.

**Comment by ibell** [comment]
The way that CoolProp evaluates speed of sound for two-phase mixtures of pure fluids is that it plugs in the temperature and density directly into the EOS to evaluate the speed of sound, as though the fluid were homogeneous, which it DEFINITELY is not.  That's why you see all manner of weird behavior.  If the state were metastable, you would likely get sensible speed of sound for well constructed EOS.  Inside the spinodal (the unstable part of the two-phase region), all bets are off.

Comparing with REFPROP is a good idea; I'm not sure how REFPROP handles speed of sound for two-phase states.  I think it gives you an answer when it shouldn't, but I'll check.  But make sure that you are doing a one-to-one comparison test.  Best to not use entropy or enthalpy as your input variable when doing the test to avoid possible issue with reference states.

**Comment by ragnar2015** [comment]
Refprop does not compute speed of sound within the dome. Phase is identified as "2-Phase" but "Sound Speed" returns "undefined". 

Linear interpolation of sound speed across the dome at a pressure using the input constant entropy value between the entropies of the liquid and vapor saturation states might be a usable method for CoolProp. A thermodynamicist may object to the simplicity of it (ie it is not a theoretical calc).

**Comment by ibell** [comment]
I think REFPROP's behavior is correct on this point.

**Comment by ibell** [comment]
Two-phase speed of sound are no longer allowed.

**Comment by thorade** [comment]
Also discussed in detail here:
https://doi.org/10.1007/s00193-019-00896-1
