### ISSUE TITLE
Temperature limits of the EOS of R-1234yf quite low

### ISSUE THREAD

**Issue by somniumAeternam** [CoolProp/CoolProp#1840]
The following call fails with CoolProp 6.3:

```python
PropsSI('T', 'H', 500000, 'S', 1800, 'R1234yf')
```

The error message corresponds to the maximum temperatur of the EOS of 410K
```python
ValueError: HS inputs correspond to temperature above maximum temperature of EOS [410 K] : PropsSI("T","H",500000,"S",1800,"R1234yf")
```

With the Refprop interface this call is working:
```python
PropsSI('T', 'H', 500000, 'S', 1800, 'REFPROP::R1234yf')
458.66080683750533
```

**Comment by ibell** [comment]
I'm not sure if refprop is really working.  Check out the temperature you
got back...  Is this a reference state issue?

>

**Comment by somniumAeternam** [comment]
The reference state is identical. The absolute values for h, s and T are also almost identical. I don't really know, why it is failing, because the following calls are working:

```python
PropsSI('T', 'H', 500000, 'P', 8000000, 'R1234yf')
PropsSI('S', 'H', 500000, 'P', 8000000, 'R1234yf')
```

```python
459.3709141034945
1799.0526697113667
```

I think, there is a problem with the input pairs H and S

**Comment by ibell** [comment]
You're well above the max temp of the EOS, so I'm not surprised that you
are having a tricky time.

Also, HS inputs are the trickiest of them all.  Can you provide a guess
value for the temperature and density?  If so, you might be better off
doing the iteration yourself and only using the model in CoolProp, but not
the algorithms.

**Comment by somniumAeternam** [comment]
I close the issue as the corresponding limit is quite clear and the EOS is not valid after that point.
