### ISSUE TITLE
PIP as input parameter

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#1846]
#659 and #658 added PIP as an output parameter.
The table of parameter strings for the high-level interface lists it as output parameter:
http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function

For research and plotting, it would be nice to also have PIP (especially PIP=0) as input parameter.

This of course has very low priority, I just filed it here to not forget the idea.

**Comment by ibell** [comment]
PIP as an output is nice and easy, PIP as an input has all the challenges of the other flash routines.  Interesting idea, but I'm not going to be able to contribute to it.
