### ISSUE TITLE
PR density calc fail

### ISSUE THREAD

**Issue by ianhbell** [CoolProp/CoolProp#1848]
PR backend fails for high pressure where it should succeed according to plotting the isotherm

fluid: Argon
Unable to find gaseous density for T: 423.11 K, p: 2.7786e+07 Pa

**Comment by thorade** [comment]
By coincidence I read this related paper few days ago:
https://doi.org/10.1021/ie4038664

**Comment by ibell** [comment]
Closed by 14be8e29fa5aec5ce069ca9ec5e4026e6c5c38a9
