### ISSUE TITLE
Lazarus examples dont work

### ISSUE THREAD

**Issue by Mol3culo** [CoolProp/CoolProp#1853]
Hello for everyone. I try to use coolprop with lazarus, but my programs dont work, I have error 000007b on application start. I have similar issues with delphi/lazarus examples officially published on the coolprop site.
For example this dont work:
```
program project1;

CONST
  COOL_PROP = 'CoolProp.dll';

  function PropsSI(Output: PAnsichar; Name1: PAnsichar; Prop1: Double; Name2: PAnsichar; Prop2: Double; FluidName: PAnsichar): Double; stdcall; external COOL_PROP name '_PropsSI@32';
var
  h: Double;
begin
     h:=PropsSI('H', 'T', 300, 'P', 101325, 'R134a');
     writeln(h);
     readln;
end.
```
What I am doing wrong, maybe working examples exist anywhere? I am using 32bit stdcall windows dll.

**Comment by ibell** [comment]
How did you handle the CoolProp dll?  Where did you download it from?  Did you download the right DLL with the appropriate bitness?

Also, please fill out the entire issue template.

**Comment by Mol3culo** [comment]
I needed to change the external name to 'PropsSI' instead of '_PropsSI@32'. Now I hope everything works as expected.

**Comment by ibell** [comment]
Yup, that's because you are now doing a 64-bit build, and symbols are not mangled in 64-bit windows builds (but they are in 32-bit builds).
