### ISSUE TITLE
Python AbstractState has no attribute 'compressibility_factor'

### ISSUE THREAD

**Issue by srgkoshelev** [CoolProp/CoolProp#1855]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

When trying to access compressibility_factor() of the AbstractState instance from python wrapper I get:
AttributeError: 'CoolProp.CoolProp.AbstractState' object has no attribute 'compressibility_factor'

I double checked the spelling and made sure original class has this method (http://www.coolprop.org/_static/doxygen/html/class_cool_prop_1_1_abstract_state.html#a9f39a26ffde9dc1eabefe9290bd9ee4f).

Other methods seem to be working fine.

### Steps to Reproduce

1. Start python
2. Create AbstractState instance
3. update() and call compressibility_factor

**Expected behavior:** Calculate compressibility factor.
**Actual behavior:** 
```
>>> import CoolProp.CoolProp as CP
>>> HEOS = CP.AbstractState('HEOS', 'water')
>>> HEOS.update(CP.PT_INPUTS, 101325, 300)
>>> HEOS.rhomass()
996.5569352652021
>>> HEOS.compressibility_factor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CoolProp.CoolProp.AbstractState' object has no attribute 'compressibility_factor'
```

High-level function is still working, though.
```
>>> CP.PropsSI('Z', 'P', 101325, 'T', 300, 'water')
0.0007343524546079561
```

### Versions

**CoolProp Version:** Requirement already up-to-date: coolprop in .../python3.7/site-packages (6.3.0)
**Operating System and Version:** MacOS HighSierra 10313.6 
**Access Method:** Python wrapper

**Comment by ibell** [comment]
The function is just not exposed through the Python interface.  You can get
Z from p/(rho R T), but we should add this function.

**Comment by ibell** [comment]
In the end, I just added it.

**Comment by srgkoshelev** [comment]
Thank you! And thank you for creating such an amazing piece of software!
