### ISSUE TITLE
List of incompressible fluids/mixtures is missing

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1856]
Hey @jowr, the incompressible fluids/mixtures seem to have disappeared from the docs: http://www.coolprop.org/dev/fluid_properties/Incompressibles.html#pure .  Any chance to put back the old tables?  The fitting report still works, but it would also be nice to have the tables on the landing page if possible.

**Comment by henningjp** [comment]
I just noticed this after following #1854, Personally, wading through the fitting report, I'd have never jumped to VCA (alphabetically at the end of the 108 page PDF) while looking for CaCl2.  It's not a term that I have ever used.  I'd say the short list on the landing page is critical.

**Comment by iamz33** [comment]
Hi, 
I too am facing same problem I guess. I'm trying to get viscosity of Propylene Glycol water mixture . I have coolprop version 6.3.1.dev0
Code:
import CoolProp.CoolProp as CP
per = '20%'
mew=CP.PropsSI('V','T',25+273.15,'P',101325,'INCOMP::MPG'+per)/1000

ValueError: Initialize failed for backend: "INCOMP", fluid: "MPG20%" fractions "[ 1.0000000000 ]"; error: key [MPG20%] was not found in string_to_index_map in JSONIncompressibleLibrary : PropsSI("V","T",298.15,"P",101325,"INCOMP::MPG20%")

**Comment by iamz33** [comment]
> Hi,
> I too am facing same problem I guess. I'm trying to get viscosity of Propylene Glycol water mixture . I have coolprop version 6.3.1.dev0
> Code:
> import CoolProp.CoolProp as CP
> per = '20%'
> mew=CP.PropsSI('V','T',25+273.15,'P',101325,'INCOMP::MPG'+per)/1000
> 
> ValueError: Initialize failed for backend: "INCOMP", fluid: "MPG20%" fractions "[ 1.0000000000 ]"; error: key [MPG20%] was not found in string_to_index_map in JSONIncompressibleLibrary : PropsSI("V","T",298.15,"P",101325,"INCOMP::MPG20%")

Sorry I think I fixed the issue: In the new version, I'm unable to use +percentage in the string. It works if I directly put percentage in there.
**mew=CP.PropsSI('V','T',25+273.15,'P',101325,'INCOMP::MPG-20%')/1000**
This fixed the issue. But does anyone know new syntax to add variable if I wanna be flexible? Thanks a lot

**Comment by ibell** [comment]
You'll note that you constructed two different fluid strings in your
examples :)  In one, the string was INCOMP::MPG20%, and in the other
INCOMP::MPG-20% (note the missing hyphen), so perhaps not surprising that
they yielded different results.

What do you mean by adding variable?

Ian

**Comment by iamz33** [comment]
Yeah thanks, I realised it later.  Thanks a lot. :)

**Comment by ibell** [comment]
@jowr can you put the tables back?  I am not able to figure out why it is missing.

**Comment by ibell** [comment]
Ok, fixed, but I don't understand why I had to wipe the folder on the server to get rsync to sync.  Anyway, its fixed now.
