### ISSUE TITLE
Convert cubics to HE

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#186]
See Scalabrin 2009 for 2-propanol

**Comment by thorade** [comment]
http://dx.doi.org/10.1063/1.3112608
13 Appendix D

**Comment by ibell** [comment]
Yes, and I have some derivations too that are generalized for SRK and PR
too.  I think I am going to be implementing this in the somewhat near
future.

**Comment by ibell** [comment]
This will form one of the major parts of the next major release of CoolProp

**Comment by ibell** [comment]
I've written and completed a paper on this topic.  When that gets published I'll implement back into CoolProp.

**Comment by ibell** [comment]
Works in C++, high-level interface is a work-in-progress

**Comment by ibell** [comment]
This now works.

**Comment by jowr** [comment]
Whoohoo, this is very interesting. I am looking forward to try this...
