### ISSUE TITLE
R Interface not working under Win10 with RStudio

### ISSUE THREAD

**Issue by elaurenz** [CoolProp/CoolProp#1862]
### Description

R fails when trying to load CoolProp.dll under Win10 with RStudio with the error: 
`Error in inDL(x, as.logical(local), as.logical(now), ...) : unable to load shared object 'CoolProp.dll': LoadLibrary failure: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.`

### Steps to Reproduce

1. Run RStudio (Version 1.2.1335) with R version 3.6.0 (2019-04-26) under Win10 or Server 2012 R2
2. load CoolProp.dll (https://sourceforge.net/projects/coolprop/files/CoolProp/6.3.0/R/, compiled 2019-05-19) with: 
`dyn.load(paste("CoolProp", .Platform$dynlib.ext, sep=""))`

**Expected behavior:**

CoolProp.dll should be loaded with no text returned to console.

**Actual behavior:** 

Error message:
`Error in inDL(x, as.logical(local), as.logical(now), ...) : unable to load shared object 'CoolProp.dll': LoadLibrary failure: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.`

### Versions

**CoolProp Version:** 6.3.0
**Operating System and Version:** Windows 10 (Version 1809)
**Access Method:** R through RStudio

### Additional Information

This issue is related to https://groups.google.com/forum/#!msg/coolprop-users/UFCwX9E6POs/3wL4Z9Q2CgAJ
The problem does not occur when using R directly without RStudio.

**Comment by ibell** [comment]
Do you get the same behavior when running directly from R, or only when
running through Rstudio?  That would help to track down the origin.  But
I'm pretty sure it's a DLL dependency hell problem.

Can you please try to recompile the library yourself?

**Comment by elaurenz** [comment]
I get the problem only when running through RStudio.

I just tried my best to recompile following the docs. After a lot of green lines and a couple of minutes it failed. I attached the CMakeCache. I used swigwin-4.0.1, tdm64-gcc-5.1.0-2 and cmake-3.16.0-rc1-win64-x64 and called cmake with
`cmake .. -DCOOLPROP_R_MODULE=ON -G "MinGW Makefiles" -DR_BIN="C:\Program Files\R\R-3.6.0\bin\x64" -DCMAKE_BUILD_TYPE=Release`
Here are the last lines returned from `cmake --build .`
```
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fc22): undefined reference to `_imp__R_NilValue'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fc3c): undefined reference to `vmaxset'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fc68): undefined reference to `Rf_warning'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fc6d): undefined reference to `_imp__R_NaInt'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fc77): undefined reference to `Rf_ScalarLogical'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fd94): undefined reference to `Rf_warning'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fd99): undefined reference to `_imp__R_NaInt'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fda3): undefined reference to `Rf_ScalarLogical'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fdd2): undefined reference to `Rf_warning'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fdd7): undefined reference to `_imp__R_NaInt'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text+0x3fde1): undefined reference to `Rf_ScalarLogical'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorIdSaIdEEE5asptrEP7SEXPRECPPS3_[__ZN4swig12traits_asptrISt6vectorIdSaIdEEE5asptrEP7SEXPRECPPS3_]+0x45): undefined reference to `Rf_length'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorIdSaIdEEE5asptrEP7SEXPRECPPS3_[__ZN4swig12traits_asptrISt6vectorIdSaIdEEE5asptrEP7SEXPRECPPS3_]+0xe4): undefined reference to `REAL'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_[__ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_]+0x44): undefined reference to `Rf_length'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_[__ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_]+0x17b): undefined reference to `Rf_coerceVector'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_[__ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_]+0x186): undefined reference to `Rf_protect'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_[__ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_]+0x230): undefined reference to `STRING_ELT'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_[__ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_]+0x238): undefined reference to `R_CHAR'
CMakeFiles\CoolProp.dir/objects.a(CoolPropR_wrap.cxx.obj):CoolPropR_wrap.cxx:(.text$_ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_[__ZN4swig12traits_asptrISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EEE5asptrEP7SEXPRECPPS9_]+0x341): undefined reference to `Rf_unprotect'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\CoolProp.dir\build.make:758: recipe for target 'CoolProp.dll' failed
mingw32-make.exe[2]: *** [CoolProp.dll] Error 1
CMakeFiles\Makefile2:104: recipe for target 'CMakeFiles/CoolProp.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
Makefile:139: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```
[CMakeCache.txt](https://github.com/CoolProp/CoolProp/files/3743118/CMakeCache.txt)

**Comment by ibell** [comment]
Hmm, this is unfortunate.  What about an older version of swig?  I think I
used something like 3.0.12?

Otherwise, you did a nice job of describing what you did.

**Comment by elaurenz** [comment]
Hmm, guess you are right. Tried with swig 3.0.12 but got the same result ... I'm at my wits' end - can someone take over?

**Comment by ibell** [comment]
Can you use Python instead of R?  I know that everything is fine in
Python-land since that's what I use every day.  Not too knowledgeable about
debugging Rstudio...

**Comment by ibell** [comment]
I can confirm this behavior on a windows 10 machine (virtual box image).  But can't rebuild for some reason that I can't explain.  It's super weird.

Can you try with mingw-64 instead of TDM-GCC?  TDM-GCC is kinda old now, last release in 2015..

**Comment by ibell** [comment]
Also, can you please provide the complete set of console output?  Might help to figure out what is going on....

**Comment by nitramwin** [comment]
I too have this problem but have found that it is easier just to follow the RStudio instructions for setting up a virtual environment of python for a given markdown file. I then use the package reticulate to "share" the R data to python and vice versa. Works very well and the support seems to be a bit more full featured so this is what I'd recommend.

**Comment by elaurenz** [comment]
The python work around works fine for me and I had no more time to put into sorting the R wrapper directly. I even found CoolProps python wrapper compined with the PythonInR package to be some 10% faster compared to the dyn.load() caller.

After installing CoolProp in Python I used:
```
install.packages("PythonInR")
pyConnect(pythonExePath="C:\\ProgramData\\Anaconda3\\python.exe")`
pyExec("import CoolProp.CoolProp as CP")
pyExec("from CoolProp.CoolProp import PropsSI")
pyExec("from CoolProp.HumidAirProp import HAPropsSI")
```
