### ISSUE TITLE
Difference between C++/FORTRAN and Python/MATLAB calls

### ISSUE THREAD

**Issue by DGSEM** [CoolProp/CoolProp#1863]
I've been stuck by calculating some vapor liquid lines/areas with CoolProp.

A brief summary: When i use the C++/FORTRAN interfaces everything is fine by using my BFGS Newton solver. By switching to MATLAB/Python i have some weird stability issues.

Can someone check the following calls in C++/FORTRAN and MATLAB/Python.

**Example**:

`HEOS = CoolProp.AbstractState("HEOS","n-Heptane") `
`HEOS.update(CoolProp.DmassT_INPUTS,4.2692360381933803,372.49600373915791)`

I get the results in **C++/FORTRAN**:

`HEOS.p()`
**123403.53262158910**
`HEOS.gibbsmass()`
**4913.1370570152885**

And in **MATLAB/Python**:

`HEOS.p()`
**104223.210485391**
`HEOS.gibbsmass()`
**1.5357820568060316**

I have used two different versions v6.2 and the current master.

Thank you for your help!

**Comment by ibell** [comment]
My guess, to be confirmed, is there is something wrong in your C++ code. Units?  Please post your minimal non-working C++ example, only calling the necessary functions.  

For me, in Python I get the same result as you:
``` python
import CoolProp.CoolProp as CP
import CoolProp
print(CoolProp.__version__)
HEOS = CP.AbstractState("HEOS", "n-Heptane")
HEOS.update(CP.DmassT_INPUTS, 4.2692360381933803, 372.49600373915791)
print(HEOS.p())
print(HEOS.gibbsmass())

CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, '/home/ian/refprop')
print(CP.get_global_param_string("REFPROP_version"))
RP = CP.AbstractState("REFPROP", "Heptane")
RP.update(CP.DmassT_INPUTS, 4.2692360381933803, 372.49600373915791)
print(RP.p())
print(RP.gibbsmass())
```
yields
```
6.3.1dev
104223.210485391
1.5357820568060316
10.0.0.61
104168.77638538752
1.5642853391205467
```
Note: REFPROP 10 and CoolProp use slightly different EOS.

**Comment by DGSEM** [comment]
Thank you for your quick reply, i have found my error in the FORTRAN wrapper:

Here is the C++ example

`#include "CoolProp.h"`
`#include "AbstractState.h"`
`#include <iostream>`
`#include "crossplatform_shared_ptr.h"`
`using namespace CoolProp;`
`int main()`
`{`
`    shared_ptr<AbstractState> HEOS(AbstractState::factory("HEOS","n-Heptane"));`
`    HEOS->update(DmassT_INPUTS, 4.2692360381933803, 372.49600373915791); // SI units`
`    std::cout << "T: " << HEOS->T() << " K" << std::endl;`
`    std::cout << "rho': " << HEOS->rhomass() << " kg/m^3" << std::endl;`
`    std::cout << "rho': " << HEOS->rhomolar() << " mol/m^3" << std::endl;`
`    std::cout << "h': " << HEOS->hmass() << " J/kg" << std::endl;`
`    std::cout << "h': " << HEOS->hmolar() << " J/mol" << std::endl;`
`    std::cout << "s': " << HEOS->smass() << " J/kg/K" << std::endl;`
`    std::cout << "s': " << HEOS->smolar() << " J/mol/K" << std::endl;`
`    std::cout << "gibbs': " << HEOS->gibbsmolar() << " J/mol" << std::endl;`
`    std::cout << "gibbs': " << HEOS->gibbsmass() << " J/kg" << std::endl;`
`    std::cout << "p': " << HEOS->p() << " Pa" << std::endl;`
`    return EXIT_SUCCESS;`
`}`

**T: 372.496 K
rho': 4.26924 kg/m^3
rho': 42.6063 mol/m^3
h': 266190 J/kg
h': 26672.8 J/mol
s': 714.607 J/kg/K
s': 71.6051 J/mol/K
gibbs': 0.153888 J/mol
gibbs': 1.53578 J/kg
p': 104223 Pa**

**Comment by DGSEM** [comment]
By the way is this behavior normal?

`#include "CoolProp.h"`
`#include "AbstractState.h"`
`#include <iostream>`
`#include "crossplatform_shared_ptr.h"`
`using namespace CoolProp;`
`int main()`
`{`
`    shared_ptr<AbstractState> HEOS(AbstractState::factory("HEOS","nHeptane"));`
`    HEOS->update(DmassT_INPUTS, 4.2692360381933803, 372.49600373915791); // SI units`
`    std::cout << "density': "<< 4.2692360381933803 << " kg/m^3" << std::endl;`
`    std::cout << "gibbs': " << HEOS->gibbsmass() << " J/kg" << std::endl;`
`    std::cout << "p': " << HEOS->p() << " Pa" << std::endl;`
`    HEOS->update(DmassT_INPUTS,  4.2692360381933803*10, 372.49600373915791); // SI units`
`    std::cout << "density': " << 42.692360381933803 << " kg/m^3" << std::endl;`
`    std::cout << "gibbs': " << HEOS->gibbsmass() << " J/kg" << std::endl;`
`    std::cout << "p': " << HEOS->p() << " Pa" << std::endl;`
`    HEOS->update(DmassT_INPUTS, 4.2692360381933803*100, 372.49600373915791); // SI units`
`    std::cout << "density': " << 420.692360381933803 << " kg/m^3" << std::endl;`
`    std::cout << "gibbs': " << HEOS->gibbsmass() << " J/kg" << std::endl;`
`    std::cout << "p': " << HEOS->p() << " Pa" << std::endl;`
`    return EXIT_SUCCESS;`
`}`

**density': 4.26924 kg/m^3
gibbs': 1.53578 J/kg
p': 104223 Pa
density': 42.6924 kg/m^3
gibbs': 1.53578 J/kg
p': 104223 Pa
density': 420.692 kg/m^3
gibbs': 1.53578 J/kg
p': 104223 Pa**

**Comment by ibell** [comment]
I'm 99% sure that the "weirdness" you are seeing is a manifestation of the
fact that your densities are two-phase, as I think you would see by also
looking at the quality Q.
