### ISSUE TITLE
Add docs for cross compilation on arm

### ISSUE THREAD

**Issue by babaksamareh** [CoolProp/CoolProp#187]
Hello guys,
Following up the conversation with Ian, I think that would be a great idea to add arm devices to the build bot. Specifically, arm64, armv7, and armv7s which are used by apple devices. Or in a more general fashion, as mentioned by Ian, this static library can also be used on raspberry PI devices.
Thanks,

**Comment by wlgardner** [comment]
Hey Guys, 

Not sure if a viable solution was found. But as of the latest cmake, cross-compiling became a bit more reliable.

Using this toolchain file:
https://code.google.com/p/ios-cmake/

and the latest cmake 3.1.0. Make will generate a usable project which will compile for iOS iPhone/simulator platforms. 

You may have a couple of issues with finding C & C++ compilers. But you can run the following commands to sort it out.

xcodebuild -find clang
xcodebuild -find clang++

etc..

Hope this helps. BTW, libCoolProp runs great on iOS platform. Thank You for you efforts! Greatly appreciated.

Regards

William

**Comment by ibell** [comment]
This would be great info to have on the web.  Can you make a PR / are you
familiar with github?

**Comment by wlgardner** [comment]
I’m fairly new at github. I can try an sort it out though. At this moment I have the CMake generated project in a Xcode 6.1 workspace as a dependency and it seems to be compiling consistently with the different Architectures (armv7s, arm64, i386, etc…).

I would be happy to contribute.

**Comment by wlgardner** [comment]
I have an question regarding some of the results I'm getting with the library compiled on iOS.

1. When the library is first initialized the following logs/warning/errors? appear.

Tmin invalid for sL for 1-Butene
Tmin invalid for sL for AceticAcid
Tmin invalid for sL for Ethanol
Tmin invalid for sL for MD3M
Tmin invalid for sL for MethylLinolenate
Tmin invalid for sL for MethylOleate
Tmin invalid for sL for MM

2. When testing the examples from the CoolProp site (http://www.coolprop.org/coolprop/HighLevelAPI.html#c-sample-code), a couple of the results do not match.

Specific heat (J/kg/K) of 20 percent ethylene glycol as a function of T
3.90527

Saturation temperature of Water at 1 atm
 647.096

Saturated vapor density of R134a at 0C
398603

Any Ideas why this may be happening.

**Comment by jowr** [comment]
Looks like you are not using the latest codebase. The ethylene glycol bug has been fixed 3 weeks ago or so.

**Comment by wlgardner** [comment]
Gotcha! I apologize. I'll sort that out a.s.a.p.

**Comment by wlgardner** [comment]
OK, so I ran the latest codebase through cmake. Generated the Xcode project, now I'm getting a Lexical or Preprocessore Issue 'REFPROP_lib.h' file not found. Is there a Flag to ignore this? Are there supposed to be REFPROP headers included? I did not have this issue previously. 

Regards

William

**Comment by wlgardner** [comment]
FYI, I just reverted back to the previous version and everything compiled fine.

**Comment by jowr** [comment]
The REFPROP headers come from a new external project. Make sure to initialise all git submodules in the externals folder.

**Comment by wlgardner** [comment]
OK. Sorry, about that. My bad again. I'll sort it out. Once I get this sorted then I will attempt to make a PR. I'll try to be as detailed as possible and include pre-compiled FAT Universal binaries as well.

Any advice for a Github noob would be welcome.

Thanks again!

**Comment by jowr** [comment]
You are welcome and thank you for contributing. The easiest way is to "fork" the project (top right corner of web page) and then "clone" your own fork with a git client. You can commit to your own branch of code and issue a pull request as soon as you are done. Do not hesitate to ask further questions.

**Comment by wlgardner** [comment]
FYI. Everything Compiled fine with the latest codebase for iOS/OSX. 
CMake has issues with creating shared library projects for Xcode. It's not a CoolProp library issue as I have tried it with a couple other libraries this afternoon. Just a reference in case it comes up.

**Comment by babaksamareh** [comment]
My personal experience: Well I was trying to build a static library for xCode using iOS/cmake toolchain. Honestly I didn't have the patience to solve all the problems and compile it. Instead, I loaded the whole C++ code into xCode and build all the necessary libraries over there. It's iOS native and it automatically combiles arm7, arm64, and armv7s. You can also build a simulator library for 32 and 64 bit machines. I have the xCode project and let me know if anyone needs that.

**Comment by ibell** [comment]
Can we integrate this discussion formally into the docs of CoolProp?  Even if one of you (@wlgardner ?) could put together a text-file with the instructions I could take care of integrating the docs.  I think it would be very useful for a lot of folks.

**Comment by babaksamareh** [comment]
Sure, actually I sent this to @wlgardner a couple of days ago:

Ok so this is how you do it:

1. Pull the latest version of CoolProp from github: git clone https://github.com/CoolProp/CoolProp --recursive
2. Go into the CoolProp folder, make a new folder for the build, let's say: mkdir build
3. Do into build folder
4. Prepare CMAKE for compilation: cmake .. -DCOOLPROP_STATIC_LIBRARY=ON
5. Now you have to actually compile the code. This compilation is useless, you only have to do it because some other files are generated during compilation and you need them in xCode: make VERBOSE=1

Now your done here. The rest of the stuff happens in xCode

1. Open the xcode and create a new project, for the template, under iOS, choose Cocoa Touch Static Library. Then the project name and save the project somewhere.
2. Now there are two files generated with your project name, one .h and one .m. Get rid of them.
3. Right click on your project name and select add files. Go to the folder where you have compiled CoolProp and add /src and /include. You should end up with something like this:

![default](https://cloud.githubusercontent.com/assets/8877630/6142114/3b4ab630-b17e-11e4-8c50-09d1edce2840.png)

Don't forget to remove .i and .cxx files, otherwise you get errors.

4. Under PROJECT -> Build Settings change the following:
        Under Architectures: Build Active Architecture Only : No
        Under Deployment: Targeted Device Family: iPhone/iPad
        You also have to sign your code, so under Code Signing -> Code Signing identity, select the relevant profile.

5. Under TARGETS -> Build Settings
        Under Deployment: Targeted Device Family: iPhone/iPad
        Under Linking: Other Linker Flags: -ObjC -all
        Under Search Paths: Header Search Paths: add the location for /externals and /Include, both of them recursive. In my case it looks like this:

![default](https://cloud.githubusercontent.com/assets/8877630/6142119/5197588a-b17e-11e4-9a74-5b21d26d5674.png)

6. Change your scheme from Debug to Release. Build the project. Now here is the thing, if you are building while on simulator, you end up with a static library .a file with 32/64 bit compatibility. If you want to build an actual arm static library, you have to compile on an actual device. Connect your phone, select it from the drop down list and build again. Now under products you should be able to see this:

![default](https://cloud.githubusercontent.com/assets/8877630/6142126/5f18842a-b17e-11e4-9668-79910380a731.png)

That libCoolPropStaticLib.a is the baby your are looking for. It contains all the arms editions required to Apple. Right click on it and click reveal in finder.

**Comment by ibell** [comment]
Nicely done, I am going to have to trust you on this since I don't have an
iPhone.  I'm going to lightly reformat your note, put you as the contact
person, and post it in the docs.  Perhaps tomorrow night.

So there is no way to make this happen  automatically?  Seems like a lot of
work that we should probably be able to get working using CMake, but
perhaps there are some blocking bugs.

**Comment by babaksamareh** [comment]
Thanks :)
Well I'm sure one can invoke xcode from command line. I can send you the prepared xcode project. You essentially just have to update coolprop files and command line compile with xcode.

**Comment by babaksamareh** [comment]
it looks great Ian, thanks
