### ISSUE TITLE
CP.PropsSI pressure  calculate error

### ISSUE THREAD

**Issue by kevinfu2** [CoolProp/CoolProp#1873]
### Description

CP.PropsSI("P", "H", 3021240.3815413937, "S", 7202.96064761869, "WATER")
results in  63850980092751.945 pa

### Versions

**CoolProp Version:** [6.3.0]  
**Operating System and Version:** [Win10]  
**Access Method:** [Python 3.7.5]  

### Additional Information
different input "H" with output "P"
seq    H                                        P
78      3021240.1615413935      63850924294504.91
79        3021240.1715413937        745968.132039806
80        3021240.1815413935        745968.303040869
81        3021240.1915413938        745968.3327498948
82        3021240.2015413935        745968.3624571852
83        3021240.211541394         745968.392165627
84        3021240.2215413935        745968.4218723334
85        3021240.231541394         745968.4515802134
86        3021240.2415413936        745968.4812892423
87        3021240.251541394         745966.5763150689
88        3021240.2615413936        745968.5015773389
89        3021240.271541394         745968.5015769979
90      3021240.2815413936      63850917817950.61
91        3021240.291541394         745968.6298286115
92        3021240.3015413936        745968.6595358996
93      3021240.311541394       63850920548314.836
94      3021240.3215413936      63850923133801.61
95      3021240.331541394       63850920076851.34
96      3021240.3415413937      63851018604260.41

**Comment by ibell** [comment]
Can you please explain in words what the problem is?  It's not obvious from
this issue

**Comment by kevinfu2** [comment]
> Can you please explain in words what the problem is? It's not obvious from this issue
Thanks for your reply, just the result of PropsSI("P", "H", 3021240.3815413937, "S", 7202.96064761869, "WATER") seems too too big , it should be some value near 745968 
not 10^8 bigger

**Comment by ibell** [comment]
Is this a reference state problem?  Where did you get your values of H and S from? 

Can you please start with a T,P pair, then calculate H,S, and then go back to T,P?  It's dangerous to start the calculation with enthalpy and/or entropy.

Please also see http://www.coolprop.org/fluid_properties/fluids/Water.html#consistency-plots

**Comment by ibell** [comment]
Also what s is used in your "Additional information"?

**Comment by kevinfu2** [comment]
> Also what s is used in your "Additional information"?

IT's the input of parameter "H" and output of “P” 
with little variation of "H" produce large different "P"

for example  
CP.PropsSI("P", "H", **3021240.271541394**, "S", 7202.96064761869, "WATER")  = **745968.50** 

CP.PropsSI("P", "H", **3021240.2815413946**, "S", 7202.96064761869, "WATER")= **63850917817950.61**  

CP.PropsSI("P", "H", **3021240.291541394**, "S", 7202.96064761869, "WATER") =  **745968.629**

**Comment by ibell** [comment]
Hmmm... That's odd, but HS inputs are by far the trickiest to get right.  Do the temperatures and densities also do weird things?
