### ISSUE TITLE
apply_simple_mixing_rule (from Python) breaks mixtures that do have interaction parameters

### ISSUE THREAD

**Issue by m-allan** [CoolProp/CoolProp#1874]
### Description

After calling `apply_simple_mixing_rule`, even with random components that don't feature in the mixture of interest, CoolProp raises an error that it has no interaction parameters for components that normally work.

### Steps to Reproduce

```
from CoolProp import CoolProp as CP
CP.apply_simple_mixing_rule("R32", "NH3", 'Lorentz-Berthelot')
CP.PropsSI("L", "P", 101325, "T", 300, "Air.mix")
```

**Expected behavior:** No error.

**Actual behavior:** 

```
ValueError: Initialize failed for backend: "?", fluid: "Air.mix" fractions "[ 1.0000000000 ]"; error: Could not match the binary pair [7440-37-1,7727-37-9] - for now this is an error. : PropsSI("L","P",101325,"T",300,"Air.mix")
```

Those CAS numbers are argon and nitrogen.

### Versions

**CoolProp Version:** 6.3.0
**Operating System and Version:** Windows 10 x64
**Access Method:** Python 3.7 x64

**Comment by ibell** [comment]
Calling that function right at the beginning forces an internal
initialization of the interaction parameter library with just the binary
you specify.  To work around:

Do some random mixture call first, then call apply.

**Comment by m-allan** [comment]
I knew I'd managed to make it work somehow yesterday but couldn't reproduce it, that explains it. I'm working in a Jupyter notebook, so it worked the first time when I first added a mixing rule to an existing notebook, and not when the notebook was restarted!

Is this not an actual bug then?

**Comment by ibell** [comment]
Correct, it's a feature :). I've been burned by this before too....

**Comment by m-allan** [comment]
I might see if I can write a PR for the documentation, don't recall seeing this mentioned?

**Comment by ibell** [comment]
Great a PR would be welcomed
