### ISSUE TITLE
Typo in enthalpy's unit of measure

### ISSUE THREAD

**Issue by tormec** [CoolProp/CoolProp#1884]
I think there is a typo in the examples reported here http://www.coolprop.org/coolprop/HighLevelAPI.html#vapor-liquid-and-saturation-states

It seems the entalpy's unit of measure is expressed in J/kg-K (which I read J/(kg K)) rather than J/kg,
 as correctly reported in the table http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function

**Comment by ibell** [comment]
Correct, typo indeed.  Can somebody fix it?  A beginner-friendly change to
CoolProp

**Comment by tormec** [comment]
Fixed with commit 30e25a7
