### ISSUE TITLE
Shared pointers do not work with MSVC2008

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1893]
The Python 2.7 extensions cannot build at the moment. It seems like the shared pointer definitions break compatibility with MSVC2008. 

See https://ci.appveyor.com/project/jowr/coolprop/builds/30402575

**Comment by jowr** [comment]
That is interesting, are you saying that these commits ended up not changing anything?

![image](https://user-images.githubusercontent.com/769593/73299286-320ee100-420f-11ea-9314-2c0fa9a73758.png)


![image](https://user-images.githubusercontent.com/769593/73299243-1dcae400-420f-11ea-925e-8c248e1ba982.png)

**Comment by ibell** [comment]
Not at all sure, but my recollection was that at one point all the builders were building again.  Can't wait for C++11 only.

**Comment by jowr** [comment]
I guess that is obsolete now. We skip Python 2 from now on.
