### ISSUE TITLE
Error calling R410A.ppf in Refprop 9.1 

### ISSUE THREAD

**Issue by jamarav** [CoolProp/CoolProp#1894]
# Description

Hi, everybody!

I open this issue because recently I noticed that there are calculation problems with the function PropsSI when I call Refprop 9.1 predefined mixtures as pseudo-pure fluids (files *.PPF in the fluids folder). The problem is easy to reproduce and it only appers when we calculate more than 1 point in the same step (vector inputs). I have this problem when I calculate the temperature dew point for R410A.PPF. I don't now the reason but the calculation is wrong with random vector lenghts. 

### Steps to Reproduce
```
import CoolProp.CoolProp as CP 

CP.set_config_string(CP.ALTERNATIVE_REFPROP_LIBRARY_PATH, '../01_prog/sources/REFPROP/REFPROP_9.1/REFPRP64.DLL')

CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, '../01_prog/sources/REFPROP/REFPROP_9.1/')

import numpy

```
Using the function PropsSI and calculating the temperature dew point for random pressure lenght vector I obtain:

```
In [32]: CP.PropsSI('T', 'P', numpy.resize(800000, 60), 'Q', 1, 'REFPROP::R410A.PPF')
Out[32]:
array([273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731])

In [33]: CP.PropsSI('T', 'P', numpy.resize(800000, 61), 'Q', 1, 'REFPROP::R410A.PPF')
Out[33]:
array([300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300.])

In [34]: CP.PropsSI('T', 'P', numpy.resize(800000, 62), 'Q', 1, 'REFPROP::R410A.PPF')
Out[34]:
array([300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300.])

In [35]: CP.PropsSI('T', 'P', numpy.resize(800000, 100), 'Q', 1, 'REFPROP::R410A.PPF')
Out[35]:
array([273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731])
```
I also tried to calculate with the file R410A.MIX and the results were correct and with Refprop 10 the results were correct with both files (*.MIX and *.PPF).

I don't now if this is a problem of Refprop or with the communication Coolprop-Refprop. I just installed the official wrapper of Refprop for python but I can't to reproduce this because I think that it doesn't allow to calculate with input vectors. I use the following call for the Refprop dll.

```
r = RP.REFPROPdll(os.path.join(os.environ['RPPREFIX'],"FLUIDS","WATER.FLD"),"PQ","T",MOLAR_BASE_SI,0,0,p_Pa,Q,[1.0])
```
Anybody knows if the official refprop warapper for python supports vectorial inputs?

Finally, I would like to know which is the most accurate method to calculate mixtures. With the pseudo-pure file (*.PPF) or with mixtures file (*.MIX)?

Thanks in advance

### Versions

CoolProp Version: CoolProp 6.3.0
Refprop Version: 9.1
Access Method: Python wrapper

**Comment by ibell** [comment]
My hypothesis is that this is a bug in REFPROP 9.1.  Seems an incorrect value is being returned from the cache, rather than doing the VLE call again.  Not sure why this happened.

You are right: the official Python wrapper for REFPROP (which I wrote), doesn't support vectorized inputs.

Seems your example works fine with the HEOS backend.  I haven't been able to find a vector length that fails in this way with the built-in code.
```
>>> CP.PropsSI('T', 'P', numpy.resize(800000, 60), 'Q', 1, 'R410A.PPF')
array([273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731,
       273.22526731, 273.22526731, 273.22526731, 273.22526731])
```

**Comment by ibell** [comment]
Also, if I use a linspace with REFPROP, I can't get the failure you have with REFPROP 10:
```
>>> CP.PropsSI('T', 'P', numpy.linspace(800000, 1000000, 64), 'Q', 1, 'REFPROP::R410A.PPF')
array([273.22526721, 273.34961155, 273.47358535, 273.5971912 ,
       273.72043164, 273.84330939, 273.9658266 , 274.0879859 ,
       274.20978973, 274.33124052, 274.45234065, 274.57309248,
       274.69349838, 274.81356063, 274.93328155, 275.0526634 ,
       275.17170842, 275.29041884, 275.40879685, 275.52684463,
       275.64456433, 275.76195808, 275.87902799, 275.99577616,
       276.11220464, 276.22831549, 276.34411072, 276.45959235,
       276.57476236, 276.68962271, 276.80417535, 276.91842221,
       277.03236519, 277.14600619, 277.25934707, 277.37238969,
       277.48513587, 277.59758745, 277.70974621, 277.82161394,
       277.9331924 , 278.04448334, 278.1554885 , 278.26620958,
       278.37664829, 278.48680631, 278.5966853 , 278.70628692,
       278.8156128 , 278.92466457, 279.03344383, 279.14195216,
       279.25019116, 279.35816237, 279.46586736, 279.57330764,
       279.68048474, 279.78740018, 279.89405543, 280.00045197,
       280.10659129, 280.21247482, 280.318104  , 280.42348027])
```

**Comment by jamarav** [comment]
Thanks you very much Ian. Could you reproduce the bug?

According to the calculation with the *.PPF files I found this in the Refprop documentation:

> https://refprop-docs.readthedocs.io/en/latest/GUI/Menu%20Commands/Substance%20Menu/pseudopurefluid.html

"*The uncertainties of the pseudo-pure fluid equations are often higher than the corresponding mixture model*"

Does this means that is most accurate to calculate with the *.MIX file? When I worked with mixtures I supposed that the best calculation was considering as pseudo-pure fluids. In fact, the graphical interface of Refprop provides the results with the *PPF file. Could you help me to understand this?

Thanks in advance

**Comment by ibell** [comment]
Yes, the mixture model is likely to be more accurate, although sometimes there are failures in the algorithms with the full mixture model that are not present with the pseudo-pure fluid, so what you "should" use is hard question to answer, and depends on the application.  In the REFPROP GUI, you can select to use either one; there are entries for pseudo-pure fluids and a separate one for predefined mixtures.

**Comment by ibell** [comment]
In your example, you should only need the second path setting for REFPROP (in theory at least).

**Comment by jamarav** [comment]
Perfect. Thanks you very much Ian. This guidelines are really useful for me. And you are right. In my example I need only the second path. Finally I changed to Refprop 10. As you said, the error is not present in the new version. My advice if it is not possible to use version 10 would be to perform the point-to-point calculation in the case of using the * .PPF files or to perform the calculation with vectorial inputs using only the * .MIX files. Do you agree?

**Comment by ibell** [comment]
If I was using REFPROP 9.x, I would use the low-level interface of CoolProp, it would avoid this discussion entirely I think.

**Comment by jowr** [comment]
Did this end up being a REFPROP bug?
