### ISSUE TITLE
nD data as inputs in Python wrapper

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1898]
Python array inputs are limited to 1D, shouldn't we extend that to nD arrays?

**Comment by ibell** [comment]
Maybe?  I'm not sure what is gained, since a pre- and post- reshape isn't too onerous

**Comment by jowr** [comment]
I guess the gain is that one does not have to mess with the shape before calling CoolProp. I'll create PR and then we can can decide whether we want to include it or not.

**Comment by ibell** [comment]
Go for it!
