### ISSUE TITLE
CoolProp on Mac

### ISSUE THREAD

**Issue by camilamsm** [CoolProp/CoolProp#1904]
I use CoolProp on MATLAB_R2018b for MacOS but I am having the following problem.
Does anyone know how can I fix this??? It is urgent!!! Please!! :) 

Undefined function or variable 'CoolPropMATLAB_wrap'.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(345,varargin{:});

**Comment by ibell** [comment]
The old Matlab interface is no longer supported, was a nightmare to keep running.  You have to call the Python interface via MATLAB, as described in the docs
