### ISSUE TITLE
Enthalpy calculation problem

### ISSUE THREAD

**Issue by hot586** [CoolProp/CoolProp#1910]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description
from CoolProp.CoolProp import PropsSI
t1 = PropsSI('T', 'P', 16744000, 'H', 682022, 'IF97::Water')
h1 = PropsSI('H', 'P', 16744000, 'T', t1 , 'IF97::Water')
[Description of the issue]
I was trying to caculate a temperature from pressure 16.744MPa and enthalpy 682.022kj/kg, the result I got was  432.4289K which was a little larger than it should be 432.4149K which I got from other software. It  was more tricky when I used this temperature and origin pressure to get enthalpy, the result which was 682.082kj/kg, it was about 0.06kj/kg larger than the origin one I used to get temperature.
--
![image](https://user-images.githubusercontent.com/62917333/78086156-a9b7e280-73ef-11ea-9c69-44f37de31e93.png)

.
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**CoolProp Version:6.3.0  [CoolProp version you are using]  
**Operating System and Version:WIN10[OS you are running CoolProp on]  
**Access Method:python 2.7.16  [How you are accessing CoolProp (i.e. Python, other wrapper, direct C++ calls, etc.)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
This is the #1 most asked question: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by hot586** [comment]
I think my problem is different with the question listed in FAQ. I can accept the temp which I got was different with other software, but I can not accept if I put the same temp I get from the function with a specified pressure and enthalpy and the same pressure, but I will get a different enthalpy from function. I think it's a problem of repeatability of the function.

if you execute the code below, I except the same value all the time, but you will see every time after the funciton ,  the temp and enthalpy will increase. 

from CoolProp.CoolProp import PropsSI
temp=[]
temp.append(PropsSI('T', 'P', 16744000, 'H', 682022, 'IF97::Water'))
enthalpy=[]
enthalpy.append(PropsSI('H', 'P', 16744000, 'T', temp[0] , 'IF97::Water'))
for i in range(10):
    temp.append(PropsSI('T', 'P', 16744000, 'H', enthalpy[i] , 'IF97::Water'))
    enthalpy.append(PropsSI('H', 'P', 16744000, 'T', temp[i+1] , 'IF97::Water'))
else: temp.append(PropsSI('T', 'P', 16744000, 'H', enthalpy[i+1] , 'IF97::Water'))

print temp
print enthalpy

[432.42890944361255, 432.44297321965786, 432.45704144139364, 432.47111410742133, 432.4851912163382, 432.4992727667375, 432.51335875720866, 432.5274491863366, 432.54154405270157, 432.5556433548809, 432.56974709144714, 432.5838552609688]
[682082.2074816858, 682142.4344925572, 682202.6810271872, 682262.9470801328, 682323.2326459328, 682383.5377191097, 682443.862294169, 682504.2063655969, 682564.5699278613, 682624.952975416, 682685.3555026953]

**Comment by Relojuca** [comment]
Hi People.

It looks to me as residual from the solver for calculate the enthalpy,
nevertheless I think that at this high pressure (15 MPa) a residual of
1x10^-5 is reasonable. If you really want to work with an Equation of state
with this degree of precision I suggest you to use the IAPWS-95 also
implemented in CoolProp as "Water", this equation of state is more accurate
than the IF97.

Regards



Em qua., 1 de abr. de 2020 às 06:27, hot586 <notifications@github.com>
escreveu:

**Comment by hot586** [comment]
Thanks for telling me the reason and thanks for you suggestion!

**Comment by Relojuca** [comment]
You are Welcome! 

But I am not part of the CoolProp development team, the last message is just my guess, however I think that for you is better use IAPWS-95, and if is important for you the calculation speed, I suggest to use the CoolProp low level interface, as explained in the following link:

http://www.coolprop.org/dev/coolprop/LowLevelAPI.html

Regards

**Comment by ibell** [comment]
What is the "other software"?  And are you quite sure they used the IF97 formulation rather than the more accurate (but computationally complicated) IAPWS standard formulation recommended by @Relojuca  ?

**Comment by hot586** [comment]
I used an Excel add-in called WASPCN V6.0 Add-in. Yes, I'm not sure how it implements, my origin attention is not about questioning the accurancy of calculation, I was confused about the repeatability of the result. Now I understand it's caused by the residual. I appreaciate your time to answer my question. I will close this issue. Thank you, all guys, have a good day!
