### ISSUE TITLE
How can I retreive the specific heat at constant volume for humid air?

### ISSUE THREAD

**Issue by mangoon91** [CoolProp/CoolProp#1911]
HAPropsSI('cp_ha','P',100000,'T',300,'R',0.2) works great for Cp.

Is there a similar command for Cv? At least [here](http://www.coolprop.org/fluid_properties/HumidAir.html) I could not find it.

Thanks much in advance!

**Comment by ibell** [comment]
I think somebody also asked about this at some point, and I added them to the C++ code, but they didn't make their way into the documentation yet.  You can see they are there in C++: https://github.com/CoolProp/CoolProp/blob/master/src/HumidAirProp.cpp#L1836-L1848
So you use the development version of CoolProp and then use the same keys like c_p, but replace c_p with c_v.

**Comment by ibell** [comment]
Updated docs in https://github.com/CoolProp/CoolProp/commit/a4e2ff8aa96a3a7a022bf2eaddc4f94ea3f2e2a5

**Comment by mangoon91** [comment]
That worked, thank you for your quick help.
