### ISSUE TITLE
ModuleNotFoundError: No module named 'Coolprop'

### ISSUE THREAD

**Issue by Abc672** [CoolProp/CoolProp#1914]
Hi everyone

Last week, after deleting the jupyter environment (conflicting when multiple env installed resulting in errormessage: "No module named: Coolprop") my coolprop was working in python 3.7, Spyder. 
Yesterday the same error popped up again out of the blue. The same error which @ibell helped solving already in previous posts:

https://github.com/CoolProp/CoolProp/issues/1682 
https://github.com/CoolProp/CoolProp/issues/1473

I pip installed and reinstalled the coolprop, but the only thing it seems to do is place the 2 folders coolprop and coolprop 6.3.0 under the site package folder in the python root. I tried replacing the folders under my anaconda3 map but that didn't work.
No other environments are installed (see 2nd screenshot) and the solutions suggested on the previous github are not satisfactory. 

I was very much hoping anyone could help me, how could the Coolprop work initially and then throw up the same error without any (that I am aware of) adjustments done?

![image](https://user-images.githubusercontent.com/63342969/78770092-7268a900-798e-11ea-8ab7-24929fdf1a14.png)

![image](https://user-images.githubusercontent.com/63342969/78769950-464d2800-798e-11ea-974a-7453d54bbc48.png)

With kind regards

**Comment by ibell** [comment]
Before a reinstall of Anaconda, I would propose to open a shell on your
computer and run

pip install -U coolprop

and paste the output here.  Then if that works, do

import CoolProp

once you start python.  I know there have been some weird things with
spyder and Anaconda, but I don't know if I've seen this particular problem
before.

>

**Comment by Abc672** [comment]
Apparently opening the Anaconda prompt and executing "conda install conda-forge::coolprop" 
did it for me. Nothing peculiar actually :)

(http://www.coolprop.org/coolprop/wrappers/Python/index.html)
