### ISSUE TITLE
Error in Low Level Interface example code on coolprop.org

### ISSUE THREAD

**Issue by nickmasonsmith** [CoolProp/CoolProp#1915]
Hi all, not sure if this is the place to file this:

On the CoolProp online page for the low-level interface, the section on partial derivatives contains an error:
[](http://www.coolprop.org/coolprop/LowLevelAPI.html#partial-derivatives)

Relevant section:
```
> # In the same way you can do second partial derivatives
> # This is the second mixed partial of entropy with respect to density and temperature
> In [33]: HEOS.second_partial_deriv(CoolProp.iSmass, CoolProp.iT, CoolProp.iDmass, CoolProp.iT, CoolProp.iDmass)
> Out[33]: -0.06606041536491998
```

In the [source documentation for second_partial_deriv](http://www.coolprop.org/_static/doxygen/html/class_cool_prop_1_1_abstract_state.html#a0815380e76a7dc9c8cc39493a9f3df46) and in [the source](http://www.coolprop.org/_static/doxygen/html/_abstract_state_8h_source.html#l00845), the arguments are:
```
second_partial_deriv(parameters Of1, parameters Wrt1, parameters Constant1, parameters Wrt2, parameters Constant2)
```

So the example code on the Low Level Interface page should be either:

1. Keep the comment the same and change the code to: HEOS.second_partial_deriv(CoolProp.iSmass, CoolProp.iT, CoolProp.iDmass, CoolProp.iDmass, CoolProp.iT); or
2. Keep the code the same and change the comment to "This is the second partial derivative of entropy with respect to temperature, at constant density"

A small point but one that led me astray! 

Thanks,
Nick

**Comment by ibell** [comment]
I would vote for fixing the docs.  Is that something you can manage?

**Comment by nickmasonsmith** [comment]
Gladly - I've just amended it.
