### ISSUE TITLE
Broken links in incompressibles.rst

### ISSUE THREAD

**Issue by fwitte** [CoolProp/CoolProp#1917]
Hi,

the links at the beginning of the Incompressibles.rst (https://github.com/CoolProp/CoolProp/blob/master/Web/fluid_properties/Incompressibles.rst#L14-L16) seem to be broken. I wanted to open a PR with a quick fix, but could not find, where those links should actually point to. Can you give me a hint? Or are those not supposed to link anywhere?

Btw: Is there an overview of all incompressibles without opening the pdf-report?

Thank you have a nice Easter weekend!

**Comment by ibell** [comment]
Hello! We had some build issues with the release of version 6.3.0 of
CoolProp and those tables were silently broken. The updated tables are on
the build server:
http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/fluid_properties/Incompressibles.html#incompressible-fluids
.  Sorry that's not very convenient, but once we release version 7, then
we'll have the updated table in the main docs again.
