### ISSUE TITLE
error: key [DowJ] was not found in string_to_index_map in JSONFluidLibrary

### ISSUE THREAD

**Issue by thermengineer** [CoolProp/CoolProp#1919]
Dear friends,

Cooplrop gives the message mentioned below for Dowtherm J
Coolprop/PropsSi: C/T/20/P/100000/DowJ Initialize failed for backend: "?", fluid: "DowJ" fractions "[ 1.0000000000 ]"; error: key [DowJ] was not found in string_to_index_map in JSONFluidLibrary

Dowtherm J is not the only liquid that we get the warning. Pure liquids (except water) give this error warning. Could you help us where we miss?
Thank you beforehand.
BR
Hasan

**Comment by ibell** [comment]
For the incompressible fluids, you need to preface the fluid name with
INCOMP:: .  Please see the examples:
http://www.coolprop.org/fluid_properties/Incompressibles.html#pure-fluid-examples

**Comment by thermengineer** [comment]
Dear Ian, Thank you for the answer. Best Regards.
