### ISSUE TITLE
General question about humid air model

### ISSUE THREAD

**Issue by nkarakin** [CoolProp/CoolProp#1920]
Hello Ian, I have a question regarding humid air properties.
On the coolprop-website it is said that the dry air is treated as ideal gas whereas the water vapor is treated as real gas.
So, the model is based on the following idea:
Humid Air = Dry Air (ideal gas) + Water Vapor (real gas)
What if I replace the dry air with some other gas? Is the model still applicable then?
I mean, somehow the specific gas constant of the dry air is incorporated into the model. This would mean, the dry air composition is part of the model, but the functions in coolprop don’t use dry air composition as input.  Can you elaborate on that without diving too much into thermodynamics?

**Comment by ibell** [comment]
Please see their paper about the model: https://www.tandfonline.com/doi/abs/10.1080/10789669.2009.10390874 . Neither dry air nor water are are treated as being ideal, rather dry air is treated with a pseudo-pure EOS, and water uses the reference EOS from IAPWS, and the mixture part comes from a virial expansion.

**Comment by nkarakin** [comment]
Hello Ian, thank you for the quick response.
Looks like I will have to dive into thermodynamics:) So far my knowledge
did not go beyond ideal gas EOS.

Am So., 19. Apr. 2020 um 23:07 Uhr schrieb Ian Bell <
notifications@github.com>:
