### ISSUE TITLE
Coolprop 

### ISSUE THREAD

**Issue by StefanoMorc** [CoolProp/CoolProp#1923]
Hi!
Following the instructions in here http://www.coolprop.org/coolprop/wrappers/StaticLibrary/index.html I created a static library and linked it in visual studio 2019.
The following error comes up: 

Error	LNK1104	cannot open file 'C:\Users\Stefano Morcelli\Documents\Progetto\CoolProp-master\include.obj'	CP Test 2	C:\Users\Stefano Morcelli\Documents\Progetto\Test\CP Test 2\LINK	1	
Someone can help me?

**Comment by ibell** [comment]
Please show all the steps you have done up to this point.  Are you using
cmake?  It's not strictly required, but strongly recommended.

>

**Comment by StefanoMorc** [comment]
[CoolProp.txt](https://github.com/CoolProp/CoolProp/files/4519565/CoolProp.txt)
I followed:
# Check out the sources for CoolProp
git clone https://github.com/CoolProp/CoolProp --recursive
# Move into the folder you just created
cd CoolProp
# Make a build folder
mkdir -p build && cd build
# Build the makefile using CMake
cmake .. -G "Visual Studio 16 2019" -DCOOLPROP_STATIC_LIBRARY=ON
# Make the static library
cmake --build .
The only diference is that I did not specify Win 64, because it gave me an error.
What I obtained is in attachment
Is it correct?

**Comment by ibell** [comment]
That all seems fine, your static library built properly. So linking it with
your own code seems to be the problem.

**Comment by StefanoMorc** [comment]
As you can see, there are some warnings... Is it normal?
For linking it, I copied the directories in 
C/C++ -> general-> additional include directories
 Linker -> additional include directories

**Comment by ibell** [comment]
You are using the same compiler for your code and the static library?
That's mandatory, unfortunately.

**Comment by StefanoMorc** [comment]
Can you clarify it?

**Comment by ibell** [comment]
If you make a static library in VS20xx, then you have to use VS20xx to
compile your own code. Sometimes even more flags need to match to ensure
binary compatibility.  If you use CMake (strongly recommended), then check
out this example: https://github.com/CoolProp/simple_cmake_example

**Comment by StefanoMorc** [comment]
Maybe I do not understand what you are trying to tell me
I followed the example that you linked...
I used cmake .. -G "Visual Studio 16 2019" -DCOOLPROP_STATIC_LIBRARY=ON 
and I do want to use VS 2019 to use Coolprop
But I had the error that I pasted before...

**Comment by StefanoMorc** [comment]
Now I have the following error, different from the previous one

Error	C1083	Cannot open include file: 'fmt/format.h': No such file or directory	Test	C:\Users\Stefano Morcelli\Documents\Project\CoolProp\include\CPstrings.h	14

**Comment by ibell** [comment]
Right - this is all because the dependencies of CoolProp are not as simple
as just the include folder of CoolProp.  That's why you should use the
CMake approach, because then all the includes are handled appropriately,
compilation flags match, etc.

**Comment by ibell** [comment]
Cannot recommend strongly enough that you build this example to get a
better sense for how the bits fit together:
https://github.com/CoolProp/simple_cmake_example/blob/master/CMakeLists.txt

**Comment by StefanoMorc** [comment]
I would like to use the CMake approch, but the problem is that I am not able to follow the procudure that you send me. The last link is for Linux but I have windows
Can you please give me some additional details?

**Comment by ibell** [comment]
Did you read step 4 in the simple_cmake_example README?

**Comment by StefanoMorc** [comment]
Please Ian be patient
If I understand well, the CMake approach in here https://github.com/CoolProp/simple_cmake_example/blob/master/CMakeLists.txt does what I tried to do adding manually the directories in VS, is it right?
With step 4 you mean cmake .. -G GENERATOR where GENERATOR is VS 2019, is it right ?
I copied the first steps in the command prompt (of git), and I obtained an error at step 2, see file in attchment
[git.txt](https://github.com/CoolProp/CoolProp/files/4523279/git.txt)
But in case this procudere is successful, what do I need to do next in order to use Coolprop in VS 2019? 
Sorry but I not familiar with the approch that you are suggesting me, and I need additional help
Thanks

**Comment by StefanoMorc** [comment]
Ok, I obtained this
[git.txt](https://github.com/CoolProp/CoolProp/files/4523712/git.txt)
error C2678
Can you suggest a way to solve it?

**Comment by ibell** [comment]
Very, very close, seems like a bug in the example :(  Let me fix it.

**Comment by StefanoMorc** [comment]
I do not why, but I redo the same procedure, and now I seems to work. This is what I obtained 
[git.txt](https://github.com/CoolProp/CoolProp/files/4523868/git.txt)
Is it correct?
Can you plaese tell me now what I should do to run a simple example to see if it really works?
In the simple_cmake_example what do I need to open? If possible can you provide a step by step procudere?
I really appreaciate you help!

**Comment by ibell** [comment]
Now you should be able to run the example, right? It is in the Release/x64 folder, or something like that.  You can also open the .sln file that is generated and run in Visual Studio (which is how I always get set up to debugging in Visual Studio, or Xcode, or ...).

Starting from that example, you would build up, replacing the code in the sample file mycode.cpp with your own code.  And if you have lots of files, then you would put them in a folder, and we could modify the CMakeLists of simple_cmake_example to compile also your project.  This is the only way to stay sane as you get more complicated projects to build.

**Comment by ORNL-Modelica** [comment]
I don't mean to hijack the conversation, so feel free to tell me to take a hike 😄 , that simple_cmake_example has been helpful. VS2019 and cmake seem to work well.

However, it ties you to compiling your *.cpp with coolprop. Is there a straightforward path for other workflows.

**Note:** This could be just requiring experience with cmake and C++ and not really a coolprop issue. Another reason for feeling free to tell me to take a hike.

Two examples:
1) Load CoolProp into your cpp file and just compile your cpp file. I think this would be using a .lib but there doesn't seem to be a single `CoolProp.h` and `CoolProp.Lib` system that works and doesn't given all sorts of errors with `fmt/*`. I think of this like python packages... my much more familiar world.

2. Workflow like what the Modelica wrapper (which I believe is defunct as ExternalMedia is still tied to CP4 and doesn't look like it will be updated anymore). That takes CoolProp and that combines everything into a .lib with a .h and then the functions are called from within Modelica.

**Comment by greenwoodms06** [comment]
I don't mean to hijack the conversation, so feel free to tell me to take a hike 😄 , that simple_cmake_example has been helpful. VS2019 and cmake seem to work well.

However, it ties you to compiling your *.cpp with coolprop. Is there a straightforward path for other workflows.

Note: This could be just requiring experience with cmake and C++ and not really a coolprop issue. Another reason for feeling free to tell me to take a hike.

Two examples:

Load CoolProp into your cpp file and just compile your cpp file. I think this would be using a .lib but there doesn't seem to be a single CoolProp.h and CoolProp.Lib system that works and doesn't given all sorts of errors with fmt/*. I think of this like python packages... my much more familiar world.
Workflow like what the Modelica wrapper (which I believe is defunct as ExternalMedia is still tied to CP4 and doesn't look like it will be updated anymore). That takes CoolProp and that combines everything into a .lib with a .h and then the functions are called from within Modelica.

**Comment by StefanoMorc** [comment]
I still have some issues...
I have opened main.sln in simple_cmake_example>build. The file mycode.cpp is already in here.
But when I do this> debug>start without debugging I obteined the following message
![Uploading Coolprop.PNG…]()
Did I do something wrong? Are there another procedure to follow?

**Comment by StefanoMorc** [comment]
Sorry, the message that pops up is unable to start....build/x64/Debug/ALL BUILD  Acess is denied
I do not know why?

**Comment by ibell** [comment]
1. Right, this is one very important difference between the C++ ecosystem and the Python one.  Package management is much cleaner in Python, and much more horrible in C++.  Your question is PRECISELY why I only recommend that people integrate CoolProp and C++ via cmake.  There were efforts to build a conan hook for CoolProp, but I don't know how far that got.
2. I was of course an important part of the ExternalMedia team back when I was in Liege, but don't touch Modelica at the moment. If you are interested in ExternalMedia, you could be the one to get it back on its feet! The amount of work should be hours, not months, to get everything operational once more.

**Comment by ibell** [comment]
@StefanoMorc :  You need to right-click on the main project in project explorer and set as a start up project.

**Comment by ibell** [comment]
Otherwise it tries to execute the ALL_BUILD item, which is only a meta project to manage dependencies, no real code.

**Comment by greenwoodms06** [comment]
Yes @ianhbell , I've seen your coffee cup all over that 😄 . I do have interest in getting it back on its feet. But sheesh, having a coolprop integration as my first "for realz" c++ project is a doozy. But, I'm trying to find folks at work who can assist so that it isn't a months long thing. Already surpassed the hours mark 😞 . Few people in my work world seem to have windows c++ experience, they all religiously stick to their unix environments. But I'm trying and am still optimistic. If we work on it, we'll be sure to contribute back to coolprop. Thanks @ianhbell . Peace out.

**Comment by StefanoMorc** [comment]
@ianhbell thanks a lot!
Now it works!!
Thanks, thanks

**Comment by ibell** [comment]
@greenwoodms06 You can send me a PM and I can put you in touch with the ExternalMedia folks, but no guarantees.
