### ISSUE TITLE
Very high deviation in the tabular back-ends for PT inputs at T_triple

### ISSUE THREAD

**Issue by fwitte** [CoolProp/CoolProp#1925]
Hi guys,
it's me again, I hope your are well and not traumatized by my almost periodic reports. I encountered this issue for both tabular back-ends using PT_INPUTS. The deviation in density, entropy and enthalpy to HEOS is extremly high (yellow is >= 200 % relative deviation!) at triple point temperature especially for not very high pressure values. If I understand the description (http://www.coolprop.org/dev/coolprop/Tabular.html) correctly, that means that the value at the triple point temperature is just loaded incorrectly into the data as it should be one of the base points. Increasing the temperature input by e.g. 5 K the deviation is as expected (very low).

Have a nice weekend and thank you very much for your work!
Cheers

``` python
for fluid in ['water', 'NH3'', 'R245fa']:
    df = {}
    for back_end in ['HEOS', 'TTSE', 'BICUBIC']:

        state = CP.AbstractState(back_end, fluid)
        T = state.trivial_keyed_output(CP.iT_triple)
        p_min = state.trivial_keyed_output(CP.iP_min)
        p_max = state.trivial_keyed_output(CP.iP_max)
        df[back_end] = pd.DataFrame(columns=['s', 'h', 'rho'])

        for p in np.geomspace(p_min, p_max, 1e3):

            try:
                state.update(CP.PT_INPUTS, p, T)
                df[back_end].loc[p, 's'] = state.smass()
                df[back_end].loc[p, 'h'] = state.hmass()
                df[back_end].loc[p, 'rho'] = state.rhomass()
            except ValueError:
                df[back_end].loc[p, 's'] = np.nan
                df[back_end].loc[p, 'h'] = np.nan
                df[back_end].loc[p, 'rho'] = np.nan

        fig, ax = plt.subplots(3, 1)

        ax[0].set_title(back_end + ' back end for ' + fluid)
        f = ax[0].scatter(
            df[back_end].index, df[back_end]['s'],
            c=abs((df[back_end]['s'] - df['HEOS']['s']) / df['HEOS']['s']),
            marker='x', vmin=0, vmax=2)
        ax[0].grid()
        ax[0].set_xlabel('pressure in Pa')
        ax[0].set_xscale('log')
        ax[0].set_ylabel('entropy in J/kgK')
        ax[1].scatter(
            df[back_end].index, df[back_end]['h'],
            c=abs((df[back_end]['h'] - df['HEOS']['h']) / df['HEOS']['h']),
            marker='x', vmin=0, vmax=2)
        ax[1].grid()
        ax[1].set_xlabel('pressure in Pa')
        ax[1].set_xscale('log')
        ax[1].set_ylabel('enthalpy in J/kgK')
        ax[2].scatter(
            df[back_end].index, df[back_end]['rho'],
            c=abs((df[back_end]['rho'] - df['HEOS']['rho']) / df['HEOS']['rho']),
            marker='x', vmin=0, vmax=2)
        ax[2].grid()
        ax[2].set_xlabel('pressure in Pa')
        ax[2].set_xscale('log')
        ax[2].set_ylabel('rho in kg/m3')
        plt.tight_layout()
        cbar = fig.colorbar(f, ax=ax.ravel().tolist(), shrink=0.95)
        cbar.set_label('relative deviation to HEOS (absolute value)', rotation=90)
        fig.savefig(fluid + '_' + back_end +'.pdf')
        fig.savefig(fluid + '_' + back_end +'.png')
        plt.close()
```

Comment on the colorbars: I cut off at >= 200 % as in some plots the values exceeded several 1.000.000 %.

![water_BICUBIC](https://user-images.githubusercontent.com/20252362/80279174-1460f300-86fc-11ea-980c-0c1297506f43.png)
![water_TTSE](https://user-images.githubusercontent.com/20252362/80279175-14f98980-86fc-11ea-99f9-bd125451d93d.png)

![NH3_BICUBIC](https://user-images.githubusercontent.com/20252362/80279171-13c85c80-86fc-11ea-9f15-3229abf1553f.png)
![NH3_TTSE](https://user-images.githubusercontent.com/20252362/80279172-1460f300-86fc-11ea-8bed-1b1fcfa147d6.png)

![R245fa_BICUBIC](https://user-images.githubusercontent.com/20252362/80279167-12972f80-86fc-11ea-92ae-78ad81bf08c6.png)
![R245fa_TTSE](https://user-images.githubusercontent.com/20252362/80279168-132fc600-86fc-11ea-92ce-2610bee32dc8.png)

While at 5 K above triple point temperature (e.g. NH3) the values are perfectly fine.
![NH3_TTSE](https://user-images.githubusercontent.com/20252362/80279371-80902680-86fd-11ea-92f5-cda40367ba5e.png)

**Comment by ibell** [comment]
I think this result should not be very surprising unfortunately.  If you consider the location of the nodes of the table, they end at the triple point, and there are essentially zero nodes in the liquid phase around the triple point.  That holds true for both TTSE and BICUBIC because they use the same nodes, albeit in a different manner.

I don't see a great path forward. One option would be to allow arguments to the library to specify how many points to use for the independent variables which would improve somewhat the accuracy of the method down there.  Better would be an adaptive tabular interpolation method, that refines as needed into the corners of the phase diagram.  But I'm not in the position to do that presently.

**Comment by fwitte** [comment]
Thank you very much for your explanation, that is indeed quite unfortunate. I'll go ahead and close this issue then.

Have a nice week!
