### ISSUE TITLE
6.4: fix windows installer

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1930]
I don't know what is wrong with the installer build, I've dug into it, and the errors are very obtuse.  Maybe something changed in visual studio?

**Comment by jowr** [comment]
The CMake generator is hard-coded in the CMakeLists.txt - It expects Visual Studio 2010 to be present on the machine...

**Comment by ibell** [comment]
But I see you have been trying to hardcode it to something else, as I also experimented with too, and that didn't seem to work for some reason.  Must I also install VS2010? Visual Studio never seems to uninstall completely...
