### ISSUE TITLE
Adding New Fluids - all_incompressibles.py

### ISSUE THREAD

**Issue by whunter7** [CoolProp/CoolProp#1931]
I wanted to add a new fluid as per the instructions on coolprop.org. After running all_incompressibles.py and reinstalling, an error appeared when importing and using PropsSI. The error also occurs without any modification to the source files (i.e. PureFluids.py).

Anaconda Python 3.7.4 on Windows 10

Steps taken:

clone repo and check out v6.3.0
run BuildCP.bat under wrappers/Python

-> no problem

run all_incompressibles.py
run ForceBuild.bat under wrappers/Python

-> problem with incompressible fluids, as follows:

In [1]: from CoolProp.CoolProp import PropsSI
Unable to load fluid: DowJ; error was input "[
    -250.0,
    1.5,
    10.0
]" is not a 2D array
input "[
    -250.0,
    1.5,
    10.0
]" is not a 2D array

In [2]: PropsSI("V","P",101325,"T",273.15,"INCOMP::DowJ")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-8652c2f6633c> in <module>
----> 1 PropsSI("V","P",101325,"T",273.15,"INCOMP::DowJ")

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.__Props_err2()

ValueError: Initialize failed for backend: "INCOMP", fluid: "DowJ" fractions "[ 1.0000000000 ]"; error: key [DowJ] was not found in string_to_index_map in JSONIncompressibleLibrary : PropsSI("V","P",101325,"T",273.15,"INCOMP::DowJ")

**Comment by jowr** [comment]
The incompressible fluids information files are stored in an intermediate format that has to be converted to C++ header files using another Python script. This is normally handled by CMake, but to do it manually *before* you rebuild the Python wrapper. The Python wrapper assumes that all code is present, but you are missing the incompressibles since the header files have not been generated.

In short:

1. update incompressibles: `python all_incompressibles.py`
2. generate headers: `python /dev/generate_headers.py`
3. build Python wrapper

**Comment by whunter7** [comment]
I tried the 3 steps you suggested. Unfortunately the problem persists. I've attached the latest build log for the Python wrapper in case that helps.

Btw, could issue [1710 ](https://github.com/CoolProp/CoolProp/issues/1710) be related?

**Comment by whunter7** [comment]
It looks like the INCOMP backend doesn't build properly if any json-file in /dev/incompressible_liquids/json contains a 1D array of coefficients for a (exp)polynomial fit.

After running `python all_incompressibles.py`, some some json-files are updated with new fitting functions and coefficients. The first file on the list alphabetically that gets a new fit with a 1D array of coefficients for an exppolynomial fit is DowJ:

Original:

` "viscosity": {
    "NRMS": 9.360408e-03,
    "coeffs": [
      7.061790e+02,
      -6.414427e+01,
      1.008341e+01
    ],
    "type": "exponential"
  },`

After `python all_incompressibles.py`:

`  "viscosity": {
    "NRMS": null,
    "coeffs": [
      -250.0,
      1.5,
      10.0
    ],
    "type": "exppolynomial"
  },`

If I remove any json files with 1D coefficient lists for polynomial fits, or make them 2D arrays in the json, i.e.:

`  "viscosity": {
    "NRMS": null,
    "coeffs": [
      [
      -250.0,
      1.5,
      10.0
      ]
    ],
    "type": "exppolynomial"
  },`

then the backend builds fine. However, the new fit for DowJ is also wrong.

So it looks like some problem in the happens during fitting and generating the json files. I've attached the output ([log.txt](https://github.com/CoolProp/CoolProp/files/4633151/log.txt)) from `python all_incompressibles.py`.

**Comment by whunter7** [comment]
I think this can be fixed with ``PR#1957``.
