### ISSUE TITLE
Questions on the changes in the 6.4.0 release

### ISSUE THREAD

**Issue by fwitte** [CoolProp/CoolProp#1935]
Hi guys,
first of all, thank you very much for rolling out the new release, I am happy to see that. I have two questions on the new release, as a test of my software failed after upgrading and came up with these "issues".

- Did the reference state of the fluids change? I have found some enthalpy values of NH3 changed for given temperature and pressure (see first code). This is not a real issue, just curious to know. I did not find the changelog.
``` python
import CoolProp as CP

state.update(CP.PT_INPUTS, 5e5, 273.15-5)
print(state.hmass())
state.update(CP.PQ_INPUTS, 5e5, 0)
print(state.hmass())
```
version 6.3.0:
320189.19694840134
362357.71653467254

version 6.4.0:
322740.9804494608
364894.63839357405

- I found a change for PT inputs at T_triple for NH3: No value is found in version 6.4.0, if the pressure higher than about 0.9 * maximum pressure (see second code). In version 6.3.0 there were no "errors".
``` python
import numpy as np
import pandas as pd
import CoolProp as CP

state = CP.AbstractState('HEOS', 'NH3')

T_trip = state.trivial_keyed_output(CP.iT_triple)

p_range = np.geomspace(
    state.trivial_keyed_output(CP.iP_min),
    state.trivial_keyed_output(CP.iP_max),
    500)

df = pd.DataFrame(columns=['success'])

for p in p_range:
    success = False
    try:
        state.update(CP.PT_INPUTS, p, T_trip)
        success = True
    except ValueError:
        pass

    df.loc[p] = success

print(df[df['success'] == False])
```
Again, thank you very much and have a nice day!
Francesco

**Comment by thorade** [comment]
There will probably be some changelog once the release also appears here:
https://github.com/CoolProp/CoolProp/releases
https://github.com/CoolProp/CoolProp/tags

There seem to be no changelogs on PyPi, also for older releases:
https://pypi.org/project/CoolProp/#history

**Comment by ibell** [comment]
The EOS has been updated: http://www.coolprop.org/fluid_properties/fluids/Ammonia.html#references

Changelog here: http://www.coolprop.org/coolprop/changelog.html

**Comment by fwitte** [comment]
Thanks to both of you!

> The EOS has been updated: http://www.coolprop.org/fluid_properties/fluids/Ammonia.html#references

I understand, that for this reason PT_INPUTS at T_triple are not supported anymore over the full value range from P_min to P_max?

**Comment by ibell** [comment]
The failures are a bug, not a feature :)  Can you please file a new issue with this problem and I'll investigate?  And this did work before?

The paper about the EOS is not yet published/written ...

**Comment by fwitte** [comment]
Okay, opened an issue at https://github.com/CoolProp/CoolProp/issues/1936. Closing this then, thank you.
