### ISSUE TITLE
Weird, weird behavior with wheels

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1937]
I don't have a complete view of this issue yet, but when I run code in PDSim that uses CoolProp, I get a super weird code path where the input to keyed_output is Smolar_residual when it should be Dmass.  I can't explain this behavior.  When I build from source, this problem doesn't occur and things make sense.  So it seems like a memory corruption of some kind, but coverity scan was giving me 503 errors when I try to check the coverity report.  I don't know what would have changed to cause this issue.  Perhaps it is something subtle in the new PCSAFT backend?

**Comment by ibell** [comment]
@jowr @thorade have you had any sort of similar experience?

**Comment by jowr** [comment]
Is this Python-only or are there also other corrupted builds?

**Comment by ibell** [comment]
I'm not yet sure...

**Comment by thorade** [comment]
Sorry, have never seen that before, no idea what might cause it.
Is everything off by one? Or just random?

**Comment by ibell** [comment]
Sorry for the noise, I think this is nothing more than a Cython "feature" where if the size of the class changes, cython has no idea and quietly still "works" but is wrong.  I have no idea how to protect against this aside from recompiling PDSim every time, which is unfortunate.
