### ISSUE TITLE
also add a tag to the commit used to build 6.4

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#1938]
https://github.com/CoolProp/CoolProp/tags
https://github.com/CoolProp/CoolProp/releases

https://github.com/CoolProp/CoolProp/issues/1935#issuecomment-627923969

I could do that, but I do not know which commit exactly is the right one.

**Comment by jowr** [comment]
We should also update the changelog, I think the commit was 2ab4cbf9.
