### ISSUE TITLE
Compilation error on MacOS - clash of homebrew and system python

### ISSUE THREAD

**Issue by kit-sg** [CoolProp/CoolProp#1939]
Hi Ian,

I am trying to compile the CoolProp Mathematica wrapper on MacOS Catalina following [http://www.coolprop.org/coolprop/wrappers/Mathematica/index.html#mathematica](http://www.coolprop.org/coolprop/wrappers/Mathematica/index.html#mathematica).
I am using homebrew with python 3.7.7 installed, up-to-date and set as the global python default version.
 
When trying to compile the Mathematica wrapper of CoolProp using
 `cmake .. -DCOOLPROP_MATHEMATICA_MODULE=ON -DCMAKE_VERBOSE_MAKEFILE=ON`, 
I notice that the MacOS system version of python 2.7 is used instead of the global python 3.7.7 according to the following terminal output:
 -- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.16", minimum required is "2.7") 

When building CoolProp using `cmake --build .`, the following error occurs:
/usr/bin/python2.7 /Volumes/.../CoolProp/dev/generate_headers.py
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/usr/bin/python2.7 /Volumes/.../CoolProp/dev/generate_headers.py'
make[2]: *** [CMakeFiles/generate_headers] Error 2
make[1]: *** [CMakeFiles/generate_headers.dir/all] Error 2
make: *** [all] Error 2

How can I build CoolProp with Python 3.7.7 and possibly avoid this error?
 
Best regards,
Steffen

**Comment by ibell** [comment]
I believe you want to pass the absolute path to Python with
-DPYTHON_EXECUTABLE=/path/to/python

**Comment by kit-sg** [comment]
Thanks Ian. This addresses the right python version.

The error above, however, was not due to the system python, but due to brackets "(...)" in the CoolProp directory name.

Regards, Steffen

**Comment by ibell** [comment]
Funny that was the problem, glad to hear it's sorted
