### ISSUE TITLE
Help with DLL hell

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#1942]
Related to #1940 , I cannot find a way to build wheels for python 3.7 or 3.8 without a dependency on vcruntime140_1.dll (which is in general not available). I have tried to install 2015 community, but it is ignored and 2019 community is used instead. I tried build tools 2019, with the same dependency problem as recommended by https://wiki.python.org/moin/WindowsCompilers . I tried to install build tools 2015, which doesn't solve the problem either.  If Anaconda would package the new runtimes, problem over, but they refuse to.

What is a working solution in 2020 to build wheels for python on windows that "just work"?

The only solution I have found so far (and which I don't like to recommend) is to install the updated c++ runtimes.

**Comment by jowr** [comment]
Well, upgrading the setuptools package installs all you need to build the software: https://wiki.python.org/moin/WindowsCompilers

But during runtime, we might have to deal with a package like this: https://pypi.org/project/msvc-runtime/

Maybe we should include a dependency?

**Comment by ibell** [comment]
Can you confirm that the msvc_runtime fixes this problem?  If so, it would be a simple fix to add the dependency to the setup.py file.

The build is not a problem, happily builds with visual studio 2019.

**Comment by ibell** [comment]
I think I fixed this with `install_requires``

**Comment by jowr** [comment]
We should use a specific version. The DLLs have to match the compiler and I think that MSVC 2019 (toolset 14.2) is compatible with MSVC 2017 (toolset 14.1), but not with earlier versions.

**Comment by ibell** [comment]
It seems that just installing the newest msvc_runtime with pip does the
trick, or do you have a more specific recommendation? My understanding is
that this includes all of the runtimes, for 2015, 2017, and 2019

**Comment by ibell** [comment]
Still not fixed...  Tried on a fresh windows 10 VM, msvc_runtime installs the right DLLs, but the location of the runtime doesn't get added to the PATH, so CoolProp doesn't load.  Inside a conda environment, it should work because the activation of the environment adds the right folders to the path.

**Comment by ibell** [comment]
Fixed by forcing the use of an older MSVC via its vcvarsall.bat
