### ISSUE TITLE
coolprop in MathCAD - current version problem

### ISSUE THREAD

**Issue by kamil-smierciew** [CoolProp/CoolProp#1944]
Hi guys,
I would like to ask for help with CoolProp. I'm using it with Mathcad and Excel, I have downloaded the latest version (6.4) for both:  Mathcad and Excel. I don't have problem with Excel, however, Mathcad still reads this as version 6.1.1. It didn’t' saw version 6.2, or 6.3 and now it can't see 6.4. Do you have any idea what is the reason? Did I missed something?

**Comment by ibell** [comment]
Can you please show a screenshot or so? Can you please also show where you
downloaded the file for 6.4.0 from?

**Comment by kamil-smierciew** [comment]
location of wrappers:
c:\Program Files\PTC\Mathcad Prime 6.0.0.0\Custom Functions\
![01](https://user-images.githubusercontent.com/66551080/83971940-021ecb00-a8de-11ea-8e0c-59f09cc8e7ff.jpg)

MathCad returns: get_global_param_string ( "version") "6.1.1dev"
![03](https://user-images.githubusercontent.com/66551080/83972009-4ca04780-a8de-11ea-9b72-65f2b5ad952f.jpg)

Files are downloaded from: https://sourceforge.net/projects/coolprop/files/CoolProp/nightly/MathCADPrime/

![02](https://user-images.githubusercontent.com/66551080/83972041-69d51600-a8de-11ea-93da-1c2b8701f93f.jpg)

**Comment by henningjp** [comment]
@kamil-smierciew CoolProp is notorious for not updating values that were previously calculated and saved.  The file you are opening (the downloaded examples file) has not been updated since it was saved with CoolProp 6.1.1dev, when I created it.  It hasn't needed to be.  So when you open it, you get:

![CoolPropVersion](https://user-images.githubusercontent.com/17114032/84070539-4a9bbe80-a99a-11ea-8a2f-8f6935fe8ee0.PNG)

Just select the equation and press <F5> to force recalculate the function, or click anywhere in the file and press <Ctrl>F5 to recalculate the whole sheet.  You should see:

![CoolPropVersion64](https://user-images.githubusercontent.com/17114032/84070650-7a4ac680-a99a-11ea-8cb9-0c4189c52f44.PNG)

Your DLL version is most likely the correct version, given the date on the file.
- Jeff

**Comment by henningjp** [comment]
Annoying, I know, but it's supposed to be an "efficiency" feature.

**Comment by kamil-smierciew** [comment]
It works,
thanks a lot!

Kamil

**Comment by GLardner** [comment]
Sorry to wake this up after several years but I am experiencing a similar issue. Excel shows CoolProp version is "6.5.0" but Mathcad Prime 9.0.0.0 shows version "6.4.0" even after recalculating (it was showing "6.1.1dev" before recalculating).

Where does Mathcad look for the CoolProp DLLs and why should it not see the new version installed today?

**Comment by ibell** [comment]
Sorry, but no idea, I am not a MathCAD person. @henningjp

**Comment by henningjp** [comment]
Mathcad loads the DLL fron the Custom Functions folder in the Mathcad Prime Installation Directory.  In your case this will be C:\Program Files\PTC\Mathcad Prime 9.0.0.0.  There’s a folder for each Mathcad version installed, even old ones left behind.  The CoolProp wrapper DLL **_must_** be copied to the Custom Functions folder for the current version of Mathcad you are using.  

You can copy the DLL from an older version directory, or get a newer version from SourceForge.

Only one version of the CoolProp DLL should exist in any version‘s Custom Functions folder.

**Comment by henningjp** [comment]
I see that the README for the Mathcad wrapper is in need of an update in this regard.   I‘ll take care of that.

**Comment by henningjp** [comment]
@GLardner - Did the above explanation help?

**Comment by henningjp** [comment]
@ibell - It looks like as of 6.4.2, the individual package add-ins are no longer being compiled on Source Forge by the build-bot.  We had this working pretty good for Mathcad as it needs it's own specific wrapper DLL.  Without it, folks have to get a compiler and build their own.  Can we restore this functionality or is this a shift in what we are going to provide?

**Comment by ibell** [comment]
Currently, the builds all happen on github action nodes because buildbot
became impossible to maintain. Therefore we can only build open-source
things automagically. But we can build (someone can) anything else for the
release and we can upload that.

**Comment by GLardner** [comment]
Thank you for the explanation.

**Comment by henningjp** [comment]
@ibell - So, can I compile the back release versions and upload them to SourceForge as an admin?  Is it that easy? Do we need to discuss off-line?

**Comment by henningjp** [comment]
@GLardner - Working on this.  For now use 6.4.1, which is available on SourceForge.

**Comment by jowr** [comment]
Hi - have a look at: https://sourceforge.net/projects/coolprop/files/CoolProp/6.5.0/MathcadPrime/

**Comment by GLardner** [comment]
Hi Jorrit, Thank you. That works in Mathcad 8 and 9.

 

From: Jorrit Wronski ***@***.***> 
Sent: Monday, September 18, 2023 8:40 AM
To: CoolProp/CoolProp ***@***.***>
Cc: GLardner ***@***.***>; Mention ***@***.***>
Subject: [allowed] Re: [CoolProp/CoolProp] coolprop in MathCAD - current version problem (#1944)

 

Hi - have a look at: https://sourceforge.net/projects/coolprop/files/CoolProp/6.5.0/MathcadPrime/

**Comment by henningjp** [comment]
Thanks @jowr !   Updating the README and Web docs soon.

**Comment by henningjp** [comment]
@GLardner If you haven't seen, Mathcad Prime library is now being automatically built again on [SourceForge](https://sourceforge.net/projects/coolprop/files/CoolProp/) for major versions and nightly builds.  The DLL and example file is located in the **Mathcad Prime** folder.

**Comment by GLardner** [comment]
@henningjp Thank you for bringing this to my attention. Yes, it is working for me now, and since v6.5.0, though I did have to force a recalculation to see the correct result.
