### ISSUE TITLE
calc speed on python 

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#1945]
hi ,i have a speed issue about coolprop on python
### Description
too slow，
### Steps to Reproduce
coolprop python wapper , install from pypi.
pycharm with python 3.7 ,on windows 10 os. 

when i calc on vb.net the same code ，much faster，about 50+ times faster

### Versions

**CoolProp Version:6.3.0
**Operating System and Version: windows 10
**Access Method: pycharm  with python3.7 , coolprop wapper install form pypi
### Additional Information

if seems python's problem，what can i do to speedup my python code？
```python
from __future__ import print_function
import time
t1 = int(round(time.time() * 1000000))
i=0
j=0
z=0
while i<100000000:
    while j<100000000:
        z=i+j
        i+=1
        j+=1

t2 = int(round(time.time() * 1000000))
print(z)
print((t2 - t1) / 1000, 'ms')
#28274.25 ms
```
```vb.net
        Dim i As Integer = 0
        Dim j As Integer = 0
        Dim z As Integer = 0
        While i < 100000000
            While j < 100000000
                z = i + j
                i = i + 1
                j = j + 1
            End While
        End While

        MsgBox(z)
'just about 1or2 second
```

**Comment by ibell** [comment]
I don't think I see any calls to coolprop in there? Also want to use low
level interface. And consider cython to spread up general python code.
