### ISSUE TITLE
Units for sigma in PC-SAFT backend

### ISSUE THREAD

**Issue by ianhbell** [CoolProp/CoolProp#1948]
The units for sigma should be Angstrom, rather than 1/Angstrom.  This issue arises in the schema as well as the fluid data for PC-SAFT backend. E.g.:

``` JSON
      "sigma": {
        "description": "Segment diameter (1/Angstrom)",
        "type": "number",
        "minimum": -2,
        "maximum": 6
      },
      "sigma_units": {
        "description": "Units of the segment diameter provided",
        "enum": [
          "1/Angstrom"
        ]
      },
```

**Comment by ianhbell** [comment]
@zmeri can you look into this? It's a quick replace-all I think.

**Comment by zmeri** [comment]
Yes, I'll take a look

**Comment by zmeri** [comment]
Yep, I must have just made a mistake when creating the JSON file and then copied it throughout the file. It is now fixed in that PR.

**Comment by ibell** [comment]
Thanks, happens all the time to me.
