### ISSUE TITLE
calc_molar_mass not implemented for incompressible fluids

### ISSUE THREAD

**Issue by Crissefy** [CoolProp/CoolProp#1951]
Hello,

I'm trying to construct a Two Phase Fluid Table of a incompressible Fluid (HFE) for usage in Matlab/Simulink. I'm running CoolProp through a Matlab Wrapper in order to execute the command to autoconstruct the Table. For Water and other Fluids it works, however for all incompressible fluids I tested I get the same error:

```
Error using twoPhaseFluidTables>coolpropPyInitialize (line 736)
CoolProp failed to initialize for 'INCOMP::HFE'.

Error in twoPhaseFluidTables>initialize (line 326)
        coolpropPyInitialize(installPath, substance);

Error in twoPhaseFluidTables (line 97)
        = initialize(installPath, substance); %#ok<ASGLU>

Caused by:
    Error using CoolProp/CoolProp.__Props_err2 (line 340)
    Python Error: ValueError: calc_molar_mass is not implemented for this backend :
    PropsSI("M","P",0,"T",0,"INCOMP::HFE")
```

I couldn't find any lead in the existing documentation, any help would be greatly appreciated!

**CoolProp Version:** 6.4.0
**Operating System and Version:** Windows 7
**Access Method:** Matlab Wrapper, Python version is 3.7

![grafik](https://user-images.githubusercontent.com/67171713/85183361-c398f100-b28b-11ea-9135-7b7f94b6fea1.png)

**Comment by ibell** [comment]
The fluids in the incompressible backend are treated as single-phase
liquids that are incompressible, so I don't think your approach will ever
work?  In general, not all methods are implemented for all backends, and
molar mass seems to not be implemented for the incompressible backend.

**Comment by Crissefy** [comment]
Thank you for the quick and clear response!
