### ISSUE TITLE
Reference for Hydrogen Nitrogen betaT and betaV binary pair data

### ISSUE THREAD

**Issue by stuart-nolan** [CoolProp/CoolProp#1953]
EDIT: I just noticed that the current betaT and betaV values in coolprop are the inverse of those reported in ref 31...  is this just the result of a typo or something related to how the equations are implemented (i.e. changing the order of the components requires using the inverse of these parameters)?

I noticed that the Hydrogen Nitrogen mixture betaT and betaV binary pair data values used in CoolProp (v 6.4.0) do not seem to match those reported in ref [31](https://pubs.acs.org/doi/10.1021/je300655b) (they do match the values documented [here](http://coolprop.org/fluid_properties/Mixtures.html#binary-pairs)).  In particular:

```
import CoolProp as cP

c1="Hydrogen"
c2="Nitrogen"
CAS_c1=cP.CoolProp.get_fluid_param_string(c1,'CAS')
CAS_c2=cP.CoolProp.get_fluid_param_string(c2,'CAS')
print("betaT: %.4f;" % float(cP.CoolProp.get_mixture_binary_pair_data(CAS_c1,CAS_c2,'betaT')))
print("betaV: %.4f;" % float(cP.CoolProp.get_mixture_binary_pair_data(CAS_c1,CAS_c2,'betaV')))
betaT: 1.0569;
betaV: 1.0282;
```
but ref 31 reports:
```
system    betaV          betaT
N2-H2     0.972532065    0.946134337
```

If I try to compare an H2-N2 HEOS mixture using the betaT, betaV values reported either in ref 31 or using current CoolProp values with experimental VLE data (at cyrogenic temperatures), both sets of values perform poorly reproducing the system pressure given a temperature and liquid mole fraction.

The betaT and betaV values currently in CoolProp do seem to perform better but no nearly as well as fitting a kij to the data using CoolProp's Peng-Robinson EOS (so I can work around this).  

I've seen hints that "GERG-2008 model" does not do well for this system at cryogenic temperatures so I'm not surprised but I am curious as the origin of the values currently in use and their range of applicability.

Can you provide some background, a reference, or just a link regarding the origin of the values currently in use?

**Comment by ibell** [comment]
First issue: 
I think you running into a common issue: betaT and betaV are reciprocals if you flip the order of components.  You can see the correct values from querying the state directly, which is more informative than the methods you are using.
```python
import CoolProp.CoolProp as CP
AS = CP.AbstractState('HEOS', 'Nitrogen&Hydrogen')
for k in ['betaT','gammaT','betaV','gammaV']:
    print(k, AS.get_binary_interaction_double(0,1,k))
print('---')
AS = CP.AbstractState('HEOS', 'Hydrogen&Nitrogen')
for k in ['betaT','gammaT','betaV','gammaV']:
    print(k, AS.get_binary_interaction_double(0,1,k))
```
yields
```
betaT 0.9461343370000002
gammaT 1.175696583
betaV 0.9725320649999999
gammaV 0.970115357
---
betaT 1.0569323624494984
gammaT 1.175696583
betaV 1.0282437319945847
gammaV 0.970115357
```

Second issue: the GERG-200X models do poorly for mixtures with hydrogen.  This is a known issue, and my colleagues are working on fitting new models that will repair the deficiencies in the existing models.

**Comment by stuart-nolan** [comment]
Thank you for explaining and for your efforts on this.
