### ISSUE TITLE
use low-level api in excel vba

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#1954]
I have already read the introduce in http://www.coolprop.org/coolprop/LowLevelAPI.html#introduction

how can i do to call low-level api in excel vba ？  or vb.net  ，the wapper is a dll。。。

**Comment by ibell** [comment]
Yes, it is possible, by calling the AbstractState_XXX functions that are exposed in the DL: https://github.com/CoolProp/CoolProp/blob/master/include/CoolPropLib.h .

**Comment by birdol** [comment]
i have try the AbstractState_XXX function in excel vba， but it's not work for my application，need any other .xla add-on file？

**Comment by ibell** [comment]
Well you need to define the interfaces to the functions.  Please show what
you've tried so far.
