### ISSUE TITLE
Wrapper PHP can't compile 

### ISSUE THREAD

**Issue by andrelec1** [CoolProp/CoolProp#1955]
### Description

Error when i try to compile the  coolprop.so for php

### Steps to Reproduce

fresh install debian10
follow the doc => http://www.coolprop.org/dev/coolprop/wrappers/PHP/index.html

**Expected behavior:** 
compile success

**Actual behavior:** [What actually happens]

```
\\\ ....

/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17467:3: error: ‘__wrap_delete_PhaseEnvelopeData’ was not declared in this scope
   __wrap_delete_PhaseEnvelopeData(rsrc, SWIGTYPE_p_CoolProp__PhaseEnvelopeData->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17467:3: note: suggested alternative: ‘_wrap_new_PhaseEnvelopeData’
   __wrap_delete_PhaseEnvelopeData(rsrc, SWIGTYPE_p_CoolProp__PhaseEnvelopeData->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   _wrap_new_PhaseEnvelopeData
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx: In function ‘void _wrap_destroy_p_CoolProp__GuessesStructure(zend_resource*)’:
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17470:34: error: ‘rsrc’ was not declared in this scope
   __wrap_delete_GuessesStructure(rsrc, SWIGTYPE_p_CoolProp__GuessesStructure->name TSRMLS_CC);
                                  ^~~~
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17470:3: error: ‘__wrap_delete_GuessesStructure’ was not declared in this scope
   __wrap_delete_GuessesStructure(rsrc, SWIGTYPE_p_CoolProp__GuessesStructure->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17470:3: note: suggested alternative: ‘_wrap_new_GuessesStructure’
   __wrap_delete_GuessesStructure(rsrc, SWIGTYPE_p_CoolProp__GuessesStructure->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   _wrap_new_GuessesStructure
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx: In function ‘void _wrap_destroy_p_CoolProp__AbstractStateGenerator(zend_resource*)’:
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17473:40: error: ‘rsrc’ was not declared in this scope
   __wrap_delete_AbstractStateGenerator(rsrc, SWIGTYPE_p_CoolProp__AbstractStateGenerator->name TSRMLS_CC);
                                        ^~~~
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17473:3: error: ‘__wrap_delete_AbstractStateGenerator’ was not declared in this scope
   __wrap_delete_AbstractStateGenerator(rsrc, SWIGTYPE_p_CoolProp__AbstractStateGenerator->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17473:3: note: suggested alternative: ‘_swigc__p_CoolProp__AbstractStateGenerator’
   __wrap_delete_AbstractStateGenerator(rsrc, SWIGTYPE_p_CoolProp__AbstractStateGenerator->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   _swigc__p_CoolProp__AbstractStateGenerator
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx: In function ‘void _wrap_destroy_p_CoolProp__Configuration(zend_resource*)’:
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17476:31: error: ‘rsrc’ was not declared in this scope
   __wrap_delete_Configuration(rsrc, SWIGTYPE_p_CoolProp__Configuration->name TSRMLS_CC);
                               ^~~~
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17476:3: error: ‘__wrap_delete_Configuration’ was not declared in this scope
   __wrap_delete_Configuration(rsrc, SWIGTYPE_p_CoolProp__Configuration->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/CoolProp/build/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx:17476:3: note: suggested alternative: ‘_wrap_new_Configuration’
   __wrap_delete_Configuration(rsrc, SWIGTYPE_p_CoolProp__Configuration->name TSRMLS_CC);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   _wrap_new_Configuration
make[2]: *** [CMakeFiles/CoolProp.dir/build.make:66: CMakeFiles/CoolProp.dir/CMakeFiles/CoolProp.dir/CoolPropPHP_wrap.cxx.o] Error 1
make[2]: Leaving directory '/root/CoolProp/build'
make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/CoolProp.dir/all] Error 2
make[1]: Leaving directory '/root/CoolProp/build'
make: *** [Makefile:133: all] Error 2

```

### Versions

**CoolProp Version:**  clonned :  e2b8d10
**Operating System and Version:** 
 debian 9 ( server prod ), 
 ubuntu 18.04 ( serveur test ),
 debian 10 (fresh vm for testing). 

same kind of error...

### Additional Information

I have successfully compiled the wrapper on my ubuntu mate 20.4 something like a month before ...
i try to use the so compiled on my pc for the server, but  seen a error saying the libc isn't the same version ...

**Comment by ibell** [comment]
What versions of PHP and swig?  My recollection is that there is a limited
set of combinations that actually work.

**Comment by andrelec1** [comment]
each server have php5.6 / php7.0 / php7.1 / php7.2 / php7.3 
for swig i see on my machine 4.01 , on my prod server ( debian 9 ) swig is on 3.0.10 and 3.0.12 for my ubuntu server...

**Comment by andrelec1** [comment]
Ok,  on annoter computer i successfully compule with swig 4.0.1 !

**Comment by andrelec1** [comment]
OK found the issue ...
i have swig3.0 installer on server ... and i compile / install the 4.0.1 manualy 

so when i run the `cmake .. -DCOOLPROP_PHP_MODULE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON' 

cmake take swig3 ...

remove swig3, reinstall swig4 and it work ...

**Comment by birdol** [comment]
hi,andrelec1.

would you upload the bin file  coolprop.so for php7.3 ?  
i had try many times and its won't work.

**Comment by andrelec1** [comment]
compiled on my machine ( ubuntu 20.04 ) => 
[coolProp6.4_php7.3.zip](https://github.com/CoolProp/CoolProp/files/4858039/coolProp6.4_php7.3.zip)

compiled on my prod server ( debian 9 ) => 
[coolProp6.4_php7.3_debian.zip](https://github.com/CoolProp/CoolProp/files/4858051/coolProp6.4_php7.3_debian.zip)

**Comment by ibell** [comment]
Can you possibly post the full build shell output for the working build?
That would be useful to know how to update the docs

**Comment by andrelec1** [comment]
## add php repo

    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update

## install tools 

    sudo apt install git cmake build-essential libc6 libpcre3-dev php7.3 php7.3-dev
 
## SWIG
### remove swig ...
#### find swig 
    dpkg --list | grep swig
![image](https://user-images.githubusercontent.com/3273204/86389720-0e0c6b80-bc97-11ea-82b5-1a4219a48c42.png)

#### uninstall
     sudo apt remove swig3.0

### install last version of swig ....
#### download
https://sourceforge.net/projects/swig/files/swig/
    *tips: get the url from sourceforge and remove jute the `/download` at the end

    wget https://sourceforge.net/projects/swig/files/swig/swig-4.0.2/swig-4.0.2.tar.gz

#### untar 
    tar -xzvf swig-4.0.2.tar.gz && rm swig-4.0.2.tar.gz && cd swig-4.0.2

#### config compile and install ...
    ./configure --prefix=/usr --without-maximum-compile-warnings 
if there are no error

    make
    sudo make install
    sudo install -v -m755 -d /usr/share/doc/swig-4.0.2
    sudo cp -v -R Doc/* /usr/share/doc/swig-4.0.2

#### and leave directory 
    cd ...

## CoolProp
### download
    git clone https://github.com/CoolProp/CoolProp --recursive
### Folder creation
    mkdir -p CoolProp/build && cd CoolProp/build
### make php module
    cmake .. -DCOOLPROP_PHP_MODULE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON

check if is the right version of swig and php is used ...
![image](https://user-images.githubusercontent.com/3273204/86391771-a0623e80-bc9a-11ea-81dd-c40068419e1a.png)

### build
    cmake --build .

#### extra step 
i don't know why but some time the binarie name is `CoolProp.so` and some time is `libCoolProp.so` depends on your os ...
rename the binarie if needed ... 
     mv CoolProp.so libCoolProp.so

### copy the so a the right place
    sudo cp libCoolProp.so `php-config --extension-dir`

### create a ini file for the extention
   echo "; configuration for php CoolProp module\n; priority=20\nextension=libCoolProp.so" | sudo tee -a /etc/php/7.3/mods-available/coolprop.ini

### activate the extention
    sudo phpenmod coolprop

### check 
    php -r "echo phpinfo();" | grep -A 7 "Additional Modules"

**Comment by ibell** [comment]
@Teddy thanks for putting together such detailed instructions
