### ISSUE TITLE
Docs do not build

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1960]
The root cause for #1933 seems to be a problem with the Sphinx builds - this should also be fixed for v6.4.1.

**Comment by jowr** [comment]
OK we are getting closer:

- the buildbot calls docs_runner.sh
   - that builds a docker image from Web/docker/docworker.Dockerfile 
   - creating a conda environment called docs
   - and then runs Web/docker/build_docs.sh in the container
- Inside the container we call Web/scripts/__init__.py
   - that calls dev/scripts/examples/LinuxRun.py
   - that import dev/scripts/examples/example_generator.py and generates examples
   - and the launches CMake builds 
   - that **also** generate the examples and this fails.

**Comment by jowr** [comment]
I think I fixed it. Maybe we can review http://www.coolprop.org/dev/ together and check that all went well.

**Comment by ibell** [comment]
Sure, drop me a line and we can discuss.

**Comment by jowr** [comment]
I fixed the example generator and the Java builds - As soon as the docs are ready, I guess we can release 6.4.1.

**Comment by jowr** [comment]
Looks like it works now, but the build process and the script surely could use some serious streamlining...
