### ISSUE TITLE
Release v6.4.1?

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1961]
Is there anything that keeps us from releasing v6.4.1?

**Comment by ibell** [comment]
I don't think there are any other blocking issues. Can you make the release?

**Comment by jowr** [comment]
Yes, I’ll prepare it later tonight.

On 3 Aug 2020, at 19.16, Ian Bell <notifications@github.com> wrote:

﻿

I don't think there are any other blocking issues. Can you make the release?
