### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AdrianoUFVJM** [CoolProp/CoolProp#1970]
C:\Users\reisa\CoolProp\build>cmake .. -DCOOLPROP_OCTAVE_MODULE=ON -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=11
-- COOLPROP_INSTALL_PREFIX=C:/Users/reisa/CoolProp/install_root
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:150 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:150 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/Users/reisa/CoolProp/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/reisa/CoolProp/build/CMakeFiles/CMakeError.log".

**Comment by AdrianoUFVJM** [comment]
Please help!

**Comment by ibell** [comment]
Please read the docs: http://www.coolprop.org/coolprop/wrappers/Octave/index.html#octave . You need to have a compiler installed, as described there.  See http://www.coolprop.org/coolprop/wrappers/Octave/index.html#windows

Also, you might be interested to see how we do the builds for windows on our build system: http://www.coolprop.dreamhosters.com:8010/builders/Octave-windows/builds/2525 (click on the build steps on the left side in green).

In the future, please fill out the issue template in its entirety

**Comment by AdrianoUFVJM** [comment]
Ok, Thanks, But I will not use on windows I will use on linux now.

thanks so much!!!
