### ISSUE TITLE
Refrigerant 2-phase Cp, Thermal conductivity value error

### ISSUE THREAD

**Issue by raccoon1007** [CoolProp/CoolProp#1973]
Hello,

I'm using CoolProp in Excel and Autohotkey with CoolProp_x64.dll. (Ver 6.4.1)
I found Cp and Thermal conductivity value error at some refrigerant 2-phase condition

For example, If I try to find Cp with below condition
1. Refrigerant : R134A
2. Pressure : 1101kPaA
3. Quality(x) : 0.4

Negative value is shown -8645 J/kg.K
This must be wrong...

Another refrigerant(R1234yf) also has a same problem.

How can I fix it? Is there anybody who could advise me?

Thanks in advance!

**Comment by jowr** [comment]
Please do not use cp or transport properties in the two-phase region. They are not defined there and the results will always be wrong / misleading.

**Comment by raccoon1007** [comment]
> Please do not use cp or transport properties in the two-phase region. They are not defined there and the results will always be wrong / misleading.

Thanks for your kind answer, very helpful!, one more question,  Does Refprop have a same problem?
