### ISSUE TITLE
AbstractState class from shared library question

### ISSUE THREAD

**Issue by sgolle** [CoolProp/CoolProp#1978]
I have a question about the usage of the shared library. Is it possible to use the CoolProp low level interface (AbstractState class) from the compiled shared library? The analysis of the library with nm shows that there is no AbstractBase class but some AbstractBase_* methods.

I would like to extend the Rust Wrapper with the low level interface #1977

**Comment by ibell** [comment]
Not directly, no.  The only access is through the high-level interface functions, which expose a subset of the functionality of the low-level interface.

**Comment by sgolle** [comment]
How is this achieved in the Python wrapper?

**Comment by ibell** [comment]
Direct use of c++ classes, see the files in wrappers/Python/CoolProp

**Comment by sgolle** [comment]
Thank you! It seems, that the implementation is a lot of work.

**Comment by ibell** [comment]
That is correct, but worth it if rust has some facility for doing semi-automatic extraction of the C++ API.
