### ISSUE TITLE
Wrong alias in "R1243zf.json"

### ISSUE THREAD

**Issue by hamidrezahassani** [CoolProp/CoolProp#1980]
Dear Mr. Bell:

I found a problem in the following JSON-file: 
"/dev/fluids/R1243zf.json"

The alias of this fluid (line 273) must be changed to "R12**43**ZF".

P.S.: The current wrong alias is "R12**34**ZF".

Best regards from Brunswick,
Hamidreza Hassani

**Comment by ibell** [comment]
Thanks for the report; fixed.
