### ISSUE TITLE
Humid air calculation problem

### ISSUE THREAD

**Issue by raccoon1007** [CoolProp/CoolProp#1991]
Hello,

I'm using CoolProp in Excel and Autohotkey. This is really helpful to my works.

I have a problem when I'm looking for W(kg/kg)

If I'm trying to find W as below
(Given data : Pressure, T_wb, Enthalpy)

=HAPropsSI("W","P",101325,"B",284.15,"H",18588)

the result always shows "0",, Please advise me thanks in advance.

**Comment by ibell** [comment]
I thought I had tested every possible set of inputs in HAPropsSI and all were working.  Evidently not.  What version of CoolProp do you use?

**Comment by raccoon1007** [comment]
I'm using v6.4.0.0 thanks!

**Comment by ibell** [comment]
This is a really challenging iteration type since neither variable is dry bulb temperature and mole fraction of water vapor. I thought I had fixed all the iteration pairs. Can you try with the development branch?

**Comment by raccoon1007** [comment]
Sorry I didn't get the meaning of the development branch, what is it?

**Comment by ibell** [comment]
Second link here:
http://www.coolprop.org/coolprop/wrappers/Installers/index.html#installers
pointing to
http://sourceforge.net/projects/coolprop/files/CoolProp/nightly/Installers

**Comment by raccoon1007** [comment]
I don't know how to update my CoolProp correctly, I just changed CoolProp.xlam to the downloaded CoolProp.xlam,,, but it still have same issue. I guess this issue is not  important to me, because I may not use this unique pair. Hope next official version will support this unique pair. Many thanks.

**Comment by ibell** [comment]
Please run the installer from the development server, from the link I sent
before.  That's more reliable than overwriting the XLAM
