### ISSUE TITLE
Isotherms and Isentropic lines displaying wrong

### ISSUE THREAD

**Issue by haeckerman** [CoolProp/CoolProp#1998]
Hi together,
after using the example from the examples page I realized that the graph is displaying the isotherms and isentropic lines wrong.

This is the output I get:
![image](https://user-images.githubusercontent.com/78759986/107274213-58857000-6a50-11eb-99ff-8541809faa72.png)

And this is the intended output from the [website](http://www.coolprop.org/coolprop/python-plotting.html) (Third example):
![image](https://user-images.githubusercontent.com/78759986/107274281-6a671300-6a50-11eb-8505-1ece29724c2b.png)

Thank you very much for your help.

With kind regards
René

**Comment by SeeSawSeen100** [comment]
I’m not sure how to help but after coping the code from the website into a small sketch I have the same issue.
