### ISSUE TITLE
 PropsSI failed ungracefully with Water::IF97

### ISSUE THREAD

**Issue by jccberthet** [CoolProp/CoolProp#1999]
### Description

PropsSI failed ungracefully, with IF97::Water

### Steps to Reproduce

import CoolProp.CoolProp as cp
cp.PropsSI('Q', 'P', 6.4743994800040303e+06, 'H',1.2394090698400016e+06 , 'IF97::Water')

**Expected behavior:**

Expected to return zero, or something indicating that the fluid in fully liquid.

**Actual behavior:**
Raised an exception:
ValueError: PropsSI failed ungracefully :: inputs were:"Q","P",6.4743994800040303e+06,"H",1.2394090698400016e+06,"IF97::Water"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

### Versions

**CoolProp Version:** 6.4.1
**Operating System and Version:** Windows 10
**Access Method:** Python

**Comment by ibell** [comment]
Is that statepoint valid? And the only problem is the value that is returned for Q?  How about density?

**Comment by henningjp** [comment]
Other props return values in the liquid phase, Q is undefined here.  This point is _just_ outside the vapor dome in the liquid region.  HEOS returns Q = -1 (i.e.. undefined) and does not throw an error.  Nudging the IF97 enthalpy value up to 1239.795 returns a sensible Q value (Hsat is 1239.7942 at this pressure).

I think the point here is that IF97 should return _something_ other than an ungraceful failure if Q is undefined.

**_Workaround:_** The calling code should check to make sure H is inclusively between the saturated liquid value and the saturated vapor value before making the call.

**Comment by ibell** [comment]
@henningjp can you add an exception for Q < 0 or Q > 1 for surface tension?

**Comment by henningjp** [comment]
Yes, once I get through this current project.  I’ll tag it.  Should be a
quickie.

**Comment by ibell** [comment]
Thanks, yes I should think so.
