### ISSUE TITLE
Surface tension calculation 

### ISSUE THREAD

**Issue by adityasappalla** [CoolProp/CoolProp#2001]
I am trying to calculate the surface tension of water at 101325 Pa and 293.15 K, which is well within the temp limits for saturation. However, the compiler doesn't give me the result. 

`st = CP.PropsSI("I", 'T', 293.15, 'P', 101325, 'IF97::Water"); print(st)`
  
The compiler returns this error message.

`Viscosity only valid along saturation curve : PropsSI("surface_tension","T",293.15,"P",101325,"IF97::Water")`

For two phase inputs, I tried this line of code. 

`CP.PropsSI('surface_tension','PQ', 101325,0,'IF97::Water')`

It returned this error message.

`expected bytes, int found`

Please help me.

Python version 3.8.5
Windows 10

**Comment by ibell** [comment]
You want: ``CP.PropsSI('surface_tension','P', 101325,'Q',0,'IF97::Water')`` (or same basic thing with Q,T)

**Comment by adityasappalla** [comment]
@ibell thanks for your help.
