### ISSUE TITLE
Isentropic process in CoolProp: HSU_P_flash, phase envelope and fluid property mismatch against mixtures

### ISSUE THREAD

**Issue by adityasappalla** [CoolProp/CoolProp#2004]
The issue has basically 2 sub-issues, both relating to an isentropic compression process. Issue #2002 also highlights the same. 

An isentropic process is a theoretical process where the entropy of the fluid remains same as it moves from one thermodynamic state point to the next. The fluid property at state - 2 is derived using the entropy at state - 1, a sort of round-tripping. 

I am trying to isentropically compress air from 1 bar and 15 C to 12.6 bar. The code for enthalpy and entropy are below. 

`h1 = CP.PropsSI('H','T',288.15,'P',100000,'Air');print(h1)
s1 = CP.PropsSI('S','T',288.15,'P',100000,'Air');print(s1)`

The output is as such for the lines above: 

`414377.8320937835
3849.9520779356976`

I use the isentropic algorithm to get to an isentropic state - 2, as below:

`h2 = CP.PropsSI('H','S',s1,'P',1260000,'air');print(h2)`

The actual output is as such: 

`721612.16008741`

Since the fluid is air, I tried using a mixture of 79% nitrogen and 21% oxygen. The code is as below. 

`h3 = CP.PropsSI('H','T',288.15,'P',100000,'Nitrogen[0.79]&Oxygen[0.21]');print(h3)
s3 = CP.PropsSI('S','T',288.15,'P',100000,'Nitrogen[0.79]&Oxygen[0.21]');print(s3)`

The expected output is values closely matching the code that uses 'air' as the working fluid. The actual results are entirely different and nowhere near the previous values. 

`290229.82727032935
6852.930722506682`

This is the first issue. The second issue is when I use the same isentropic logic to get `h4`, the isentropic state for `h3`, with the code block below. 

`h4 = CP.PropsSI('H','S',s3,'P',1276699,'Nitrogen[0.79]&Oxygen[0.21]');print(h4)`

The expected output is a floating point value of enthalpy. The actual output is an error, below.

`phase envelope must be built to carry out HSU_P_flash for mixture : PropsSI("H","S",6852.930723,"P",1276699,"Nitrogen[0.79]&Oxygen[0.21]")`

This is the second issue. 

I request you to help me in understanding what is going on the backend of CoolProp in both cases and help me approach the isentropic process easily. 

CoolProp version: **6.4.1**
Windows version: **Windows 10 64-bit OS**
Access method: **Python 3.8.5**

**Comment by ibell** [comment]
"Air" is a pseudo-pure fluid, and behaves like a pure fluid in the algorithms.  Therefore it is no more complicated than normal pure fluids (nitrogen for instance).  Mixtures are in many ways totally unlike pure fluids.  

Enthalpy and entropy are relative properties, you should not compare them directly, only differences.  That question is even nastier for mixtures, where it gets truly confusing.

In theory, something like this should do it:
``` python
import CoolProp.CoolProp as CP
AS = CP.AbstractState('HEOS','Nitrogen&Oxygen')
AS.set_mole_fractions([0.79,0.21])
AS.update(CP.PT_INPUTS, 1e5, 288.15)
s1 = AS.smass()
h1 = AS.hmass()

AS.build_phase_envelope("")
AS.update(CP.PSmass_INPUTS, 12.6e5, s1)
print(AS.T())
```
but the second call to update gives:
``` python
Traceback (most recent call last):
  File "C:\Users\ian\Desktop\PS.py", line 9, in <module>
    AS.update(CP.PSmass_INPUTS, 12.6e5, s1)
  File "CoolProp\AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update
  File "CoolProp\AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update
ValueError: DHSU_T_flash does not support mixtures (yet)
```
So your better bet is to use conventional rootfinding:
``` python
import CoolProp.CoolProp as CP
import scipy.optimize

AS = CP.AbstractState('HEOS','Nitrogen&Oxygen')
AS.set_mole_fractions([0.79,0.21])
AS.update(CP.PT_INPUTS, 1e5, 288.15)
s1 = AS.smass()
h1 = AS.hmass()

# AS.build_phase_envelope("")
# AS.update(CP.PSmass_INPUTS, 12.6e5, s1)
# print(AS.T())

def objective(T):
    AS.update(CP.PT_INPUTS, 1.6e5, T)
    return AS.smass()-s1

# Solve for isentropic temperature
T2s = scipy.optimize.newton(objective, AS.T())
print(T2s)
# Use isentropic temp to get h2s
AS.update(CP.PT_INPUTS, 1.6e5, T2s)
s2 = AS.smass()
h2s = AS.hmass()
print(h1, h2s)
```

**Comment by ibell** [comment]
I'm not really sure why the PS call doesn't work at all, even after building the isopleth of the phase envelope.

**Comment by adityasappalla** [comment]
@ibell thanks for the update. I have tried the second rootfinding code. While it works for 1.6e5 pressure, the actual pressure I am compressing air to is 12.6e5. Anything above 1.7e5 returns this error. 

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-aefd9200d20b> in <module>
     16     return AS.smass()-s1
     17 
---> 18 T2s = scipy.optimize.newton(objective, AS.T())
     19 print(T2s)
     20 # Use isentropic temp to get h2s

~\Anaconda3\lib\site-packages\scipy\optimize\zeros.py in newton(func, x0, fprime, args, tol, maxiter, fprime2, x1, rtol, full_output, disp)
    353             p0, q0 = p1, q1
    354             p1 = p
--> 355             q1 = func(p1, *args)
    356             funcalls += 1
    357 

<ipython-input-29-aefd9200d20b> in objective(T)
     13 
     14 def objective(T):
---> 15     AS.update(CP.PT_INPUTS, 1.8e5, T)
     16     return AS.smass()-s1
     17 

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.update()

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.update()

ValueError: One stationary point (not good) for T=340.36,p=180000,z=[ 0.808188294185, 0.191811705815 ]`

The code for tried for p2 = 1.8e5.

**Comment by ibell** [comment]
Yes, this is evidence of a problem of a different sort - this is a consequence of errors in the equation of state itself that cause trouble for the P,T call.  You could do a nested call, with an inner rootfinding with T,D as inputs to get the right P (replacing the PT flash call).

But for now, better bet to use REFPROP.

**Comment by amy11223344** [comment]
This is really helpful, I have used it to model a mixture for my dissertation. If you have time would you mind explaining what the following functions mean so I can write it up in my methodology please?


> AS = CP.AbstractState('HEOS','Nitrogen&Oxygen')
> AS.set_mole_fractions([0.79,0.21])
> AS.update(CP.PT_INPUTS, 1e5, 288.15)
> s1 = AS.smass()
> h1 = AS.hmass()

**Comment by ibell** [comment]
@amy11223344 line by line we have:

1. Create an instance of the mixture model, in this case a multi-fluid mixture model, with the binary interaction parameters of http://www.coolprop.org/fluid_properties/Mixtures.html#binary-pairs (reference: http://www.coolprop.org/zbibliography.html#gernert-thesis-2013).
2. Set the mole fractions
3. Do a pressure-temperature flash calculation, to internally calculate density and other thermodynamic variables
4. Obtain specific entrpoy
5. Obtain specific enthalpy

**Comment by adityasappalla** [comment]
@ianhbell, the conventional root-finding code you have given using abstract state in this code below works for natural gas mixtures, but for low pressure ratios (3.5-5). 

```
import CoolProp.CoolProp as CP
import scipy.optimize

AS = CP.AbstractState('HEOS','methane&ethane&propane&nitrogen')
AS.set_mole_fractions([0.92,0.02,0.002,0.05])
AS.update(CP.PT_INPUTS, 2.52e6, 324.26)
s1 = AS.smass()
h1 = AS.hmass()

# AS.build_phase_envelope("")
# AS.update(CP.PSmass_INPUTS, 12.6e5, s1)
# print(AS.T())

def objective(T):
    AS.update(CP.PT_INPUTS, 5.73e6, T)
    return AS.smass()-s1

# Solve for isentropic temperature
T2s = scipy.optimize.newton(objective, AS.T())
print(T2s)
# Use isentropic temp to get h2s
AS.update(CP.PT_INPUTS, 5.73e6, T2s)
s2 = AS.smass()
h2s = AS.hmass()
print(h1, h2s)
```
Is the low pressure ratio enabling EoS to perform?  Unlike the high pressure ratio case that was earlier. What am I missing here? 

Also, can you please give a brief explanation of the same?

Thanks.

**Comment by ianhbell** [comment]
I would guess that your guessed temperature of ``AS.T()`` (input to newton) is fine as you are close to your first state, but as you move to higher pressures, the guess value is inadequate, causing failure of the iterative routine. If you can bound your guess, you should instead of ``newton`` use the ``brentq`` function.

Wikipedia has some information on rootfinding: https://en.wikipedia.org/wiki/Root-finding_algorithms
