### ISSUE TITLE
Incomplete R452a Coolprop data 

### ISSUE THREAD

**Issue by ExchangeHeat** [CoolProp/CoolProp#2015]
Hi everybody, I use an excel calculation sheet that is programmed to run a Coolprop add-in to retrieve necessary data on mediums in order to make thermodynamic calculations that are used to build heat exchangers. 

Today It did not work as intended with the medium R452a. It normally retrieves data using "@PropSI" and, with information that I fill in, it generates the "D" (density), "CPMASS" (heat capacity), "CONDUCTIVITY", "VISCOSITY", "HMASS", "SURFACE TENSION", "PRANDTL", among other things for the specific situation at hand. 
But, today, for some reason, for this medium, it retrieves all except the "CONDUCTIVITY" and "SURFACE TENSION". 

The formulas are the same for other mediums, like R134a, and work perfectly. 

The formula for conductivity is =@PropsSI("CONDUCTIVITY";"T";$E$28+273,15;"Q";0;$D$139)
I can increase the value of cell E28 arbitrarily which changes the value for conductivity from error to an actual number. But, even though Surface Tension has the same formula except for its name, the same change does not occur. 
I have tried to remove the add-in and re-connect it, without any luck. 

What can I try to solve this issue?

**Comment by ibell** [comment]
What error message do you get? Please provide a sample input demonstrating
the problem with numerical values.
