### ISSUE TITLE
PC-SAFT integration

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#2020]
Hi, 
there are some tickets and pull requests around PC-SAFT:
https://github.com/CoolProp/CoolProp/issues?q=PC-SAFT
Is it documented/explained somewhere how PC-SAFT is integrated into Coolprop?
Or, can you recommend any paper how to express/transform/combine PC-SAFT as Helmholtz energy equation of state?
Thanks for any input or pointers to relevant publications!

ping @CarlosTrujilloGonzalez

**Comment by jowr** [comment]
This has been fixed some time ago.
