### ISSUE TITLE
Coolprop Ammonia Hmass issue

### ISSUE THREAD

**Issue by leroycollavo90** [CoolProp/CoolProp#2023]
Hi

I would like to have some help with the coolprop.
The problem that i have is when i use Ammonia to calculate the "H" of an Ammonia Point it is incorrect.

For example:
=PropsSI("H";"T";3+273.15;"P";4.8;Ammonia)/1000  it gives me 1652.9 kJ/kgK
but the correct point would bei: 1463.76 kJ/kgK

Do i make a mistake ore is that a fail in the list?

Thanks for your answer

CoolProp Version:** [6.4.1]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Excel
![Coolprop](https://user-images.githubusercontent.com/84270905/118394451-1ff3c480-b645-11eb-9b11-53e28b83ab3d.png)
]

**Comment by ibell** [comment]
Please see FAQ number 1: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by leroycollavo90** [comment]
Hi, 

Thanks for your fast answer but i don't get it.
What i have to change?

Thanks

**Comment by ibell** [comment]
Nothing, there is nothing wrong!

Enthalpy and entropy are relative properties, and you should only compare
differences, not one tabulated value against another.  If you want, you can
change the reference state to match.
