### ISSUE TITLE
Erroneous water specific heat (CVMASS) computed as a function of enthalpy and pressure

### ISSUE THREAD

**Issue by bjschoenfeld** [CoolProp/CoolProp#2026]
CoolProp 6.4.1 (f5ebb4e655add4c23bb327ab5209f3dbf919bc6d) is giving me extremely large specific heat values for water when computed as a function of specific enthalpy and pressure. I am creating interpolation tables and a few occasional values are very different than the rest. The data below has specific heat values mostly on the order of 4,000, but there are some in the range of 10^12 (I have seen 10^15 in other generated tables). I compiled CoolProp myself and am wrapping it in Swift.

Here is the data I have generated:
[water_specificHeatAtConstantPressure.csv](https://github.com/CoolProp/CoolProp/files/6634736/water_specificHeatAtConstantPressure.csv)

Here is a 3D plot of the data, where x is specific enthalpy, y is pressure, and z is specific heat of water:

<img width="462" alt="Screen Shot 2021-06-10 at 4 30 45 PM" src="https://user-images.githubusercontent.com/17132161/121605200-381eef80-ca09-11eb-9b45-d0b182402b7b.png">

**Comment by ibell** [comment]
Where's the critical point?  Cp is infinite at the critical point.

**Comment by bjschoenfeld** [comment]
I did some exploration and those points are right on the phase change boundary where it makes sense to have extremely large specific heat values. CoolProp is correct. Sorry to waste your time.
