### ISSUE TITLE
matlab py.CoolProp.CoolProp.PropsSI Returns U out of bounds

### ISSUE THREAD

**Issue by wwehner** [CoolProp/CoolProp#2030]
py.CoolProp.CoolProp.PropsSI works fine with input 'PT', but not input 'UP', which is required for twoPhaseFluidTables. For example:

```
Ttest = 3000; Ptest = 7e6;  %K, Pa
Fluid = 'Hydrogen';
U_from_table = py.CoolProp.CoolProp.PropsSI('U', 'T', Ttest, 'P',Ptest, Fluid);  % [J/kg]
T = py.CoolProp.CoolProp.PropsSI('T', 'U', U_from_table, 'P',Ptest, Fluid);
```

The last line should work, since the U input was obtained from the table itself on the preceding line. But results in error (U out of bounds)

```
Error using CoolProp/CoolProp.__Props_err2 (line 344)
Python Error: ValueError: unable to solve 1phase PY flash with
Tmin=13.956, Tmax=1500 due to error: HSU_P_flash_singlephase_Brent
could not find a solution because Umolar [71842.3 J/mol] is above
the maximum value of 31769.5819421 J/mol :
PropsSI("T","P",7000000,"U",35638199.66,"H2")
```

**Comment by ibell** [comment]
Sounds like your inputs are out of bounds.  Can you adjust the limits?

**Comment by wwehner** [comment]
Yes, but I think it's erroneously declaring the inputs out of bounds. As you can see I use the 'PT' input to get an acceptable U value, then call again with the 'PU' input. How can that U be out of bounds? I obtained it directly from the table. Granted I'm not that familiar with fluids, but I can't see how a U value obtained from the table could be declared out of bounds on the second query.

**Comment by henningjp** [comment]
@wwehner - See the message and check Tmax for Hydrogen.  It's 1500K.  Not sure why the first call returns a value for "U" without throwing the same message.
