### ISSUE TITLE
Hi Team, When I try to use this code line, I get the below error message, Any suggestion, what could be going wrong?

### ISSUE THREAD

**Issue by Abhijit81** [CoolProp/CoolProp#2035]
import CoolProp.CoolProp as CP
CP.get_global_param_string('predefined_mixtures').split(',')[0:6]
CP.PropsSI('D','P',101325,'T',300,'Air.mix')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-56-280e3117be16> in <module>
      1 import CoolProp.CoolProp as CP
      2 CP.get_global_param_string('predefined_mixtures').split(',')[0:6]
----> 3 CP.PropsSI('D','P',101325,'T',300,'Air.mix')

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.__Props_err2()

ValueError: Initialize failed for backend: "?", fluid: "Air.mix" fractions "[ 1.0000000000 ]"; error: Could not match the binary pair [7440-37-1,7727-37-9] - for now this is an error. : PropsSI("D","P",101325,"T",300,"Air.mix")

**Comment by ibell** [comment]
What version do you run? I ran this script:
```python
import CoolProp
print(CoolProp.__version__)
import CoolProp.CoolProp as CP

#CP.get_global_param_string('predefined_mixtures').split(',')[0:6]
print(CP.PropsSI('D','P',101325,'T',300,'Air.mix'))
```
and I got:
```
(py38) C:\Users\ian\Desktop>python air.py
6.4.2dev
1.1766922904667523
```

**Comment by ibell** [comment]
Same result if I uncomment the commented line

**Comment by Abhijit81** [comment]
Hi ibell, somehow its working for me now, i am not sure what was the issue then, but thank you very much for looking into it.
