### ISSUE TITLE
CoolProp in Excel on Mac M1

### ISSUE THREAD

**Issue by HCSpin** [CoolProp/CoolProp#2040]
A fully functional version of CoolProp 6.3 on an Intel mac using Excel 16.52 was imported to an M1 Mini running the same code.

I was immediately hit with Error 53 (/Users/.../libCoolProp.dylib file not found).  

~/Library/LaunchAgents/my.startup.plist was set identically as before
To my knowledge, all other settings and file locations are correct and identical to the previous installation.

(I also downloaded a fresh version of CoolProp.xlam (6.4.1), updated the references to libCoolProp.dylib as indicated in Part 4b on [http://www.coolprop.org/coolprop/wrappers/Excel/index.html#excel](url) and obtained the same results.)

Is it possible I need to rebuild libCoolProp.dylib manually rather than using the one provided from SourceForge?
(Current version yields: libCoolProp.dylib: Mach-O 64-bit dynamically linked shared library x86_64)

If so, could someone please provide explicit instructions for the rebuild?

**Comment by ibell** [comment]
M1 chips not supported yet.   Please check out the other issues on this
topic.

**Comment by hzlchn** [comment]
Will it be available for M1 chips as well, if you know?

**Comment by hzlchn** [comment]
@HCSpin could you get it working by any other way?

**Comment by hzlchn** [comment]
@HCSpin could you get it working by any other way?

**Comment by ibell** [comment]
You need to compile the shared library yourself:  http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#user-compiled-binaries

**Comment by HCSpin** [comment]
I haven't gotten Excel to work, but CoolProp works just fine with python.  I would definitely use it in Excel for simple calculations if you find it can work.  I just haven't had the opportunity to return to it after August. Please let me know if you get it to work!

**Comment by HCSpin** [comment]
The link provided on Nov 8, 2021 is for generating CoolProp.xlam.  

The following errors occurred during the build:
----------
Building CXX object CMakeFiles/CoolProp.dir/src/AbstractState.cpp.o
In file included from /Users/ME/CoolPropM1/CoolProp/src/AbstractState.cpp:14:
In file included from /Users/ME/CoolPropM1/CoolProp/include/AbstractState.h:11:
In file included from /Users/ME/CoolPropM1/CoolProp/include/CachedElement.h:11:
In file included from /Users/ME/CoolPropM1/CoolProp/include/CoolPropTools.h:15:
/Users/ME/CoolPropM1/CoolProp/include/CPstrings.h:45:61: error: expected expression
        s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](unsigned char ch) {
                                                            ^
/Users/imby-hcs/CoolPropM1/CoolProp/include/CPstrings.h:61:52: error: expected expression
        s.erase(std::find_if(s.rbegin(), s.rend(), [](unsigned char ch) {
                                                   ^
2 errors generated.
make[2]: *** [CMakeFiles/CoolProp.dir/src/AbstractState.cpp.o] Error 1
make[1]: *** [CMakeFiles/CoolProp.dir/all] Error 2
make: *** [all] Error 2
----------
As far as I could tell, libCoolProp.dylib was not generated (perhaps because of the error).  How can I build that specifically for the M1?  CoolProp does not work with the libCoolProp.dylib copied from my Intel Mac.

Has anyone else gotten CoolProp to work on an M1?

**Comment by HCSpin** [comment]
Seems that the newest versions of the OS prevent DYLD_LIBRARY_PATH from being set.
[https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html](url)

If someone has found a workaround, please post.  Thanks!

**Comment by HCSpin** [comment]
I haven't--which has kept me on an old mac to be able to use some legacy spreadsheets.  I have not tried again recently, though.  Please post it if you break through!

**Comment by Husoosh** [comment]
Thank you for your answer, I will try.

**Comment by HCSpin** [comment]
I believe I found a workaround, thanks to [https://socialgrep.com/search?query=intel%20mac%20os](url).  Open a terminal window and enter
`arch -x86_64 /Applications/Microsoft\ Excel.app/Contents/MacOS/Microsoft\ Excel`
This forces the mac to open Excel in Rosetta.  There are probably performance hits, but at least it seems to work!

As it says in the link I included, you can also force Excel to always run this way by choosing "Open using Rosetta" after clicking once on the Excel app icon and clicking File/Get Info.
