### ISSUE TITLE
Cannot create propertyplot for ammonia

### ISSUE THREAD

**Issue by lwallsch** [CoolProp/CoolProp#2043]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

Creating  a PropertyPlot with the medium 'ammonia' results in an Error and the plot is not created.

### Steps to Reproduce

1. from CoolProp.Plots import PropertyPlot
2. plot = PropertyPlot('ammonia', 'TS')

**Expected behavior:** [What you expect to happen]

I would expect the plot to bea created. Then I would add isolines and show the plot

**Actual behavior:** [What actually happens]

Error message occurs:
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    plot = PropertyPlot('HEOS::ammonia', 'TS')
  File "C:\Python38\lib\site-packages\CoolProp\Plots\Plots.py", line 68, in __init__
    super(PropertyPlot, self).__init__(fluid_name, graph_type, **kwargs)
  File "C:\Python38\lib\site-packages\CoolProp\Plots\Common.py", line 756, in __init__
    Base2DObject.__init__(self, graph_type[1], graph_type[0], state, **kwargs)
  File "C:\Python38\lib\site-packages\CoolProp\Plots\Common.py", line 382, in __init__
    if state is not None: self.state = state
  File "C:\Python38\lib\site-packages\CoolProp\Plots\Common.py", line 409, in state
    self._T_small = self.critical_state.keyed_output(CoolProp.iT) * self._small
  File "C:\Python38\lib\site-packages\CoolProp\Plots\Common.py", line 395, in critical_state
    self._critical_state = get_critical_point(self._state)
  File "C:\Python38\lib\site-packages\CoolProp\Plots\Common.py", line 73, in get_critical_point
    raise ValueError("Could not calculate the critical point data. " + msg)
ValueError: Could not calculate the critical point data. Bad phase to solver_rho_Tp_SRK - Bad phase to solver_rho_Tp_SRK - Temperature specified is not the imposed phase region. - Temperature specified is not the imposed phase region. -

### Versions

**CoolProp Version:**  6.4.1  
**Operating System and Version:** Windows 10  
**Access Method:** Python 3.8.0 64-bit

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by paullonden96** [comment]
I have the same problem. Neither SimpleCompressionCycle or PropertyPlot works with Ammonia. Any help would be appreciated.

**Comment by jowr** [comment]
Did you try the development version? Ammonia properties improved a lot lately.

**Comment by paullonden96** [comment]
well thanks for your answer but this leads to another problem.  I can't build the develop branch from your install.py file.

**Comment by jowr** [comment]
Have you tried the latest python packages? See #2119 

```shell
python -m pip install -i https://test.pypi.org/simple/ CoolProp
```

**Comment by paullonden96** [comment]
thanks! install worked and the plot works too!
