### ISSUE TITLE
Old Coolprop Commands not working on newer version

### ISSUE THREAD

**Issue by Harish-tech1997** [CoolProp/CoolProp#2044]
**Description of Problem**
I'm trying to run a code on MATLAB written in 2016 with coolprops. Commands such as calc_pressure and find_state_function have been used. When I try to run the code as in on the 6.4.1 version that I have installed I get the error "Unable to resolve the name CoolProp.PropsSI". When I use py.CoolProp.CoolProp.PropsSI too I get the same error. Is there a way to fix this issue? Should I probably install an older version of coolprop to run such commands?

**Comment by ibell** [comment]
Are you sure those are not custom functions provided by your code?  I don't
remember them from old CoolProp.  What version of CoolProp was used before?

**Comment by Harish-tech1997** [comment]
The older version of Coolprop used was 5.0.8. As you said if these functions aren't on the database they should be custom-made functions.
