### ISSUE TITLE
How to calculate IsoButene Steam Properties Tables for Simulink Rankine Cycle with CoolProp?

### ISSUE THREAD

**Issue by YegorMorozov** [CoolProp/CoolProp#2047]
### Description

Dear Community,

I need to calculate IsoButene Steam Properties Tables for the Simulink Rankine Cycle model https://www.mathworks.com/help/physmod/simscape/ug/rankine-cycle-steam-turbine.html .
I am grateful for the Developers who helped me to install CoolProp wrappers on MATLAB and LibreOffice.
Yet, I still have a problem with using CoolProp for IsoButene.
MATLAB Technical Support suggested me to use ‘twoPhaseFluidTables’ function to calculate them:
https://www.mathworks.com/help/physmod/simscape/ref/twophasefluidtables.html 
But when I run it in MATLAB command line with the CoolProp Wrapper installed and tested working, I get the following errors:

### Steps to Reproduce

I put in the MATLAB command line and enter the following:

IsobuteneTables = twoPhaseFluidTables([30,4000],[0.001,100],25,25,60,...
'Isobutene','py.CoolProp.CoolProp.PropsSI')

**Expected behavior:**

Get IsoButene twoPhaseFluidTables to install into the Simulink Rankine Cycle model Steam Properties block. 

**Actual behavior:** 

MATLAB with the CoolProp Wrapper installed says the following:

IsobuteneTables = twoPhaseFluidTables([30,4000],[0.001,100],25,25,60,...
'Isobutene','py.CoolProp.CoolProp.PropsSI')
Error using twoPhaseFluidTables>coolpropSaturationProperties (line 860)
CoolProp failed to return fluid properties at P = 0.001 MPa, Q = 0.

Error in twoPhaseFluidTables>@(p,q)coolpropSaturationProperties(p,q,substance,coolpropFun) (line 786)
saturationProperties = @(p, q) coolpropSaturationProperties(p, q, substance, coolpropFun);

Error in twoPhaseFluidTables (line 132)
            = saturationProperties(p(j), 0);

Caused by:
    Error using CoolProp/CoolProp.__Props_err2 (line 344)
    Python Error: ValueError: Viscosity model is not available for this fluid : PropsSI("V","P",1000,"Q",0,"Isobutene")
 
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information,
click here. 

### Versions

**CoolProp Version:** [CoolProp 6.4.1]
**Operating System and Version:** [Ubuntu 20.04]  
**Access Method:** [How you are accessing CoolProp (MATLAB)]  

### Additional Information

Do you know how to resolve this errors to calculate IsoButene twoPhaseFluidTables to install into the Simulink Rankine Cycle model Steam Properties block?
MATLAB Technical Support tells me that the issue is on CoolProp Wrapper side, and I must ask CoolProp developers.
If possible, please post examples and/or screenshots of the issue:

![Снимок экрана от 2021-09-15 23-10-24](https://user-images.githubusercontent.com/4655425/133643648-5ccefc37-0c22-4ff3-a978-53706cab5f22.png)
![Снимок экрана от 2021-09-16 09-03-45](https://user-images.githubusercontent.com/4655425/133646412-b47ce639-8af1-4e23-885b-292104fbc4ba.png)

**Comment by ibell** [comment]
Did you see the error message?

>

**Comment by YegorMorozov** [comment]
@ibell  yes, I did.
"Viscosity model is not available for this fluid"
Is there any other way to calculate the IsoButene twoPhaseFluidTables to install into the Simulink Rankine Cycle model Steam Properties block?

> Did you see the error message?
> […](#)

**Comment by ibell** [comment]
No, not until someone develops a viscosity model for isobutene.  There is
an extended corresponding states model in REFPROP that someone (not me)
could implement.

>

**Comment by YegorMorozov** [comment]
> No, not until someone develops a viscosity model for isobutene. There is an extended corresponding states model in REFPROP that someone (not me) could implement.
> […](#)

@ibell thank you for your response.
Do you mean that REFPROP could have the IsoButene viscosity model to calculate the IsoButene twoPhaseFluidTables to install into the Simulink Rankine Cycle model Steam Properties block? I have asked data@nist.gov, is it a correct address to ask?

**Comment by ibell** [comment]
If you purchase and install Refprop you can call it through the PropsSI
function.

**Comment by YegorMorozov** [comment]
> If you purchase and install Refprop you can call it through the PropsSI function.

@ibell but does it have the IsoButene viscosity model and other models to calculate the IsoButene twoPhaseFluidTables to install into the Simulink Rankine Cycle model Steam Properties block? This determines if purchasing it will help.

**Comment by ibell** [comment]
Yes it does

**Comment by YegorMorozov** [comment]
I just tried for another working fluid, Isobutane, to check if the twoPhaseFluidTables function works. LibreOffice had Prandtl for Isobutane.
Do you know how to resolve the "unable to calculate melting line" error?

IsobutaneTables = twoPhaseFluidTables([0,4000],[0.001,100],25,25,60,...
'Isobutane','py.CoolProp.CoolProp.PropsSI')
Error using twoPhaseFluidTables>coolpropFluidProperties (line 899)
CoolProp failed to return fluid properties at P = 45.816 MPa, U = 896.4927 kJ/kg.

Error in twoPhaseFluidTables>@(p,u)coolpropFluidProperties(p,u,substance,coolpropFun) (line 789)
fluidProperties = @(p, u) coolpropFluidProperties(p, u, substance, coolpropFun);

Error in twoPhaseFluidTables (line 215)
            = fluidProperties(p(j), u_sat_liq(j));

Caused by:
    Error using CoolProp/CoolProp.__Props_err2 (line 344)
    Python Error: ValueError: unable to calculate melting line T(p) for polynomial_in_Theta curve for p=4.5816e+07; bounds
    are 0.0219,4.12796e+07 Pa : PropsSI("D","P",45815976.69,"U",896492.7144,"Isobutane")
   
![Снимок экрана от 2021-09-16 09-44-40](https://user-images.githubusercontent.com/4655425/133653013-e6544e3d-f96c-4a40-a6b2-01af294e1722.png)

**Comment by ibell** [comment]
Use lower max pressure

**Comment by YegorMorozov** [comment]
@ibell thank you for the suggestion!
I decreased max pressure 10 times, now it returns another errors:

IsobutaneTables = twoPhaseFluidTables([0,4000],[0.001,10],25,25,60,...
'Isobutane','py.CoolProp.CoolProp.PropsSI')
Error using twoPhaseFluidTables>coolpropFluidProperties (line 899)
CoolProp failed to return fluid properties at P = 0.001 MPa, U = 2057.4009 kJ/kg.

Error in twoPhaseFluidTables>@(p,u)coolpropFluidProperties(p,u,substance,coolpropFun) (line 789)
fluidProperties = @(p, u) coolpropFluidProperties(p, u, substance, coolpropFun);

Error in twoPhaseFluidTables (line 237)
                = fluidProperties(p(j), u_vap(i,j));

Caused by:
    Error using CoolProp/CoolProp.__Props_err2 (line 344)
    Python Error: ValueError: unable to solve 1phase PY flash with Tmin=183.368, Tmax=862.5 due to error:
    HSU_P_flash_singlephase_Brent could not find a solution because Umolar [119581 J/mol] is above the maximum value of
    119357.687222 J/mol : PropsSI("D","P",1000,"U",2057400.872,"Isobutane")

![Снимок экрана от 2021-09-23 08-12-21](https://user-images.githubusercontent.com/4655425/134534581-0ae66ed9-6cf2-4877-a9c2-6b1d3db936d5.png)

**Comment by ibell** [comment]
Sounds to me like your max temp limit needs to be reduced

**Comment by YegorMorozov** [comment]
> Sounds to me like your max temp limit needs to be reduced

@ibell thank you, but how? I see only specific internal energy (u) and pressure (p) ranges and the matrix size are declared in the syntax that I have found:
"IsobutaneTables = twoPhaseFluidTables([0,4000],[0.001,10],25,25,60,...
'Isobutane','py.CoolProp.CoolProp.PropsSI')"

**Comment by ibell** [comment]
So then a lower max internal energy

**Comment by YegorMorozov** [comment]
Thank you very much, it actually worked, the 1x1 structure actually contained all the 20x40 Isobutane tables!
Now, I need to assign it to Simulink Steam Properties block. The syntax for that is: 
twoPhaseFluidTables(__________, IsobutaneTables), where _________ should be replaced by the path.
Do you know how to specify the correct path to the Steam Properties Simulink block? I tried, but it didn't work:


>> IsobutaneTables = twoPhaseFluidTables([0,2000],[0.01,10],20,20,40,...
'Isobutane','py.CoolProp.CoolProp.PropsSI')

IsobutaneTables = 

  struct with fields:

         p: [1×40 double]
    liquid: [1×1 struct]
     vapor: [1×1 struct]
     u_min: 0
     u_max: 2000
     p_min: 0.0100
     p_max: 10
    p_crit: 3.6290
    u_crit: 617.8627
     n_sub: 34

>> twoPhaseFluidTables(Steam Properties, IsobutaneTables)
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information,
click here. 
 twoPhaseFluidTables(Steam Properties, IsobutaneTables)
                           ↑
Error: Invalid expression. Check for missing multiplication operator, missing or unbalanced delimiters, or other syntax
error. To construct matrices, use brackets instead of parentheses.
 
>> 

![Снимок экрана от 2021-10-14 09-19-05](https://user-images.githubusercontent.com/4655425/137361042-58eba160-0268-44c9-bcc4-a6031bff5363.png)

**Comment by YegorMorozov** [comment]
Thank you very much, I finally generated the Isobutane properties with CoolProp and assigned them into the Simulink ORC model using the following command:
`twoPhaseFluidTables(gcb, IsobutaneTables)`
So, the CoolProp part is done, but the Simulink ORC model stopped working properly. Now I will fix Simulink, make ORC work.
