### ISSUE TITLE
Negative Values n-Hexane high level interface 

### ISSUE THREAD

**Issue by ice0man** [CoolProp/CoolProp#2048]
Hello I am using Coolprop to model some thermodynamic cycles but I have a problem using it to calculate the properties and I don't know if it is a problem of my computer or a bug.

The problem is the following :

CP.PropsSI('H','T',30+273,'Q',0,'n-Hexane')/1000 = -92.572 kj/kg.

Comparing the results with EES for the same characteristics the enthalpy gives me 7.09 kj/kg.

CoolProp gives me a negative value for that property and different from EES I think there is an error but I don't know how to correct it, I would appreciate if you could guide me to the solution or where I am going wrong, I have already checked the units and everything, I am using the latest version of CoolProp.

**Comment by ibell** [comment]
Please see question number one in FAQ:
https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by ice0man** [comment]
thaks @ibell
