### ISSUE TITLE
Different Reference state for mixtures using REFPROP backend and REFPROP itself

### ISSUE THREAD

**Issue by OmarZaki96** [CoolProp/CoolProp#2064]
### Description
When using REFPROP backend with CoolProp to find mixture enthalpy (e.g. for R410A), the values are different than values obtained from REFPROP itself using R410A as predefined mixture. However, the difference between the values is the same, indicating a different reference state between the two methods.

Does CoolProp use a different reference state for mixtures? would that affect accuracy for entropy or density?

### Steps to Reproduce

```
import CoolProp as CP
AS = CP.AbstractState("REFPROP","R410A.MIX")
AS.update(CP.PT_INPUTS,2733532,40+273.15)
```
I get
`267149.1083935976`

where REFPROP software returns
`265935.277663`

### Versions

**CoolProp Version:** 6.4.1
**Operating System and Version:** Windows 10 x64
**Access Method:** Python
**REFPROP Version:** 10.0

**Comment by ibell** [comment]
Yes, reference states for mixtures are not implemented in CoolProp. The
reference state only impacts enthalpy,  entropy,  and other properties that
contain them.   Density is not impacted for PT inputs.
