### ISSUE TITLE
how to link static library of CoolProp?

### ISSUE THREAD

**Issue by pBlasiak** [CoolProp/CoolProp#207]
Hi all,
I compiled CoolPro to a static library according to:

http://www.coolprop.dreamhosters.com:8010/sphinx/coolprop/wrappers/StaticLibrary/index.html#user-compiled-binaries

Now I want to link created library file to my main.cpp

How can I do that?

best regards
Przemek

**Comment by tianshuluo** [comment]
I have the same error.
If one don not use REFPROP, can one bypass REFPROP?

**Comment by jowr** [comment]
I do not understand your problem, sorry. REFPROP is only used when you explicitly specify it as backend.

**Comment by ibell** [comment]
See the response in issue #823 - the ``-ldl`` flag is missing.
