### ISSUE TITLE
Using CoolProp to access RefProp in Modelica Code

### ISSUE THREAD

**Issue by patrick-fourspring-nnl** [CoolProp/CoolProp#2074]
(duplicate post from https://github.com/modelica-3rdparty/ExternalMedia/issues/48)

We welcome any suggestions for the following issue using External Media (v3.3.0) within OpenModelica (runing Modelica v3.2.3):

The following Modelica code works:

model CoolPropTest

package Medium = 
ExternalMedia.Media.CoolPropMedium(
mediumName = "Water");

Medium.AbsolutePressure p1 = 8e6;
Medium.SpecificEnthalpy h1 = 1.0e5;

Medium.Density d;

equation

d = Medium.density_ph(p1, h1, 0);

end CoolPropTest;

Using the same code to access RefProp does not work

model CoolPropTest

package Medium = 
ExternalMedia.Media.CoolPropMedium(
mediumName = "REFPROP::Water");

Medium.AbsolutePressure p1 = 8e6;
Medium.SpecificEnthalpy h1 = 1.0e5;

Medium.Density d;

equation

d = Medium.density_ph(p1, h1, 0);

end CoolPropTest;

error Code:

calc_transport has the value of 1
TTSE is off
enable_TTSE has the value of 0
BICUBIC is off
enable_BICUBIC has the value of 0
enable_EXTTP has the value of 1
twophase_derivsmoothing_xend has the value of 0.0
rho_smoothing_xend has the value of 0.0
debug has the value of 0

This backend does not implement calc_specify_phasefunction
simulation terminated by an assertation at initialization
Simulation process failed. Exited with code -1.

Thanks,
Patrick

**Comment by jowr** [comment]
This is not a CoolProp issue, please stick to ExternalMedia for discussing this
