### ISSUE TITLE
Unable to Get Values using H and T as Inputs

### ISSUE THREAD

**Issue by FishInChips** [CoolProp/CoolProp#2086]
### Description

Hello. I'm unable to assess properties using T and H as inputs to the PropsSI function. I have seen a post from 2017 on this issue giving a reason for it not working, but I know that others can do this using EES. So why can EES do it, but not Python? Is there a way around this as I only have T and H to use and inputs.

I'd appreciate any help.

The MATLAB code is as follows:
P = py.CoolProp.CoolProp.Props('P', 'H', 601770, 'T', 301.15 'Propane')

### Versions

**CoolProp Version:** [6.4.1]  
**Operating System and Version:** [Windows]  
**Access Method:** [Python 3.9 and MATLAB]  

### Additional Information

![image](https://user-images.githubusercontent.com/98783063/152025093-dab36efc-683e-453a-aac6-76beee790fde.png)

**Comment by ibell** [comment]
I'm afraid not.   The problem with TH inputs is that multiple solutions are
possible for a given set of TH, and communicating the desired solution is
difficult. Sounds like EES might return the wrong root sometimes. Don't you
know pressure? In most cases you do.

**Comment by FishInChips** [comment]
In this case I don't know pressure. It's for a university project so only the minimum information is given. It makes sense that there would be multiple solutions if the state is not known. Perhaps EES is assuming the state is within the vapor dome and has a quality between 0 and 1. I'm going to have to make a similar assumption in my case. Thank you for the reply.
