### ISSUE TITLE
Multiple Instances  Shared Library on Linux

### ISSUE THREAD

**Issue by vskconsultants** [CoolProp/CoolProp#2087]
Hi

I have installed Cool Prop Shared Library on Linux and trying to access it serval places at the same time. I could see there are issues with overlapping data between shared library calls.

Is it possible to use a shared library on Linux with multiple instances or need to recompile static library  ?

**Comment by ibell** [comment]
Can you please provide more info? Hard to say anything with given report

**Comment by mboogi** [comment]
Hi VSK...
although the coolprop should be thread safe, there is certain thread showing that in some cases it  doesn't really work in such way (this was really a special case)
https://github.com/CoolProp/CoolProp/issues/1859

My workaround was synchronization of method calls, and that didn't create any issue. Now dependently if you are just calling one method from c++, and if that methods does not modify non local memory, it is threadsafe and problem should be somewhere else.

**Comment by vskconsultants** [comment]
Hi Ian
I am running multiple instances of CoolProp and see data overlapping between the instances.

**Comment by ibell** [comment]
Need much more info than that. See the level of detail in the linked issue.

**Comment by vskconsultants** [comment]
To fix the above issue, I am trying to cross-compile CoolProp Library on the NI RT Linux x64, I have installed all the pre-requisites as required but getting the following compile error.

Error 
[ 25%] Building CXX object CMakeFiles/CoolProp.dir/src/PolyMath.cpp.o
c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [CMakeFiles/CoolProp.dir/build.make:375: CMakeFiles/CoolProp.dir/src/PolyMath.cp
make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/CoolProp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Full log attached.

Can someone please suggest ?
[CoolProp Build Error.txt](https://github.com/CoolProp/CoolProp/files/7994262/CoolProp.Build.Error.txt)

**Comment by ibell** [comment]
Are you trying to cross compile or build locally?  They are fundamentally
different. In any case, looks like you found a bug in the compiler.

**Comment by vskconsultants** [comment]
What should I do then, am I stuck or is there anything can be done ?

**Comment by mboogi** [comment]
From your logs it could be seen that error is at compiler, not on cmake itself

c++: internal compiler

I believe I had the same issue back in the day, but I changed the compiler completely and than it worked. 

To change compiler, try out specifying it like in the second method here
https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake
BR
Mb

**Comment by ibell** [comment]
@vskconsultants it would be very helpful if you would clearly explain what you are trying to achieve and what you have already tried. So for, the explanations are not helpful for debugging purposes
