### ISSUE TITLE
CoolProp.oct file is not found in Octave-6.4.0 directory even though it is placed there

### ISSUE THREAD

**Issue by felixtd99** [CoolProp/CoolProp#2089]
Hey there,

I am currently trying to set up CoolProp in Octave and am having some trouble. Despite the CoolProp.oct file being located in the correct directory (using the ls command in Octave confirms the .oct file is present), It is not able to find the module and gives me the following error:
>> CoolProp
error: opening the library 'C:\Users\Felix\Octave\Octave-6.4.0\CoolProp.oct' failed (error 126): The specified module could not be found.

I did notice that when downloading the CoolProp file is states it is for Octave-5.2.0, could this be the source of the issue I am experiencing?

Thanks advance, 
Felix

**Comment by ibell** [comment]
Yes,  you will have to build it yourself,  probably the binary is linked
against a library not present on your machine

**Comment by felixtd99** [comment]
Thanks for the quick response!
