### ISSUE TITLE
When I use “git clone https://github.com/CoolProp/CoolProp --recursive”  command，Causes the folder “externals”content to be empty，like：fmtlib、IF97、Eigen，etc.

### ISSUE THREAD

**Issue by NT10450110** [CoolProp/CoolProp#2093]
Dear author, Hello：
When I use “git clone https://github.com/CoolProp/CoolProp --recursive”  command，Some errors have occurred. Causes the folder “externals”content to be empty，like：fmtlib、IF97、Eigen，etc.

![1645705220(1)](https://user-images.githubusercontent.com/63385130/155523362-5e9a2fea-6a5b-460f-a513-35802543bd0e.png)
![微信截图_20220224202457](https://user-images.githubusercontent.com/63385130/155523593-e3f8bed0-46ec-42af-94cf-649a82627de3.png)

What should I do to solve this problem?

**Comment by ibell** [comment]
Try again later, seems like github is down temporarily

**Comment by NT10450110** [comment]
Dear Author:

I have been trying on different machines for days, and I suspect that there is a problem in the Chinese mainland network. Could you please download it and send it to my personal email（ yzgeqiping@163.com ）, thank you very much!

**Comment by ibell** [comment]
Sorry,  don't think I can do that.

**Comment by NT10450110** [comment]
OK, thank you for your answer.
