### ISSUE TITLE
Coolprop on Labview and some fluid missing - R1233zd(E)

### ISSUE THREAD

**Issue by TommasoERRE** [CoolProp/CoolProp#2094]
Dears,
my name is Tommaso and i'm correctly using coolprop wrapper on labview, with no problems for all fluids listed (water, air, etc)
I'm working with Labview 2019 32bit and coolprop wrapped found [here](http://www.coolprop.org/coolprop/wrappers/Labview/index.html#labview)
I'm trying to evaluate the thermal properties of R1233zd(E) which is not present in the list of selectable fluid.
i've modified the list of the available fluids into initialise_coolprop.vi adding many items: R1233zd(E), R1233zd(e) and other possible names with and without brackets, capital letters etc)
(note that in ..\Coolprop_sources\dev\fluids R1233zd(E).json is present)
if I select some of the added names like R1233zd(E) Labview gives error n1097 - Call Library Function Node in initialise_coolprop.vi->prova_coolprop.vi
if I select other names like R1233zd(e) I don't receive any error but all the outputs are "Inf"
it seems that the DLL I'm loading does not include this fluid
i've tried to download the last release of dll but nothing changed
what can I try to solve this problem?

moreover: the only working dll is "32bit_cdecl". "32bit" and "32bit_stdcall" give me error n.13 and 1097

thank you in advance and kind regards
Tommaso

**Comment by ibell** [comment]
Where did you get your DLL from?

**Comment by TommasoERRE** [comment]
i get dll from [HERE](https://sourceforge.net/projects/coolprop/files/CoolProp/nightly/shared_library/)
however, yesterday in the end I've solved
I'm writing down here the steps that worked for me (maybe it will be useful for someone else)
after importing coolprob for labview (see [here](http://www.coolprop.org/coolprop/wrappers/Labview/index.html#labview)) 
1. open "initialise_coolprop.vi" - add item in "fluidOfInterest"
2. again in "initialise_coolprop.vi" Call Library Function Node - properties - Function name = "Props"
3. the same has to be done in the Call Library Function Node of "calculate_coolprop.vi"

look at the image herebelow

![Cattura](https://user-images.githubusercontent.com/100577097/156142251-06c8774b-d017-4c9e-8054-c111cb93e8d7.JPG)

Hope this helps 
kind regards
Tommaso
