### ISSUE TITLE
Bound-check fluid indices in setting mixture parameters

### ISSUE THREAD

**Issue by friederikeboehm** [CoolProp/CoolProp#2102]
### Description
When setting fluid mixture parameters like binary interaction or alpha parameters, the indices of the fluids are not being bound-checked. Using out of bounds indices reports no error but simply crashes (as it is undefined behaviour).

### Steps to Reproduce

1. Create State with a cubic fluid mixture (e.g. two fluids)
2. set_cubic_alpha_C for an index out of bounds (e.g. 5)

**Expected behavior:** Error message along the lines of "the index used [5] is out of bounds [0-1]."

**Actual behavior:** crash

### Versions

**CoolProp Version:** current master branch
**Operating System and Version:** Windows  10
**Access Method:** Mathematica Wrapper (modified)  

### Solution
Implement bound-checks for functions 
 - set_binary_interaction_double(const std::size_t i, const std::size_t j, const std::string &parameter, const double value)
 - set_binary_interaction_string(const std::size_t i, const std::size_t j, const std::string &parameter, const std::string &value)
 - get_binary_interaction_double(const std::size_t i, const std::size_t j, const std::string &parameter)
 - apply_simple_mixing_rule(std::size_t i, std::size_t j, const std::string &model) 
 - set_cubic_alpha_C(const size_t i, const std::string &parameter, const double c1, const double c2, const double c3) 
 - set_fluid_parameter_double(const size_t i, const std::string &parameter, const double value) 
 - get_fluid_parameter_double(const size_t i, const std::string &parameter) 

I'd be happy to implement this, just wanted to discuss in advance whether this is useful.

**Comment by ibell** [comment]
PR welcomed
