### ISSUE TITLE
Trouble installing MATLAB wrapper via Python

### ISSUE THREAD

**Issue by bmarjaba** [CoolProp/CoolProp#2114]
I am having trouble installing the MATLAB wrapper via Python for CoolProp.

### Steps to Reproduce

1. I installed python 3.8
2. In terminal, I typed _python3_ to enter python shell, then _import sys_, then _sys.path_ to find the python3 executable file path.
3. In MATLAB shell, I typed **pyversion /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8** to tell which version of python to use.
4. I then typed [v,e] = pyversion; system([e,' -m pip install --user -U CoolProp']) to install coolprop in the given python version.

**Expected behavior:** A successful installation of CoolProp without errors. 

**Actual behavior:** 
 The following error occurred when calling the function in step 4.

Collecting CoolProp
  Using cached CoolProp-6.4.1.tar.gz (12.9 MB)
Building wheels for collected packages: CoolProp
  Building wheel for CoolProp (setup.py) ... [?25lerror
[31m  ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/setup.py'"'"'; __file__='"'"'/private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-wheel-4zrokjqu
       cwd: /private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/
  Complete output (55 lines):
  OSX build detected, targetting 10.14 using clang/gcc v13.1.6.
  Assuming that we cannot build for 10.14 using clang/gcc 13.1.6, resetting target to 10.9
  Cython will not be used; cy_ext is cpp
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.8
  creating build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/constants.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/BibtexParser.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/HumidAirProp.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/State.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  creating build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
  copying CoolProp/tests/runner.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
  copying CoolProp/tests/test_plots.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
  copying CoolProp/tests/test_Props.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
  copying CoolProp/tests/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
  copying CoolProp/tests/test_CoolPropState.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
  creating build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
  copying CoolProp/GUI/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
  copying CoolProp/GUI/CoolPropGUI.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
  copying CoolProp/GUI/PsychScript.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
  creating build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/ConsistencyPlots_pcsaft.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/PsychChart.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/SimpleCycles.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/psy.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/Plots.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/Common.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/SimpleCyclesCompression.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/ConsistencyPlots.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/PsychScript.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/Tests.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/Plots/SimpleCyclesExpansion.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  copying CoolProp/typedefs.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/CoolProp.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/State.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/cAbstractState.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/constants_header.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/AbstractState.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
  copying CoolProp/Plots/psyrc -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
  running build_ext
  creating private
  creating private/var
  creating private/var/folders
  creating private/var/folders/xc
  creating private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn
  creating private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T
  creating private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh
  creating private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c /private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/tmpjutdd7sj.cpp -o private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/tmpjutdd7sj.o
  error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.9" but "10.14" during configure
  ----------------------------------------[0m
[31m  ERROR: Failed building wheel for CoolProp[0m
[?25h  Running setup.py clean for CoolProp
Failed to build CoolProp
Installing collected packages: CoolProp
    Running setup.py install for CoolProp ... [?25lerror
[31m    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/setup.py'"'"'; __file__='"'"'/private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-record-za0ensng/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/marjaba/Library/Python/3.8/include/python3.8/CoolProp
         cwd: /private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/
    Complete output (47 lines):
    OSX build detected, targetting 10.14 using clang/gcc v13.1.6.
    Assuming that we cannot build for 10.14 using clang/gcc 13.1.6, resetting target to 10.9
    Cython will not be used; cy_ext is cpp
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.8
    creating build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/constants.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/BibtexParser.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/HumidAirProp.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/State.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    creating build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
    copying CoolProp/tests/runner.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
    copying CoolProp/tests/test_plots.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
    copying CoolProp/tests/test_Props.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
    copying CoolProp/tests/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
    copying CoolProp/tests/test_CoolPropState.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/tests
    creating build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
    copying CoolProp/GUI/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
    copying CoolProp/GUI/CoolPropGUI.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
    copying CoolProp/GUI/PsychScript.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/GUI
    creating build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/ConsistencyPlots_pcsaft.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/PsychChart.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/SimpleCycles.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/psy.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/Plots.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/Common.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/SimpleCyclesCompression.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/ConsistencyPlots.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/PsychScript.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/Tests.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/Plots/SimpleCyclesExpansion.py -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    copying CoolProp/typedefs.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/CoolProp.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/State.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/cAbstractState.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/constants_header.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/AbstractState.pxd -> build/lib.macosx-10.14-x86_64-3.8/CoolProp
    copying CoolProp/Plots/psyrc -> build/lib.macosx-10.14-x86_64-3.8/CoolProp/Plots
    running build_ext
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c /private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/tmp9fq4a39s.cpp -o private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/tmp9fq4a39s.o
    error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.9" but "10.14" during configure
    ----------------------------------------[0m
[31mERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/setup.py'"'"'; __file__='"'"'/private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-install-1fkqbkeh/coolprop/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xc/4y9h7w6s4kj6kncm4vw0myt80000gn/T/pip-record-za0ensng/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/marjaba/Library/Python/3.8/include/python3.8/CoolProp Check the logs for full command output.[0m
[33mWARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.[0m
[?25h
ans =

     1

Also the following error occurs when running PropSi function:
py.CoolProp.CoolProp.PropsSI('C', 'T', 273, 'P', 1600000, 'R1234yf')
Unable to resolve the name 'py.CoolProp.CoolProp.PropsSI'.

### Versions

**CoolProp Version:** I don't know what version I am trying to install.  But v6.4.1 is installed on python, using PyCharm.
**Operating System and Version:** macOS Monterey v12.2
**Access Method:** MATLAB wrapper. CoolProp is successfully installed on python though (using PyCharm), without any issues.
### Additional Information
I am following the instructions in the following link:
http://www.coolprop.org/dev/coolprop/wrappers/MATLAB/index.html#pre-generated-wrapper-code

**Comment by ibell** [comment]
Please try that command now, wheels have been pushed to TestPYPI
