### ISSUE TITLE
The enthalpy of LiBr-Water in EES is not equal to CoolProp.

### ISSUE THREAD

**Issue by GanzorigKhun** [CoolProp/CoolProp#2115]
### Description
The enthalpy of LiBr-Water in **EES** is not equal to **CoolProp**. I don‘t know how it happened? Please help to solve this problem.
Thank you.

### Versions

**CoolProp Version:** 6.4.1
**Operating System and Version:** win10
**Access Method:** Python

### Additional Information
In EES, this is
![image](https://user-images.githubusercontent.com/52224515/162718041-349218b7-967c-4449-a190-3e0e9612d0fa.png)

In Coolprop, this is

![image](https://user-images.githubusercontent.com/52224515/162720725-f997f154-c2c3-4237-8f99-5335bb5ed285.png)

**Comment by chandradharkoneti** [comment]
Enthalpy and entropy of multiple sources will not match unless they are using the same datum. Generally, the datums considered are either -40 C or 0 C. 
Please take a look at https://github.com/CoolProp/CoolProp/blob/master/FAQ.md#usage

Anyhow, the absolute value of enthalpy is meaningless. You only ever need the **_change_** in enthalpy value for various processes. 

To get clarity on what I am talking about, please try this:
Take the enthalpy value in EES at 2 different points (say 280 K and 320 K)
Now take the enthalpy values in CoolProp at the same points. (280 K and 320 K)

Verify if the difference in enthalpy [  (h_320_EES - h_280_EES)  =  (h_320_cp - h_280_cp) ] is the same or not. **If not, please post here**. It will be considered.

**Comment by jowr** [comment]
Another important issue is that CoolProp does not compute the enthalpy of mixing. You can only compare enthalpy values at constant concentrations.
