### ISSUE TITLE
CoolProp CO2 not working with turbomachinery components

### ISSUE THREAD

**Issue by shigrekar1** [CoolProp/CoolProp#2121]
### Description
I am trying to set up a sCO2 Brayton cycle, however, I am facing issues running the turbine and compressor with the CoolProp CO2 model. I have an Aspen HYSYS model that I use as a basis to set up this Dymola-based model and I'm using REFPROP to ensure that my thermophsyical properties are realistic. 

When I try separating the compressor (or turbine) and run it, it still fails with the following error:

Invalid values for inputs p=100000 h=0 for fluid CarbonDioxide
The stack of functions is:
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6
ExternalMedia.Media.CoolPropMedium.setState_ph_Unique6(100000.0, Comp1.gas_iso.h, 0)
ExternalMedia.Media.CoolPropMedium.temperature_ph_Unique21(Comp1.gas_iso.p, Comp1.gas_iso.h, Comp1.gas_iso.phaseInput)

I have tried modifying my compressor model to set the fluid state at the outlet using p & T instead of p & h. This has not helped. 

The model works fine with an Ideal gas-based CO2 medium, but then the fluid properties are not accurate. 

I would appreciate any guidance that you may provide. 

Thank you,
Amey 

### Versions

**CoolProp Version:** Currently using CoolProp from ExternalMedia 3.2.1 
**Operating System and Version:** Windows 10 
**Access Method:** Dymola 2021x

### Additional Information

![Capture1](https://user-images.githubusercontent.com/85127687/163017059-6638e6da-c110-486b-80d9-2cdf321ed15f.PNG)

**Comment by ibell** [comment]
Please do this test outside HYSYS, like in python or something to help the
debugging.  Too many layers of possible problems otherwise.

**Comment by shigrekar1** [comment]
Do you mean to test the acquisition of thermophysical properties or to set up a compressor model in Python?

**Comment by ibell** [comment]
I mean to do the particular inputs P&H directly in the high-level interface
of CoolProp (no ExternalMedia, no HYSYS, etc.)

**Comment by shigrekar1** [comment]
I am sorry but I do not know how to do that. Is there any documentation on how to do this?

Also, HYSYS is a standalone steady-state tool that I am using just to check whether the values my Dymola model is providing make sense or not.

**Comment by ibell** [comment]
www.coolprop.org has lots of docs

**Comment by shigrekar1** [comment]
Hello Ian,
Thank you for all your help. I was able to debug my model and realized that the default pressure input to the turbomachinery components was causing the issue. I changed that parameter and the models work just fine. 

I will go ahead and close this issue. 
Regards,
Amey
