### ISSUE TITLE
Incorrect values for Air fluid

### ISSUE THREAD

**Issue by Gorg0n** [CoolProp/CoolProp#2124]
Hello,
I haven't found this as a known issue, so I'm writing to point out that using "Air" as a working fluid, apparently CoolProp returns wrong values for Specific Enthalpy and Entropy

In fact, both using both the Python wrapper and the online webtool I got at ambient pressure & temperature (101325 Pa & 298 K):
Enthalpy [J/kg] | 424285.098086
Entropy [J/kg/K] | 3879.98276257

Correct values should be:
Specific Enthalpy : | 298.59701875 | [ kJ / kg ]
Specific Entropy : | 6.8644596875 | [ kJ / kg K ]

Conversely, when dealing with Nitrogen, Oxygen and Argon values at the same pressure & temperature h and s seem to be ok

**Comment by ibell** [comment]
Faq #1: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md#usage
