### ISSUE TITLE
CO2 two phase density mismatch between CoolProp call and calculation with same quality

### ISSUE THREAD

**Issue by ragnar2015** [CoolProp/CoolProp#2131]
CoolProp version: Excel 6.4.0 installed on a Mac with OSX 10.14.6 (Mojave)
Substance:	CO2
REGION:		Two phase at P = 4.2 MPa

Observed problem:

I found a CO2 two phase density mismatch when calculated two ways:
1) a direct CoolProp call 
2) manual calculation with same quality

Screenshot attached (excel spreadsheet using Coolprop.  REFPROP parallel results included):

![Screen Shot 20220503](https://user-images.githubusercontent.com/11840318/166584971-1d850d73-5673-481c-8bc2-ea82ef385a7b.png)

Background:

I entered the CO2 2-phase dome with 4.2 MPa and entropy s = 1738.1565 J/kg-K.

I manually compute quality = 0.9128 (confirmed by REFPROP) using saturated liquid, saturated vapor and 2phase entropy per equation: quality = (s_2phase - s_liquid)/(s_vapor-s_liquid)

With same P = 4.2 MPa and s = 1738.1565 J/kg-K, CoolProp computes density = 133.234 kg/m3.
Again confirmed by REFPROP.

Alternatively, using P=4.2 MPa and same quality=0.9128, CoolProp again computes density = 133.234 kg/m3.

So far so good!

However, when density is HAND COMPUTED as follows using the standard quality equation with quality x=0.9128 from above:

density = quality * (rho_vapor - rho_liquid) +  rho_liquid

density = 189.341 kg/m3 per 0.9128 * (123.2379 - 881.0187) +  881.0187

This density differs by +42% from the CoolProp density at the same quality.

This is not supposed to happen. Any thoughts and or suggestions?

Thanks in advance!

**Comment by ibell** [comment]
Your equation with densities is not correct,  use volumes and it'll be
fine. I remember getting tripped up by this for a long time.

**Comment by ragnar2015** [comment]
Thanks Ian.

Count me as one tripped up too.

Using specific volume with quality to compute 2phase specific volume then inverting for density is a subtlety. Makes sense due to PvT nature of EOS equations from which the intrinsic property of quality is computed I suppose. Thanks again!
