### ISSUE TITLE
Helium properties deviate significantly from REFPROP around critical point

### ISSUE THREAD

**Issue by renzhuo** [CoolProp/CoolProp#2145]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

Helium properties deviate significantly from REFPROP around critical point

### Steps to Reproduce

1. Calculate density of helium at T = 1.01 Tc, P = Pc 
2. density from coolprop is 32% lower than density calculated from REFPROP

**Expected behavior:** [What you expect to happen]
Expected around 1% or lower difference
**Actual behavior:** [What actually happens]
Difference at 32%, and gradually decreases as pressure deviates from critical pressure. 
### Versions

**6.4.1** [CoolProp version you are using]  
**Windows 10 Pro** [OS you are running CoolProp on]  
**Excel wrapper** [How you are accessing CoolProp (i.e. Python, other wrapper, direct C++ calls, etc.)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
Weird. It looks like the implementation is ok:
http://www.coolprop.org/fluid_properties/fluids/Helium.html#refprop-validation-data
.  Can you please provide the inputs and outputs?

**Comment by renzhuo** [comment]
Here is input to Excel: =PropsSI("D","T", 5.1953,"P",227600,"helium"), same T and P for REFPROP. Output from CoolProp is 55.93307176 and 84.04747067 from REFPROP. 

I tried both EES and HEPAK as well. HEPAK output is 84.05070808, and EES output is 58.8. So it seems like a problem with my REFPROP being 8.0.0....

**Comment by ibell** [comment]
REFPROP 10 and CoolProp use the same eos, and both give 55.933071761154
kg/m³ for these inputs

**Comment by renzhuo** [comment]
I see, the problem is with REFPROP 8 and HEPAK then. Thanks!
