### ISSUE TITLE
Bug in the departure function parameters for GeneralizedHFC in CoolProp

### ISSUE THREAD

**Issue by khlee22** [CoolProp/CoolProp#2149]
### Description

I have found that the order of departure function parameters, "l", for GeneralizedHFC in CoolProp v. 6.4.1 (also in v. 6.3.0)
is not the same as that in its original paper (Lemmon-JPCRD-2004).
The departure function parameters are used for the R125-R134a mixture. 
The 3rd and 4th parameters for "l" in the file, mixture_departure_functions.json, might be corrected as follows:

--- CoolProp.sources_v641/dev/mixtures/mixture_departure_functions.json	2020-08-04 04:31:32.000000000 +0900
+++ CoolProp.sources_v641/dev/mixtures/mixture_departure_functions_corrected.json	2022-08-02 10:56:57.739664100 +0900
@@ -27,7 +27,7 @@
 "n" : [-0.013073, 0.018259,0.0000081299,0.0078496],
 "t" : [7.4, 0.35, 10.0, 5.3],
 "d" : [1, 3, 11, 2],
-"l" : [1, 1, 3, 2]
+"l" : [1, 1, 2, 3]
 },
 {
 "Name" : "GeneralizedAirComponents",

### Behavior

The parameters seem to affect the properties at relatively high pressures.
Sample results at T=373.15 K, p=20 MPa for R421A (R125&R134A)  are as follows:

In CoolProp (v.6.4.1),
Density (kg/m^3) = 1073.687441
Specific heat (J/kgK) =1375.319849
Enthalpy (J/kg) = 333062.9903

In CoolProp (v.6.4.1, corrected),
Density (kg/m^3) = 1073.457356
Specific heat (J/kgK) = 1374.775073
Enthalpy (J/kg) = 333085.1973

In REFPROP (v.10),
Density (kg/m^3) = 1073.457343
Specific heat (J/kgK) = 1374.795481
Enthalpy (J/kg) = 333080.8816

**Comment by ibell** [comment]
REFPROP agrees with you:

#MXM              !Mixture model specification
KWT  Lemmon and Jacobsen model for refrigerant mixtures
?
?```````````````````````````````````````````````````````````````````````````````
?E.W. Lemmon and R.T Jacobsen
? "Equations of State for Mixtures of R-32, R-125, R-134a, R-143a, and
R-152a,"
? J. Phys. Chem. Ref. Data, Volume 33, Number 2, pp. 593-620, 2004.
?
!```````````````````````````````````````````````````````````````````````````````
 BetaT    GammaT   BetaV    GammaV    Fij    not used      !Descriptors for
binary-specific parameters
  1.0      1.0      1.0      1.0      0.0      0.0         !Default values
(i.e. ideal-solution)
  4 4      0        0 0      0 0      0 0      0 0         !# terms and #
coefs/term for normal terms, Kunz-Wagner terms, and Gaussian terms.  3rd
column is not used.
 -0.013073    7.4    1.   1.
!a(i),t(i),d(i),c(i)
  0.018259    0.35   3.   1.
  0.81299e-5  10.0   11.  2.
  0.0078496   5.3    2.   3.

Can you make a pull request to fix this?

**Comment by khlee22** [comment]
I have made the pull request in the branch "ext_fix" since I cannot make a new one. If it is not a proper branch, please move it another one.

**Comment by khlee22** [comment]
It's not easy for a beginner to make new fork and 'pull request'. Please check the validity of the pull request.

**Comment by ibell** [comment]
There is some info here:
https://github.com/CoolProp/CoolProp/wiki/Contributing:-git-development-workflow
.  You might want to just edit the file in the github website, and let
github manage the branches.  It takes a while to get comfortable in git,
that's for sure.
