### ISSUE TITLE
Hydrogen Pressure Issue

### ISSUE THREAD

**Issue by dwork101** [CoolProp/CoolProp#2154]
### **Description**

We are currently working on simulating pure hydrogen gas behavior in storage tanks while fulling and defueling the tank. Unfortunately, there seems to be a Coolprop issue when hydrogen in the tanks reaches or circles its critical density. Throwing the following error:

Python Error: ValueError: p is not a valid number : PropsSI("T","D",31.46258141,"U",2391760.261,"Hydrogen")

In general, the gas in the storage tanks should increase or decrease in density and at the same time increase or decrease its inner energy due to removing or including an enthalpy flow. So, the gas should always at some point reach up to its critical density and therefore possibly throw this error. 

However, we noticed that it is possible in some cases to adjust the simulation timestep and “skipping” the zone of the critical density. Unfortunately, this only works in some cases, and it is notoriously difficult to find the right starting parameters.     
So I just wanted to ask if there is any workaround for suppressing the error throw?

Thank you!

### **Steps to Reproduce**

Try: 
py.CoolProp.CoolProp.PropsSI('T','D',31.46258141'U',2391760.261,'Hydrogen')

### **Expected behavior:**
There should be a corresponding temperature as a result ranging between -40 to 140 °C depending on the parameters.  

### **Actual behavior:** 
No temperature output.

### **Versions**

**CoolProp Version:** 6.4.1.0
**Operating System and Version:** Windows 10
**Access Method:** Matlap Version R2021b with a Python 3.9 Wrapper

**Comment by ibell** [comment]
I would recommend that you, in this case, workaround by using the fsolve
function in MATLAB to solve for the temperature which gives you the right
internal energy.  That is what CoolProp is doing under the hood, but this
calculation is complicated by the critical region; in particular, solving
for the equilibrium temperature for densities near the critical density.
The failures there can be mitigated by the use of superancillary equations,
but those have not been implemented in CoolProp (yet).
