### ISSUE TITLE
Warning at CoolProp.CoolProp.State: Use CoolProp.CoolProp.AbstractState

### ISSUE THREAD

**Issue by carlos-adir** [CoolProp/CoolProp#2166]
This Issue is not very complicated or urgent, probably it's a documentation issue.
When I do ```help``` in ```State``` class, it says 

```
Warning: This class is deprecated.  You should use :py:class:`CoolProp.AbstractState` instead
``` 

But I don't know how to init an ```AbstractState```. Using ```help(CoolProp.CoolProp.AbstractState)``` or looking into its [documentation](http://www.coolprop.org/apidoc/CoolProp.AbstractState.html?highlight=state#module-CoolProp.AbstractState), it doesn't help much.

* Example code:

```python
from CoolProp.CoolProp import State, AbstractState
Pamb = 101325  # Pa
Tamb = 25 + 273.15  # K
mystate = State("air", {"T":Tamb, "P": Pamb})  # Nice
mystate = AbstractState("air", {"T":Tamb, "P": Pamb})  # Error
```

**Comment by ibell** [comment]
Please see http://www.coolprop.org/coolprop/LowLevelAPI.html
