### ISSUE TITLE
calculate error with refprop 9.1

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#2174]
### Versions
**CoolProp Version:** 6.4.1 
**Operating System and Version:** windows 10  
**Access Method:** C# 
** refprop ver. 9.1
### Additional Information

Hi, there， I got compare  this four way to caluate sat Temperature 

···
double PPPP = -0.96900795620149793;
//1、 this got error, BUT ITS OK
// System.ApplicationException:“Pressure to PQ_flash [     0 Pa] must be in range [0.000171848 Pa, 4.2512e+06 Pa]”
string refname = "R290";
CoolProp.PropsSI("T", "P", PPPP * 1000, "Q", 1, refname)

//2、 this got error, BUT ITS OK
//System.ApplicationException:“Pressure to PQ_flash [     0 Pa] must be in range [0.000171848 Pa, 4.2512e+06 Pa]”
string refname = "PROPANE";
CoolProp.PropsSI("T", "P", PPPP * 1000, "Q", 1, refname)

//3、this got error, BUT ITS OK
// Initialize failed for backend: "REFPROP", fluid: "R290" fractions "[ 1.0000000000 ]"; error: Could not load these fluids: R290
string refname = "REFPROP::290";
CoolProp.PropsSI("T", "P", PPPP * 1000, "Q", 1, refname)

//4、this work ok？？？ amazing
//300
string refname = "REFPROP::PROPANE";
CoolProp.PropsSI("T", "P", PPPP * 1000, "Q", 1, refname)
···

**Comment by ibell** [comment]
1), 2), 3) should all yield exception in C# (R290 is not a valid identifier
in REFPROP)

4) should be ok because your input is 300 kPa, if I understand your post
correctly.

**Comment by ibell** [comment]
For 4), it works because your input argument is temperatureCompIn rather
than PPP. If I understand correctly, that is.

**Comment by birdol** [comment]
> For 4), it works because your input argument is temperatureCompIn rather than PPP. If I understand correctly, that is.
> […](#)
> Message ID: ***@***.***>

I had already edit my post。   there is no temperatureCompIn anymore

**Comment by ibell** [comment]
I think this is a bug in Refprop, you should get an out of range error

**Comment by birdol** [comment]
but when i call refprop in excel，with formula ：
=Temperature("PROPANE","PQ","C",-0.000969007956201497,1)

it's show error “#[PQFLSH error  4] one or more inputs are out of range:    pressure < 0, P =-0.96901E-03 MPa ”

**Comment by jowr** [comment]
Is this a REFPROP problem? If so, can we close this issue?
