### ISSUE TITLE
Please update github release

### ISSUE THREAD

**Issue by jsalort** [CoolProp/CoolProp#2178]
Would it be possible to create a new GitHub release ? The last one is currently from 2020. The reason I am asking is that I have submitted a PR to the Macports repository to have a macports package for coolprop. And the policy in MacPorts is to pull the source tarballs from a release, or based on a tag. They do not want port version with some random git commit hash.

See: https://github.com/macports/macports-ports/pull/14841

**Comment by ibell** [comment]
I do not have the bandwidth to do this right now but I emailed some
developers to see if someone could help out. I agree entirely that a new
release is warranted.

Nevertheless, why macports? Wouldn't it be better to install pre-built
binaries?

**Comment by jsalort** [comment]
I use MacPorts because I install a lot a different software, and it is convenient to have one consistent package manager, instead of installing a bunch of pre-built binaries from various sources. It is also easier to upgrade, or roll back to a specific version. It is similar to how much more convenient it is to use apt-get on Linux instead of installing every software manually (even pre-built). That being said, I understand that pre-built binaries are nice for people who like to install a few packages in this way.

MacPorts has strict requirements for ports, to ensure robustness and cleaness. Other package managers make other choices which also make sense depending on what one wants. Another issue with CoolProp in its present form is that I am under the impression that it also manually installs several external dependencies such as pybind11, using git submodules, while those should be (and are) available in the package manager already, and could just be marked as a dependency. I don't know if it is possible to have a flag to indicate not to install external dependencies, but instead to have a clear list of what the dependencies are. Relying on a package manager also avoids duplicates.

I am aware that all this requires time, and I am not in a hurry. I have made my own CoolProp Portfile (see the MacPorts Pull-request linked above), and it works for my personal use. The only issue is that if I want to get it merged in MacPorts for others to use (which would be convenient to get my students to install CoolProp on their machine, on top of other software that we need), then I need to base the Portfile on a release instead of a hash, and remove the manually installed external dependencies...

**Comment by longemen3000** [comment]
another datapoint: i use CoolProp mainly from the julia wrapper. the wrapper downloads a precompiled binary of CoolProp available from https://github.com/JuliaPackaging/Yggdrasil. (compiled to a list of architectures listed in https://github.com/JuliaBinaryWrappers/CoolProp_jll.jl)  .To support an M1 build, a new version was needed for semver reasons. (see https://github.com/JuliaPackaging/Yggdrasil/issues/5468). a release has to be made up to allow the new platform. It would be great to have a new version tagged

**Comment by ibell** [comment]
@longemen3000 I backported the binaries for 6.4.1 to include the M1 binaries, it should work, works on my M1 MacBook now.

@jsalort I get the point of macports, but I guess my question was more along the lines of why macports rather than homebrew, which seems to have swallowed macports whole. Or at least, from where I sit that seems to be the case.

**Comment by jsalort** [comment]
> @jsalort I get the point of macports, but I guess my question was more along the lines of why macports rather than homebrew, which seems to have swallowed macports whole. Or at least, from where I sit that seems to be the case.

MacPorts is still well alive. I have been using it for ages, since when it still was called DarwinPorts. I've only started making small contributions recently (essentially ports that I need). Fink is also alive and well AFAIK. Homebrew has very good communication skills for sure, which both MacPorts and Fink appear to lack, but I haven't noticed that it had any impact on MacPorts development at all, and there is a user base that still continues to use those systems and are happy with them. The design choices are quite different, and it is a good thing that people have a choice.

Amongst other things, one of the very important point of MacPorts is that they support much more platforms: they still have support for Mac OS X 10.5 on PowerPC. That requires quite some work from them, notably regarding the libc and C++ standard library, and how to link with older system libraries, which is also a reason why you may not want to try to bundle the external dependencies yourself, you'll only succeed for the very recent OS unless you spend prohibitive time on the issue. Indeed supporting older OS is far from trivial, but is solved within MacPorts because they never stopped the support and adapted along the way. 
In the end, for people like me who tend to keep computers for a while, it is very important because it allows to keep the same up-to-date installation on all the machines, even the older ones. Though I don't personnally use PowerPC machines anymore, I do have colleagues who still do, because they use it for experiment controls with older hardware which is not always supported by newer machines. Changing the harware may be too costly, not to mention the environmental impact of changing some harware just for software reasons. (and this hardware is not connected to the internet, so the question of system security of those old OS is moot).

In addition to that, there is the port system with the notion of "variants" which is very nice. Overall, MacPorts is robust, reliable and with a strong emphasis on backwards compatibility, and it provides a clean and consistent environment. It has also become much easier to contribute now that it is hosted on Github.
