### ISSUE TITLE
CoolProp Online throwing internal error

### ISSUE THREAD

**Issue by Lalo-ATX** [CoolProp/CoolProp#2184]
CoolProp online page here

http://www.coolprop.org/online/index.html

links to here

https://ibell.pythonanywhere.com/

2nd link returns "Internal error" and "Ticket issued: coolpropgit/...."

**Comment by ibell** [comment]
I won't be able to look into this for at least a week, but I will after
that.

**Comment by ibell** [comment]
Back online
