### ISSUE TITLE
Ammonia critical point issue behaviour

### ISSUE THREAD

**Issue by b10stompson** [CoolProp/CoolProp#2186]
As you already know ammonia critical point issue affects the construction of ammonia diagrams. I report the behaviour of saturation curves around critical point using the code https://github.com/jjfPCSI1/py4phys/blob/master/lib/T6_diagramme_Ph_coolprop.py
As you can see from a certain pressure the calculations near critical point explode.
Hope it could be helpful to solve the problem.
![image](https://user-images.githubusercontent.com/118093652/201506838-4da5644b-2da1-489b-880c-ea50cb619a3d.png)

**Comment by ibell** [comment]
What version are you using?  If 6.4.1, please try with 6.4.2

**Comment by ibell** [comment]
https://github.com/CoolProp/CoolProp/issues/2119

**Comment by cyrilpic** [comment]
Thanks! I can confirm that at least for me, the issues with ammonia are resolved in 6.4.2.
