### ISSUE TITLE
The online version of CoolProp cannot work

### ISSUE THREAD

**Issue by David-Alfred** [CoolProp/CoolProp#2187]
### Description

The online version of CoolProp cannot work

### Steps to Reproduce

1. Open the webpage:  https://ibell.pythonanywhere.com/
2. Get error: Internal error  Ticket issued: Unknown
![image](https://user-images.githubusercontent.com/42257910/202835228-a69f79a4-f21c-486f-869f-7fcf3aee2834.png)

**Comment by ibell** [comment]
Back online
