### ISSUE TITLE
CoolProp pure Hexane bug

### ISSUE THREAD

**Issue by k3ro** [CoolProp/CoolProp#2200]
### Description
It seems like a error on my part but for some reason CoolProp seems unable to calculate the vapor temperature of hexane at low pressures.

### Steps to Reproduce
I just want to convert vapor pressures of pure n-hexane into the corresponding temperature.
6065 Pa is the Vapor pressure of Hexane at 0°C.
 Code:
  
import CoolProp.CoolProp as CP
CP.PropsSI('T','P',6065,'Q',0,"Hexane")

**Expected behavior:** [What you expect to happen]

I expect it to return 273. 
As this is the vapor temperatur in Kelvin.

**Actual behavior:** [What actually happens]

ValueError: solver_rho_Tp was unable to find a solution for T=    507.82, p=      6065, with guess value     5522.8 with error: The molar density of -9.484198 mol/m3 is below the minimum of 0.000000 mol/m3 : PropsSI("T","P",6065,"Q",0,"Hexane")

### Versions

**CoolProp Version:** 6.4.3.post1
**Operating System and Version:** Windows 10 Enterprise
**Access Method:** Im using python and spyder

### Additional Information

I also tried to calculate the pressure for 273K and input that pressure. 
but that is also not possible:
import CoolProp.CoolProp as CP
Pressure = CP.PropsSI('P','T',273,'Q',0,"Hexane")

print(Pressure)

import CoolProp.CoolProp as CP
Temp = CP.PropsSI('T','P',Pressure,'Q',0,"Hexane")

print(Temp)

solver_rho_Tp was unable to find a solution for T=    507.82, p=   5992.24, with guess value    5459.22 with error: The molar density of -10.228558 mol/m3 is below the minimum of 0.000000 mol/m3 : PropsSI("T","P",5992.242029,"Q",0,"Hexane")

**Comment by ibell** [comment]
I can confirm this bug. Not sure why, but it is definitely happening.

**Comment by k3ro** [comment]
Thanks ibell for confirming this issue.
I have now played around with this problem and i found another issue:

The vapor pressure calculated from CoolProp for hexane at 273K is 5992.242029006102 (Pa).
When i enter this to calculate the temperature again i get the same error:

Code : CP.PropsSI('T',"P",5992.242029006102,'Q',0,"Hexane")
Error:
ValueError: solver_rho_Tp was unable to find a solution for T=    507.82, p=   5992.24, with guess value    5459.22 with error: The molar density of -10.228558 mol/m3 is below the minimum of 0.000000 mol/m3 : PropsSI("T","P",5992.242029,"Q",0,"Hexane")



But if i use only 5992.2 for the pressure:
Code:  CP.PropsSI('T',"P",5992.2,'Q',0,"Hexane")

I get: 507.819999
Which is really strange. Because of course that is not 273K. I don't even know what unit this is supposed to be.


It gets even stranger... If i repeat this calculation now for Hexane at 400 K  i get a pressure of 466276.6274843224 Pa.
When i then calculate the temperature from this pressure i get 399.9999973218979 K which is totaly fine.
But this proves that the unit is supposed to be K. Also there i no difference whether i enter the Pressure at 400K with all its digits or just 466276.6.  Using 466276.6. Pa i get a Temperature of 399.9999973218979 K. Which is fine. But no error, just like it is supposed to be.

**Comment by longemen3000** [comment]
found the error here @ibell, triple point densities are inverted. i don't know how CoolProp generates initial guesses for volumes, but i generate mine with triple point densities.

**Comment by longemen3000** [comment]
at 273K ,the liquid density ancillary gives a value of 18168.32890296282 [mol/m3], which is higher than the triple point density of 8801.554295434455 [mol/m3]

**Comment by ibell** [comment]
Can you fix the ancillary? Perhaps that is the problem?

**Comment by longemen3000** [comment]
update: that was not the problem, checked again and the ancillary was fine (error in my code). that makes the error more weird, i can't reproduce it using the same parameters.

**Comment by longemen3000** [comment]
btw, 507.82 is the critical point of hexane. how is the first estimation for that combination of inputs calculated?

**Comment by ibell** [comment]
> btw, 507.82 is the critical point of hexane. how is the first estimation for that combination of inputs calculated?

Not sure I follow your question

**Comment by longemen3000** [comment]
>  ValueError: solver_rho_Tp was unable to find a solution for T= 507.82, p= 5992.24, with guess value 5459.22 with error: The molar density of -10.228558 mol/m3 is below the minimum of 0.000000 mol/m3 : PropsSI("T","P",5992.242029,"Q",0,"Hexane")
Somehow, the critical temperature of hexane is being used as an first guess for a temperature that could solve for P = 5992..., Q = 0

**Comment by ibell** [comment]
Weird. Can you see why it guesses the critical point temperature?

**Comment by longemen3000** [comment]
hmm, not totally familiar with the CoolProp codebase, but i can check

**Comment by ibell** [comment]
@msaitta-mpr want to take on another one?

**Comment by longemen3000** [comment]
another clue: 507.819999 = Tc - 1e-6, i saw some of those in VLERoutines.cpp.

**Comment by msaitta-mpr** [comment]
Looks like it is failing in the Akshasa saturation solver. I will need some time to come up with a solution.

**Comment by ibell** [comment]
Actually I think this is my booboo.  I think I possibly messed up the
ancillary when converting. See a fix in :
https://github.com/usnistgov/teqp/commit/7de5755594f0c3ba201a9ecd368be5dd0543d7a7
. I think that fix is needed in CoolProp too.

**Comment by msaitta-mpr** [comment]
Good thinking. Making that change makes the original test problem return 273.225 ("273" expected).

**Comment by ibell** [comment]
Can you file a PR with this fix?

**Comment by msaitta-mpr** [comment]
The fix has been implemented in the code. If you need the fix now, you can download the latest copy of the source code and rebuild CoolProp on your own machine. Alternatively, you can wait for the official release, but I do not know when the maintainers will do that. 

A "PR" is a "Pull Request". It is a formal way of modifying the code that allows for traceability and peer review.
