### ISSUE TITLE
N-heptane has repeated IdealGasHelmholtzCP0AlyLee

### ISSUE THREAD

**Issue by longemen3000** [CoolProp/CoolProp#2201]
While parsing the JSONs for consistency, i found this repeated Aly-lee term for n-Heptane

https://github.com/CoolProp/CoolProp/blob/d241e083b7dae0163c1d8be2991cba135ad3bd5a/dev/fluids/n-Heptane.json#L253-L276

which is the correct one? are both used?

**Comment by ianhbell** [comment]
Please take a look at the original publication; my recollection is that there are multiple terms of the same form, in CoolProp, these terms are added together.

**Comment by longemen3000** [comment]
investigating a little more, the alylee form in the original paper has 7 terms, whereas CoolProp only seems to parse 5 at a time, so repeating those two is the only option to account for the complete equation. It is important to note that only two fluids use this ideal term: n-heptane and D6.
