### ISSUE TITLE
Wrong enthalpy for Ammonia

### ISSUE THREAD

**Issue by wolfgang-302** [CoolProp/CoolProp#2204]
### Description

I am using CoolProp.CoolProp.PropsSI to calculate values for ammonia.

```python
import CoolProp
CoolProp.__version__
```
results in  '6.4.1'
```python
import CoolProp.CoolProp as CP

T_0 = 273.15 # K
t = -25 # degC
Q = 1 # Vapor quality

fluid = 'Ammonia'

CP.PropsSI('H','T',T_0+t,'Q',Q,fluid) # J/kg
```

**Actual behavior**
1576181.3550504625 # J/kg

**Expected behavior**
1430651.6538970063 # J/kg

(This value is from iapws, other sources have similar values)

**CoolProp Version** 
6.4.1

**Operating System and Version:** [OS you are running CoolProp on]  
MAC OS on M1-chip

**Access Method:**
Python 3.10

**Comment by ibell** [comment]
See our most popular FAQ: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by wolfgang-302** [comment]
I confess, i should have known this. Or should have read the FAQ before posting.
So let me wish you a Happy New Year. And thank you for the prompt answer
Wolfgang
