### ISSUE TITLE
Coolpropgit has internal error when under saturation dome

### ISSUE THREAD

**Issue by KianAtWSU** [CoolProp/CoolProp#2219]
### Description

When obtaining fluid properties with CoolProp Online (Coolpropgit) for fluids where properties are under the saturation dome, or a quality is specified that is greater than 0 and less than 1, an internal error occurs.

### Steps to Reproduce

Specify quality in range (0, 1) with valid other property.
Click submit.
Error will be reported.

### Additional Information

![image](https://user-images.githubusercontent.com/114362340/222852551-3587a743-c64c-4d9d-9e28-a4129080dab9.png)

========================================================

![image](https://user-images.githubusercontent.com/114362340/222852576-53de2906-08a1-4282-88b0-1526ef175d36.png)

**Comment by ibell** [comment]
I fixed it; speed of sound is not valid for two-phase states
