### ISSUE TITLE
The steps for adding an Excel (Version 16.43) wrapper doesn't work for MacOS (10.13.6)

### ISSUE THREAD

**Issue by sagarkhushalraozade** [CoolProp/CoolProp#2224]
The steps for adding an Excel (Version 16.43) wrapper in http://www.coolprop.org/coolprop/wrappers/Excel/index.html doesn't work for MacOS (10.13.6). Despite following all the steps, I was getting an .....Error 53: Cannot find the file..... This was not related to me needing a 32 bit version of libCoolProp.dylib as suggested in the debug steps of the manual. 

One of the reasons is that the command
**launchctl setenv DYLD_LIBRARY_PATH** to be pasted in the new .plist file doesn't work due to Apple's system integrity protection.

However, I was able to get it to work by copying the libCoolProp.dylib file to another location **/Users/yourusername/Library/Containers/com.microsoft.Excel/Data**. Credits: https://stackoverflow.com/questions/53772597/dylib-file-not-found-vba-excel-mac-2016

Note that when I do the following in my Terminal:
`$ file libCoolProp.dylib `
I get the following output:
`libCoolProp.dylib: Mach-O 64-bit dynamically linked shared library x86_64`
This means that I am using the correct 64 bit version of libCoolProp.dylib

Another thread that greatly helped me: https://github.com/CoolProp/CoolProp/issues/1430

**Comment by YanZhang20220712** [comment]
hi sagarkhushalraozade, pls check this [thread](https://github.com/CoolProp/CoolProp/issues/2235) for help.
