### ISSUE TITLE
fatal error: fmt/format.h: No such file or directory  

### ISSUE THREAD

**Issue by ztdepztdep** [CoolProp/CoolProp#2228]
fatal error: fmt/format.h: No such file or directory
 #    include "fmt/format.h"  // For addition of the string formatting functions and macros from fmtlib

 I have install fmt8 in opensuse system. but how to resolve this error.

**Comment by ibell** [comment]
I'm guessing you did not do a recursive clone? It is ok,  because you can
now do a: git submodule init --recursive

**Comment by chen-erqi** [comment]
hi!
Do you solve this question?
I meet this question too, and I dont know how to solve it.
Could you please to tell me how to do?

**Comment by wandadars** [comment]
> hi!
> Do you solve this question?
> I meet this question too, and I dont know how to solve it.
> Could you please to tell me how to do?

Did you follow Ian's suggestion from his reply to the original issue?

**Comment by chen-erqi** [comment]
> > hi!
> > Do you solve this question?
> > I meet this question too, and I dont know how to solve it.
> > Could you please to tell me how to do?
> 
> Did you follow Ian's suggestion from his reply to the original issue?

yes, I follow the reply and do this clone:
git clone --recursive [the url of coolprop]
and I check the files that fmt/format is exist.

specifically, I try to use C++ with coolprop and g++ to compile.
And I try to include "CoolProp.h" and add the include path and -I args as follows:

`
"includePath": [
                "${workspaceFolder}/**",
                "C:/{myworkspace}/coolprop_c/CoolProp/include**",
                "C:/{myworkspace}/coolprop_c/CoolProp/externals/fmtlib/include**"
            ],
`

`
"-I",
                "C:\{myworkspace}\\coolprop_c\\CoolProp\\include",
                "C:\\{myworkspace}\\coolprop_c\\CoolProp\\externals\\fmtlib\\include",
`

In the end, it doesnt work.
Could you please to give me a advice? Sincerely thanks a lot!

**Comment by ibell** [comment]
Please use the approach in https://github.com/CoolProp/simple_cmake_example . Full integration with CMake is strongly recommended.

**Comment by chen-erqi** [comment]
> Please use the approach in https://github.com/CoolProp/simple_cmake_example . Full integration with CMake is strongly recommended.

thanks a lot! and i have solved this question successfully!
