### ISSUE TITLE
Compiling SU2 using CoolProp for thermodynamic properties

### ISSUE THREAD

**Issue by GianmarcoFarro** [CoolProp/CoolProp#2232]
When I run the simulation with SU2 using CoolProp to compute the thermodynamic properties of the fluid in use I get the following error:

Error in "CCoolProp::CCoolProp(std::__cxx11::string)": 
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
-------------------------------------------------------------------------
SU2 was not compiled with CoolProp (-Denable-coolprop=true). Note that CoolProp cannot be used with directdiff or autodiff

Can you help me to solve this problem?

**Comment by ibell** [comment]
Sounds like a problem in SU2. You mean you did compile with CoolProp
right?

**Comment by GianmarcoFarro** [comment]
Exactly. It sounds like it can't use those libraries. To try to fix the
problem I downloaded the CoolProp library again but it still doesn't work.
Do you know, basing on the error I get, how can I fix the problem?

Il Dom 2 Apr 2023, 21:04 Ian Bell ***@***.***> ha scritto:

**Comment by ibell** [comment]
I have no idea. It sounds like SU2 has hooks for CoolProp, but I have no idea how to use them.

**Comment by GianmarcoFarro** [comment]
Have you ever seen this error message?

Il Lun 3 Apr 2023, 00:23 Ian Bell ***@***.***> ha scritto:

**Comment by ibell** [comment]
No,  it doesn't come from coolprop

**Comment by GianmarcoFarro** [comment]
Indeed, it comes from SU2. It's weird because the CoolProp libraries are
installed in the machine

Il Lun 3 Apr 2023, 12:57 Ian Bell ***@***.***> ha scritto:

**Comment by GianmarcoFarro** [comment]
How should I check if coolprop works? I mean what is the command to tap on
the command line to compute properties using coolprop? I'm working on Ubuntu

Il Lun 3 Apr 2023, 13:12 Gianmarco Farro ***@***.***> ha
scritto:

**Comment by GianmarcoFarro** [comment]
Ok, thank you anyway

Il Lun 3 Apr 2023, 15:23 Ian Bell ***@***.***> ha scritto:
