### ISSUE TITLE
Pressure units in CoolProp online

### ISSUE THREAD

**Issue by WarthogARJ** [CoolProp/CoolProp#2236]
Hi,
Firstly, thanks VERY much for all your work on CoolProp, and at NIST.

A minor issue, but would it be possible to change the Pressure units in CoolProp online from Pa to.....anything else?
Preferably MPa or Bar?
I'm truly a fan of the SI unit system, but sometimes....

Even units of Adult Elephant Weight per Adult Elephant Foot would be better in terms of reducing the zero's...

Thank you in the hope that you have a Nice Day...:-}
Alan
N.B. Perhaps I should add that a Standardized African Elephant's Foot pressure is 18,717 Pa.
Using the standard assumptions that he places his weight on all four legs evenly, and keeps trunk off ground, or pesky tourists.

If nothing else, using these units would get some excellent comments from our friends in Germany.

**Comment by Padanian** [comment]
Pa is fine for me. Assuming you're not a troll, why don't you just divide by 1e3 or 1e6?

**Comment by ibell** [comment]
I think the OP meant this in a very tongue-in-cheek way. The core of
CoolProp will never change from base SI on my watch,  but I'm open to
changing the units on tools that call or use CoolProp core.  Or at least
making it an option. But this also opens a pandoras box that might be best
kept closed.

**Comment by WarthogARJ** [comment]
Howzit,
Me no Troll.
Dang.
Maybe I make bad jokes....:-}

As far as just dividing by whatever, sure.

I CAN convert, and have.
I am Canadian born (in 1960), and went to Queen's (Kingston, not the Irish variant) to do engineering.
And learned both sets of units for engineering, as well for as my subsequent jobs in the oilfield and related R&D.

HOWEVER, there's a LOT to be said for making the units work FOR you.

As in, do you think in m/sec when you DRIVE?
Or walk or run?
No.
Why not??

And, if you do any work in crystallography, you see right away that Angstroms are still a pretty sensible unit to use in terms of atomic structure.

And there's still a LOT of solid state guys in magnetics who still use the non-SI system.
Not just the old ones, either.

Perhaps I digress, but many moons ago I was on a road trip in South Africa with some friends, and we stopped to brew up under a bridge.
One guy, a civil engineer, asked me how fast the water was flowing next to us.
This was before I started kayaking seriously, so I wasn't hands-on with flow rates.
Hmmmmm .....well, what are the units you guys use, I asked?
Aha....he said. You've got it.
And yeah, I did.
Cubic metres/sec.
Go outside and look at a stream: you can visualise a rough cross section, and think of a chunk of it 1 metre long moving along at some multiple of m/sec.

Knowing the right units is half the battle.

As in, if it's cubic metres per sec as most suited, then even a wild guess from somewhere between 1 to a 100 is STILL within +/- an order of magnitude: close enough for government work, as they say at NIST: right?

And....Grasshopper, as David Carradine used to say.
There's more.

Do you know the most sensible units to estimate size (volume) of an oilfield reservoir for a lot of people?
Is NOT in SI system.
Acre-feet.
Yup.
I HATE American/Imperial units....but....
THINK about it.
For someone standing a few km above some oil reservoir, you can roughly estimate volume by a vague idea of the AREA it covers (again, like the stream example: in 99% cases is somewhere between 10 acres to a few hundred for a BIG sucker).
And depth is going to be ballpark from a 10 feet for REALLY thin to a few hundreds of feet).
Multiple together, and you've got a volume estimate that ANYONE can actually VISUALLIZE.
AND, you can improve its accuracy once you get a bit more info.

Mr. SI Man, if you had to say in cubic metres, you'd have ZERO clue on what seemed abut right.

OK: you COULD go a little bit metric and use hectare-metres: as long as you have a good grasp of how big a hectare is.

**Comment by WarthogARJ** [comment]
Anyways: I made my point.
Perhaps at least you could adjust the output so it puts out in scientific notation.
At the moment it doesn't even add in commas.

Thanks for your time.
And patience.

**Comment by Padanian** [comment]
> I do like SI units, but I regard MPa as an SI unit: with a built in factor of 10^6. I'm an engineer: NOBODY uses Pascals on their own for ANYTHING that's related to real life.

Wrong, Fans pressure is measured in Pa, and rightly so. 
Bananas on square thumbs not applicable.

**Comment by WarthogARJ** [comment]
Heh heh heh...
But I didn't poke fun at the commonly used Italian pressure units of "rubbio/scorza", now did I???

As for Pascals for fans: you got me there.
I DID think about a real life application that uses Pa on its own: and yeah, fans is perhaps the only one.

But don't think me as a sore loser, you tend to see it as "mm Hg" though, or in Donald Trump units in "inches H2O".

And jeez, what's wrong with bananas per square thumb??
You're just not a open-minded guy.
__________
You can ignore this next.....unless it's coffee time for you.
My first job was in the oilfield, working in the Sumatran jungle in Indonesia with a Japanese company trying to find oil where there wasn't any.

So we drill to what was SUPPOSED to be the oil reservoir, hook-up the lines to the burner pit, and open the valves.
They were HOPING for oil or gas to flow.
NOTHING.
The very hopeful Japanese Drilling Engineer insists my prssure gauge is not working, and insists I change it.
After going from 10,000 psi to 1,000 psi to 10 psi he's STILL not happy.

So I stick on a length of rubber hose and put it into a bucket of water.
AHA!!!!
BUBBLES!!!
He's happy.

Asks me the pressure.
I think: Jeez, this guy just doesn't wan to admit this well is a dud.
So I convert inches of water into psi (and for Herr Ian Bell, I COULD do it in Pascals as well).
He's MUCH happier.
Except then he gets cocky, and wants to know the flow rate.
????!!!!££$%....arggghhhh

Jeez.....OK, so I do a calculation to give him a flow rate.
And note, this was in 1982, there's ZERO internet: no personal computers at the rig site.
Best I have is a HP calculator and some paper and a really vague attempt to use Bernoulli's equation.

But I DID double check it by measuring bubbles/second, with an average bubble size.
