### ISSUE TITLE
different result coolprop and refprop10

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#2239]
hi there 
I use refprop10 and coolprop 6.4.3

T=9.7778℃
P=2154.0 KPa A

I got result：
coolprop：
=PropsSI("H","T",9.778+273.15,"P",2154*1000,"REFPROP::R454B.MIX")
=222620.6 =222.6206 kJ/kg
refprop
=Enthalpy("R454B.MIX","TP","C",9.778,2154/1000)
=216.0817  kJ/kg
i also check other way to call refprop，for example C# ，I got 222.6206  kJ/kg
and  with refprop‘s user interface, i got 216.0817 

why?

another problem:
if i use the firest formula(coolprop) in excel，then the second formula(refprop) can also get 222.6206  kJ/kg
which one I can believe？

![why](https://user-images.githubusercontent.com/8532202/231203833-49440f94-a08e-436c-9da9-d8826c193a36.png)

**Comment by ibell** [comment]
Reference states are not trivial for mixtures. Note that REFPROP has multiple approaches for setting reference starts for mixtures, and CoolProp doesn't set reference states for mixtures.

**Comment by birdol** [comment]
I tested four methods:

            CoolProp.set_reference_stateS("REFPROP::R454B.MIX", "IIR");
            CoolProp.set_reference_stateS("REFPROP::R454B.MIX", "ASHRAE");
            CoolProp.set_reference_stateS("REFPROP::R454B.MIX", "NBP");
            CoolProp.set_reference_stateS("REFPROP::R454B.MIX", "DEF");

The result is nothing like the refprop

**Comment by birdol** [comment]
Thank you very much. I notice that the excel add-on to refprop calls：
```
SetRefdll(hrf, 2, x(0), hRef, sRef, Tref, pref, ierr, herr, 3, 255)
```
which comment ：
```  'Use the following line to calculate enthalpies and entropies on a reference state
            'based on the currently defined mixture, or to change to some other reference state.
            'The routine does not have to be called, but doing so will cause calculations
            'to be the same as those produced from the graphical interface for mixtures.
```
What happens if I edit the file
CoolProp-master\src\Backends\REFPROP\REFPROPMixtureBackend.cpp

?

Can I compile my own binaries with Visual Studio ?

**Comment by birdol** [comment]
the function set_reference_stateS   set ixflag =1 hardcode.  why?

**Comment by ibell** [comment]
My short answer, which I am sure you will not like, is to not worry about reference states for mixtures.

**Comment by ibell** [comment]
My longer answer is you need to show what you tried to do to get compilation errors. Make sure you check out recursively and build with cmake.

**Comment by birdol** [comment]
aha，😆Im ok，🤣but my program ‘s user  donot like……
I trying hrad on complie，no much error now，only when I call it form c#, vs told me “not found entry point”🥹

**Comment by birdol** [comment]
1、about the compiling error
https://github.com/CoolProp/CoolProp/blob/5f3223c505d507a8543ddaa0dea899ca6533087d/dev/generate_headers.py#L178
the function “gitrev_to_file” show error(like utf8/ascii code seems like some strange errors ,maybe only happend in my computer. But that doesn't matter. ) while compling.

I change it like this:
```
def gitrev_to_file(root_dir):
    """
    If a git repo, use git to update the gitrevision.  If not a git repo, read
    the gitrevision from the gitrevision.txt file.  Otherwise, fail.
    """
    hashes['gitrevision'] = "myprop20230425"
```
https://github.com/CoolProp/CoolProp/blob/master/src/CoolProp.cpp#L69
can not find include file gitrevision.h, need commented out
https://github.com/CoolProp/CoolProp/blob/master/src/CoolProp.cpp#L988
gitrevision no define, change it =>     return version;

2、about the different between “coolprop call refprop backend”and refprop ui.
My current test result is like this.
https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L345
change it like this，add three lines bellow:
```
                SETMIXdll(mix, hmx_bnc, reference_state, &N, component_string, &(x[0]), &ierr, herr, 255, 255, 3, 10000, 255);
                int ixflag = 2;
                double h0 = 0, s0 = 0, t0 = 0, p0 = 0;
                SETREFdll(reference_state, &ixflag, &(x[0]), &h0, &s0, &t0, &p0, &ierr, herr, 3, 255);
```

I don't know if there are any other issues with this modification?

**Comment by ibell** [comment]
How did you try to build? You should have run ``python setup.py bdist_wheel`` in the wrappers/Python folder. Maybe you need to do a fresh clone

**Comment by birdol** [comment]
build step?
1、git clone https://github.com/CoolProp/CoolProp --recursive
2、mkdir build86 && cd build86
3、cmake .. -DCOOLPROP_CSHARP_MODULE=ON -DCOOLPROP_NO_EXAMPLES=ON -DCOOLPROP_SWIG_OPTIONS="-namespace MyProp" -G "Visual Studio 15 2017"
4、cmake --build .

I found it form  here：   http://www.coolprop.org/coolprop/wrappers/Csharp/index.html#user-compiled-binaries


I need c# wapper.

**Comment by ibell** [comment]
Did you try to call the set_reference_stateS method on an instance of the low-level interface?

**Comment by birdol** [comment]
> Did you try to call the set_reference_stateS method on an instance of the low-level interface?

not work for predefind mixtures.

**Comment by ibell** [comment]
This method: http://www.coolprop.org/coolprop/LowLevelAPI.html#reference-states

**Comment by ibell** [comment]
To be called *after* instantiation

**Comment by birdol** [comment]
My check code bellow
```
import sys

import CoolProp as CP

# ALL TEST fllow T=9.7778℃，P=2154 kPa A。

def mycheck_c_nothing_R410A():
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A")
    print("Coolprop R410A Without setREF",h1)

def mycheck_c_DEF_R410A():
    CP.CoolProp.set_reference_state('R410A', 'DEF')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A")
    print("Coolprop R410A With setREF DEF",h1)

def mycheck_c_NBP_R410A():
    CP.CoolProp.set_reference_state('R410A', 'NBP')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A")
    print("Coolprop R410A With setREF NBP",h1)

def mycheck_c_IIR_R410A():
    CP.CoolProp.set_reference_state('R410A', 'IIR')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A")
    print("Coolprop R410A With setREF IIR",h1)

def mycheck_c_ASHRAE_R410A():
    CP.CoolProp.set_reference_state('R410A', 'ASHRAE')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A")
    print("Coolprop R410A With setREF ASHRAE",h1)

def mycheck_c_nothing_R410AMIX():
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A.MIX")
    print("Coolprop R410A.MIX Without setREF", h1)
def mycheck_c_DEF_R410AMIX():
    CP.CoolProp.set_reference_state('R410A', 'DEF')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A.MIX")
    print("Coolprop R410A.MIX With setREF DEF",h1)

def mycheck_c_NBP_R410AMIX():
    CP.CoolProp.set_reference_state('R410A', 'NBP')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A.MIX")
    print("Coolprop R410A.MIX With setREF NBP",h1)

def mycheck_c_IIR_R410AMIX():
    CP.CoolProp.set_reference_state('R410A', 'IIR')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A.MIX")
    print("Coolprop R410A.MIX With setREF IIR",h1)

def mycheck_c_ASHRAE_R410AMIX():
    CP.CoolProp.set_reference_state('R410A', 'ASHRAE')
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "R410A.MIX")
    print("Coolprop R410A.MIX With setREF ASHRAE",h1)


def mycheck_c2r_nothing():
    h1 = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "REFPROP::R410A.MIX")
    print("Coolprop REFPROP::R410A.MIX Without setREF",h1)

def mycheck_c2r_DEF():
    CP.CoolProp.set_reference_state('REFPROP::R410A', 'DEF')
    h_def = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "REFPROP::R410A.MIX")
    print("Coolprop REFPROP::R410A.MIX With DEF",h_def)
def mycheck_c2r_NBP():
    CP.CoolProp.set_reference_state('REFPROP::R410A', 'NBP')
    h_def = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "REFPROP::R410A.MIX")
    print("Coolprop REFPROP::R410A.MIX With NBP",h_def)

def mycheck_c2r_IIR():
    CP.CoolProp.set_reference_state('REFPROP::R410A', 'IIR')
    h_def = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "REFPROP::R410A.MIX")
    print("Coolprop REFPROP::R410A.MIX With IIR",h_def)


def mycheck_c2r_ashrae():
    CP.CoolProp.set_reference_state('REFPROP::R410A', 'ASHRAE')
    h_def = CP.CoolProp.PropsSI("H", "T", 9.7778 + 273.15, "P", 2154 * 1000, "REFPROP::R410A.MIX")
    print("Coolprop REFPROP::R410A.MIX With ASHRAE",h_def)




# 按装订区域中的绿色按钮以运行脚本。
if __name__ == '__main__':
    print("coolprop with R410A, this case maybe like R410A.PPF?")
    mycheck_c_nothing_R410A()
    mycheck_c_DEF_R410A()
    mycheck_c_NBP_R410A()
    mycheck_c_IIR_R410A()
    mycheck_c_ASHRAE_R410A()
    print("\r\n")

    print("coolprop with R410A.MIX")
    mycheck_c_nothing_R410AMIX()
    mycheck_c_DEF_R410AMIX()
    mycheck_c_NBP_R410AMIX()
    mycheck_c_IIR_R410AMIX()
    mycheck_c_ASHRAE_R410AMIX()
    print("\r\n")

    print("coolprop to refprop with REFPROP::R410A.MIX")
    mycheck_c2r_nothing()
    mycheck_c2r_DEF()
    mycheck_c2r_NBP()
    mycheck_c2r_IIR()
    mycheck_c2r_ashrae()
    print("\r\n")

    print(CP.__version__)
    print(sys.version)

```

```
C:\Users\Administrator\Desktop\coolprop_bug\venv\Scripts\python.exe C:\Users\Administrator\Desktop\coolprop_bug\main.py 
coolprop with R410A, this case maybe like R410A.PPF?
Coolprop R410A Without setREF 214997.8001388374
Coolprop R410A With setREF DEF 214997.8001388374
Coolprop R410A With setREF NBP 88528.34685427517
Coolprop R410A With setREF IIR 214997.6607900431
Coolprop R410A With setREF ASHRAE 72753.23508719912


coolprop with R410A.MIX
Coolprop R410A.MIX Without setREF 216223.55389878328
Coolprop R410A.MIX With setREF DEF 216223.55389878328
Coolprop R410A.MIX With setREF NBP 216223.55389878328
Coolprop R410A.MIX With setREF IIR 216223.55389878328
Coolprop R410A.MIX With setREF ASHRAE 216223.55389878328


coolprop to refprop with REFPROP::R410A.MIX
Coolprop REFPROP::R410A.MIX Without setREF 216223.20174696876
Coolprop REFPROP::R410A.MIX With DEF 216223.20174696876
Coolprop REFPROP::R410A.MIX With NBP 216223.20174696876
Coolprop REFPROP::R410A.MIX With IIR 216223.20174696876
Coolprop REFPROP::R410A.MIX With ASHRAE 216223.20174696876


6.6.0
3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
```

 It's really amazing that none of the calculations match the results from REFPROP, the results of which can be seen in the screenshot.

![REFPROP_calcresult](https://github.com/CoolProp/CoolProp/assets/8532202/3f06deb4-81f3-4370-b267-412a1d1a6b6d)

**Comment by birdol** [comment]
The reason why I didn't use R454B in this example is that when I call the function CP.CoolProp.set_reference_state('R454B.MIX', 'ASHRAE'), it throws an error.

```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\coolprop_bug\main.py", line 89, in <module>
    mycheck_c_ASHRAE_R410A()
  File "C:\Users\Administrator\Desktop\coolprop_bug\main.py", line 27, in mycheck_c_ASHRAE_R410A
    CP.CoolProp.set_reference_state('R454B.MIX', 'ASHRAE')
  File "CoolProp\\CoolProp.pyx", line 170, in CoolProp.CoolProp.set_reference_state
RuntimeError: key [R454B.MIX] was not found in string_to_index_map in JSONFluidLibrary

```

**Comment by ibell** [comment]
First make an instance of the low-level interface and _then_ call the function: http://www.coolprop.org/coolprop/LowLevelAPI.html#reference-states

**Comment by ibell** [comment]
There is a simple answer: don't worry about reference states. They are a
distraction for mixtures and frankly I don't really understand the best way
to handle them. You should always write your calculations such that the
reference state is irrelevant.
