### ISSUE TITLE
Incorrect Saturation Temperature Calculation

### ISSUE THREAD

**Issue by danielkwalsh** [CoolProp/CoolProp#2245]
### Description
When attempting to compute the saturation temperature of Ammonia over a reasonable pressure range (around 5 to 35 pounds per square inch), there are multiple temperatures that are computed incorrectly (a discrepancy of hundreds of degrees compared to the correct value in some cases)

### Steps to Reproduce

Run the following code to make a plot of the  Saturation Temperature (Kelvin) versus Pressure (Pascal) of Ammonia:

```
fig, ax = plt.subplots(1)
Prange = np.arange(46195,239180, 100)
ax.plot(Prange, [PropsSI('T','P', p,'Q',1,'Ammonia') for p in Prange])
```

**Expected behavior:**
We expect to see the plot of a smooth curve generated showing how the saturation temperature of ammonia depends on the pressure.

**Actual behavior:**
Much of the curve looks correct, but there are numerous areas where the answer returned is absurdly incorrect (as I mentioned, off by hundreds of degrees, even) that appear only below atmospheric pressure (as far as I can tell), and become progressively worse as the pressure is reduced.

### Versions

CoolProp Version: 6.4.3
Operating System and Version: MacOS Monterey (12.6)
Access Method: Python

### Additional Information

<img width="745" alt="image" src="https://user-images.githubusercontent.com/42506941/236072124-943c5234-8b4d-4fe3-8536-87de21cabc4a.png">

**Comment by ibell** [comment]
That's ugly :(. Can you try with the development version?  I recall I fixed
an issue with ancillary equations for ammonia.

**Comment by danielkwalsh** [comment]
@ibell Yes, thanks for getting back to this quickly. What's the best way for me to download and test the development version?

**Comment by ibell** [comment]
https://github.com/CoolProp/CoolProp/issues/2119

**Comment by ibell** [comment]
Drop the version and that will give you the most tippy development version

**Comment by ibell** [comment]
Yes, you want to get to 6.5.3 dev:
```
(py310) ianbell@Ians-MacBook-Air Code % pip install -i https://test.pypi.org/simple/ CoolProp
Looking in indexes: https://test.pypi.org/simple/
Collecting CoolProp
  Using cached https://test-files.pythonhosted.org/packages/43/eb/eb5cd9acb332c0b694ff89f1ce18c8d40126ada5d00091e9c8facd0ec1de/CoolProp-6.5.0.post1-cp310-cp310-macosx_11_0_arm64.whl (2.3 MB)
Installing collected packages: CoolProp
Successfully installed CoolProp-6.5.0.post1
```
but that doesn't solve the problem. Anyway, REFPROP does a lot better with this:
```
import matplotlib.pyplot as plt
import numpy as np
import CoolProp

CP = CoolProp.CoolProp
print(CoolProp.__version__)

import os
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, os.getenv('HOME')+'/REFPROP10')

fig, ax = plt.subplots(1)
Prange = np.arange(46195,239180, 100)
ax.plot(Prange, CP.PropsSI('T','P', Prange,'Q',1,'Ammonia'))

fig, ax = plt.subplots()
Trange = np.arange(225, 260, 1)
ax.plot(Trange, CP.PropsSI('P','T', Trange,'Q',1,'Ammonia'))
```

@msaitta-mpr want to dig into this?

**Comment by danielkwalsh** [comment]
@ibell what does the plot look like with REFPROP?

**Comment by msaitta-mpr** [comment]
@ibell I confirmed that the issue exists in the current master branch.

The issue seems to be that the Akasaka solver in `saturation_PHSU_pure` thinks that it has found a good solution, but the solution is not good. My guess is that we need to implement a check for `p_error` as is done in most of the other saturation solvers. I do not have time to test that today but will try to look into it later this week.

**Comment by ibell** [comment]
It's perfect in Refprop
