### ISSUE TITLE
Accessing Therminol VP-1  properties

### ISSUE THREAD

**Issue by allanc1** [CoolProp/CoolProp#2248]
I believe that Therminol VP-1 properties have been included in Coolprop.  Is this available within Excel (I have used the  Windows Installer or only from Python? Could you please give a simple example of getting the specific heat given the temperature?

Regards
Allan

**Comment by ibell** [comment]
It'll be something like this: http://www.coolprop.org/fluid_properties/Incompressibles.html#pure-fluid-examples

**Comment by allanc1** [comment]
Excellent, works in Excel - I missed the INCOMP: part.
Kind regards
Allan
