### ISSUE TITLE
Javascript Wrapper unavailble for version 6.4.3

### ISSUE THREAD

**Issue by dvd101x** [CoolProp/CoolProp#2259]
By following the instructions in [Javascript Wrapper](http://coolprop.org/coolprop/wrappers/Javascript/index.html#javascript) I see there is no file for the latest version [6.4.3](http://sourceforge.net/projects/coolprop/files/CoolProp/6.4.3/Javascript)

The latest I found is [6.4.1](http://sourceforge.net/projects/coolprop/files/CoolProp/6.4.1/Javascript)

I'm glad to have access to that version, just letting you know that there are no javascript files for the latest versions.

Also it would be nice to have access through a CDN (in a similar fashion to https://cdnjs.com/libraries/d3)

**Comment by ibell** [comment]
As I mentioned in #2258 it is hard to keep them up to date. Recommend you build your own.  At one point someone tried to get them added to a CDN, but they were rejected because we didn't have enough stars on github at the time.
