### ISSUE TITLE
Sharp non-differentiable changes in thermal conductivity of CO2 and other gases

### ISSUE THREAD

**Issue by Arnab-Mahanti** [CoolProp/CoolProp#2265]
Sudden sharp changes leading to non-differentiable behavior in certain ranges of temperature for thermal conductivity are seen for gases like CO2, Methane and possibly others (not verified).

## The following is a plot for thermal conductivity of `CO2` at a pressure of `8MPa`.
![image](https://github.com/CoolProp/CoolProp/assets/64639502/66be4283-1116-4225-beda-facc8c0c628f)

## Zooming at around 304K shows this behavior explicitly.
![image](https://github.com/CoolProp/CoolProp/assets/64639502/eebfcc9b-6bb3-4ea5-b249-426310e7773d)

## Comparision with the commercial RFPROP Library shows significant deviation of the properties as well as absence of such a behavior.
![image](https://github.com/CoolProp/CoolProp/assets/64639502/fc8e7b4a-e22e-455a-9a41-96050e734be6)

## Similar behavior is seen for `Methane` at `8MPa`
![image](https://github.com/CoolProp/CoolProp/assets/64639502/d3eab5fa-9de5-4635-ad11-472bce700c36)

###  The problem can be assumed to be related to the underlying interpolation schemes or with the transition from one way of  calculation of the properties to another due to its presence in different gases.

**Comment by ibell** [comment]
The thermal conductivity is divergent in the vicinity of the critical
point, hence the bump. This is a well known phenomenon.

The models for CO2 are slightly different in REFPROP (please specify which
version you are using) and CoolProp. That explains the differences.

**Comment by Arnab-Mahanti** [comment]
1.The pressure chosen (8Mpa) is above the critical point of CO2 and thus does not come near the critical point. For arguments' sake here are the plots for carbon dioxide at 9MPa and 10MPa showing a similar behavior.

### P=9MPa
![image](https://github.com/CoolProp/CoolProp/assets/64639502/c899930d-2a18-4de7-84e7-e28483820308)

### P=10MPa
![image](https://github.com/CoolProp/CoolProp/assets/64639502/c9ba5763-3059-4b6b-bc50-ebc9f7756895)


2. The data is taken from [NIST Thermophysical Properties](https://webbook.nist.gov/chemistry/fluid/). However, REFPROP shows a similar behavior (the sharp non-differentiability doesn't arise) and I am currently unable to show it due to its commercial licensing model. I am more interested in the non-differentiable behavior rather than the difference due to the nature of my work, which is related to stability. In the transcritical flows this causes convergence issues and hinders the prediction of stability characteristics.

**Comment by ibell** [comment]
See the comparison against REFPROP 10.0:
http://www.coolprop.org/fluid_properties/fluids/CarbonDioxide.html#refprop-validation-data
. The model in the webbook (from Huber et al.) is newer than that in
CoolProp, hence the differences.  The model in CoolProp is from Scalabrin
et al.:
http://www.coolprop.org/fluid_properties/fluids/CarbonDioxide.html#references
. This seems to be a deficiency in the model implemented in CoolProp from
Scalabrin. You might want to email the authors of that paper to let them
know.

Someone should implement the better TCX model from Huber et al. for CO2 in
CoolProp.

**Comment by Arnab-Mahanti** [comment]
I see. I will check it out. Meanwhile, here are some plots from the [MINIREF](https://[trc.nist.gov/refprop/MINIREF/MINIREF.HTM](https://trc.nist.gov/refprop/MINIREF/MINIREF.HTM)) tool.
![image](https://github.com/CoolProp/CoolProp/assets/64639502/a027289e-bb88-4dbc-8309-ce68b74125de)

@ibell As rightly pointed out a divergence behavior can be noticed near the critical point (~7MPa) but the non-differentiable sharp change does not arise for the other pressure values, which is I think what is expected.

**Comment by Arnab-Mahanti** [comment]
@ibell Can you please share the reference of the TCX model by Hubber et. al. for CO2?

**Comment by ibell** [comment]
https://pubs.aip.org/aip/jpr/article-abstract/45/1/013102/242053/Reference-Correlation-of-the-Thermal-Conductivity

**Comment by Arnab-Mahanti** [comment]
What may be the reason for this behavior in Methane ?

**Comment by ibell** [comment]
An old model that has a non-physical bump? I'm not really sure.

**Comment by Arnab-Mahanti** [comment]
@ibell To change the model, we need to change the coefficients for the residual and dilute contributions in the transport > conductivity section of the all_fluids.json file, and change the model of the critical contribution. Am I in the right direction?

**Comment by Arnab-Mahanti** [comment]
@ibell There exists a function `CoolPropDbl TransportRoutines::conductivity_dilute_hardcoded_CO2(HelmholtzEOSMixtureBackend&)`. Looking at the `CarbonDioxide.json` file shows that the dilute part of the thermal conductivity is set to none. Is it a relic from the implementation of a previous model?
