### ISSUE TITLE
Javascript Wrapper unable to compiled for version coolprop 6.5.0

### ISSUE THREAD

**Issue by xpretycn** [CoolProp/CoolProp#2278]
### Description

on windos,when i build the Javascript module with command like this As described on the official website :
cmake ../ -DCOOLPROP_JAVASCRIPT_MODULE=ON -DCMAKE_TOOLCHAIN_FILE=%EMSCRIPTEN%/cmake/Modules/Platform/Emscripten.cmake

I got an error : CMake Error at CMakeLists.txt:415 (message):Must be able to find shared_ptr

-- Configuring incomplete, errors occurred!

### Versions 

**CoolProp Version:** [6.5.0]  
**emcc Version:**[3.1.44]
**cmake Version:**[3.27.1]
**visual studio Version:**[community 2022]
**Operating System and Version:** [Windows 11]  
**Access Method:** [javascript wrapper]  

![图片](https://github.com/CoolProp/CoolProp/assets/20868765/31822800-1bfe-4ba8-9ad7-3e99829bb0c0)

**Comment by xpretycn** [comment]
![图片](https://github.com/CoolProp/CoolProp/assets/20868765/55c2c8e1-b57b-47b4-89d0-da4a011b46c5)

**Comment by xpretycn** [comment]
I really don't know where the problem lies

**Comment by ibell** [comment]
I don't follow. The javascript wrapper is to be compiled with the docker image.

**Comment by ibell** [comment]
See https://github.com/CoolProp/CoolProp/tree/master/wrappers/Javascript . You need to install docker, then run the docker_build.sh script in wrappers/Javascript

**Comment by ibell** [comment]
The docs have not yet been updated, but need to be.

**Comment by pkirkham** [comment]
I ran into a very similar issue when compiling the Java wrapper. I resolved it by adding a line to the `FindSharedPtr.cmake` file.

![image](https://github.com/CoolProp/CoolProp/assets/9302840/0825f7af-03bd-446e-b464-e296cf741b7b)

**Comment by jowr** [comment]
Hi, I have added the Javascript builder to the release pipeline. Could you please confirm that the new file works before I publish these changes:
https://www.jottacloud.com/s/160bb80e865ae0f402ea75571bc88d73b5c

**Comment by xpretycn** [comment]
> yes,it works on web environment

> Hi, I have added the Javascript builder to the release pipeline. Could you please confirm that the new file works before I publish these changes: https://www.jottacloud.com/s/160bb80e865ae0f402ea75571bc88d73b5c

**Comment by jowr** [comment]
Thanks - the next nightly build is going to contain javascript binaries 😄

**Comment by xpretycn** [comment]
> I ran into a very similar issue when compiling the Java wrapper. I resolved it by adding a line to the `FindSharedPtr.cmake` file.
> 
> ![image](https://user-images.githubusercontent.com/9302840/259605525-0825f7af-03bd-446e-b464-e296cf741b7b.png)
I tried it your way, but still failed for javascrit wrapper, i'll try  compile with the docker image .

**Comment by jowr** [comment]
I guess this is closed by #2279
