### ISSUE TITLE
Getting fugacity from the shared library

### ISSUE THREAD

**Issue by jyoungca** [CoolProp/CoolProp#2284]
### Description

We are trying to use CoolProp through the Julia interface, and there seems to be no way to get the fugacity from the shared library (http://www.coolprop.org/_static/doxygen/html/_cool_prop_lib_8h.html) since it is not included as keyed output or returned in a separate wrapped function. We are unsure of how to wrap the existing fugacity function in Julia without using PyCall.

### Steps to Reproduce

`CoolProp.AbstractState_keyed_output(handle, CoolProp.get_param_index("fugacity"))`

**Expected behavior:** fugacity (or fugacity vector) returned

**Actual behavior:** `CoolProp: Unknown parameter: fugacity`

or

`CoolProp.AbstractState_get_fugacity(handle, i)`

**Expected behavior:** fugacity of species i returned

**Actual behavior:** `ERROR: UndefVarError: AbstractState_get_fugacity not defined`

### Versions

**CoolProp Version:** 6.5.0  
**Operating System and Version:** Windows 10
**Access Method:** Julia wrapper

**Comment by longemen3000** [comment]
As far as I know, CoolProp.jl still uses CoolProp 6.4.3

**Comment by jyoungca** [comment]
I don't see a fugacity function in CoolPropLib for 6.4.3 or 6.5.0.

**Comment by ibell** [comment]
That is correct. It would need to be added, following the pattern for the
other functions. While there you might want to also add the fugacity
coefficient method.

**Comment by chris-hampel-CA** [comment]
We expect the required code in `CoolProp.cpp` to be something like this:

```
EXPORT_CODE double CONVENTION AbstractState_get_fugacity(const long handle, const std::size_t i, long* errcode, char* message_buffer, const long buffer_length) {
    *errcode = 0;
    try {
        shared_ptr<CoolProp::AbstractState>& AS = handle_manager.get(handle);
        return AS->fugacity(i);
    } catch (...) {
        HandleException(errcode, message_buffer, buffer_length);
    }
    return _HUGE;
}
```

and in `CoolPropLib.h` to be something like this: 

```
EXPORT_CODE double CONVENTION AbstractState_get_fugacity(const long handle, const std::size_t i, long* errcode, char* message_buffer, const long buffer_length);
```

Would appreciate any advice on the correctness of the code, as we're more familiar with Julia versus C++. Regardless, we can start a fork plus pull request and hopefully get this feature tested and released as soon as possible. Thanks.
