### ISSUE TITLE
Link CoolProp in C program language

### ISSUE THREAD

**Issue by zhoulei3A** [CoolProp/CoolProp#2293]
I am newbie coming to CoolProp, and I try to link CoolProp's static library or shared library in my own code which write in c program language.  But I don't know how to do it, could somebody give me some sample code or instructions? Thanks very much.

By the way, the code run in Linux platform.

**Comment by pkirkham** [comment]
I use the Java wrappers, so I'm no expert on calling it from C. However this looks like it might be what you are after:

[https://github.com/CoolProp/simple_sharedlibrary_example](https://github.com/CoolProp/simple_sharedlibrary_example)

**Comment by ibell** [comment]
Indeed. I had forgotten I put together this example :)
