### ISSUE TITLE
Viscosity and thermal conductivity lookups unavailable for Peng-Robinson and Redlich-Kwong EOS's

### ISSUE THREAD

**Issue by chris-hampel-CA** [CoolProp/CoolProp#2298]
### Prerequisites

This issue does not appear to be mentioned in Github issues nor any of the latest releases. However, it was mentioned in the User Group [here](https://groups.google.com/g/coolprop-users/c/AFlXCduMjP8/m/HyRypvlABAAJ).  The answer to the issue is that the transport lookups for using cubic EOS do not exist in CoolProp, currently. I am adding it here as an issue as this has not been worked on since the question appeared in the User Group 

### Description

I have found that using a cubic EOS, like Peng-Robinson (`"PR"`) or Redlich-Kwong (`"SRK"`), when solving iterative systems of equations, can see a large speed-up in model performance with still good accuracy, (compared to `"HEOS"`). However, my models require lookups for viscosity, `mu` and thermal conductivity, `k`. Both are unavailable when using these cubic EOS's. 

Can we work on a method to return these two transport properties for this instance? I have done some research online and there are a variety of techniques to examine before deciding which one to use. I am no properties expert, so I would have a difficult time making a recommendation and/or starting this work myself. Is there something that exists internal to CoolProp already that could be catered to this problem? 

### Steps to Reproduce

1. Create fluid model with species `N2` using the `"PR"` or `"SRK"` backend, assign T and p, call for viscosity, `mu` or thermal conductivity, `k`.
```
CP = pyimport("CoolProp.CoolProp")
model = CP.AbstractState("PR","N2")
model.update(CP.PT_INPUTS, 1e5, 300)
model.viscosity()
```

**Expected behavior:** return value of `mu` or `k`

**Actual behavior:** 
```
ValueError('Thermal conductivity model is not available for this fluid')
  File "CoolProp\AbstractState.pyx", line 324, in CoolProp.CoolProp.AbstractState.conductivity
```
The same is true for `mu`

### Versions

**CoolProp Version:** [6.4.1]  
**Operating System and Version:** Windows OS  
**Access Method:** using PyCall in Julia

### Additional Information

n/a

**Comment by ibell** [comment]
This is one good option: https://pubs.acs.org/doi/10.1021/acs.iecr.1c01386
.  Not as accurate as entropy scaling approaches based on PC-SAFT, but if
all you have is a cubic EOS...

**Comment by chris-hampel-CA** [comment]
Did this feature get added or is it being marked as non-applicable any more?

**Comment by ibell** [comment]
Not applicable - if someone wanted to tackle this they would be welcome
