### ISSUE TITLE
CoolProp cannot import name '_constants'

### ISSUE THREAD

**Issue by Odiur** [CoolProp/CoolProp#2299]
### Description

I installed CoolProp via: 
pip install CoolProp

**Actual behavior:** After calling the coolprop module I get the following ImportError:
```
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\kdunowski\.spyder-py3\cp.py:10
    from CoolProp import CoolProp as CP

  File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\CoolProp\__init__.py:5
    from . import constants

  File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\CoolProp\constants.py:5
    from . import _constants

ImportError: cannot import name '_constants' from partially initialized module 'CoolProp' (most likely due to a circular import) (C:\Users\KDunowski\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\CoolProp\__init__.py)
```
### Versions

**CoolProp Version:** [CoolProp 6.5.0]  
**Operating System and Version:** [Windows 10 ]  
**Access Method:** Spyder 5.4.5 ,Python 3.11.5]

**Comment by ibell** [comment]
Try doing the import outside of spyder, in a normal python environment.

**Comment by Odiur** [comment]
I use command line "cmd" for the import. What do you mean with "normal python environment"?

**Comment by ibell** [comment]
Test something like this:
```
C:\Users\ian>python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import CoolProp
```

**Comment by Odiur** [comment]
I have uninstalled existing coolprop using pip uninstall coolprop than according to your suggestion:
C:\Users\KD\>python
Ptyhon 3.11.5 (tags/v3.11.5:cce6ba9, aug24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32

>>>import CoolProp
Result:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'CoolpProp'

**Comment by ibell** [comment]
Try reinstalling coolprop with

python -m pip install coolprop

And try again

**Comment by Odiur** [comment]
After python -m pip install coolprop the info is :"Successfully installed coolprop-6.5.0.post1"

Import Error as result of running the code:
runfile('C:/Users/KDunowski/.spyder-py3/untitled0.py', wdir='C:/Users/KDunowski/.spyder-py3')
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\kdunowski\.spyder-py3\untitled0.py:7
    from CoolProp import CoolProp as CP

ImportError: cannot import name 'CoolProp' from 'CoolProp' (unknown location)

**Comment by ibell** [comment]
And now run python from that shell just like I did.  Spyder comes next.

**Comment by Odiur** [comment]
In the shell the code is running properly :)

**Comment by Odiur** [comment]
How to run code in the Spyder?
