### ISSUE TITLE
try to make a STATIC_LIBRARY for Visual Studio 17 2022

### ISSUE THREAD

**Issue by liuwei-kyushu** [CoolProp/CoolProp#2301]
Hi,

I want to use CoolProp in Visual Studio 17 2022.

Referecing to the instruction shown in http://www.coolprop.org/coolprop/wrappers/StaticLibrary/index.html#, 
I am trying to make a STATIC_LIBRARY for Visual Studio 17 2022. The steps are:
/--------------------------------------------------------
$ git clone https://github.com/CoolProp/CoolProp --recursive
$ cd CoolProp
$ mkdir build && cd build
$ cmake .. -DCOOLPROP_STATIC_LIBRARY=ON -G "Visual Studio 17 2022"
$ cmake --build
/--------------------------------------------------------

However, in the step   $ cmake .. -DCOOLPROP_STATIC_LIBRARY=ON -G "Visual Studio 17 2022", it showed following messages:
/--------------------------------------------------------
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2.7")
-- Looking for Python
-- Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
-- Looking for Python2
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter)
-- Looking for Python3
-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
CMake Warning at CMakeLists.txt:315 (message):
  Could not find Python, be prepared for errors.
/--------------------------------------------------------

Now my quesetions are
(1) If everthing goese well, I should find a new CoolProp.LIB file in the "build" folder, right?
Because i can't find the file now, I failed the STATIC_LIBRARY development, right?
(2)  Does the above error message affect my STATIC_LIBRARY development for Visual Studio 17 2022?

Best regards,

Wei

**Comment by ibell** [comment]
Yes,  python is a mandatory dependency.

**Comment by liuwei-kyushu** [comment]
Thank you for your quick answer. 
Do you know what should I do to fix the problem? 
Or only the developers for CoolProp can fix it?

**Comment by ibell** [comment]
You need to install python on your computer

**Comment by liuwei-kyushu** [comment]
Thank you for your advice.
I installed python on my computer and repeated the LIBRARY creating process.
Same error showed and  Nothing changed.

**Comment by ibell** [comment]
Please show the complete set of output to the shell

**Comment by liuwei-kyushu** [comment]
Thank you.
/-----------------------------------------------------------------------------
$ cmake .. -DCOOLPROP_STATIC_LIBRARY=ON -G "Visual Studio 17 2022"
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- COOLPROP_INSTALL_PREFIX=C:/Users/liuwe/CoolProp/install_root
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.37.32824.0
-- The CXX compiler identification is MSVC 19.37.32824.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CoolProp version: 6.5.1pre
CMake Warning (dev) at CMakeLists.txt:277 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:280 (set):
  implicitly converting 'LIST' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:295 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2.7")
-- Looking for Python
-- Found Python: C:/Users/liuwe/AppData/Local/Programs/Python/Python311/python.exe (found version "3.11.6") found components: Interpreter
-- Looking for Python2
-- Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter)
-- Looking for Python3
-- Found Python3: C:/Users/liuwe/AppData/Local/Programs/Python/Python311/python.exe (found version "3.11.6") found components: Interpreter
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Library compilation detected:
-- Creating CoolProp, a 64-bit library
-- CMAKE_SYSTEM_NAME: Windows
-- COOLPROP_STATIC_LIBRARY: ON
-- COOLPROP_SHARED_LIBRARY: OFF
-- COOLPROP_OBJECT_LIBRARY: OFF
-- CONVENTION:
-- COOLPROP_LIBRARY_HEADER: include/CoolPropLib.h
-- COOLPROP_LIBRARY_SOURCE: src/CoolPropLib.cpp
-- COMPILE_FLAGS:
-- LINK_FLAGS:
-- Configuring done (10.8s)
-- Generating done (0.1s)
-- Build files have been written to: C:/Users/liuwe/CoolProp/build

**Comment by ibell** [comment]
Ok, that seems ok, next step is:
```
cmake --build .
```
Don't miss the ``.``

**Comment by liuwei-kyushu** [comment]
Thank you very much. 
Of couse I did the cmake --build.  It showed as follows.
But where is the new LIBRARY which I can use in Visual Studio?
/-------------------------------
$ cmake --build
Usage: cmake --build <dir>             [options] [-- [native-options]]
       cmake --build --preset <preset> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --preset <preset>, --preset=<preset>
                 = Specify a build preset.
  --list-presets[=<type>]
                 = List available build presets.
  --parallel [<jobs>], -j [<jobs>]
                 = Build in parallel using the given number of jobs.
                   If <jobs> is omitted the native build tool's
                   default number is used.
                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
                   specifies a default parallel level when this option
                   is not given.
  -t <tgt>..., --target <tgt>...
                 = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --resolve-package-references={on|only|off}
                 = Restore/resolve package references during build.
  -v, --verbose  = Enable verbose output - if supported - including
                   the build commands to be executed.
  --             = Pass remaining options to the native tool.

**Comment by ibell** [comment]
Yes, that is right because you did your build in Debug mode. You should see
this example for how to properly integrate CoolProp into your code:
https://github.com/CoolProp/simple_cmake_example
