### ISSUE TITLE
Release archives are missing the submodules

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#2305]
As noted in https://github.com/pyodide/pyodide/pull/4028, the release ``.zip`` and ``.tar.gz`` available here (https://github.com/CoolProp/CoolProp/releases/tag/v6.5.0) do not include the submodules. The folders are present, but not populated.

**Comment by jowr** [comment]
The packages are generated automatically when we make a release. Submodules are not populated - one should use SourceForge to get a file with readily populated submodules.

**Comment by jowr** [comment]
This is just how it is on GitHub - there is nothing we can do about it
