### ISSUE TITLE
Feature Request: Implementation of the novel Refrigerant R1336mzz(e) into HEOS Backend

### ISSUE THREAD

**Issue by chrishauptmannAtEsiGroup** [CoolProp/CoolProp#2307]
Dear CoolProp team,

Please consider adding R1336mzz(e) to the HEOS-Backend. 

Do you think it's possible for me to do the implementation with the sources provided below?

- https://www.nist.gov/publications/helmholtz-energy-equation-state-trans-111444-hexafluoro-2-butene-r-1336mzze

- https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=935812

**Comment by longemen3000** [comment]
the suplementary information on the first link has a json file that has all the necessary information to add that fluid to CoolProp. if you are using CoolProp along a programing language, you can load that json directly: http://www.coolprop.org/coolprop/HighLevelAPI.html#adding-fluids

**Comment by ibell** [comment]
@longemen3000 is right. I just didn't add it to CoolProp, but PR adding would be welcomed. Make sure to update the reference in the BibTeX library

**Comment by chrishauptmannAtEsiGroup** [comment]
Thank you for your recommendations, it helped a lot. =) 

I implemented R1336mzze succesfully to my local CoolProp. 
But for my use case i also need additional equations e.g. for viscosity and conductivity, the warnings of CoolProp say's this is not implemented. 

Is it correct that the R1336mzze.json file of Akasaka-IJT-2023 has not this equations, or is it my fault in implementation? 

Furthermore i implemented the R1336mzze.FLD File to Refprop v10.0. This worked really well for my application, so currently i have no need to implement it in HEOS. If there would be a sufficient solution for the viscosity and conductivity, i would do it. 

Thank you so much for your support. =)

**Comment by ibell** [comment]
Well, an EOS has nothing to do with the transport properties (viscosity and
thermal conductivity), at its core.

The FLD file has an ECS model that you could translate to CoolProp format,
or you could implement one the entropy scaling models that work quite well
for refrigerants. For instance this one:
https://pubs.acs.org/doi/abs/10.1021/acs.jced.0c01009

**Comment by jowr** [comment]
I think this has been fixed in #2309 - but the transport properties are still missing though.
