### ISSUE TITLE
HEOS::R1336MZZE does not work properly

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#2325]
@jfreissmann and @ibell - did you check the JSON file you added for R12336mzz(E)? 

It seems that the consistency plots fail with a division by zero due to either pressure or density being zero, see https://github.com/CoolProp/CoolProp/actions/runs/7031174954/job/19132234200

```shell
fluid: R1336MZZE
Writing to /__w/CoolProp/CoolProp/Web/fluid_properties/fluids/Consistencyplots/R1336MZZE.py
calling: python "R1336MZZE.py" in /__w/CoolProp/CoolProp/Web/fluid_properties/fluids/Consistencyplots
***********************************************************************************
*************** HEOS::R1336MZZE ************************
***********************************************************************************
1-phase took 0.020544052124023438 s for PT
1-phase took 0.014697074890136719 s for DmolarT
Traceback (most recent call last):
  File "/__w/CoolProp/CoolProp/Web/fluid_properties/fluids/Consistencyplots/R1336MZZE.py", line 8, in <module>
    ff = ConsistencyFigure('R1336MZZE')
  File "/opt/conda/envs/docs/lib/python3.10/site-packages/CoolProp/Plots/ConsistencyPlots.py", line 122, in __init__
    ax.consistency_check_twophase()
  File "/opt/conda/envs/docs/lib/python3.10/site-packages/CoolProp/Plots/ConsistencyPlots.py", line 462, in consistency_check_twophase
    if abs(self.state_QT.rhomolar() / self.state.rhomolar() - 1) < 1e-3 and abs(self.state_QT.p() / self.state.p() - 1) < 1e-3 and abs(self.state_QT.T() - self.state.T()) < 1e-3:
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/__w/CoolProp/CoolProp/Web/scripts/fluid_properties.Consistency.py", line 36, in <module>
    subprocess.check_call('python -u "' + fluid + '.py"', cwd=plots_path, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/opt/conda/envs/docs/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -u "R1336MZZE.py"' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/__w/CoolProp/CoolProp/Web/scripts/__init__.py", line 98, in <module>
    run_script(os.path.normpath(fname))
  File "/__w/CoolProp/CoolProp/Web/scripts/__init__.py", line 59, in run_script
    subprocess.check_call('python -u {0}'.format(file_name), cwd=file_path, shell=True)
  File "/opt/conda/envs/docs/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -u fluid_properties.Consistency.py' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

**Comment by jowr** [comment]
For reference, this is related to #2309

**Comment by jowr** [comment]
There seems to be some work left:
![R1336MZZE](https://github.com/CoolProp/CoolProp/assets/769593/2b864cb7-2321-46c0-b678-40cc5da1b78d)

**Comment by jowr** [comment]
Please continue the development for R1336mzz(E) in this branch https://github.com/CoolProp/CoolProp/tree/feature/R1336MZZE

I am going to remove it from the planned release of v6.6.0.

I guess this is also relevant for #2307

**Comment by ibell** [comment]
> There seems to be some work left: ![R1336MZZE](https://private-user-images.githubusercontent.com/769593/286594646-2b864cb7-2321-46c0-b678-40cc5da1b78d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyOTE5MzEsIm5iZiI6MTcwMTI5MTYzMSwicGF0aCI6Ii83Njk1OTMvMjg2NTk0NjQ2LTJiODY0Y2I3LTIzMjEtNDZjMC1iNjc4LTQwY2M1ZGExYjc4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQyMTAwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWI0NjY1NzFkNTFiYWFhMWU4MTRkNjk2YjkzMjlmNTkxMmU4Njc2MDM4ZTZkOGI2ZTM3OTQ0ZWMzYjBjMTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X44ATyM-PqeX-uOzK01yDlHauCIFnLTdZI7Q-XWAgUA)

I don't see what you are complaining about :) 

I guess I should have run that test before I pushed. Maybe the ancillary are messed up? Sorry for the rushed commit, I will debug ASAP and
