### ISSUE TITLE
how to use low-level interface code in Incompressible Fluids?

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#2335]
when i use low-level interface code in refrigerant
```c#
 AbstractState cpa;
 cpa = AbstractState.factory("HEOS", para.CoolPropName);// //R32&R1234yf
 para.MoleFractions = para.MoleFractions.Replace("[", "").Replace("]", "");//
 string[] stringArray = para.MoleFractions.Split(',');
 double[] doubleArray = Array.ConvertAll<string, double>(stringArray, delegate (string s) { return double.Parse(s); });
 DoubleVector molefractions = new DoubleVector(doubleArray);
 cpa.set_mole_fractions(molefractions); 
-----balabalaba...
```
How do I handle this with Incompressible Fluids ?  for example   INCOMP::AEG[0.5] ?
can you show me the python or c# demo code?

**Comment by ibell** [comment]
How about: http://www.coolprop.org/fluid_properties/Incompressibles.html#pure-fluid-examples ?

**Comment by birdol** [comment]
there is only the pure fluid , i want the mix fluid....

and I need low-level interface, not the PropsSI function。

**Comment by ibell** [comment]
Start here: http://www.coolprop.org/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface

Replace "HEOS" with "INCOMP" in instantiation

Then call set_mass_fractions after initialization

**Comment by birdol** [comment]
set_mass_fractions  ?  IF mixtrue is vol-base， which one ？ cpa.set_volu_fractions？

**Comment by ibell** [comment]
Yes, that is right
