### ISSUE TITLE
Strange question....R515B

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#2337]
I want to call refprop backend with coolprop, with code：
```c#
cpa = AbstractState.factory("HEOS", "R1234ZEE&R227EA");
```
then it's show me the error msg 1
```
Error msg 1：
Could not match the binary pair [29118-24-9,431-89-0] - for now this is an error
```
And then I found this sadly issue:
https://github.com/CoolProp/CoolProp/issues/1594#issuecomment-344959427

So I am goto change it like
```c#
cpa = AbstractState.factory("HEOS", "R515B");
```
then it's show me the error msg 2
```
Error msg 2：
System.ApplicationException:“key [R515B] was not found in string_to_index_map in JSONFluidLibrary”
```
I knew that the second method would never work, but I need coolprop to calc fluid status (liquid/vap/....)

If I use refprop, I can only calculate the quality, but I can't determine the state....
```c#
cpa = AbstractState.factory("REFPROP", "R454B.MIX");
```

Is there anything I can do to help?
1、fix the “binary pair ” issue？
2、add R515B key to JSONFluidLibrary ，when compiling coolprop ？

**Comment by ibell** [comment]
I don't entirely follow the question - there are multiple backends and multiple mixtures you mention in various places. Can you please clarify?

**Comment by birdol** [comment]
its solved。sorry for my description。
