### ISSUE TITLE
The docs are broken since md-January

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#2349]
I think this commit broke the docs: https://github.com/CoolProp/CoolProp/commit/443a2fd276112a88ab42c3e74ce2aeb1c7b40764

See run 673 of the documentation builder for details, maybe @msaitta-mpr could have a look?

**Comment by ibell** [comment]
My first guess is that it is not related to that PR, but I am not sure where that error is coming from.

**Comment by msaitta-mpr** [comment]
Looks like the issue in in the TTSE tables. I didn't touch them in https://github.com/CoolProp/CoolProp/commit/443a2fd276112a88ab42c3e74ce2aeb1c7b40764 (#2250). 

```
 ValueError: Cell is invalid and has no good neighbors for x = 46916.8, y= 400000
Traceback (most recent call last):
  File "/__w/CoolProp/CoolProp/Web/scripts/__init__.py", line 98, in <module>
    run_script(os.path.normpath(fname))
  File "/__w/CoolProp/CoolProp/Web/scripts/__init__.py", line 59, in run_script
    subprocess.check_call('python -u {0}'.format(file_name), cwd=file_path, shell=True)
  File "/opt/conda/envs/docs/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python -u coolprop.tabular.speed.py' returned non-zero exit status 1.
```

This looks strangely similar to some errors that I have been getting while investigating for #2318. I will try to find some more time this week to dive back into that and hopefully figure out what is going on with the doc builds at the same time.

**Comment by msaitta-mpr** [comment]
OK, this was an interesting one. You were right that https://github.com/CoolProp/CoolProp/commit/443a2fd276112a88ab42c3e74ce2aeb1c7b40764 broke it. There was in issue with the secondary check on convergence missing one of the possible acceptable states. 

I have created a PR that should address this.
