### ISSUE TITLE
PropSi returns erroneous values for NH3 in Excel

### ISSUE THREAD

**Issue by bwiencke** [CoolProp/CoolProp#2356]
At certain pressures (below 79000 Pa) erroneous temperature values are returned or no values are returned.  This issue is not present when using RefProp.
CoolProp Version: 6.6.0 and 6.6.1
Operating system: Microsoft® Excel® 2021 MSO (Version 2401 Build 16.0.17231.20236) 64-bit 

For example:
1) =PropsSI("T","P",57565.979,"Q",1,"AMMONIA")
Expected value:  229.15 K
Returned value: 337.45 K

2) =PropsSI("T","P",30086.278,"Q",1,"AMMONIA")
Expected value:  218.15 K
Returned value: Inputs in Brent [219.766178,223.766178] do not bracket the root.  Function values are [180.302048,624.573688] : PropsSI("T","P",30086.27794,"Q",1,"AMMONIA")
<img width="1175" alt="Screenshot 2024-02-24 103632" src="https://github.com/CoolProp/CoolProp/assets/77804098/784fb748-9fdc-43e8-8cd2-fcb9b29a1c72">

**Comment by ibell** [comment]
There was a problem with the saturated vapor density ancillary function in 6.6.0. It was fixed in https://github.com/CoolProp/CoolProp/commit/443a2fd276112a88ab42c3e74ce2aeb1c7b40764 . Building from source should fix this problem.

**Comment by ibell** [comment]
I had to make another fix to the ancillary (sigh...) but it should be working now. The consistency plots look much better after this fix:

[Ammonia.pdf](https://github.com/CoolProp/CoolProp/files/14396805/Ammonia.pdf)
