### ISSUE TITLE
Thermal conductivity for parahydrogen can't be calculated for temperatures ranging between 30 and 50 K

### ISSUE THREAD

**Issue by vins1996** [CoolProp/CoolProp#2371]
Hello there, I am trying to calculate thermal condictivity for parahydrogen between 30 and 50 K and unfortunately CoolProp fails the calculation exclusively in that range. I read that it could be about the JSON fluid definition. So I am asking what part of the JSON file I need ot change to allow the calculation to succeed. 
Thanks for helping in case.

**Comment by ibell** [comment]
The viscosity correlation (needed in the critical enhancement term) had not been implemented for parahydrogen. The correlation for normal hydrogen is also valid for parahydrogen so I copied it over. That should fix the problem.

**Comment by vins1996** [comment]
Dear Ian, thank you for the answer. 
By the way I'm not sure I understood how to fix the problem. I compared the two JSON files for both hydrogen and parahydrogen and nothing changes between them except for the empirical parameters' values. So, for example, how should I do in order to calculate the thermal conductivity @50 bars and 40K?

**Comment by ibell** [comment]
You need to recompile CoolProp from source, making sure your source revision is after https://github.com/CoolProp/CoolProp/commit/f6eb03742f9430f8dbf9e5a950b2d914b9edc0d1

**Comment by vins1996** [comment]
Dear Ian, after a long time trying out to recompile from source (which I hadn't done before) I at last was capable to do that. I am so grateful you answered to me and fixed the problem.
Thanks a lot.

**Comment by ibell** [comment]
Glad to hear you got it sorted!
