### ISSUE TITLE
How to plot P-h and T-s plot for cascaded refrigeration system  in python using coolprop.

### ISSUE THREAD

**Issue by Rishu2425** [CoolProp/CoolProp#2381]
I want to plot P-h and T-s graph in python using CoolProp for an cascaded refrigeration system, but I am unable to plot saturation liquid and saturation vapour line for other refrigerant.
![1](https://github.com/CoolProp/CoolProp/assets/171242581/0b7ba7cd-279e-4947-bb74-b5cd657f93dd)
![2](https://github.com/CoolProp/CoolProp/assets/171242581/490de8fe-fd60-4412-9a58-6b3e52152fd7)

Python code for plotting graph is given below. 
#Ph plot 
#plot = PropertyPlot('R744' and 'R717', 'PH', unit_system='EUR', tp_limits='ACHP')
plot = PropertyPlot('R744', 'PH', unit_system='EUR', tp_limits='ACHP')

#plot.draw_isolines('Q', [0.3, 0.5, 0.7, 0.8])
plot.calc_isolines(CoolProp.iQ, num = 11)
plot.calc_isolines(CoolProp.iT,[0, 150], num=20)
#plot.calc_isolines(CoolProp.iSmass, num=15)
"Axis limits"
plot.set_axis_limits([0,2000,2,300])

# Add optimized point to the plot
plot.axis.plot(h_1/1000, P_1/100000, 'bo', label='1')
plot.axis.plot(h_2/1000, P_2/100000, 'ro', label='2')
plot.axis.plot(h_3/1000, P_3/100000, 'go', label='3')
plot.axis.plot(h_4/1000, P_4/100000, 'ko', label='4')
"-----------------------CO2-----------------------------"
plot.axis.plot(h_5/1000, P_5/100000, 'ro', label='5')
plot.axis.plot(h_6/1000, P_6/100000, 'ro', label='6')
plot.axis.plot(h_7/1000, P_7/100000, 'ro', label='7')
plot.axis.plot(h_8/1000, P_8/100000, 'ro', label='8')
plot.axis.plot(h_9/1000, P_9/100000, 'ro', label='9')
plot.axis.plot(h_10/1000, P_10/100000, 'ro', label='10')
plot.axis.plot(h_11/1000, P_11/100000, 'ro', label='11')
plot.axis.plot(h_12/1000, P_12/100000, 'ro', label='12')
plot.axis.plot(h_13/1000, P_13/100000, 'ro', label='13')
plot.axis.plot(h_14/1000, P_14/100000, 'ro', label='14')

# Connect the points to form a cycle
#evaporator
plot.axis.plot([h_4/1000, h_1/1000], [P_1/100000, P_1/100000], 'b-', label='Evaporation', linewidth=2)
# compressor isentropic
plot.axis.plot([h_1/1000, h_2_is/1000], [P_1/100000, P_2/100000], color='orange',  label='Compression', linewidth=2)
#Compressor
plot.axis.plot([h_1/1000, h_2/1000], [P_1/100000, P_2/100000], 'k--',  label='Compression', linewidth=2)
#Gas cooler
plot.axis.plot([h_2/1000, h_3/1000], [P_2/100000, P_3/100000], 'r-',  label='Heat rejection', linewidth=2)
#Throttling
plot.axis.plot([h_3/1000, h_4/1000], [P_3/100000, P_1/100000], 'g--',  label='Expansion', linewidth=2)
"----------------------------------------"
plot.axis.plot([h_5/1000, h_6/1000], [P_5/100000, P_6/100000], 'b-', label='C2', linewidth=2)
plot.axis.plot([h_6/1000, h_7/1000], [P_6/100000, P_7/100000], 'b-', label='C2', linewidth=2)
plot.axis.plot([h_7/1000, h_8/1000], [P_7/100000, P_8/100000], 'b-', label='Condenser', linewidth=2)
plot.axis.plot([h_8/1000, h_9/1000], [P_8/100000, P_9/100000], 'b-', label='C2', linewidth=2)
plot.axis.plot([h_9/1000, h_11/1000], [P_9/100000, P_11/100000], 'b-', label='EV2', linewidth=2)
plot.axis.plot([h_9/1000, h_10/1000], [P_9/100000, P_10/100000], 'b-', label='C2', linewidth=2)
plot.axis.plot([h_10/1000, h_12/1000], [P_10/100000, P_12/100000], 'b-', label='EV3', linewidth=2)
plot.axis.plot([h_12/1000, h_13/1000], [P_12/100000, P_13/100000], 'b-', label='LT', linewidth=2)
plot.axis.plot([h_13/1000, h_14/1000], [P_13/100000, P_14/100000], 'b-', label='C3', linewidth=2)
plot.axis.plot([h_14/1000, h_7/1000], [P_14/100000, P_7/100000], 'b-', label='C2', linewidth=2)
plot.axis.plot([h_11/1000, h_5/1000], [P_11/100000, P_5/100000], 'b-', label='C2', linewidth=2)

# Annotate state points
for (x, y, label) in [(h_1/1000, P_1/100000, '1'), 
                        (h_2/1000, P_2/100000, '2'), 
                        (h_3/1000, P_3/100000, '3'), 
                        (h_4/1000, P_4/100000, '4'),
                        (h_5/1000, P_5/100000, '5'),
                        (h_6/1000, P_6/100000, '6'),
                        (h_7/1000, P_7/100000, '7'),
                        (h_8/1000, P_8/100000, '8'),
                        (h_9/1000, P_9/100000, '9'),
                        (h_10/1000, P_10/100000, '10'),
                        (h_11/1000, P_11/100000, '11'),
                        (h_12/1000, P_12/100000, '12'),
                        (h_13/1000, P_13/100000, '13'),
                        (h_14/1000, P_14/100000, '14'),
                        ]:
    plot.axis.annotate(label, (x, y), textcoords="offset points", xytext=(5,5), ha='center')
# Show the plot
plot.grid()
plot.show()

**Comment by spinnau** [comment]
By default the `PropertyPlots` class creates a new matplotlib axes instance for each plot. But it's also possible to plot into an already existing subplot using the `axis` keyword argument when creating the `PropertyPlot`, e.g.

```python
import matplotlib.pyplot as plt
import CoolProp
from CoolProp.Plots import PropertyPlot

fig, ax1 = plt.subplots(1)

ph1 = PropertyPlot('R744', 'PH', axis=ax1)
ph1.calc_isolines(CoolProp.iQ)

ph2 = PropertyPlot('R717', 'PH', axis=ax1)
ph2.calc_isolines(CoolProp.iQ)

ph1.show()
ph2.show()

ax1.set_xlim(0, 1800)
```
