### ISSUE TITLE
Cannot access Coolprop site

### ISSUE THREAD

**Issue by augustinphilips** [CoolProp/CoolProp#2386]
Dear Coolprop Team, When I try to access the site "http://ibell.pythonanywhere.com" 

A message shows up like this, Can you please check. Thank you.
 
![1](https://github.com/CoolProp/CoolProp/assets/172358976/6b224f5c-6069-4baa-890b-7f2531ec8dc0)
![2](https://github.com/CoolProp/CoolProp/assets/172358976/8adc11db-95a0-46bd-9953-51c97a7e1a80)

**Comment by ibell** [comment]
Sessions were full. I flushed them you should be good again

**Comment by fbarbuto** [comment]
Chrome prevented me from accessing Coolprop site. It says it's an insecure site. MS Edge says it's OK.

**Your connection is not private
Attackers might be trying to steal your information from www.coolprop.org (for example, passwords, messages or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID**

**Comment by ibell** [comment]
The correct location for this post is #2350
