### ISSUE TITLE
Critical point of a mixture

### ISSUE THREAD

**Issue by fbarbuto** [CoolProp/CoolProp#2392]
Good day,

In a phase envelope similar to one of the curves shown in:

http://www.coolprop.org/fluid_properties/Mixtures.html#phase-envelope

and for a mixture containing 80% methane and 20% ethane, how would I pinpoint exactly (that is, within a couple of decimal 
places) the point where the dew and bubble point curves meet?

I don't necessarily have to have the phase envelope determined or plotted; any other method (simpler or more straightforward) 
to determine this point would do.

Thanks.

Fausto

**Comment by ibell** [comment]
This example shows two ways of doing such a calculation. In the first, the critical point routines from this paper are used: https://doi.org/10.1016/j.fluid.2016.10.030 .  Note that ``all_critical_points`` can yield more than one critical point, not all of which may be stable.

In the second the more explicit method is used where crossing of the densities are looked for, and then a critical point single iterative calculation is launched.


```python
import CoolProp.CoolProp as CP
import matplotlib.pyplot as plt
import scipy.optimize
import numpy as np

HEOS = CP.AbstractState('HEOS', 'Methane&Ethane')

for x0 in [0.02, 0.2, 0.4, 0.6, 0.8, 0.98]:
    HEOS.set_mole_fractions([x0, 1 - x0])
    try:
        HEOS.build_phase_envelope("dummy")
        PE = HEOS.get_phase_envelope_data()
        PELabel = 'Methane, x = ' + str(x0)
        line, = plt.plot(PE.T, PE.p, '-', label=PELabel)

        # The rigorous method of tracing the spinodal, looking
        # for points that satisfy the critical conditions
        for pt in HEOS.all_critical_points():
            plt.plot(pt.T, pt.p, '*', color=line.get_color())
            break

        # The simplified method of looking for density crossing
        # and then doing a 2D solve for the temperature and density
        
        def residcrit(x):
            T, rho = x
            HEOS.specify_phase(CP.iphase_gas)
            HEOS.update(CP.DmolarT_INPUTS, rho, T)
            HEOS.unspecify_phase()
            return HEOS.criticality_contour_values() 
        
        # This is a bit too simplistic because you should also check that the 
        # compositions are the same of the two phases
        density_diff = (np.array(PE.rhomolar_vap)-np.array(PE.rhomolar_liq))
        for i in range(len(density_diff)-1):
            if density_diff[i]*density_diff[i+1] < 0:
                xinit = [PE.T[i], PE.rhomolar_vap[i]]
                x = scipy.optimize.fsolve(residcrit, xinit)
                # The iterative calculations will have been setting 
                # the state inside the AbstractState so you can 
                # just call the accessor
                plt.plot(HEOS.T(), HEOS.p(), 'o', color=line.get_color(), mfc='none')

    except ValueError as VE:
        print(VE)

plt.xlabel('Temperature [K]')
plt.ylabel('Pressure [Pa]')
plt.yscale('log')
plt.title('Phase Envelope for Methane/Ethane Mixtures')
plt.legend(loc='lower right', shadow=True)
plt.savefig('methane-ethane.pdf')
plt.savefig('methane-ethane.png')
plt.close()

```

**Comment by fbarbuto** [comment]
Very nice, thanks! The code works beautifully.

Another tool I have access to (Multiflash 7.2) says that the critical point for a mixture composed of 60% CH4 and 40% C2H6 is something like Tc = 253.2 K, pc = 7008261.4 Pa . CoolProp calculated Tc =  251.7 K, pc =  6906057.4 Pa. Pretty good.

Thanks again for your  help.

Fausto

**Comment by ibell** [comment]
I'm guessing any differences with multiflash are down to the thermo model

**Comment by fbarbuto** [comment]
Indeed. In the case above, I specifically picked the results from PR78A. 

There are several models available (regrettably, GERG2008 is not one of them).

Fausto
