### ISSUE TITLE
REFPROP no loading/not found

### ISSUE THREAD

**Issue by fbarbuto** [CoolProp/CoolProp#2393]
Hi all,

I do have **REFPROP.dll** and **REFPRP64.dll** in **C:\Program Files\Python\Lib\site-packages\CoolProp\wrappers**, which is in 
the PATH. Yet I'm unable to call REFPROP through the high-level interface.

I tried to temporarily add this location with:

`import sys`
`sys.path.append('C:\Program Files\Python\Lib\site-packages\CoolProp\wrappers')`

and also

`import json, CoolProp.CoolProp as CP`
`CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, \`
`'C:\\Program Files\\Python\\Lib\\site-packages\\CoolProp\\wrappers')`

None of these worked. I wonder what's going on.

The files have the following properties in the dir: 

**06/04/2013  07:00         1,740,288 refprop.dll
06/04/2013  07:00         2,531,328 REFPRP64.DLL**

They look old - 11 full years since they were built. Are those DLLs supposed to still work?

Any hints?

Thanks.

Fausto

**Comment by henningjp** [comment]
You must have NIST REFPROP (preferably the latest version) installed on your system.  It's not free.  You can get it here: https://www.nist.gov/srd/refprop.

Once installed, the correct versions of the DLL will be located at `C:\Program Files (x86)\REFPROP`.   CoolProp will find the correct DLLs there.

**Comment by fbarbuto** [comment]
Thanks, I thought that the DLL only would suffice.

**Comment by henningjp** [comment]
It depends on where the DLLs you have came from and if you have the FLUIDS and MIXTURES directories that go with them.  They quite old.  REFPROP is not usually located in the Python site packages directly; it is a stand-alone program.

Can we close this issue?

**Comment by fbarbuto** [comment]
> It depends on where the DLLs you have came from and if you have the FLUIDS and MIXTURES directories that go with them. They quite old. REFPROP is not usually located in the Python site packages directly; it is a stand-alone program.
> 
> Can we close this issue?

Yes, no problem.
