### ISSUE TITLE
 temperature input to temperature-quality flash is greater than critical temperature; T = 813.50 K, Tcrit = 647.10 K.

### ISSUE THREAD

**Issue by coward122** [CoolProp/CoolProp#2397]
![12](https://github.com/user-attachments/assets/9d0d280c-8bdf-4a58-b5c6-8be39d695c00)
how to solve？

**Comment by ibell** [comment]
CoolProp has nothing to do with refpropm. Also the refpropm interface is
deprecated and you should use the python one instead
