### ISSUE TITLE
CoolProp - REFPROP computational overhead with different fluids in different Abstract States

### ISSUE THREAD

**Issue by GiuSirianni** [CoolProp/CoolProp#2410]
### Description

I am using CoolProp as a wrapper for REFPROP for a project and I have encountered a behavior that I am not sure is related to CoolProp, or the way REFPROP is installed.

I have installed REFPROP 10.0 on an Ubuntu machine using the following guide (https://github.com/usnistgov/REFPROP-cmake). 

If I create different Abstract States with different fluids, every time I call ```update()``` for the first time it is roughly 1000 times slower than a DT call with specified phase. I imagine it is an unspecified overhead from loading the fluid to memory. Every call after that is as fast as it should be but if I then switch back the Abstract State, the 1000x slow down re-appears and then goes away for subsequent calls, rinse and repeat.

### Steps to Reproduce

Minimum working example in python, but my code is in C++. The issue is the same:
```python
import time
import CoolProp
from CoolProp.CoolProp import get_global_param_string


def main(fluid_name1, fluid_name2):
    n_iter = 1000

    # create EoS
    AS1 = CoolProp.AbstractState("REFPROP", fluid_name1)
    AS1.build_phase_envelope("")
    AS2 = CoolProp.AbstractState("REFPROP", fluid_name2)
    AS2.build_phase_envelope("")

    # state 1 for fluid 1 (if fluid the same, state still different)
    p1 = AS1.p_critical() / 0.4
    T1 = AS1.T_critical() / 0.97
    AS1.update(CoolProp.PT_INPUTS, p1, T1)
    rho1 = AS1.rhomass()

    # state 2 for fluid 2 (if fluid the same, state still different)
    p2 = AS2.p_critical() / 0.5
    T2 = AS2.T_critical() / 0.98
    AS2.update(CoolProp.PT_INPUTS, p2, T2)
    rho2 = AS2.rhomass()

    # measure time
    t0_refprop = time.time()

    for i in range(n_iter):
        AS1.specify_phase(CoolProp.iphase_gas)
        AS1.update(CoolProp.DmassT_INPUTS, rho1, T1)

        AS2.specify_phase(CoolProp.iphase_gas)
        AS2.update(CoolProp.DmassT_INPUTS, rho2, T2)

    return (time.time() - t0_refprop) / n_iter


print("CoolProp version : ", get_global_param_string("version"))
print("REFPROP version  : ", get_global_param_string("REFPROP_version"))
print(
    "Refprop (MM,   MM)      : " + str(1e9 * main("MM", "MM")) + " [ns] per iteration"
)
print(
    "Refprop (MD4M, MM)      : " + str(1e9 * main("MD4M", "MM")) + " [ns] per iteration"
)
print(
    "Refprop (CO2,  N2)      : "
    + str(1e9 * main("CO2", "NITROGEN"))
    + " [ns] per iteration"
)
print(
    "Refprop (MM,   R134a)   : "
    + str(1e9 * main("MM", "R134a"))
    + " [ns] per iteration"
)
print(
    "Refprop (CO2,  CO2)     : " + str(1e9 * main("CO2", "CO2")) + " [ns] per iteration"
)
```

Output:

```shell
CoolProp version :  6.6.0
REFPROP version  :  10.0
Refprop (MM,   MM)      : 1852.273941040039 [ns] per iteration
Refprop (MD4M, MM)      : 1637926.5785217285 [ns] per iteration
Refprop (CO2,  N2)      : 1917508.602142334 [ns] per iteration
Refprop (MM,   R134a)   : 1642870.6645965576 [ns] per iteration
Refprop (CO2,  CO2)     : 2823.352813720703 [ns] per iteration
```

**Expected behavior:** 

I expect to have no overhead, except maybe the first call (even then I would expect the overhead only in the constructor).

**Actual behavior:** 

Every time I switch Abstract State, if the fluid is different, there is an unspecified overhead with a slowdown that is roughly 1000x the speed of a DT call with specified phase.

### Versions

**CoolProp Version:** 6.6.0
**REFPROP Version:** 10.0
**Operating System and Version:** Ubuntu 22.04
**Access Method:** Python wrapper, C++ statically linked

**Comment by ibell** [comment]
Yes, because REFPROP is not thread-safe. You are essentially forcing a re-setup within REFPROP each time you do a calculation with a model. It is better to a) use this library I made: https://github.com/usnistgov/REFPROP-manager or b) use HEOS backend, which is thread-safe and no re-initialization.

I think it would be possible to implement the REFPROP-manager goodies in CoolProp to make interfacing with REFPROP easier, but it would take quite some work from an experienced developer.

**Comment by GiuSirianni** [comment]
I am already using the HEOS backend for everything and its working great.  I only have one "issue": some fluids appear to be using a completely different EOS than REFPROP (MD4M for example) and I need to compare results I get using REFPROP's mixture capabilities to a fluid simulation I run using the HEOS backend.  I though I could get around it by just using REFPROP through CoolProp, but this is where I encountered the above issue.

Is there any way to use the REFPROP fluid file with the HEOS backend? I am not enough of an expert on these parametric equations of state, nor was I able to find documentation.

Implementing the REFPROP-manager ability to instantiate more than one REFPROP instance in CoolProp would be super, but I am afraid it is not a high priority feature.

Thank you!

**Comment by ibell** [comment]
@GiuSirianni Yes, in some cases the EOS are not the same. It will depend on the respective versions of REFPROP and CoolProp. 

I wrote some scripts (Python & C++) for conversion of REFPROP fluid file format to that of CoolProp: https://github.com/ianhbell/REFPROP-interop. I also integrated that library into teqp: https://teqp.readthedocs.io/en/latest/models/REFPROP_conversion.html
