### ISSUE TITLE
(Helium) PropsSI failed ungracefully 

### ISSUE THREAD

**Issue by Aristos998** [CoolProp/CoolProp#2424]
When I try to calculate tables about Helium in order to insert into Simscape, Matlab returns this error

Steps to Reproduce

1. HeTables = twoPhaseFluidTables([-5.99,500],[0.2275,3],25,25,60,'HELIUM','py.CoolProp.CoolProp.PropsSI')

Expected behavior
To calculate a struct with fields (like the picture with the N2Tables)

Actual behavior
Error about PropsSI failed 

### Versions

**CoolProp Version:** 6.6.0
**Operating System and Version:** Windows 10  
**Access Method:** I am using Matlab wrapper with python 

### Additional Information

![Screenshot 2024-10-11 142828](https://github.com/user-attachments/assets/48f7492c-fd3e-41af-9b2b-30be499a8686)
![Screenshot 2024-10-11 142856](https://github.com/user-attachments/assets/4df20f37-d0e4-4c6b-be90-6ea026819fa3)

**Comment by ibell** [comment]
Does density work at that statepoint? Can you reproduce that failure outside the table generator?

**Comment by Aristos998** [comment]
No I cannot

**Comment by ibell** [comment]
You'll have to take it up with Mathworks then if it cannot be reproduced outside of the table generator
