### ISSUE TITLE
HmassT_INPUTS not yet supported error when running CoolProp 6.6.0

### ISSUE THREAD

**Issue by matlawicebox** [CoolProp/CoolProp#2428]
### Description

I'm trying to determine fluid properties based on enthalpy and temperature inputs, but I get an error.  (For the actual fluid I'm interested in, It's in a region where the answer may not be unique - but I was hoping to use specify_phase to pin it, but right now it seems to say it can't even use h and t as inputs for water)

With these lines of code:

`import CoolProp.CoolProp as CP`
`state = CP.AbstractState("HEOS", "Water")`
`h = 3000 # kJ/kg`
`T = 300 # K`
`state.update(CP.HmassT_INPUTS, h, T)`
`p = state.p() # Pressure in Pa`
`print("Pressure:", p, "Pa")`

I'm expecting to get the pressure but what I get is this:

`Traceback (most recent call last):`
  `File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()`
  `File "<input>", line 5, in <module>`
  `File "CoolProp/AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update`
  `File "CoolProp/AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update`
`ValueError: This pair of inputs [HmassT_INPUTS] is not yet supported`

### Versions

**CoolProp Version:** 6.6.0
**Operating System and Version:** MacOS 14.6.1
**Access Method:** Python

### Additional Information

I double-checked my CoolProp version with this terminal call:

`python -c 'help("CoolProp")'`

which gives the output below.  I think it's saying that HmassT_INPUTS should be supported (under Data section there's this line: HmassT_INPUTS = 13)?:

Help on package CoolProp:

NAME
    CoolProp

PACKAGE CONTENTS
    BibtexParser
    CoolProp
    GUI (package)
    HumidAirProp
    Plots (package)
    State
    _constants
    constants
    tests (package)

FUNCTIONS
    copy_BibTeX_library(file=None, folder=None)
        Copy the CoolProp BibTeX library file to the file given by 'file', or the folder given by 'folder'
        
        If no inputs are provided, the file will be copied to the current working
        directory
        
        Parameters
        ----------
        file : string
            Provide if you want to put the file into a given file
        folder : string
            Provide if you want to put the CoolPropBibTeXLibrary.bib file into the given folder
    
    get(s)
        This is just a shorthand function for getting a parameter from
        "CoolProp.get_global_param_string"
    
    get_include_directory()
        Get the include directory for CoolProp header files that are needed if you want
        to compile anything else that uses the CoolProp Cython extension type
        
        Returns
        -------
        include_directory: The path to the include folder for CoolProp
    
    test()
        Run the tests in the test folder

DATA
    ALTERNATIVE_REFPROP_HMX_BNC_PATH = 6
    ALTERNATIVE_REFPROP_LIBRARY_PATH = 7
    ALTERNATIVE_REFPROP_PATH = 5
    ALTERNATIVE_TABLES_DIRECTORY = 4
    ASSUME_CRITICAL_POINT_STABLE = 24
    CRITICAL_SPLINES_ENABLED = 2
    CRITICAL_WITHIN_1UK = 1
    DONT_CHECK_PROPERTY_LIMITS = 14
    DmassHmass_INPUTS = 30
    DmassP_INPUTS = 18
    DmassQ_INPUTS = 8
    DmassSmass_INPUTS = 32
    DmassT_INPUTS = 10
    DmassUmass_INPUTS = 34
    DmolarHmolar_INPUTS = 31
    DmolarP_INPUTS = 19
    DmolarQ_INPUTS = 7
    DmolarSmolar_INPUTS = 33
    DmolarT_INPUTS = 11
    DmolarUmolar_INPUTS = 35
    FLOAT_PUNCTUATION = 26
    FLUID_TYPE_INCOMPRESSIBLE_LIQUID = 3
    FLUID_TYPE_INCOMPRESSIBLE_SOLUTION = 4
    FLUID_TYPE_PSEUDOPURE = 1
    FLUID_TYPE_PURE = 0
    FLUID_TYPE_REFPROP = 2
    FLUID_TYPE_UNDEFINED = 5
    HENRYS_LAW_TO_GENERATE_VLE_GUESSES = 15
    HmassP_INPUTS = 20
    HmassQ_INPUTS = 6
    HmassSmass_INPUTS = 26
    HmassT_INPUTS = 13
    HmolarP_INPUTS = 21
    HmolarQ_INPUTS = 5
    HmolarSmolar_INPUTS = 27
    HmolarT_INPUTS = 12
    INPUT_PAIR_INVALID = 0
    INVALID_PARAMETER = 0
    LIST_STRING_DELIMITER = 27
    MAXIMUM_TABLE_DIRECTORY_SIZE_IN_GB = 13
    NORMALIZE_GAS_CONSTANTS = 0
    OVERWRITE_BINARY_INTERACTION = 22
    OVERWRITE_DEPARTURE_FUNCTION = 21
    OVERWRITE_FLUIDS = 20
    PHASE_ENVELOPE_STARTING_PRESSURE_PA = 16
    PQ_INPUTS = 2
    PSmass_INPUTS = 22
    PSmolar_INPUTS = 23
    PT_INPUTS = 9
    PUmass_INPUTS = 24
    PUmolar_INPUTS = 25
    QSmass_INPUTS = 4
    QSmolar_INPUTS = 3
    QT_INPUTS = 1
    REFPROP_DONT_ESTIMATE_INTERACTION_PARAMETERS = 8
    REFPROP_ERROR_THRESHOLD = 11
    REFPROP_IGNORE_ERROR_ESTIMATED_INTERACTION_PARAMETERS = 9
    REFPROP_USE_GERG = 10
    REFPROP_USE_PENGROBINSON = 12
    R_U_CODATA = 17
    SAVE_RAW_TABLES = 3
    SPINODAL_MINIMUM_DELTA = 19
    SmassT_INPUTS = 15
    SmassUmass_INPUTS = 28
    SmolarT_INPUTS = 14
    SmolarUmolar_INPUTS = 29
    TUmass_INPUTS = 17
    TUmolar_INPUTS = 16
    USE_GUESSES_IN_PROPSSI = 23
    VTPR_ALWAYS_RELOAD_LIBRARY = 25
    VTPR_UNIFAC_PATH = 18
    __fluids__ = ['D4', 'HydrogenSulfide', 'o-Xylene', 'R125', 'IsoButane'...
    __gitrevision__ = 'ba21c74fd1c3a4934bbecbf459936983dec424c2'
    __incompressibles_pure__ = ['HC20', 'PNF2', 'HY40', 'PMR', 'AS30', 'Fo...
    __incompressibles_solution__ = ['MAM2', 'IceNA', 'MGL2', 'MEG', 'ZAC',...
    absolute_import = _Feature((2, 5, 0, 'alpha', 1), (3, 0, 0, 'alpha', 0...
    iBvirial = 62
    iCp0mass = 40
    iCp0molar = 28
    iCpmass = 39
    iCpmolar = 27
    iCvirial = 63
    iCvmass = 41
    iCvmolar = 29
    iDelta = 23
    iDmass = 36
    iDmolar = 24
    iFH = 74
    iGWP100 = 72
    iGWP20 = 71
    iGWP500 = 73
    iGmass = 43
    iGmolar = 31
    iGmolar_residual = 35
    iHH = 75
    iHelmholtzmass = 44
    iHelmholtzmolar = 32
    iHmass = 37
    iHmolar = 25
    iHmolar_residual = 33
    iODP = 77
    iP = 20
    iPH = 76
    iPIP = 67
    iP_critical = 10
    iP_max = 16
    iP_min = 17
    iP_reducing = 11
    iP_triple = 13
    iPhase = 78
    iPrandtl = 48
    iQ = 21
    iSmass = 38
    iSmolar = 26
    iSmolar_residual = 34
    iT = 19
    iT_critical = 7
    iT_freeze = 70
    iT_max = 15
    iT_min = 14
    iT_reducing = 6
    iT_triple = 12
    iTau = 22
    iUmass = 42
    iUmolar = 30
    iZ = 66
    iacentric_factor = 3
    ialpha0 = 57
    ialphar = 54
    iconductivity = 46
    id2alpha0_ddelta2_consttau = 60
    id3alpha0_ddelta3_consttau = 61
    idBvirial_dT = 64
    idCvirial_dT = 65
    idalpha0_ddelta_consttau = 59
    idalpha0_dtau_constdelta = 58
    idalphar_ddelta_consttau = 56
    idalphar_dtau_constdelta = 55
    idipole_moment = 18
    ifraction_max = 69
    ifraction_min = 68
    ifundamental_derivative_of_gas_dynamics = 53
    igas_constant = 1
    iisentropic_expansion_coefficient = 52
    iisobaric_expansion_coefficient = 51
    iisothermal_compressibility = 50
    imolar_mass = 2
    iphase_critical_point = 4
    iphase_gas = 5
    iphase_liquid = 0
    iphase_not_imposed = 8
    iphase_supercritical = 1
    iphase_supercritical_gas = 2
    iphase_supercritical_liquid = 3
    iphase_twophase = 6
    iphase_unknown = 7
    irhomass_critical = 9
    irhomass_reducing = 8
    irhomolar_critical = 5
    irhomolar_reducing = 4
    ispeed_sound = 49
    isurface_tension = 47
    iundefined_parameter = 79
    iviscosity = 45

VERSION
    6.6.0

FILE
    /opt/miniconda3/envs/CondaHP/lib/python3.8/site-packages/CoolProp/__init__.py

**Comment by ibell** [comment]
Right - HT inputs are tricky because there are possibly two solutions and making sure you are getting the right one is hard to do reliably. Can you use PT inputs? If not, can you please explain your use case?
