### ISSUE TITLE
can not find parameter to calculate Components within each phase of a gas-liquid two-phase mixture

### ISSUE THREAD

**Issue by yplakaka** [CoolProp/CoolProp#2429]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

[can not find parameter to calculate Components within each phase of a gas-liquid two-phase mixture]

### Steps to Reproduce

1. [I am trying to calculate two phase mixture Component fraction ,I checked the parameter in http://www.coolprop.org/coolprop/HighLevelAPI.html, suitable parameter found,  but in refpropm function in matlab this function can achieved              [x y] = refpropm('X','P',5e2,'Q',0.4,'R134a','R32',[0.8, 0.2])
                  %      Temperature as well as gas and liquid compositions for a mixture of two refrigerants at a certain pressure and quality.]
3. [Second Step]
4. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**CoolProp Version:** [6.6]  
**Operating System and Version:** [windows]  
**Access Method:** [matlab)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
I guess you mean the mole fractions accessors in the low-level interface. For instance: http://coolprop.org/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface

**Comment by yplakaka** [comment]
Thank you! That is exactly what I want.😀
