### ISSUE TITLE
Mixed work fluid component content cannot be expressed via variable

### ISSUE THREAD

**Issue by yplakaka** [CoolProp/CoolProp#2431]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

[Hello, when I calculate mixture work fluid properties, I found a problem, mixed work fluid component content cannot be expressed via variable]

### Steps to Reproduce

1. [
    T_2=373.15;
    p_2=1993600;
    H_2=py.CoolProp.CoolProp.PropsSI('Hmolar','T',T_2,'P',p_2,'REFPROP::R134a[0.4]&R245fa[0.6]')]
this will get a result back, but when I tried to use variables to replace the mixed work fluid component, there is an error.
3. [a=0.4;
    b=0.6;
    T_2=373.15;
    p_2=1993600;
    H_2=py.CoolProp.CoolProp.PropsSI('Hmolar','T',T_2,'P',p_2,'REFPROP::R134a[a]&R245fa[b]')]
Python  ValueError: fraction [a] was not converted fully : PropsSI("Hmolar","T",373.15,"P",1993600,"REFPROP::R134a[a]&R245fa[b]")
In the model I built, the mixture component always change, so it is necessary to replace number by variable .

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**CoolProp Version:** [6.6]  
**Operating System and Version:** [windows]  
**Access Method:** [matlab]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ibell** [comment]
You can use f strings, like this: ``f'REFPROP::R134a[{a}]&R245fa[{b}]')``. But this is a very(!) bad solution for speed because REFPROP will constantly get reloaded and the fluids initialized at each call which is expensive. You should us ethe low-level interface and pass the composition to set_mole_fractions(). See http://coolprop.org/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface

**Comment by yplakaka** [comment]
Thank you for your answer, it helps me a lot!
