### ISSUE TITLE
python numpy 2 

### ISSUE THREAD

**Issue by gitsdfawfevi** [CoolProp/CoolProp#2437]
### Description

the python wrapper "CoolProp" is only incompletely compatible with numpy > 2. specifically, I noticed this with the np.nan in CoolProp/Plots/Common.py ("Alias np.NaN has been removed. Use np.nan instead.", https://numpy.org/doc/stable/release/2.0.0-notes.html)

### Versions

**CoolProp Version:** 6.6.0
**Operating System and Version:** Archlinux 
**Access Method:** Python

**Comment by ibell** [comment]
Do you want to take on fixing that? It would be appreciated by the
community.

**Comment by gitsdfawfevi** [comment]
Yes, I will help and create a pull request specifically for the np.NaN. I'll have to see for myself how I can possibly provide more support.

**Comment by jowr** [comment]
I guess this was closed in #2439
