### ISSUE TITLE
CoolProps Ammonia & Water Mixtures

### ISSUE THREAD

**Issue by myksb** [CoolProp/CoolProp#2441]
Having a problem with calculate enthalpy of the mixture with this code

`
from numpy import *
from matplotlib.pyplot import *
import CoolProp.CoolProp as CP

#find properties at a_1

T_a1 = 326.97
P_a1 = 5335360
x_NH3_a1 = 0.4101
x_H2O_a1 = 1 - x_NH3_a1

H_Solution =CP.PropsSI('D','T',300,'P',101325,'REFPROP::Ammonia[0.697615]&Water[0.302385]') / 1000

print(f"Enthalpy of Soltion: {H_Solution} kJ/kg")
`

showing error "Initialize failed for backend: "REFPROP", fluid: "Ammonia&Water" fractions "[ 0.6976150000, 0.3023850000 ]"; error: fluid directories "FLUIDS" or "fluids" could not be found in the directory [/opt/refprop] : PropsSI("D","T",300,"P",101325,"REFPROP::Ammonia[0.697615]&Water[0.302385]")"

**Comment by myksb** [comment]
I already config the REFPROPS path, But still cannot use.
for more information, I only have REFPROPS64.dll

![image](https://github.com/user-attachments/assets/b63698a7-5a0c-4229-9203-58314674155f)
![image](https://github.com/user-attachments/assets/979ac016-a998-464c-ae8d-cc5872a4b7c1)

**Comment by wandadars** [comment]
From looking at your picture, it is complaining that you are using `REFPROPS` and not `REFPROP` in line 5 of your code.

**Comment by ibell** [comment]
Yes, I think it is a typo only. REFPROP is singular

**Comment by jowr** [comment]
... and the path should be the folder without the file name.
