### ISSUE TITLE
Some fluids have different (lower) max temps than REFPROP

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#257]
fluid, Tmax, Tmax from REFPROP

ARGON 700.0 2000.0
CO2 1100.0 2000.0
DME 550.0 525.0
IBUTENE 525.0 550.0
IHEXANE 500.0 550.0
METHANOL 580.0 620.0
MLINOLEA 700.0 1000.0
MLINOLEN 700.0 1000.0
MOLEATE 700.0 1000.0
MPALMITA 700.0 1000.0
MSTEARAT 700.0 1000.0
MM 580.0 673.0
BUTANE 340.0 575.0
C12 800.0 700.0
HEPTANE 310.0 600.0
HEXANE 548.0 600.0
OCTANE 548.0 600.0
PENTANE 573.0 600.0
NEON 723.0 700.0
NITROGEN 1100.0 2000.0
OXYGEN 300.0 2000.0
R11 595.0 625.0
R123 523.0 600.0
R143A 450.0 650.0
R152A 471.0 500.0
R23 425.0 475.0
R404A 450.0 500.0
R407C 450.0 500.0
R410A 450.0 500.0
R507A 450.0 500.0
SF6 650.0 625.0
WATER 1273.0 2000.0

**Comment by bilderbuchi** [comment]
it [seems](https://github.com/CoolProp/CoolProp/blob/a117eedbb0119dd88ff7900a60c8c1fbfbd2f8e0/dev/fluids/Oxygen.json#L268) oxygen still has a Tmax of 300K, are data for higher temps available?

**Comment by ibell** [comment]
Seems like an oversight.  Want to file a pull request?  Any others in this family of error still?

**Comment by bilderbuchi** [comment]
sorry, wouldn't know where to begin (with the oxygen data and code, PR filing would be no problem). I was just researching for oxygen data, and stumbled across this. :-(

**Comment by ibell** [comment]
I'm trying to build up a new generation of CoolProp developers, and this
would be a very simple way for you to get involved.  If you filed a PR to
update the max temp for Oxygen, that would be great.  Obviously I could do
it in a few seconds, but I'd rather help you to do it.

On Tue, May 3, 2016 at 10:55 AM, Christoph Buchner <notifications@github.com

**Comment by bilderbuchi** [comment]
so what, it's not about verifying results, finding relations valid in the respective regime, etc.? only update the value? Yeah I could do that. Mind you, I don't have access to a working instance of coolprop, and neither to refprop, so I can't really test the changes.

**Comment by ibell** [comment]
Yup, all that needs to be done is to update the value in the JSON file.  It
was just an oversight.  I'm pretty sure I can be sure that you will get it
right.  Besides, our testing will catch any issues.  File the PR and you'll
get the credit.

**Comment by bilderbuchi** [comment]
Sure, here, have a PR: #1053.
