### ISSUE TITLE
Requirement for zipped source code file

### ISSUE THREAD

**Issue by ChenYuChih** [CoolProp/CoolProp#293]
Hi Mr. Ian Bell,

Currently the code of version 5 in sourceforge is only some wrappers for different programming languages, no source code. Would you please upload source code zip files for releases in the future? Thank you very much!

Sincerely,
ChenYuChih (David Chen)

**Comment by ChenYuChih** [comment]
Oops.... The source code of v5.0.5 is forgotten ..... Please attached it. Thanks!

**Comment by jowr** [comment]
I'll fix that as soon as possible. I have no idea why this is not there, it should be an automated part of the release procedure. @ChenYuChih, you seem to be very interested in the source code, that is nice. Maybe you could consider using a git client and generate the header files yourself. It might make things easier for you compared to manually downloading a zip archive.

**Comment by jowr** [comment]
Fixed: https://sourceforge.net/projects/coolprop/files/CoolProp/5.0.5/source/
