### ISSUE TITLE
draw_process disappeared and problems in draw_isolines

### ISSUE THREAD

**Issue by pdewallef** [CoolProp/CoolProp#351]
It seems that the function draw_process disappeared from CoolProp release 5. In CoolProp 4 it used to be a part of PropsPlot but it is no longer present. Moreover, I noticed some issues in using draw_isolines in T-s property plot. Isobaric curves are flat.`

I supply below my code and the resulting chart.

    from CoolProp.CoolProp import PropsSI
    from CoolProp.Plots import PropsPlot
    import matplotlib.pylab as pl
    from numpy import *
    %matplotlib inline

    eta_e_s = 0.88
    eta_p_s = 0.5
    T_max = 550 + 273.15
    p_max = 13000.e3 
    p_cd = 5.e3

    def SimpleRankineCycle(T3, p3, p1, epsilon_e, epsilon_p, fluid='water'):
       h1 = PropsSI('H', 'P', p1, 'Q', 0., fluid)
       s1 = PropsSI('S', 'P', p1, 'Q', 0., fluid)
       T1 = PropsSI('T', 'P', p1, 'Q', 0., fluid)

       p2 = p3
       h2 = h1 + (PropsSI('H', 'P', p2, 'S', s1, fluid) - h1) / epsilon_p
       s2 = PropsSI('S', 'H', h2, 'P', p2, fluid)
       T2 = PropsSI('T', 'H', h2, 'P', p2, fluid)

       h3 = PropsSI('H', 'P', p3, 'T', T3, fluid)
       s3 = PropsSI('S', 'H', h3, 'P', p3, fluid)

       p4 = p1
       h4 = h3 - epsilon_e * (h3 - PropsSI('H', 'P', p4, 'S', s3, fluid))
       s4 = PropsSI('S', 'H', h4, 'P', p4, fluid)
       T4 = PropsSI('T', 'H', h4, 'P', p4, fluid)

       w_net = h3 - h4
       q_boiler = h3 - h2
       eta_c = w_net / q_boiler

       Ts = PropsPlot(fluid, 'Ts')
       Ts.draw_isolines('P', [p1, p3], num=10)
       Ts.set_axis_limits([0., 12., 200., 900.])

      ax = Ts.axis
      ax.text(s1/1000, T1,' 1', fontsize=10, rotation=0, color='r')
      ax.text(s2/1000, T2,' 2', fontsize=10, rotation=0, color='r')
      ax.text(s3/1000, T3,' 3', fontsize=10, rotation=0, color='r')
      ax.text(s4/1000, T4,' 4', fontsize=10, rotation=0, color='r')
      ax.text(8., 850., "Efficiency: %.1f%%" %(eta_c*100.))
      ax.text(8., 800., "Net work: %d kJ/kg" %(w_net/1000))
      ax.text(8., 750., "Heat input: %d kJ/kg" %(q_boiler/1000))
      return Ts

    Ts = SimpleRankineCycle(T_max, p_max, p_cd, eta_e_s, eta_p_s, fluid="water")

![chart](https://cloud.githubusercontent.com/assets/10206458/5451550/6e58504e-8511-11e4-91a5-2c065c4c3292.png)

**Comment by ibell** [comment]
Yeah, it seems the isoline plotting is quite seriously messed up unfortunately.

**Comment by ibell** [comment]
Sorry I don't have the chance to deal with this right now, I'm going to push it back until 5.0.6

**Comment by ibell** [comment]
@pdewallef @jjfPCSI1 can either of you dig into this one a bit more?  I'm severely time constrained right now, and don't use the plotting routines myself.

**Comment by jjfPCSI1** [comment]
Sorry, I will not have time to get back to CoolProp before at least a
month, even if I try to follow the discussions.

2015-01-07 23:39 GMT+01:00 Ian Bell <notifications@github.com>:

> @pdewallef <https://github.com/pdewallef> @jjfPCSI1
> <https://github.com/jjfPCSI1> can either of you dig into this one a bit
> more? I'm severely time constrained right now, and don't use the plotting
> routines myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoolProp/CoolProp/issues/351#issuecomment-69105618>.
>



-- 
JJ Fleck
Physique et Informatique
PCSI1 Lycée Kléber

**Comment by jowr** [comment]
I think I managed to rewrite most of the plotting code to make use of the AbstractState class. I would really like to clean up the API. Could you guys, especially @mayersre and @ibell, help me to make a list of function that your would like to keep? Please have a look at https://github.com/CoolProp/CoolProp/tree/draw_process .
The included example now produces the following graph and you can switch seemlessly between different unit systems.
![untitled](https://cloud.githubusercontent.com/assets/769593/8419999/a8b6c990-1ebe-11e5-8f72-e607b08f0af7.jpg)

**Comment by ibell** [comment]
Woot!  The plotting routines have desperately needed some love for quite
some time.  Feel free to start with a clean slate, changing as you feel
necessary.  For me, I don't heavily use the plotting routines, and they are
currently pretty much useless, so as they say, the ball is in your court.

**Comment by jowr** [comment]
There is still some way to go, but https://github.com/CoolProp/CoolProp/blob/draw_process/dev/Tickets/351.py now produces the first reasonable results. `draw_propcess` still needs some work though.
![untitled](https://cloud.githubusercontent.com/assets/769593/8425248/3d32a856-1f04-11e5-9342-3b7a85d6cb71.jpg)

**Comment by mayersre** [comment]
I do not use any Coolprop plot functions in my code.
So feel free to go as you think is right.

If I may voice one wish :
Please separate code for plotting lines and labels from code for formatting and sizing the canvas so a preformated axes/figure can be used for plotting

Looking forward to add it to the CP GUI :)

**Comment by jowr** [comment]
OK, I only saw these imports (https://github.com/CoolProp/GUI/blob/master/cpgui_diagram.py#L19-L21)  and thought you also used the classes (https://github.com/CoolProp/GUI/blob/master/cpgui_diagram.py#L145). 

Regarding your wish: That has been done already. You can pass a preformatted figure and axis object to the new PropertyPlot class. The other functions will then obey the axis limits and the formatting. See also: https://github.com/CoolProp/CoolProp/blob/draw_process/wrappers/Python/CoolProp/Plots/Common.py#L551-L574 to see how to override the default formatting options and how to pass the objects to the plot classes.

**Comment by mayersre** [comment]
I completely forgot about that part in the GUI ... actually I stopped writing this code when I discovered that it always changed my axis limits and settings (see PH Diagram). I will adapt it to the new version and add it to the cycle calculation when you tell me it is ready. I use static pictures there at the moment.

**Comment by jowr** [comment]
OK, good to know. Thanks for the prompt response!

**Comment by ibell** [comment]
See also #651 - not a bad idea

**Comment by spinnau** [comment]
@jowr good to see someone working on this. I have also thought about a rewrite of the `draw_process` function and the plotting code, but the biggest issue was to find a nice and easy to use solution for handling of the states similar to the deprecated `State` class. I think your [solution](https://github.com/CoolProp/CoolProp/blob/draw_process/dev/Tickets/351.py) may be good approach for this.

Are the inline labels for isolines working? I think for isolines `matplotlib.contour.ContourSet` could be used as shown below. This already includes code for labeling and would reduce the codebase to maintain in CoolProp.

```python
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.contour import ContourSet
from CoolProp import CoolProp

fluid = 'water'

state = CoolProp.AbstractState('HEOS', fluid)
state.build_phase_envelope('')
phase_envelope = state.get_phase_envelope_data()

fig = plt.figure()
ax = fig.add_subplot(111)

# plot phase envelope
s = np.array(phase_envelope.smolar_vap) / state.molar_mass()
T = phase_envelope.T        
ax.plot(s, T, color='k', lw=1.5)

# plot isolines as contours
Tt = CoolProp.PropsSI(fluid, 'Ttriple')
Tc = CoolProp.PropsSI(fluid, 'Tcrit')
T = np.linspace(Tt, Tc*1.2, 100)

lines = []
label_pos = []
label = {}   

p = [1e5, 10e5, 30e5, 90e5, 22e6, 35e6, 60e6]

# contour lines
for p_i in p:
    s = CoolProp.PropsSI('S', 'T', T, 'P', p_i, fluid)
    # filter inf-values to avoid problems with clabel positioning
    ind = np.where(s < np.inf)
    lines.append(np.dstack((s[ind], T[ind])))

# contour labels
for i, l in enumerate(lines):
    ind = np.where(l[0] <= 0.9*max(T))[0]
    label_pos.append(l[0][ind[-1]])    
    label[p[i]] = '{0:1.1f} MPa'.format(p[i]/1e6)

cs = ContourSet(ax, p, lines, colors='blue', linewidths=0.5)
ax.clabel(cs, fmt=label, manual=label_pos, fontsize=9)

fig.show()
```

![isolines](https://cloud.githubusercontent.com/assets/2995937/8482185/3de565dc-20e8-11e5-876d-73e962807555.jpg)

**Comment by jowr** [comment]
Thanks for the input. I’ll have a closer look in the weekend, but it looks like a convenient way to label isolines.

**Comment by mayersre** [comment]
I avoid using turned Labels wherever possible. So Please add a flag that allows to switch them off.
The DIN for drawing says to place labels horizontally or vertically. I dislike labels in the middle of the diagram ... try to plot a Rankine power plant cycle in the Water TS Chart above  ... you will collide
with the labels. In fact I use inlinelabel only on some Mollier hx chart for the relative humidity lines.

See this example for labeling : 
http://www.informations-gmbh.de/jpgs/Fotos/R-407C-phdia.png (high resolution)

Strategies I use for labeling:
- label outside the diagram whenever possible
- put units and other info into the legend and use $SYMBOL=value
- colour lines, text in legend, grid line and labels always in the same colour
- use thick and thin lines in regular distance and label only the thick ones
- make other lines a label by choosing a good start point
  ( see isochoric lines in example, start every 5 K on dew line)

In the implementation I use matplotlib transforms : 
        # define :
        self.transDA = transforms.blended_transform_factory(self.ax.transData, self.ax.transAxes)
        self.transAD = transforms.blended_transform_factory(self.ax.transAxes, self.ax.transData)
        # use : 
        # isothermal label outside box, enthalpy of last upper dot in the line
        # and Axes coordinate for the top placement 
        label=self.ax.text(  enthalpy,  1.013,labeltext,transform=self.transDA ...)

**Comment by jowr** [comment]
That is exactly the discussion I was hoping for. Thank you all for the inputs. I also really appreciate that all of you contributed code snippet instead of simply static wishes. 

I conclude that we need some sort of a switch to control the labelling. I personally really like the inline labels, but that is of course a personal preference and if the standard wants it differently, that is just one more reason to make the code more flexible.

**Comment by jowr** [comment]
@mayersre : Very nice diagram! It looks like you already found a smart way to plot major and minor lines, also the temperature related isochores look interesting. Just one question: Why do you need the blended_transform_factory? Wouldn't `label=self.ax.text( h_x_axis, 1.013, labeltext, transform=self.ax.transAxes)` do the job equally well?

**Comment by jowr** [comment]
Ah, got it. Your enthalpy has not been transformed before and comes as data.

**Comment by mayersre** [comment]
I use data coordinates in the diagrams, so enthalpy in kJ/kg would be something around 100 and pressure is in bar so here between .5 and ~50 while the axes coordinates will be from 0 to 1 thus - 0.013 or 1.013 are on the same distance each outside my diagram. The second value 1.013 without transform would be at 1.013 bar down in the diagram.

**Comment by mayersre** [comment]
yes

**Comment by mayersre** [comment]
thus I never scale the coordinates of the label ... and the axes labels are easy to format

**Comment by ibell** [comment]
For what its worth, my vote is for labels aligned with the line they
label.  It is much more satisfying visually (to me at least).  I would like
that to be the default behavior if possible.

I know (from painful first-hand experience) how painful these plotting
issues are, and I thank you all for contributing to the discussions on this
very important topic.

**Comment by mayersre** [comment]
As long as placement can be controlled and they can be switched off, I am fine with inline labels.
I will use them in the GUI Diagrams ... .

**Comment by mayersre** [comment]
I can not contribute my last code as it belongs to the school. But this is in general how I structure it : 
- create a class c1 for the type of diagram
- create an inside class for the lines and labels data, so it can be stored and loaded
- inside create a method m1 for each line, it only draws one line and labels it
- inside create a method m2 to calculate the amount of lines of one type and plot them using m1

Example just fragments of code or declarations :

class diagram_p_h:
    #
    def __init__(self,
         ref=None,          # Refrigerant name for backend e.G. REFPROP::Propane
         refname=None,      # Refrigerant name for Title   e.G. R-290
         title=u'Nice Log p h Diagram for %s \n',
         pmin=50000,        # Y-Axis lowest value in Pascal
         pmax=None,         # Y-Axis highest value in Pascal
         hmin=None,         # X-Axis lowest value in J/kg
         hmax=None,         
         smin=None,         # Entropy
         smax=None,
         Tmin=173.15,       # Temperature
         Tmax=493.15,
         Ttrip=None,        # override automatic, Sometimes neccessary for mixtures
         PlotFogArea=False, # Isochoric and Isentropic lines for q=0 to 1
         s_distance=None,   # distance from one isentropic line to the next in J/(kgK)
         t_distance=10,     # distance from one isothermal line to the next defaults to 10°C None=automatic
         isothermals=None,  # numpy array with values for all isothermal lines, disables automatic
         qualities=None,    # numpy array with values for all quality lines, disables automatic
         isentropics=None,  # numpy array with values for all isentropic lines, disables automatic
         #
         size_x=14,         # Figure size in inches
         size_y=10,         #
         yticks=None,       # ticks to use on the pressure axis, None=automatic
         legende=True,      # display legend
         top=0.94,          # Borders of figure in plot
         bottom=0.08,
         left=0.06,
         right=0.96,
         #
         data=None,         # class of calculated data, no calculation, plot from data

         **kwargs):
        
        # Now define colors, 
        self.h_color='DarkCyan' # b
        self.t_color='r' # r
        self.d_color='SeaGreen' # g
        self.x_color='k' # k
        self.p_color='brown'
        self.s_color='blue'
        self.cp_color='MediumPurple'
        self.BubbleLine_color='MediumVioletRed'
        self.DewLine_color='DarkBlue'
        #ticks ...  
        ticks[water]=([0.007,0.008,0.01,0.015,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.1,0.15,0.2,0.3,0.4,0.5,0.6,0.7,0.8,1.0,1.5,2,3,4,5,6,7,8,10,15,20,30,40,50,60,70,80,100,150,200,250,300,350])
        ticks[p45]= ...
        # then grid ...
        # place axis ticks and labels and titles
        # add Methods to load/save data, png, ps, svg, add Logos
        # Determine Critical point and Triple point, iterate a close value for plotting in case of failure
        # set reference state
                
    def Plot_saturation_lines(self):
        #
    def Plot_Isothermal_Line(self, #plots just one line
                       Temperature, 
                       Color='r', 
                       Linewidth=0.5,
                       Label=True,
                       Commadigits=2):
        
    def Plot_isothermal_lines(self):
        # calculates amount of lines and calls Plot_Isothermal_Line for each
        
    def Plot_Isentrope(self,
                       Entropy,
                       Color='b',
                       Linewidth=0.5,
                       Label='s={0:.2f}'): # Label can not only be true or false ...
    
    def Plot_isentropic_lines(self):
        #
        minorsteps=self.s_distance*self.kJ # thin lines
        majorsteps=5.0*minorsteps          # thick labeled lines
        #
        # Find a start and end for Isentropic lines, I try around critical point and lower right corner of diagram
        s_top    = round((PropsSI('S','T',self.Tcrit,'Q',1,self.ref))/100,0)*100.0
        s_bottom = round((PropsSI('S','P',self.pmin,'H',self.hmax,self.ref))/100,0)*100.0
        #
        isentropics=np.arange(s_top,s_bottom,minorsteps)*1.0 # make it floats
        #
        for iv in range(len(isentropics)):
            if ( (isentropics[iv]% (majorsteps-0.00001)) < minorsteps ) :
                Linewidth=0.5
            else :
                Linewidth=0.25  

Finally I format the labels usually down to 4 relevant digits depending on the size of
my value to have not unneccessary long values and avoid exponential notation.

                if (specific_volume < 0.01) :
                    vlabel='v={0:.6f}'
                elif (specific_volume >= 0.01) and (specific_volume <= 0.1 ):
                    vlabel='v={0:.5f}'
                elif (specific_volume >= 0.1) and (specific_volume < 10 ):
                    vlabel='v={0:.4f}'
                elif (specific_volume >= 10) :
                    vlabel='v={0:.2f}'
                elif (specific_volume >= 100) :
                    vlabel='v={0:.1f}'

I hope this helps or inspires a little

**Comment by mayersre** [comment]
oh,  and 220°C as highest temperature suits well for refrigeration. Most oils stop working there, so compressor discharge has to remain well below ...

**Comment by jowr** [comment]
Thanks again. I am quite busy these days, but I hope that I can get back to this issue after the summer, which is not before September I am afraid. If anyone has the energy to continue the work, please feel free to have a look at the `draw_process` branch.

**Comment by jowr** [comment]
The last commit 832241f02c013f40fc7b03f518acccf8e736bbb7 looks a little better. 
```Python
pp = PropertyPlot('HEOS::Water', 'TS', unit_system='EUR')
ph = pp.get_axis_limits(CoolProp.iP, CoolProp.iHmass)
pp.calc_isolines(CoolProp.iP,     ph[0:2])
pp.calc_isolines(CoolProp.iHmass, ph[2:4])
pp.calc_isolines(CoolProp.iQ,     [0.0,1.0], num=11)
cycle = SimpleRankineCycle('HEOS::Water', 'TS', unit_system='EUR')
T0 = 300
pp.state.update(CoolProp.QT_INPUTS,0.0,T0+15)
p0 = pp.state.keyed_output(CoolProp.iP)
T2 = 700
pp.state.update(CoolProp.QT_INPUTS,1.0,T2-150)
p2 = pp.state.keyed_output(CoolProp.iP)
cycle.simple_solve(T0, p0, T2, p2, 0.7, 0.8, SI=True)
cycle.steps = 50
sc = cycle.get_state_changes()
pp.draw_process(sc)
cycle.simple_solve(T0-273.15-10, p0/1e5, T2-273.15+50, p2/1e5-5, 0.7, 0.8, SI=False)
sc = cycle.get_state_changes()
pp.draw_process(sc, line_opts={'color':'blue', 'lw':1.5})
pp.show()
```
now yields
![figure_1](https://cloud.githubusercontent.com/assets/769593/8805042/6d5b36e8-2fcf-11e5-9959-283b2ea3b667.png)

**Comment by jowr** [comment]
@pdewallef , is this what you were looking for?
