### ISSUE TITLE
Some headers are missed in source code zip file on SourceForge

### ISSUE THREAD

**Issue by ChenYuChih** [CoolProp/CoolProp#362]
Dear Mr. Bell,

With the source code zip file on SourceForge, some error messages just show up during compiling. After read the messages, I found that some headers(such like "all_fluids_JSON.h", "all_incompressibles_JSON.h", "mixture_binary_pairs_JSON.h", "mixture_departure_functions_JSON.h", "predefined_mixtures_JSON.h" ... etc) are missed. Would you please put them together? Thank you very much!

Sincerely,
ChenYuChih(David Chen)

**Comment by ChenYuChih** [comment]
Excuse me, I found that the new external dependency "msgpack" is not packed into the source code of version 5.0.8. Would you please add it into the source code packing list? 

Thank you very much!

Regards,
ChenYuChih(David Chen)

**Comment by ibell** [comment]
Not sure why it isn't getting packed, it should be, but I'll take a look.

**Comment by ibell** [comment]
Ok, the submodules were not getting initialized.  This should fix it for
the next release: c2667db3448efcfa5d13a7182f19b166a1466e1c

**Comment by ChenYuChih** [comment]
Thank You ;)

2015-03-03 10:55 GMT+08:00 Ian Bell <notifications@github.com>:

> Ok, the submodules were not getting initialized. This should fix it for
> the next release: c2667db3448efcfa5d13a7182f19b166a1466e1c
>
>
