### ISSUE TITLE
Also integrate the sphinx docs into the binaries/release/unstable folder output

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#378]
I am not sure how best to handle this, but we should make sure that when we do a release, the docs are up to date with the release branch.  Currently they always upload to public_html/binaries

**Comment by jowr** [comment]
I'll have a look - docs are always uploaded to Sphinx, only the release script pushes a zip files to binaries...

**Comment by ibell** [comment]
Yes, always uploading to public_html/sphinx is the problem, but I'm not
sure how to fix this because we need to use something that is renderable.

**Comment by jowr** [comment]
This is not done. The commit f635528101a2f36192a2ed81aed808f7ad0052ca messed up the release script. 

This line https://github.com/CoolProp/CoolProp/blob/master/dev/scripts/release.bsh#L106 refers to folderm that has been replaced by 'sphinx' and this one https://github.com/CoolProp/CoolProp/blob/master/dev/scripts/release.bsh#L118 expands to ```$BASEDIR/$BINFOLDER/sphinx/sphinx``` is that intended? Do we really want the sphinx files on sourceforge - http://sourceforge.net/projects/coolprop/files/CoolProp/5.0.6/sphinx ?

If you could explain the desired behaviour, I might be able to help :wink:

**Comment by ibell** [comment]
Argh.  Sorrry about that. The idea is that we also want the docs to be
built in the same way as the binaries, getting put into binaries/sphinx for
a build from master branch, or release/sphinx when built from release
branch.  That way we can be 100% sure that the docs are also tagged to the
same revision as the binaries.  Furthermore, I am now automatically forcing
a full rebuild of all binary builders as well as the docs if the branch is
release, so that should avoid old files ending up in sphinx docs.

$BASEDIR/$BINFOLDER/sphinx/sphinx should be $BASEDIR/$BINFOLDER/sphinx I
think

And no, I don't think we want the sphinx files on SF :)

Ian

**Comment by jowr** [comment]
OK, I'll have a look. Thanks.

**Comment by jowr** [comment]
I just committed some changes to the script. I could not test the upload of the docs without making a release, but the rest should work. Let us keep this issue around until the new script is fully tested.

**Comment by ibell** [comment]
Yes, sounds good.  What was the problem with the docs when I released
v5.0.6?  It looks ok to me from a cursory glance.

Ian

**Comment by jowr** [comment]
The sphynx folder was on SourceForge and the zip file was not generated correctly.

**Comment by ibell** [comment]
Umm @jowr, are we safe to close this one after the 5.0.7 release? It looks good to me I think, there are the docs in a zip file, and no sphinx directory
