### ISSUE TITLE
Bibtex numbering

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#386]
Seems like PybTex still chokes occasionally, check references at: http://www.coolprop.org/fluid_properties/Mixtures.html#mixtures

**Comment by ibell** [comment]
Any guess why this happens?

**Comment by ibell** [comment]
This seems to be a bug in pybtex, this is in the build log:

```
/Users/jowr/Documents/OSX-IPU-slave/Sphinx_docs/build/Web/fluid_properties/PurePseudoPure.rst:110: WARNING: duplicate citation Lemmon-JPCRD-2000, other instance in /Users/jowr/Documents/OSX-IPU-slave/Sphinx_docs/build/Web/fluid_properties/Mixtures.rst
```
we have 
```
.. bibliography:: ../../CoolPropBibTeXLibrary.bib
   :filter: docname in docnames
   :style: unsrt
```
in fluid properties, and 
```

.. bibliography:: ../../CoolPropBibTeXLibrary.bib
   :filter: docname in docnames
   :style: unsrt
```
in mixtures, so it should work.

**Comment by ibell** [comment]
I'm trying to figure - did this work properly before?

**Comment by jowr** [comment]
No idea, guess I never checked it before.

**Comment by ibell** [comment]
Ah, it seems you can't have more than one bibliography in the project.  Bummer.
