### ISSUE TITLE
Vectorised PropSI breaks plotting functions

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#387]
Looks like the new PropsSI causes some trouble.
```
Traceback (most recent call last):
    isoqual = isoObj.get_isolines([0.0,1.0], num=2)
  File "/home/jowr/envs/CoolProp5/lib/python2.7/site-packages/CoolProp/Plots/Plots.py", line 370, in get_isolines
    lines = self._get_sat_lines(x=iso_range)
  File "/home/jowr/envs/CoolProp5/lib/python2.7/site-packages/CoolProp/Plots/Common.py", line 183, in _get_sat_lines
    kind, sat_mesh)
  File "/home/jowr/envs/CoolProp5/lib/python2.7/site-packages/CoolProp/Plots/Common.py", line 153, in _get_fluid_data
    return numpy.array([x_vals, y_vals])
ValueError: could not broadcast input array from shape (500,1) into shape (500)
```

**Comment by ibell** [comment]
Probably needs a squeeze() call to chop off useless axis.  We might want to
do that automatically in pyx file

**Comment by jowr** [comment]
Go ahead and fix it :wink:

**Comment by ibell** [comment]
Will do, I just need to figure out how best to handle it.  I think the
squeeze() should do the trick

**Comment by jowr** [comment]
There are some more pitfalls hiding. `Tv` and `Pv` are numpy arrays of the same length with valid inputs:
```
Dv = PropsSI("D","T",Tv,"P",Pv,fluid)
File "CoolProp/CoolProp.pyx", line 204, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:16510)
File "CoolProp/CoolProp.pyx", line 238, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:15967)
File "stringsource", line 63, in vector.from_py.__pyx_convert_vector_from_py_double (CoolProp/CoolProp.cpp:25113)
TypeError: only length-1 arrays can be converted to Python scalars
```
Note that `Tv` and `Pv` are **2D** arrays, if that is not supported, we should provide a proper error message.

**Comment by jowr** [comment]
nope, they are truely 2d, guess we just need a better message.

**Comment by ibell** [comment]
Did that ever work before?  I'm not sure why it would have...  Your best
bet would be to reshape the inputs to Nx1, then reshape back after the
calculations

**Comment by jowr** [comment]
Yep, it never worked before. I was just curious to test it now that we have the mighty PropsSImulti that works like a charm.

**Comment by ibell** [comment]
Unrelated, but have you done any speed comparisons between PropsSImulti and
multiple PropsSI calls? I'm curious how much of a difference it makes.

**Comment by ibell** [comment]
What should we do about this issue? Can you recommend a solution? I can implement it.

**Comment by jowr** [comment]
Well, I think it is fixed. If no one encountered any problems yet, my solution might just work (for once). Haven't tested the speed though.

**Comment by jowr** [comment]
We are still missing a propper error message though.

**Comment by ibell** [comment]
Hmm I can fix that.  Should be easy to repair.
