### ISSUE TITLE
CoolProp 5.0.5 from PyPI: Python import error

### ISSUE THREAD

**Issue by frisbee00** [CoolProp/CoolProp#388]
Hi,
<b>CoolProp 5.0.5 + Python 3.4.2</b>

Installed CoolProp 5.0.5 from PyPI and using:
<pre>import CoolProp.CoolProp as CP</pre>
throws the error:
<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/CoolProp/__init__.py", line 5, in <module>
    from . import constants
  File "/usr/lib/python3.4/site-packages/CoolProp/constants.py", line 3, in <module>
    import _constants
ImportError: No module named '_constants'
</pre>
<b>EDIT:</b> Running Archlinux

**Comment by ibell** [comment]
I think I have fixed this in the linked commit. As this is a serious bug, we will try to push out 5.0.6 earlier than originally planned.  For the time, being, you can compile from source.  As you are on linux, that should be painless.

**Comment by frisbee00** [comment]
Yeah, that's fine; will close the issue once the fix is confirmed.

**Comment by ibell** [comment]
Fixed.
