### ISSUE TITLE
HAPropsSI("D", "T",273.15+20, "R", 0.8, "P", 101325) lead to an error

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#389]
Hello Ian,

I wish the best for the new year !

Description of the error :  "Saturation pressure [101325 Pa] corresponding to T [373.124 K] is within 1e-4 % of given p [101325 Pa]"
The DLL called is the last on the website http://www.coolprop.dreamhosters.com:8010/binaries/MicrosoftExcel/

Sincerely,
PY

**Comment by pmanach** [comment]
Hello Ian, have you look at this problem ?

**Comment by ibell** [comment]
No, not yet.  I'm in the middle of a bunch of other things, hopefully I can
take a look today.

**Comment by ibell** [comment]
Bug confirmed.
