### ISSUE TITLE
crash: AccessViolationException in .net when calling certain coolprop functionality

### ISSUE THREAD

**Issue by koenveevee** [CoolProp/CoolProp#392]
When implementing the logic for calling CoolProp, we have added some tests, including running the test code your team provided
(http://ubuntu.mirrorservice.org/sites/ftp.sourceforge.net/pub/sourceforge/c/project/co/coolprop/CoolProp/nightly/Csharp/Example.cs)
But at line 99 (Density of saturated liquid Propane at 101325 Pa, calculation via RefProp), the call to CoolProp fails on certain machines, on others it works.
Oddly enough, previous calls (2 lines before) to CoolProp work correctly on all machines.

![code](https://cloud.githubusercontent.com/assets/10421867/5631608/184f98ac-95c8-11e4-93af-9c9fa1bbb563.png)

The executing directory is "C:\\Program Files (x86)\\RefProp"
which contains a fully working version of RefProp (the setup is identical to that of the working machines)

![refprop version](https://cloud.githubusercontent.com/assets/10421867/5631620/28ebfcd2-95c8-11e4-92df-00602b2467a1.png)

**Comment by ibell** [comment]
You should get an error message as part of the traceback if you are using
the most up-to-date versions of CoolProp.  What version do you use?  The
CoolProp call should always work without problems since it calls the
CoolProp flash routines.

**Comment by koenveevee** [comment]
Hi Ian,

 

We’re using CoolProp version: 4.2.5

What do you mean with ‘traceback’? I’m debugging in .net, and there, the exception does not contain any more info than what I’ve passed in the screenshot. To my experience, it’s an error outside the .net CLR, i.e. in the native x86 code inside the dll, making the interoperability environment crash. This seems like a segmentation fault to me.

Is there more info to be found? I cannot find an error log file in the neither directory.

 

Koen

**Comment by koenveevee** [comment]
Hi Ian,

 

If it can help you, I managed to refine the reproduction conditions of the error: 

The error always occurs at the second call to calculate via RefProp. In this case, by using "REFPROP-R401A" as liquid.
It suggests me that the first call to RefProp corrupts something, e.g. a pointer, making it break a second call?
 
I have been looking further (see issue #393) and see that the RefProp fluid name is wrong, although when using it on one machine this seems to work. When I use “REFPROP::R401A” it does not crash.
However, I always get INF as a result, while it should be a regular number. 
 
Regards,
Koen

**Comment by jowr** [comment]
This is very likely. There are some bugs in the handling of the refprop library and your problem might just vanish in version 5. Have you tried to use that one?

**Comment by jowr** [comment]
That should be fine, I was just wondering if you only tried 4.2.5. Sorry, but I cannot help you at the moment.

**Comment by ibell** [comment]
You should follow the C# instructions here: http://www.coolprop.org/coolprop/wrappers/Csharp/index.html#csharp

That will give you a fully featured wrapper for CoolProp in C#

In v5.0.5 and onwards, the error messages caused by an inability to load REFPROP properly are bubbled properly through to C# and you can hopefully figure out why it didn't work properly.

Most likely your system PATH is correct on one machine, and wrong on the other one, which is why REFPROP loads on one, and not on the other.  Have you installed REFPROP to creative places on your machine?

**Comment by ibell** [comment]
Any progress?

**Comment by koenveevee** [comment]
Hi Ian,

 

No, RefProp is installed on the regular place, i.e. c:\program files (x86) 

For x86 processes, this directory is translated from c:\program files for the case some software would look on that path.

 

Koen

**Comment by koenveevee** [comment]
I was not able to test v5.05 since I got the code, but the dlls I found that were meant to match this code all yielded the following error: dll entry point not found, which basically means the .net interoperability functionality does not find a method with that name and signature.

This was obtained without altering anything in the code. So I’m stuck there on what concerns v5.0.5

**Comment by ibell** [comment]
You don't use one of the standard dll, you know that right?  You use the C#
special DLL as described here:
http://www.coolprop.org/coolprop/wrappers/Csharp/#pre-compiled-binaries

Start with a blank C# project, add the example.cs file, and then all the
files in the platform-independent zip file.  Add the C# DLL to the project,
and I think you can right click on the DLL and tell it C# to copy the DLL
to the output directory.  That should "just work".

I think the easiest way to get people started might be to just package an
entire solution for visual studio.  We could add that to the automatically
generated files. It would decrease the barriers to entry I think.  What
version of Visual Studio do you use?

**Comment by koenveevee** [comment]
Hi Ian,

 

The problem was that the directory

http://sourceforge.net/projects/coolprop/files/CoolProp/5.0.5/Csharp/platform-independent/

contained a link stating “looking for the latest version” suggesting that there the platform independent code was to be found in a zipfile, whilst it is the CoolProp code and not what I expected. Now I took the 7z file one directory higher and the 32-bit coolprop. Those interoperability (SWIG) files do the job. There are other interop cs files circulating that do not match the dll you provided. 

I’ve been testing on different machines. On the machines where previous version worked the new version also works. On the machine where the crash occurred the RefProp calls did not work at first (although the working directory was the default RefProp installation directory), an exception was thrown stating:

ApplicationException: Initialize failed for backend: "REFPROP", fluid: "Propane" fractions "[ 1.0000000000 ]"; error: REFPROP fluid files must be copied to c:\P

rogram Files\REFPROP\fluids

RefProp was installed using the default settings, which redirects it to c:\program files (x86)\refprop which is default on x64 Windows versions (this one was Windows 7 ultimate).

However, seems that your code searches in c:\program files\refprop

So from the I copied the contents from c:\program files (x86)\refprop to c:\program files\refprop it worked. However, I’d prefer it having to work with the default settings as well instead of forcing c:\program files\refprop.

 

 

Am I correct, following what I see in the example code, that TTSE is not to be used anymore? Its calling code is commented out.

 

Thanks for the feedback

Koen

**Comment by ibell** [comment]
It's not a problem with CoolProp, it's a problem with REFPROP.  The first
place it searches for fluid files is *always* c:\Program Files\REFPROP,
regardless of where it is installed.  This is a known issue with REFPROP
that I can try to see if I can get fixed.  For now, just copy the files to
c:\Program Files\REFPROP.  This is why we compile all the fluid information
into CoolProp, it avoids one additional complication with regards to
loading of fluid files.

**Comment by ibell** [comment]
Also, there is a facility, though not well-documented at all, and subject to change, to change an internal  configuration variable in order to change the fluid loading path for REFPROP.

At the beginning of your code, before doing anything, do a call like 

CoolProp.set_config_string(configuration_keys.ALTERNATIVE_REFPROP_PATH,"NEW\\PATH\\TO\\REFPROP\\ROOT\\DIRECTORY")

I might be a tad bit off on the syntax there, but that's the basic concept.

**Comment by koenveevee** [comment]
Ok Thanks Ian!
