### ISSUE TITLE
The coolprop example in c# for RefProp is wrong

### ISSUE THREAD

**Issue by koenveevee** [CoolProp/CoolProp#393]
On http://www.coolprop.dreamhosters.com:8010/sphinx/v4/examples/CSharp/example.html, a code example is found, however, in the part demonstrating the algorithm in RefProp, the fluid used is not a RefProp name thus not calling the RefProp algorithms but the CoolProp ones.
The C++ variant of the example (https://media.readthedocs.org/pdf/coolprop/latest/coolprop.pdf) is correct: it adds the line
RPName = get_REFPROPname("Propane");
and uses RPName further. But in C#, the method get_REFPROPname is absent.

**Comment by ibell** [comment]
The API has changed since v4, and the examples you are running are out of date.  There is a minimal example for v5 with C#, but we need help with updating the examples (see #296).  In v5, you would do:

```
get_fluid_param_string("Propane","REFPROPname")
```
