### ISSUE TITLE
keyed_output and incompressibles

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#395]
There is a new error with the minimum temperatures... http://coolprop.sourceforge.net/fluid_properties/Incompressibles.html#pure-fluid-examples

**Comment by ibell** [comment]
Can you add a failing test for this and I'll add a bug fix?  Otherwise I
can handle it

**Comment by ibell** [comment]
These fail:

``` python
PropsSI('Tmin','T',0,'P',0,'INCOMP::DowQ')
PropsSI('Tmax','T',0,'P',0,'INCOMP::DowQ')
```

**Comment by jowr** [comment]
Thanks, was just about to commit the catch tests...
