### ISSUE TITLE
Initialize fail for HEOS in mixture with Argon and CarbonDioxide (in Matlab)

### ISSUE THREAD

**Issue by xaumex** [CoolProp/CoolProp#396]
Hi,

If you try to compute a mixture with Argon and CarbonDioxide in its components, for example
\>\> CoolProp.PropsSI('D','T',298.15,'P',101325,'HEOS::Argon[0.5]&CarbonDioxide[0.5]')

the following error appears:
Warning: Initialize failed for backend: "HEOS", fluid:
"Argon[0.5]&CarbonDioxide[0.5]" fractions "[ 0.5000000000,
0.5000000000 ]"; error: n could not be matched in get_double_vector 

I found this error in Coolprop wrapper of Matlab (v5.0.5 and 5.0.4). I'm using Matlab R2013b in win64 arch.
I don't know if the error is in the matlab wrapper or in coolprop.

Thank you

**Comment by ibell** [comment]
That looks like a bug.  I'll try to fix it today.

**Comment by ibell** [comment]
It's a bug with that particular binary pair. Others seem to work fine.
