### ISSUE TITLE
HAPropsSI(Output, "B",252.84, "D";250.85, "P", 101325) lead to an infinite value

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#398]
Whatever the output HAPropsSI(Output, "B",252.84, "D";250.85, "P", 101325) lead to an infinite value.

**Comment by ibell** [comment]
Why are you providing wetbulb and dewpoint?  Can you provide the absolute humidity instead?  I'll try to fix this bug, but I don't know how involved it will be, and I'm short on time right now.

**Comment by pmanach** [comment]
Hello Ian, I tried to use absolute humidity instead of dew point, but problem is the same ( see #399)

**Comment by ibell** [comment]
I was thinking get rid of wetbulb, since that is the most problematic from
a numerical standpoint.

**Comment by pmanach** [comment]
Adsorption as a modification of air follows an Iso-wetbulb .... I think it's a good thing to maintain wetbulb ....

**Comment by ibell** [comment]
Sorry I don't know what I was thinking with that comment, maybe I meant
providing wetbulb and dewpoint, but yes, wetbulb will definitely still be
supported.

**Comment by pmanach** [comment]
hello Ian,
I tried the last version of coolprop:
HapropsSi(Output, W, Value_W, Input2, Value2, P, 101325) don't work for Input2 = B, H, R, V.

**Comment by ibell** [comment]
Please provide a separate issue, and please give the numerical values that
don't work.

**Comment by ibell** [comment]
This one works now too.
