### ISSUE TITLE
HAPropsSI(Output, "B",valueB, "R", 1, "P", 101325) lead to an error

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#400]
What ever the value of valueB and the Output, when R=1, HAPropsSI(Output, "B",valueB, "R", 1, "P", 101325) lead to an error

**Comment by ibell** [comment]
Its helpful if you provide the error message you get as well.  

I'm not surprised this doesn't work since the problem is somewhat overconstrained.  If the relative humidity is 1.0, the drybulb and wetbulb and dewpoint temperatures are all the same.  If R=1, don't also provide wetbulb
