### ISSUE TITLE
PropsSI vector function returns different array dimension on Linux and windows

### ISSUE THREAD

**Issue by mayersre** [CoolProp/CoolProp#402]
Linux python 2.7
Windows python 3.4
Coolprop 5.0.6dev 

Windows, returned array 1 dimension :
PropsSI(['H','D','S'],'P',[300000],'Q',1,'R134a')
array([  3.98995150e+05,   1.47701690e+01,   1.72671540e+03])   <<< one bracket

Linux, returned array 2 dimensions :
PropsSI(['H','D','S'],'P',[300000],'Q',1,'R134a')
array([[  3.98995150e+05,   1.47701690e+01,   1.72671540e+03]])  <<< two brackets

so on linux I need to add [0] after each vector call !

**Comment by ibell** [comment]
If you run from git, this issue should not exist, we do a squeeze to remove
empty axes.  The new release (today?) will fix this issue.

**Comment by ibell** [comment]
Works on linux:
``` python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import CoolProp
>>> CoolProp.__version__
u'5.0.6'
>>> CoolProp.CoolProp.PropsSI(['H','D','S'],'P',[300000],'Q',1,'R134a')
array([  3.98995150e+05,   1.47701690e+01,   1.72671540e+03])
```
