### ISSUE TITLE
Error in new CoolProp version in the function HAPropsSI (variable combination 'PH' and 'W')

### ISSUE THREAD

**Issue by somniumAeternam** [CoolProp/CoolProp#403]
There is a new error in the latest version of CoolProp in the module HAPropsSI:

>In [1]: from CoolProp.HumidAirProp import HAPropsSI
>
>In [2]: HAPropsSI('T','H',267769,'P',104300,'W',0.)
>
>ValueError                                Traceback (most recent call last)
><ipython-input-2-d43ecf629665> in <module>()
>----> 1 HAPropsSI('T','H',267769,'P',104300,'W',0.)

>C:\Program Files (x86)\Anaconda3\lib\site-packages\CoolProp\CoolProp.pyd in >CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:3741)()
>
>C:\Program Files (x86)\Anaconda3\lib\site-packages\CoolProp\CoolProp.pyd in >CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2484)()
>
>ValueError: Inputs in Brent [210.000000,450.000000] do not bracket the root.  Function values are >[-331293.270340,-88934.622659] :: inputs >were:"T","H",2.6776900000000000e+05,"P",1.0430000000000000e+05,"W",0.0000000000000000e+00 

This problem is not occuring in version 5.0.0:

>In [2]: HAPropsSI('T','H',267769,'P',104300,'W',0.)
>Out[2]: 536.4475964934569
>
>HAPropsSI('T','H',267769,'P',104300,'W',0.)

**Comment by ibell** [comment]
Yes Ill take a look.  I "fixed" a problem in HAPropsSI and it seems I broke
a few other things.

**Comment by ibell** [comment]
Actually, I think your "correct" temperature is wrong.  It is above the
maximum temperature at your atmospheric pressure, the maximum is given by
the saturation temperature of water at the atmospheric pressure.

**Comment by ibell** [comment]
Although.... if the "humid" air is actually dry, this should work.  It's a nasty corner case, I'll see what I can do.

**Comment by somniumAeternam** [comment]
Just for curiosity, why is that a corner case. According to the documentation: 

"It is applicable for pressure from 0.01 kPa up to 10 MPa, in a temperature range from -143.15 °C up to 350 °C with a humidity ratio from 0 kg of water up to 10 kg of water per kg of dry air."

The temperature is around 262 °C here. It should work?

**Comment by ibell** [comment]
Corner case in the sense that HAPropsSI is for *humid* air.  W=0 is dry
air, and there are in fact some inconsistencies between the humid air
properties and the dry air properties.  In that sense it is a corner case.
I've fixed this bug though.
