### ISSUE TITLE
Add R407F and R407A as Pseudo-Pure fluid

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#405]
Hello Ian, is it possible to add pseudo-pure R407F and R407A fluids in coolprop ?

**Comment by jowr** [comment]
Hi, do you have a publication with a description of the EOS and the coefficients? I am not aware of any published material and we cannot just copy coefficiecnt from REFPROP...

**Comment by ibell** [comment]
Nope, in fact there are no pseudo-pure EOS fit for these fluids.  Not in
REFPROP, not in CoolProp, nowhere.  So sorry, you are out of luck.  I can
make no promises, but I can ask about fitting pseudo-pure EOS for these
mixtures.

Ian

**Comment by thermengineer** [comment]
Dear Ian, Do you have any progress for R407F and R407A refrigerants?

**Comment by ibell** [comment]
Not far now.  I'm publishing a paper with the coefficients, once it is
submitted (by the middle of the week) I will implement the coefficients.

**Comment by thermengineer** [comment]
Dear Ian, Thank you for your prompt reply and works. You shall be highly appreciated if you also inform us by replying this issue after releasing update. Best regards.

**Comment by ibell** [comment]
You should join the mailing list, I plan to announce there. And probably on
this issue too.

**Comment by thermengineer** [comment]
Thank you.

**Comment by kevmegforest** [comment]
Just wanted to know what was the progress on this issue.

Thank you.

**Comment by ibell** [comment]
I should mention that it won't be a pseudo-pure fluid, rather it will be
interaction parameters for the mixture model.  That's quite a bit less
exciting since the flash routines for CoolProp are not as
complete/developed as for pseudo-pure fluids

**Comment by kevmegforest** [comment]
Hello Ian, was the paper published? And what`s the link to the mailing list?
Thanks

**Comment by ibell** [comment]
The paper has been submitted, but not accepted yet.  If you want a copy of the preprint, please email me at ian.bell@nist.gov.

The mailing list is listed here: http://www.coolprop.org/dev/#help

**Comment by ahjortland** [comment]
Wondering if there has been any progress made towards adding R407A & R407F as pseudopure mixtures...

**Comment by ibell** [comment]
Nope, my colleague Eric Lemmon would be the one to bug about that.  He said
it's quite easy...
