### ISSUE TITLE
Triple point temperature Refprop vs Coolprop wrong

### ISSUE THREAD

**Issue by mayersre** [CoolProp/CoolProp#406]
ref1='Propane'
ref2='REFPROP::Propane'
PropsSI(ref1,'Ttriple')
85.525
PropsSI(ref2,'Ttriple')
169.85
Win Excel = 85.525
Coolprop Version :  5.0.6
Gitrevision      :  038b0100bf26f6fc2dfc131e1d86b148245be3cf

**Comment by ibell** [comment]
Confirmed. Weird.

```
In [1]: import CoolProp

In [2]: CoolProp.CoolProp.PropsSI("Ttriple","Water")
Out[2]: 273.16

In [3]: CoolProp.CoolProp.PropsSI("Ttriple","Propane")
Out[3]: 85.525

In [4]: CoolProp.CoolProp.PropsSI("Ttriple","REFPROP::Propane")
Out[4]: 169.85

In [5]: CoolProp.CoolProp.PropsSI("Ttriple","REFPROP::Water")
Out[5]: 169.85
```

**Comment by mayersre** [comment]
Same with Butan, Isobutan and CO2

PropsSI('REFPROP::Butane','Ttriple')
63.151
PropsSI('R600','Ttriple')
134.895

PropsSI('R600a','Ttriple')
113.73
PropsSI('REFPROP::isobutan','Ttriple')
63.151

PropsSI('REFPROP::CO2','Ttriple')
169.85
PropsSI('CO2','Ttriple')
216.592
Am 15.01.2015 um 03:10 schrieb Ian Bell:

**Comment by ibell** [comment]
I'll bet this is a one-line fix.  I'll take a look tonight.

**Comment by jowr** [comment]
Works now:
```
In [1]: import CoolProp

In [2]: CoolProp.CoolProp.PropsSI("Ttriple","Water")
Out[2]: 273.16

In [3]: CoolProp.CoolProp.PropsSI("Ttriple","REFPROP::Water")
Out[3]: 273.16

In [4]: CoolProp.CoolProp.PropsSI("Ttriple","Propane")
Out[4]: 85.525

In [5]: CoolProp.CoolProp.PropsSI("Ttriple","REFPROP::Propane")
Out[5]: 85.525
```
