### ISSUE TITLE
HapropsSI function issues

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#408]
All these exaples lead to an infinite value: 

HapropsSI("B",232.93,"W",7.926*10^-7,"P",101325)
HapropsSI("R",0.01,"W",7.926*10^-7,"P",101325)
HapropsSI("H",-40221,"W",7.926*10^-7,"P",101325)

HapropsSI("B",233.11,"W",6.342*10^-5,"P",101325)
HapropsSI("R",0.8,"W",6.342*10^-5,"P",101325)
HapropsSI("H",-40069,"W",6.342*10^-5,"P",101325)

HapropsSI("B",251.62,"W",6.366*10^-6,"P",101325)
HapropsSI("R",0.01,"W",6.366*10^-6,"P",101325)
HapropsSI("H",-20096,"W",6.366*10^-6,"P",101325)

HapropsSI("B",271.99,"W",3.028*10^-3,"P",101325)
HapropsSI("R",0.8,"W",3.028*10^-3,"P",101325)
HapropsSI("H",7569,"W",3.028*10^-3,"P",101325)
HapropsSI("B",271.99,"D",270.47,"P",101325)

**Comment by pmanach** [comment]
Hello Ian, have you look at these problems ?

**Comment by ibell** [comment]
Nope, not yet.  These are very dry and very cold, perhaps that is the reason it fails...

**Comment by pmanach** [comment]
Hello Ian, there also some problem with hotter temperature : 

T=20°C / R =0.01 :
HapropsSI(Output,"B",279.14,"W",1.442^-4,"P",101325)
HapropsSI(Output,"V",0.830,"W",1.442^-4,"P",101325)
HapropsSI(Output,"R",0.01,"W",1.442^-4,"P",101325)
HapropsSI(Output,"H",20483,"W",1.442^-4,"P",101325)

T=20°C / R =0.8
HapropsSI(Output,"B",290.83,"W",1.175^-2,"P",101325)
HapropsSI(Output,"V",0.846,"W",1.175^-2,"P",101325)
HapropsSI(Output,"R",0.8,"W",1.175^-2,"P",101325)
HapropsSI(Output,"H",49933,"W",1.175^-2,"P",101325)

T=20°C / R =1
HapropsSI(Output,"B",293.15,"W",1.476^-2,"P",101325)
HapropsSI(Output,"V",0.850,"W",1.476^-2,"P",101325)
HapropsSI(Output,"R",1,"W",1.476^-2,"P",101325)
HapropsSI(Output,"H",57561,"W",1.476^-2,"P",101325)

**Comment by ibell** [comment]
All these work now:

```
from CoolProp.HumidAirProp import HAPropsSI

print HAPropsSI("T", "B",271.99,"W",3.028e-3,"P",101325)
print HAPropsSI("T", "R",0.8,"W",3.028e-3,"P",101325)
print HAPropsSI("T", "H",7569,"W",3.028e-3,"P",101325)
print HAPropsSI("T", "B",271.99,"D",270.47,"P",101325)

print HAPropsSI("T", "B",232.93,"W",7.926e-7,"P",101325)
print HAPropsSI("T", "R",0.01,"W",7.926e-7,"P",101325)
print HAPropsSI("T", "H",-40221,"W",7.926e-7,"P",101325)

print HAPropsSI("T", "B",233.11,"W",6.342e-5,"P",101325)
print HAPropsSI("T", "R",0.8,"W",6.342e-5,"P",101325)
print HAPropsSI("T", "H",-40069,"W",6.342e-5,"P",101325)

print HAPropsSI("T", "B",251.62,"W",6.366e-6,"P",101325)
print HAPropsSI("T", "R",0.01,"W",6.366e-6,"P",101325)
print HAPropsSI("T", "H",-20096,"W",6.366e-6,"P",101325)
```

**Comment by ibell** [comment]
These all work too:

``` python
from CoolProp.HumidAirProp import HAPropsSI
Output = 'k'

print HAPropsSI(Output,"B",279.14,"W",1.442e-4,"P",101325)
print HAPropsSI(Output,"V",0.830,"W",1.442e-4,"P",101325)
print HAPropsSI(Output,"R",0.01,"W",1.442e-4,"P",101325)
print HAPropsSI(Output,"H",20483,"W",1.442e-4,"P",101325)

#T=20 C / R =0.8
print HAPropsSI(Output,"B",290.83,"W",1.175e-2,"P",101325)
print HAPropsSI(Output,"V",0.846,"W",1.175e-2,"P",101325)
print HAPropsSI(Output,"R",0.8,"W",1.175e-2,"P",101325)
print HAPropsSI(Output,"H",49933,"W",1.175e-2,"P",101325)

#T=20 C / R =1
print HAPropsSI(Output,"B",293.15,"W",1.476e-2,"P",101325)
print HAPropsSI(Output,"V",0.850,"W",1.476e-2,"P",101325)
print HAPropsSI(Output,"R",1,"W",1.476e-2,"P",101325)
print HAPropsSI(Output,"H",57561,"W",1.476e-2,"P",101325)
```
