### ISSUE TITLE
HapropsSI function issues

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#414]
Hello Ian,

I've put the last version of HAPROPSSI function in my own test:
There are plenty of problems during the tests.

1/ When R=1 for one input, and B as a second input, there are some issues for the following outputs : T / D / V / W / H
example : hapropossi(T, B, 233.15, R, 1, P, 101325)
example : hapropossi(T, B, 253.15, R, 1, P, 101325)
example : hapropossi(T, B, 273.15, R, 1, P, 101325)
example : hapropossi(T, B, 293.15, R, 1, P, 101325)
example : hapropossi(T, B, 308.15, R, 1, P, 101325)
example : hapropossi(T, B, 343.15, R, 1, P, 101325)

2/ Others troubles near T=0°C :
hapropssi(H, D, 226.75, R, 0.01, P, 101325) lead to a false value
hapropssi(H, W, 3.767*10^-5, R, 0.01, P, 101325) lead to a false value
hapropssi(H, D, 226.94, R, 0.01, P, 101325) lead to a false value
hapropssi(H, W, 3.767*10^-5, R, 0.01, P, 101325) lead to a false value

3/ T&B and B&T lead to an error what ever the Ouput at the following value : 
hapropssi(Output, T, 293.15, B, 279.14, P, 101325) lead to a false value
hapropssi(Output, T, 293.15, B, 290.83, P, 101325) lead to a false value
hapropssi(Output, T, 293.15, B, 293.15, P, 101325) lead to a false value
hapropssi(Output, T, 308.15, B, 286.10, P, 101325) lead to a false value
hapropssi(Output, T, 308.15, B, 304.96, P, 101325) lead to a false value
hapropssi(Output, T, 308.15, B, 308.15, P, 101325) lead to a false value
hapropssi(Output, T, 343.15, B, 298.39, P, 101325) lead to a false value
hapropssi(Output, T, 343.15, B, 338.32, P, 101325) lead to a false value
hapropssi(Output, T, 343.15, B, 343.15, P, 101325) lead to a false value

4/ R&T (NOK) and T&R (OK) don't give the same values (infinite) for output B / D / W
hapropssi(Output, R, 0.01, T, 293.15, P, 101325)
hapropssi(Output, R, 0.8, T, 293.15, P, 101325)
hapropssi(Output, R, 1, T, 293.15, P, 101325)
hapropssi(Output, R, 0.01, T, 308.15, P, 101325)
hapropssi(Output, R, 0.8, T, 308.15, P, 101325)

5/ D&B (NOK) and B&D (OK) don't give the same values (infinite) for output V / R / H
hapropssi(Output, D, 289.60, B, 290.83, P, 101325)
hapropssi(Output, D, 293.15, B, 293.15, P, 101325)
hapropssi(Output, D, 304.18, B, 304.96, P, 101325)

6/ W&B (NOK) and B&W (OK) don't give the same values (infinite) for output T / V / H
hapropssi(Output, W, 1.175*10^-2, B, 290.83, P, 101325)
hapropssi(Output, W, 1.476*10^-2, B, 293.15, P, 101325)
hapropssi(Output, W, 3.676*10^-2, B, 308.15, P, 101325)
hapropssi(Output, W, 2.792^-1, B, 343.15, P, 101325)

7/ hapropssi(H, T, 293.15, D, 293.15, P, 101325) = OK where as hapropssi(H, D, 293.15, T, 293.15, P, 101325) lead to a infinite value
hapropssi(H, T, 308.15, D, 304.18, P, 101325) = OK where as hapropssi(H, D, 304.18, T, 308.15, P, 101325) lead to a infinite value

8/ hapropssi(H, R, 0.01, D, 265.25, P, 101325) = OK where as hapropssi(H, D, 265.25, R, 0.01, P, 101325) lead to a infinite value

**Comment by ibell** [comment]
These seem to be 8 different problems.  Please open 8 separate issues so we
can track the fixing of these bugs properly.

In general, there are serious numerical problems with wetbulb and dewpoint
calculations, so you can expect them to show bad behavior.  Some of these
look like simple bugs, some are more complex.

Also, please express numbers in scientific format at 3.676e-2 rather than
3.676*10^-2 as the former is computer readable and doesn't require me to do
reformatting.

Some of these I am aware of, others are surprising.  I am quite limited
time wise for CoolProp, but I will see what I can do.
