### ISSUE TITLE
Sphinx docs

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#416]
Just a reminder for the problems with the docs:
  - [ ] Docs do not build properly, timeout after 1200 seconds, occurs in buildbot and ssh mode
  - [ ] Docs link to the wrong doxygen folder
  - [ ] Add a link to the docs for v4

**Comment by ibell** [comment]
Any idea about the timeout?  Are you seeing anything on the slave?  I can't
see anything aside from the fact that it times out

Ah yes I noticed that too, I will fix part 2 tonight.

**Comment by jowr** [comment]
No, i have no idea. I sshed to the box and tried to fix it, but even ssh dies when running the builder. Docs build fine on my laptop though.

When you change the links, please link to sourceforge and not the buildbot-master.

**Comment by jowr** [comment]
Did I say things build fine? They certainly do not build on my laptop either... The process just hangs at `reading sources... [ 19%] coolprop/examples/examples `

**Comment by jowr** [comment]
Even increased verbosity does not help `sphinx-build -vvv -T -b html -d _build/doctrees . _build/html` just dies as well.

**Comment by ibell** [comment]
Hmm, that is weird.  I will try to dig into this tonight if I can find some
time. And yes, I will link to SF

**Comment by ibell** [comment]
Fails for me on ubuntu as well.  Just sits at coolprop/examples/examples

**Comment by ibell** [comment]
This is the problem:
```
HAPropsSI('T','P',101.325,'H',h,'R',1.0); print T
```
