### ISSUE TITLE
HapropsSI : trouble around 0°C

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#418]
2/ Others troubles near T=0°C :
hapropssi(H, D, 226.75, R, 0.01, P, 101325) lead to a false value
hapropssi(H, W, 3.767e-5, R, 0.01, P, 101325) lead to a false value
hapropssi(H, D, 226.94, R, 0.01, P, 101325) lead to a false value
hapropssi(H, W, 3.767e-5, R, 0.01, P, 101325) lead to a false value

**Comment by ibell** [comment]
This code
``` python
from CoolProp.HumidAirProp import HAPropsSI

print HAPropsSI('H', 'D', 226.75, 'R', 0.01, 'P', 101325)
print HAPropsSI('H', 'W', 3.767e-5, 'R', 0.01, 'P', 101325)
print HAPropsSI('H', 'D', 226.94, 'R', 0.01, 'P', 101325)
print HAPropsSI('H', 'W', 3.767e-5, 'R', 0.01, 'P', 101325)
```
yields
```
165.939725476
95.4792090765
480.563252703
95.4792090765
```
Looks fine.
