### ISSUE TITLE
HapropSI ("T","B",273.15+37,"D",273.15+36.44,"P",101325) lead to an error ...

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#419]
HapropSI ("T","B",273.15+37,"D",273.15+36.44,"P",101325) lead to the following error : 
"Inputs in Brent [313.487978,450.000000] do not bracket the root.  Function values are [0.061224,14.997309]"

**Comment by pmanach** [comment]
Hello Ian, have you find some time to look at this problem ?

**Comment by ibell** [comment]
This one works for me in C++ now.
