### ISSUE TITLE
HapropsSI : T&D / D&D don't give the same results

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#423]
hapropssi(H, T, 293.15, D, 293.15, P, 101325) = OK where as hapropssi(H, D, 293.15, T, 293.15, P, 101325) lead to a infinite value
hapropssi(H, T, 308.15, D, 304.18, P, 101325) = OK where as hapropssi(H, D, 304.18, T, 308.15, P, 101325) lead to a infinite value

**Comment by ibell** [comment]
This code:
```python
from CoolProp.HumidAirProp import HAPropsSI
    
print HAPropsSI('H', 'T', 293.15, 'D', 293.15, 'P', 101325), HAPropsSI('H', 'D', 293.15, 'T', 293.15, 'P', 101325)
print HAPropsSI('H', 'T', 308.15, 'D', 304.18, 'P', 101325), HAPropsSI('H', 'D', 304.18, 'T', 308.15, 'P', 101325)
```
yields
```
57560.8928984 57560.8928984
109759.88226 109759.88226
```
Looks fine to me.
