### ISSUE TITLE
HapropSI("T","B", ValueB+273.15,"W",0,"P",101325) near T=0°C

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#426]
Hello Ian,
could you tell why there is this allure for this function :

![capture](https://cloud.githubusercontent.com/assets/5717348/5893356/0d040afa-a4e1-11e4-8842-9b3cf1921aaa.PNG)

**Comment by ibell** [comment]
I think we had this discussion before, but the sublimation curve and the
saturation curve are not consistent, resulting in this jagged behavior
around the triple point temperature.  I think this is the explanation.

Also, degrees Kelvin should not use the degree symbol.  It's one of the
weird things with units in the SI system.

**Comment by pmanach** [comment]
For this problem. I think we can close the subject.

**Comment by ibell** [comment]
Go ahead, you can close the issue.  Click the close button in the web
interface.
