### ISSUE TITLE
HapropsSi("W","B", 279.15, "T", 293.15, "P", 101325) lead to a "-1.#IND" value

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#427]
HapropsSi("W","B", 279.15, "T", 293.15, "P", 101325) lead to a "-1.#IND" value (Not A Number)

Errstring : "p is not a valid number"

**Comment by pmanach** [comment]
Hello Ian, have you find some time to look at this problem ?

**Comment by ibell** [comment]
Nope.  Anything with wetbulb as an input is problematic, this might not be
simple/possible to fix.
