### ISSUE TITLE
Entropy of Melinder fluids giving wrong results

### ISSUE THREAD

**Issue by ericksonla** [CoolProp/CoolProp#429]
The entropy call with Melinder fluids changes with multiple calls. A simple test code:

from CoolProp.CoolProp import PropsSI

print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')

returns:
227508.367363
215363.646742
191074.205501

I have done a bit more testing:
-Occurs for other Melinder fluid mixtures
-Does not occur for single component incompressible fluids
-Does not occur for other property calls
-Does not appear to depend on the input values

I just upgraded to the latest version. I don't think this problem occurred before upgrade (4.?), but I can't be 100% sure.

**Comment by jowr** [comment]
Hi, thank you for the report. Are you sure that you have the latest version? It looks like bug #413 has nnot been solved entirely. For me, the output is
```
In [1]: import CoolProp
In [2]: print CoolProp.__version__ 
5.0.7dev
In [3]: from CoolProp.CoolProp import PropsSI
In [4]: print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
-227029.535639
In [5]: print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
233580.727674
In [6]: print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
-227029.535639
``` 
It is different, but also wrong. The alternating values tell me that it is the reference states function that does not reset the values properly. I'll have a look.

**Comment by ericksonla** [comment]
Just double checked- I'm on 5.0.7

**Comment by jowr** [comment]
Sorry, but that version does not exist. Well, it does not matter whether you are you on 5.0.6 or 5.0.7dev, the bug has to be fixed...

**Comment by jowr** [comment]
Thanks for reporting the bug. I broke it last week while fixing #413. Should be cool now:
```
In [1]: import CoolProp                                
In [2]: print CoolProp.__version__
5.0.7dev       
In [3]: from CoolProp.CoolProp import PropsSI         
In [4]: print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
239.415862162
In [5]: print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
239.415862162
In [6]: print PropsSI('S', 'T', 313.15, 'P', 100000., 'INCOMP::MEA[0.6]')
239.415862162
```

**Comment by jowr** [comment]
Luke, can you confirm that it works? It looks like you got different results earlier. Are you on Windows, Linux or a Mac?

**Comment by ericksonla** [comment]
I'm on Mac. I tried:
pip --upgrade --pre CoolProp
but it couldn't find 5.0.7dev.

Whats the preferred way of getting it?

**Comment by jowr** [comment]
The Mac binaries got generated 20 seconds ago, you can force a reinstall of the Python library by running `pip install --find-links http://www.coolprop.dreamhosters.com:8010/binaries/Python/ -U --force-reinstall CoolProp` or a similar command for your virtual environment. Does that make sense?

**Comment by ericksonla** [comment]
The first time I tried it just pulled 5.0.6 again but I added the --pre flag and then got 5.0.7dev. I don't know whether the flag or waiting 15 minutes made the difference but it worked.

I ran the test script again and everything looks good. My original code seems to be working too.

Thanks!

**Comment by jowr** [comment]
Good to hear and thanks again for the bug report.

**Comment by ibell** [comment]
Sometimes a couple of ```pip uninstall CoolProp``` in a row helps for future reference

**Comment by jowr** [comment]
Something is still wrong here! http://coolprop.dreamhosters.com:8010/builders/Catch-OSX/builds/977/steps/shell_2/logs/stdio
