### ISSUE TITLE
REFPROP should not be reloaded after every call to PropsSI

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#431]
When PropsSI is called multiple times, REFPROP should not be reloaded for each one, it is *much* slower.  What was the reason behind the destructor unloading REFPROP dll every time (https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L280-L303)?  We could add a simple wrapper class of REFPROP (REFPROP manager) that will ensure that the REFPROP unloader gets called exactly one time when the last instance is unloaded.

This code:
``` python
import CoolProp

CoolProp.CoolProp.set_debug_level(10)
PropsSI = CoolProp.CoolProp.PropsSI

for i in range(4):
    PropsSI('T','P',101325,'Q',0,'REFPROP::Water')
```
yields
```
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (WATER
..\..\..\..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:419: Successfully loaded REFPROP fluid: WATER.FLD
_PropsSI will return 373.124
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (WATER
..\..\..\..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:419: Successfully loaded REFPROP fluid: WATER.FLD
_PropsSI will return 373.124
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (WATER
..\..\..\..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:419: Successfully loaded REFPROP fluid: WATER.FLD
_PropsSI will return 373.124
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (WATER
..\..\..\..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:419: Successfully loaded REFPROP fluid: WATER.FLD
_PropsSI will return 373.124
```

**Comment by ibell** [comment]
So, the issues are:

1) We want to tie one instance of REFPROP to a state class
2) We want that multiple calls to PropsSI that use REFPROP do NOT result in REFPROP being loaded every time

**Comment by ibell** [comment]
@jowr I've been thinking about this quite a bit, and am at an impasse.  What is the best way to go about this? Hold onto the last state class created using a shared_ptr, and only reset it if the fluid string changes?

**Comment by jowr** [comment]
Yes, that sounds like the easiest solution. I am not sure how much it takes to implement this, but I reckon that this is the "cheapest" solution for now.

**Comment by ibell** [comment]
Yet another idea, when the REFPROP class calls its destructor, store the
pointer to the REFPROP dll instance, and the fluids loaded as a string.
That REFPROP instance could be loaded in the next call to the constructor.
I gather that REFPROP does not reload the fluids if the fluids have not
changed, so there is no need to check that in the CoolProp code.

**Comment by ibell** [comment]
So some info:

* Currently, only one copy of REFPROP gets loaded, subsequent calls to LoadLibrary or dlopen just result in the pointer getting returned
* It *is* possible to load multiple copies of a shared library on linux: http://stackoverflow.com/questions/1745975/load-multiple-copies-of-a-shared-library
* Not sure about windows

**Comment by ibell** [comment]
:(  : http://stackoverflow.com/questions/1587176/load-multiple-copies-of-dll-in-same-process

**Comment by ibell** [comment]
See https://github.com/CoolProp/CoolProp/tree/REFPROP_multiple_copies

**Comment by ibell** [comment]
We have a problem with master.  This crashes, but not until returning the same critical temperature (that of water) for BOTH states !!!!  Which is clearly wrong!  For some reason the second nitrogen call causes a crash.

``` python
import CoolProp

Water = CoolProp.AbstractState('REFPROP', 'WATER')
N2 = CoolProp.AbstractState('REFPROP', 'NITROGEN')
print Water.keyed_output(CoolProp.iT_critical), N2.keyed_output(CoolProp.iT_critical)

N2 = CoolProp.AbstractState('REFPROP', 'NITROGEN')
Water = CoolProp.AbstractState('REFPROP', 'WATER')
print Water.keyed_output(CoolProp.iT_critical), N2.keyed_output(CoolProp.iT_critical)
```

**Comment by ibell** [comment]
Now this works properly:
``` python
import CoolProp

Water = CoolProp.AbstractState('REFPROP', 'WATER')
N2 = CoolProp.AbstractState('REFPROP', 'NITROGEN')
print Water.keyed_output(CoolProp.iT_critical), N2.keyed_output(CoolProp.iT_critical)

N2 = CoolProp.AbstractState('REFPROP', 'NITROGEN')
Water = CoolProp.AbstractState('REFPROP', 'WATER')
print Water.keyed_output(CoolProp.iT_critical), N2.keyed_output(CoolProp.iT_critical)
```
yields
```
647.096 126.192
647.096 126.192
```
