### ISSUE TITLE
CoolProp Online

### ISSUE THREAD

**Issue by amasal** [CoolProp/CoolProp#435]
The mole-based property calculation doesn't work properly, although the mass-based does

**Comment by ibell** [comment]
Thanks for the note, I haven't worked on the online code in a while...

**Comment by ibell** [comment]
Seems like it is working for me.  Can you provide a set of inputs that don't work for you?  A screenshot of the error would be helpful.

**Comment by amasal** [comment]
Dear Ian,
thank you for considering my comment. Let's take one example:
Fluid		 n-Propane	Input #1	         Pressure[Pa]	Value #1	         658612.5
Input #2	          Temperature [K]	Value #2          284.65
Output Units	:  Mass-based
Output:
n-PropaneAt the specified state pointTemperature [K]       284.65Pressure [Pa]	             658612.499957
Vapor quality [kg/kg]	-1.0Speed of sound [m/s]	219.725509508Density [kg/m3]		14.228114439Enthalpy [J/kg]		587485.958612Entropy [J/kg/K]	        2363.42627281
Constant-pressure specific heat [J/kg/K]	1847.85527954Constant-volume specific heat [J/kg/K]		1492.0187385*************************************************************Which are correct. However, for same input data if  mole-based output Unitsis selected the following results are obtained:
Output:
n-PropaneAt the specified state point
Temperature [K]	284.65Pressure [Pa]	       658612.499957
Vapor quality [kg/kg]	-1.0Speed of sound [m/s]	  219.725509508Density [mol/m3]	          322.665027478   CORRECTEnthalpy [J/mol]	         587485.958612    INCORRECT, MUST BE  = 2596 [J/mol] Entropy [J/mol/K]	         2363.42627281    INCORRECT, MUST BE  = 104.2167 [J/mol]
Constant-pressure specific heat [J/mol/K]	81.4823242215  CORRECTConstant-volume specific heat [J/mol/K]       65.7914913258  CORRECT
The incorrect values are, because they are not converted to the mol-based units (Molecular weight of Propane=0.04409562 Kg/kmol)
Other Issue are:
*the p-T saturation plot is not plotted. 
* Could be useful if the references estate is shown. For this case:
Tref = 273.15 K, Pref= 0.001 MPa and Href= 26148.48 [J/mol] Sref = 157.9105 [J/mol/K]    ( Lemmon, E. W., 2009, J. Chem. Eng. Data, 54:3141–3180)
Regards

Date: Tue, 27 Jan 2015 15:57:01 -0800

**Comment by ibell** [comment]
Closed by https://github.com/CoolProp/Coolprop-Online/commit/2fdf8df4902cf714c7d6b18640afe6b55dc59fcb
