### ISSUE TITLE
Installing CoolProp 5.0.6 on Linux

### ISSUE THREAD

**Issue by JAExposito** [CoolProp/CoolProp#436]
Hello,

I had previously used CoolProp 4.2.0 and I installed it on Linux running the make file in the shared library folder of the source code. Now, in the version 5.06 there is no shared library folder within the wrappers folder so I would like to know how should I install it?

Thank you in advance and kind regards.

**Comment by ibell** [comment]
Have you seen this: http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#shared-library ?

**Comment by JAExposito** [comment]
Hello,

Yes I saw it but I was not sure if this would work like the previous version I used. Will this execute the cmakelist file? I guess that the command "cmake .. -DCOOLPROP_32BIT_STDCALL_SHARED_LIBRARY=ON" will execute the installation as it used to be with the make file y version 4.2.0 and then CoolProp can be used like in the example in C++ code. Is that correct? 
For installing the new versión 5.0.6 should I remove the previous one before?

Kind regards.

**Comment by jowr** [comment]
It will build the library, not install it. We do not include install scripts in the new version, you are very welcome to contribute an updated makefile that can be used to install the shared library on Linux and MacOS.

**Comment by jowr** [comment]
You can also check the cmake docs, something like `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCOOLPROP_32BIT_STDCALL_SHARED_LIBRARY=ON .. && make all install` might work as well, but I am not sure. ... and yes, you should remove the old version before installing a new one.

**Comment by jowr** [comment]
I just tried it myself and something is wrong here: 
```
In file included from /home/jowr/Documents/Fluids/CoolProp.GitHub/src/CoolPropLib.cpp:9:0:
/home/jowr/Documents/Fluids/CoolProp.GitHub/include/CoolPropLib.h:70:35: error: expected initializer before ‘Props1SI’
     EXPORT_CODE double CONVENTION Props1SI(const char *FluidName, const char* Output);
```
It looks like the calling conventions are somehow messed up fir 32bit Linux.

**Comment by jowr** [comment]
For me, `cmake ../CoolProp.GitHub -DCOOLPROP_32BIT_SHARED_LIBRARY_LINUX_MODULE=ON` could compile the code properly. To install, you have to run
```
sudo cp libCoolProp.so /usr/local/lib/libCoolProp.so.32.5.0.7dev
pushd /usr/local/lib
sudo ln -sf libCoolProp.so.32.5.0.7dev libCoolProp.so.5.0
sudo ln -sf libCoolProp.so.5.0 libCoolProp.so.5
sudo ln -sf libCoolProp.so.5 libCoolProp.so
popd
```
You might also need the new header file `CoolPropLib.h`. This one should go to `/usr/local/include`.

**Comment by ibell** [comment]
Does the ``make install`` do the trick if you set the CMAKE_INSTALL_PREFIX?

**Comment by ibell** [comment]
bump.  Can we close this issue?
