### ISSUE TITLE
Problem with inputs Density and Entropy to the PropsSI function

### ISSUE THREAD

**Issue by jzarzu** [CoolProp/CoolProp#439]
Hi! I am trying to calculate the Pressure using as inputs the Density and the Entropy and I get this error:

Warning: Inputs in Brent [171.050000,660.000000] do not bracket the root.  Function values are [-282.172348,-21.216202] 
Error using CoolPropMATLAB_wrap
Failure in function PropsSI.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(202,'_wrap_PropsSI',varargin{:});

Error in expanderB (line 90)
P_in_exp=CoolProp.PropsSI('P','D',d_in_exp,'S',s_su2_exp,fluid);

I am using the latest version of CoolProp...I thought it would work with these inputs

**Comment by jowr** [comment]
Which fluid do you use? Could you maybe post the whole call? `CoolProp.PropsSI('P','D',XXX,'S',YYY,ZZZ)`, what are the values for X,Y and Z?

**Comment by jowr** [comment]
Have you had a look at the consistency plots for your fluid in the documentation? D,S solvers might be unstable...

**Comment by jzarzu** [comment]
this is the call:
CoolProp.PropsSI('P','S',1409.8,'D',2527.3, R245fa)
[S]=J/mol/K
[D]=kg/m^3

**Comment by jowr** [comment]
Yes, looks like a bug. Maybe you  can try other inputs until we get around this issue...

**Comment by jzarzu** [comment]
I will have to use fsolve to calculate T and then use T as an input to calculate P (courtesy of your colleague Ian). Thanks anyway!! Please let me know when you fix it!

**Comment by ibell** [comment]
Looks like your entropy is too high, the temperature is above 660 K (1.5*Tc), so that's why you get this error.  Seems like you've got a bad input?

**Comment by ibell** [comment]
Input for S is out of range as hinted at by the error.  If I reduce S, I can get a solution.  For some reason your inlet entropy is way too high.

```python
In [10]: import CoolProp

In [11]: CoolProp.CoolProp.PropsSI('T','S',1409.8,'D',2527.3,'R245fa')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-2e911e0cfcd4> in <module>()
----> 1 CoolProp.CoolProp.PropsSI('T','S',1409.8,'D',2527.3,'R245fa')

C:\Miniconda\lib\site-packages\coolprop-5.0.7dev-py2.7-win-amd64.egg\CoolProp\CoolProp.pyd in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:15464)()

C:\Miniconda\lib\site-packages\coolprop-5.0.7dev-py2.7-win-amd64.egg\CoolProp\CoolProp.pyd in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:15267)()

C:\Miniconda\lib\site-packages\coolprop-5.0.7dev-py2.7-win-amd64.egg\CoolProp\CoolProp.pyd in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:13685)()

ValueError: Inputs in Brent [171.050000,660.000000] do not bracket the root.  Function values are [-283.152323,-21.819491] : PropsSI("T","S",1409.8,"D",2527.3,"R245fa")

In [12]: CoolProp.CoolProp.PropsSI('T','S',1009.8,'D',2527.3,'R245fa')
Out[12]: 573.2810534838972
```
