### ISSUE TITLE
TTSE range

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#44]
Make a smart function to determine TTSE ranges in all dimensions. Generate some nice plots in *ph* and *vT* and have a look at mixtures. 

For now, make one table per composition.

**Comment by jowr** [comment]
Maybe we should collect all issues in one place -> #262

**Comment by ibell** [comment]
Looks like the solution of using Tmax line to determine hmax is going to work fine, though it is not entirely clear what to do about the right edge of the h,p surface (at T=Tmax).  So I think for now that this issue can be considered closed by using maximum enthalpy along Tmax line.

One thing I still haven't figured out is what to do about if you want to change the reference state for enthalpy, but that's a detail we can deal with later on.  Basically I think that would force a new set of tables, which doesn't take too long, so the penalty is not too great.
