### ISSUE TITLE
High-Level API may raise an Exception

### ISSUE THREAD

**Issue by bungle** [CoolProp/CoolProp#441]
I have been building Lua wrapper for this library, but there are some faults in the API. It looks at least that `get_param_index` may raise C++ exception that is `undefined behavior` on C. 

Say I have this code:

```lua
local cp = require "coolprop"
print(cp.get_param_index("Error"))
```

I do get this and it will crash the Lua:

```
libc++abi.dylib: terminating with uncaught exception of type CoolProp::ValueError:
Your input name [Error] is not valid in get_parameter_index (names are case sensitive)
Abort trap: 6
```

So I think you need to fix this to make High-Level C API more robust.

On LuaJIT side I can catch this with `pcall` but I think that it will only work in some of the platforms.

Regards
Aapo

**Comment by bungle** [comment]
Same goes with `get_parameter_information_string`.

**Comment by ibell** [comment]
The functions in CoolProp.h are allowed to throw, but those in
CoolPropLib.h should not, and if they do, it is an error

**Comment by bungle** [comment]
Yes, all the functions I have been using are from `CoolPropLib.h`.

**Comment by ibell** [comment]
Right. Bug.  I'll take a look.
