### ISSUE TITLE
Julia Box-CoolProp Speed

### ISSUE THREAD

**Issue by 11718pauld** [CoolProp/CoolProp#447]
On using CoolProp in Juliabox, as per my code, the execution speed was 0.0009(~0.001).
Can we slightly have it faster, as my code involves around 1000 state variables with its added complexities to be solved by ODE solvers !
![untitled](https://cloud.githubusercontent.com/assets/10331330/6022302/ce3758ec-abe1-11e4-8b83-e6156517bc2f.png)

**Comment by jowr** [comment]
What can you propose? Do you have an idea how? If you need speed, use the state class instead of PropsSI. Why do you go via Python when there is a Julia wrapper and you care for speed?

**Comment by 11718pauld** [comment]
Julia version: 0.3.5 with Juliabox.
Julia wrapper requires v0.4. Hence, the problem.

**Comment by jowr** [comment]
Depending on where you are in the h,p domain, you can expect these times per call (us stands for microseconds):
![timecomp-hp-heos-water](https://cloud.githubusercontent.com/assets/769593/6022522/addcf35a-abbd-11e4-8a6a-8b0c3e8ab18f.jpg)

**Comment by jowr** [comment]
You measured 1 ms peer call, that should be OK for the high-level wrappers. It won't get much faster without direct access to C++.

**Comment by jowr** [comment]
In CoolProp4, we had the interpolation tables, which can get you down to 10 microseconds per call, but they have not been reimplemented for CoolProp5. If you really need speed now, go for http://github.com/ibell/coolprop .

**Comment by 11718pauld** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10331330/6081934/1e6e4a4c-ae43-11e4-996b-57af9ee2fb85.png)

**Comment by ibell** [comment]
Hard to say anything with one call.  Try a few thousand and then compare.
The precision of the timer is often on the order of 1ms,

**Comment by 11718pauld** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/10331330/6082341/c439dff6-ae46-11e4-841e-5c1420e41a68.png)

**Comment by jowr** [comment]
That seems to be an OK average time per call. You basically get the same results as posted above (slow in the subcooled liquid and fast in two-phase). What is the purpose of your postings? Do you have suggestions for how to speed things up?

**Comment by 11718pauld** [comment]
I dont have a suggestion, but I am seeking for an advice.
As, I have posted above, my system posses ~ 1000 State variables, and ode solvers are painfully slow. So, was wandering how to achive a faster way to get things going.

**Comment by jowr** [comment]
If you want speed, go for the abstract state class and make all your calls functions of temperature and density. You might also want to try the old CoolProp4. 
citing myself:
In CoolProp4, we had the interpolation tables, which can get you down to 10 microseconds per call [... or less], but they have not been reimplemented for CoolProp5. If you really need speed now, go for http://github.com/ibell/coolprop .

**Comment by 11718pauld** [comment]
Any help/examples for using abstract class?

**Comment by jowr** [comment]
http://coolprop.sourceforge.net/apidoc/CoolProp.CoolProp.html#CoolProp.CoolProp.AbstractState
and 
http://coolprop.sourceforge.net/_static/doxygen/html/class_cool_prop_1_1_abstract_state.html
should get you going.

Make yourself familiar with `generate_update_pair`, `get_parameter_index`, `keyed_output` and `state.update` and you should be in business.

**Comment by 11718pauld** [comment]
Thanx.
can you give me a sample of 
temperature = function(Pressure, Enthalpy) kind of a thing.
I then shall proceed with it.

**Comment by jowr** [comment]
I agree, documentation for this could be better... Would you be able to make some nice examples from your code? (if you actually end up using the state class...) 

Just from the top of my mind in Python notation:
```
import CoolProp.constants
from CoolProp.CoolProp import generate_update_pair,get_parameter_index,set_debug_level,get_phase_index
from CoolProp.CoolProp import AbstractState as State
state = State("HEOS","water")
Tcrit = state.keyed_output(CoolProp.constants.iT_critical)
# Sort the inputs! A pair has to be in the right order
pair, in1, in2 = generate_update_pair(CoolProp.constants.iP, 2e5, CoolProp.constants.iT, 300)
state.update(pair, in1, in2)
print state.keyed_output(CoolProp.constants.iDmass)
print state.rhomass()
# I know that the order is p,T
state.update(pair, 2e5, 320)
print state.keyed_output(CoolProp.constants.iDmass)
print state.rhomass()
```

**Comment by 11718pauld** [comment]
Yes, definitely, no problem regarding the same.
I shall try it with Julia (using PyCall maybe... as per your code.)

**Comment by 11718pauld** [comment]
http://www.coolprop.org/apidoc/CoolProp.constants.html
How can I get the Information regarding the allowable objects,
CoolProp.constants.iP
CoolProp.constants.iT
I tried, CoolProp.constants.iH for enthalpy, didn't work ! Any help

**Comment by jowr** [comment]
You noticed I wrote 'Dmass' and not 'D' right? Mass based enthalpy would be 'Hmass'... 
Parameters: https://github.com/CoolProp/CoolProp/blob/master/include/DataStructures.h#L41-L140
Input pairs: https://github.com/CoolProp/CoolProp/blob/master/include/DataStructures.h#L187-L227
Please try to have a look at the source code before you ask questions. I know docs could be better, but our time is very limited these days.

**Comment by ibell** [comment]
How's this going?

**Comment by 11718pauld** [comment]
Things to resume, as I come back from my leave.

On Friday, February 13, 2015, Ian Bell <notifications@github.com> wrote:
> How's this going?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/nuTkyeCibABR-90mnGKlw20P3ec-9TEITi7G8ZpHl6Yy2PYR31h6R-nRX5nDKBnPGxDQHG0ieF4DkrAlq92Lu9OkptW5YGCzU94-XSjWg2jR5G7RzZG6POj-TNc3VyWfZN1oEOim8FeujEonuHvKpz7XBTm6Ig=s0-d-e1-ft#https://github.com/notifications/beacon/AJ2kwiXR3rVnRa-yYjQP0JQkpG8ZDclrks5nrWZdgaJpZM4Da_34.gif
>

**Comment by JonWel** [comment]
From my personal testing, the speed difference between Python and the Julia Wrapper comes from the fact that python uses a C3 compiled code and that the daily build of the CoolProp library is not built with -O3.
A 10 000 call test to PropsSI("H", "T", 500., "P", 2.0e7, "Water"):
Python: 2.05 sec
Julia daily built: 3.07 sec
Julia built with -O3: 1.97 sec

I think the release version of the library is built with -O3.

**Comment by ibell** [comment]
@JonWel, that is interesting and is a bug if that is the case about building a debug version in the nightly build.  I would have no idea why that would be the case. Why do you think that is the case?

**Comment by ibell** [comment]
Seems like you were right @JonWel , I fixed the config and now the builds should be Release mode, thus -O2 optimization: https://github.com/CoolProp/CoolProp/commit/b6912e1e1c883f732fff05eb9789c0b56228569a

**Comment by ibell** [comment]
@JonWel can you run your speed tests again with the new Release mode shared libraries? They should be competitive with python wrapper, if not faster, now.

**Comment by JonWel** [comment]
Test with:
http://sourceforge.net/projects/coolprop/files/CoolProp/nightly/shared_library/Linux/64bit/ ~ 9s
http://sourceforge.net/projects/coolprop/files/CoolProp/5.0.7/shared_library/Linux/64bit/ ~ 9s
Pycall ~ 6s
Custom build with -O3 ~ 6s
(Theses 4 tests where made on economy saving mode thus the big difference in time compared to the previous test, I however time 3 time to be sure the numbers are stable, and always on same energy mode on one range of test).
So the speed difference is still there.
The size of the binary is also different (8,6 MO for the downloaded build, 3MO for the compiled).

**Comment by ibell** [comment]
Right, I fixed the release builds for linux, I didn't fully understand how to do release builds with CMake on non-visual studio builders

**Comment by ibell** [comment]
Now the shared library is ~3MB on ubuntu.  That should resolve the speed differences I hope.

**Comment by JonWel** [comment]
I realise that the sourceforge shared library are not up to date (2015-02-15 for nightly and  2015-02-11 for release).
Shouldn't the nightly build be updated more often?

**Comment by jowr** [comment]
The nightly builds are updated at 12:30 Central European Time, you can see a timestamp at the bottom of the download page:
![so_nightly](https://cloud.githubusercontent.com/assets/769593/6314055/e1ed7c02-b9cb-11e4-889c-b51e4c58923c.png)

... which is outdated. I'll have a look.

**Comment by jowr** [comment]
Nope, it was my browser cache, everything is up to date.

**Comment by JonWel** [comment]
I cleaned my browser cache and have now an up to date nightly library (of 2.9MB).
Now 1.85 sec (in performance mode with same test function) => shortest time I ever had => the speed issue with the shared library is fixed for the nightly build.

**Comment by ibell** [comment]
Cool, I think we can close this issue then.

**Comment by ibell** [comment]
Well, calling through the DLL, you have removed the python-layer overhead, but the string parsing overhead is still there.  I've thought about bringing back the IPropsSI function which would use only integers and allow for faster calling through the DLL, but that hasn't happened yet.

For now, I'm closing this issue.
