### ISSUE TITLE
Retrieving acentric factor through Props1SI fails

### ISSUE THREAD

**Issue by DanWBR** [CoolProp/CoolProp#448]
Using C# interface, calling Props1SI("1-Butene", "accentric") fails with an invalid identifier exception.

This is on v5.0.6, it was working fine on v4.

By the way, shouldn't it be called "acentric", with only one "c"? Also tried that and it failed. I've searched the documentation but didn't find anything helpful (a list of valid properties, for instance).

**Comment by ibell** [comment]
How about this:
http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function
?

And yes, seems accentric is missing for some reason.  I'll fix it.

And yes, it seems you are right about the spelling :)  Oops.

**Comment by DanWBR** [comment]
Hi Ian,

I found that table, but it contains the parameter list for PropsSI, not Props1SI...

I'll wait for the fix then. I'm currently updating the calls in DWSIM to use v5 and found this bug during initialization of the compound database.

Thanks!

**Comment by ibell** [comment]
Ah right, the possible inputs to Props1SI are the trivial inputs, those
that don't require any information about the state.  I'm fixing the
acentric bug right now.

If you are are using Csharp, you might want to consider using the abstract
state classes added in v5.  It's much faster!

Ian

**Comment by ibell** [comment]
This one is fixed, if there are others let us know.
