### ISSUE TITLE
Excel Refer to a cell as input data

### ISSUE THREAD

**Issue by malloot** [CoolProp/CoolProp#449]
Hey

I'm just starting to use Coolprop and have a question i hope can be answered. I use Excel as a wrapper.

I want to refer to a value in a cell as input to a formula from Coolprop. 
so lets say i have 328 as input in A2 and have this formula
=PropsSI("P";"T";328;"Q";0;"HEOS::R600") This works fine
=PropsSI("P";"T";A2;"Q";0;"HEOS::R600") does not work and gives #VALUE

Is there a way to make these kinds of referral's work to make a more workable worksheet as having all the data hidden behind the cells makes it hard to check if all the input is correct and hard to edit if needed. 

Thanks in Advance for any awnser

**Comment by ibell** [comment]
Is there anything else in your workbook?  That should definitely work!
Excel is problematic because the order of evaluation of cells is undefined

**Comment by malloot** [comment]
Hmm, thats very weird i tried it on a empty sheet and it worked.

Will have to fix my sheet then, thanks allot for your reply and the hard work you have done on Coolprop!
