### ISSUE TITLE
Calling PropsSI to get thermal conductivity throws an exception

### ISSUE THREAD

**Issue by DanWBR** [CoolProp/CoolProp#450]
Call:

PropsSI("L","T", 215, "P", 101325, "R14")

Throws:

System.ApplicationException was unhandled by user code
  HResult=-2146232832
  Message=_phase is unknown
  Source=CoolPropInterface
  StackTrace:
       CoolProp.PropsSI(String Output, String Name1, Double Prop1, String Name2, Double Prop2, String FluidName) na c:\Users\Daniel\Documents\Visual Studio 2013\Projects\DWSIM3\CoolPropInterface\source\CoolProp.cs:line 99

This is with the latest nightly build.

**Comment by ibell** [comment]
Hmm that should probably be an error, not an exception. I'll take a look.

**Comment by ibell** [comment]
Or maybe not.  CoolProp functions are now allowed to throw exceptions in c#
(and other swig wrappers), in order to facilitate error bubbling.

**Comment by DanWBR** [comment]
Yes, this was thrown by CoolProp.cs at line 99.

**Comment by ibell** [comment]
Hmm, perhaps this is because the temperature of R14 results in a temperature for the reference fluid in ECS (R134a I believe), this is out of range.  The error message certainly could be more useful !

**Comment by ibell** [comment]
Bug, it gets the density, viscosity, fine, but not the conductivity.  Thanks for the report.
 
``` python
In [3]: CoolProp.CoolProp.PropsSI("D","T", 215, "P", 101325, "R14")
Out[3]: 5.043445303076324

In [4]: CoolProp.CoolProp.PropsSI("C","T", 215, "P", 101325, "R14")
Out[4]: 566.0670728568936

In [5]: CoolProp.CoolProp.PropsSI("V","T", 215, "P", 101325, "R14")
Out[5]: 1.2816089795803069e-05

In [6]: CoolProp.CoolProp.PropsSI("L","T", 215, "P", 101325, "R14")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-589d6979f195> in <module>()
----> 1 CoolProp.CoolProp.PropsSI("L","T", 215, "P", 101325, "R14")

C:\Miniconda\lib\site-packages\coolprop-5.0.7dev-py2.7-win-amd64.egg\CoolProp\CoolProp.pyd in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:16127)()

C:\Miniconda\lib\site-packages\coolprop-5.0.7dev-py2.7-win-amd64.egg\CoolProp\CoolProp.pyd in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:15930)()

C:\Miniconda\lib\site-packages\coolprop-5.0.7dev-py2.7-win-amd64.egg\CoolProp\CoolProp.pyd in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:14348)()

ValueError: _phase is unknown : PropsSI("L","T",215,"P",101325,"R14")
```
