### ISSUE TITLE
PropsSI function gives wrong values for enthalpy and entropy of Ammonia

### ISSUE THREAD

**Issue by ziSo12** [CoolProp/CoolProp#451]
Ammonia at saturated liquid point (T: 243.15 K (-30 °C) and Quality: 0) gives (Source: Excel Addin and Coolprop online):
H (enthalpy) : *206757* J/kg
S(entropy):    *944.6* J/kgK
I have 3 sources (CoolPack, VDI heat atlas, ammonia table in a book)  that say enthalpy and entropy at this saturation point should be around the following values:
H: *63600 - 64640* J/kg
S: *473 - 477* J/kgK

Entropy looks like the coolprop-result is double the value it should be.
I tried using calculation by density and by pressure. The result is the same. 
All the other properties of Ammonia seem to be correct at this point.

Thanks in advance.

**Comment by jowr** [comment]
Enthalpy and entropy have arbitrary values, it is the difference that matters. Either check delta h and delta s between two points or make sure that you use the same reference points.

**Comment by ziSo12** [comment]
Thank you for your answer. I didn't think of that.
The differences are correct, indeed!
Can u explain, why the values are arbitrary though?

**Comment by jowr** [comment]
As explained in http://coolprop.sourceforge.net/apidoc/CoolProp.CoolProp.html#CoolProp.CoolProp.set_reference_state , we use three different reference points. Those points are defined to standardise calculations and to reduce confusion. You could also choose 0 Kelvin and 0 Pa as a reference point, but then you would end up having to deal with huge numbers for enthalpy and entropy.
