### ISSUE TITLE
New user: unable to use Props1 and HAProps in Excel

### ISSUE THREAD

**Issue by fluenthair** [CoolProp/CoolProp#453]
Dear developers, 
I'm a new CoolProp user and after having downloaded it and added it into Microsoft Excel, and using the sintax specified, I noticed the following facts:
- Props function isn't in SI units, in fact pressure is given in kPa;
- Props1 and HAprops don't work (their outputs are "VALUE!")

Are they common issues?
Thank you all for your attention.
Best regards.

**Comment by jowr** [comment]
Hi, for SI units, use `PropsSI`. I do not know much about the other problems, I never used Excel myself, sorry.

**Comment by fluenthair** [comment]
Ok thanks. I think that these problems are maybe only related on the Excel package CoolProp.xlam .

**Comment by ibell** [comment]
Yes, the Props1 function and HAProps functions are relics of v4, you should
use Props1SI and HAPropsSI as @jowr recommends.
