### ISSUE TITLE
Add density dependency to entropy and enthalpy of incomprerssible fluids

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#454]
The current version does not include the density terms for the entropy and enthalpy calculation for **incompressible** fluids. They should be added even though their contribution is very limited. Terms to implement: 

  - [x] ![dsEquation](http://www.sciweavers.org/tex2img.php?eq=ds%20%3D%20cT%5E%7B-1%7D%20dT%20%2B%20%5Cunderbrace%7B%5Crho%5E%7B-2%7D%20%5Cleft%28%20%5Cfrac%7B%5Cpartial%20%5Crho%7D%7B%5Cpartial%20T%7D%20%5Cright%29_p%20dp%7D_%7B%5Ctext%7Bcurrently%20missing%7D%7D&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)

  - [x] ![dhEquation](http://www.sciweavers.org/tex2img.php?eq=dh%20%3D%20c%20dT%20%2B%20%5Crho%5E%7B-1%7D%20%5CBigg%28%201%20%2B%20%5Cunderbrace%7BT%20%5Crho%5E%7B-1%7D%20%5Cleft%28%20%5Cfrac%7B%5Cpartial%20%5Crho%7D%7B%5Cpartial%20T%7D%20%5Cright%29_p%7D_%5Ctext%7Bcurrently%20missing%7D%20%5CBigg%29%20dp&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)

  - [x] d(Umass)/d(T)|P
  - [x] d(Hmass)/d(T)|P
  - [x] d(Hmass)/d(P)|T
  - [x] d(Dmass)/d(T)|P
  - [x] d(Smass)/d(T)|P
  - [x] d(Smass)/d(P)|T
  - [x] Invert the calculation of u and h (now u(h), before h(u))
  - [x] Fix the reference state update procedure.
  - [x] Don't forget to update the the docs.

**Comment by jowr** [comment]
I do not know, what is wrong with the equations, but here are the first one should read: <img src="http://www.sciweavers.org/tex2img.php?eq=dh%20%3D%20%5Cleft%28%20%5Cfrac%7B%5Cpartial%20u%7D%7B%5Cpartial%20T%7D%20%5Cright%29_v%20dT%20%2B%20%20%5Cbigg%28%20v%20-%20%5Cunderbrace%7BT%20%5Crho%5E%7B-2%7D%20%5Cleft%28%20%5Cfrac%7B%5Cpartial%20%5Crho%7D%7B%5Cpartial%20T%7D%20%5Cright%29_p%7D_%5Ctext%7Bcurrently%20missing%7D%20%5Cbigg%29%20dp%20&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0" align="center" border="0" alt="dh = \left( \frac{\partial u}{\partial T} \right)_v dT +  \bigg( v - \underbrace{T \rho^{-2} \left( \frac{\partial \rho}{\partial T} \right)_p}_\text{currently missing} \bigg) dp " width="340" height="71" />

**Comment by jowr** [comment]
Sorry for the mess with the equations, but GitHub some how caches images.

**Comment by jowr** [comment]
Don't forget to 

  - [ ] Update the the docs.

**Comment by jowr** [comment]
I think this should be done by implementing the partial derivative functions. It might be slightly less efficient, but we can expose the derivatives to the users as a additional benefit. 
  - [ ] d(Umass)/d(T)|Dmass
  - [ ] d(Hmass)/d(T)|P
  - [ ] d(Hmass)/d(P)|T
  - [ ] d(Dmass)/d(T)|P
  - [ ] d(Smass)/d(T)|P

and probably some more.

**Comment by ibell** [comment]
Is this a 5.0.7 target? I think 5.0.7 is ready.

**Comment by jowr** [comment]
Ok, I'll move it to wishlist because the contribution is very minor (dp of 1 bar equals a dT of 0.025 K)...

**Comment by jowr** [comment]
I made some calculations, the difference is up to 2% for entropy, I implemented it and update the docs now...
