### ISSUE TITLE
HS Inputs in PropsSI function working in two-phase region?

### ISSUE THREAD

**Issue by somniumAeternam** [CoolProp/CoolProp#455]
I tried to calculate the pressure with enthalpy and entropy as inputs für CO2 in CoolProp 5.0.6:

> PropsSI('P','H',310000,'S',1400,'R744')

which gives:
>ValueError: saturation_PHSU_pure solver did not converge after 50 iterations for Hmolar=13643 current error is 7.11139 : PropsSI("P","H",310000,"S",1400,"R744")

These values will be in the two-phase region. I read a couple of months ago, that HS inputs only work in the single phase region. Can you confirm this or should it also work in the two-phase region?

**Comment by ibell** [comment]
Is it only that state point or all state points?  In principle two-phase HS inputs should work now.  You might be close to critical values, which cause problems.

**Comment by somniumAeternam** [comment]
I have just tested a wide range of input values right in the middle of the two-phase region of CO2 (pressure between 30 and 55 bar, entropy between 1200 and 1600 J/kgK). I calculated the minimum and maximum enthalpy for each entropy with PS as inputs. Everything below an entropy of 1600 leads to some errors. The lower the entropy the more errors occur. Everything below an entropy of about 1470 only leads to errors.

The command:
>PropsSI('P','H',325125,'S',1470,'R744')

leads to the strange error:
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp\CoolProp.pyx", line 204, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:15824)
  File "CoolProp\CoolProp.pyx", line 236, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:15619)
  File "CoolProp\CoolProp.pyx", line 173, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:14440)
ValueError: p is not a valid number : PropsSI("P","H",325125,"S",1470,"R744")

**Comment by ibell** [comment]
Can you show your code?  I think you might be evaluating solid inputs
sometimes?

**Comment by somniumAeternam** [comment]
I added a condition for the right phase. Here is the Python-code:

```python
from CoolProp.CoolProp import PhaseSI
from CoolProp.CoolProp import PropsSI
import numpy as np

s = np.arange(1200,1600,10)
p = np.arange(30*10**5,55*10**5,1*10**5)

counter = 0
error = 0

h = np.zeros(p.size)

for i in np.arange(s.size):
    for j in np.arange(p.size):
        h[j] = PropsSI('H','P',p[j],'S',s[i],'R744')
    
    if PhaseSI('P',p[j],'S',s[i],'R744') == u'twophase':   
        for k in np.arange(h.size):
            try:            
                print(PropsSI('P','H',h[k],'S',s[i],'R744'))
                counter += 1
            except:
                print('Error')
                error += 1
 
print('Correct: '+str(counter))
print('Errors: '+str(error))
```
By the way, is there a page in the documentation with the reference states for enthalpy and entropy?

**Comment by ibell** [comment]
I'd recommend a few small changes to your script, but yes, it does seem to result in quite a few failures. I'm about to embark on #262, it might be a while before I can take a look :(

``` python
from __future__ import print_function

from CoolProp.CoolProp import PhaseSI, PropsSI
import numpy as np

s = np.arange(1200,1600,10)
p = np.arange(30e5,55e5,1e5)

counter = 0
error = 0

h = np.zeros(p.size)

for i in np.arange(s.size):
    for j in np.arange(p.size):
        h[j] = PropsSI('H','P',p[j],'S',s[i],'R744')

    if PhaseSI('P',p[j],'S',s[i],'R744') == u'twophase':   
        for k in np.arange(h.size):
            try:            
                print(PropsSI('P','H',h[k],'S',s[i],'R744'))
                counter += 1
            except BaseException as BE:
                print('Error', BE)
                error += 1

print('Correct: '+str(counter))
print('Errors: '+str(error))
```
