### ISSUE TITLE
Slave alert

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#456]
quoting @ibell: We might want to consider setting up emailing if the slave goes down: http://docs.buildbot.net/latest/manual/cfg-buildslaves.html#when-buildslaves-go-missing

**Comment by ibell** [comment]
Added the code, but it doesn't seem to fire, there is no warning in the twist.log suggesting that it tried to send an email.  We need some jowr-fu.

**Comment by ibell** [comment]
Thanks!  Wasn't a complex fix in the end...
