### ISSUE TITLE
PropsSI ("Q", "P", valueP, "H", valueH, "R410A") return -1 for liquid phasis and for vapour phasis

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#458]
Examples :
PropsSI ("Q", "P", 600000, "H", 200000, "R410A")  = -1 (liquid phasis) => NOK
PropsSI ("Q", "P", 600000, "H", 300000, "R410A")  = 0.4633 (liquid+vapour phasis) => OK
PropsSI ("Q", "P", 600000, "H", 400000, "R410A")  = 0.9381 (liquid+vapour phasis) => OK
PropsSI ("Q", "P", 600000, "H", 500000, "R410A")  = -1 (vapour phasis) => NOK

**Comment by ibell** [comment]
A quality value that is not in between 0 and 1 is a homogeneous state point.

**Comment by pmanach** [comment]
OK
