### ISSUE TITLE
PropsSI ("Q", "P", valueP, "H", valueH, "REFPROP-R410A") only return 0

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#460]
Examples :
PropsSI ("Q", "P", 600000, "H", 200000, "REFPROP-R410A") = 0 (liquid phasis) => NOK
PropsSI ("Q", "P", 600000, "H", 300000, "REFPROP-R410A") = 0 (liquid+vapour phasis) => NOK
PropsSI ("Q", "P", 600000, "H", 400000, "REFPROP-R410A") = 0 (liquid+vapour phasis) => NOK
PropsSI ("Q", "P", 600000, "H", 500000, "REFPROP-R410A") = 0 (vapour phasis) => NOK

**Comment by ibell** [comment]
That might be a bug in REFPROP.  I'll take a look.
