### ISSUE TITLE
Links to doxygen still point to buildbot master

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#463]

**Comment by ibell** [comment]
Doh.  I'll try again, I thought I had fixed that...

**Comment by ibell** [comment]
This commit (251f7fecf8935131e91a7340b6907f79497a5e6c) unfixed it, I'm on it.

**Comment by jowr** [comment]
Sorry, but that was not the problem. There is a general flaw somewhere else. The issue is that `:cpapi:` points to the wrong place. I think it was OK to use that command there since CoolProp.h is a good point to start browsing the doxygen pages. I'll try to have a look.

**Comment by ibell** [comment]
Ah, right, now I understand.  I hadn't checked any of the cpapi links.
Its in conf.py, I'm about to go to bed, I can fix it when I wake up too...

**Comment by jowr** [comment]
Sleep well, it might be fixed when you wake up :-)
