### ISSUE TITLE
Consider evaluating water at Tdb,p for transport properties in humid air

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#470]

**Comment by MrMatt2532** [comment]
In some cases, especially low temperature moist air, you will be evaluating the transport properties of liquid water/ice, which I don't think you want. I think in these cases, you need to evaluate at the dry bulb temperature and the saturation pressure.

**Comment by ibell** [comment]
That's an excellent point that I didn't think about.  I think this issue
needs to be revisited.  Or, we use the water *partial* pressure instead of
the total pressure.  That might do it.

**Comment by MrMatt2532** [comment]
Right, I too have considered the approach you mentioned. I think either way would get you close to what want and need. However, I'm not 100% sure which is more rigorously correct. If you learn any further theory, I would be interested, thanks.

**Comment by MrMatt2532** [comment]
Can you explain why you went back to the old formulation? As a first approximation, the steam transport properties should be a function of temperature only, so why not a function of QT (instead of PQ)?

**Comment by MrMatt2532** [comment]
There is a formulation for evaluating transport properties of humid air described in the following papers:

Herrmann, Sebastian, et al. "Properties of Humid Air for Calculating Power Cycles." Journal of Engineering for Gas Turbines and Power 132.9 (2010): 093001.
with most of the detail in the following report:
Herrmann, S., et al. "Determination of Thermodynamic and Transport Properties of Humid Air for Power-Cycle Calculations." Physikalisch-Technische Bundenanstalt, Chemische Physik, PTB-CP-3 (Braunschweig, 2009), ISBN-978-3-86509-917-4 (2009).

Prior to throwing the air and water properties into the transport mixture formula (note they are using a more advanced mixture formula than you are using), they appear to be evaluating the water properties in the following way: 
1) when superheated water vapor, evaluated as function of (p, T)
2) when not superheated vapor, evaluate at a given temperature and the saturation vapor pressure, with a correction term to account for the pressure effects. Basically, I am seeing k = k(T, rho_sat) + k(T_ref, rho) - k(T_ref, rho_sat) where k is a transport property function as a function of (T, p) and T_ref = 650 K which is a few degrees higher than the critical point.

As a first approximation, to me it seems you should do something very similar:
if (superheated water vapor)
k = k(p, T)
else
k = k(p_sat(vapor), T)

**Comment by ibell** [comment]
Fortunately I have both papers in my possession.  Unfortunately, the
transport properties of humid air are not too high on my list of
priorities.  So if you wanted to take the lead on this, it's all yours.
I'm content for the moment to have mostly working code.

I would want to see some experimental data before I worried too much about
which method we selected.
