### ISSUE TITLE
Crash in Julia when invalid temperature range

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#477]
When I execute in Python, I have a nice message explaining the problem while with the Julia wrapper it crash:

Python:

    julia> using PyCall

    julia> @pyimport CoolProp.CoolProp as CoolProp

    julia> CoolProp.PropsSI("S", "T", 700., "Q", 0., "Water")
    ERROR: PyError (:PyObject_Call) <type 'exceptions.ValueError'>
    ValueError('Temperature to QT_flash [700 K] must be in range [273.16 K, 647.096 K] : PropsSI("S","T",700,"Q",0,"Water")',)
      File "CoolProp.pyx", line 204, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:15306)
      File "CoolProp.pyx", line 278, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:15109)
      File "CoolProp.pyx", line 173, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:13679)

     in pyerr_check at /home/jonwel/.julia/v0.3/PyCall/src/exception.jl:58
     in pycall at /home/jonwel/.julia/v0.3/PyCall/src/PyCall.jl:91
     in fn at /home/jonwel/.julia/v0.3/PyCall/src/conversions.jl:181

    julia>

Julia Wrapper:

    julia> import CoolProp

    julia> CoolProp.PropsSI("S", "T", 700., "Q", 0., "Water")

    signal (6): Abandon
    gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    _Unwind_Resume at /lib/x86_64-linux-gnu/libgcc_s.so.1 (unknown line)
    _ZN8CoolProp16_PropsSI_outputsERNSt3tr110shared_ptrINS_13AbstractStateEEESt6vectorINS_16output_parameterESaIS6_EENS_11input_pairsERKS5_IdSaIdEESD_RS5_ISB_SaISB_EE at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    _ZN8CoolProp13_PropsSImultiERKSt6vectorISsSaISsEERKSsRKS0_IdSaIdEES6_SA_S6_S4_SA_RS0_IS8_SaIS8_EE at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    _ZN8CoolProp7PropsSIERKSsS1_dS1_dS1_ at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    PropsSI at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    PropsSI at /home/jonwel/.julia/v0.3/CoolProp/src/CoolProp.jl:14
    Abandon (core dumped)
    jonwel@PC:~$ 

Done under Ubuntu 14.10 64bit with last CoolProp library compiled from github.
Preventing this crash would allow to add error handling with the Julia wrapper.

**Comment by ibell** [comment]
Perhaps Julia doesn't understand infinity?  That is the return value if
there is an error, and maybe Julia thinks that is an error?  Or maybe it is
a real crash.

**Comment by JonWel** [comment]
Julia has an infinity value, but maybe not the same.
I'll look deeper in this direction, thanks for the idea.

**Comment by ibell** [comment]
Looking at that traceback, it seems there is a different problem.  What if
you call the so with invalid inputs from python?  That looks very much like
an uncaught exception

What version of julia?  OS?

**Comment by JonWel** [comment]
I done the test with Julia 0.3 and 0.4 with the same error.
I compiled the library from the GitHub on my computer with Ubuntu 14.10 (October 2014) 64 bit with -O3 -DNDEBUG -march=native -mtune=native.
I'll check again with the nightly build (to be sure).
I'll check to load the library from python directly to see the result.

**Comment by ibell** [comment]
I confirm this error in Julia.  I'm not at all sure why this is happening.  It should catch the exception, and return HUGE, but something is going wrong.

**Comment by ibell** [comment]
This seems like a Julia related issue.  When I try the shared library in python, it works:

``` python
from ctypes import *

CoolProp = cdll.LoadLibrary('/home/ian/Code/coolprop/build/so/CoolProp.so')

PropsSI = CoolProp.PropsSI
PropsSI.restype = c_double

print PropsSI(c_char_p("T"), c_char_p("P"),c_double(101325),c_char_p("Q"),c_double(1.0),c_char_p("Water"))
print PropsSI(c_char_p("T"), c_char_p("P"),c_double(-101325),c_char_p("Q"),c_double(1.0),c_char_p("Water"))
print PropsSI(c_char_p("P"), c_char_p("T"),c_double(700),c_char_p("Q"),c_double(1.0),c_char_p("Water"))
```
yields
```
373.124295848
inf
inf
```

**Comment by ibell** [comment]
I think it is a julia bug: https://github.com/JuliaLang/julia/issues/10273

**Comment by JonWel** [comment]
I experience the same behaviour than you when calling in python.
The problem seems to be Julia related (and present in Julia 0.3 and 0.4).

**Comment by ibell** [comment]
Confirmed bug in Julia ppa; Resolution is indeterminate

**Comment by JonWel** [comment]
Corrected for Julia 0.4 nightly build.
Still crash for Julia 0.3 ubuntu ppa.

**Comment by JonWel** [comment]
It seems it was also the cause to the bad behaviour of Props1SI(const char *FluidName, const char* Output) with any values (correct or not):

Julia 0.4 with corrected ppa:

    julia> importall CoolProp

    julia> Props1SI("Water", "Tcrit")
    647.096

    julia> Props1SI("Tcrit", "Water")
    647.096

    julia> Props1SI("Water", "Tcri")
    ERROR: CoolProp:Unable to use input parameter [Tcri] in Props1SI for fluid Water; error was Output parameter parsing failed; error: Output string is invalid [Tcri] : PropsSI("Tcri","",0,"",0,"Water")
     in error at error.jl:20
     in PropsSI at /home/johndoe/.julia/v0.4/CoolProp/src/CoolProp.jl:32

Julia 0.3 with still faulty ppa:

    julia> importall CoolProp

    julia> Props1SI("Water", "Tcrit")

    signal (6): Abandon
    gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    _Unwind_Resume at /lib/x86_64-linux-gnu/libgcc_s.so.1 (unknown line)
    _ZN8CoolProp19HelmholtzEOSBackendC1ERKSs at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    _ZN8CoolProp13AbstractState7factoryERKSsRKSt6vectorISsSaISsEE at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    _ZN8CoolProp13AbstractState7factoryERKSsRKSt6vectorISsSaISsEE at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    _ZN8CoolProp13AbstractState7factoryERKSsS2_ at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
   _ZN8CoolProp21is_valid_fluid_stringERSs at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
   _ZN8CoolProp8Props1SIERKSsS1_ at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    Props1SI at /usr/bin/../lib/x86_64-linux-gnu/julia/CoolProp.so (unknown line)
    PropsSI at /home/johndoe/.julia/v0.3/CoolProp/src/CoolProp.jl:30
    jlcall_PropsSI_20229 at  (unknown line)
    jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
    unknown function (ip: 1789087048)
    unknown function (ip: 1789083577)
    unknown function (ip: 1789152253)
    jl_f_top_eval at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
    eval_user_input at REPL.jl:53
    jlcall_eval_user_input_20159 at  (unknown line)
    jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at task.jl:95
    jl_handle_stack_switch at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
    julia_trampoline at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
    unknown function (ip: 4199613)
    __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
    unknown function (ip: 4199667)
    unknown function (ip: 0)
    Abandon (core dumped)

This error is solved with the corrected ppa, so I'll add the ´Props1SI´ function to the wrapper.

**Comment by ibell** [comment]
Ok, this issue is closed(ish) now

**Comment by JonWel** [comment]
Both ppa are now fixed:
0.3.6-depsfix9-utopic
0.4.0-1955~ubuntu14.10.1

Both handle error correctly now.
