### ISSUE TITLE
RelativeHumidity simplification

### ISSUE THREAD

**Issue by mikekaganski** [CoolProp/CoolProp#479]
In HumidAirProp.cpp, the RelativeHumidity() is defined quite verbosely, but actually it is simply the equation
R=p_w/p_s
where
p_w = psi_w*p.

Currently the partial water pressure is calculated using this:
p_w = W/epsilon * p/(1+W/epsilon),
and
W = psi_w * epsilon/(1-psi_w)
so
p_w = psi_w * ~~epsilon~~/(1-psi_w)/~~epsilon~~ * p/(1+psi_w * ~~epsilon~~/(1-psi_w)/~~epsilon~~) = psi_w * p /((1-psi_w) * (1+psi_w/(1-psi_w))),
and the divisor simplifies to this:
(1-psi_w) * (1+psi_w/(1-psi_w)) = 1-psi_w + ~~(1-psi_w)~~*psi_w/~~(1-psi_w)~~ = 1 - ~~psi_w~~ + ~~psi_w~~ = 1.

So, finally we reached the equation p_w = psi_w*p. But why so wordy? I'm not sure if the compiler simplifies all the code (including HumidityRatio() call) to produce this simple form.

So, I suggest to rewrite the RelativeHumidity() like this:

```c++
double RelativeHumidity(double T, double p, double psi_w) 
{ 
    double p_ws, f, p_s; 
    if (T >= 273.16){ 
        // Saturation pressure [Pa] 
        Water->update(CoolProp::QT_INPUTS, 0, T); 
        p_ws = Water->keyed_output(CoolProp::iP); //[Pa] 
    } 
    else{ 
        // sublimation pressure [Pa] 
        p_ws = psub_Ice(T); 
    } 
    // Enhancement Factor [-] 
    f = f_factor(T,p); 

    // Saturation pressure [Pa] 
    p_s = f*p_ws; 

    return psi_w*p/p_s; 
} 
```

**Comment by ibell** [comment]
There are, as I have learned, actually multiple definitions for the relative humidity.  But using our definition, yes, your way make way more sense and I wonder why it wasn't defined that way from the outset.
