### ISSUE TITLE
Ideal gasses and ideal mixtures backend

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#480]
@LeonardoPierobon suggested to include ideal gasses and ideal mixtures. The idea is to provide means of calculating combustion processes in gas turbines and gasifiers. The gasses behave almost like an ideal gas and including a new backend should not affect the rest of the architecture. Leonardo and me are going to look into that in May, but it would be nice to have a little discussion going here before that.

**Comment by ibell** [comment]
Yes, I very much like this idea.  While you are at it, how about a cubic
backend that uses SRK or VdW for mixtures?  That would be a useful addition.

**Comment by jowr** [comment]
Hehe, while I am at it... Yes, I agree that it would be useful.

**Comment by LeonardoPierobon** [comment]
Hi guys,

I personally believe that adding the ideal-mixture-of-gases feature would add a lot to the already large capabilities of Coolprop. After my period at TU Delft is over, I will sit down with Jorrit and hopefully we will get it done.

**Comment by ibell** [comment]
Might be a nice collaboration with RUB.  They've done a lot of that work
already.

**Comment by ibell** [comment]
Ok, so what is the scope of this? Are we considering just f(T,P), or other flashes as well?

**Comment by jowr** [comment]
Well, I would also consider f(H,P) simply because it is so frequently used, but it doesn't have to be part of the first version of this backend...

**Comment by thorade** [comment]
ThermoC has a lot of equations of state implemented:
http://thermoc.uni-koeln.de/thermoc/eos/eos.html
For inspiration what can be done after Helmholtz, ideal gas, VdW and RKS...

**Comment by ibell** [comment]
Any chance

a) those guys are interested in collaborating with us
b) you want to work with Leonardo and @jowr on this?

**Comment by thorade** [comment]
I believe ThermoC is mainly used as a demonstrator of their published algorithms.
http://www.uni-koeln.de/math-nat-fak/phchem/deiters/indexE.html
One would have to ask them what they are really interested in.

**Comment by ibell** [comment]
Are you interested in being a go-between between us and them about
ThermoC?  It would be great if we could not reinvent the wheel.

**Comment by thorade** [comment]
Eric knows Prof. Deiters, maybe he is a better contact person? I can of course try and make them aware of CoolProp (in case they are not already). One would have to discuss what they can win, and what CoolProp would win.

**Comment by thorade** [comment]
For cubic EoS, there is a good introduction in the book by Baehr (in German):
https://books.google.de/books?id=VrsiBgAAQBAJ&pg=PA194

**Comment by ibell** [comment]
I've been to Cologne to speak with Prof. Deiters.  For other reasons, we are going to be implementing SRK in the near future.  I'm thinking in the next month or so it will be more or less completed.  Which will be very, very nice.  

Already, we have SRK translations to Helmholtz energy to replace fluids in the mixture model, but this is going to be a complete implementation, including composition derivatives.

**Comment by ibell** [comment]
@LeonardoPierobon @jowr do you have any docs on how one would go about implementing this?  Doesn't sound too bad I think, but don't know where to start.

**Comment by LeonardoPierobon** [comment]
Hi Ian,

I can share with you a FORTRAN script programmed at the Department of Chemical Engineering, DTU for solving problems related to phase-equilibrium. The script contains also the implementation of EOS, SRK and Peng-Robinson.

I hope it helps.

**Comment by ibell** [comment]
OK, we can close this issue since I have done the derivations for the cubics at NIST and implemented them into CoolProp.  A cubic EOS backend (covering SRK and PR) is taking shape.
