### ISSUE TITLE
A bug is found when pressure approximates Critical Pressure for Air

### ISSUE THREAD

**Issue by Haobai-Xue** [CoolProp/CoolProp#481]
Dear Ian Bell, 
I feel very sorry to trouble you since I know you're very busy. But I think I might have found some bugs about CoolProp at Critical Pressure. For example, with CoolProp Online, if we try:
P = 3748006.75,      S = 3258.16089,      Working Fluid = 'Air'
P = 3749006.75,      S = 3258.16089,      Working Fluid = 'Air'
P = 3750006.75,      S = 3258.16089,      Working Fluid = 'Air'
We will find that the middle combination returns an "Internal Error", while the rest two combinations will return the correct results, although the pressure difference of the three cases is insignificant. I'm afraid it's not only the bug of CoolProp Online, but also that of the latest version (5.207) of CoolProp, because I've tested with it and it returns "Infinity" as the result. We have also tested it with the previous version (4.2) of CoolProp and it returns the correct answer. Since the pressure 37 bar is very close to the Critical Pressure of Air, so perhaps the latest version of Coolprop is not very robust at those points.
Similar results are found with the combinations:
P = 3744213.00,      T = 385.545654,      Working Fluid = 'Air'
P = 3754213.00,      T = 385.545654,      Working Fluid = 'Air'
P = 3794213.00,      T = 385.545654,      Working Fluid = 'Air'
And we could find that the middle one couldn't work properly.
I'm wondering would you mind helping us with those problems? Thank you very much! 
I'm looking forward to your reply.
Yours,
Haobai Xue

**Comment by JonWel** [comment]
I experience the same problem.
The shared library and python returns the following code:
```
CoolProp: Residual function in secant returned invalid number : PropsSI("H","T",673.15,"P",3783521.691,"Air")
```

**Comment by ibell** [comment]
Seriously, why does everyone like hanging out in the critical region, its
not a cool place to be...  I'll see if I can come up with a robust solution
for this, we have some other tests that fail as well.

**Comment by JonWel** [comment]
My personal  workaround is in deed to never go under 40 bar.
However the temperature used are far from the critical point (and I really have to avoid being near as I don't want some liquid air), so I can imagine that this instability near the "critical line" is not so pleasant.

**Comment by speredenn** [comment]
@ibell : Critical region is useful for ORC systems ;-) ; no surprise that some people try to hang out there :-)

**Comment by Haobai-Xue** [comment]
When a cavern is charging or discharging, the pressure changes 
continuously from 25 bar to 100 bar, so the critical region (37 bar) is 
somewhere inevitable.

**Comment by ibell** [comment]
Ok, ok, I get the point :) It's moving up the list of things to do.

**Comment by ibell** [comment]
Now all these points work:
``` python
import CoolProp, matplotlib.pyplot as plt, numpy as np
tt = []
for p in np.logspace(np.log10(3649006.75), np.log10(3849006.75), 1000):
    tt.append(CoolProp.CoolProp.PropsSI('D','T',300,'P',p,'Air'))
plt.plot(tt)
plt.yscale('log')
plt.show()
```

**Comment by JonWel** [comment]
There seems to be a similar error with PS inputs (maybe every couples with P?):
`Residual function in secant returned invalid number : PropsSI("H","P",3760000,"S",4000,"Air")`

**Comment by ibell** [comment]
Right, I'll take a look tomorrow.

**Comment by ibell** [comment]
Ok, that point at least is working again.  I think there still might be a tiny region in the critical region that is problematic.  I have a discussion tomorrow to see if there is a good resolution.
