### ISSUE TITLE
Performance: double map lookup

### ISSUE THREAD

**Issue by mikekaganski** [CoolProp/CoolProp#482]
src\Backends\Helmholtz\MixtureParameters.cpp 

```c++
bool is_predefined_mixture(const std::string name, Dictionary &dict){
    if (predefined_mixtures_library.predefined_mixture_map.find(name) != predefined_mixtures_library.predefined_mixture_map.end()){
        dict = predefined_mixtures_library.predefined_mixture_map[name];
        return true;
    }
    else{
        return false;
    }
}
```
Currently, two searches are performed here when the name is predefined: one to check for existence (calling method find()), one to return value (calling operator []). I propose this change to do it only once:

```c++
bool is_predefined_mixture(const std::string name, Dictionary &dict){
    std::map<std::string, Dictionary>::iterator iter = predefined_mixtures_library.predefined_mixture_map.find(name);
    if (iter != predefined_mixtures_library.predefined_mixture_map.end()){
        dict = iter->second;
        return true;
    }
    else{
        return false;
    }
}
```

**Comment by jowr** [comment]
Thanks, I am going to include it. Do you know how to make pull requests? It is a really nice way of submitting patches...

**Comment by mikekaganski** [comment]
2/22/2015 3:13 AM, Jorrit Wronski пишет:
> Do you know how to make pull requests? It is a really nice way of 
> submitting patches... 
Actually no,
I am getting used to GitHub now
I'll learn, but until then, I'll still keep sending this way to avoid 
forgetting "wise thoughts" :)
Hope it's not utterly rude

**Comment by jowr** [comment]
No worries, we are happy for every piece of code that is reviewed.
