### ISSUE TITLE
Add partial pressure of water as an output in HAPropsSI

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#490]
Add:
- P_WS : water saturation pressure 
- P_W : water  pressure 
as Input of Coolprop.

**Comment by ibell** [comment]
You mean P_W as an output, right?  I don't think it makes sense to use it
as an input.

**Comment by pmanach** [comment]
Hello Ian, 
Yes of Course, only INPUT.
I propose to help you to debug the HAPROPSI function : I've again seen some troubles...
Could you explain me how work your solvers ?

**Comment by ibell** [comment]
Have you looked at the C++ code:
https://github.com/CoolProp/CoolProp/blob/master/src/HumidAirProp.cpp ?

Basically we take any inputs, and convert to Temperature, pressure, and
water mole fraction.

And then all outputs can be obtained as a function of Temperature,
pressure, and water mole fraction

**Comment by ibell** [comment]
Can you please clarify this issue?  I am prepared to implement it, but I want to make sure we are talking about the same things.

If I understand correctly, you would like two features added as output-only parameters

* The pressure of pure(!) water (not including the enhancement factor), p_ws, or as sometimes referred to, p_w0. This is the same value as could be obtained from ``PropsSI("P","T",298.15,"Q",0,"Water")`` for instance.  Thus I am not sure it is worth it to implement it in HAPropsSI
* Water partial pressure, which is given by the enhancement factor times the water-alone pressure p_w0 - this definitely should be implemented in HAPropsSI

**Comment by pmanach** [comment]
Hello Ian,
What I asked is only the water partial pressure in air and the water partial pressure in air at saturation (R=1).
Sincerely,PY MANACH
Date: Wed, 11 Mar 2015 18:49:43 -0700

**Comment by ibell** [comment]
Ok, I think it only makes sense to calculate the partial pressure of water,
and if you want it at saturation, you just do:

PP_ws = HAPropsSI("PP_w","P",101325,"R",1,"T",298)

That should be easy to implement
