### ISSUE TITLE
HAProp - Conductivity & Viscosity

### ISSUE THREAD

**Issue by kkous** [CoolProp/CoolProp#498]
Hello, 

Conductivity and viscosity calculations for moist air are based on Tsilingris work: "Thermophysical and transport properties of humid air at temperature range between 0 and 100C". 

According to Tsilingris relation (see attached figure, the black & white one), when the relative humidity rises for a given temperature, the thermal conductivity falls.
Plotting the same data with HAProps and MATLAB gave me the second figure (same axis than the first), where it is clear that an increasing RH gives an increasing conductivity.

After investigation, it seems that HAProps uses the properties of pure liquid water (at normal conditions) instead of steam/vapour water ones. If I'm not wrong, the viscosity values used in the calculation of the moist air conductivity, T≃ 40°C, P=101325 Pa are:
- (Dry) Air, approx. 1.92e-5 Pa⋅s, which is OK
- Water, approx. 6.4**e-4** Pa⋅s

While the viscosity value for vapour water in the same conditions is approx. 1.04e-5 Pa⋅s, according to the VDI Heat Atlas relations. A ratio of 10 for 1 which could explains the behaviour in fig. 2.

My knowledge in cpp is very limited and I couldn't investigate any further. Is this a desired behaviour? 

Thank you for your superb work and your help.

![conductivity-t-rh tsilingris](https://cloud.githubusercontent.com/assets/11183559/6360230/c8dd827a-bc78-11e4-9951-76d7171a3e56.png)
![conductivity-t-rh haprops](https://cloud.githubusercontent.com/assets/11183559/6360229/c8dc3866-bc78-11e4-9edd-8d9c0b2269a7.png)

**Comment by ibell** [comment]
Yes, see also https://github.com/CoolProp/CoolProp/issues/470

I think what they do in Tsilingiris is to use the thermal conductivity of
water at 0 pressure

Do you have access to the paper?  What would be interesting is to compare
the thermal conductivity curve they use for water and either a) saturated
water vapor at the given pressure b) thermal conductivity of water at 0
pressure (or equivalently zero density).  Could you do that?

**Comment by kkous** [comment]
The paper is easily found online. Concerning the water properties they are using:
> From this point of view, all selected properties were derived from the Handbook of Heat Transfer [23]
> ...
> 
> Corresponding data for the water vapor properties were taken from the same literature source as compiled from Toulukian et al. [25]. These data were fitted by the following appropriate degree polynomials in the temperature range 0 <= t <= 120 °C.
> 
> The viscosity in Ns/m2 · 10-6 was determined by the following linear expression,
> mu_v = MV0 + MV1 ⋅ t
> with MV0 = 8.058131868 · 10^1 and MV1 = 4.000549451 ·10^-1.
>
> The thermal conductivity in W/m K · 10-3 was determined by the expression,
> kv = KV0 + KV1⋅t + KV2 ⋅ t^2
> where KV0 = 1.761758242 · 10^1, KV1= 5.558941059 ·10^-2 and KV2 = 1.663336663 · 10^-4.

> The specific heat capacity in (kJ/kg K) was determined by the following expression,
> cpv = CV0 + CV1⋅t  + CV2 ⋅ t2
> with CV0 = 1.86910989, CV1 = -2.578421578 · 10-4 and CV2 = 1.941058941 · 10-5.

[23] Rohsenow WM, Hartnett JP, Cho YI. Handbook of heat transfer. 3rd ed. McGraw-Hill; 1998.
[25] Touloukian YS, Powell RW, Ho CY, Clemend PG. Thermophysical properties of matter, vol. 1. NY; 1970.

Attached the comparison of conductivities of water vapour used by Tsilingiris (presumed 1 atm), and from the VDI relations (1 atm).
![conductivity vapour](https://cloud.githubusercontent.com/assets/11183559/6367545/b2ee474a-bcd4-11e4-81c1-79ac71374cc8.png)

Water at 0 pressure will come later.

Thanks!

**Comment by ibell** [comment]
Nice work! Problem is, as rightly noted in the other issue, what do we do
when T < 273.16 K?

**Comment by kkous** [comment]
Using the partial pressure for water do the trick for 0 < T < 100°C (if we get rid of calculation errors that lead to a partial pressure value > saturation pressure, and so uses liquid water conductivity for the calculation).

The easiest way I found was forcing the vapour quality to 1 : 
```  
Water->update(CoolProp::QT_INPUTS,1,T);
``` 

Moist air conductivity (W/mK) for RH  0 → 1 :
![26-02-2015 10-35-31_scrot](https://cloud.githubusercontent.com/assets/11183559/6389488/877aded6-bda4-11e4-9bf0-09f583290fa6.png)

Water vapour conductivity (blue: CoolProp with Q=1) (green: VDI relations)
![26-02-2015 10-43-58_scrot](https://cloud.githubusercontent.com/assets/11183559/6389513/c3002ace-bda4-11e4-82c7-206fcc93dab1.png)


For T < 273.16K, it seems indeed that some investigation should be made that I can't help right now. 

Thank you!
