### ISSUE TITLE
thread_local broken on OSX

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#502]
@mikekaganski , the thread_local fix didn't work for some builders on OSX: http://www.coolprop.dreamhosters.com:8010/builders/Python-binaries-osx-64bit-py27/builds/564

```
g++ -fno-strict-aliasing -I/Users/jowr/miniconda/envs/CoolProp27/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I../../include -I../../src -I../../externals/Eigen -I../../externals/REFPROP-headers -I../../externals/msgpack-c/include -I/Users/jowr/miniconda/envs/CoolProp27/include/python2.7 -c ../../src/CoolPropTools.cpp -o build/temp.macosx-10.5-x86_64-2.7/../../src/CoolPropTools.o
../../src/CoolPropTools.cpp:20:8: error: thread-local storage is unsupported for the current target
static thread_local unsigned long long ftw_summer; // An evil global variable for the ftw function
       ^
../../include/CoolPropTools.h:54:34: note: expanded from macro 'thread_local'
            #define thread_local __thread
                                 ^
1 error generated.
```

**Comment by mikekaganski** [comment]
Maybe then define it as empty for MacOS?

I work now to re-implement the directory size count without global 
variables. It will make this specific one irrelevant, but still, there 
are a number of other places where thread-local storage is highly 
desirable, so I wouldn't remove the macro definition itself for now

26.02.2015 13:03, Ian Bell пишет:

**Comment by ibell** [comment]
Some info: 

http://stackoverflow.com/questions/23791060/c-thread-local-storage-clang-503-0-40-mac-osx
http://stackoverflow.com/questions/28094794/why-does-apple-clang-disallow-c11-thread-local-when-official-clang-supports?lq=1

**Comment by ibell** [comment]
6cd7307a06745483a36b98d8242f533442ef9c96 and 63b5fd938d19c7015c6f22dc5438b7769f6a3978 fixes this
