### ISSUE TITLE
PropsSI function only accepts independent variables that are 1 dimensional

### ISSUE THREAD

**Issue by AndySchroder** [CoolProp/CoolProp#514]
The PropsSI function only seems to accept independent variables that are 1 dimensional.
The function should accept any number of dimensions as long as both independent variables are the same shape.

Here is a simple example:

```python
$ ipython
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy

In [2]: from CoolProp.CoolProp import PropsSI

In [3]: PropsSI('H', 'T', 310*numpy.ones((2,2)), 'P', 12*10**6*numpy.ones((2,2)), 'CO2')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-cb699e40268b> in <module>()
----> 1 PropsSI('H', 'T', 310*numpy.ones((2,2)), 'P', 12*10**6*numpy.ones((2,2)), 'CO2')

/usr/local/lib/python2.7/dist-packages/CoolProp/CoolProp.so in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:16127)()

/usr/local/lib/python2.7/dist-packages/CoolProp/CoolProp.so in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:15374)()

ValueError: Input 3 is not one-dimensional

In [4]: PropsSI('H', 'T', 310*numpy.ones((2,1)), 'P', 12*10**6*numpy.ones((2,1)), 'CO2')
Out[4]: array([ 285711.64933968,  285711.64933968])



In [10]: import CoolProp

In [11]: CoolProp.__gitrevision__
Out[11]: u'173bc5e06d2c6ffe5f7906349e7e92678f38d9e5'

In [12]: CoolProp.__version__
Out[12]: u'5.0.7'


```

A wrapper function can be written to flatten and then reshape, but this is not ideal. A non-robust example:

```python
$ ipython
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy

In [2]: from CoolProp.CoolProp import PropsSI

In [3]: def PropsSI2(*args):
   ...:     TheShape=args[2].shape
   ...:     return numpy.reshape(PropsSI(args[0],args[1],args[2].flatten(),args[3],args[4].flatten(),args[5]),TheShape)
   ...: 

In [4]: PropsSI2('H', 'T', 310*numpy.ones((2,2)), 'P', 12*10**6*numpy.ones((2,2)), 'CO2')
Out[4]: 
array([[ 285711.64933968,  285711.64933968],
       [ 285711.64933968,  285711.64933968]])

In [5]: 


```

This type of functionality is needed because many times it is faster and more stable to pre-populate values into an interpolation table.

**Comment by ibell** [comment]
Unfortunately, the low-level function that PropsSI calls (PropsSImulti) only takes 1D inputs, thus, PropsSI does as well.  

If it's speed you are after, you should be using the low-level interface: http://www.coolprop.org/coolprop/LowLevelAPI.html

Also, we will have exceptionally fast tabular interpolation tables based on TTSE or bicubic interpolation, they are in the tabular branch right now, and will probably be merged into master in another few days.  There are a few small issues that remain, the core code is functional.

**Comment by AndySchroder** [comment]
Good to see a link to a little more information about the abstract state 
function, but I'm still at a loss at how to use it. More python examples 
would be greatly appreciated!


Also, regarding your table lookup mechanism, this sounds really 
exciting. Will the user have control over the grid point clustering, or 
do you have an automatic clustering based upon gradients in fluid 
properties? I'm just concerned about appropriate resolution near the 
critical point. In python, I'm currently using a multi-dimensional 
version of meshgrid to create my grid and data tables and then using 
LinearNDInterpolator as my table lookup mechanism. I crudely (manually) 
tweak the grid based on the property variations. Will your new approach 
be faster than LinearNDInterpolator? I will say that with this approach, 
CoolProp is about 70% faster than REFPROP to generate the data tables. I 
am then able to pickle the LinearNDInterpolator object to a file so that 
it dramatically speeds up the startup of my script each time. Will the 
data table be able to be saved to a file so that it can be quickly 
loaded in?

I can work with the simple wrapper function I have now if you don't want 
to mave multi dimensional support, and I'm hoping your table lookup 
approach will eliminate the need completely.



Andy Schroder

**Comment by ibell** [comment]
I think you would probably be hard pressed to do much better in terms of
speed and accuracy than our new method.  Its a regularly spaced grid in p-h
or p-T, and as long as you are not very very close to the critical point,
it should work fine.

Speed-wise, it looks like about 0.7 us/call, accuracy is excellent, for
more information, see our paper on CoolProp:
http://pubs.acs.org/doi/abs/10.1021/ie4033999.  Further information to
follow.  The tables can probably be merged into master in their current
state so you can get started with playing with them while we fix the last
few bugs.

For an example of using the abstract state from python, see this example:

``` python
from __future__ import print_function
from CoolProp import AbstractState
from CoolProp.CoolProp import PhaseSI, PropsSI, get_global_param_string
from CoolProp.HumidAirProp import HAPropsSI
from math import sinprint("**************** INFORMATION ***************")
print("CoolProp version:", get_global_param_string("version"))
print("CoolProp gitrevision:", get_global_param_string("gitrevision"))
print("CoolProp Fluids:", get_global_param_string("FluidsList"))
print("*********** HIGH LEVEL INTERFACE *****************")
print("Critical temperature of water:", PropsSI("Water", "Tcrit"), "K")
print("Boiling temperature of water at 101325 Pa:", PropsSI("T", "P",
101325, "Q", 0, "Water"), "K")
print("Phase of water at 101325 Pa and 300 K:", PhaseSI("P", 101325, "Q",
0, "Water"))
print("c_p of water at 101325 Pa and 300 K:", PropsSI("C", "P", 101325,
"T", 300, "Water"), "J/kg/K")
print("c_p of water (using derivatives) at 101325 Pa and 300 K:",
PropsSI("d(H)/d(T)|P", "P", 101325, "T", 300, "Water"), "J/kg/K")
print("*********** HUMID AIR PROPERTIES *****************")
print("Humidity ratio of 50% rel. hum. air at 300 K, 101325 Pa:",
HAPropsSI("W", "T", 300, "P", 101325, "R", 0.5), "kg_w/kg_da")
print("Relative humidity from last calculation:", HAPropsSI("R", "T", 300,
"P", 101325, "W", HAPropsSI("W", "T", 300, "P", 101325, "R", 0.5)),
"(fractional)")
print("*********** INCOMPRESSIBLE FLUID AND BRINES *****************")
print("Density of 50% (mass) ethylene glycol/water at 300 K, 101325 Pa:",
PropsSI("D", "T", 300, "P", 101325, "INCOMP::MEG-50%"), "kg/m^3")
print("Viscosity of Therminol D12 at 350 K, 101325 Pa:", PropsSI("V", "T",
350, "P", 101325, "INCOMP::TD12"), "Pa-s")
print("*********** LOW-LEVEL INTERFACE *****************")
AS = AbstractState("HEOS", "Water&Ethanol")
z = [0.5, 0.5]
AS.set_mole_fractions(z)
AS.update(input_pairs.PQ_INPUTS, 101325, 1)
print("Normal boiling point temperature of water and ethanol:", AS.T(), "K")
```

**Comment by ibell** [comment]
Here are docs on the tabular methods we've implemented: http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/coolprop/Tabular.html
