### ISSUE TITLE
Problem using CoolProp with Fortran 77

### ISSUE THREAD

**Issue by michaelbazin** [CoolProp/CoolProp#517]
Hello everyone,

I am using CoolProp in order to evaluate the variation of physical properties in a CFD problem. I am using a program written in Fortran 77 to call the library. I have a problem with the isobaric heat expansion coefficient. All I get in return after executing my program is a series of «Infinity». I am also calling other properties like the density, the heat conductivity, …, and no problem with them.
I also tried to call some other parameters which sting input name were using underscore, like speed_of_sound, and it works well.

Does anybody have an idea about how to solve this problem ?

Here is my code

      DOUBLE PRECISION Pref, Tref
      character(LEN=32) Ref, Name1, Name2
      character(LEN=32) Output1, Output2, Output3, Output4
      double precision outVal1, outVal2, outVal3, outVal4, Prop1, Prop2

	Pref=8000000.D0
	Tref=313.15D0
	outVal2=0.03587  

	Output1 = "D"//CHAR(0)
        Output2 = "ISOBARIC_EXPANSION_COEFFICIENT"//CHAR(0)
	Output3 = "C"//CHAR(0)
	Output4 = "L"//CHAR(0)

        Name1  = "T"//CHAR(0)	
        Name2  = "P"//CHAR(0)
        Prop2  = Pref
        Ref    = "CARBONDIOXIDE"//CHAR(0)

	DO IEL = 1,NCELET
	
       Prop1  = PROPHY(IEL,ITEMPK(1)) 

       call propssi(Output1, Name1, Prop1, Name2, Prop2, Ref, outVal1)
      call propssi(Output2, Name1,Prop1, Name2, Prop2, Ref, outVal2)
       call propssi(Output3, Name1, Prop1, Name2, Prop2, Ref, outVal3)
       call propssi(Output4, Name1, Prop1, Name2, Prop2, Ref, outVal4)

        write(*,*) outVal1, outVal2, outVal3, outVal4 
	PROPHY(IEL,IROM(1))=outVal1*(1-OutVal2*(W1(IEL)-Tref))
	PROPHY(IEL,ICP(1)) = outVal3
        PROPHY(IEL,IVISCL(1)) = outVal4/Outval3 

	END DO

And when I get in return

   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002
   277.89725622343570                       Infinity   4950.0920596451224        4.3107995978438486E-002

Thanks a lot.

Regards,

Michaël.

**Comment by ibell** [comment]
I think we just haven't implemented this function.  I'll take a look, can't
be tough to fix.  Thanks for the report

**Comment by michaelbazin** [comment]
Tkanks a lot for your help. I launched a new simulation, and obviously, that doesn't seem to work better. Should I wait a little bit before the modification take place ?
Thank you.

Regards,

Michaël.

**Comment by ibell** [comment]
Did you download from nightly?

**Comment by michaelbazin** [comment]
You mean should I download the library again ? Sorry, I am not an expert in data processing (I'm studying fluid mechanics). 

Thanks a lot for your support.

Michaël.

**Comment by michaelbazin** [comment]
I just installed the new .so file, put it in the right place and launch a new simulation, and unfortunately, it still does not work. I tried with "ISOBARIC_EXPANSION_COEFFICIENT" and "isobaric_expansion_coefficient", and no one works.

Regards,

Michaël.

**Comment by ibell** [comment]
Where did you download the .so from?  Following the instructions here (
http://www.coolprop.org/coolprop/wrappers/FORTRAN/index.html#fortran77) you
should download the nightly version from here:
http://sourceforge.net/projects/coolprop/files/CoolProp/nightly/shared_library/
. That change hasn't made it into a numbered release yet

**Comment by ibell** [comment]
I confirm that it works for me, so an updated .so should do the trick.

**Comment by michaelbazin** [comment]
My mistake, it works great !

Best regards,

Michaël.
