### ISSUE TITLE
error: thermal conductivity R32:  _phase is unknown

### ISSUE THREAD

**Issue by dipi91** [CoolProp/CoolProp#523]
When I ask for the thermal conductivity of R32 at working condition of [T=273K; P=8.48e5Pa] 
Coolprop 5 returns following error: _phase is unknown. But when I ask for the phase at those conditions it returns that it is in liquid phase.

**Comment by ibell** [comment]
Ok, this is a case where the extended corresponding states method fails to
find the conformal state for the reference fluid.  The error could be more
useful.  I'll fix the error message.

**Comment by dipi91** [comment]
When I ask the same thing in the old Coolprop (V4) or RefProp it does work.

**Comment by ibell** [comment]
Right, I'll take a look.
