### ISSUE TITLE
critical point calculation in Coolprop 5.0.7

### ISSUE THREAD

**Issue by eosilva77** [CoolProp/CoolProp#525]
Hi everyone,

Hi Ian,

I am using the Modelica Wrapper available in CoolProp SVN at "CoolProp-5.0.7-sources\wrappers\Modelica\src" to build a library of Coolprop that I can use in my program. I changed the files in this folder to call the functions of CoolProp 5 as described at http://www.coolprop.org/coolprop/LowLevelAPI.html and . When I calculate the critical point of "CO2", "R134a", or "Water" using the following code, the program crashes:
.
.
.
fluid_string = "Water";
backend = "?";
shared_ptr<CoolProp::AbstractState> state(CoolProp::AbstractState::factory(backend, fluid_string));
T_ccb = state->T_critical(); //CoolProp::Props1SI(substanceName,"Tcrit");
dc = state->rhomass_critical(); //CoolProp::Props1SI(substanceName,"rhocrit");
state->update(CoolProp::DmassT_INPUTS,dc,T_ccb); //->not possible calculate at the critical point!! - it crashes
hc = state->hmass(); //CoolProp::Props1SI(substanceName,"Hcrit"); in version 4
sc = state->smass(); //CoolProp::Props1SI(substanceName,"Scrit"); in version 4
.
.
.

In Coolprop 5, this algorithm crashes always at the call of function "update". With Coolprop 4, it was the properties "Hcrit" and "Scrit" still available and didn't have problems at all. What exactly I am doing wrong? 

Thanks and best Regards,

Erick

**Comment by ibell** [comment]
Actually version 5 is correct - you cannot evaluate the critical state for
CO2 or water (their equations are not defined at the the critical state).
If you want the properties AT the critical state, you must just a small
increment away from the critical point

**Comment by jowr** [comment]
Just a small reminder: CoolProp has been integrated into ExternalMedia and version 5 will be added to ExternalMedia in the near future. If you need it now, please feel free to start the work. Note that ExternalMedia has an internal work around for the critical properties.

**Comment by ibell** [comment]
@eosilva77 and @jowr - I am closing this issue for now, but it would be really great if you could collaborate to bring the v5 interface to ExternalMedia
