### ISSUE TITLE
Error loading v5.0.8 through the C# interface

### ISSUE THREAD

**Issue by DanWBR** [CoolProp/CoolProp#531]
It seems that an error-registering function is missing from the shared library.

System.TypeInitializationException was caught
  HResult=-2146233036
  Message=The type initializer for 'CoolPropPINVOKE' threw an exception.
  Source=CoolPropInterface
  TypeName=CoolPropPINVOKE
  InnerException: System.TypeInitializationException
       HResult=-2146233036
       Message=The type initializer for 'SWIGExceptionHelper' threw an exception.
       Source=CoolPropInterface
       TypeName=SWIGExceptionHelper
       InnerException: System.EntryPointNotFoundException
            HResult=-2146233053
            Message=Unable to find an entry point named 'SWIGRegisterExceptionCallbacks_CoolProp' in DLL 'CoolProp'.
            Source=CoolPropInterface
            TypeName=""

**Comment by DanWBR** [comment]
Sorry, I was using the wrong DLL. Closing this issue.

**Comment by ibell** [comment]
Yes perhaps we should rename the C# DLL in order to reduce confusion with
the DLL versions

**Comment by DanWBR** [comment]
Couldn't you include the C# functions in the default DLL, or are they Windows-specific?

**Comment by ibell** [comment]
Not really possible - they are auto-generated by SWIG, and there's no nice
way of making them all work together

**Comment by DanWBR** [comment]
No problem then. I really forgot that I should look for the specific DLL in Csharp folder and went directly to the shared library one. :-)
