### ISSUE TITLE
Julia on linux is broken for me

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#542]
@JonWel - It seems something is broken on linux, I can't run Julia code with CoolProp.  Can you replicate?

```
ian@ian-VirtualBox:~/Desktop$ julia runme.jl 
OpenBLAS : Your OS does not support AVX instructions. OpenBLAS is using Nehalem kernels as a fallback, which may give poorer performance.
PropSI: 
elapsed time: 16.239165108 seconds (2 MB allocated)
Abstract Class: 
ERROR: LoadError: ccall: could not find function AbstractState_factory in library CoolProp
 in AbstractState_factory at /home/ian/Desktop/CoolProp.jl:85
 in AC at /home/ian/Desktop/runme.jl:53
 in include at ./boot.jl:250
 in include_from_node1 at loading.jl:129
 in process_options at ./client.jl:318
 in _start at ./client.jl:402
while loading /home/ian/Desktop/runme.jl, in expression starting on line 62
```
Julia:
```
ian@ian-VirtualBox:~/Desktop$ julia
OpenBLAS : Your OS does not support AVX instructions. OpenBLAS is using Nehalem kernels as a fallback, which may give poorer performance.
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3864 (2015-03-17 19:48 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 09604d6 (0 days old master)
|__/                   |  x86_64-linux-gnu
```

**Comment by 11718pauld** [comment]
@ibell ....You can use [Juliabox](juliabox.org), sign-in using your gmail account. You don't have to worry about the Julia-Installation.
Only thing you need to do is install CoolProp using the Console...
pip install --user CoolProp
(Which perhaps does the v5.0.8)
or,
use the nightly build shared library interfaced with coolprop.jl (with updated file path for coolprop.so)
and things do run.

**Comment by JonWel** [comment]
The OpenBLAS error may be caused by VirtualBox: https://www.virtualbox.org/ticket/12206

For the second error `could not find function AbstractState_factory in library CoolProp`, I suggest you to check your library version, the `5.0.8` release do not have the low level interface, so replacing it by the nightly build (be sure to clean the cache is the nightly build version is not new enough), or a custom build from sources.

**Comment by ibell** [comment]
@JonWel - I assure you that this function is in my .so - I did a ``nm
CoolProp.so`` to check.  I think it is related to the ccall arguments
because I played with them and I got a different failure.  Does it work for
you on linux with everything up-to-date?

**Comment by JonWel** [comment]
I do not have your runme.jl file to test but usage of the abstract class still work on Julia 0.4 for me:
```Julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3888 (2015-03-18 19:42 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 5762a5d (0 days old master)
|__/                   |  x86_64-linux-gnu
```
```Julia
julia> errcode = Ref{Clong}(0);

julia> const buffer_length = 255;

julia> message_buffer = Array(UInt8, buffer_length);

julia> function AbstractState_factory(backend::String, fluids::String)
         AbstractState = ccall( (:AbstractState_factory, "CoolProp"), Clong, (Ptr{UInt8},Ptr{UInt8},Ref{Clong},Ptr{UInt8},Clong), backend,fluids,errcode,message_buffer::Array{Uint8,1},buffer_length)
         if errcode[] != 0
           if errcode[] == 1
             error("CoolProp: ", bytestring(convert(Ptr{UInt8}, pointer(message_buffer))))
           elseif errcode[] == 2
             error("CoolProp: message buffer too small")
           else # == 3
             error("CoolProp: unknown error")
           end
         end
         return AbstractState
       end
AbstractState_factory (generic function with 1 method)

julia> AbstractState_factory("TTSE&HEOS", "Water")
Loading table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logph.bin.z
Loaded table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logph.bin.z in 0.107356 sec.
Loading table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logpT.bin.z
Loaded table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/single_phase_logpT.bin.z in 0.102261 sec.
Loading table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/pure_saturation.bin.z
Loaded table: /home/johndoe/.CoolProp/Tables/HelmholtzEOSBackend(Water)/pure_saturation.bin.z in 0.001572 sec.
0

julia> 
```

**Comment by ibell** [comment]
Interesting.  I'll try again this weekend, where did you get the .so from?

**Comment by JonWel** [comment]
The one used on this test was a custom build from the GitHub, but the nightly build gives the same results (just tested now with the nightly build from 11 hours ago).

**Comment by ibell** [comment]
Me:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3888 (2015-03-18 19:42 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 5762a5d (1 day old master)
|__/                   |  x86_64-linux-gnu

julia> errcode = Ref{Clong}(0);

julia> const buffer_length = 255;

julia> message_buffer = Array(UInt8, buffer_length);

julia> function AbstractState_factory(backend::String, fluids::String)
                AbstractState = ccall( (:AbstractState_factory, "CoolProp"), Clong, (Ptr{UInt8},Ptr{UInt8},Ref{Clong},Ptr{UInt8},Clong), backend,fluids,errcode,message_buffer::Array{Uint8,1},buffer_length)
                if errcode[] != 0
                  if errcode[] == 1
                    error("CoolProp: ", bytestring(convert(Ptr{UInt8}, pointer(message_buffer))))
                  elseif errcode[] == 2
                    error("CoolProp: message buffer too small")
                  else # == 3
                    error("CoolProp: unknown error")
                  end
                end
                return AbstractState
              end
AbstractState_factory (generic function with 1 method)

julia> AbstractState_factory("TTSE&HEOS", "Water")
ERROR: ccall: could not find function AbstractState_factory in library CoolProp
 in AbstractState_factory at none:2
```
and 
```
ian@ian-VirtualBox:~/Desktop$ nm CoolProp.so | grep AbstractState_
000000000016e130 T AbstractState_factory
000000000016dcd0 T AbstractState_free
000000000016d360 T AbstractState_keyed_output
000000000016d610 T AbstractState_set_fractions
000000000016d0c0 T AbstractState_update
```

**Comment by ibell** [comment]
The really odd part is that it loads other functions (like PropsSI) fine

**Comment by JonWel** [comment]
My library file is in `/usr/lib/x86_64-linux-gnu/julia/CoolProp.so`.
May you have an older version of the library in a directory searched before your `~/Desktop/` directory?

**Comment by ibell** [comment]
Ah you must be right.  Typical newbie mistake.  In fact I'm sure you're right.

**Comment by ibell** [comment]
Right, so evidently there is no way to get Julia to load the .so in the current directory and it always searches in ``/usr/lib/x86_64-linux-gnu/julia/`` first.

**Comment by 11718pauld** [comment]
Julia searches for the default, but I did that some time ago like this...
changing all the `ccall`'s with
```
ccall( (:F2K, "/home/juser/c_nbuilt/CoolProp_nbld")
```

It works....

**Comment by JonWel** [comment]
An other way would be to put a `CoolProp.so` link in the `/usr/lib/x86_64-linux-gnu/julia/` directory pointing to your built `libCoolProp.so`.
That way you can update the `CoolProp.jl` file and your built `libCoolProp.so` do not even have to be renamed when you compile again.

**Comment by ibell** [comment]
@JonWel Yes that is another good solution.  Want to update the docs?  We
now have three solutions to the shared library search problem in Julia

**Comment by JonWel** [comment]
I see that you already update it with `export LD_LIBRARY_PATH=${PWD}`.
If I understand well, this is a bash command that would be written before starting Julia and it require to set the `PWD` variable to be the path to the library (that still have to be renamed to `CoolProp.so`).
Did you check if it works?

I saw an other way by ihnorton in JuliaLang/julia#10273 : 
A `push!(DL_LOAD_PATH,".")` in Julia makes Julia search in the local directory for shared library, with "." that can be replaced by any other path.

**Comment by ibell** [comment]
The environmental variable ``PWD`` is the current working directory (just
like ".")  And yes, this command is run before starting Julia.  And you do
still need to rename the library to CoolProp.so, that is true.  That could
be overcome by making a soft link from CoolProp.so to libCoolProp.so in the
current working directory.  My method does work, I checked.

I like the push!(DL_LOAD_PATH,".") - that is a more Julia-like way of doing
things.  Let's add that to the docs as well.
