### ISSUE TITLE
dr/dp and dr/dh

### ISSUE THREAD

**Issue by enter802** [CoolProp/CoolProp#543]
Hi,

how to extract the dr/dp and dr/dh states in coolprop for a fluid in MATLAB? is it even possible?

Thanks.

**Comment by ibell** [comment]
Have you read the docs? (
http://www.coolprop.org/coolprop/HighLevelAPI.html#partial-derivatives)

**Comment by jowr** [comment]
Could you help me here? What is "r"? In general, partial derivartives are available via "d(OF)/d(WRT)|CONSTANT" as dcumented in http://coolprop.sourceforge.net/coolprop/HighLevelAPI.html#partial-derivatives

**Comment by enter802** [comment]
"r" is rho (density). 
i didn't go through the doc before so sorry about that. But I am still having trouble extracting this information using coolprop.

unlike the syntax shown in the doc, I use, for example, Props('D','P',14000,'T','300','R245fa') for extracting the density information at the given parameters. I tried Props('d(Hmass)/d(T)|P','P',101325,'T',300,'Water') but it shows "Your output key [d(Hmass)/d(T)|P] is not valid." as an error. Could you please provide me the exact syntax I should use to extract dr/dp and dr/dh?

Sorry for all the trouble and thanks in advance!

**Comment by ibell** [comment]
As you see in the example, the function to call is PropsSI, not Props
(Props is a deprecated function).  Always a good idea to start off with a
copy-paste when possible.

**Comment by enter802** [comment]
thank you sir for your fast responses. the wrapper I downloaded, for some reason, does not support the PropsSI syntax and supports only Props. I guess I have the wrong wrapper then?

**Comment by ibell** [comment]
Where did you download it from?

**Comment by enter802** [comment]
i downloaded it from github

**Comment by ibell** [comment]
I don't understand how you could "download it from github" for the MATLAB
wrapper.  Try following these instructions:
http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#matlab

**Comment by enter802** [comment]
got it working sir! thank you so much for your kind help and patience. although I will bother you one last time - should the command be "CoolProp.PropsSI('d(D)/d(P)|P','P',101325,'T',300,'R245fa')" if I want to have drho/dp? I am a bit confused about the "|P" part and right now I am getting "inf" for the above input.

**Comment by ibell** [comment]
The part after the | is the parameter held constant.  I assume you want
enthalpy held constant, so that would be

"CoolProp.PropsSI('d(Dmass)/d(P)|Hmass','P',101325,'T',300,'R245fa')"

Does that work?

**Comment by enter802** [comment]
Thank you so much. That works perfectly. But what is that "mass" after D and H? what is its functionality?

**Comment by ibell** [comment]
you can either have mass-based (Dmass) or mole-based (Dmolar) properties,
hence the two.  There are also aliases, do D = Dmass.  See also
http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function

**Comment by enter802** [comment]
That clears all! Thank you so much sir. I can't appreciate any less for all your help!

But suddenly I remember why I stopped using CoolProp.PropsSI and started using Props syntax - it is because for any given combination of P and T, the quality Q is always -1 for R245fa. Is that a bug?

**Comment by ibell** [comment]
The vapor quality Q is only useful if it is two-phase, if it is not
two-phase, the quality is not between 0 and 1 (inclusive)

**Comment by enter802** [comment]
Thank you so much sir. Learnt a lot about the coolprop. It is a great job you are doing with the coolprop. Thanks for everything! Hope you succeed more with your research and contribution to the field. Best of luck!

**Comment by ibell** [comment]
My pleasure.
