### ISSUE TITLE
Clean up Julia wrappers using typealias

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#544]
I think we can condense the two 0.3 and 0.4 version wrappers using a typedef for UInt8 (and maybe Ref as well?).  @JonWel are you up to it?

See http://julia.readthedocs.org/en/latest/manual/types/#type-aliases

**Comment by JonWel** [comment]
So we would make a version check and if 0.3 or lower using typedef to point to the old names.
That would make the loading of the wrapper a little slower (but it is quite fast by now) and should not impact too much the execution).

Something like:
```Julia
if VERSION <= VersionNumber(0,4)
  typealias UInt8 Uint8
end
```
Should make it quite easily for the `UInt`. 

The Ref is a bit more complex as theses type are not used the same way (the `UInt8` are used exactly the same way and are aliases with a deprecated warning for `Uint8` in Julia `0.4`).
The `Ref{Clong}(0)` creates an reference pointer to a Clong (initialised to 0 but it's value do not mater) that is directly passed to the C++ library, whereas the `Array(Clong, 1)` creates an Array of one element (without initialising the value, so it's real value is equal to what was previously written in this place in memory) of which the pointer to the first (and only) element is passed to the library (the same way the text strings are passed to the library).

The old way (the array) will still work in Julia 0.4 but is deprecated when it is only needed to pass a pointer to a single value (it is still the good way to pass vectors).

I think it may be required to use some kind of macro to determine which way will be used depending Julia version.
I should document myself a bit more on macros in Julia before having a solution to this.

An other problem is that it is best for speed usage to precise the type of the global variable at the time it is used in the function (so the compiler know the type will never change and optimise for this type, example: `errcode::Array{Clong,1}` in Julia 0.3). But this time a second alias may be enough.

**Comment by JonWel** [comment]
Placing this following code at the beginning of the Julia 0.4 wrapper:
```Julia
if VERSION <= VersionNumber(0,4)
  typealias UInt8 Uint8
  typealias Ref Ptr
  errcode = Array(Clong, 1)
else
  errcode = Ref{Clong}(0)
end
```
Plus suppressing the line defining `errcode` plus suppressing all `::Base.RefValue{Clong}` works, but there is a performance regression.
1e10 execution of the low level interface pass from:
´´´Julia
elapsed time: 7.729897476 seconds (80 bytes allocated)
```
to
```Julia
elapsed time: 9.155892367 seconds (320000080 bytes allocated, 1.24% gc time)
```

I still have to find a way to tell witch type the `errcode` variable is when used in the functions.

**Comment by JonWel** [comment]
Oh, it seems I can get best of both world with:
```Julia
if VERSION <= VersionNumber(0,4)
  typealias UInt8 Uint8
  typealias Ref Ptr
  typealias RefValue Array
  errcode = Array(Clong, 1)
else
  errcode = Ref{Clong}(0)
end
```
And specifying `errcode::RefValue{Clong,1}` when using `errcode`.

Julia 0.3 before:
```Julia
elapsed time: 7.729897476 seconds (80 bytes allocated)
```
Julia 0.4 before:
```Julia
elapsed time: 8.016877508 seconds (120 bytes allocated)
```
Julia 0.3 after:
```Julia
elapsed time: 7.90943363 seconds (80 bytes allocated)
```
Julia 0.4 after:
```Julia
elapsed time: 7.551739111 seconds (120 bytes allocated)
```

Now I'm wondering if this `Ref` is really better (seems to use a bit more memory).

**Comment by ibell** [comment]
Looks good to me - go for the merge and update of the docs.  I like that we are going to be able to only maintain one interface file
