### ISSUE TITLE
Problem with HAPropsSI

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#548]
Hello,

I had an error when using:

HAPropsSI('W','T',288.209928591,'P',101325,'H',40531.8272297)

Eror Message:
File "HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp/CoolProp.cpp:3649)
  File "HumidAirProp.pyx", line 47, in CoolProp.CoolProp.HAPropsSI (CoolProp/CoolProp.cpp:2560)
ValueError: p is not a valid number :: inputs were:"W","T",2.8820992859116438e+02,"P",1.0132500000000000e+05,"H",4.0531827229742747e+04 

Thank you

**Comment by ibell** [comment]
T,H are problematic inputs, to be avoided if possible.  Once we do this
one: https://github.com/CoolProp/CoolProp/issues/486 it should solve many
of these problems.

**Comment by bo3mrh** [comment]
So, meanwhile I can still use HAProps!?

**Comment by ibell** [comment]
Nope, HAProps calls HAPropsSI, so you will have to give me a bit of time to
dig into this one, shouldn't be too bad, though I thought we had fixed all
the ones in this family of error.

**Comment by bo3mrh** [comment]
OK. Therefore, I will update the ACHP code with HAPropsSI
