### ISSUE TITLE
alternative for UseSaturationLUT

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#551]
Hi,

Is there any alternative for UseSaturationLUT in CoolProp 5.x ?
The role of UseSaturationLUT is to use the Look Up Tables for calculating the saturation properties for the sake of speed and cost.

Thank you

**Comment by ibell** [comment]
At the moment, no, but once I finish IF97 implementation, we will use  that
which is much faster

**Comment by ibell** [comment]
IF97 has been coded up, now I just need to implement in HAPropsSI internally.  I think I'll get to it tomorrow.
