### ISSUE TITLE
IsFluidType function

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#552]
Hi,

I'm working on ACHP model with CoolProp 5.x, and IsFluidType function is intensively used in the model. If there is no alternative, could you please re-implement the function ?

Thank you

**Comment by bo3mrh** [comment]
Hi,

I guess it can be done without re-implementing IsFluidType. Correct me if I'm wrong.
Since the backend "INCOMP" is mostly for Brine and mixture fluids, I can replace the current If statement (if IsFluidType(Ref,'Brine')==:) in ACHP model with (if 'INCOMP' in Ref:). 
Can that works ?

**Comment by ibell** [comment]
Yes, but it doesn't separate pure and pseudo-pure fluids

**Comment by ibell** [comment]
See https://github.com/ibell/coolprop/blob/c67ecc570e545d624c18feaf2a01e48b63ae1501/CoolProp/CoolProp.cpp#L446 and convert to CP v5 style

**Comment by bo3mrh** [comment]
It has the same style as before. Thank you

**Comment by ibell** [comment]
That, in fact, is the old code :)

**Comment by ibell** [comment]
Ok, new idea.  I think it makes more sense to implement the function in ACHP, so what I propose is that I add an output to get_fluid_param_string that returns "true" if it is a pure fluid, or "false" if it is a pseudo-pure fluid.  Now that you pretty much have to provide the backend in v5, that simplifies determination of the fluid type.

**Comment by ibell** [comment]
Ok, now that you can differentiate between pure and pseudo-pure fluids with the HEOS backend, I think you have all you need to re-implement the functionality of IsFluidType in ACHP.  In the end, I like this solution better than writing a hacky fix in CoolProp.
