### ISSUE TITLE
SO2 with Air mixture: Could not match the binary pair

### ISSUE THREAD

**Issue by samiit** [CoolProp/CoolProp#553]
Sulfur dioxide (SO2) with Nitrogen and Oxygen (Air) mixture when applied using:
```python
PropsSI("Dmolar","T",473,"P",1.9613e3,"N2[0.78]&O2[0.21]&SO2[0.01]")
```
gives an error:
`Could not match the binary pair [7446-09-5,7727-37-9] - for now this is an error.`

I even tried with the REFPROP module and similar error is issued.
```python
PropsSI("Dmolar","T",473,"P",1.9613e3,"REFPROP::N2[0.78]&O2[0.21]&SO2[0.01]")
```
`[SETUP error 101] error in opening file for component #  1; filename = (/opt/refprop/fluids/N2.ppf ...`

**Comment by ibell** [comment]
Yup, I don't think there are any mixture interactions parameters for SO2
with anything else.  Hence the errors for your mixture.

**Comment by samiit** [comment]
Thanks Ian.
Does it mean there is no way around? No way to create an moist-air + SO2 mixture for studying acid rains' effect and the like? :))

**Comment by ibell** [comment]
Nope, I am afraid not for now.  REFPROP doesn't have this mixture either.  I am working on a predictive scheme in my day job, hopefully I can implement that into CoolProp in the near future.
