### ISSUE TITLE
Coolprop for Matlab R2008a

### ISSUE THREAD

**Issue by seppschnorcher** [CoolProp/CoolProp#554]
Hello,
Unfortunately Coolprop doesn’t work on my system although I considered all installation advices.
I think my Matlab Version is too old. Is there any solution for this problem?
Thanks, simon

**Comment by ibell** [comment]
Yes it seems that backwards compatibility ends with MATLAB 2012. You could
try with CoolProp v4.2.5, though some things (notably mixtures) are in v5
that were not in v4. What error message do you get?

**Comment by seppschnorcher** [comment]
Thank you very much, this version works fine.

**Comment by seppschnorcher** [comment]
Actually there has appeared another question:

I was trying to calculate the density of saturized methane in two different ways (directly via PropsSI and indirectly). Actually the solution should be the same, but it isn't.

**Matlab Input:**

p = 10e5; %pressure
x = 0.3;  %mass Ratio vapour
fluid='methane';

dg  = PropsSI('D','P',p,'Q',1,fluid);  %density gas
df  = PropsSI('D','P',p,'Q',0,fluid);   %density liquid
d_1 = PropsSI('D','P',p,'Q',x,fluid); %density @ x
d_2 = df + x * (dg - df);                   %density @ x

d_1-d_2                                          %should equal zero!!!

**Matlab Output:**

ans =

 -208.9533

**Comment by ibell** [comment]
Nope.  VOLUME is mole-fraction weighted, not density.  That tripped me up
for a long time.

**Comment by jowr** [comment]
Was volume already mole-fraction-based v4, didn't that come with v5? I think @seppschnorcher refers to v4.2.5.

**Comment by seppschnorcher** [comment]
Actually I'm working on v4.2.4.
Shouldn't the mole-fraction be the same as the mass fraction with the molar Mass M being constant?

mole_fraction = n_gas / (n_gas + n_liqu)

mass_fraction = m_gas / (m_gas + m_liqu)

with m = n * M

**Comment by ibell** [comment]
You can do

v = vf*x + vl*(1-x)

but you cannot(!!!) do

rho = rhof*x + rhol*(1-x)

**Comment by ibell** [comment]
That's what I was trying to say with my previous comment

**Comment by seppschnorcher** [comment]
ah ok i got you, thanks for your patience ;)
