### ISSUE TITLE
Error PropsSI with R410A

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#557]
I'm getting the following error:
Two-phase inputs not supported for pseudo-pure for now

when calling:
PropsSI("Q","T",310.996631,"P",2301391.979,"R410A")

However, 
PropsSI("Q","T",310.996631,"P",2301391.979,"REFPROP::R410A") is working fine!

**Comment by ibell** [comment]
Question is, what are the dewpoint and bubble point temperatures calculated
by CoolProp and REFPROP for that pressure?  Maybe CoolProp is right...

**Comment by bo3mrh** [comment]
They are exactly the same
T_bub = 310.995939813
T_dew = 311.11561476

**Comment by ibell** [comment]
Those are not exactly the same :)  And you are in fact in between them, so
CoolProp is right.

**Comment by bo3mrh** [comment]
I meant both CoolProp and REFPROP give me the same T_bub and T_dew. 
Is there an update for CoolProp to calculate the Quality in that small region?

**Comment by ibell** [comment]
No.  Quality cannot be defined for pseudo-pure fluids when the T-P is
two-phase.  REFPROP is actually wrong in this case.  Or rather, they yield
an incorrect, approximate solution.  And CoolProp is more strictly
correct.  It is up to you to figure out what you want to do when the state
is two-phase.  Unless you use a full mixture model (SLOW!!), you can't get
it from T,P ->Q in two-phase.  I can explain the science of it if you are
interested.

**Comment by bo3mrh** [comment]
That makes sense to me now. Thank you
