### ISSUE TITLE
CoolProp convergence failure at near 100% mixture concentrations

### ISSUE THREAD

**Issue by murenrb** [CoolProp/CoolProp#558]
Using the CoolProp RefProp wrapper, there seems to be limited stability around high concentration mixtures. I imagine this is something to do with the high rate of change of the properties in this area. 

Specifically, I am using ammonia mixtures. For example calls like the following don converge:
PropsSI("H","Q",1,"P",210000,"REFPROP-MIX:AMMONIA[0.987]&WATER[0.013]")
PropsSI("T","Q",1.,"P",100000.,"REFPROP-MIX:AMMONIA[0.97]&WATER[0.03]")

The value error returned is: 

[PQFLSH error] (sat vapor):  [SATP error 148] iteration for saturation state did not converge;  

I am hoping that this is a problem in CoolProp because if its a problem in RefProp then I may be hosed. 

Thanks!

**Comment by ibell** [comment]
Bad new for you - its a problem in REFPROP.  All is not lost though.  We've
added a function to the low-level interface that allows you to provide
guesses that improves the stability.  What language are you calling
CoolProp from?

**Comment by ibell** [comment]
As this is a REFPROP problem, you could also try emailing Eric
Lemmon: Eric.Lemmon@NIST.gov

**Comment by murenrb** [comment]
I was afraid of that! I am using Python.

On Wednesday, March 25, 2015, Ian Bell <notifications@github.com> wrote:

> Bad new for you - its a problem in REFPROP. All is not lost though. We've
> added a function to the low-level interface that allows you to provide
> guesses that improves the stability. What language are you calling
> CoolProp from?
>
> On Wed, Mar 25, 2015 at 9:53 PM, murenrb <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Using the CoolProp RefProp wrapper, there seems to be limited stability
> > around high concentration mixtures. I imagine this is something to do
> with
> > the high rate of change of the properties in this area.
> >
> > Specifically, I am using ammonia mixtures. For example calls like the
> > following don converge:
> > PropsSI("H","Q",1,"P",210000,"REFPROP-MIX:AMMONIA[0.987]&WATER[0.013]")
> > PropsSI("T","Q",1.,"P",100000.,"REFPROP-MIX:AMMONIA[0.97]&WATER[0.03]")
> >
> > The value error returned is:
> >
> > PQFLSH error <http://sat%20vapor>: [SATP error 148] iteration for
> > saturation state did not converge;
> >
> > I am hoping that this is a problem in CoolProp because if its a problem
> in
> > RefProp then I may be hosed.
> >
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CoolProp/CoolProp/issues/558>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoolProp/CoolProp/issues/558#issuecomment-86329506>.
>


-- 
Russell Muren
CO-founder
Rebound Technologies
303 330-2712 | email <russell@rebound-tech.com> | website
<http://www.REbound-tech.com> | linkedin
<http://www.linkedin.com/in/russellmuren>

Unless otherwise noted, please consider all information in this email
confidential

**Comment by ibell** [comment]
Well that's at least good.  Let me see about pushing that code up to
CoolProp and I'll add some information to the docs. Hmm.. Actually I think
for now the guesses only work for CoolProp, not REFPROP, but I can
certainly fix that.

**Comment by murenrb** [comment]
Ok, well let me know if I can be helpful. For now I am using Conde
correlations when the refprop call throws an exception. But it would be
great to have an option of giving it better guess values.

On Wednesday, March 25, 2015, Ian Bell <notifications@github.com> wrote:

> Well that's at least good. Let me see about pushing that code up to
> CoolProp and I'll add some information to the docs. Hmm.. Actually I think
> for now the guesses only work for CoolProp, not REFPROP, but I can
> certainly fix that.
>
> On Wed, Mar 25, 2015 at 10:10 PM, murenrb <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I was afraid of that! I am using Python.
> >
> > On Wednesday, March 25, 2015, Ian Bell <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Bad new for you - its a problem in REFPROP. All is not lost though.
> We've
> > > added a function to the low-level interface that allows you to provide
> > > guesses that improves the stability. What language are you calling
> > > CoolProp from?
> > >
> > > On Wed, Mar 25, 2015 at 9:53 PM, murenrb <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > > > Using the CoolProp RefProp wrapper, there seems to be limited
> stability
> > > > around high concentration mixtures. I imagine this is something to do
> > > with
> > > > the high rate of change of the properties in this area.
> > > >
> > > > Specifically, I am using ammonia mixtures. For example calls like the
> > > > following don converge:
> > > >
> PropsSI("H","Q",1,"P",210000,"REFPROP-MIX:AMMONIA[0.987]&WATER[0.013]")
> > > >
> PropsSI("T","Q",1.,"P",100000.,"REFPROP-MIX:AMMONIA[0.97]&WATER[0.03]")
> > > >
> > > > The value error returned is:
> > > >
> > > > PQFLSH error <http://sat%20vapor>: [SATP error 148] iteration for
> > > > saturation state did not converge;
> > > >
> > > > I am hoping that this is a problem in CoolProp because if its a
> problem
> > > in
> > > > RefProp then I may be hosed.
> > > >
> > > > Thanks!
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/CoolProp/CoolProp/issues/558>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/CoolProp/CoolProp/issues/558#issuecomment-86329506
> >.
> > >
> >
> >
> > --
> > Russell Muren
> > CO-founder
> > Rebound Technologies
> > 303 330-2712 | email <russell@rebound-tech.com
> <javascript:_e(%7B%7D,'cvml','russell@rebound-tech.com');>> | website
> > <http://www.REbound-tech.com> | linkedin
> > <http://www.linkedin.com/in/russellmuren>
> >
> > Unless otherwise noted, please consider all information in this email
> > confidential
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CoolProp/CoolProp/issues/558#issuecomment-86331109>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoolProp/CoolProp/issues/558#issuecomment-86332356>.
>


-- 
Russell Muren
CO-founder
Rebound Technologies
303 330-2712 | email <russell@rebound-tech.com> | website
<http://www.REbound-tech.com> | linkedin
<http://www.linkedin.com/in/russellmuren>

Unless otherwise noted, please consider all information in this email
confidential

**Comment by murenrb** [comment]
Ian,
Just to keep you in the loop, Eric sent me a new FLD file for ammonia. Its
available online at:

http://www.boulder.nist.gov/div838/theory/refprop/901/REFPROP.HTM

I have not tested it thoroughly yet, but so far it is producing more stable
solutions.


On Wed, Mar 25, 2015 at 10:15 PM, Russell Muren <russell@rebound-tech.com>
wrote:

> Ok, well let me know if I can be helpful. For now I am using Conde
> correlations when the refprop call throws an exception. But it would be
> great to have an option of giving it better guess values.
>
>
> On Wednesday, March 25, 2015, Ian Bell <notifications@github.com> wrote:
>
>> Well that's at least good. Let me see about pushing that code up to
>> CoolProp and I'll add some information to the docs. Hmm.. Actually I think
>> for now the guesses only work for CoolProp, not REFPROP, but I can
>> certainly fix that.
>>
>> On Wed, Mar 25, 2015 at 10:10 PM, murenrb <notifications@github.com>
>> wrote:
>>
>> > I was afraid of that! I am using Python.
>> >
>> > On Wednesday, March 25, 2015, Ian Bell <notifications@github.com>
>> wrote:
>> >
>> > > Bad new for you - its a problem in REFPROP. All is not lost though.
>> We've
>> > > added a function to the low-level interface that allows you to provide
>> > > guesses that improves the stability. What language are you calling
>> > > CoolProp from?
>> > >
>> > > On Wed, Mar 25, 2015 at 9:53 PM, murenrb <notifications@github.com
>> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>> > >
>> > > > Using the CoolProp RefProp wrapper, there seems to be limited
>> stability
>> > > > around high concentration mixtures. I imagine this is something to
>> do
>> > > with
>> > > > the high rate of change of the properties in this area.
>> > > >
>> > > > Specifically, I am using ammonia mixtures. For example calls like
>> the
>> > > > following don converge:
>> > > >
>> PropsSI("H","Q",1,"P",210000,"REFPROP-MIX:AMMONIA[0.987]&WATER[0.013]")
>> > > >
>> PropsSI("T","Q",1.,"P",100000.,"REFPROP-MIX:AMMONIA[0.97]&WATER[0.03]")
>> > > >
>> > > > The value error returned is:
>> > > >
>> > > > PQFLSH error <http://sat%20vapor>: [SATP error 148] iteration for
>> > > > saturation state did not converge;
>> > > >
>> > > > I am hoping that this is a problem in CoolProp because if its a
>> problem
>> > > in
>> > > > RefProp then I may be hosed.
>> > > >
>> > > > Thanks!
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub
>> > > > <https://github.com/CoolProp/CoolProp/issues/558>.
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/CoolProp/CoolProp/issues/558#issuecomment-86329506>.
>> > >
>> >
>> >
>> > --
>> > Russell Muren
>> > CO-founder
>> > Rebound Technologies
>> > 303 330-2712 | email <russell@rebound-tech.com> | website
>> > <http://www.REbound-tech.com> | linkedin
>> > <http://www.linkedin.com/in/russellmuren>
>> >
>> > Unless otherwise noted, please consider all information in this email
>> > confidential
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/CoolProp/CoolProp/issues/558#issuecomment-86331109
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CoolProp/CoolProp/issues/558#issuecomment-86332356>.
>>
>
>
> --
> Russell Muren
> CO-founder
> Rebound Technologies
> 303 330-2712 | email <russell@rebound-tech.com> | website
> <http://www.REbound-tech.com> | linkedin
> <http://www.linkedin.com/in/russellmuren>
>
> Unless otherwise noted, please consider all information in this email
> confidential
>
>


-- 
Russell Muren
CO-founder
Rebound Technologies
303 330-2712 | email <russell@rebound-tech.com> | website
<http://www.REbound-tech.com> | linkedin
<http://www.linkedin.com/in/russellmuren>

Unless otherwise noted, please consider all information in this email
confidential

**Comment by ibell** [comment]
Okie dokie, I guess for now this issue is closed, not sure there is much we can do at the REFPROP level.
