### ISSUE TITLE
pairs of statevariables

### ISSUE THREAD

**Issue by seppschnorcher** [CoolProp/CoolProp#559]
Is there any reason why only Special pairs of state variables are allowed?

I Need for example T = f(u,d) or Q=f(u,d) and so on.

Therefore I now use the Workaround to varify T until the  function 
y = u - PropsSI('U','T',T,'D',d,fluid)    
for given d and u equals zero, for example with fzero in matlab.

Do you see any Problems with this solution?

**Comment by ibell** [comment]
What version of CoolProp do you use?  In version 5.x, U,D are valid inputs,
internally we do the iteration that you describe.
