### ISSUE TITLE
Molecular Formulas as Trivial Property

### ISSUE THREAD

**Issue by thebear9** [CoolProp/CoolProp#564]
Since properties such as molar mass, critical temp, critical pressure, etc. can be retrieved based on the fluid name, why not add a feature to retrieve the formula?

std::string formula = CoolProp::get_fluid_param_string("Nitrogen", "Formula");

to return "N2"

Obviously, there would be some exceptions like air which doesn't have a molecular formula, but this feature would still be helpful.

**Comment by ibell** [comment]
That's a great idea.  Can you put it together?

**Comment by ibell** [comment]
Looks like it should be pretty easy actually: http://chemspipy.readthedocs.org/en/latest/guide/gettingstarted.html

**Comment by thebear9** [comment]
That's a great solution!  I meant to reply earlier, but I wanted to compile the formulas first.  I'll look into your solution soon!

**Comment by ibell** [comment]
There's also this - http://cactus.nci.nih.gov/chemical/structure .  I've heard its a lot more reliable.  Looks like you can get back the chemical formula, and it can all be scripted.  Do you use python?

**Comment by thebear9** [comment]
Ian,

Thanks for the additional details!  I actually code in Objective-C and I've been working on bringing in CoolProp to my app, Chemical Engineering Appsuite.  I should have an update to the app finalized by the end of the month.

https://itunes.apple.com/us/app/chemical-engineering-appsuite/id526158171?mt=8

Best,
Jason
