### ISSUE TITLE
documentation confusing

### ISSUE THREAD

**Issue by hyhzju** [CoolProp/CoolProp#565]
Today I am going to calculate the thermal conductivity of R22 in Excel by using the function PropsSI(). I don't now which character/symbol I should use for this property. 

Firstly i tried to find information for the folder "Microsoft Excel" wrapper which contains the coolprop.dll and coolprop.xlam/xla. No such a brief but clear document was coming with it. I checked the Excel test example, no information there too. 

Then I google with the key words "coolprop, thermal conductivity, props". Wow, I found much different results,:
1.Here use "L": http://coolprop.readthedocs.org/en/latest/apidoc/CoolProp.html and here https://github.com/ibell/coolprop/blob/master/dev/IncompressibleLiquids/tester.py 
2.Here use "k": http://www.coolprop.org/apidoc/CoolProp.CoolProp.html 
3.... What the correct on for current version? I tried either Props("L","T",273.16,"Q",0,"R22")1000) or Props("k","T",273.16,"Q",0,"R22")1000) but both neither outputs a value (in Excel i got "#VALUE! ".

For visicosity, somewhere uses "Visc", somewhere uses "V"...

I guess it is due to the version change. 

Suggestions: how about put an "brief" but "full" instruction in each wrapper folder or even as comments in the testing file. In this way, any user can find the useful information at the first glance. 
 And/or provide a example with all kinds of fuctions application.

By the way, is there any version info for the coolprop.dll file? A fuction to output? or by checking the property of the file? How can tell which coolprop is the latest version if I have couple of them on the hardrive?

**Comment by ibell** [comment]
How about http://www.coolprop.org/coolprop/HighLevelAPI.html and
http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function
?

The Props function is deprecated.  Use the PropsSI function.

You can get the version of CoolProp by calling
get_global_param_string("version")

**Comment by ibell** [comment]
Do things make more sense now?

**Comment by hyhzju** [comment]
Yes! That　“Table of string inputs to PropsSI function” is very straight forward and helpful. Thanks.
I still suggest to put a link or hint in the example file to the URL of this table. In the future, there might be other modifications or upgrades of the variables. Adding a simple sentence with a link into the wrapper examples or "readme"  will save time and make him/her happy for any newbie to this great code. 

for the thermal conductivity calculation, I finally found it was not wrong with the expression " Props("L","T",273.16,"Q",0,"R22")1000). The problem is due to the fluid itself. I change to other fluids, the fuction gave right answers.

**Comment by jowr** [comment]
OK, good to hear that this one is solved. Please do yourself a favour and try to avoid the `Props` function and replace it with `PropsSI`. We cannot guarantee that future versions of CoolProp support the `Props` notation.

**Comment by ibell** [comment]
Added a link to generated examples: 4ba64735092605b46491ae1ccd06c575882b974e
