### ISSUE TITLE
Reference of state not working for Refprop backend

### ISSUE THREAD

**Issue by mayersre** [CoolProp/CoolProp#568]
The reference of state CoolProp.CoolProp.set_reference_state() does not work for the 
Refprop backend. It would be great to have it for the GUI

**Comment by ibell** [comment]
I'm on it, I'll fix it for pure fluids this weekend.

**Comment by ibell** [comment]
Unfortunately, given the architecture, it doesn't seem possible to set the reference state for mixtures in REFPROP, pure fluids only.
