### ISSUE TITLE
NBS Water Composition

### ISSUE THREAD

**Issue by paarfi** [CoolProp/CoolProp#571]
If I run this code:
AbstractState state = AbstractState.factory("INCOMP", "NBS");
state.set_mass_fractions(new DoubleVector(new double[] { 1 }));
state.update(input_pairs.PT_INPUTS, 10135, 313);

or this code:
double q = CoolProp.PropsSI("C", "T", 308.15, "P", 101325, "INCOMP::NBS");

I get this error message:
Your composition 1.000000 is not between 0.000000 and 0.000000.

It works fine with DowthermJ or the Dynalenes. I haven't tried them all, but I suspect it's a problem with water [NBS] only. Am I doing something wrong, or is this a bug?

**Comment by ibell** [comment]
@jowr?

**Comment by jowr** [comment]
Thanks, I am going to fix it soon. 
As quick fix for now: 
  - You could also avoid setting the concentration at all, it should work without it.
  - You can also use `INCOMP::Water`, that works.

**Comment by paarfi** [comment]
It works now through the PropsSI interface. I couldn't test the abstractState with the development build because I didn't have the updated swig wrappers. But I expect it was the same underlying problem so it should be good as well. I'll test it to make sure when y'all have 5.1.0 released. Thanks.
