### ISSUE TITLE
Methane (and pentane) transport properties

### ISSUE THREAD

**Issue by jl230** [CoolProp/CoolProp#574]
Running module CoolProp.CoolProp.PropsSI for viscosity of methane results in an error stating "viscosity model is not available for this fluid."

Properties can be found in this document:
http://www.nist.gov/data/PDFfiles/jpcrd97.pdf

Thanks

**Comment by ibell** [comment]
Another option (I think to be preferred) is this one: http://pubs.acs.org/doi/abs/10.1021/jp0618577

**Comment by ibell** [comment]
I think I will implement the paper I refer to, it will fix problems for pentane (making @jowr happy) and methane, and I'll see if any others are missing that are in that paper.

**Comment by ibell** [comment]
Implemented in branch(https://github.com/CoolProp/CoolProp/tree/methane_pentane), values obtained seem wrong.  More debugging to follow.
