### ISSUE TITLE
HAProps at low humidity ratio

### ISSUE THREAD

**Issue by acuiko** [CoolProp/CoolProp#585]
HAProps gives wrong result when humidity ratio equal zero
double foo1 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.013);
double foo2 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.007);
double foo3 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.0000001);
Console.WriteLine(foo1); 437.400114479866 (good)
Console.WriteLine(foo2); 453.709902458561 (good)
Console.WriteLine(foo3); 453.709902458561 (wrong, this is a previous calculation (foo2) result, real value must be 473.151043639829)
If we do only one calculation before
double foo2 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.007);
double foo3 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0);
Console.WriteLine(foo2); 453.709902458561 (good)
Console.WriteLine(foo3); 3.221548321E-285 (wrong, always some numberE-285)
If no calculation before
double foo3 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0);
Console.WriteLine(foo3); 4.5020275E-308 (wrong, always some numberE-308)

**Comment by acuiko** [comment]
One more thing
			double foo1 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.013);
			double foo2 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.007);
			double foo3 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.0000001);
			Console.WriteLine(foo1);	 437.400114479866
			Console.WriteLine(foo2);	 453.709902458561
			Console.WriteLine(foo3);	 453.709902458561
W=0 gives a previous calculation (foo2) result (real value must be 473.151043639829)
If we do only one calculation before 
			double foo2 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0.007);
			double foo3 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0);
			Console.WriteLine(foo2); 453.709902458561
			Console.WriteLine(foo3); 3.221548321E-285
If no calculation before
			double foo3 = CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0);
			Console.WriteLine(foo3); 4.5020275E-308

**Comment by ibell** [comment]
Why are you doing calculations with HW as inputs?  It requires iteration,
and TW are the native inputs.  That said HW should work, but this
formulation is not consistent between dry air and almost dry air, which
might explain some of the behavior you see here.

**Comment by acuiko** [comment]
I must know a temperature of absolutely dry air, when enthalpy is known. There was no problem in CoolProp4. Now it gives either previous calculation value (which is most strange in this situation) or unexpected value close to 0.

**Comment by ibell** [comment]
Thanks for the clear description of the problem.  I'll take a look, looks like a simple bug to fix.

**Comment by ibell** [comment]
Interesting error.  Thanks for the report!
