### ISSUE TITLE
HAProps humidity ratio calculation issue

### ISSUE THREAD

**Issue by acuiko** [CoolProp/CoolProp#586]
HAPropsSI("W", "T", 284.126559814803, "P", 101325, "H", 27341.3380686986) = 0.0064681.., which is true, but increasing enthalpy by 0.0000000001 gives an error
HAPropsSI("W", "T", 284.126559814803, "P", 101325, "H", 27341.3380686987) = Infinity
increasing enthalpy by 0.0000000001 once again gives good result
HAPropsSI("W", "T", 284.126559814803, "P", 101325, "H", 27341.3380686988) = 0.0064681..
Is this problem with input parameters precision?

Also CoolProp "remembers" some errors(?) from previous calculations:
HAPropsSI("W", "T", 277.85346492137359, "R", 0.79755875874022542, "P", 101325) = 0.0042... which is true, but if we do a "bad" calculation before this one, we got an error in both calls:
HAPropsSI("W", "T", 284.126559814803, "P", 101325, "H", 27341.3380686987) = Infinity (This fails always)
HAPropsSI("W", "T", 277.85346492137359, "R", 0.79755875874022542, "P", 101325) = Infinity (this fails when "bad" calculation is made right before it)

**Comment by ibell** [comment]
I think this is related to #585 -  something is not getting cleared properly it seems.  I'll take a look.
