### ISSUE TITLE
Quality value far away from two phase zone

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#587]
It would be great if Q returned for fluid states far away from the two phase zone have meaningful values: I need to check automatically if a point maps to a superheated vapour, so it would be great if asking for Q returns 1 (or 0 in case of subcooled fluids). This behaviour is consistent with its physical meaning (moles of vapour / moles of liquid).

**Comment by jowr** [comment]
Have you tried using http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function ?

**Comment by ibell** [comment]
Yes, I recommend you use the low-level interface, as there is a phase() function which returns an enumeration for the phase.

The reason we can't calculate a reasonable value for Q in the other regions is that it requires a call to the saturation routines, which makes it much slower.  I suppose we could do something like Q in [0,1] if two-phase, and then the phase index + 10 if it is not two-phase.  But then you are just back to the same problem again.  Have you checked out the docs that @jowr recommends?  I recommend them too.
