### ISSUE TITLE
Request for extension: table of quantities in the documentation for HAPropsSI like for PropsSI

### ISSUE THREAD

**Issue by postmath** [CoolProp/CoolProp#591]
It looks like both input and output quantities are routed through `Name2Type` in the `HumidAirProp.cpp` file. The error message in that function also appears to be somewhat out of date -- the givens `Hha`, `Sha`, `Vha`, `Cha`, `Y`, `V`, `C`, `Z` are not listed (nor are their aliases).

**Comment by ibell** [comment]
Correct.  Could you make me a complete list of what is missing?

**Comment by postmath** [comment]
As far as I can see, there are 18 quantities that would be accepted: `T`, `P`, `R`, `W`, `D`, `B`, `H`, `S`, `M`, `K`, and the 8 quantities listed above. I think a table could have three or four columns: one to list all their aliases (once again lifted from `Name2Type`); one with the appropriate SI unit; one with a textual description; and maybe some form of info on what is appropriate for input or output, though I think (from reading the source, and from http://www.coolprop.org/fluid_properties/HumidAir.html) that the criteria are too complicated to capture easily in a table column.

**Comment by ibell** [comment]
Basically this one, right?:
http://www.coolprop.org/apidoc/CoolProp.CoolProp.html#CoolProp.CoolProp.HAPropsSI

**Comment by postmath** [comment]
Ah, cool! Yes, that's the one. If we include the paragraph directly below the table, and additionally `Sha`, `Y`, and `Z` :)

Reading that page very strictly, it says that these are the valid strings for input. As I understand it, they're also exactly the set of valid strings for output; it might be good to add that explicitly.

**Comment by postmath** [comment]
Thanks, Ian.
