### ISSUE TITLE
ReadTheDocs.org

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#594]
Is the readthedocs thing still used?
http://coolprop.readthedocs.org/ points to the 4 version of CoolProp.
Or should I just delete that bookmark?

**Comment by ibell** [comment]
Yes, it would be best to delete it - I had entirely forgotten about readthedocs

**Comment by ibell** [comment]
@Rod-Persky Can you take down the readthedocs.org documentation please?  It's very out of date now and I don't want to direct people to the wrong place.

**Comment by thorade** [comment]
Or let it point to the new repo address. I personally like the rtfd site
Am 22.04.2015 02:34 schrieb "Ian Bell" <notifications@github.com>:

**Comment by ibell** [comment]
I "like" the RTFD page too, but it doesn't integrate well with our workflow
since we have some scripts that run upstream to make figures, auto-generate
tables, etc.  Also, you can't compile code on their servers so you can't do
fully integrated testing in the restructured text.

**Comment by Rod-Persky** [comment]
I’ve removed the RTFD docs page
