### ISSUE TITLE
add DOIs to bibliography

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#595]
I guess the reference list at
http://www.coolprop.org/zbibliography.html
is somehow dynamically generated from 
https://github.com/CoolProp/CoolProp/blob/master/CoolPropBibTeXLibrary.bib

If you don't mind, I would in the next weeks add some DOIs to that bib file.

**Comment by ibell** [comment]
Yes, please do.  This is the sort of contribution that is greatly appreciated.

**Comment by ibell** [comment]
And yes, it is dynamically generated by sphinx

**Comment by jowr** [comment]
I have some DOIs already, I'll add them ASAP.

**Comment by jowr** [comment]
Sorry guys, I cannot find the list i made once.

**Comment by jowr** [comment]
Might help: http://sherman.library.nova.edu/doi/
