### ISSUE TITLE
Issue with installing CoolProp in MAC

### ISSUE THREAD

**Issue by enter802** [CoolProp/CoolProp#596]
Hi, I am having issue in integrating the CoolProp in my MAC. I did everything same as with windows except that I have replaced the MEX file for windows with that of MAC. I have attached the screenshot for the error I am getting.

I downloaded the MEX file from http://sourceforge.net/projects/coolprop/files/CoolProp/5.0.8/MATLAB/

My OSX is Yosemite (Version 10.10.2). Platform I am trying to integrate CoolProp with is MATLAB 2015a.

Thanks for your time in advance.

![screen shot 2015-04-16 at 12 06 02 pm](https://cloud.githubusercontent.com/assets/9440833/7192742/8d5bb280-e455-11e4-93f0-769e90c8bc0a.png)

**Comment by jowr** [comment]
The error message tells you that the CoolProp code expects a certain function in `/Applications/MATLAB_R2015a.app/bin/maci64/libmx.dylib`, which is not there. This could be a Sphinx issue, but I am not sure at all. Maybe someone who owns a Mac and can help debugging can comment on this. Maybe @speredenn or @ibell have an idea. It seems like Yosemite changed a lot, we already had some trouble with Python and it seems that the changes introduced in 10.10 have millions of side effects. They changed the basic C++ standard libraries :unamused:

**Comment by ibell** [comment]
I think I might know how to fix this, but let me see.

**Comment by ibell** [comment]
Nope, that didn't work.  In the folder that is listed for libmx.dylib, can you please do this at the command line:

``nm libmx.dylib > exports.txt`` 

and email me the ``exports.txt``

**Comment by enter802** [comment]
I am not so sure what you actually want me to do, I am not such a technical person honestly when it comes to all these commands. Should I open the terminal window and type the command you just asked me to execute? Some guide would be great - plus I am new with MAC.

**Comment by enter802** [comment]
I am new with MAC so having some problem with command window. 

When I am typing "cd ~/Applications", it shows "No such file or directory" although working just fine for other directories such as Documents and Downloads. Help?

**Comment by enter802** [comment]
I finally was able to do what you told me to do but I eventually ended up getting this:
![screen shot 2015-04-17 at 11 35 51 pm](https://cloud.githubusercontent.com/assets/9440833/7214149/9ec20b40-e55a-11e4-928f-9ddb7b05d27d.png)

**Comment by ibell** [comment]
Looks like you don't have XCode installed.  I think MATLAB switched standard libraries between 2014 and 2015, which means that it just won't work.  We might have to compile a special version for 10.10 which would be very annoying.  

Could you also try ``otool -L libmx.dylib`` like you did for the other one?

**Comment by enter802** [comment]
Here it is - looks like again something missing. Please provide a solution fast as without CoolProp, I am pretty much stuck (!). I am sure you will do Mr. Bell!

![screen shot 2015-04-18 at 4 55 39 pm](https://cloud.githubusercontent.com/assets/9440833/7217510/015b2c46-e5ec-11e4-834a-c8bdc9e1f9a3.png)

**Comment by ibell** [comment]
I'm not sure this is a problem that can be fixed :( Apple messed up a lot
of stuff when they went to 10.10, and this might be yet another one.
Another idea, can you email me the libmx.dylib file? I have XCode installed
on my machine.

**Comment by enter802** [comment]
I cannot find any "libmx.dylib" file in the folder rather when I search for it, it shows some other files instead:
![screen shot 2015-04-18 at 7 48 07 pm](https://cloud.githubusercontent.com/assets/9440833/7217825/01333fc0-e604-11e4-977e-3e34ce94fe05.png)

**Comment by ibell** [comment]
It probably can't find it because it is inside an application.  In the
finder, right click on the MATLAB application, then click Browse(or
explore, or something, I can't remember exactly what command it is).  Then
bin/maci64, then email me the libmx.dylib

**Comment by enter802** [comment]
oh got it! check your email Mr. Bell!

**Comment by ibell** [comment]
"Solution" for now is to downgrade to 10.9

**Comment by pdenis13** [comment]
Hi , 

Same pb encountered. 

On a 2014a release all works. on the 2015a  it crash as said enter802. I try to build wrapper but without success.  some idea since April ?

**Comment by ibell** [comment]
Yes, downgrade to 10.9 :( OSX is proving to be a problem.

**Comment by ibell** [comment]
The problem is we need to built the wrapper on 10.10, not 10.9, and we don't have access to a 10.10 machine.

**Comment by jowr** [comment]
Which steps are required? I do have one...
```
dhcp076090:~ jowr$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.4
BuildVersion:   14E46
```

**Comment by ibell** [comment]
You'll need MATLAB as well, do you have a license?

**Comment by jowr** [comment]
:-1:  OK, that is a show stopper...

**Comment by pdenis13** [comment]
If needed, I can help with my 2015a license and 10.10 mac OS X

**Comment by ibell** [comment]
Yes, that might be very useful indeed.  Can you please email me at
ian.h.bell@gmail.com and we can see what we can do.

**Comment by enter802** [comment]
@pdenis13 is CoolProp working properly in 10.10? I downgraded my OSX because it wasn't working properly previously (at the very beginning of the release of Yosemite).

**Comment by pdenis13** [comment]
Yes it works but with Mapple 2014a release, note with 2015a

**Comment by elFuser89** [comment]
Hi, I have the same problem with Matlab R2015b (academic license) on my mac (OS X 10.11.1).
Has this issue been solved?
Thanks.

**Comment by pdenis13** [comment]
actually Coolprop works great with Matlab R2014a on Mac OsX 10.11 (El capitan)  or 10.10 (Yosemite). 

It doesn't work using  R2015a or R2015b on OsX 10.10 and 10.11

the message is the following  : 

'~/CoolProp/CoolPropMATLAB_wrap.mexmaci64':
dlopen(~/CoolProp/CoolPropMATLAB_wrap.mexmaci64,
6): Symbol not found: __ZTISt16invalid_argument
  Referenced from:
  ~/CoolProp/CoolPropMATLAB_wrap.mexmaci64
  Expected in: /Applications/MATLAB_R2015b.app/bin/maci64/libmx.dylib
 in /~/CoolProp/CoolPropMATLAB_wrap.mexmaci64

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(261,varargin{:});


My knowledges in Computer & programing science are too poor to understand and propose an issue

**Comment by elFuser89** [comment]
I will use Matlab R2014a. Thank you very much.

**Comment by ibell** [comment]
For you guys who are struggling with MATLAB on OSX, you probably have to build it yourself on your computer to make sure the libraries that CoolProp links with are all correct.  I can't do it for you since I don't have access to OSX 10.11.  So basically follow the instructions in this section, downloading from the development link:

http://www.coolprop.dreamhosters.com/binaries/sphinx/coolprop/wrappers/MATLAB/index.html#pre-generated-wrapper-code

You will probably need to install cmake, and maybe XCode command line tools as well.  Let me know if you run into troubles.

**Comment by pdenis13** [comment]
Dear elFuser, 


I try to compile the wrapper using R2015b (Os X 10.11 El Capitan), if you want to test it  : 

https://www.dropbox.com/sh/yrvk9bx8jft8n9h/AAAy5Y2ZoE3TfEqtJVqYVgQOa?dl=0

On my computer it works

**Comment by elFuser89** [comment]
Thank you all for the support! Now it works with the folder given to me by pdenis13.
For my knowledge, have you follow the instructions provided by Ian Bell?
Thanks again to everyone for the help.

**Comment by pdenis13** [comment]
Yes I do (He give me additional information to build the wrapper, 

I’m able to produce wrapper  in V5 form (CoolProp_wrap.mexmaci64)  (folder I send you - I’m pdenis13)  or V4 form (HAPropsSI.mexmaci64/ PropsSI.mexmaci64) 

I’m happy that it’s work !!

**Comment by mchristians** [comment]
Hello, would anybody be so kind as to reupload the file @pdenis13 uploaded in Dropbox on Nov 1 2015? The current link points to a 404.

Many thanks!

**Comment by pdenis13** [comment]
I will do that as soon as possible, I’m in china actually, it’s difficult to access Dropbox.

**Comment by pdenis13** [comment]
here is the new link , sorry for the trouble : https://www.dropbox.com/sh/yrvk9bx8jft8n9h/AAAy5Y2ZoE3TfEqtJVqYVgQOa?dl=0 <https://www.dropbox.com/sh/yrvk9bx8jft8n9h/AAAy5Y2ZoE3TfEqtJVqYVgQOa?dl=0>

**Comment by ibell** [comment]
Thanks for the update!

**Comment by pdenis13** [comment]
Do you think it’s necessary to build another wrapper ? (This one is from November.)

**Comment by mchristians** [comment]
It's quite bizarre, I keep getting a 404 message. Is anyone else getting that problem?

**Comment by pdenis13** [comment]
try  this : https://www.dropbox.com/sh/3frjawndzuvkj9w/AACk5cgGabOtAbXL8wGMth98a?dl=0


it is the complete folder (including old syntax wrapper

**Comment by mchristians** [comment]
The latest link worked well, thank you!

**Comment by ibell** [comment]
Can you folks please try out this .mexmaci64: http://www.coolprop.dreamhosters.com:8010/unstable/MATLAB/OSX10.10%2B/ ?  I've updated our build system to automatically generate it.

**Comment by pdenis13** [comment]
OK , i’m in vacancies until 18 April, I will try it as soon as possible

**Comment by ibell** [comment]
@pdenis13 - it's ok, another user tested it and it worked!  So you don't need to worry about updating your 
version on dropbox anymore

**Comment by Talone** [comment]
@ibell Thanks, it's working here (OSX 10.11.4, Matlab 2015a) to! Could you address the problem with 10.10 and the spezial required version on the [Matlab wrapper instructions page](http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#matlab-wrapper)?
Tried to solve the problem for some time until I finally found this thread.

**Comment by pdenis13** [comment]
I will try it this Week-end

**Comment by ibell** [comment]
@Talone What is your problem with 10.10?  Have you checked out the development docs for matlab: http://www.coolprop.org/dev/coolprop/wrappers/MATLAB/index.html#pre-compiled-binaries

**Comment by Talone** [comment]
@ianhbell No problems here anymore since using the build you posted 2 weeks ago ([10.10 Build](http://www.coolprop.dreamhosters.com:8010/unstable/MATLAB/OSX10.10%2B/).
Thanks for the quick warning message on the Matlab wrapper page!
