### ISSUE TITLE
TTSE fails for two-phase H,P with heavy water

### ISSUE THREAD

**Issue by 11718pauld** [CoolProp/CoolProp#602]
```python
import CoolProp as CPpy
import numpy as np

len = 10
st = CPpy.AbstractState('TTSE&HEOS','D2O')
h = np.linspace(900e3,1100e3,len)
p = np.linspace(2.8e6,3e6,len)

HmassP_INPUTS = CPc.HmassP_INPUTS
Dmass = CPc.iDmass

for i in range(1, len):
    st.update(HmassP_INPUTS, h[i], p[i])
    print('%f %f %f' % (h[i], p[i], st.keyed_output(Dmass)))
```
```
922222.222222 2822222.222222 926.811018
944444.444444 2844444.444444 919.161382
966666.666667 2866666.666667 inf
988888.888889 2888888.888889 inf
1011111.111111 2911111.111111 nan
1033333.333333 2933333.333333 inf
1055555.555556 2955555.555556 nan
1077777.777778 2977777.777778 nan
1100000.000000 3000000.000000 nan
```
```python
CPpy.PropsSI('D','H',1100000.000000,'P',3000000.000000,'D2O')
```
```
175.13547986164923
```

Some Issue !

**Comment by 11718pauld** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/10331330/7215627/7f39ceda-e5fe-11e4-8535-525f289cd34e.png)
Some abrupt transitions !
```python
len = 500
dr_dh = np.zeros(len)
dr_dp = np.zeros(len)
x = np.zeros(len)
fluid = 'D2O'

h = np.linspace(800e3,1800e3,len)
p = np.linspace(2.8e6,3e6,len)

for i in range(len):
    dr_dh[i] = CPpy.PropsSI('d(D)/d(H)|P','P',p[i],'H',h[i],fluid)
    dr_dp[i] = CPpy.PropsSI('d(D)/d(P)|H','P',p[i],'H',h[i],fluid)
    hval = CPpy.PropsSI('H','P',p[i],'Q',0.0,fluid)
    hvalg = CPpy.PropsSI('H','P',p[i],'Q',1.0,fluid)
    x[i] = (h[i] - hval)/(hvalg - hval)

plt.subplot(2, 1, 1)
plt.plot(x, dr_dh)
plt.ylabel('dr_dh')

plt.subplot(2, 1, 2)
plt.plot(x, dr_dp)
plt.ylabel('dr_dp')
plt.xlabel('Quality')
plt.show()
```

**Comment by 11718pauld** [comment]
![prop_derivatives](https://cloud.githubusercontent.com/assets/10331330/7215677/82748138-e600-11e4-9ee9-424df6ed3a72.png)
Something like this I was expecting !

**Comment by ibell** [comment]
It could be a problem with the equation of state.  What if you use water?  Water and D2O have quite similar properties.

**Comment by ibell** [comment]
Also, please provide runnable examples including all imports so that a copy-paste can be done.

**Comment by ibell** [comment]
For the derivative problem, it is straightforward.  PropsSI derivatives are HOMOGENEOUS region (liquid, gas, supercritical).  Two phase derivatives are not supported with PropsSI.  You might want to look at http://www.coolprop.org/dev/_static/doxygen/html/class_cool_prop_1_1_abstract_state.html#a482c8088357c8d474bc4b0b95ab8c7cb which does support the derivative you want.  That should be exposed in the Python interface

**Comment by ibell** [comment]
Also, please one issue per problem.  The two issues you posted are entirely unrelated, except that they are a problem with D2O, though they would be with other fluids too.

**Comment by ibell** [comment]
Ok the other problem with interpolation is because the first inputs are subcooled liquid, and then the failures are two-phase.

**Comment by 11718pauld** [comment]
TTSE : Runnable Example

```python
import CoolProp.CoolProp as CPpy
import numpy as np
import CoolProp.constants as CPc
len = 10
st = CPpy.AbstractState('TTSE&HEOS','D2O')
h = np.linspace(900e3,1100e3,len)
p = np.linspace(2.8e6,3e6,len)

HmassP_INPUTS = CPc.HmassP_INPUTS
Dmass = CPc.iDmass

for i in range(1, len):
    st.update(HmassP_INPUTS, h[i], p[i])
    print('%f %f %f' % (h[i], p[i], st.keyed_output(Dmass)))
```
TTSE Water seems ok.

Partial Derivative
```Python
import CoolProp.CoolProp as CPpy
import numpy as np
import matplotlib.pyplot as plt

len = 500
dr_dh = np.zeros(len)
dr_dp = np.zeros(len)
qual = np.zeros(len)
fluid = 'D2O'

h = np.linspace(800e3,1800e3,len)
p = np.linspace(2.8e6,3e6,len)

for i in range(len):
    dr_dh[i] = CPpy.PropsSI('d(D)/d(H)|P','P',p[i],'H',h[i],fluid)
    dr_dp[i] = CPpy.PropsSI('d(D)/d(P)|H','P',p[i],'H',h[i],fluid)
    hval = CPpy.PropsSI('H','P',p[i],'Q',0.0,fluid)
    hvalg = CPpy.PropsSI('H','P',p[i],'Q',1.0,fluid)
    qual[i] = (h[i] - hval)/(hvalg - hval)

plt.subplot(2, 1, 1)
plt.plot(qual, dr_dh)
plt.ylabel('dr_dh')

plt.subplot(2, 1, 2)
plt.plot(qual, dr_dp)
plt.ylabel('dr_dp')
plt.xlabel('Quality')
plt.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/10331330/7218279/c37be3f0-e683-11e4-9c11-50826e20fe7c.png)

For, Water
![figure_2](https://cloud.githubusercontent.com/assets/10331330/7218281/fbe0aa3c-e683-11e4-8ef0-eadf76d5f593.png)

**Comment by ibell** [comment]
Did you read my comment?  If it is two-phase, you can't use CPpy.PropsSI('
d(D)/d(H)|P','P',p[i],'H',h[i],fluid) directly, for water or D2O. You need
to use the other two-phase derivative function.

**Comment by 11718pauld** [comment]
ok.....
Is it available for python and matlab interfaces along with the spline rho and spline density derivates?

**Comment by 11718pauld** [comment]
But definitely there is some issue with the TTSE D2O.

**Comment by ibell** [comment]
Yes, I will fix the issue you note, please try the other derivatives.
