### ISSUE TITLE
Props function returns 1.INF for Brine (MEG-20%)

### ISSUE THREAD

**Issue by selvagit123** [CoolProp/CoolProp#603]
Hi ,

I am trying to find heat capacity, with below function, 

Props("C",'T',300,'P',101.325,"MEG-20%");

i am receiving 1.INF unknown value.

Coolprop  version 5.0.8
Windows 8 MSVC 2010 Ultimate
Static Lib built with CMAKE.

Thanks,
Selva

**Comment by jowr** [comment]
Hi, two issues here:

  -1) Can you use PropsSI instead? Props is deprecated and will be removed from the interface with version .
  -2) You have to tell CoolProp that it is incompressible. Please read the docs to find out what changed from version 4 to version 5. This is one of the issues where version 5 is not backward compatible. 

Having said all that, `Props("C",'T',300,'P',101.325,"INCOMP::MEG-20%");` just works fin :wink:
