### ISSUE TITLE
 Bug with R245fa conductivity

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#604]
A follow up on https://github.com/ibell/coolprop/issues/255 .

@evinvodkha wrote: 
Hi,
Using Coolprop 5.0.8 in Python, the following line raises an exception :
cp.PropsSI('L','P',5e5,'T',373,'R245fa')
saying:
ValueError: Conformal state solver failed; error was _phase is unknown : PropsSI("L","P",500000,"T",373,"R245fa")
However the line:
cp.PropsSI('L','P',5e5,'T',373,'REFPROP-R245fa')
works fine, giving result 0.0193013951388472
Any idea?
Thanks for the great work !
Thomas.

my reply:
Have you checked where the phase boundary is? CoolProp tells you that it does not know the phase. REFPROP might do something special (interpolation?) in the two-phase region. This is disabled by default in CoolProp because there are many different ways to interpolate and we want the user to be aware of the problem.

**Comment by evinvodkha** [comment]
The saturation pressure of R245fa at 100°C is 1269 kPa, therefore (500 kPa, 100°C) should be vapor.

I tried with other (pressure, temperature) points with R245fa in the vapour phase, and I always get the same error. However, there is no problem with other fluids like R134a for instance. It seems linked to the R245fa

**Comment by ibell** [comment]
Is it *all* points for R245fa?

**Comment by evinvodkha** [comment]
Yes, the problem occurs only when using R245fa, if that's what you mean

**Comment by ibell** [comment]
Works fine in development version:
```python
import CoolProp
print CoolProp.CoolProp.PropsSI("L","P",5e5,"T",373,"R245fa")
```
yields
```
0.0199619443758
```
