### ISSUE TITLE
CMake changes

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#605]
I just rewrote the library switches for CMake, see https://github.com/CoolProp/CoolProp/blob/master/CMakeLists.txt#L174-L318. 

I hope I did not break anything, but we still have to 
  - [x] Use the new notation in the buildbot config
  - [x] Document the new switches on the website
  - [x] Modify release scripts etc to match the new binary location?
  - [x] Remove the converters that translate the old options to the new options in CMakeLists.txt

I hope this is more generic and saves work in the future.

**Comment by ibell** [comment]
I think you broke quite a lot :( - a lot of the builds are failing now

**Comment by jowr** [comment]
Yes, I can see that...

**Comment by jowr** [comment]
Well, I think most builds work again. The Fortran problems still have to be solved.

**Comment by ibell** [comment]
Can you reboot your IPU slave that is doing the sdist?  It seems to be hung
up and I cant reboot it remotely.

**Comment by ibell** [comment]
Thanks for taking a crack at this! I think we should do something similar for all the SWIG based wrappers.  It will restore a certain level of sanity to the build process.

**Comment by jowr** [comment]
I hope we are somewhat back in business. @ibell, can you have a look at the Python builds for Windows? It is really difficult to debug using buildslaves only and maybe you find the problem straight away when doing a local build.

Are there any problems with the repository? These errors do not look familiar: http://www.coolprop.dreamhosters.com:8010/builders/EES-windows/builds/1068/steps/git/logs/stdio

**Comment by ibell** [comment]
That's a new one - how about doing clean builds for the python guys?

**Comment by jowr** [comment]
I think GitHub was down. I scheduled a rebuild...

**Comment by jowr** [comment]
Very nice, thank you Cython magician.

**Comment by ibell** [comment]
What I did I don't think should have fixed anything, I think it just needed a clean actually.

**Comment by ibell** [comment]
Should we leave the remove for 5.2?  So we can better document it?

**Comment by jowr** [comment]
I think it is done already...
