### ISSUE TITLE
Host development python binaries somewhere

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#613]
I suspect we are getting some traffic on dreamhosters machine since we direct people to download development python versions like this:
```
pip install --find-links http://www.coolprop.dreamhosters.com:8010/binaries/Python/ -U --force-reinstall CoolProp
```
would be better if we could put the files somewhere on sourceforge and do the same sort of thing

@jowr - ideas?

**Comment by jowr** [comment]
Yes, agreed, but I have no solution at the moment. BTW, who directs people to that download? I certainly don't :wink: .

The only thing I can think of is a simple directory on the web server. Our main issue is the buildbot master that is allergic to traffic, hosting the binaries in a directory that is available via port 80 would at least move traffic from the python server to the ordinary web server.

**Comment by jowr** [comment]
Things to do: 
  - [ ] make symlink to `/binaries` and create a script that fixes the permissions
  - [ ] Remove all links to `:8010/binaries` from the docs 
  - [ ] Make web server log traffic and count visitors

**Comment by jowr** [comment]
We have a slight permission problem. The uploaded binaries are not readable for the webserver by default. I made a cron task that checks permissions every 15 minutes and fixes them if required. That means that it might take 15 minutes for the binaries to show up on the web page after they have been built. I hope that is acceptable.

**Comment by ibell** [comment]
Our website directs people there :
http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#automatic-installation
:)

Otherwise there is no easy way to pip install, you would have to download
the correct wheel, then pip install that wheel.  Not so nice to automate.

**Comment by jowr** [comment]
It does not anymore... Have a look at the link you posted :smile:

**Comment by ibell** [comment]
Ah right, I should open my eyes, I saw dreamhosters and I automatically
assumed it was the same.
