### ISSUE TITLE
Ammonia T-P saturation calculation deviation

### ISSUE THREAD

**Issue by ChenYuChih** [CoolProp/CoolProp#615]
Hello Mr. Bell,

Few days ago, I did some strange tests with CoolProp Library. I found that in some range the iteration result of T-P saturation calculation is not exactly the same as original input for pure fluid. For example,

A = PropsSI("P","T",292.15,"Q",1,"R717"); // A = 830387.585
B = PropsSI("T","P",A,"Q",1,"R717"); // B = 292.15011 > 292.15

So far I just know that it happens on Ammonia around T= 292.15 only. But I am not sure if it would occur for other conditions or fluids. Is it a bug? If not, how to reduce the error?

Thanks you !

Best Regards,
ChenYuChih(David Chen)

**Comment by ibell** [comment]
The saturation calls are iterative, so you should not expect them to be
exactly the same.  In this range though I would expect better consistency.
I'll take a look.

**Comment by ibell** [comment]
Yeah consistency is pretty good, but could be better.  REFPROP fares better by quite a lot.
```
import numpy as np, matplotlib.pyplot as plt, CoolProp
fld = 'Ammonia'
T = np.linspace(250, CoolProp.CoolProp.PropsSI('Tcrit',fld),100000)
p = CoolProp.CoolProp.PropsSI('P','T',T,'Q',0,fld)
T2 = CoolProp.CoolProp.PropsSI('T','P',p,'Q',0,fld)

plt.plot(T, T2/T-1)
plt.xlabel('T')
plt.ylabel('T(p)/T-1')
plt.tight_layout()
plt.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/1859947/7312530/f4772914-ea08-11e4-9f2c-2162d33fe952.png)

**Comment by ChenYuChih** [comment]
Okay.....So from the chart you plot, the maximum deviation of temperature would be about 0.0003 degC.( = 8E-7 * 350 K)
As long as I set the temperature precision to 1E-3, the iteration use should not be a problem. But I still wonder if other fluid has the same deviation scale. How precise should I set for general fluid application?

**Comment by ibell** [comment]
1e-3 should always be good, I think I can tighten up a little bit the
convergence criterion for T(p) which should help with this.  I'll have a go
tonight.

**Comment by ibell** [comment]
![figure_2](https://cloud.githubusercontent.com/assets/1859947/7330441/df00b2a0-eaab-11e4-91f2-078fdb8aee1a.png)
