### ISSUE TITLE
TTSE Input Param (Water)

### ISSUE THREAD

**Issue by 11718pauld** [CoolProp/CoolProp#621]
[Input Param](http://www.coolprop.org/_static/doxygen/html/namespace_cool_prop.html#a4b49eeb37210a720b188f493955d8364) as per Low Level Interface yields error for iviscosity
```python
import CoolProp.CoolProp as CPpy
import CoolProp.constants as CPc
import numpy as np
import time

def PyACTTSE(p,h,vis,st,CPc):
    HmassP_INPUTS = CPc.HmassP_INPUTS
    for i in range(1, len):
        st.update(HmassP_INPUTS, h[i], p[i])
        st.keyed_output(CPc.iviscosity)
        
len = 100
vis = np.zeros(len)
h = 1e3*np.linspace(700,1500,len)
p = 1e6*np.linspace(2.8,3,len)

st = CPpy.AbstractState('TTSE&HEOS','Water')
t1 = time.time()
PyACTTSE(p,h,vis,st,CPc)
t2 = time.time()
print('Total : %f\tPer Call : %e'%((t2 - t1),((t2 - t1)/len)))
```
```python
ValueError                                Traceback (most recent call last)
<ipython-input-4-d3f67a2db7dc> in <module>()
     17 st = CPpy.AbstractState('TTSE&HEOS','Water')
     18 t1 = time.time()
---> 19 PyACTTSE(p,h,vis,st,CPc)
     20 t2 = time.time()
     21 print('Total : %f\tPer Call : %e'%((t2 - t1),((t2 - t1)/len)))

<ipython-input-4-d3f67a2db7dc> in PyACTTSE(p, h, vis, st, CPc)
      8     for i in range(1, len):
      9         st.update(HmassP_INPUTS, h[i], p[i])
---> 10         st.keyed_output(CPc.iviscosity)
     11 
     12 len = 100

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.keyed_output (CoolProp/CoolProp.cpp:10591)()

CoolProp/AbstractState.pyx in CoolProp.CoolProp.AbstractState.keyed_output (CoolProp/CoolProp.cpp:10526)()

ValueError: invalid key
```
Same for few others as well.

**Comment by ibell** [comment]
This is a bug for viscosity, it is definitely implemented.  I'll fix it.

Not everything is implemented for the tabular backends, can you provide a wishlist of parameters that you would like to have access to but that you do not have access to currently?

**Comment by jowr** [comment]
Thank you for all the bug reports @11718pauld. For future reference,could you also provide the CoolProp version you are using? Something like 
```
print(CoolProp.__version__)
print(CoolProp.__revision__)
```
should be all you need.

**Comment by 11718pauld** [comment]
As of now, I require
1. Quality
2. Density
3. Viscosity
4. Temperature
5. d(rho)/dh|p
6. d(rho)/dp|h
(for both 1 & 2 Phase with Inputs being Pressure and Enthalpy)
7. Splined Density & its derivatives

Fluid : Water and Heavy Water

I heavily require the TTSE for speed for what ever param's it is possible. 
(I shall check as per the latest build, and then inform regarding the param's which are not accessible)

@jowr 
```python
>>> print(CoolProp.__version__)
5.1.0dev
```
```python
>>> print(CoolProp.__revision__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__revision__'
```

**Comment by jowr** [comment]
Sorry, I think it should be `print(CoolProp.__gitrevision__)`
