### ISSUE TITLE
CoolProp 5.0.8 from PyPI: Python import error

### ISSUE THREAD

**Issue by frisbee00** [CoolProp/CoolProp#623]
Hi,
<b>CoolProp 5.0.8 + Python 3.4.3</b> on Arch Linux

Installed CoolProp 5.0.8 from PyPI and using:

<pre>import CoolProp.CoolProp as CP</pre>

throws the error:
<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/CoolProp/__init__.py", line 5, in <module>
    from . import constants
  File "/usr/lib/python3.4/site-packages/CoolProp/constants.py", line 5, in <module>
    from . import _constants
ImportError: /usr/lib/python3.4/site-packages/CoolProp/_constants.cpython-34m.so: undefined symbol: AnnotateIgnoreReadsBegin
</pre>

**Comment by jowr** [comment]
Could this be a permission problem? It looks like you installed as root and now you run as normal user. Have you tried a local install? 
```
sudo pip uninstall coolprop
pip install coolprop --user
```

**Comment by ibell** [comment]
Also, you could try to do a few ``sudo pip uninstall coolprop`` just to make sure you really have removed all the versions

**Comment by frisbee00** [comment]
Looks fine now after a :
<pre>sudo pip uninstall Coolprop</pre>
and installing <b>CoolProp 5.1.0</b> from PyPI
Closing the issue.
