### ISSUE TITLE
Stability in two-phase region

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#624]
It seems like we introduced some problems lately. During the speed tests I noticed that certain areas do not get covered anymore. My code automatically removes faulty points and large blank spots thus mean that there is a stability problem because all points in that area get marked as faulty. Sorry for the colour, but magenta makes it easy to spot the empty spots. The example below shows air, but the same issues occur for (at least) n-pentane, R134a and CO2 as well. The shape of the faulty region is also similar regardless of the fluid.

**Comment by jowr** [comment]
Would it make sense to include the 2-phase region in the consistency plots?

**Comment by jowr** [comment]
It looks like the f(rho,T) solver does not work reliably in the two-phase region. I have no idea why, but this could be related to the "holes" in the performance plots.

**Comment by jowr** [comment]
Here are the other graphs

Air
---
![timecomp-air 1x4](https://cloud.githubusercontent.com/assets/769593/7338366/f4c699ca-ec49-11e4-95e6-925d716df6b1.jpg)

CO2
------
![timecomp-co2 1x4](https://cloud.githubusercontent.com/assets/769593/7338367/f6a51910-ec49-11e4-94fb-da4c8e8df685.jpg)

n-pentane
-------------
![timecomp-pentane 1x4](https://cloud.githubusercontent.com/assets/769593/7338370/034c8784-ec4a-11e4-898c-c08884376447.jpg)

R134a
--------
![timecomp-r134a 1x4](https://cloud.githubusercontent.com/assets/769593/7338371/05cb67f0-ec4a-11e4-9fa8-e6d14e306705.jpg)

**Comment by jowr** [comment]
The consistency plots are ready: http://www.coolprop.dreamhosters.com/binaries/sphinx/_downloads/CarbonDioxide1.pdf

**Comment by ibell** [comment]
:( I'll take a look, has got to be easy to fix.  Thanks for finding this.

**Comment by ibell** [comment]
By the way, the color choice is somewhat an issue because its not possible
to differentiate between max error and missing data point.  What about a
yellow background or something?

**Comment by ibell** [comment]
I think we can safely close this issue.  The situation is much better than before.

**Comment by jowr** [comment]
Indeed, I just ran some new speed tests, watch #411 for more updates.
