### ISSUE TITLE
how to obtain properties of mixtures

### ISSUE THREAD

**Issue by jbensabat** [CoolProp/CoolProp#625]
hello 
I am trying to use coolprop with a mixture of CO2 and H2O
I am working with the c++ interface 
is it possible to get an example on how to do it ?
I tried by analogy with the c++ example to call the following function 
PropsSI("Dmolar","T",298,"P",1e5,"CO2[0.5]&Water[0.5]") but I get an error
any help would be most welcome 
best

**Comment by jowr** [comment]
Have you read the docs at http://coolprop.sourceforge.net/coolprop/HighLevelAPI.html#c-sample-code ? You have to make sure that you use components that can be mixed, as documented here: http://coolprop.sourceforge.net/fluid_properties/Mixtures.html#binary-pairs

**Comment by jowr** [comment]
It also helps a lot to post the error you are getting, often the error message tells you what is wrong.

**Comment by ibell** [comment]
That binary pair should work, though Water creates weird mixture with a lot
of other components.  Can you please provide a minimal example that doesn't
work along with the error message?

**Comment by jbensabat** [comment]
Hi
I am not sure I understand this question.
Usually I can provide a temperature and pressure and then get the mass fractions of the CO2 and H2O and their phase state, and dissolved in each phase.
How can we do that in Coolprop ?
Best
Jac

**Comment by jbensabat** [comment]
In addition to my last mail I do not know the proper syntax for that
Best
Jac

**Comment by jowr** [comment]
The approach here is different, CoolProp assumes that you know the bulk composition. You are looking for a low-level functionality that is not provided by the PropsSI function. You could use CoolProp for your purpose, but I would recommend that you browse the source code of http://sourceforge.net/projects/dwsim/ to see how CoolProp can be used in a Chemical Engineering context.

**Comment by jbensabat** [comment]
Hi
Thanks for your message
I tried the following PropsSI("Dmolar","T",298,"P",1e6,"water[0.5]&co2[0.5]") and I got #INF as result
I went with the debugger and it seems that the software does not recognize the mixture thus giving and exception
Best
Jac

**Comment by jowr** [comment]
How do you compile your code? For your example, I get: 
`ValueError: 
Bad phase to solver_rho_Tp_SRK: PropsSI("Dmolar","T",298,"P",1e6,"Water[0.5]&CO2[0.5]")`
... but another concentration works fine
`PropsSI("Dmolar","T",298,"P",1e6,"Water[0.95]&CO2[0.05]") = 53035.55855461623`

**Comment by jbensabat** [comment]
I have compiled the code with Visual Studio 2012.
Indeed when I am trying the mixture ,"Water[0.95]&CO2[0.05]" I get the same value as you.
Thanks
Jac

**Comment by jowr** [comment]
I recommend to use the source code directly instead of the library. That allows you debug CoolProp and will provide you with the correct error messages. DLLs have to be bullet-proof and that is why there is no exception. There is also the `get_global_param("errstring")` function, which micht be useful for you. 

Are you sure that 50/50 water and CO2 should work? Have you checked the reference for the EOS? PhD thesis Gernert 2013, I think.

**Comment by jbensabat** [comment]
Hi
Thanks
Using visual studio and a static lib you can debug exactly the same way as with the source
I do not know if 0.5-0.5 works for the pressure and temperature that I have chosen but I shall look into Gernert
Best
Jac

**Comment by jowr** [comment]
You are welcome, please feel free to reopen this issue if you keep experiencing problems. I'll close it for now.
