### ISSUE TITLE
Dry air enthalpy

### ISSUE THREAD

**Issue by acuiko** [CoolProp/CoolProp#628]
Hi,
ISSUE #585 is closed, but I still get an error when try to calculate something like
CoolProp.HAPropsSI("T", "P", 101325, "H", 202520, "W", 0);

**Comment by ibell** [comment]
I can take another look, see what is going on.  What operating system,
wrapper, etc.?

**Comment by ibell** [comment]
This works fine on linux, fails on windows.  To be continued.
