### ISSUE TITLE
Handle PT inputs around saturation in a better way with BICUBIC

### ISSUE THREAD

**Issue by paarfi** [CoolProp/CoolProp#629]
I'm getting different values for entropy between the EOS and using the Bicubic. Do they use different reference points by default, or is there some other problem?

double p = 1350770;
double t = 308;
AbstractState eos = AbstractState.factory("HEOS", "R717");
eos.update(input_pairs.PT_INPUTS, p, t);
double sEos = eos.smass();

AbstractState bicubic = AbstractState.factory("BICUBIC&HEOS", "R717");
bicubic.update(input_pairs.PT_INPUTS, p, t);
double sBicubic = bicubic.smass();

sEos = 2035.8210382395168
sBicubic = 3198.0584779984738

**Comment by ibell** [comment]
That's a bug.  I'll take a look.

**Comment by ibell** [comment]
Are you very close to saturation curve?  Maybe it gave you vapor solution
instead of liquid solution.  P-T is always a bit dangerous from that
standpoint.

**Comment by ibell** [comment]
Yup, Ts = 308.150011408 for p = 1350770 Pa.  P-T is giving you the vapor solution.  There isn't much that can be done about this unfortunately.  In p-T coordinates, if the cell overlaps the saturation curve, you get the wrong solution.  Just stay away from the saturation curve.  You might want to try TTSE for P,T, as that should give you the "right" solution.

For python
``` python
import CoolProp
p = 1350770;
t = 308;
eos = CoolProp.AbstractState("HEOS", "R717");
eos.update(CoolProp.PT_INPUTS, p, t);
sEos = eos.smass();
Ts = CoolProp.CoolProp.PropsSI('T','P',p,'Q',0,'R717')
print Ts

bicubic = CoolProp.AbstractState("TTSE&HEOS", "R717");
bicubic.update(CoolProp.PT_INPUTS, p, t);
sBicubic = bicubic.smass();

print sEos, sBicubic
``` 
yields
```
2035.82103824 2035.82086485
```

**Comment by paarfi** [comment]
Thanks. That makes sense. I don't have the choice to stay away from the saturation curve, but at least I can test Q after the fact and see if it gave me the wrong phase.

**Comment by ibell** [comment]
Actually,  I think we can be a bit more intelligent about this, and at least give a reasonable error.

Currently, the Q you get from BICUBIC is not actually useful because it is not specific to liquid or vapor, but I have some ideas about how to resolve this problem.

You are not the only person that will run into issues with this, so we should solve the problem in some fashion

**Comment by ibell** [comment]
Somehow detect when the cell overlaps the saturation curve, then once that is done, back off away from the saturation curve and extrapolate.
