### ISSUE TITLE
Methane conductivity

### ISSUE THREAD

**Issue by jl230** [CoolProp/CoolProp#631]
Related to #547 - Viscosity of methane is functional, but missing conductivity. Some common correlations that I am aware of include Kumakawa 1986, Chin 1995, and Cook 1984.

**Comment by ibell** [comment]
Can you provide references please?

**Comment by ibell** [comment]
And it needs to cover the whole surface, liquid/vapor/critical

**Comment by jl230** [comment]
Cook:
https://ia600505.us.archive.org/2/items/nasa_techdoc_19850004010/19850004010.pdf

Will look for more in-depth tables.

**Comment by jl230** [comment]
Another:
http://www.nist.gov/data/PDFfiles/jpcrd397.pdf

**Comment by ibell** [comment]
Again, it needs to cover the full surface, it seems about the only model
available is the one in REFPROP, which is ancient:
http://www.nist.gov/data/PDFfiles/jpcrd362.pdf

**Comment by jl230** [comment]
Yes, that is the only complete model I know of. Can find bits and pieces around, but nothing as complete.

**Comment by ibell** [comment]
Which actually doesn't seem as horrible as I remember.

**Comment by jl230** [comment]
It is a good reference, I have used it in the past, though like you said, very old.

**Comment by jl230** [comment]
Found the other reference I have used, might be able to compare to Friend.
http://www.nist.gov/data/PDFfiles/jpcrd97.pdf
