### ISSUE TITLE
CoolProp - ExternalMedia -Initialization issue for fluid SES36

### ISSUE THREAD

**Issue by labothap** [CoolProp/CoolProp#633]
When modelling Modelica models with SES36 during the initialization process:
ExternalMedia.Media.CoolPropMedium fails to find a consinstent value of density as a function of 
temperature and pressure.

The same models work fine with CoolProp2Modelica.

**Comment by jowr** [comment]
Could you provide the inputs that fail or the error message you get? I hope this is going to be solved by the new Modelica wrapper in version 5.1.1, but please provide the details.

**Comment by labothap** [comment]
Ok. Below a screenprint of how the error starts:
![dslog](https://cloud.githubusercontent.com/assets/5320839/7368591/e077b060-eda9-11e4-99e0-ec3441455d55.PNG)

The solver then keeps iterating and the following is the last
![dslog_final](https://cloud.githubusercontent.com/assets/5320839/7368618/43400cf6-edaa-11e4-88f1-9f68e2bf88ed.PNG)
 part of the dslog:

**Comment by ibell** [comment]
Any idea @jowr?

**Comment by jowr** [comment]
I assume you are running H,P inputs right? Have you tried modifying the default values for h and p for the fluid? Have you tried playing with the nominal values as well? I know thos are not the very structured approaches, but thats all I can think of. Have you been able to reproduce the problem in a smaller system? I can see that you work with heat exchangers, could you isolate the behaviour?

**Comment by ibell** [comment]
Can you turn on debug?

**Comment by ibell** [comment]
Any progress here?

**Comment by ibell** [comment]
Ok, due to a lack of feedback, I'm going to close this issue.  Please reopen if you can give us inputs that fail.
