### ISSUE TITLE
Error surface tension in CoolProp v5.1.0

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#636]
Updating to CP v5.1.0, I got the following error:

ValueError: p is not a valid number : PropsSI("I","T",328.9778772,"Q",0.5,"R410A")

while CP v5.0.8 gives not error!

**Comment by jowr** [comment]
Is that a surprise? Please correct me if I am wrong, but I would not know how to calculate the surface tension of a mixture of gas and liquid.

**Comment by ibell** [comment]
There are correlations for the pseudo - pure though

**Comment by ibell** [comment]
This should be an error, but a different error than what you got. 

If you want to get the surface tension directly, see #640, I'm fixing this.

**Comment by ibell** [comment]
Basically, 0 < Q < 1 is undefined behavior for pseudo-pure fluids since you don't know what is happening with the mole fractions of liquid and vapor in equilibrium.

**Comment by ibell** [comment]
You need to figure out how you want to handle it yourself.

**Comment by bo3mrh** [comment]
Thank you. This was helpful.

**Comment by ibell** [comment]
Does that make sense to you?

**Comment by bo3mrh** [comment]
Yes.
I thought the surface tension is a function of quality!
