### ISSUE TITLE
Version 4.2.5 CoolProp  to calculate the Saturation specific heat of the air 

### ISSUE THREAD

**Issue by daidog** [CoolProp/CoolProp#643]
Hi, Bell. Need you help, it seem that  the 4.2.5 CoolProp can't calculate the Saturation specific heat of the air by using function cair_sat(T) under MATLAB platform. Thanks!     By the way, under the  the MATLAB platform, I found the efficiency of the 4+ CoolProp code is much quicker than the 5+ CoolProp.

**Comment by ibell** [comment]
4.2.5 is no longer actively developed, and we are no longer accepting bug reports on it.  I think cair_sat should work in MATLAB in v5.  Please let me know if this is not the case.

MATLAB has very (!) poor support for C++, and we went with a different solution in v5 than in v4.  I know it is slower, but there is nothing to be done.  Don't use MATLAB, and use python, or c#, or ... if you want speed and a high-level interface.

**Comment by daidog** [comment]
Thanks, Bell. My currently Maltlab Version is 2013a, I think that's the problem, and thank you for your advice.
