### ISSUE TITLE
Unable to use input parameter [Pcrit] in Props1SI for fluid HEOS::R245fa[0.375]&R134a[0.625]

### ISSUE THREAD

**Issue by davideziviani** [CoolProp/CoolProp#649]
Hey !!  I was trying to call 'pcrit' for the zeotropic mixture 'R245fa[0.375]&R134a[0.625]' but I got the following ValueError:

 File "CoolProp\CoolProp.pyx", line 210, in CoolProp.CoolProp.PropsSI(CoolProp\CoolProp.cpp:21548)
  File "CoolProp\CoolProp.pyx", line 224, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:20566)
  File "CoolProp\CoolProp.pyx", line 172, in CoolProp.CoolProp.__Props_err1 (CoolProp\CoolProp.cpp:19438)
ValueError: Unable to use input parameter [Pcrit] in Props1SI for fluid HEOS::R245fa[0.375]&R134a[0.625]; error was No outputs were able to be calculated : PropsSI("Pcrit","",0,"",0,"R245fa[0.375]&R134a[0.625]") :: inputs were :"HEOS::R245fa[0.375]&R134a[0.625]","Pcrit"

I have tried 'HEOS::R245fa[0.375]&R134a[0.625]' with the same results. Of course only 'REFPROP::R245fa[0.375]&R134a[0.625]' worked.

**Comment by ibell** [comment]
This is actually kind of hard, since for a mixture the critical point is not so easy to find.

**Comment by ibell** [comment]
As a workaround, one way you could do it is to generate a phase envelope for that mixture composition (http://www.coolprop.org/fluid_properties/Mixtures.html#phase-envelope) and interpolate to find the temperature where the densities of liquid and vapor are the same - that is your critical point.  It's not so nice, I know.  I'll see what I can do about fixing this, but sadly it is going on the wishlist.

**Comment by ibell** [comment]
All of these work now:
``` c++
double Dc1 = PropsSI("rhomolar_critical","",0,"",0,"HEOS::R245fa[0.375]&R134a[0.625]");
double Dc2 = PropsSI("rhomolar_critical","",0,"",0,"REFPROP::R245fa[0.375]&R134a[0.625]");
double Tc1 = PropsSI("T_critical","",0,"",0,"HEOS::R245fa[0.375]&R134a[0.625]");
double Tc2 = PropsSI("T_critical","",0,"",0,"REFPROP::R245fa[0.375]&R134a[0.625]");
double pc1 = PropsSI("p_critical","",0,"",0,"HEOS::R245fa[0.375]&R134a[0.625]");
double pc2 = PropsSI("p_critical","",0,"",0,"REFPROP::R245fa[0.375]&R134a[0.625]");
```
