### ISSUE TITLE
Add ability to calculate Ideal curves

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#654]
See Lemmon and Jacobsen 2009

**Comment by ibell** [comment]
@thorade - I think this one is actually not as hard as I thought originally.  I need this for my day job, so I'll probably do this next week/ tomorrow unless you want to work on it together.

**Comment by thorade** [comment]
Ideal curves are as difficult or as easy as a pT (or similar) flash, I would say.
I have a deadline on May 20th, after that I want to look at #581.
Even though I have not yet contributed any code to CoolProp, I am in principle interested in doing so...

**Comment by thorade** [comment]
http://dx.doi.org/10.1007/BF02575343
http://dx.doi.org/10.1351/pac199769061237
http://dx.doi.org/10.1016/S0378-3812(98)00477-4

**Comment by ibell** [comment]
Well that worked (R125):

![idealcurves](https://cloud.githubusercontent.com/assets/1859947/7664270/aa3e6d90-fb3c-11e4-974a-41d87a71751d.png)

**Comment by ibell** [comment]
Would be nice to do this at the C++ level, but I'm not sure about a good API.  Once we figure out the interface, it is a straightforward translation from python to C++

**Comment by ibell** [comment]
Maybe move into the AbstractState class instead.  TBD.

**Comment by ibell** [comment]
Now in python:
```
import CoolProp, matplotlib.pyplot as plt
AS = CoolProp.AbstractState('HEOS','Water')
for curve in ['Joule-Thomson', 'Joule-Inversion', 'Ideal', 'Boyle']:
    T, p = AS.ideal_curve(curve)
    plt.plot(T, p)
plt.xscale('log')
plt.yscale('log')
plt.show()
```
yields
![ideal](https://cloud.githubusercontent.com/assets/1859947/7953619/51dfe7b8-0984-11e5-8fdc-cbda84d15d9b.png)
