### ISSUE TITLE
More ancillary functions

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#655]
I could use a short update regarding the ancillary functions. Why are the enthalpy and entropy functions named differently `sL` and `sLV` instead of `sV`? Do they work at all? It seems like they are not used anywhere and they are also not accessible from outside the HEOS state object...

**Comment by ibell** [comment]
The reason I did it it like that with the h,s ancillaries is that hL v T looks pretty clean, and hV-hL v. T is relatively clean, while hV v. T is not monotonic.

These ancillaries were at one point in use for some the flash routines (T,X) I think.

**Comment by ibell** [comment]
Can we close this issue?

**Comment by jowr** [comment]
Ok, was just curious.
