### ISSUE TITLE
Vapor mass quality = 1 generates error for pseudo-pures

### ISSUE THREAD

**Issue by Finnepinnen** [CoolProp/CoolProp#663]
Hi,

when evaluating EoS in a point on the envelope the following error occurs:
Warning: PQ:

Thesis: It only happens with refrigerants having temperature glide.

<-- Example in MatLab R2014b -->

import CoolProp.*;

Temp_Cond = 313.15;

% For refrigerant R22
Ref_1 = CoolProp.AbstractState.factory('REFPROP', 'R22');

Ref_1.update(CoolProp.QT_INPUTS, 1, Temp_Cond);
p_31 = Ref_1.p();

Ref_1.update(CoolProp.PQ_INPUTS, p_31, 0);

% For refrigerant R407C
Ref_2 = CoolProp.AbstractState.factory('REFPROP', 'R407C');

Ref_2.update(CoolProp.QT_INPUTS, 1, Temp_Cond);
p_32 = Ref_2.p();

% This works
Ref_2.update(CoolProp.PQ_INPUTS, p_32, 1e-10);

% This doesn't work
Ref_2.update(CoolProp.PQ_INPUTS, p_32, 1e-11);

% Neither does this
Ref_2.update(CoolProp.PQ_INPUTS, p_32, 0);

<-- End of example -->

Best regards
/Peter

**Comment by jowr** [comment]
I can confirm this bug. It has to be something with the REFPROP backend. I get the following output from Python:
```
from CoolProp.CoolProp import PropsSI
PropsSI("P","T",313.5,"Q",0,"REFPROP::R407C")
763854.5019926345
PropsSI("P","T",313.5,"Q",0,"HEOS::R407C")
1763854.501992638
P = PropsSI("P","T",313.5,"Q",0,"REFPROP::R407C")
PropsSI("T","P",P,"Q",0,"REFPROP::R407C")
---------------------------------------------------------------------------
UnicodeDecodeError: 
'ascii' codec can't decode byte 0xb4 in position 259: ordinal not in range(128)
---------------------------------------------------------------------------
PropsSI("T","P",P,"Q",0,"HEOS::R407C")
313.4999999999999
PropsSI("T","P",P,"Q",1e-5,"REFPROP::R407C")
313.5000485245311
```
@Finnepinnen , do you get another error message? Mine seems to come from Python and yours might be different since you are using MATLAB...

**Comment by Finnepinnen** [comment]
This is the error that I get:

Warning: PQ: 
Error using CoolPropMATLAB_wrap
Failure in function AbstractState_update.

Error in CoolProp.AbstractState/update (line 22)
      [varargout{1:nargout}] = CoolPropMATLAB_wrap(130,'AbstractState_update',self,varargin{:});

Error in SwigRef/subsref (line 26)
      [varargout{1:nargout}] = builtin('subsref',self,S);

Error in bug_example (line 23)
Ref_2.update(CoolProp.PQ_INPUTS, p_32, 1e-11);

**Comment by ibell** [comment]
This looks to be a REFPROP bug.  It seems it has unicode in the error
message, let me debug a bit more.

**Comment by ibell** [comment]
Or not, it works fine in REFPROP, seems like a bug in REFPROP backend.

**Comment by ibell** [comment]
I see the problem, but I'm not sure how to fix it - PPF cannot be used with
SATTP function, but there is no way to determine whether a fluid is pure or
pseudo-pure in REFPROP as far as I can tell.
