### ISSUE TITLE
Viscosity convergence issue

### ISSUE THREAD

**Issue by paarfi** [CoolProp/CoolProp#665]
double visc = CoolProp.PropsSI("V", "T", 233.15, "Q", 1, "R32");
conformal_state_solver took too many iterations; residual is 9.04098e-005; prior was 9.07048e-005

**Comment by ibell** [comment]
Ah, the joys of ECS...

**Comment by ibell** [comment]
I can replicate, but don't have an obvious solution.

**Comment by paarfi** [comment]
Heh. I've been there. I've fallen back on NIST for R32 for now. Hopefully a solution will turn up.
