### ISSUE TITLE
R wrapper

### ISSUE THREAD

**Issue by mihirparadkar** [CoolProp/CoolProp#668]
Could an R wrapper be added? I don't know of any packages that even come close to the functionality of CoolProp and it'd be really useful to have in R, even if it's a simple set of ffi calls around the C++ shared library.

**Comment by ibell** [comment]
Yes, this would be very simple in linux, slightly less so in windows.  I've
done similar for REFPROP, could do so for CoolProp.

**Comment by ibell** [comment]
Are you willing to do some testing?  Let me know what version of R you use, what platform, etc.

**Comment by mihirparadkar** [comment]
Yes, of course. I primarily use R 3.2.0 on 32-bit Ubuntu, but I also use R 3.1.3 on 64-bit Windows 7.

**Comment by ibell** [comment]
Hmm, I am not sure how important the version of R is in terms of cross-version compatibility, but I'll put some stuff together, should be a week or so.

**Comment by mihirparadkar** [comment]
Thanks. Once I have what you put together and some basic instructions on how to install/import the library, I'll make sure to give my feedback.

**Comment by AntonioCarrilloAndres** [comment]
Hello, I was searching for a CoolProp R wrapper and found this conversation. I think it will be great to have this wrapper. I use R on 64 bit windows 7. Thank you.

**Comment by ibell** [comment]
Yes it will be great, though I'm not sure when Ill have a chance to finish
it.  Should only take a few hours once I sit down and get at it.

**Comment by AntonioCarrilloAndres** [comment]
I am sure that a lot of people will thank  you if you manage to finish the R wrapper!

**Comment by ibell** [comment]
Ok, working on windows, and should basically be working on linux soon.  One or two little bugs to resolve.

**Comment by ibell** [comment]
Weirdly, it seems to be working fine on windows, and I am running into a few bugs that I don't understand on linux and OSX.  Usually it is the other way around.

**Comment by ibell** [comment]
Ready for some testing I think.  Files are up at http://www.coolprop.dreamhosters.com:8010/binaries/R/ .  Docs are ready but not building properly now.  Download Example.R, CoolProp.R,and the shared library for your appropriate platform, place them all in the same directory.  Run the example. On windows, even though it says Windows_32bit, it is actually 64bit.

**Comment by AntonioCarrilloAndres** [comment]
Thank you Ian, I will be happy to test on Win64 and give some feedback

**Comment by AntonioCarrilloAndres** [comment]
I have made a first test on Win64 and seems to be working fine! Now I will try to use it in some research. Thank you again Ian!

**Comment by ibell** [comment]
For curiosity, what version of R do you use?  This R wrapper was compiled
with 3.2.1

**Comment by mihirparadkar** [comment]
Thanks Ian! I'm really excited to try this out but there's a slight problem.
I can test on 64-bit Ubuntu and I use R 3.2.0, but the CoolProp.R and example.R files are compressed in the links (newlines are removed). Is there anywhere else I can download the .R files?

**Comment by ibell** [comment]
If you right-click on the file and "Save As..." it should repair the line
endings.  buildbot does something funny with text files in its server

**Comment by ibell** [comment]
Also, on linux you might need to rebuild it yourself.  Linux is more
special about architecture of binary files.  Instructions are here for now:
https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/R/index.rst

**Comment by mihirparadkar** [comment]
Thank you very much. Surprisingly, it seems to work without building it myself.

**Comment by AntonioCarrilloAndres** [comment]
Ian, I use R 2.15 (I am a bit outdated..)

**Comment by ibell** [comment]
wow... and it still works for you?  That is great news.

**Comment by jowr** [comment]
If you have any problems with the files, please try to download the files using the webserver instead of the buldbot frontend: http://www.coolprop.dreamhosters.com/binaries/R/

**Comment by ibell** [comment]
Ok, tests run and pass on windows, linux and OSX. Finally closing this issue.  Thanks for your patience. Please let us know if you run into any other issues of any kind.
