### ISSUE TITLE
Excel temp calc (S,P) error

### ISSUE THREAD

**Issue by drewtam** [CoolProp/CoolProp#669]
Using the function:
=PropsSI("T","Smass",U166 * 1000,"P",E167 * 1000,"air")
 
I get this error:
“Residual function in secant returned invalid number : PropsSI("T","Smass",4102.133269,"P",3770762.948,"air")”
 
 
At slightly lower pressures and entropy, it works fine.
=PropsSI("T","Smass",4045.265 ,"P",3406908,"air")
=917.38

Windows 7, x64
MS Office 2013
Coolprop 5.1.0, x64
Purpose: iterative isentropic compression/expansion

**Comment by jowr** [comment]
pseudo-pure fluids and especially air do not work great close to the critical pressure, I am not sure this can be improved...

**Comment by ibell** [comment]
I think this might be fixed in the nightly build, I know I fixed some bugs, maybe this one too.  Can you try with that?

**Comment by drewtam** [comment]
I downloaded the x64.dll and xlam from the nightly folder. Pointed excel to the new file. Restarted excel. It performs the same error.

**Comment by ibell** [comment]
Right, it's a bug then, I'll see what I can do.

**Comment by ibell** [comment]
I cannot replicate this behavior.  Even at higher entropies it is working for me:

```
from CoolProp.CoolProp import PropsSI
TTT = PropsSI("T","Smass",4202.133269,"P",3770762.948,"air")
print TTT
```
yields
```
1079.55976714
```

**Comment by ibell** [comment]
Can you give me an exact set of inputs that cause failure?

**Comment by drewtam** [comment]
Ian, thanks for the continued help. I am not understanding what you want me to capture. The original post is exactly what fails...please see the screen shots.
![coolprop_issue_capture](https://cloud.githubusercontent.com/assets/12429491/7632688/7b21fdd0-fa1d-11e4-80db-8efb5404534c.JPG)
![coolprop_issue_capture2](https://cloud.githubusercontent.com/assets/12429491/7632689/7e6bbd96-fa1d-11e4-9edd-797c4331bbe0.JPG)

**Comment by ibell** [comment]
The original post had cell references.  I'm not sure what is going on since
this definitely works in C++/python.  Are you 100% sure you have the
updated version of the DLL? Sometimes it will find an older version even if
you have a newer version installed.

**Comment by drewtam** [comment]
Yes, I had deleted the old dll after downloading the new one. I removed the cell references to make understanding the calc clearer.

**Comment by ibell** [comment]
I have Excel 2010 32-bit and it works just fine for me.

a) Have you made any modifications to the xlam? (the xla is only for older versions of Excel)
b) If you delete your dll file, does it give you an error that it can't find c:\CoolProp\CoolProp_x64.dll ?  If not, it is finding an older version of the DLL on your computer.

**Comment by drewtam** [comment]
Good call! I was deleting the x64.dll from the wrong folder. Update it to the nightly and the temp calc error goes away.


Now I get a new error on the Entropy calc...
  unable to solve 1phase PY flash with Tmin=59.749, Tmax=3000 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Hmolar [109932 J/mol] is above the maximum value of 106246.596602 J/mol : PropsSI("Smass","Hmass",3795290.151,"P",14223634.49,"air")

**Comment by ibell** [comment]
And your PH error is because your temperature=f(P,H) is above Tmax*1.5.
That's not a bug, just a friendly reminder
