### ISSUE TITLE
Low-Level interfacing with MATLAB

### ISSUE THREAD

**Issue by enter802** [CoolProp/CoolProp#670]
I want to compute partial derivatives for the saturation(two-phase) region and hence need to use the Low-Level interface. But I am not sure how to do the interfacing with MATLAB since this is the platform I am using right now. Any help? Thanks in advance!

**Comment by ibell** [comment]
See 8c131017edcebb4684d69c522e1ae2311110a7f4

**Comment by ibell** [comment]
Added some docs to www.coolprop.org/dev/coolprop/LowLevelAPI.html
