### ISSUE TITLE
MATLAB on OSX cannot load REFPROP

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#671]
@jowr - any ideas why?  It works fine with all the other wrapper on OSX, except MATLAB.  Argh.

**Comment by jowr** [comment]
Have you modified the `refpropm.m` according to https://github.com/jowr/librefprop.so? By the way, things would be much(!) easier if NIST could provide the modified file. At the moment, we have to patch it manually to make it work. 

You are more than welcome to contribute to https://github.com/jowr/librefprop.so/milestones/0.7

**Comment by ibell** [comment]
Nah this is calling through CoolProp, no refpropm.m involved.  Are there other dependencies that we might see only on MATLAB on OSX?

**Comment by ibell** [comment]
Could we have a conditional based on the operating system so that we can
integrate refpropm back into REFPROP?  Which would remove the need for
patching?

**Comment by jowr** [comment]
Yes, that is what I am working on in https://github.com/jowr/librefprop.so/tree/addPatch

**Comment by jowr** [comment]
See https://github.com/jowr/librefprop.so/blob/addPatch/matlab/refpropm.m#L197-L230

**Comment by jowr** [comment]
... but to work properly, https://github.com/jowr/librefprop.so/issues/28 has to be fixed.

**Comment by ibell** [comment]
When this is done, let me know and I can integrate it back into REFPROP docs

**Comment by ibell** [comment]
Here's the problem, looks like a clash with the MATLAB gfortran.  Joy.
```
dlopen(librefprop.dylib, 2): Symbol not found: __gfortran_transfer_character_write
  Referenced from: /usr/local/lib/librefprop.dylib
  Expected in: /Applications/MATLAB_R2014a.app/sys/os/maci64/libgfortran.3.dylib
 in /usr/local/lib/librefprop.dylibCould not load librefprop.dylib 
```

**Comment by ibell** [comment]
Seems MATLAB munges the DLL loading path.  As you can see by doing ``exec('env')``

**Comment by ibell** [comment]
Yes, this is the problem.  Can we make librrefprop.so statically link the gfortran library?  That would fix this problem.

**Comment by ibell** [comment]
Closed by https://github.com/jowr/librefprop.so/pull/29
