### ISSUE TITLE
Saturation Point Partial derivatives

### ISSUE THREAD

**Issue by badkoubeh** [CoolProp/CoolProp#679]
I need the partial derivatives of R245fa in saturation points.
I would like to make sure that Coolprop gives me the right value.
For instance, I used the following command in MATLAB:
CoolProp.PropsSI('d(H)/d(P)|T','T',379.3877,'Q',0,'R245fa')
or
CoolProp.PropsSI('d(D)/d(P)|H','P',1450000,'Q',0,'R245fa')
or
CoolProp.PropsSI('d(H)/d(P)|T','T',379.3877,'Q',1,'R245fa')
or
CoolProp.PropsSI('d(D)/d(P)|H','P',1450000,'Q',1,'R245fa')

Do these commands give me the right value?

Thanks,
Babak

**Comment by ibell** [comment]
There are quite a few different options when you start talking about
saturation and two-phase.  Those work ONLY for homogeneous states (liquid,
gas, supercritical).  You need to use the low-level interface otherwise,
see http://www.coolprop.org/dev/coolprop/LowLevelAPI.html

**Comment by ibell** [comment]
Closing for now, please specify more clearly the problem you are trying to solve.

**Comment by badkoubeh** [comment]
Thanks Ian,
It was so helpful.
By the way, I am try to model a heat exchanger which its working fluid is R245fa. That is why I need the partial derivatives ( dh'/dp , dh''/dp , drho'/dp , drho''/dp , drho'/dh and ... ).  
Thanks,
Babak
