### ISSUE TITLE
Tabular backend data range too small for (P,H) inputs and R245fa

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#680]
Either with 5.1.0 (from MATLAB) or 5.1.1dev (from C++), the following happens:

    >> CoolProp.PropsSI('T','Hmolar',97000,'P',500300,'R245fa')
        ans = 571.6983
    >> as=CoolProp.AbstractState.factory('BICUBIC&HEOS','R245fa');
    >> as.update(CoolProp.HmolarP_INPUTS,97000,500300)
        Warning: inputs are not in range, hmolar=97000, p=500300 
        [...]
    >> CoolProp.PropsSI('T','Hmolar',97000,'P',10e5,'R245fa')
        ans = 573.4390
    >> as.update(CoolProp.HmolarP_INPUTS,97000,10e5)
        Warning: inputs are not in range, hmolar=97000, p=1e+006
        [...]
    >> CoolProp.PropsSI('T','Hmolar',85000,'P',10e5,'R245fa')
        ans = 502.9987
    >> as.update(CoolProp.HmolarP_INPUTS,85000,10e5)
        Warning: inputs are not in range, hmolar=85000, p=1e+006
        [...]
    >> CoolProp.PropsSI('T','Hmolar',110000,'P',10e5,'R245fa')
        ans = 645.0882
    >> as.update(CoolProp.HmolarP_INPUTS,110000,10e5)
        Warning: inputs are not in range, hmolar=110000, p=1e+006
        [...]
    >> CoolProp.PropsSI('T','Hmolar',110000,'P',4e5,'R245fa')
        ans = 643.5982
    >> as.update(CoolProp.HmolarP_INPUTS,110000,4e5)
        Warning: inputs are not in range, hmolar=110000, p=400000
        [...]

**Comment by ibell** [comment]
The tables are built up to Tmax, the hard limit on the EOS evaluation is
Tmax*1.5

Tmax for R245fa is 440 K.  So it all makes sense.  I guess we could build
tables up to Tmax*1.5 for consistency's sake, and for fluids like this one
with relatively low max temperatures.

**Comment by Astrinus** [comment]
Thanks, now it make sense.
