### ISSUE TITLE
Error with CP v5.1

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#682]
Am getting the following error when update CP to v5.1.0

```ValueError: unable to solve 1phase PY flash with Tmin=281.213, Tmax=675 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Hmolar [100556 J/mol] is above the maximum value of 62476.4362388 J/mol : PropsSI("T","H",1385343.035,"P",1024032.381,"R410A")```

I didn't get that when running the same code in CP v5.0.8!!!

**Comment by jowr** [comment]
Did you check that your is in the correct range? Where does the enthalpy value come from?

**Comment by bo3mrh** [comment]
My bad .. you are right. I should check that. Thank you tho
