### ISSUE TITLE
some problem and questions for calc in Excel

### ISSUE THREAD

**Issue by hyhzju** [CoolProp/CoolProp#684]
I am calling functions/subroutines in the coolprop.dll file from Excel. And currently have the following problems and questions:

1. to get the maximum pressure, I use =Props1SI("oxygen","PMAX") and it works. However, when I change the substance to nitrogen. It does not give any value ---Empty in the Excel cell. The same problem with some other fluids like helium, argon,..

2. how to use the function phaseSI in Excel?

3. I tried both =get_phase_index("phase_twophase") and =get_phase_index("phase_liquid") in Excel but all produce  the resutls : $NAME?

4. how to get the density, enthalpy, etc of the liquid on the melting line?

5. how to get the maximum density/ minimum specific volume value for any selected fluid?

6. to get the CAS code, I use =Props1SI("Water","CAS"), but I get "Unable to use input parameter [CAS] in Props1SI for fluid Water; error was Output parameter parsing failed; error: Output string is invalid [CAS] : PropsSI("CAS","",0,"",0,"Water")"

**Comment by ibell** [comment]
Most of the things you want are not yet implemented in the Excel wrapper, but could be if you wanted to do it, or if I can find the time to do so.  Supporting Excel is low on my list of priorities, and we need help from CoolProp users.

1) Fluid names are case sensitive.  PMAX should be defined for all fluids.  If not, please file an issue.

2) Not implemented - feel free to do so

3) Not implemented - feel free to do so

4) Not implemented - feel free to do so

5) Not implemented in CoolProp at all

6) It should be get_fluid_param_string("Water","CAS"), but its not implemented yet

**Comment by hyhzju** [comment]
I have figured out No.2 and 6. The get_fluid_param_string function and PhaseSI function are now implemented in my Excel wrapper.  I tried to put as more as possible example of calling all those functions I know in the Excel cells. 

For No.1, I carefully typed the fluid names and still found PMAX worked for oxygen (Oxygen) and many other refrigerant fluids but not for Nitrogen (nitrogen, N2...) as well as argon, helium, etc...

For getting properties of the melting line, any clues for realizing that? Then I will have a try.

**Comment by ibell** [comment]
Please make a pull request with an updated xlam for Excel

That PMAX is a bug, please file a separate issue.

Melting line is currently only accessible from the low-level interface.
Open a new issue if you would like it accessible from the high-level
interface.

**Comment by ibell** [comment]
PMAX doesn't seem to be a problem, see this python code:
```
import CoolProp
for fluid in CoolProp.__fluids__:
    print fluid, CoolProp.CoolProp.PropsSI(fluid,"PMAX")
```
which yields
```
1-Butene 50000000.0
Acetone 700000000.0
Air 2000000000.0
Ammonia 1000000000.0
Argon 1000000000.0
Benzene 500000000.0
CarbonDioxide 800000000.0
CarbonMonoxide 100000000.0
CarbonylSulfide 50000000.0
cis-2-Butene 50000000.0
CycloHexane 250000000.0
Cyclopentane 250000000.0
CycloPropane 28000000.0
D4 30000000.0
D5 30000000.0
D6 30000000.0
Deuterium 2000000000.0
DimethylCarbonate 60000000.0
DimethylEther 50000000.0
Ethane 900000000.0
Ethanol 280000000.0
EthylBenzene 60000000.0
Ethylene 300000000.0
Fluorine 20000000.0
HeavyWater 1000000000.0
Helium 1000000000.0
HFE143m 7200000.0
Hydrogen 2000000000.0
HydrogenSulfide 170000000.0
IsoButane 35000000.0
IsoButene 50000000.0
Isohexane 1000000000.0
Isopentane 1000000000.0
Krypton 200000000.0
m-Xylene 200000000.0
MD2M 30000000.0
MD3M 30000000.0
MD4M 30000000.0
MDM 30000000.0
Methane 1000000000.0
Methanol 500000000.0
MethylLinoleate 50000000.0
MethylLinolenate 50000000.0
MethylOleate 50000000.0
MethylPalmitate 50000000.0
MethylStearate 50000000.0
MM 30000000.0
n-Butane 12000000.0
n-Decane 800000000.0
n-Dodecane 200000000.0
n-Heptane 100000000.0
n-Hexane 92000000.0
n-Nonane 800000000.0
n-Octane 96000000.0
n-Pentane 69000000.0
n-Propane 1000000000.0
n-Undecane 500000000.0
Neon 700000000.0
Neopentane 200000000.0
Nitrogen 2200000000.0
NitrousOxide 50000000.0
o-Xylene 70000000.0
OrthoDeuterium 2000000000.0
OrthoHydrogen 2000000000.0
Oxygen 80000000.0
p-Xylene 200000000.0
ParaDeuterium 2000000000.0
ParaHydrogen 2000000000.0
Propylene 1000000000.0
Propyne 31800000.0
R11 100000000.0
R113 200000000.0
R114 21000000.0
R116 50000000.0
R12 200000000.0
R123 76000000.0
R1233zd(E) 100000000.0
R1234yf 30000000.0
R1234ze(E) 15000000.0
R1234ze(Z) 6000000.0
R124 40000000.0
R125 60000000.0
R13 50000000.0
R134a 70000000.0
R14 51000000.0
R141b 400000000.0
R142b 60000000.0
R143a 150000000.0
R152A 58000000.0
R161 5000000.0
R21 138000000.0
R218 20000000.0
R22 60000000.0
R227EA 60000000.0
R23 120000000.0
R236EA 6000000.0
R236FA 70000000.0
R245fa 200000000.0
R32 70000000.0
R365MFC 35000000.0
R404A 50000000.0
R407C 50000000.0
R41 70000000.0
R410A 50000000.0
R507A 50000000.0
RC318 60000000.0
SES36 500000000.0
SulfurDioxide 35000000.0
SulfurHexafluoride 150000000.0
Toluene 500000000.0
trans-2-Butene 50000000.0
Water 1000000000.0
Xenon 700000000.0
```

**Comment by hyhzju** [comment]
It's weird. The bug only happens to Excel wrapper? 
![image](https://cloud.githubusercontent.com/assets/9360521/8122439/6573b704-10ec-11e5-9199-20f48aaca176.png)

**Comment by ibell** [comment]
Yeah I see the same thing too in Excel with PMAX. Weird.  I'll figure it
out.

**Comment by ibell** [comment]
Aha, it was a bug in the Excel xlam file.  I have fixed it and added
PhaseSI function.
