### ISSUE TITLE
Problem with Hazard output

### ISSUE THREAD

**Issue by babaksamareh** [CoolProp/CoolProp#685]
Hello guys,

When I try to get the FH, HH, or PH outputs, for example:
double FH = CoolProp::Props1SI("Ammonia", "FH");
I get +Inf. Any idea?

Thanks,

**Comment by jowr** [comment]
+Inf indicates an error, use `std::string CoolProp::get_global_param_string("errstring")` to get the latest error message. It is quite likely that the value is undefined for a couple of fluids. We used a lot of information compile by my former colleagues at DTU, but it is far from comlpete even though Ian updated it occasionally.

**Comment by ibell** [comment]
Not all fluids have hazard flags set.  @jowr is right about checking the error string.

**Comment by babaksamareh** [comment]
Thanks for the info guys.

**Comment by ibell** [comment]
It's working now by the way, at least for the fluids that have data for those parameters.
