### ISSUE TITLE
Bug in Development version of HAPropsSI

### ISSUE THREAD

**Issue by TimHarvey2** [CoolProp/CoolProp#686]
HAValidation.py runs fine under version 5.1 but fails part way through in 5,1,1dev version.
This may only be a python issue as the calculation that fails in python works fine using Excel function on development version (Note using the 64bit DLL in Excel and 32bit python2.7).
 
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\HAValidation.py", line 136, in <module>
    HotAir('9')
  File "C:\Python27\Lib\site-packages\HAValidation.py", line 55, in HotAir
    Twb=HAPropsSI('Twb','T',T,'W',W,'P',101325)-273.15
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4062)
  File "CoolProp\HumidAirProp.pyx", line 49, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2853)
ValueError: HAProps failed ungracefully with inputs: "Twb","T",5.9314999999999998e+02,"W",9.0000000000000002e-01,"P",1.0132500000000000e+05

**Comment by TimHarvey2** [comment]
it works for all value of W except in range around 0.9
>>> HAPropsSI('Twb','T',593.15,'W',0.89999999999999,'P',101325)-273.15
88.44940856396641
>>> HAPropsSI('Twb','T',593.15,'W',0.899999999999999,'P',101325)-273.15

Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    HAPropsSI('Twb','T',593.15,'W',0.899999999999999,'P',101325)-273.15
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4062)
  File "CoolProp\HumidAirProp.pyx", line 49, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2853)
ValueError: HAProps failed ungracefully with inputs: "Twb","T",5.9314999999999998e+02,"W",8.9999999999999902e-01,"P",1.0132500000000000e+05 
>>> HAPropsSI('Twb','T',593.15,'W',0.90000000000001,'P',101325)-273.15

Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    HAPropsSI('Twb','T',593.15,'W',0.90000000000001,'P',101325)-273.15
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4062)
  File "CoolProp\HumidAirProp.pyx", line 49, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2853)
ValueError: HAProps failed ungracefully with inputs: "Twb","T",5.9314999999999998e+02,"W",9.0000000000001001e-01,"P",1.0132500000000000e+05 
>>> HAPropsSI('Twb','T',593.15,'W',0.9000000000001,'P',101325)-273.15
88.44940856396937

**Comment by ibell** [comment]
Looks fine to me:
```
from CoolProp.HumidAirProp import HAPropsSI

import CoolProp
print CoolProp.__version__
print CoolProp.__gitrevision__

print HAPropsSI("Twb","T",5.9314999999999998e+02,"W",9.0000000000000002e-01,"P",1.0132500000000000e+05)
print HAPropsSI("Twb","T",5.9314999999999998e+02,"W",8.9999999999999902e-01,"P",1.0132500000000000e+05)
```
I get 
```
5.1.1dev
f0bf0cf9fc556c06ace43cf085d2acd8f1183376
361.599408564
361.599408564
```

**Comment by ibell** [comment]
Can you try to uninstall completely and reinstall?

**Comment by TimHarvey2** [comment]
I did try that when I install 5.1 and the 5.1 Dev again, but I will retry including a python install on another computer.
The References to (CoolProp\CoolProp.cpp:4062) and (CoolProp\CoolProp.cpp:2853) did not make any sense to me as they are both comment lines. Bunt my understanding of C++ is very limited at moment.

**Comment by ibell** [comment]
Yes those references are to C++ files generated in the python wrapper.

**Comment by jowr** [comment]
Is this a 64bit vs 32bit issue? Note that @TimHarvey2 stated in the beginning that it works with 64bit Excel, but not with 32bit Python.

**Comment by jowr** [comment]
Hm, no it isn't. Just tried with 32bit Linux and it works just fine.

**Comment by TimHarvey2** [comment]
I have reinstalled with latest development version  and HAValidation.py ran with out errors, I thin reinstalled version that I had problem with and it worked fine as well. Seems Like it was installation issue (of MS) at my end, Sorry for any inconvenience I will test more thoroughly before I raise any similar issues.
