### ISSUE TITLE
Examples on homepage not updated

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#687]
Something has gone wrong during the last release. The examples are still tagged as v5.0.8: http://coolprop.sourceforge.net/coolprop/examples/examples.html

**Comment by ibell** [comment]
That's weird, since on the server, the examples page looks right:
http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/coolprop/examples.html
.  Perhaps there is/was a permissions problem?

**Comment by jowr** [comment]
Are we sure that the builder was finished when the release was made? I could not find any immediate permissions problem - we are using rsync with the "ignore permissions" flag to sync the directories.

**Comment by ibell** [comment]
My question is more along the lines of do the permissions keep the files from getting rsync copied properly, not access permissions.

**Comment by ibell** [comment]
Let's delete all the files on the server next time we do a release.

**Comment by ibell** [comment]
Seems to be fixed now
