### ISSUE TITLE
PropsSI in saturation region

### ISSUE THREAD

**Issue by acuiko** [CoolProp/CoolProp#688]
Hi,
CoolProp.PropsSI("I", "T", 278.15, "P", CoolProp.PropsSI("P","T",278.15,"Q",1,"R410A"), "R410A") works fine, but
CoolProp.PropsSI("I", "T", 278.15, "P", CoolProp.PropsSI("P","T",278.15,"Q",1,"R22"), "R22") gives an error
Saturation pressure [584109 Pa] corresponding to T [278.15 K] is within 1e-4 % of given p [584109 Pa]

Why is not the problem in the first case?

**Comment by jowr** [comment]
My first guess is that it is related to R410A being pseudo-pure, but I agree that it looks like we could be more consistent here.

**Comment by paarfi** [comment]
R410 is a mixture with a glide. For a given pressure, the temperature on the vapor line of the saturation dome is higher than on the liquid line. R22 is a single molecule without a glide. For a given pressure, the temperature at the vapor and liquid lines of the saturation dome are the same. So specifying T and P is fine for defining your saturated liquid state for R410. But for R22, that same T and P could be saturated liquid, saturated vapor, or something in-between under the dome. Thus the error message.

**Comment by jowr** [comment]
Thank you for providing a proper description. I guess we can close this issue, can't we, @acuiko ?

**Comment by acuiko** [comment]
of course. Thanks for the explanation.

**Comment by ibell** [comment]
Actually, the first one *should* be an error.  With the full mixture model, T,P are valid inputs through the two-phase region.  With the pseudo-pure, not so much.  Pseudo-pure EOS are like pure fluid EOS, but not valid in the two-phase region (roughly).
