### ISSUE TITLE
variable names for second_partial_deriv

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#691]
See doxygen info for second_partial_deriv:
http://www.coolprop.org/_static/doxygen/html/class_cool_prop_1_1_abstract_state.html#a9a7511a913cfc6327b71085bfec59e93

The variable `Of2` should instead be named `Wrt2`.

Then the Python example can be extended:
http://www.coolprop.org/coolprop/LowLevelAPI.html#partial-derivatives-low-level

```python
import CoolProp
HEOS = CoolProp.AbstractState("HEOS", "nButane")
HEOS.update(CoolProp.PT_INPUTS, 101325, 400)

ds_dT_d = HEOS.first_partial_deriv(CoolProp.iSmass, CoolProp.iT, CoolProp.iDmass)
print(ds_dT_d)

d2s_dT2_d = HEOS.second_partial_deriv(CoolProp.iSmass, CoolProp.iT, CoolProp.iDmass, CoolProp.iT, CoolProp.iDmass)
print(d2s_dT2_d)
```

**Comment by ibell** [comment]
Good point, yes I will do this.  Correct on both counts.  A simple fix.
Or...  Could you put together a pull request?  It should be a clear enough
PR.

**Comment by thorade** [comment]
Thanks for adding the Python example. 
Still, this does not fix the problem of wrong variable names in C++. 
I do not currently see how one could ever have different `Of1` and `Of2`? 
This has to be fixed in `second_partial_deriv` (easy) and in `second_saturation_deriv` (needs some more thinking).

**Comment by ibell** [comment]
Yes, I basically agree with you about Of1 and Of2 being different, but we
need a second mixed partial along the saturation in the splines, and I
don't really know what to do about that.

**Comment by thorade** [comment]
But a second derivative would always be the derivative of a derivative, right? Then how can the "Of" part change? Totally possible that I just don't see what you want to calculate.

**Comment by ibell** [comment]
Yes, I think you are correct.  I think this is a bug.  Perhaps it would be
best to just fix the function, though it will break some people's code.
But it's wrong, so let's fix it.
