### ISSUE TITLE
Adding CV, Internal Energy , Speed of Sound and Isotropic Exponent to HAPropsSI Wish List, Ref #503

### ISSUE THREAD

**Issue by TimHarvey2** [CoolProp/CoolProp#693]
I looking at formulas in Section 5.3 of "Herrmann, S.; Kretzschmar, H.-J.; Teske, V.; Vogel, E.; Ulbig, P.; Span, R.; Gatley, D.P.: Determination of Thermodynamic and Transport Properties for Humid Air
for Power-Cycle Calculations. PTB-Verlag, Braunschweig (2009).
I was able to calculate CV and "CP" with good correlation to LibHAirProps-SI and Refprop See below I am trying to get the others to work But Speed of Sound is a bit more complex.Do you think this is a suitable method or do I have to go back to derivatives. I like these methods as they enable other gas mixes to be used provided Moisture content can be calculated (that's future wish list Item the Enhancement factor for gas mixes other than AIr (there are some paper by David C. Shallcross that attempt this but maybe better methods now?))
![cv humid air usings propssi](https://cloud.githubusercontent.com/assets/11156125/8078256/bdb7e758-0f9f-11e5-95ff-eacba6f8a3ee.JPG)
I hope attache Image come through I migh Emai in case

**Comment by ibell** [comment]
I think your method is simple to implement, but not terribly accurate.  I
think you need to use the definitions of cp (=dh/dT|p) and cv (=du/dt|rho)
and use the derivatives.  In CoolProp we use numerical derivatives.  It
would be interesting to see what your deviations look like at higher water
contents.

**Comment by TimHarvey2** [comment]
You are correct, Errors are no to bad except near saturation as I assume the PRopSI properties for pure water are returning liquid properties as Partial pressure of water generated from W is in liquid region. But for most of range differences are less than those from REFPROP when compared to LibAirProps-SI. It also fails at lower water content before other methods do.

**Comment by ibell** [comment]
Actually it should be pretty easy to implement internal energy (u = h-p/rho)

And then cv should be pretty easy too. Numerical derivative of u w.r.t. T with v constant.

**Comment by ibell** [comment]
I'll do that when I get a free moment.

**Comment by TimHarvey2** [comment]
Thanks I will run some comparisons with LibHAirProps-SI and Refprop when nightly build available in the morning.

**Comment by TimHarvey2** [comment]
Comparison Cv from LibHAirProps-SI not  as good as Cp see attached I will email spreadsheet
![image](https://cloud.githubusercontent.com/assets/11156125/8713276/34acb53e-2baa-11e5-856e-a5af60a742d0.png)

**Comment by ibell** [comment]
Any idea how they calculate cv in LibHuAir?  I suspect should be the same
as in PTB report.

**Comment by TimHarvey2** [comment]
Ian 
I have sorted Cv I think,I get good agreement .001% with  LibHAirProps-SI what you have done is fine its just that you have to have specific volume and W constant and Solve for the pressure value to use in u that keeps Specif volume constant when temperature changes by dT
I have introduced a function pressure in code Which is not correct but it is to represent the solve function, I hope this is clear if My C++ was a bit better I would attempt to write but I am sure similar solves exist elsewhere in code that can be used.
 My suggested code is below

![image](https://cloud.githubusercontent.com/assets/11156125/8892657/729fcb22-33a9-11e5-8777-7bf2c4637cab.png)

**Comment by ibell** [comment]
I think I fixed CV, can you please check?

**Comment by ibell** [comment]
Isentropic exponent is simply cp/cv, so that is easy, and maybe not worth implementing.

I'm not sure what to do about speed of sound.

**Comment by TimHarvey2** [comment]
I am Not sure about Cp/Cv being isotropic exponent, it is I think for Ideal gas but not quite for real gas (ref paper "Calculation of  Natural gas Isentropic Exponent by Maric et al From Flow Measurement and Instrumentation, 16 (2005) 13 -20)  I have been playing with 
![image](https://cloud.githubusercontent.com/assets/11156125/8896432/c0ff6494-343f-11e5-8ad3-161fe57f6ab4.png)  and 
![image](https://cloud.githubusercontent.com/assets/11156125/8896436/e660dace-343f-11e5-9fa4-650eeec7c50e.png)
From LibHAirProps Help 
Having Reasonable success with Isentropic exponent by solving for pressure again at constant entropy with small changes in specific volume, error ~ 0.07%  I will compared with Cp/Cv over range of values and see what I get I will also compared with LibHAirProps and Refprop 
and I will check you implementation of CV over same ranges.

**Comment by TimHarvey2** [comment]
Ian a check on your New CV works well at does Internal energy u
My spreadsheet version of Isentropic exponent error is =.037% compared to LibHAirProps where as cp/cv error is 0.031% only one case looked at. As to the Speed of Sound error is a little more at 0.389% 
I used the above two formulas
My attempt at code enclosed is a bit of guess (trying to replicate my spreadsheet solve and what you did for cv) isentropic exponent first then the speed of sound

![image](https://cloud.githubusercontent.com/assets/11156125/8904417/8342e168-34a2-11e5-8bff-ec2dbee8c624.png)


Also enclosed is CV and internal energy  comparison I have not done error on u for refprop as I can never seem to get the same reference state to LibHAirProps

![image](https://cloud.githubusercontent.com/assets/11156125/8904592/0c0e247a-34a4-11e5-8f0a-2ec91c7397e1.png)

**Comment by TimHarvey2** [comment]
Complete code attempt for Isentropic exponent and Speed of sound from above
![image](https://cloud.githubusercontent.com/assets/11156125/8904635/943016c4-34a4-11e5-97ee-59ececcfcf08.png)

**Comment by TimHarvey2** [comment]
The Above Attempt at Code will not work because Pressure function Requires Temperature however using  formula in Maric
![image](https://cloud.githubusercontent.com/assets/11156125/8921259/9e394146-3516-11e5-8b73-314d05be7990.png)

then I get Isotropic exponent error of 0.007% compared to LibHAirProps
code would be something Like below only written by someone who understand C++ better
![image](https://cloud.githubusercontent.com/assets/11156125/8921318/469671b0-3517-11e5-835e-a52efb3cc567.png)


As to Speed of Sound I am still working on this formula from Younglove and McLinden refered to in Refprop Might Work But not for me at moment.
![image](https://cloud.githubusercontent.com/assets/11156125/8921382/14602046-3518-11e5-9860-3307ffac990b.png)

**Comment by ibell** [comment]
Right then, both of those look pretty straightforward to me, I'll try to
code them up tonight.

**Comment by TimHarvey2** [comment]
I have cracked Speed of sound Problem was (1+W)  error 0.003%
I have to think about why this is required here and not in isentropic exponent

Calculation can be done two way from isentropic exponent using Formula form PTB and solving for Speed of sound
![image](https://cloud.githubusercontent.com/assets/11156125/8923035/87f40dfe-352e-11e5-8e90-5b599518aaa1.png)
 Note Density is mass density I just had to devide this by (1+W) inside the square root
![image](https://cloud.githubusercontent.com/assets/11156125/8923072/5024d7e0-352f-11e5-9e48-2ce2e31821eb.png)

or by Younglove and McLinden equation
Code  ~
![image](https://cloud.githubusercontent.com/assets/11156125/8923101/bcbc4ff0-352f-11e5-9982-6077eac42c71.png)

Note in Isentropic exponent code I had signs wrong in pressure equations

Being able to calculate Pressure as a special function would be useful as well I guess this would need a change ti excel macro
![image](https://cloud.githubusercontent.com/assets/11156125/8923253/96661780-3531-11e5-812d-a0446fea937f.png)


Also given C represent  cp  is there need to rething symbols here of just add cv as well as CV ? 
![image](https://cloud.githubusercontent.com/assets/11156125/8923212/0608d2e0-3531-11e5-8355-60f2170b90c7.png)

**Comment by TimHarvey2** [comment]
oops I meant to put 
![image](https://cloud.githubusercontent.com/assets/11156125/8923298/1e4708c6-3532-11e5-97ff-4b5d063673e9.png)

instead of first bit of code above Hope my text now makes sence.

**Comment by ibell** [comment]
I think if I understand it, we can limit ourselves to just derivatives with respect to molar volume, which is just fine.  Derivatives with entropy held constant are less convenient and require a new solver.

Doing p=f(T,psi_w,v_bar) from Excel is going to be a problem.  

So let's just do isentropic exponent and speed of sound using the formulations you propose.  Can you email me the papers you are referring to?  I want to make sure we can use their analysis.

**Comment by TimHarvey2** [comment]
Ok I have sent email Thanks I guess this closes this issue.

**Comment by ibell** [comment]
Well, I have to actually implement these things, but it seems like its
pretty straightforward actually.  We shall see.  Thanks for the email.

**Comment by ibell** [comment]
Ok, I think this issue can be put to bed now with this commit.

**Comment by ibell** [comment]
Please test (cv as well), and if all is well we can close this issue.

**Comment by TimHarvey2** [comment]
OK I will do that over next couple of Days

**Comment by TimHarvey2** [comment]
It checks out well over ranges I have tested did Also managed to compile Myself without any issues 
I will email comparaitive spreadsheets
