### ISSUE TITLE
Excel wrapper dll shouts error

### ISSUE THREAD

**Issue by ozanamatanor** [CoolProp/CoolProp#694]
I am trying to install the Excel Wrapper on my machine and it did not work until now.

I have Excel 2013 64bits, Windows 7 Professional 64bits and I downloaded CoolProp 5.1.0 recently. 
As explained in the install procedure, I put the file CoolProp_x64.dll in the folder C:\CoolProp and registered the file CoolProp.xlam as Excel Add-In.

When I try to execute Prop1SI("R410A";"Tcrit") wich I found in the Test file, Excel anwers me 'The most recent error number is 453.' and that the entry point Props1SI of a dll was not found in C:\CoolProp\ CoolProp_x64.dll

Did anyone have this issue before and what can I try to fix it ?

Thanks !

**Comment by ibell** [comment]
Hmm this is a new one for me.  Sounds like you followed the procedure
properly. What exactly does your call look like in the cell that causes the
failure?  Can you please email me (ian.h.bell@gmail.com) the exact DLL that
you are using?

**Comment by ibell** [comment]
Is it a file permissions problem?  Do you definitely have read/write access to the dll?

**Comment by ibell** [comment]
I just checked the 64-bit DLL and it definitely has the Props1SI function

**Comment by ozanamatanor** [comment]
Thank you for the answer. I sent you details per email.

**Comment by ibell** [comment]
Any progress?

**Comment by ibell** [comment]
In my excel on windows it works fine: 

=Props1SI("R410A","Tcrit") yields 344.494

Can you download the DLL from http://www.coolprop.dreamhosters.com/binaries/MicrosoftExcel/ and try again please?

**Comment by ozanamatanor** [comment]
Hello Ian!

With the DLL from the link it works fine. I don't know why mine was corrupted but anyway, I am gonna be able to use it now. Thank you for helping!
