### ISSUE TITLE
Problem with reference state

### ISSUE THREAD

**Issue by babaksamareh** [CoolProp/CoolProp#695]
Hello guys, look at this:

CoolProp::set_reference_stateS("water", "ASHRAE");

I get this error: 
libc++abi.dylib: terminating with uncaught exception of type CoolProp::CoolPropError<(CoolProp::CoolPropBaseError::ErrCode)4>: Temperature to QT_flash [233.15 K] must be in range [273.06 K, 647.096 K]

Is this normal?

**Comment by ibell** [comment]
That's basically the correct behavior.  ASHRAE reference state uses
saturation temperature of -30C IIRC, which doesn't work so well for Water :)

Perhaps we should emit a nicer error.  I'll leave this issue open.

**Comment by babaksamareh** [comment]
Well yep that I know, but it crashes :) which is not good.

**Comment by ibell** [comment]
Right, but but you should always assume that any function in CoolProp can
throw an exception, which you are responsible for catching.

**Comment by ibell** [comment]
I'll change the error message in the exception to be more user-friendly.
