### ISSUE TITLE
Wrong Value Refprop/Excel XP40.MIX and coolprop REFPROP::XP40.MIX

### ISSUE THREAD

**Issue by mayersre** [CoolProp/CoolProp#698]
It concerns all quantities across the complete range, just one example here 

I obtain different Values for this mixture : 

PropsSI('P','T',273.15,'Q',1,'REFPROP::XP40.MIX')
473378.35703522776
same value on Windows and Linux
But Excel
=pressure("XP40.MIX";"TVAP";"mks";273,15)
512985.876571066 << This is the correct one

In Refprop and Excel/Refprop the values are right, called
with Coolprop they are wrong Linux and Windows.

### begin file XP40.MIX ###
XP40
 87.2128980797299 354.635323643064 4446.95779408287 5.33687501421782
 4 
R32.FLD
R125.FLD
R134A.FLD
R1234YF.FLD
 .407364566995509
 .179481207732065
 .219673384884062
 .193480840388364
 0 
### end file ###

If I create XP40 myself in Refprop the file looks different. The Molar quantities are
the same but the 4 top values are different. 

### begin file R449A.MIX ###
 R449A
 87.2128980797299 355.225670708966 4499.88624171494 5.49696723606428
 4 
R32.FLD
R125.FLD
R1234YF.FLD
R134A.FLD
 .407364566995509
 .179481207732065
 .193480840388364
 .219673384884062
 0 
### end file ###

Guess : Maybe it is connected with the mixture setup and those 4 numbers
CoolProp.__gitrevision__
'ccc012c31a7c1505f5399acfa5ab85f24f41fd8b'
CoolProp.__version__
'5.1.1dev'

**Comment by ibell** [comment]
Where did you get that XP40.mix from?  It's not in the standard
installation, nor is it in the new set of mixtures for REFPROP.  I think
the first four values are the critical point parameters, which might
explain why you get different values.

Does R449A work properly for you?  What if you save the XP40 generated by
the GUI as something new (XP40AAA.mix), does that work properly?

**Comment by mayersre** [comment]
The XP40 Mix is from DuPont Duprex and gives the official product values for XP40(R449A). Duprex is a refprop 9.11 dll based program. The XP40 mixture comes with mixture- and fluid files from Dupont. I even faked Coolprop into using the Duprex provided refprop.dll and their mixture and fluids files ... same result.

Excel/refprop.dll right, Coolprop wrong.

The second mixture file is such a Refprop GUI generated file, see 'begin file R449A.MIX'. In Coolprop it brings the exact same results than calling just with the mixture string.

PropsSI('P','T',273.15,'Q',1,'REFPROP::R449A.MIX') #<- file generated with refprop gui

and

R449A='REFPROP::R32[0.4073645669955089]&R125[0.1794812077320650]&R134a[0.2196733848840616]&R1234yf[0.1934808403883644]'

PropsSI('P','T',273.15,'Q',1,R449A)

give me the same values

PropsSI('P','T',273.15,'Q',1,'REFPROP::XP40.MIX')
gives the same values too, but it should not ...

it seems to ignore the different critical parameters during setup of the mixture

With excel/refprop on windows the values are like in Duprex.

I strongly suspect these critical parameters to be the difference.

And I think/guess it happens during mixture setup

The Coolprop Interface is a beauty ...

(just tryin to run B. Thelen's python refprop interface to narrow down the issue)
if you have a working version of it try to get P for T=273.15 at Q=1 from it for XP40.MIX
if it delivers 512985.876571066 the bug is likely in the mixture setup at coolprop.

**Comment by ibell** [comment]
What does your XP40.mix file look like if you generate it from the REFPROP
GUI?  If 449A works properly, there is absolutely no reason that XP40
should behave differently.

**Comment by mayersre** [comment]
The R449A file : 

R449A
 87.2128980797299 355.225670708966 4499.88624171494 5.49696723606428
 4 
R32.FLD
R125.FLD
R1234YF.FLD
R134A.FLD
 .407364566995509
 .179481207732065
 .193480840388364
 .219673384884062
 0

**Comment by mayersre** [comment]
The XP40 file I got from Dupont

XP40
 87.2128980797299 354.635323643064 4446.95779408287 5.33687501421782
 4 
R32.FLD
R125.FLD
R134A.FLD
R1234YF.FLD
 .407364566995509
 .179481207732065
 .219673384884062
 .193480840388364
 0

**Comment by ibell** [comment]
What if you generate the XP40.mix file using the REFPROP GUI?  Does it look
the same?

**Comment by mayersre** [comment]
Yes ...
What if Dupont defines the mixture components differently, let me check
I copied the refprop binary and co into the duprex folder and started it from there
now I have the same like in excel ?!?

I will diff the fld files of duprex and refprop and tell you later or tomorrow

**Comment by mayersre** [comment]
It is much simpler than I thought

hmx.bnc has three additional binary pairs added, see diff below ...

diff -bur fluids/HMX.BNC fluids_rp/HMX.BNC
--- fluids/HMX.BNC      2014-09-15 18:10:48.000000000 +0200
+++ fluids_rp/HMX.BNC   2015-06-17 17:08:04.231547298 +0200
@@ -4390,24 +4390,6 @@
                           TC1  190.54     -785.69     2755.1     -4030.2      2343.4         0.
                           VC1   -0.0286      0.6137     -2.5987      3.9065     -1.9875      0.
 !
-?R134A/R1234YF
-?Naicker (2013)           Based on experimental data from Chien-Ping Kao, Private communication via J. Hughes
-811-97-2/754-12-1         KW0    0.996096  0.99401771   1.0328709   0.9435635   0.0000000   0.0000000
-                          TC1    0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000
-                          VC1    0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000
-!
-?R1234yf/R32                (R1234yf/R32)
-?Naicker (9/12/2011)      Based on experimental data from Chien-Ping Kao, Private communication via J. Hughes
-754-12-1/75-10-5          KW0    1.005107   0.9445894   0.8898251   1.1125273   0.0000000   0.0000000
-                          TC1    0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000
-                          VC1    0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000
-!
-?R125/R1234YF
-?Naicker (2013)           Based on Experimental data from Chien-Ping Kao via J. Hughes
-354-33-6/754-12-1         KW0    0.983231  0.99924695   1.1393739   1.0000000   0.0000000   0.0000000
-                          TC1    0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000
-                          VC1    0.0000000   0.0000000   0.0000000   0.0000000   0.0000000   0.0000000
-!
 
 
 #MXM              !mixture model specification

**Comment by ibell** [comment]
Thanks for the update, I removed the parameters, I think they are proprietary.
