### ISSUE TITLE
Fugacity using Python wrapper

### ISSUE THREAD

**Issue by samiit** [CoolProp/CoolProp#699]
Is there a python wrapper function to return a list of fugacity values,
much like the **fgcty** REFPROP python interface.

Sam

**Comment by ibell** [comment]
Currently, no, but we do calculate the fugacity, it's just not exposed,
either for the high-level or low-level API.

**Comment by ibell** [comment]
We could expose it to the low-level interface.  Would that be sufficient?

**Comment by samiit** [comment]
Thanks for the answer and sorry for not following up.
Well, I would need it for my Python application, but can wait until it is released. You can go ahead at your convenience.
Best wishes,
Sam

**Comment by ibell** [comment]
Here you go:
``` python
import CoolProp
for be in ['REFPROP','HEOS']:
    AS = CoolProp.AbstractState(be, 'R32&R125')
    AS.set_mole_fractions([0.5, 0.5])
    AS.update(CoolProp.PQ_INPUTS, 101325, 0)
    print AS.fugacity(0), AS.fugacity_coefficient(0)
```
