### ISSUE TITLE
Vectorized version of PropsSI for MATLAB

### ISSUE THREAD

**Issue by FenryrMKIII** [CoolProp/CoolProp#701]
Hello,

coolProp for MATLAB works great when asking singe value e.g.  (assuming P and T are vectors)
CoolProp.PropsSI('CVMOLAR','T',T(1),'P',P(1),'oxygen')
works fine

but
CoolProp.PropsSI('CVMOLAR','T',T,'P',P,'oxygen')
raises an error

Does a vectorized version of coolProp exist for MATLAB ? This would avoid having to program loops.

Thank you for the help.
BR

**Comment by ibell** [comment]
No vectorized version exists for MATLAB, but PropsSI is vectorized in
python. I'm not a fan of MATLAB, and I don't foresee implementing this,
even though I can clearly see the use case.

**Comment by jowr** [comment]
I think Harald once tried to implemented that for the old CoolProp v4: https://github.com/hnil/coolprop
The new version does not have it, but maybe you can use the old code to implement it yourself.

**Comment by ibell** [comment]
Actually, it might be fairly easy, there is a function called PropsSImulti that should theoretically be exposed to MATLAB, but I just need to deal with a bug in MATLAB wrapper

**Comment by ibell** [comment]
One last little bit of work remains on the SWIG+MATLAB side and you should be good to go with the PropsSImulti function.  I'll provide an example when it works

**Comment by FenryrMKIII** [comment]
Dear Ian,

Thanks a lot for the follow-up and the work you are providing.

BR

**Comment by ibell** [comment]
OK, so this is actually harder than I thought.  This might have to sit on the wishlist for now.

**Comment by ibell** [comment]
There is a new function available that you can use for vectorized evaluation: http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#calling-low-level-interface-through-dll

I don't think we will ever be able to get the other things working in the SWIG matlab wrapper.
