### ISSUE TITLE
1 : HapropsSI ( "T" , "H" , ValueH, "W" , 0 , "P" , 101325) lead to an error

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#702]
Hello Ian,

HapropsSI ( "T" , "H" , ValueH, "W" , 0 , "P" , 101325) 
lead to a zero value for plenty of ValueH (-5000 ; 0 ; 5000 ; 10000 ; ...)

Message Error is : "options.p is not valid in saturation_T_pure_1D_P for T = 135"

**Comment by ibell** [comment]
Ill take a look!

**Comment by pmanach** [comment]
Hello Ian,

have you get time to look at these problem ? (703 and 703) ?

**Comment by ibell** [comment]
Not yet.  I am doing this all in my free time right now, which is quite limited at the moment.  Working on psychrometric properties is not very much fun, so it tends to lag a bit.  I'll see what I can do.
