### ISSUE TITLE
2/ HapropsSI ( "T" , "B" , ValueB, "W" , 0 , "P" , 101325) lead to an error

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#703]
Hello Ian,

HapropsSI ( "T" , "B" , ValueB, "W" , 0 , "P" , 101325) 
lead to a zero value for plenty of ValueB ( 263.15 ; 264.15  ; 265.15  ; ...)
Message Error is : "options.p is not valid in saturation_T_pure_1D_P for T = 135"

**Comment by ibell** [comment]
Well, it's dry air - there are issues when the air is dry that makes life difficult. This formulation does not fully extrapolate to dry air
