### ISSUE TITLE
Help needed for MEG2, AEG and APG

### ISSUE THREAD

**Issue by hasanacul** [CoolProp/CoolProp#704]
Dear friends, we run MEG (Etylen Glycol) and MPG (Polypilen Glycol) in coolprop in C#, however we could not run MEG2, AEG and APG. Could you please help us to run mentioned brines. Thank you.

**Comment by jowr** [comment]
Please provide some more info. What version of CoolProp? What error message do you get? How does your function call look?

**Comment by hasanacul** [comment]
Hi! 
Sorry.We could not see the version number.
Error message: infinity.
Call: Props('C', 'T', 300, 'P', 101.325, "AEG-24%")
Thanks for the answer.
Br
Hasan

iPhone'umdan gönderildi

29 Haz 2015 tarihinde 17:28 saatinde, Jorrit Wronski <notifications@github.com> şunları yazdı:

**Comment by ibell** [comment]
That is the syntax for the old version of CoolProp (v4), not supported in
v5. Please see the examples here:
http://www.coolprop.org/fluid_properties/Incompressibles.html#mixture-examples

**Comment by hasanacul** [comment]
Dear friends,

We have been using Csharp and coolprop.dll with the files which are mentioned below. Now, we have get type convertion error. What are the changes?

 

_params.cs

CoolProp.cs

CoolPropPINVOKE.cs

CoolPrp.cs

phases.cs

SWIGTYPE_p_a_2__double.cs

SWIGTYPE_p_double.cs

SWIGTYPE_p_std__string.cs

SWIGTYPE_p_std__vectorT_double_t.cs

SWIGTYPE_p_std__vectorT_std__string_t.cs

unit_constants.cs

unit_systems.cs

 

 

Best Regards,

 

Hasan ACUL

 

Office Phone   : (+90 216) 345 5525

Cell Phone      : (+90 533) 664 5601

**Comment by ibell** [comment]
Have you tried a simple example like the Example.cs provided?  Did you
remove the old code and replace it with the new code?  Where do you get the
conversion error?

**Comment by hasanacul** [comment]
Dear friends,

 

Here is the error when we use Example.cs:

 

"'SWIGExceptionHelper' tür başlatıcısı özel durum döndürdü."

 konum: CoolPropPINVOKE.M_PI_get()

 konum: CoolProp..cctor()

CoolPropPINVOKE

 

 konum: CoolProp.PropsSI(String Output, String Name1, Double Prop1, String Name2, Double Prop2, String Ref)

   konum: ConsoleApplication1.Program.Main(String[] args)

   konum: System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)

   konum: System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)

   konum: Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()

   konum: System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   konum: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   konum: System.Threading.ThreadHelper.ThreadStart()

 

 

 

Saygılarımla,

 

Hasan ACÜL

 

Ofis Tel         : (+90 216) 345 5525

Mobil Tel      : (+90 533) 664 5601

**Comment by hasanacul** [comment]
Dear friends, 

 

We keep working on it. We try to use latest version of dll and now we have an error. What we do know:

 

1.      We download 5.1.0 coolprop dll files from the link:  <http://sourceforge.net/projects/coolprop/files/CoolProp/5.1.0/Csharp/Windows_64bit/CoolProp.dll/download> CoolProp.dll

2.      We download platform-independent.7z files from the link:  <http://sourceforge.net/projects/coolprop/files/CoolProp/5.1.0/Csharp/platform-independent.7z/download> platform-independent.7z

3.      We can not even pass CoolProp.get_global_param_string("version")in Example.cs files and gives this error

"'CoolPropPINVOKE'
konum: CoolPropPINVOKE.get_global_param_string(String jarg1)
   konum: CoolProp.get_global_param_string(String ParamName

 

 

Saygılarımla,

 

Hasan ACÜL

 

Ofis Tel         : (+90 216) 345 5525

Mobil Tel      : (+90 533) 664 5601

**Comment by ibell** [comment]
Did you add all the CoolProp cs files to your project?  It definitely works
fine in visual studio - the example output is autogenerated in this way.


Ian

**Comment by hasanacul** [comment]
Dear Ian,

 

We used 32 bit and solved the problem. Please be informed that our computer’s operating system is 64 bit. We can not run the dlls with 64 bit and that is why we tried 32 bit.

 

Best Regards,

 

Hasan ACUL

 

Office Phone   : (+90 216) 345 5525

Cell Phone      : (+90 533) 664 5601

**Comment by ibell** [comment]
Really?  I am pretty sure we are doing our testing in 64-bit builds, and
they seem to be running just fine.

**Comment by hasanacul** [comment]
Yes. We run it in 32 bit without  any problem. however, we have another problem that it works in local but when we try to run it on internet we have problem. here is our web service

 

http://213.142.144.44:1923/PropsSiSalamura/CoolpropWebApi/C/T/300/P/101325/MEG-20

 

our method is like that

 

 public static double PropsSiSalamura(

            string val1,

            string val2,

            double val3,

            string val4,

            double val5,

            string salamura

            )

        {

            return CoolProp.PropsSI(val1, val2, val3, val4, val5, "INCOMP::" + salamura + "%");

        }

 

sonuç "C:Infinity"

 

 

here is another example which works with unspecial caracters

 

http://213.142.144.44:1923/PropsSi/CoolpropWebApi/C/T/300/P/101325/water

 

which works fine.

 

What your comments can be? What the problem can be?

 

 

Best Regards,

 

Hasan ACUL

Founder/Manager

Mechanical Engineer, NPDP

 

Phone/Fax : (+90 216) 345 5525

Cell Phone : (+90 533) 664 5601

E-Mail        : hasan@iklimsoft.com     

Web           : www.iklimsoft.com

**Comment by ibell** [comment]
I bet this is an issue of escaping characters - not related to CoolProp

Maybe you need to escape : or % characters, which is why water works but
the others don't.

**Comment by ibell** [comment]
Or, there is something with permissions in your DLL.  Hard to say.  Can you run that input in standalone mode without the webservice?

**Comment by hasanacul** [comment]
Dear Ian,

 

We have been working on the issue for two weeks but we can not solve it. We have had still same errors and can not run on the internet. It works in local but not from our server to internet.

 

Your solution offer was: "Maybe you need to escape : or % characters, which is why water works but"

 

What we have now is

 

1.     Please see that “:” and “%” characters are in your coolprop method which is mentioned below. Whem we try to remove these chacters project cannot be build or gives error.

CoolProp.PropsSI("D", "T", 300, "P", 101325, "INCOMP::MEG-50%") + " " + "kg/m^3" + "\n");

 

2.     When we use Coolpro dll 64 bit in our server, we get this error ( An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) and that is why we can not use 64 bit

3.     When we use Coolpro dll 32 bit in our server, we get these errors 

Unable to load DLL 'CoolProp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Unable to load DLL 'HaPropSI': The specified module could not be found.

 

4.     Our developers search for solution alternatives but we can not solve it.

5.     We have been using previous version and not had sameproblem.

6.     All  we want to do is to use “AEG” and “APG” for VOLUMETRIC brine rate calculation. We dont want to use MASS brine rate.

 

Please help us to solve the problem.

 

Thank you for your help before hand.

 

Hasan

**Comment by ibell** [comment]
I have no idea.  I have never used ASP.net at all, and definitely not
CoolProp and ASP.net.  It is not one of the applications that we use/ have
the ability to debug.  And I see no reason that will change in the near
future.

Quite honestly, this seems more like a problem with your integration with
ASP.net than a bug in CoolProp.  The first thing that I would guess is that
your permissions are not allowing you to load the DLL in the web
application.

Questions:
a) Is your webserver itself 64-bit or 32-bit? Obviously if 32-bit, it will
not load 64-bit DLL
b) When you install the DLL, you know you need the magical C# dll, that is
in the C# directory, not the one that is in the shared_library folder,
correct?
c) Are you using 5.1.1dev?  If not, please do.  There are some bugs in
5.0.8 that have been fixed in 5.1.1 and the subsequent 5.1.1dev version
which will soon turn into 5.1.1 release.

Here are some recommended steps to check things are working properly:
a) Can you call the function F2K? It is a simple function that converts a
temperature in Fahrenheit (double) to a temperature in Kelvin (double).  It
is useful for testing
b) When this works, write out to file, or debug log, or somewhere else, the
EXACT inputs you are giving to the PropsSI function.

This is all work done in our free time, so if you want assistance, you must
describe (VERY CLEARLY) exactly what you have tried and the results that
you have obtained.  (Links to the files you downloaded, screenshots of your
webapp showing the files included, etc.)

Also, this question is no longer related to a desire for a properties for
these incompressible fluids.  Please open one issue per particular thing
that doesn't work.  Please do not respond to this thread.
