### ISSUE TITLE
Higher Pressure

### ISSUE THREAD

**Issue by enter802** [CoolProp/CoolProp#706]
Hi, I am trying to validate my ORC model with an existing plant which has 4760 kPa as maximum pressure in the cycle (the cycle uses R134a as working fluid). But CoolProp does not seem to support that range of pressure for calculations (mainly in the two-phase region). Is there any way I can deal with this or would it be possible to increase the range of pressure in CoolProp?

and this might sound ridiculous, but is it possible to scale down the pressure values and the enthalpy value in a proportionate manner so that the cycle still remains the same attributes? i know this question is a bit vague, so leave it if it doesn't make sense.

thanks for your time in advance!

**Comment by ibell** [comment]
See the limits here for R134a:
http://www.coolprop.org/fluid_properties/fluids/R134a.html#fluid-r134a

For the two-phase region, you are 100% constrained by the critical
pressure, which for R134a is 4.06 MPa, and you will never be able to exceed
this in the two-phase region.  In the single-phase regions, you should in
general be able to get to pmax, which for R134a is 70 MPa.  If this is not
the case, please open a new issue describing your problem, with the inputs
you used and the error message you get.

No idea about the other question.  It sounds like you are heading towards
something like corresponding states.
