### ISSUE TITLE
conda builds

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#707]
I currently work on a conda binstar channel for the CoolProp Python wrapper. @ibell: I update the docs as well, but could you please install new Python packages on your OSX bot? We need
```
conda update -yq conda
conda install -yq conda-env conda-build binstar binstar-build jinja2 requests
```

**Comment by jowr** [comment]
Ups, please do the same on the Windows and Linux machines. Thanks.

**Comment by ibell** [comment]
Yes sure, I'll do so tonight.

**Comment by jowr** [comment]
... and while you are at it: I think the OSX slave got stuck somewhere.

**Comment by ibell** [comment]
Actually, its the IPU slave that is stuck, mine seems ok I think.

**Comment by ibell** [comment]
Ok, done on windows and OSX.  Linux box does not currently use anaconda

**Comment by ibell** [comment]
I've done what I can from my side, it seems most of the python builds are actually happening on your machines as far as I can tell.

**Comment by jowr** [comment]
Sorry for that, you are right it was the IPU machine.

**Comment by ibell** [comment]
Do you want to get this together for the very-long-overdue 5.1.1?  Is this almost working?  It is definitely time for a release.

**Comment by jowr** [comment]
Yes, it's overdue It will be without Modelica, but I am going to try to include conda,

**Comment by jowr** [comment]
Looks like the conda stuff has to be removed from the normal build process. It literally takes ages, e.g. 35 minutes, for one single build.

**Comment by ibell** [comment]
So, push that all into a nightly build then?

**Comment by ibell** [comment]
So, it looks like the conda builds are happening, right?  Is this all done, or is there still more to be done?

**Comment by jowr** [comment]
They build, but it is not very reliable on Windows. We also miss the Linux builders and the integration into the release script. 

 - [ ] Linux build slaves
 - [ ] Automate release on binstar
 - [ ] Try (!) to fix the permission problems on Windows

**Comment by jowr** [comment]
I think we are done. Keep an eye on https://binstar.org/CoolProp/coolprop during the next release.

**Comment by ibell** [comment]
Excellent.  Thanks for your work on this issue.  Does that mean we can now
(or will be able to) do

conda install CoolProp

? That would be certainly very handy.

**Comment by jowr** [comment]
No it's not going to be that simple :wink:. They have their own repo and we cannot submit binaries to it. However, we can use a binstar channel 
`conda install -c https://conda.binstar.org/coolprop coolprop` 
and I am also going to file a pull request to the conda recipe directory as soon as I am sure that the build works well with the pip packages. See also https://github.com/CoolProp/conda-recipes. BTW, there are some syntax errors in the current Python files that I had to fix. The conda compiler is somewhat more picky than pip.

**Comment by ibell** [comment]
a) Did you have to make major changes to python code to make conda happy?
b) Did you document the ability to install using conda in the docs?

**Comment by jowr** [comment]
a) No
b) No, I think we should test it before we make people use it.
