### ISSUE TITLE
Matlab issue

### ISSUE THREAD

**Issue by willhunt** [CoolProp/CoolProp#708]
I have added the CoolProp files into the directory structure as suggested for Matlab but when i run the example:

     CoolProp.PropsSI('T','P',101325,'Q',0,'Air')

I get the error:

     Warning: function PropsSImulti requires at least 8 arguments 
     Error using CoolPropMATLAB_wrap
     Fatal error.

     Error in CoolProp.PropsSI (line 2)
     [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(244,varargin{:});

I am using MATLAB 2014a on a 32bit system. Any help is greatly appreciated.

**Comment by ibell** [comment]
Interesting.  I'll take a look.  That's a weird bug.

**Comment by ibell** [comment]
Are you on Windows?  Can you please attach a screenshot of your folder layout?  I'm a bit confused how your MATLAB wrapper code is calling ``PropsSImulti`` at all actually.  From the MATLAB level, it should never call the ``PropsSImulti`` function, though internally that is actually what is happening inside the ``PropsSI`` function.  Does the normal example work with Water instead of Air?  I can't see why it would, but...

Also, where (exactly) have you installed your CoolProp wrapper from?

**Comment by willhunt** [comment]
Yes I am on Windows 7 32bit.

My folder directory is set up as shown in the attached .jpg and is
comprised of files downloaded from here:

 http://sourceforge.net/projects/coolprop/files/CoolProp/5.1.0/MATLAB/

as directed from here:

http://www.coolprop.org/coolprop/wrappers/MATLAB/

Trying to run the example today with air and water resulted in this
feedback:

Trial>> CoolProp.PropsSI('T','P',101325,'Q',0,'Air')
Undefined function or variable 'CoolPropsetup'.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(244,varargin{:});

Warning: function PropsSImulti requires at least 8 arguments
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(244,varargin{:});

Trial>> CoolProp.PropsSI('T','P',101325,'Q',0,'Water')
Warning: function PropsSImulti requires at least 8 arguments
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(244,varargin{:});

Trial>> CoolProp.PropsSI('T','P',101325,'Q',0,'Air')
Warning: function PropsSImulti requires at least 8 arguments
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(244,varargin{:});

Thanks for looking into this, it is greatly appreciated.

Regards,
Will

**Comment by ibell** [comment]
A) I can't see your image, attachments get dropped, you need to do it in
the github interface

B) Try the development version from 5.1.1 (
http://sourceforge.net/projects/coolprop/files/CoolProp/nightly/MATLAB/)

C) What version of MATLAB do you use?

**Comment by ibell** [comment]
It seems there is a bug in the generated code for 32-bit MATLAB.  Any chance you can use 64-bit MATLAB?  That works just fine.

**Comment by ibell** [comment]
Sorry, the wrapper now requires an additional file called CoolPropsetup.m that I was not providing previously.  Adding that should fix your problem.  Download the new files using the link shown above.

**Comment by ibell** [comment]
Please confirm that it works for you now.

**Comment by willhunt** [comment]
It works now thanks! On first use when opening Matlab it still warns that 'CoolPropSetup'is not defined but it still gives the answer/result. On further use the warning does not show. Thanks for the fast response and providing this resource.
