### ISSUE TITLE
Error in calculating Thermal Conductivity and Viscosity in MATLAB on OSX

### ISSUE THREAD

**Issue by enter802** [CoolProp/CoolProp#709]
Hi, I am having error in calculating the Thermal Conductivity and Viscosity for R245fa for a pair of inputs (p,h), but no error when I am calculating other states, e.g., T, D, etc.

input: CoolProp.PropsSI('L','P',1450000,'H',300000,'R245fa')

error: Error using CoolPropMATLAB_wrap
         Failure in function PropsSI.
         Error in CoolProp.PropsSI (line 2)
         [varargout{1:max(1,nargout)}] =
         CoolPropMATLAB_wrap(207,'_wrap_PropsSI',varargin{:});

FYI: i am using MAC and my colleague is using Windows, but he is not getting any error for the same pair of inputs.

Thanks in advance!

**Comment by ibell** [comment]
Do you get any other error message than what you show here?  Failure in function PropSI isn't very helpful.

**Comment by ibell** [comment]
Can you please state where (exactly) you are downloading CoolProp from?  Are you using the development version?

**Comment by ibell** [comment]
Also, what version of MATLAB do you use, and is it 32-bit or 64-bit?

**Comment by enter802** [comment]
this is from where I downloaded the CoolProp 

http://sourceforge.net/projects/coolprop/files/CoolProp/ 

and no, that was the only error message that I got and nothing else.

I am using MATLAB R2013a 64 bit.

**Comment by ibell** [comment]
More specific please.  Exactly what folder from sourceforge did you
download the files from?

What version of OSX? 10.9? 10.10?

Also MATLAB R2013a is pretty old now.  Perhaps it is a version issue

**Comment by enter802** [comment]
OSX is 10.8.5, but I don't think it is a MATLAB version issue because in my Windows laptop I use 2013a as well and it is working there just fine.

Regarding the folder, I exactly don't remember. I downloaded it some time ago. But I downloaded the file from the same folder for both windows and MAC - windows is working but MAC isn't.

**Comment by ibell** [comment]
Works just fine for for with development version:

```
>> CoolProp.PropsSI('L','P',1450000,'H',300000,'R245fa')

ans =

    0.0760
```

Can you try to install most recent version from http://www.coolprop.dreamhosters.com/binaries/MATLAB/?  You'll also need the new CoolPropsetup.m file

**Comment by enter802** [comment]
I just tried it. It still isn't working. But having a different error this time -

Warning: function AbstractState_d4alphar_dTau4 takes at most 1 arguments 
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(243,varargin{:});

**Comment by enter802** [comment]
By the way, I opened the setup .m file, and it has only 

"% This is the setup script for CoolProp." within it..does it make sense?

**Comment by ibell** [comment]
It might be an OSX version issue.  We've had a LOT of problems with incompatibility between versions of OSX.  My setup looks the same too.

**Comment by ibell** [comment]
Please show the entire script you ran that could duplicate this error.  Otherwise we have no way to test.

**Comment by enter802** [comment]
what do you mean by the entire script? i am not so sure what you are asking for - do you mean the input command?

**Comment by ibell** [comment]
Yes, whatever you did to cause MATLAB to fail - MATLAB prompt input, script, etc.

**Comment by ibell** [comment]
Ah, you mean this, right: ``CoolProp.PropsSI('L','P',1450000,'H',300000,'R245fa')``

**Comment by enter802** [comment]
Yes...exactly

**Comment by ibell** [comment]
Do you have access to a newer version of OSX?  I cannot replicate this error on 10.9.

In about 30 minutes version 5.1.1 will be out, can you try with 5.1.1?

**Comment by enter802** [comment]
I have access to Yosemite, but the reason why I downgraded from Yosemite to this is because CoolProp wasn't working with Yosemite. So I am not so sure I want to try Yosemite.

However, I just downloaded 5.1.1 from http://sourceforge.net/projects/coolprop/files/CoolProp/5.1.1/MATLAB , but now it says "Invalid MEX file", even for temperature!

i have attached the screenshots for your reference, along with the directory setup.

![screen shot 2015-07-15 at 3 32 22 pm](https://cloud.githubusercontent.com/assets/9440833/8710437/ec447b9a-2b06-11e5-8ed7-30c348c70fd7.png)

![screen shot 2015-07-15 at 3 33 23 pm](https://cloud.githubusercontent.com/assets/9440833/8710438/ee94edee-2b06-11e5-8466-95ab657ed775.png)

**Comment by ibell** [comment]
Good news is I now have a Yosemite box, so we can try some new ideas for debugging this issue.

**Comment by enter802** [comment]
finally some hope of light!

**Comment by ibell** [comment]
Yes, do you have a free MATLAB license by any chance?  I'm not keen to buy another license of MATLAB just for 10.10

**Comment by ibell** [comment]
Do you have to use MATLAB?  Do you have any experience with python?  I used to be a MATLAB user and now I do everything in python.  So much nicer.

**Comment by enter802** [comment]
I have only one license of MATLAB which i am currently using. and I have no experience with Python and not planning to do anything with it right now - at least not before my masters. i have only 1 year left before which i have to finish my project and hence cannot afford to learn a different platform now!

**Comment by ibell** [comment]
Got it.  Matlab is causing us all kinds of problems, and Mathworks is
unwilling to come up with a solution that can make it work for us.  The
python interface is very stable and works great.

**Comment by enter802** [comment]
i just copied the wrapper my colleague was using in her MAC, and now the commands for Thermal Conductivity and Viscosity works just fine! although 5.1.1 didn't work. What could be the problem? i wonder!

**Comment by ibell** [comment]
No idea, but glad to hear it is working now!
