### ISSUE TITLE
json files: Ancillaries for pV and pL

### ISSUE THREAD

**Issue by thorade** [CoolProp/CoolProp#711]
All fluids have Ancillaries for both pV and pL, but that is necessary for pseudo-pures only. For pure fluids, pV and pL should be identical. One solution could be to have just one Anciallry named pS, but for consistency it is also OK to have both pV and pL defined and just let them have identical values.

**Comment by ibell** [comment]
Yes, the nicest solution would be pL and pV for pseudo-pure fluids, pS for pure fluids
