### ISSUE TITLE
Expose saturation derivatives from PropsSI [wishlist]

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#712]
It would be great if one can call PropsSI like

    CoolProp.PropsSI('D(D)/D(P)|sigma', 'P', 4e5, 'Q', 1, 'R245fa')

to get the saturation derivatives.

**Comment by thorade** [comment]
One could even discuss whether the D and bracket are necessary.
Or maybe distiguish between d and D, as in `('d(D)/d(P)|sigma'`?

**Comment by ibell** [comment]
Unfortunately, in order to support EES, it has to be case-insensitive. It's
annoying, but there is no other way.

That said, this is an excellent idea, and I will implement it when I have a
chance.

**Comment by ibell** [comment]
Although with respect to the question of @thorade , I quite like the way the strings are handled, and I am not such a huge fan of ``dD_dP_s``.  Your suggestion is good in terms of string parsing, but we will need to support the old way anyway.  Furthermore, for parameters that themselves have subscripts, it gets nasty.  For those reasons, I think my inclination is to pass on the suggestion.

I will implement the saturation derivatives in PropsSI.  Good idea.
