### ISSUE TITLE
Bicubic backend and first_saturation_deriv

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#713]
Fluid: R245fa
Language: C++
(P,Q) = (406200, 0)

Using the HEOS backend, saturation derivatives are fine, whereas using the BICUBIC&HEOS one results in "Invalid index to calc_first_saturation_deriv in TabularBackends".

**Comment by jowr** [comment]
I am not totally sure, but I think everything is fine. They are simply not implmented.

**Comment by Astrinus** [comment]
Either in CoolProp 5.1.0 and in the 5.1.1dev of a month ago they are implemented.

Il 07/07/2015 13:24, Jorrit Wronski ha scritto:

**Comment by ibell** [comment]
Probably just a bug.  I thought I had tests for the derivatives with the
tables, but let's see.  Should be pretty straightforward.
