### ISSUE TITLE
Possible error in isobaric thermal expansion coefficient

### ISSUE THREAD

**Issue by EdoMacchi** [CoolProp/CoolProp#714]
Hello,

I am beginning to use CoolProp (version 5.1.0) to compute thermophysical and transport properties of CO2 inside a CFD simulation. As a first test I used the example for the C++ low-level interface using CO2 and air as fluids. 

Density, specific heat, viscosity and other properties are fine however the values computed for the isobaric thermal expansion coefficient for air and CO2 seems wrong to me: they are much lower than expected (2-3 orders of magnitude).

For air at ambient temperature and pressure I would expect about 3e-03 1/K while for CO2 at 95°C and 100 bar it should be around 7e-03 1/K.

Maybe I am doing something wrong but could you please check if there is some problem in the computation of this coefficient?

Thank you!
Best regards,

Edoardo

**Comment by ibell** [comment]
Was a bug in the ``isobaric_expansion_coefficient`` function implementation.  Now I get:

```python
import CoolProp
for backend in ['HEOS','REFPROP']:
    HEOS = CoolProp.AbstractState(backend,'Air')
    HEOS.update(CoolProp.PT_INPUTS, 101325, 298)
    print HEOS.isobaric_expansion_coefficient()
```

**Comment by EdoMacchi** [comment]
Perfect! Now it works fine. Thank you.
