### ISSUE TITLE
Adding new fluids

### ISSUE THREAD

**Issue by kaizoku-ou** [CoolProp/CoolProp#715]
I've been using CoolProp for a few days. I wanted to know if we can new fluids to the library. If so, how? Pls help

**Comment by ibell** [comment]
What fluids do you want to add?  It's not currently such a trivial thing to add new fluids, though I would like to add some documentation about how to do that.

**Comment by kaizoku-ou** [comment]
For example Acetic acid

**Comment by ibell** [comment]
Hmm, acetic acid was in CoolProp, but I disabled it because the equation of state has a lot of issues.

**Comment by ibell** [comment]
Any other ones?

**Comment by kaizoku-ou** [comment]
It's more of the procedure of how to fluids rather than wanting to add a fluid

**Comment by ibell** [comment]
We have pretty much implemented every high-accuracy equation of state in the literature at this point

**Comment by kaizoku-ou** [comment]
I get that almost all (maybe all) commonly used fluids have been added in the source  for different EoS. Say there is some fluid A, how do I add it's data in the source code? How do use this new source code for the wrapper?

**Comment by ibell** [comment]
Well, the fluid properties are encoded in JSON form in the files here: https://github.com/CoolProp/CoolProp/tree/master/dev/fluids

If you add another JSON file for a new fluid, it will get compiled into CoolProp.

**Comment by kaizoku-ou** [comment]
Thank you. So, if I add a new JSON file in that repository, it'll get updated in CoolProp?

**Comment by ibell** [comment]
Well, if you push it into the repository, yes.

**Comment by kaizoku-ou** [comment]
Thank you

**Comment by kaizoku-ou** [comment]
One more thing. If I edit, for example, some values of water, will the changes be reflected in the wrapper. Say, I change the value of Tmax of water in the repository, how do I make the change reflect in Python? This is just my interest of seeing how I can modify CoolProp

**Comment by ibell** [comment]
If you want to do that, you would check out a local copy of the repository,
make the change in the JSON file, and recompile CoolProp on your machine.

**Comment by kaizoku-ou** [comment]
Thank you for your time. If I have some questions, I'll reopen the issue

**Comment by kaizoku-ou** [comment]
How do I recompile?

**Comment by ibell** [comment]
What language do you interface with CoolProp from?  In general you should read the build directions on the page for your language: http://www.coolprop.org/dev/coolprop/wrappers/index.html

**Comment by Bmuehl** [comment]
Is it possible to take the following refrigerants in the Coolprop database?
R413a
R417a
R422a
R427a

**Comment by jowr** [comment]
Could you point us to the publications with the equations of state? Without a publication or any other source of data it is difficult to include new fluids.

**Comment by ibell** [comment]
I believe these are mixtures.  See #719

**Comment by kaizoku-ou** [comment]
I use python. I've installed CoolProp. I made some changes in the data for Acetone. I dont know how to  recompile so that this data is used. How do I do it?

**Comment by ibell** [comment]
Unfortunately the sourceforge server (for www.coolprop.org) is down, so for
now you can refer to the docs on the build server:
http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/coolprop/wrappers/Python/index.html#manual-installation

Basically, once you have checked out the sources for CoolProp, go into the
wrappers/Python folder, and do

sudo python setup.py install

Out of curiosity, what are you changing in the fluid file?

**Comment by kaizoku-ou** [comment]
Critical Temperature to a random value. Just checking out the limits of the software

**Comment by ibell** [comment]
Ok, but I hope you know its not recommended to change the critical point values.  Out of curiosity, do you have a game plan with your changes, or are you just experimenting (also good!)

**Comment by kaizoku-ou** [comment]
I'm just experimenting...

**Comment by kaizoku-ou** [comment]
I changed the value... I used package_json.py in dev. It gave 4 json files, one of which is all_fluids_verbose.json. How do I convert this to a C++ header file? I tried to use generate_headers.py, but I'm not getting a header file...

**Comment by ibell** [comment]
The header files are auto-generated in the include directory when you run setup.py script, by calling the generate_headers.py script internally.

**Comment by kaizoku-ou** [comment]
I get this error when I run generate_headers.py.....
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\CoolProp\dev\generate_headers.py", line 295, in <module>
    generate()
  File "C:\Python27\Lib\site-packages\CoolProp\dev\generate_headers.py", line 280, in generate
    shutil.copy2(os.path.join(repo_root_path, 'externals','Catch','single_include','catch.hpp'),os.path.join(repo_root_path,'include','catch.hpp'))
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'C:\\Python27\\Lib\\site-packages\\CoolProp\\externals\\Catch\\single_include\\catch.hpp'

**Comment by ibell** [comment]
I think you are confused about how to work with CoolProp sources.  You need
a source tree of CoolProp, that must be checked out using git with all the
submodules attached.  This source tree should be placed somewhere on your
computer, I tend to use the Code/coolprop directory, but it doesn't really
matter.  You should definitely *not* be doing anything in the site-packages
directory of python.

Please follow the instructions I linked to above

Essentially the steps are:
a) Check out CoolProp with all its associated dependencies using git
b) Run the build script which will build CoolProp and copy its dependencies
into the site-packages directory for python

**Comment by kaizoku-ou** [comment]
I think I messed up in the 'not do anything in the site-packages'. Thanks, I'll try and get back to you

**Comment by kaizoku-ou** [comment]
Okay, I tried it. My CoolProp is installed in C:\Python27\Lib\site-packages. I didn't touch that. I downloaded the source files with all sub-files from github to E:\ drive. I ran setup.py in wrappers\Pyhton in this E drive. Then I changed the value in dev\fluids. I ran setup.py again. But the all_fluids_JSON.h file in 'inlcude' of site-packages didn't get updated(C drive). Then I ran the generate_headers.py in dev(E drive). Once again it didn't get updated. What should I do? I also ran the BuildCP and ForceBuild in wrappers/Pyhton.

**Comment by jowr** [comment]
Hi, I am not sure what confuses you, but the instructions here (http://www.coolprop.dreamhosters.com/binaries/sphinx/coolprop/wrappers/Python/index.html#manual-installation) should work for you. 
```batch
pip install cython numpy scipy matplotlib pandas
git clone --recursive https://github.com/CoolProp/CoolProp.git
cd CoolProp/wrappers/Python
# STOP -- Edit the JSON files -- STOP #
python setup.py install
```
If you need to make more changes, simply run `python setup.py install` again.

**Comment by jowr** [comment]
If in doubt, you can run `pip uninstall coolprop` a couple of times before install again.

**Comment by kaizoku-ou** [comment]
Thank you. I've got it to work now.

**Comment by ibell** [comment]
Thanks @jowr for the help!

**Comment by kaizoku-ou** [comment]
I have a small problem again. I downloaded the github repository to my E:\. setup.py works and the change in data after running it, is updated in the include folder in this directory. I copied this inlcude folder and pasted it in C:\Pyhton27\Lib\site-packages\CoolProp and replaced the inlcude folder there. But the change in data is not working when I use PropsSI. What should I do?

**Comment by jowr** [comment]
Parameters are compile into the binaries. You have to recompile the whole thing as described in https://github.com/CoolProp/CoolProp/issues/715#issuecomment-122813211 .

**Comment by kaizoku-ou** [comment]
Sorry for asking the same questions but, I'm still not getting it. I downloaded the source code and ran setup.py in wrappers/Python. How does the files get copied to site-packages in C:/Python/Lib?

**Comment by kaizoku-ou** [comment]
How do I change the directory to CoolProp/wrappers/Python? I think that must be the problem...

**Comment by ibell** [comment]
Open a command prompt, then type:

cd E:\path\to\CoolProp\wrappers\Python

and then

python setup.py install

When you do this successfully, you will see the output from the script, and
at the end it will tell you what files it has copied over.

What do you get when you run setup.py on your machine?  Can you send a
screenshot?

**Comment by jowr** [comment]
Hm, did we solve this issue?

**Comment by ARAIO** [comment]
hi i am new user.
i dont know any thing about phyton and i want know if i want to understand code of coolprop how should i start it?
and i want to add ses24 to coolprop but when i open .json file i dont understand  "ANCILLARIES": {
    "hL": {
      "A": [
        -18419.858867823586, 
        -1074.141372978665, 
        8.588404274043512, 
        -0.0310581993186087, 
        6.598079876842749e-05, 
        -8.430742809745438e-08, 
        6.028394237885649e-11, 
        -1.8861199497679133e-14
      ], 
      "B": [
        1, 
        -0.0016904703507669703
      ], 
      "Tmax": 589.7877587758776, 
      "Tmin": 289.8, 
      "_note": "coefficients are in increasing order; input in K, output in J/mol; value is enthalpy minus hs_anchor enthalpy", 
      "max_abs_error": 5608.996769270838, 
      "max_abs_error_units": "J/mol", 
      "type": "rational_polynomial"
    }, 
    "hLV": {
      "A": [
        -21768.582277585465, 
        548.6932063172326, 
        -1.7026892672173306, 
        -0.006641100371990552, 
        5.193021158373598e-05, 
        -1.2643144075047972e-07, 
        1.3854906816248072e-10, 
        -5.798679240112129e-14
      ], 
what are these?
where is the one user guide or book t start?

**Comment by ibell** [comment]
What is SES24?  You'll need to have a Helmholtz energy explicit EOS or a
cubic eos to integrate it into CoolProp.  Please email what you have on
this fluid to ian.h.bell@gmail.com

**Comment by thorade** [comment]
Closing this issue, as the original issue by the original poster was resolved and marked closed before.
You can still comment on closed issues and the original poster can re-open.
Others should file a new issue instead of asking in the comments of an old issue.

**Comment by DjelJ** [comment]
Hi, 
Could you please add R1123 to CoolProp? Here the EoS
https://docs.lib.purdue.edu/iracc/1698/
Please let me know if that is possible.
Thanks a lot

**Comment by ibell** [comment]
I am not in a position to add R1123 now, but you can!  It would be a
learning experience! You could take an existing fluid as a template and
fill in the coefficients from the paper from Purdue. In principle, that is
all that is required.  It is then only asked that you make a pull request
with the update so that others can use it.  CoolProp is community
developed, so everyone is invited to chip in.

**Comment by PedroSciven** [comment]
I've been using Coolprop lately. I would like to add a  fluid (therminol 55), however I am not getting it. Can you help me??
