### ISSUE TITLE
REFPROP interface failing

### ISSUE THREAD

**Issue by samiit** [CoolProp/CoolProp#716]
I am experiencing some trouble in 5.1.0 with using the REFPROP interface. It was working fine until recently. Now simply I get a Segmentation Fault (core dumped) error when I use the Python interface. I have REFPROP 9.0.

The crash report revealed the following manner in which python crashed:

------------------------------
/usr/local/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.so
/usr/local/lib/python2.7/dist-packages/numpy/core/scalarmath.so
/usr/local/lib/python2.7/dist-packages/numpy/random/mtrand.so
/usr/local/lib/python2.7/dist-packages/CoolProp/CoolProp.so
/usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.so
/usr/local/lib/python2.7/dist-packages/numpy/core/umath.so
/usr/local/lib/refprop/librefprop.so.9.1
/usr/local/lib/python2.7/dist-packages/numpy/lib/_compiled_base.so
/usr/local/lib/python2.7/dist-packages/numpy/fft/fftpack_lite.so
/usr/local/lib/python2.7/dist-packages/CoolProp/_constants.so
/usr/local/lib/python2.7/dist-packages/numpy/linalg/_umath_linalg.so

------------------------------
Sam

**Comment by jowr** [comment]
Could you please provide some more information? Which Linux are you using? 32bit? Why do you install REFPROP 9.0 as `librefprop.so.9.1`? What happened that makes it crash? Di you update Python?

**Comment by samiit** [comment]
I am using 64-bit Xubuntu provided by CAE Linux.

I used [Ben's] (https://github.com/BenThelen/python-refprop) proposed method; so it generated librefprop.so.9.1.
The shared object file has all the necessary functions `nm /usr/local/lib/refprop/librefprop.so.9.1`
and I can also access with my own python wrapper written along the lines of that proposed on [REFPROP's website] (http://www.boulder.nist.gov/div838/theory/refprop/LINKING/WERNICK.ZIP). 

Update: I compiled it with v0.2 of [your] (https://github.com/jowr/librefprop.so) repository with gfortran-4.9 (4.6 didn't work) and it compiled. Now I have the shared object for librefprop.so.9.0, and the example.py works perfectly. Still when I try to call this within CoolProp the following way (within ipython):
`In [1]: import CoolProp.CoolProp as Cp`
`In [2]: Cp.PropsSI('D','P', 101325, 'T', 300, 'Water')`
`Out[2]: 996.5569352650017`
`In [3]: Cp.PropsSI('D','P', 101325, 'T', 300, 'REFPROP::Water')`
`Segmentation fault (core dumped)`

I did not update Python, but recently while installing julia, I did got a few things messed up with the blas and lapack libraries (it brought in some atlas libraries which I don't understand well enough). I removed julia and its ppa and got things back as much as I could perceive.

**Comment by jowr** [comment]
Yes, the solver packages should get in your way. CoolProp looks in `/opt/refprop` (https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L64), it might help to make symlinks in that directory that point to your files in `/usr/local/lib`. Just guessing though.

**Comment by samiit** [comment]
Hi Jorrit,
I do have the right files in `/opt/refprop`. That happened when I installed v0.2 of your [repository](https://github.com/jowr/librefprop.so).
Something else seems to be troubling.

**Comment by jowr** [comment]
Could you debug your installation? 
```
from __future__ import print_function
import CoolProp
print(CoolProp.__version__)
print(CoolProp.__gitrevision__)
import CoolProp.CoolProp as CP
CP.set_debug_level(150)
CP.PropsSI('D','P', 101325, 'T', 300, 'REFPROP::Water')
```

**Comment by samiit** [comment]
This is the output.

--------------------------------------------------
`import CoolProp`
`print(CoolProp.__version__)`
5.1.0

`print(CoolProp.__gitrevision__)`
dca69a8bb79b3511648b128e080aba85d04e191f

`import CoolProp.CoolProp as CP`
`CP.set_debug_level(150)`
`CP.PropsSI('D','P', 101325, 'T', 300, 'REFPROP::Water')`

src/CoolProp.cpp:101: backend extracted. backend: REFPROP. fluid: Water
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (/opt/refprop/fluids/WATER
src/Backends/REFPROP/REFPROPMixtureBackend.cpp:473: Successfully loaded REFPROP fluid: /opt/refprop/fluids/WATER.FLD
src/CoolProp.cpp (311): input pair = 7 
src/CoolProp.cpp (312): in1 = [ 101325.000 ] 
src/CoolProp.cpp (313): in2 = [  300.000 ] 
src/CoolProp.cpp (326): Iterating over 1 input value pairs.
src/Backends/REFPROP/REFPROPMixtureBackend.cpp:369: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match 
src/Backends/REFPROP/REFPROPMixtureBackend.cpp:369: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match

--------------------------------------------
Sam

**Comment by jowr** [comment]
Yes, the fluid file is not the problem. Your output tells you that CoolProp found the file and loaded it successfully. I could confirm your issues on a 64bit system and on a 32bit system:
```
git clone --recursive https://github.com/jowr/librefprop.so.git librefprop.so.git
cd librefprop.so.git
git checkout tags/v0.2
cp -r ../refprop9.0/fortran/* fortran
cp -r ../refprop9.0/fluids files/
cp -r ../refprop9.0/mixtures files/
# For 64bit you have to add -fPIC to the default compile flags in Makefile
make header library
sudo make install
conda create -yq -n refproptest cython pip matplotlib numpy scipy pandas
source activate refproptest
conda install -y -c https://conda.binstar.org/coolprop/channel/dev coolprop
python -c "from __future__ import print_function
import CoolProp
print(CoolProp.__version__)
print(CoolProp.__gitrevision__)
import CoolProp.CoolProp as CP
CP.set_debug_level(150)
CP.PropsSI('D','P', 101325, 'T', 300, 'REFPROP::Water')"
```
on 64bit:
```
5.1.1dev
f4cda1d82816bdfc1b042d581398265fc3541f52
../../src/CoolProp.cpp:101: backend extracted. backend: REFPROP. fluid: Water
AbstractState::factory(REFPROP,[ Water ])
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (/opt/refprop/fluids/WATER
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:306: Successfully loaded REFPROP fluid: /opt/refprop/fluids/WATER.FLD
../../src/CoolProp.cpp (317): input pair = 7
../../src/CoolProp.cpp (318): in1 = [ 101325.000 ]
../../src/CoolProp.cpp (319): in2 = [  300.000 ]
../../src/CoolProp.cpp (332): Iterating over 1 input value pairs.
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:192: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:192: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match
Segmentation fault
```
on 32bit:
```
5.1.1dev
f4cda1d82816bdfc1b042d581398265fc3541f52
../../src/CoolProp.cpp:101: backend extracted. backend: REFPROP. fluid: Water
AbstractState::factory(REFPROP,[ Water ])
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (/opt/refprop/fluids/WATER
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:306: Successfully loaded REFPROP fluid: /opt/refprop/fluids/WATER.FLD
../../src/CoolProp.cpp (317): input pair = 7
../../src/CoolProp.cpp (318): in1 = [ 101325.000 ]
../../src/CoolProp.cpp (319): in2 = [  300.000 ]
../../src/CoolProp.cpp (332): Iterating over 1 input value pairs.
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:192: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:192: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match
Segmentation fault
```
Stay tuned, I'll try to dig into this, but it looks more like a REFPROP issue...

**Comment by jowr** [comment]
As expected, something is wrong with the REFPROP library. We might actually call functions that do not exist in version 9.0, but I am nore sure. It however work with REFPROP 9.1:
```
git clone --recursive https://github.com/jowr/librefprop.so.git librefprop.so.git
cd librefprop.so.git
cp -r ../refprop9.1/fortran/* fortran
cp -r ../refprop9.1/fluids files/
cp -r ../refprop9.1/mixtures files/
make header library
sudo make install
conda create -yq -n refproptest cython pip matplotlib numpy scipy pandas
source activate refproptest
conda install -y -c https://conda.binstar.org/coolprop/channel/dev coolprop
python -c "from __future__ import print_function
import CoolProp
print(CoolProp.__version__)
print(CoolProp.__gitrevision__)
import CoolProp.CoolProp as CP
CP.set_debug_level(150)
CP.PropsSI('D','P', 101325, 'T', 300, 'REFPROP::Water')"
```
On 64bit *and* 32bit systems:
```
5.1.1dev
f4cda1d82816bdfc1b042d581398265fc3541f52
../../src/CoolProp.cpp:101: backend extracted. backend: REFPROP. fluid: Water
AbstractState::factory(REFPROP,[ Water ])
REFPROP error/warning [ierr: 101]: [SETUP error 101] error in opening file for component #  1; filename = (/opt/refprop/fluids/WATER
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:306: Successfully loaded REFPROP fluid: /opt/refprop/fluids/WATER.FLD
../../src/CoolProp.cpp (317): input pair = 7
../../src/CoolProp.cpp (318): in1 = [ 101325.000 ]
../../src/CoolProp.cpp (319): in2 = [  300.000 ]
../../src/CoolProp.cpp (332): Iterating over 1 input value pairs.
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:192: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:192: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match
../../src/Backends/REFPROP/REFPROPMixtureBackend.cpp:192: The current fluid can be reused; /opt/refprop/fluids/WATER.FLD and /opt/refprop/fluids/WATER.FLD match
AbstractState: keyed_output called for Dmass
_PropsSI will return 996.557
```

**Comment by samiit** [comment]
Thanks for verifying that. I would like to add that I didn't face this problem until around a month ago. I mean:
`CP.PropsSI('D','P', 101325, 'T', 300, 'REFPROP::Water')`

used to work until recently. Does it work with the previous release of CoolProp?

Sam

**Comment by jowr** [comment]
I think the reason is that we changed some of the internals to make use of new REFPROP features, but I cannot remember at when we changed it. You could have a look at the changelog file for CoolProp to find out when REFPROP-related changes occurred.

**Comment by jowr** [comment]
... but why don't you just upgrade to 9.1? If you have a license for 9.0, the upgrade is for free: http://www.nist.gov/srd/nist23.cfm

**Comment by samiit** [comment]
Yes, I think we'll do that.
Thanks,
Sam
