### ISSUE TITLE
Matlab-binaries-windows-64bit-VS10 broken

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#717]
This commit broke the one of the builds for the MATLAB wrapper: a58f670413223f21d7024a2e36938a57c6908d09 
Any idea what went wrong?

**Comment by ibell** [comment]
I'm not entirely sure.  We might have to disable testing of MATLAB on windows, as was done before.  It seems there is something wrong on windows.

**Comment by ibell** [comment]
Working now.
