### ISSUE TITLE
Unable to find an entry point named \u0027CSharp

### ISSUE THREAD

**Issue by hasanacul** [CoolProp/CoolProp#718]
Dear friends,
We update our version to 5.0.8 and we got an error which we have not had from previous versions that

Unable to find an entry point named \u0027CSharp_HAPropsSI\u0027 in DLL \u0027CoolProp\u0027."
Unable to find an entry point named 'CSharp_HAPropsSI' in DLL 'CoolProp

Please help us to run it.
br
Hasan

(PS:We use web based technology, asp.net, mvc 4)

**Comment by ibell** [comment]
Please try the 5.1.1 development download following the second link in paragraph 1 from here: http://www.coolprop.org/dev/coolprop/wrappers/Csharp/index.html#pre-compiled-binaries

I had someone report a similar bug that was fixed by this version.

**Comment by ibell** [comment]
Also, you should definitely make sure it works properly on your PC in visual studio before deploying it.  Much easier to debug the local version.

**Comment by ibell** [comment]
Any progress?

**Comment by hasanacul** [comment]
Dear Ian,

 

Sorry for my late reply. We have solved the issue by using updated dll.  

 

By the way we have also solved another issue which is related to getting problem when we try to use AEG and APG brines on the internet.  We think that the problem has come from server edition. We got problem on 2003 edition but not on 2012.

 

Best Regards,

 

Hasan
