### ISSUE TITLE
R1233zd(E) surface tension curve not implemented

### ISSUE THREAD

**Issue by agshaligram** [CoolProp/CoolProp#720]
Hi,

I am working on Matlab code using R1233zd(E). When I run my program, I get an error as follows : 

Warning: surface tension curve not provided 
Error using CoolPropMATLAB_wrap
Failure in function PropsSI.
Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] =
  CoolPropMATLAB_wrap(236,'_wrap_PropsSI',varargin{:});
Error in Bubble_Dep_Dia_R1233zdE_4point4 (line 9)
sigma=CoolProp.PropsSI('I','T',277.4,'Q',0,'R1233zd(E)');

Can you advise what could be the issue and how to solve it ??

**Comment by jowr** [comment]
Normally, I would advise you to got to http://coolprop.sourceforge.net/fluid_properties/PurePseudoPure.html#list-of-fluids and check the references for the fluid you want to use. Not all fluids have functions for all properties. Since all references are missing for your fluid, there is a good chance that there simply is no data. Do you have a reference publication for transport properties of R1233zd(E)?

**Comment by ibell** [comment]
@jowr is right.  The text "Warning: surface tension curve not provided " should have been a giveaway. There is currently no surface tension curve for this fluid available.

**Comment by ibell** [comment]
Curves available in Condou paper.

**Comment by agshaligram** [comment]
Hi,

I am not clear. Does this mean I can use CoolProp with R1233zd(E) without
any error ? What about k (thermal conductivity) and cp(specific heat at
constant pressure) ??

**Comment by ibell** [comment]
Cp is definitely no problem for R12333zd(E)

Viscosity and conductivity for HFO (of which R1233zd(E) is one) is more
problematic.  Correlations have not been constructed for these fluids.

**Comment by jowr** [comment]
There are some data for transport properties here: http://dx.doi.org/10.1021/je300776s but that is not sufficient for a proper implementation. @agshaligram, thank you for pointing to that paper, but I guess the best way forward is to implement things yourself based on the data from the paper.

**Comment by jowr** [comment]
Note also: http://pubs.acs.org/doi/abs/10.1021/acs.jced.5b00348

**Comment by ibell** [comment]
See also #728
