### ISSUE TITLE
HapropsSI("T", "B", 299.15, "R", 0, "P", 101325) lead to an error

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#727]
errstring	"Temperature to QT_flash [1000 K] must be in range [273.06 K, 647.096 K]"

**Comment by ibell** [comment]
Ok, I'll take a look.  It would be nice if when I fix bugs you could test
and make sure they work and write a little note to that effect on the issue.

**Comment by pmanach** [comment]
Thanks Ian.
