### ISSUE TITLE
formula problem when using coolprops in excel

### ISSUE THREAD

**Issue by sumitmahajanmnsuedu** [CoolProp/CoolProp#729]
I have one trouble while using CoolProps. It’s more of the excel problem but please look at it. The issue is, if I solve a power cycle problem by using CoolProps in excel and then send the file to other users. At other user computer, there is some address which appear in front of the formula. And to make sure that the file run in other computer the user has to delete the address from everywhere if front of CoolProp.
For instant:
If I download the TestExcel file, which is available at coolprop website, and try to run, the following things come in front of the formula in my computer:
Critical temperature of R410A:
 
='C:\Users\Belli\Documents\Code\PythonModules\coolprop\wrappers\Excel\CoolProp.xlam'!Props1SI("R410A","Tcrit")
Critical density of propane:
='C:\Users\Belli\Documents\Code\PythonModules\coolprop\wrappers\Excel\CoolProp.xlam'!Props1SI("Propane","rhocrit")
Density of Air at STP:
 
='C:\Users\Belli\Documents\Code\PythonModules\coolprop\wrappers\Excel\CoolProp.xlam'!PropsSI("Dmass","T",298.15,"P",101325,"HEOS::Nitrogen")
 
To make sure it works in my computer, I have to delete “'C:\Users\Belli\Documents\Code\PythonModules\coolprop\wrappers\Excel\CoolProp.xlam'!” part manually.
The same issue comes when I send my file to other users. I am attaching my file to you. Kindly, have a look at it. Is there any solution for this problem? I know it is more of excel problem but is there any solution for this problem. Thanks.
Regards,
Sumit

**Comment by ibell** [comment]
I'm really not sure.  I think this is an excel-related problem, but there might be a resolution.  I'm not sure what it might be though...

**Comment by ibell** [comment]
Seems this is a well-known problem: http://stackoverflow.com/questions/6414719/remove-addin-path-from-udf-in-excel-formula

**Comment by ibell** [comment]
Looks like another bad design decision in Excel.  Sorry there's not more we can do for you.

**Comment by ibell** [comment]
Actually, I am wrong about this.

If you go into Data->Update links in Excel, you can select the location for CoolProp.xlam, and that should update all the links to the right place.
