### ISSUE TITLE
docs not building

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#736]
The documentation builder has been broken for a while :-(

**Comment by ibell** [comment]
Yes, I am sadly aware of the issue, and will try to fix it tonight.

**Comment by ibell** [comment]
Looks like some non-ascii characters made it into the bib file

**Comment by ibell** [comment]
see 3124bc93a64974f55439215c0f04037b94365278, this might have fixed it

**Comment by ibell** [comment]
And we're back.
