### ISSUE TITLE
TTSE ranges

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#738]
I have some fluids (custom REFPROP files) that have a `Tmin>Ttriple`, which causes problems with the tables. We might want to build the tables for `max(Tmin,Ttriple)<T<Tmax` and `max(pmin,ptriple)<p<pmax` instead.

**Comment by ibell** [comment]
Do you have a fluid in mind that I could test with?

**Comment by jowr** [comment]
Haven't seen it in any of the public files yet.

**Comment by ibell** [comment]
Some of the old refrigerants I think - R11?
