### ISSUE TITLE
HapropsSI("T", "B", 299.15, "R", 0, "P", 101325) lead to an error

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#740]
Sorry Ian, another bug ...

**Comment by ibell** [comment]
That's the one I just fixed...

**Comment by ibell** [comment]
Cannot replicate.  Both W=0 and R=0 work fine for me.

**Comment by TimHarvey2** [comment]
HapropsSI("T", "B", 299.15, "W", 0, "P", 101325) give 0 for me where HapropsSI("T", "B", 299.16, "W", 0, "P", 101325) gives 351.1027252 
HapropsSI("T", "B", 299.15, "R", 0, "P", 101325) gives 0 at any value of B, But works for any value of R >0 <1 using Excel 10 64bit and 5.1.1DLL

**Comment by ibell** [comment]
How about the nightly version?  I fixed some bugs with this stuff.

**Comment by TimHarvey2** [comment]
Same result but looks like same version same size and date 15/7/2015 SourcForge having problems maybe it is not updated yet.

**Comment by TimHarvey2** [comment]
Python give error will try new version when available

>>> TTest= HaPropsSI("T", "B", 299.15, "W", 0, "P", 101325)

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    TTest= HaPropsSI("T", "B", 299.15, "W", 0, "P", 101325)
NameError: name 'HaPropsSI' is not defined
>>> TTest= HAPropsSI("T", "B", 299.15, "W", 0, "P", 101325)

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    TTest= HAPropsSI("T", "B", 299.15, "W", 0, "P", 101325)
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4112)
  File "CoolProp\HumidAirProp.pyx", line 47, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2865)
ValueError: Brent's method f(t) is NAN for t = 717.837 :: inputs were:"T","B",2.9914999999999998e+02,"W",0.0000000000000000e+00,"P",1.0132500000000000e+05 
>>> >>> TTest= HAPropsSI("T", "B", 299.16, "W", 0, "P", 101325)
SyntaxError: invalid syntax
>>> >>> TTest= HAPropsSI('T', 'B', 299.15, 'W', 0, 'P', 101325)
SyntaxError: invalid syntax
>>> TTest= HAPropsSI('T','B',299.15,'W',0,'P',101325)

Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    TTest= HAPropsSI('T','B',299.15,'W',0,'P',101325)
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4112)
  File "CoolProp\HumidAirProp.pyx", line 47, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2865)
ValueError: Brent's method f(t) is NAN for t = 717.837 :: inputs were:"T","B",2.9914999999999998e+02,"W",0.0000000000000000e+00,"P",1.0132500000000000e+05 
>>> TTest= HAPropsSI('T','B',299.16,'W',0,'P',101325)
>>> PRint TTest
SyntaxError: invalid syntax
>>> Print TTest
SyntaxError: invalid syntax
>>> print TTest
351.102725155
>>>

**Comment by pmanach** [comment]
Hello Ian, yes problem on sourceforge. The nightly version is 15-07-2015.

**Comment by ibell** [comment]
Try from here temporarily - these are nightly builds:
http://www.coolprop.dreamhosters.com/binaries/

**Comment by TimHarvey2** [comment]
R one works in excell
W give 0 in excell but works with B = 299.16
in Python Neither work unless B = 299.16
>>> TTemp = HAPropsSI('T','B',299.15,'W',0,'P',101325)

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    TTemp = HAPropsSI('T','B',299.15,'W',0,'P',101325)
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4112)
  File "CoolProp\HumidAirProp.pyx", line 47, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2865)
ValueError: Brent's method f(t) is NAN for t = 717.837 :: inputs were:"T","B",2.9914999999999998e+02,"W",0.0000000000000000e+00,"P",1.0132500000000000e+05 
>>> TTemp = HAPropsSI('T','B',299.16,'W',0,'P',101325)
>>> print TTemp
351.102725155

**Comment by pmanach** [comment]
hello Ian, 

I just downloaded the latest version at http://www.coolprop.dreamhosters.com/binaries/

HAPropsSI('T','B',299.15,'W',0,'P',101325) : 
In Excel, the result is OK.
In VB.NET, the result is NOK.

"Brent's method f(t) is NAN for t = 717.837"

**Comment by pmanach** [comment]
hello Ian,
did you find soem time to look at thsi problem ?
Sincerely

**Comment by ibell** [comment]
I'm afraid I don't entirely follow all the things that have been mentioned
in this thread.  Can you please summarize for me what exactly doesn't work?

**Comment by pmanach** [comment]
hello Ian,

I just download the latest version today (5.1.2dev).
Gitversion  : bccebc2592e9b3ddbaf99f21dfa05a4684fc4280

the problem is the following : 
HAPropsSI('T','B',299.15,'W',0,'P',101325) : 
- In Excel, the result is OK.
- In VB.NET, the result is NOK  : "Brent's method f(t) is NAN for t = 717.837"

**Comment by pmanach** [comment]
Thanks for your time and your help.
It works well.
