### ISSUE TITLE
PropsSI("V", "T", 259.0780739464716, "P", 200000.0, "Water") problem

### ISSUE THREAD

**Issue by acuiko** [CoolProp/CoolProp#743]
Hi,
could you please check this
PropsSI("V", "T", 259.0780739464714, "P", 200000.0, "Water"); gives 0.0031969285849966045
PropsSI("V", "T", 259.0780739464716, "P", 200000.0, "Water"); leads to an error
PropsSI("V", "T", 259.0780739464718, "P", 200000.0, "Water"); gives 0.0031969285849965633

Error message: Inputs in Brent [50409.092155,72813.133113] do not bracket the root.  Function values are [127.600581,6895.755236]

I'm using dll downloaded from http://www.coolprop.dreamhosters.com/binaries/Csharp/Windows_32bit/

**Comment by jowr** [comment]
Haven't checked it, but aren't almost on the melting line?

**Comment by acuiko** [comment]
Seems to be on the line, sorry for the inattention
