### ISSUE TITLE
Implement viscosity models for HFO (ECS?)

### ISSUE THREAD

**Issue by agshaligram** [CoolProp/CoolProp#746]
Hi,

I am getting all sorts of problems in using new version of CoolProp. I had successfully used version 4 ( more than a year ago) ; but with version 5.1 the same Code is not working. Just to give an example : I am trying to use R1234ze(E) and am getting an error that viscosity model is not available for this fluid. Whereas earlier I did use the same Code and it was giving me results using the R1234ze(E).

Can you advise where could be the problem ??

Thanks

**Comment by jowr** [comment]
It might be that the transport routines were removed due to large uncertainties. @ibell what do you think? Please have a look at https://github.com/CoolProp/CoolProp/blob/master/FAQ.md#usage

**Comment by ibell** [comment]
@agshaligram : The models that were in 4.2.x were very approximate, there is some new data and I plan to fit curves myself in the near future that will fix the viscosity formulations

**Comment by ibell** [comment]
Would be nice to have something for R1234ze and R1234yf at the very least
