### ISSUE TITLE
Plotting example on coolprop.org does not work - potentially related to issue #351

### ISSUE THREAD

**Issue by bachc** [CoolProp/CoolProp#747]
I noticed this issue when trying the plotting example on http://www.coolprop.org/apidoc/CoolProp.Plots.Plots.html 

It appears the the Ts plot uses kJ/kg, but the isolines use J/kg. Commenting out shows that the isolines are drawn, just in different units.  See modified example code below. Hope this is a relatively easy fix.

from matplotlib import pyplot
from CoolProp.Plots import Ts, drawIsoLines
Ref = 'n-Pentane'
ax = Ts(Ref)
#ax.set_xlim([-0.5, 1.5])
#ax.set_ylim([300, 530])
quality = drawIsoLines(Ref, 'Ts', 'Q', [0.3, 0.5, 0.7, 0.8], axis=ax)
isobars = drawIsoLines(Ref, 'Ts', 'P', [100, 2000], num=5, axis=ax)
isochores = drawIsoLines(Ref, 'Ts', 'D', [2, 600], num=7, axis=ax)
pyplot.savefig('props_plot.png')
pyplot.show()
![props_plot](https://cloud.githubusercontent.com/assets/2520741/8882311/9407ecda-320b-11e5-80a5-35b56d593033.png)

**Comment by ibell** [comment]
The plotting code, while unloved for a long time, is getting a serious
overhaul: https://github.com/CoolProp/CoolProp/tree/draw_process

**Comment by jowr** [comment]
Please also look at our discussion at #351

**Comment by bachc** [comment]
Looks great! Any idea on when this will be merged back (and the examples functional) with the main branch?

**Comment by jowr** [comment]
No, not really. I cannot work on it until September, but all are invited to continue the work in the meantime.
