### ISSUE TITLE
Invalid index to calc_first_saturation_deriv in TabularBackends

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#750]
In C++, when executing the [line](https://github.com/CoolProp/ExternalMedia/blob/JonWel/Projects/Sources/coolpropsolver.cpp#L358):
```C++
properties->dTp = state->first_saturation_deriv(CoolProp::iT, CoolProp::iP);
```
with a tabular backend (`TTSE` or `BICUBIC`), I get the [following error](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.h#L280):
```
Invalid index to calc_first_saturation_deriv in TabularBackends
```

I think it has something to do [with](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L551) `cached_saturation_iL` and `cached_saturation_iV` with both values equal to `0` as initialised in `update(PQ_INPUTS, p, 0)` (see [TTSEBackend](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TTSEBackend.cpp#L183) or [BICUBICBackend](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/BicubicBackend.cpp#L268) ).
This is smaller 2 thus giving the error.

I didn't get any error executing this line with the non tabular `HEOS` backend.

**Comment by ibell** [comment]
Can you give a more complete example showing what inputs you used to call update() function?

**Comment by JonWel** [comment]
I currently tested it from a C++ code executing `ExternalMedia` (that I adapt to run with `CoolProp 5`):
```C++
#define _CRTDBG_MAP_ALLOC
#define _CRT_SECURE_NO_WARNINGS
#include <stdlib.h>
#include <crtdbg.h>

#include "CoolProp.h"
#include "math.h"
#include "time.h"
#include "stdlib.h"
#include <stdio.h>
#include <iostream>
#include <vector>
#include <conio.h>
#include "Solvers.h"
#include "AbstractState.h"
#include "externalmedialib.h"
#include "crossplatform_shared_ptr.h"

struct structtype{
	double Pr;		//prandtl number
    double T;		//temperature
    double a;		//velocity of sound
    double beta;	//isobaric expansion coefficient
    double cp;		//specific heat capacity cp
    double cv;		//specific heat capacity cv
    double d;		//density
    double ddhp;	//derivative of density wrt enthalpy at constant pressure
    double ddph;	// derivative of density wrt pressure at constant enthalpy
    double eta;		//dynamic viscosity
    double h;		//specific enthalpy
    double kappa;	//compressibility
    double lambda;	//thermal conductivity
    double p;		//pressure
    double s;		//specific entropy
	int phase;		//phase
};

structtype mystruct;

ExternalThermodynamicState state;	// Defined in the externalmedia headers

int main()
{	
	std::cout << "1) ExternalMedia R245fa calc_transport=0|debug=10" << std::endl;
	struct structtype *struct_pointer;
	struct_pointer = &mystruct;
	struct_pointer->eta = 3;
	mystruct.p=2;

	ExternalThermodynamicState *pointer;
	pointer = &state;
	
	TwoPhaseMedium_setState_ph_C_impl(8e5, 4E5, 2, pointer, "R245fa", "CoolProp", "R245fa|calc_transport=0|debug=10");

	std::cout << "2) ExternalMedia R245fa calc_transport=0|enable_TTSE=1|debug=10" << std::endl;
	TwoPhaseMedium_setState_ph_C_impl(8e5, 4E5, 2, pointer, "R245fa", "CoolProp", "R245fa|calc_transport=0|enable_TTSE=1|debug=10");

	std::cout << "3) ExternalMedia R245fa calc_transport=0|enable_BICUBIC=1|debug=10" << std::endl;
	TwoPhaseMedium_setState_ph_C_impl(8e5, 4E5, 2, pointer, "R245fa", "CoolProp", "R245fa|calc_transport=0|enable_BICUBIC=1|debug=10");

	system("pause");
	return 0;
}
```
With the  `ExternalMedia` code from https://github.com/CoolProp/ExternalMedia/tree/JonWel

But I think it would be easier for you to test from a code using more specifically the problematic part (internally executed in `ExternalMedia`):
```C++
shared_ptr<CoolProp::AbstractState> state(CoolProp::AbstractState::factory("TTSE&HEOS","R245fa"));
state->update(CoolProp::PQ_INPUTS,3.647349e+6,0);
//! Derivative of Ts wrt pressure
double dTp = state->first_saturation_deriv(CoolProp::iT, CoolProp::iP);
```

However, I just wonder if the error could be caused by table that would not have been updated since `CoolProp` updates. I'll remove them and run again to check if it improves anything.

**Comment by JonWel** [comment]
I updated the post above.

**Comment by ibell** [comment]
Perfect, I can work with that.  I thought I had fixed the bugs with the saturation calls, but clearly not.  I'll take some time this weekend and fix it.
