### ISSUE TITLE
Phase above Critical Pressure

### ISSUE THREAD

**Issue by enter802** [CoolProp/CoolProp#752]
I realized that one cannot determine the phase for a fluid above critical pressure with CoolProp. e.g. I tried -  CoolProp.PhaseSI('T',273+110,'P',4.7e6,'R134a') and the answer is "supercritical". The parameters chosen are from a real plant fro R134a. 

But according to the definition of critical temperature (The critical temperature of a substance is the temperature at and above which vapor of the substance cannot be liquefied, no matter how much pressure is applied. source: https://www.chem.purdue.edu/gchelp/liquids/critical.html), since the critical temperature of R134a is 101.2100 degC, should not the phase at the above parameters be vapor? 

I would convince myself it to be vapor, but was just wondering, if it is that simple, why cannot CoolProp provide the phase. Some suggestions to determine the phase would be greatly appreciated.

Thanks in advance!

**Comment by jowr** [comment]
We do differentiate between gas-like, liquid-like and supercritical states: 
http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function
https://github.com/CoolProp/CoolProp/blob/master/include/AbstractState.h#L56

It should yield supercritical liquid in your case. Have you tried `CoolProp.CoolProp.PropsSI('Phase','T',273+110,'P',4.7e6,'R134a')`?

**Comment by enter802** [comment]
i just tried the command line you shared and the answer is "1" and when I checked the phase index, 1 = supercritical. So, it really does not make any difference compared to the command line I used previously, which also gave "supercritical".

**Comment by jowr** [comment]
OK, I had a second look at your data. Am I right that both *T* and *p* are above critical conditions? If so, the figure in the documentation reveals that CoolProp calls that state supercritical:
![image from docs](http://www.coolprop.dreamhosters.com/binaries/sphinx/_images/HighLevelAPI-1.png)

This definition is also in agreement with, for example, the article on wikipedia:
![wikipedia](https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Phase-diag2.svg/350px-Phase-diag2.svg.png)

I am wondering what it is you need help with:
  - Would you like us to merge `supercritical` and `supercritical_gas`?
  - Would you like to add a paragraph to the docs? If you think that others might be confused/surprised by the same issue, you are more than welcome to improve the documentation.

**Comment by enter802** [comment]
Yes, you are absolutely right that both T and p are above critical conditions. And I will tell you why I am "almost" convinced that even with both T and p are above critical conditions, the state should be supercritical gas - 

I am working on a real ORC plant and the inlet condition at the turbine/expander is 4658kPa and 235degC both of which are above the critical point for R134a, and since it is not possible to have anything but gas entering the turbine/expander, it strongly suggests (at least from a practical point of view) that the phase should be supercritical gas.

I personally am not an expert in this field and hence looking for your expert opinions instead!

**Comment by ibell** [comment]
The term "supercritical" is not well defined.  As a result we have decided
(somewhat arbitrarily) to split up the regions into supercritical (T>Tc and
p > pc), supercritical gas (T > Tc and p < pc) and supercritical liquid (T
< Tc and p > pc).  There is no clear break between a gas that is above the
critical temperature and a supercritical fluid.

**Comment by ibell** [comment]
We could add more information to the docs if there is something concrete
that is unclear.

**Comment by thorade** [comment]
Another approach could be to use the critical density and then say
 * states with d<d_crit behave vapour_like and 
 * states with d>d_crit behave liquid_like.
Just try and add the d=d_crit line to the above pT plot, it extends the saturation line nicely.
Also, one could try to divide the regions based on a dT plot.

But there are many other ways to divide the T>T_crit region, many of them extend the saturation line nicely. E.g. one could make up a criterion based on Z or on isothermal compressibility (∂v/∂p)_T and its derivatives to decide whether the fluid behaves like a liquid or like a gas (also see #659).

**Comment by ibell** [comment]
@thorade is right that there are many definitions of/in the "supercritical" domain.  We went for the simplest one to understand.  The division based on density gives a "gas"-like and "liquid"-like division in the SC region.

In the end, I think our phase division makes sense, and I don't see a compelling reason to change it.  It's somewhat arbitrary anyway.
