### ISSUE TITLE
Relative humidity calculation error

### ISSUE THREAD

**Issue by acuiko** [CoolProp/CoolProp#753]
Hi,
the error occurs sometimes when try to calculate relative humidity. In the same conditions the other things (enthalpy, humidity ratio etc.) are calculated faultless

HAPropsSI("R", "T", 294.68737245854609, "D", 283.95, "P", 98755) = 0.503...
HAPropsSI("R", "T", 294.68737245854612, "D", 283.95, "P", 98755) = Infinity
HAPropsSI("R", "T", 294.68737245854616, "D", 283.95, "P", 98755) = 0.503...

Coolprop library is downloaded from http://www.coolprop.dreamhosters.com/binaries/Csharp/Windows_32bit/

**Comment by ibell** [comment]
a) Can you do the same with 64-bit C#?
b) What if you call get_global_param_string("errstring") after the failing
call? What do you get?

**Comment by acuiko** [comment]
a) result is the same with 64bit dll
b) Maxwell solver did not converge after 30 iterations;  rhoL: 55388.15439495009 rhoV: 1.051082911190593 error: 2.05134e-009 dvL/vL: 1.77528e-014 dvV/vV: 1.22615e-014 pL: 2571.61 pV: 2571.61

**Comment by ibell** [comment]
I'm thinking this should be fixed.  Re-open if that is not the case.  Please confirm.

**Comment by acuiko** [comment]
now it works, thanks
