### ISSUE TITLE
HAPropsSI does not converge for T= 299.8 K

### ISSUE THREAD

**Issue by bachc** [CoolProp/CoolProp#756]
Back for more software testing :)

HAPropsSI works great, except for 299.8 K, but works fine for other temperatures.
Version of CoolProp is the current one.

Added printout below, issue seems convergence in CoolProp.cpp.

>>> import CoolProp as CP
>>> CP.__version__
u'5.1.1'
>>>

>>> HAPropsSI('W','T',299.1,'P',101325,'R',0.51)
0.01072579950552751
>>> HAPropsSI('W','T',299.8,'P',101325,'R',0.51)

Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    HAPropsSI('W','T',299.8,'P',101325,'R',0.51)
  File "CoolProp\HumidAirProp.pyx", line 3, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:4112)
  File "CoolProp\HumidAirProp.pyx", line 47, in CoolProp.CoolProp.HAPropsSI (CoolProp\CoolProp.cpp:2865)
ValueError: Maxwell solver did not converge after 30 iterations;  rhoL: 55317.94333544713 rhoV: 1.404747498588554 error: 3.95539e-009 dvL/vL: -1.07605e-014 dvV/vV: -2.78591e-014 pL: 3495.44 pV: 3495.44
 :: inputs were:"W","T",2.9980000000000001e+02,"P",1.0132500000000000e+05,"R",5.1000000000000001e-01 
>>> HAPropsSI('W','T',299.9,'P',101325,'R',0.51)
0.011253867557047863
>>> import CoolProp as CP
>>> CP.__version__
u'5.1.1'
>>>

**Comment by ibell** [comment]
32-bit or 64-bit?

**Comment by ibell** [comment]
That works fine in C++ on OS X in 64-bit

**Comment by ibell** [comment]
Works fine for me:
``` python
>>> import CoolProp
>>> HA = CoolProp.CoolProp.HAPropsSI
>>> HA("W","T",2.9980000000000001e+02,"P",1.0132500000000000e+05,"R",5.1000000000000001e-01 )
0.011186615660923415
```

**Comment by ibell** [comment]
And for me on windows (python 2.7, 64-bit):
```
>>> import CoolProp
>>> HA = CoolProp.CoolProp.HAPropsSI
>>> HA("W","T",2.9980000000000001e+02,"P",1.0132500000000000e+05,"R",5.1000000000000001e-01 )
0.011186615660678806
```

**Comment by ibell** [comment]
Pushed a change - can you please try with the development version? http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation

**Comment by ibell** [comment]
I'm thinking this should be fixed. Re-open if that is not the case. Please confirm.

**Comment by bachc** [comment]
Works perfectly. Thanks for the quick fix!!

Side-note: 
On http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation, you could add '--trusted-host www.coolprop.dreamhosters.com', to the pip command for installing the development version. Otherwise pip just installs the current release.
