### ISSUE TITLE
HAPropsSI is very slow!

### ISSUE THREAD

**Issue by babaksamareh** [CoolProp/CoolProp#758]
Hello guys,

Is it normal for HAPropsSI to take 10 seconds to calculate all the available variables? Is there anyway to speed up the process?

Cheers,

**Comment by ibell** [comment]
What are your inputs?  For some inputs, there are many(!) levels of nested
iterations.  Things like wet bulb temperatures are particularly slow.
Though 10 seconds for one input does seem slow to me.

Can you show your code?

**Comment by babaksamareh** [comment]
Well I'm using this engine in an app. The idea is to find all the properties based on 2 inputs. Here is the code:

    float P   = HumidAir::HAPropsSI("P", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Tdb = HumidAir::HAPropsSI("Tdb", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Twb = HumidAir::HAPropsSI("Twb", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Tdp = HumidAir::HAPropsSI("Tdp", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Vha = HumidAir::HAPropsSI("Vha", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Vda = HumidAir::HAPropsSI("Vda", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Hda = HumidAir::HAPropsSI("Hda", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Hha = HumidAir::HAPropsSI("Hha", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Sda = HumidAir::HAPropsSI("Sda", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Sha = HumidAir::HAPropsSI("Sha", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Y   = HumidAir::HAPropsSI("Y", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Pw  = HumidAir::HAPropsSI("P_w", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float RH  = HumidAir::HAPropsSI("RH", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float W   = HumidAir::HAPropsSI("W", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Z   = HumidAir::HAPropsSI("Z", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float SHd = HumidAir::HAPropsSI("cp", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float SHh = HumidAir::HAPropsSI("Cha", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float TC  = HumidAir::HAPropsSI("K", "P", pFloat, var1Name, var1Float, var2Name, var2Float);
    float Vis = HumidAir::HAPropsSI("M", "P", pFloat, var1Name, var1Float, var2Name, var2Float);

So var1Name and var2Name are the 2 parameters that the user selects. Can be anything from the available input list. Retrieving all the available possible outputs takes about 10 seconds.

**Comment by ibell** [comment]
Hmm, yup not surprising.  If you have for instance wet bulb and humidity
ratio as inputs, it will be very(!) slow.  What you should do is to first
convert your inputs to T,P,W, and then do all subsequent calculations with
those inputs.  That will be as fast as you can get.

I would be curious if you could do some speed testing though, to perhaps
demonstrate what are particularly slow inputs.  Not guaranteeing we can do
anything about it though....

**Comment by babaksamareh** [comment]
hmmm sounds interesting. I have to do speed check anyways, I'll report back.
Are you still loyal to your Nokia? If you have an i device I can add you as a test flight user and you can play with this new app.

**Comment by babaksamareh** [comment]
Ok problem solved. I find T,P,W first and the rest is fast. It gives me everything in less than a sec.

Thanks :)
