### ISSUE TITLE
Add comprehensive docs for REFPROP interface

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#759]

**Comment by ibell** [comment]
@mayersre Do you have any ideas for things we might want to add to the docs currently at http://www.coolprop.dreamhosters.com/binaries/sphinx/coolprop/REFPROP.html#refprop ?  I think you are the most experienced CoolProp+REFPROP user

**Comment by mayersre** [comment]
sorry for the delay, but I move my home office currently ...

I like the documents from the link above and I like the alternative REFPROP path, it will help a lot when
experimenting with different binary pairs or using modern blends from dupont in calculation as it allows the usage of the duprex hmx.bnc file . I like the documentation on the low level interface even better ... I will try it in winter with my diagrams and some new nomographs and look what performance improvement can be gained.

**Comment by ibell** [comment]
Ok, glad you like them.  If you have any ideas for things to put there, let
me know.

**Comment by mayersre** [comment]
I run TestCoolprop.py code below

import CoolProp
print(CoolProp.__version__)
print(CoolProp.__gitrevision__)

import json, CoolProp.CoolProp as CP

jj = json.loads(CP.get_config_as_json_string())
jj['ALTERNATIVE_REFPROP_PATH'] = '/home/mayers/git/kformaug/extern/rp_nist/'
jj = CP.set_config_as_json_string(json.dumps(jj))
     
ref='REFPROP::R449A.MIX'
press=101325
bub_nist=CP.PropsSI('T','P',press,'Q',0,ref)-273.15
dew_nist=CP.PropsSI('T','P',press,'Q',1,ref)-273.15
print('{} Bubble point : {} Dew point {} at {} Pa.'.format(ref,bub_nist,dew_nist,press))

Output is fine 
5.1.1dev
ccc012c31a7c1505f5399acfa5ab85f24f41fd8b
REFPROP::R449A.MIX Bubble point : -44.04775623435387 Dew point -38.05712164462065 at 101325 Pa.
or
5.1.2dev
851c961cd6e584c452489fd3ae668e6f03ef1da6
REFPROP::R449A.MIX Bubble point : -44.04775623435387 Dew point -38.05712164462065 at 101325 Pa.


But it does not take refprop from '/home/mayers/git/kformaug/extern/rp_nist/'

if I strace it, the output does not even contain 'nist'
strace -o x.out python TestCoolprop.py
grep nist x.out > nothing

**Comment by jowr** [comment]
Thanks for the comment. I am not sure how the path is handled on Linux, I think we only support Windows for now...

@mayersre , I edited your post and added fenced code blocks to make the source code easier to read.

**Comment by ibell** [comment]
Actually, I wrote the docs, but they are currently ahead of the code.  I'll
fix the code soon I hope.

**Comment by ibell** [comment]
Can you try again?  I updated the code.  If it works, we can close the issue.

**Comment by mayersre** [comment]
That works nicely now on Linux. I cloned the repo, built coolprop by instruction from the website, installed it into my virtualenv (no sudo neccessary), re-ran the commands for refprop access from django --> success. 
Coolprop Version :  5.1.2dev
Gitrevision      :  08e27612ea002350ae6b9b73991ff0afff0b2ae5

Switch ALTERNATIVE_REFPROP_PATH  from rp_nist to rp_honeywell to rp_dupont --> success

Thanks :+1:

**Comment by ibell** [comment]
Have you tried to use the path to the HMX.BNC file?  Does that work for you?  I think it should.  For now, I am going to close this issue...  Any further problems, please re-open.  Any other recommendations for the docs, I'm game as well.
