### ISSUE TITLE
Temperature with `HmassP_INPUTS` with twophase fluid and tabular

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#762]
This input pair works to compute temperature with HEOS backend, but not with the tabular ones:
```julia
import CoolProp

fluid = "R245fa"
input1 = 4e5 # Hmass
input2 = 8e5 # P
output = CoolProp.get_param_index("T")
input_pair = CoolProp.get_input_pair_index("HmassP_INPUTS")

handle = CoolProp.AbstractState_factory("HEOS", fluid)
CoolProp.AbstractState_update(handle,input_pair,input1,input2)
println("HEOS    gives: ", CoolProp.AbstractState_keyed_output(handle,output))
CoolProp.AbstractState_free(handle)

handle = CoolProp.AbstractState_factory("TTSE&HEOS", fluid)
CoolProp.AbstractState_update(handle,input_pair,input1,input2)
println("TTSE    gives: ", CoolProp.AbstractState_keyed_output(handle,output))
CoolProp.AbstractState_free(handle)
```
Output:
```julia
HEOS    gives: 353.7035584315394
ERROR: CoolProp: no correct state has been set with AbstractState_update
 in AbstractState_keyed_output
```

Asking for other properties with the same update works (tested with density and entropy).
I think it may be related to the fact that the searched point is in two state area, so with a constant temperature.

**Comment by Astrinus** [comment]
Which version are you using? With the latest stable (5.1.1) for me works well either with BICUBIC and TTSE.

    >> tmp = CoolProp.AbstractState.factory('BICUBIC&HEOS','R245fa');
    >> tmp.update(CoolProp.HmassP_INPUTS,4e5,8e5)
    >> tmp.T()
        ans = 353.703558431357
    >> tmp = CoolProp.AbstractState.factory('TTSE&HEOS','R245fa');
    >> tmp.update(CoolProp.HmassP_INPUTS,4e5,8e5)
    >> tmp.T()
        ans = 353.703558431357

**Comment by JonWel** [comment]
I used a build from latest GitHub sources.
But it may be that the tables are outdated, I go build them again.

**Comment by JonWel** [comment]
Generating new tables did not help.
I go make a new source build.

**Comment by ibell** [comment]
I wonder if there is something funny in the high-level wrapper of the low-level interface.  Maybe its a bug.

**Comment by ibell** [comment]
Given #777, I bet this is related to something curious on your side.  Anyone else on linux that can confirm this behavior? @jowr?

**Comment by jowr** [comment]
I am out of office until September and have only limited internet access, feel free to remind me again later. 

My immediate guess would be to make sure that there is no broken library file lurking anywhere in the search path.

**Comment by JonWel** [comment]
I was experiencing this firstly on Windows XP (My testing code for `ExternalMedia` set state with p and h and calculate most of the outputs but was stuck on temperature).
I did test this code again with the latest source code on Linux and still have the same error.
If I remembered well, the same code searching for temperature in monophasic area worked.

**Comment by ibell** [comment]
Should be fixed now - tested on linux in C++

**Comment by JonWel** [comment]
:thumbsup:
