### ISSUE TITLE
Add and implement all phase functions to tabular backends

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#763]
Needed for `ExternalMedia`.

**Comment by JonWel** [comment]
I think adding the line `phases calc_phase(void){return _phase;};` to the TabularBackends.h should solve it.
Is there an ideal place to add this? (I was tinking of line 775, but an other one may be good too)?

Others similar functions may be added this way:
```C++
phases calc_phase(void){return _phase;};
void calc_specify_phase(phases phase){ specify_phase(phase); }
void calc_unspecify_phase(){ unspecify_phase(); }
```

Should I add them?

**Comment by ibell** [comment]
Currently phase is not used/implemented for tabular backends, is it strictly needed?

I'm unavailable until Tuesday of next week, you are on your own until them.  I think I should be able to merge pull requests though.

**Comment by JonWel** [comment]
It's used to know when to apply `twophase_derivsmoothing_xend` or `rho_smoothing_xend`.

(adding this line made the code run but the answer is always `7`, thus never two phases `6`).

**Comment by ibell** [comment]
Maybe there is a bug in the phase determination for tabular backends
(probably there is actually!).  Can you come up with a minimal example that
demonstrates the problem?  It would be good if you could check all the
domains in the plot in
http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function

**Comment by JonWel** [comment]
I still don't have a minimal example because I'm experiencing a problem when I'm trying to use tables with PT inputs in Julia https://github.com/CoolProp/CoolProp/issues/777 .

**Comment by JonWel** [comment]
Trying to reproduce the plot from http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function only gives `7.0` (one phase) on the tested domain (T = 280 to 700, P = 1e4 to 3e7, giving a matrix of 10000x10000)

**Comment by ibell** [comment]
Yeah, that isn't all that surprising.  I haven't implemented the phase
functions yet, and I will do so in the next week hopefully.

**Comment by JonWel** [comment]
Will the `specify_phase` function be added to the tabular backends when the phase will be implemented?
