### ISSUE TITLE
Pressure changes do not effect T_freeze, C, D and other properties in PropsSI when using INCOMP

### ISSUE THREAD

**Issue by hasanacul** [CoolProp/CoolProp#766]
Dear friends,
Could you help me that when I change (P) pressure it does not effect T_freeze, C, D and other properties in PropsSI when using INCOMP brine fluids. Herewith attached please find print screen of the code.
Thanks for your help.
BR
Hasan
![adsiz](https://cloud.githubusercontent.com/assets/5855156/9063888/759d8082-3ad2-11e5-8f3a-4d2c508049df.png)

**Comment by ibell** [comment]
As you should not expect them to!  That is the whole point of the
incompressible fluids.  Their T_melt, c_p and density are functions only of
temperature, and not of pressure.  Real fluids obviously do have a pressure
dependence, but the incompressible fluid treatment does not.
