### ISSUE TITLE
Improve docs for second partial derivatives

### ISSUE THREAD

**Issue by enter802** [CoolProp/CoolProp#769]
Hi, is it possible to get the partial derivatives d(C)/d(P) and d(C)/d(Hmass) from CoolProp? 

i tried the following commands but i end up getting errors:

1. CoolProp.PropsSI('d(C)/d(P)|Hmass','P',1.45e+06,'Hmass',4.5e+05,'R245fa')

2. CoolProp.PropsSI('d(C)/d(Hmass)|P','P',1.45e+06,'Hmass',4.5e+05,'R245fa')

error for both the commands: 

"Warning: input to get_dT_drho[Cpmass] is invalid 
Error using CoolPropMATLAB_wrap
Failure in function PropsSI.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] =
  CoolPropMATLAB_wrap(236,'_wrap_PropsSI',varargin{:});"

so what should be my inputs?

Thanks in advance!

**Comment by thorade** [comment]
That would be a second derivative, as cp is a derivative already. Coolprop knows how to calculate second derivatives, but I belive you currently have to rewrite the derivative of cp manually. A description how to do that is given in Table 6 of this paper:
http://publications.iass-potsdam.de/pubman/item/escidoc:247373:4/component/escidoc:306833/247373.pdf

**Comment by ibell** [comment]
You would want something like: 
```
"d(d(Hmass)/d(T)|P)/d(Hmass)|P"
```
I'll add some docs for the second partial derivative.  Your c_p is the inner part: ``d(Hmass)/d(T)|P``

**Comment by enter802** [comment]
Thanks a lot!
