### ISSUE TITLE
HAPropsSI Limits

### ISSUE THREAD

**Issue by babaksamareh** [CoolProp/CoolProp#771]
Is there any document on what are the physical limits for this function? For example, what is the min and max temp or pressure.

Cheers

**Comment by jowr** [comment]
I remember making a table once, but I cannot find it anymore. You might be able to find something in the docs for version 4 - it was some time ago that I made the table and I think we were still working on v4 at that time.

**Comment by babaksamareh** [comment]
Just in case:

Pressure: 0.01 ≤ p ≤ 10,000 kPa
Temperature: –143.15 ≤ t ≤ 350 °C
Humidity ratio: 0 ≤ W ≤ 10 kgw/kga
Relative humidity: 0 ≤ ϕ ≤ 1 (decimal ratio)
Dew-point temperature: –143.15 ≤ t ≤ 350 °C
Wet-bulb temperature: –143.15 ≤ t ≤ 350 °C
