### ISSUE TITLE
Acentric factor of air

### ISSUE THREAD

**Issue by phileasfoggy** [CoolProp/CoolProp#772]
Hello,

how is the acentric factor of air calculated? The output of  PropsSI('acentric', 'air') is 0.0816749632704
I wonder because the acentric factors of oxygen and nitrogen are 0.0222 and 0.037200000000000004.

**Comment by ibell** [comment]
Hmm that might be a bug.  It is based on the saturation pressure, and I
agree that this value doesn't seem correct to me.

**Comment by phileasfoggy** [comment]
OK, thanks so far.
What about the Phase? CoolProp.CoolProp.PhaseSI('P',101325,'T',300,'air') returns
'supercritical_gas' shouldn't be 'gas' the correct Phase?

**Comment by ibell** [comment]
According to our definition of phase, gas is only for temperatures below
the critical temperature.  See for reference
http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function

**Comment by ibell** [comment]
It's a bug, REFPROP says it should be 0.0335.

**Comment by ibell** [comment]
Actually, I am not so sure about this after all.  Air is a mixture, and the acentric factor is only defined for pure fluids.

**Comment by ibell** [comment]
Perhaps we should remove it entirely.

**Comment by phileasfoggy** [comment]
Maybe. I used CoolProp to get the Density of air. I compared the values to the results of cubic real-gas-equations. To use the cubic real-gas-equations I had to define critical properties and an acentric factor.
I calculated the values by using the mole fraction Xi.

**Comment by ibell** [comment]
Ok, the "fix" for this problem is going to be to remove the acentric factor and make it equal to infinity.  I couldn't come to an agreement about what the acentric factor for air should be, so the safest answer is: not defined.
