### ISSUE TITLE
Missing files in LabVIEW wrapper folder or documentation needed

### ISSUE THREAD

**Issue by bachc** [CoolProp/CoolProp#773]
https://github.com/CoolProp/CoolProp/tree/master/wrappers/Labview
states:

To Install
----------
1. Copy the files CoolProp.vi, Coolprop.llb and CoolProp.dll from this folder to somewhere you want
2. ...

Unfortunately the CoolProp.vi, Coolprop.llb and CoolProp.dll files are not in the above folder and compiling the dll seems to be a bit tedious for "normal" users.

**Comment by ibell** [comment]
Actually this is where you should look: http://www.coolprop.org/coolprop/wrappers/Labview/index.html#labview

Those files you reference are actually from version 4.2.x

**Comment by bachc** [comment]
Perfect, worked for me. Thanks! 

Maybe change the to install part on https://github.com/CoolProp/CoolProp/tree/master/wrappers/Labview to the below. Would do it myself, but don't have writing rights to the site. Thanks again!

To Install
----------
1. Copy the files CoolProp.vi, Coolprop.llb and CoolProp.dll from this folder to somewhere you want. You can find an up-to-date version of these two files here: http://www.coolprop.org/coolprop/wrappers/Labview/index.html#labview
2. ...

**Comment by ibell** [comment]
Or we just delete this file entirely.  The idea is that that these are just upstream files that are consumed to generate the website information.

**Comment by bachc** [comment]
Might be an idea. Or just replace the content of the rst-file by:

For instructions of using CoolProp in LabVIEW see here: http://www.coolprop.org/coolprop/wrappers/Labview/index.html#labview

That way you can keep the files that need to be versioned in git and reduce the documentation overhead.
