### ISSUE TITLE
Implement new EOS for R-245fa

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#774]
See paper 792 - *A NEW EQUATION OF STATE FOR 1,1,1,3,3-PENTAFLUOROPROPANE (R-245fa)* at ICR2015: http://www.icr2015.org/program/day-3.html

**Comment by jowr** [comment]
Or are the coefficients the same as in http://scitation.aip.org/content/aip/journal/jpcrd/44/1/10.1063/1.4913493 (which is the one that is implemented)?

**Comment by ibell** [comment]
Pretty sure that is just the same as in the referenced paper.  If you can
get the paper we can confirm.
