### ISSUE TITLE
Seawater

### ISSUE THREAD

**Issue by paarfi** [CoolProp/CoolProp#775]
Would it be possible to add seawater to the incompressibles? It looks like there is a decent reference here:
http://web.mit.edu/seawater/

**Comment by jowr** [comment]
Sure, I'll have a look this weekend. Thanks for the reference.

**Comment by thorade** [comment]
Also see the IAPWS guidelines on seawater:
http://iapws.org/relguide/Seawater.html

**Comment by jowr** [comment]
OK, looks like we should include both and give them proper names, see #85 . Thanks for the additional information. I haven't had the time to do things this weekend, but it does not seem to be overly complicated since we have the framework for the data fitting.

**Comment by jowr** [comment]
One of the problems I have at the moment is the enthalpy of mixing. The incompressibles were designed to treat fluids with different compositions as different fluids. This neglects the possibility of phase change as well as compositional changes. I could implement seawater, but I have to remove the ![dh/dx_T](http://www.sciweavers.org/tex2img.php?eq=%5Cleft%28%20%5Cfrac%7Bdh%7D%7Bdx%7D%20%5Cright%29_T&bc=White&fc=Black&im=jpg&fs=12&ff=cmbright&edit=0) part and I do not think that is a good idea. 

@paarfi : Would a formulation without the enthalpy of mixing be sufficient for you?

**Comment by paarfi** [comment]
@jowr: That would be fine with me. Thanks.

**Comment by jowr** [comment]
@paarfi : Is this what you had in mind? 
![mitsw_fitreport_page_1](https://cloud.githubusercontent.com/assets/769593/9682787/30f31726-530a-11e5-9de8-b735a5fe10d0.jpg)

**Comment by paarfi** [comment]
@jowr : yes. that looks excellent.

**Comment by jowr** [comment]
Tomorrow's nightly builds should include `INCOMP::MITSW` (Python might lag a bit due to #810)

**Comment by jowr** [comment]
@paarfi : Have you tried the fluid? Does it work as expected?

**Comment by paarfi** [comment]
@jowr : Sorry, I've been out. I'll give it a try next week. Thanks for putting that in.

**Comment by paarfi** [comment]
@jowr : Hmm. Something seems wrong. If I run this:
double ds = CoolProp.PropsSI("D", "T", 275.15, "P", 101325, "INCOMP::MITSW[0.035]");
(using 3.5% typical seawater) I get 995.5 kg/m3.
But the table on page 3 of this pdf linked from teh MIT site:
http://web.mit.edu/seawater/Seawater_Property_Tables.pdf
and this online calculator from the iapws site that @thorade linked
http://thermodynamik.hszg.de/fpc/index.php
both say it should be around 1027 kg/m3 for that case.

**Comment by jowr** [comment]
OK, but it fits with the graph I posted earlier... I think there is a factor of 10 missing in the concentration parameters... I'll try to fix it.

**Comment by jowr** [comment]
... and shouldn't density decrease with temperature?

**Comment by jowr** [comment]
@paarfi : Is this more like it? 
![mitsw_fitreport_page_1](https://cloud.githubusercontent.com/assets/769593/9876592/8a04b17a-5bb7-11e5-8196-9e549244690d.jpg)

**Comment by paarfi** [comment]
@jowr : yes. Those graphs look much better vs the tables linked from the MIT site. Thanks for fixing it.

**Comment by jowr** [comment]
Nice, if the graphs are OK, I expect the binaries to behave well too. Please get the latest files from  http://www.coolprop.dreamhosters.com/binaries/ in approximately 1 hour and test them. Feel free to reopen this issue in case you encounter any problems.

**Comment by paarfi** [comment]
@jowr : The dll looks good as well. Thanks again.

**Comment by jowr** [comment]
great, welcome!
