### ISSUE TITLE
Pirobloc Basic

### ISSUE THREAD

**Issue by jzarzu** [CoolProp/CoolProp#790]
Hi everyone!
Im trying to model an evaporator in MATLAB using r245fa as working fluid and Pirobloc basic as HTF. My problem is that Pirobloc Basic is not included in the CoolProp library. Hereunder is the datasheet of this fluid. Is it possible to add it to the library?
http://www.fluidotermico.com/downloads/pdf/es/Hoja-Tecnica-Pirobloc-HTF-BASIC.pdf
Thanks in advance!

**Comment by jzarzu** [comment]
I have also tried to use Therminol 66 as HTF but I have the same problem. Maybe I am doing something wrong because I think Therminol 66 is already in the CoolProp library... Datasheet of Therminol 66:
http://twt.mpei.ac.ru/TTHB/HEDH/HTF-66.PDF

**Comment by ibell** [comment]
Can you provide a code sample that doesn't work for you?  Have you read the
docs here: www.coolprop.org/fluid_properties/Incompressibles.html ?

**Comment by jzarzu** [comment]
A simple sample is this one:
PropsSI('C','T',385.25,'P',2e5,'T66')

And this is what MATLAB yields:

Warning: Initialize failed for backend: "?", fluid: "T66" fractions "[ 1.0000000000 ]"; error: key [T66] was not found in
string_to_index_map in JSONFluidLibrary 
Error using CoolPropMATLAB_wrap
Failure in function PropsSI.

Error in PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(207,'_wrap_PropsSI',varargin{:});

**Comment by ibell** [comment]
Should be 'INCOMP::T66' - the 'T66' only works in v4.x of CoolProp

See
http://www.coolprop.org/fluid_properties/Incompressibles.html#pure-fluid-examples

**Comment by jzarzu** [comment]
THANKS! 
So for all incompressible fluids it must be 'INCOMP::nameofthefluid'
To add the Pirobloc Basic do you need more information or the datasheet I have attached is fine?

**Comment by ibell** [comment]
That should be fine, but our incompressible guy is on vacation, so it might
be a few weeks.

**Comment by ibell** [comment]
@jowr - this one is for you :)

**Comment by jowr** [comment]
@jzarzu: Could you provide us with some tabulated data? There are only graphs and the information on viscosity is not that comprehensive? Would you mind conatcting the company and asking for additional information? They might also be interested in having their fluid in CoolProp...

**Comment by jzarzu** [comment]
@jowr Done. I am waiting for their answer. I will give you more information asap.

**Comment by jowr** [comment]
Any news here?

**Comment by jzarzu** [comment]
Not yet... I have tried to contact the company several times. I guess they will be back from holidays soon!

**Comment by jzarzu** [comment]
Good news! I have received the datasheet of the fluid. It is a pdf file...how can I send it to you @jowr ?

**Comment by jowr** [comment]
You can mail it to me at jowr@ipu.dk .

**Comment by jowr** [comment]
Does that look correct?
![pbb_fitreport_page_1](https://cloud.githubusercontent.com/assets/769593/9852103/ac53ac10-5afc-11e5-94d1-1c7df13ad176.jpg)

**Comment by jzarzu** [comment]
Yes it looks good! now in the latest version of CoolProp this fluid will be included, is that right?
Thanks!

**Comment by jowr** [comment]
Yes, the nightly builds get updated at around 13:00 Central European Time, visit http://sourceforge.net/projects/coolprop/files/CoolProp/nightly/ in about 21 hours and you should get your fluid.

**Comment by jowr** [comment]
Please report back if it works and close the issue.

**Comment by jowr** [comment]
Sorry, I forgot to merge my changes to the master branch. You should be able to get an updated library with your fluid from http://www.coolprop.dreamhosters.com/binaries/ in approximately 1 hour.

**Comment by jzarzu** [comment]
Ok thanks! I will check it this afternoon and let you know if it works!

**Comment by jzarzu** [comment]
It works perfectly! Thanks to both of you @ibell and @jowr 
Closing the issue

**Comment by adex987** [comment]
I just started using coolprop, MATLAB Wrapper. I have difficulty, how to define bubble and dew properties.

For saturated liquid: I defined "CoolProp.PropsSI('D', 'P', p, 'Q', 0, 'Water')"- this works but for buble, I defined: CoolProp.PropsSI('dl', 'P', p, 'Q', 0, 'Water'), this one didn't works.

How I can define for dew and bubble properties? saturated liquid/ vapor properties are different from bubble/dew.

Thank you,

**Comment by aditya-pillai009** [comment]
I had a similar problem with Therminol 66 and this thread helped. I wasn't adding 'INCOMP::' before the fluid name. I also use a fluid from 'Brines and Solutions' category (Ethylene Glycol). I get a value error. I assume I'm making a similar mistake in naming the fluid. Can I please get help in figuring out what's wrong?
Using Python 3.7 on Windows10.

Code:
fluid_hot = 'INCOMP::T66' #T66 = Therminol66
fluid_cold = 'MEG-30%' #MEG-30% = 30% Ethylene Glycol (C2H6O2)

Th_i = 133+273 #Hot fluid inlet temp, K
Tc_i = 10+273 #Cold fluid inlet temp, K
m_h = 5 #Hot fluid mass flow rate, kg/s
m_c = 3 #Cold fluid mass flow rate, kg/s

Ph_i = 206 #Hot fluid inlet press in kPa

Cp_h = CP.PropsSI('C','T',Th_i,'P',Ph_i,fluid_cold)
print(Cp_h)

Error:
ValueError: Initialize failed for backend: "?", fluid: "MEG" fractions "[ 0.3000000000 ]"; error: key [MEG] was not found in string_to_index_map in JSONFluidLibrary : PropsSI("C","T",283,"P",206,"MEG-30%")

**Comment by ibell** [comment]
For some reason I cannot see this issue on github.  Any idea why?

The resolution is to add INCOMP:: to the beginning of the name.  The string
to the left of the :: indicates which backend is to be used inside
CoolProp.  The default is the multiparameter EOS for fluids, and doesn't
make sense for the incompressibles.

>

**Comment by aditya-pillai009** [comment]
I realised my mistake and deleted the comment. Thank you for your time and help.
