### ISSUE TITLE
Interfacing wrapper in Maple (OSX)

### ISSUE THREAD

**Issue by MahsaSadegh** [CoolProp/CoolProp#794]
For interfacing the wrapper, I used 

"PropsSI := define_external('PropsSI', LIB = "Users\\mahsa\\Downloads\\libCoolProp.dylib", 'Output'::string, 'In1'::string, 'Val1'::(float[8]), 'In2'::string, 'Val2'::(float[8]), 'Fluid'::string, RETURN::(float[8]))"

but it shows the error -

"Error, external linking: error loading external library Users\mahsa\Downloads\libCoolProp.dylib: dlopen(Users\mahsa\Downloads\libCoolProp.dylib, 129): image not found"

i downloaded the wrapper from "http://sourceforge.net/projects/coolprop/files/CoolProp/5.1.1/shared_library/Darwin/32bit/"

So please help as in how should I integrate the wrapper or what mistake am i making here. 

Thanks!

**Comment by enter802** [comment]
Command:

"PropsSI := define_external('PropsSI', LIB = "//Users//mahsa//Downloads//libCoolProp.dylib", 'Output'::string, 'In1'::string, 'Val1'::(float[8]), 'In2'::string, 'Val2'::(float[8]), 'Fluid'::string, RETURN::(float[8]))"

this should do the job

**Comment by ibell** [comment]
Is your maple 32-bit or 64-bit?  I think it is 64-bit, so you need the 64-bit version of the dylib.

**Comment by ibell** [comment]
Any update?

**Comment by MahsaSadegh** [comment]
It works pretty well now.
Thanks for your help.
Regards

**Comment by ibell** [comment]
Good to hear!  Thanks for the update.
