### ISSUE TITLE
Failure in compiling CoolPropLib.lib for Modelica

### ISSUE THREAD

**Issue by OhPeach** [CoolProp/CoolProp#803]
The batch file "CoolProp/wrappers/Modelica/BuildLIB-VS20xx.bat" cannot work. It seems the file has not been updated for a year, and the directory for *.cpp and *.h files here cannot match the existing files now. Could anyone help? Anyone using CoolProp in Modelica tools?

**Comment by jowr** [comment]
Correct, please have a look at ExternalMedia which integrates with CoolProp. The stable version still uses CoolProp v.4, but we are working on supporting v.5. The whole directory should be deleted. Note that the documentation for Modelica on http://www.coolprop.org/ links to https://github.com/modelica/ExternalMedia

**Comment by OhPeach** [comment]
Thanks a lot.
