### ISSUE TITLE
Coolprop function like Refprop Excel Fluidstring Function for mixtures

### ISSUE THREAD

**Issue by TimHarvey2** [CoolProp/CoolProp#805]
A Mixture string function would be useful for CoolProp functions in excel and LibreOffice Spreadsheets and may be in some other Wappers (not sure of how some of them handle data). example pictures of Refprop Fluidstring and Propose CoolProp Mixture string enclosed.
![refprop fluidstring](https://cloud.githubusercontent.com/assets/11156125/9628911/1fa92e3c-51b2-11e5-8c77-84861a3bcc0d.JPG)
![coolprop mixturestring](https://cloud.githubusercontent.com/assets/11156125/9628912/2684fbd2-51b2-11e5-9c11-51e4cf565d96.JPG)

**Comment by ibell** [comment]
Good idea, I'll implement it in C++ and make it available in Excel.

**Comment by mayersre** [comment]
I use this in Python :  

# -*- coding: utf-8 -*-
#
# Gemische für Diagramme und Dampftafeln
#
from CoolProp.CoolProp import PropsSI
#

def refprop_mixname(reflist,masslist):
    '''
    Creates a refprop mixture string from names and mass fractions
    e.G. 
    reflist   = list of refrigerants in a mixture
    masslist  = massfraction in kg/kg
    '''
    # Calculate total
    molelist=[]
    molefrac=[]
    namelist=[]
    denominator=0
    # Get moles and calculate denominator
    for index in range(len(reflist)):
        m=PropsSI("M",reflist[index])
        molelist.append(m)
        namelist.append(reflist[index].split(':')[-1])
        denominator+=(masslist[index]/molelist[index])
    # Denominator is calculated, now molefractions
    for index in range(len(reflist)):
        #
        mol=(masslist[index]/molelist[index])/denominator
        molefrac.append(mol)       
    # now create string from data
    refpropstring='REFPROP::'
    add_ampersand=False
    #
    for index in range(len(namelist)):
        if add_ampersand :
            refpropstring+='&'+namelist[index]+'[%0.16f]'%molefrac[index]
        else :
            refpropstring+=namelist[index]+'[%0.16f]'%molefrac[index]
            add_ampersand=True
    #
    return refpropstring

if __name__=='__main__':
    #
    print(refprop_mixname(['REFPROP::R134a','REFPROP::R1234ze'],[0.42,0.58]))
    # R404A
    print(refprop_mixname(['R125','R143a','R134a'],[0.44,0.52,0.04]))
    #
    print('R-448A : ',refprop_mixname(['REFPROP::R32','REFPROP::R125','REFPROP::R1234yf','REFPROP::R134a','REFPROP::R1234ze'],[26.0,26.0,20.0,21.0,7.0]))
    #
    print('R-449A',refprop_mixname(['REFPROP::R32','REFPROP::R125','REFPROP::R134a','REFPROP::R1234yf'],[24.3,24.7,25.7,25.3]))

**Comment by ibell** [comment]
It's called MixtureString in the VBA module now...

**Comment by TimHarvey2** [comment]
Ian I get an error in macro I downloaded latest 64 bit DLL and XLAm from http://www.coolprop.dreamhosters.com/binaries/ and get an error on i being undefined in function
![function error](https://cloud.githubusercontent.com/assets/11156125/10708155/f3951a96-7a41-11e5-8733-a144938fcbc8.jpg)

**Comment by ibell** [comment]
I pushed up the new version after my first attempt.  I thought I had fixed
that bug too, but apparently not.  I pushed up a new version that should
work properly.  I've been doing a lot of crashing of Excel which isn't too
nice.
