### ISSUE TITLE
matlab installation

### ISSUE THREAD

**Issue by gpsimms** [CoolProp/CoolProp#806]
I'm sorry to be a bother - it seems like everyone else is getting things up and running just fine. But I am not for some reason. It seems like everything is in the proper directory, here is a screenshot:

![coolprop_help](https://cloud.githubusercontent.com/assets/14096126/9637786/bf6ad142-5170-11e5-8f04-cefce82f2f7c.png)

Thanks for the help, sorry again.

simms

**Comment by ibell** [comment]
Hi simms,

Looks like you are trying to use the v4 interface even though you have the v5 interface installed.  Have you tried 
``CoolProp.PropsSI('T','P',101325,'Q',0,'Water')`` 

for instance as is recommended in the docs: http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#pre-compiled-binaries?

Also, check out the MATLAB examples in the online documentation: http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#example-code

Hope that helps.

**Comment by gpsimms** [comment]
Hi Ian,

Thanks for writing back. I don't think that is the issue, although I was calling the function incorrectly in the above screenshot, I had tried both the old and new call, and just took the screenshot of the wrong attempt. 

For example, the "test.m" script that came with the download shows the same error.

![image](https://cloud.githubusercontent.com/assets/14096126/9661206/a9639138-5227-11e5-986a-bfe5e82eb7ba.png)

One thing I noticed that seems definitely-not-right is the file I am supposed to download, 'coolpropsetup.m' is empty.  The entire content of the setup file are:

% This is the setup script for CoolProp.

Thanks again for the help. 

simms

**Comment by ibell** [comment]
I think the problem is that the structure of the +CoolProp is incorrect.  Please see the file layout here: http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#pre-compiled-binaries  .  You should not have the top level files in the +CoolProp folder as well.  Inside the +CoolProp directory should be all the .m files that come packaged in the +CoolProp folder in the .7z file.

The setup script is usually empty, so that is not a concern.

**Comment by gpsimms** [comment]
yup. I'm an idiot. We're good now.  Thanks for spending a minute to set me straight, Ian.
