### ISSUE TITLE
Python builds crash on Windows

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#810]
Any idea what broke the Python builds on Windows? It looks like commit https://github.com/CoolProp/CoolProp/commit/50ec26f8f38a2262a395e9ca0ceafb323fd11e61 broke the Python wrappers.

**Comment by jowr** [comment]
... and I still do not understand why the 64bit builds take 3-4 times longer than the 32bit builds (for Python on Linux)

**Comment by ibell** [comment]
a) That commit should have FIXED the problem.  Are you still getting build failures as a result of it?  Interesting.  Can you show me the error?

b) Dunno - are they using the static library such that we get incremental builds?

**Comment by jowr** [comment]
a) Check the buildbot logs for Python on Windows.
b) Let us not worry now, but I would like to keep it in mind.

**Comment by ibell** [comment]
Interestingly, it builds just fine for me.  Maybe it is something funny
with your setup.  A clean and a build didn't fix it unfortunately.

**Comment by ibell** [comment]
Bug in cython.

**Comment by ibell** [comment]
Ok, now they hang on linux but work fine on windows.  I don't get it.  I just checked and my linux builds work fine.  Can you try a local build on linux?

**Comment by jowr** [comment]
Yep, I'll have a look, but the bots seem to build fine. I removed all temporary files on the linux slaves, let's see if that changed anything.

**Comment by jowr** [comment]
I guess this one is solved for now.

**Comment by ibell** [comment]
OK good to hear.
