### ISSUE TITLE
Add ability to retrieve mass fractions

### ISSUE THREAD

**Issue by romarro** [CoolProp/CoolProp#812]
First of all can I use AbstractState for Humid Air?
I have tried in python using AbstractState("HEOS","Air&Water") but I keep getting an error
Can you please help me with some examples.
An other thing is that AbstractState has only get_molar_fractions without having molar masses of the mixture constituents how can I get the mass fraction or volume fraction?

**Comment by ibell** [comment]
a) You can construct a mixture using the constituents of humid air
(Water&Nitrogen&Argon&Oxygen), but your best bet for humid air is to use
HAPropsSI function:
http://www.coolprop.org/fluid_properties/HumidAir.html#sample-hapropssi-code
.  Are you aware of that function?  The HAPropsSI will be faster and more
reliable than using the full mixture model.  The algorithms for mixtures
with water are not very robust.
b) You can use the mixture of Nitrogen and Water in an AbstractState, but
not Air and Water.  Air is not a pure fluid, it is a mixture.
c) You raise a good point on this front.  The get_mass_fractions function
is not implemented for mixtures.  Is this something you are interested in?

**Comment by romarro** [comment]
Thank. 
I did know about the HAPropSI but I tried with AbstractClass becauce it seems more object oriented. I'm working in heat exchanger industry and my usually fluids are air water/ glycol and lubricant oils. I'm intrested in a function to get the mass fractions specially for water/glycol mxture. 
By the way do  plan to implement also the CO2, in some cases where I have to design EGR I need it in order to model the exchaust gases in the EGR.

**Comment by ibell** [comment]
@jowr - what do you think about adding the ability to get mass fractions through the Abstract State?

**Comment by jowr** [comment]
Hm that opens the door for many pitfalls. In which way should we calculate the mass fraction? I am not sure it makes sense to have it in the abstract state. @romarro , could you tell us more about the way you would use such a function?

**Comment by ibell** [comment]
I think the better option is a function called something like ``mole_fraction_to_mass_fraction`` in the ``AbstractState`` that converts a vector of mole fractions to a vector of mass fractions.  How does that sound to you?

**Comment by romarro** [comment]
sorry for not answering you sooner but the mole_fraction_to_mass_fraction sounds ok.

**Comment by ibell** [comment]
Ok good, I'll go ahead and do that then.

**Comment by ibell** [comment]
@jowr I had a change of heart and now return the mass fractions calculated from the mole fractions.  What do you think about doing the same for incompressibles?  For now, it's just going to throw an exception for incompressibles.

The use case is pretty clear.  See for instance:
``` python
>>> import CoolProp
>>> AS = CoolProp.AbstractState('HEOS','R410A.mix')
>>> AS.get_mass_fractions()
[0.4999999999999999, 0.5000000000000002]
>>> AS.get_mole_fractions()
[0.6976146993758631, 0.30238530062413804]
```

**Comment by jowr** [comment]
Good idea, but are you referring to the volume-to-mass conversion? I haven't come across any incompressibles with mole fractions yet.

**Comment by ibell** [comment]
I'm not sure the right way to handle this with incompressibles.  But what I
can say is that the get_mass_fractions doesn't work at all for them, nor
does the mole version

**Comment by ibell** [comment]
"them" in this context being the incompressibles.  You'll have to think
what you want to do about that.
