### ISSUE TITLE
Poor compilation performance on the 64bit Linux slave for Python

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#813]
The machine building the 64bit Python binaries for Linux takes ages to compile the sources. I have no idea what is going on, the setup is identical to the 32bit builder that performs as expected.

**Comment by ibell** [comment]
Where does it take forever - in the actual compilation?  Is the conda build
doing something special?

**Comment by jowr** [comment]
Unfortunately, you were right about pip. Both, conda and pip, take forever during the actual compilation step.

**Comment by ibell** [comment]
That's so weird.  On my linux box the builds are normal speed - a few
minutes.

**Comment by jowr** [comment]
I moved the 64bit to a docker container on the same machine. Everything builds just fine now and I have no idea what was wrong. Actually things are even further away from the hardware now. I am running the `coolprop/slavepython` docker image in a virtual Linux running on top of OSX and everything builds at a reasonable speed. Check http://www.coolprop.dreamhosters.com/binaries/sphinx/develop/buildbot.html#work-in-progress-dockerfile-generator for the temporary documentation. 

What about moving the documentation builder to a docker container as well? I think we might benefit from it in the long run as it seems like we need a better way to handle build configurations and machine setups. I started looking into it here: https://hub.docker.com/r/coolprop/slaveweb

**Comment by ibell** [comment]
I'm definitely not opposed. I have no experience with docker, and somehow I
think you are in the same boat.  But I think this is a great idea, and I'm
keen to see how far we can go with it.  Do you want to attack this problem,
or should I?

**Comment by jowr** [comment]
The 64bit Python builder works reliably now. There are still some issues with the 32bit architecture since the containers are 64bit and one has to manually tell the system to operate in 32bit mode, but it almost works.

I currently test the documentation builder, so be prepared for many error messages from the buildbot master...

**Comment by jowr** [comment]
Well, it looks like the examples won't work in a docker image - they need MATLAB, R, Octave... I enabled the old builder again.

**Comment by ibell** [comment]
Hmm, that is a bummer.  I started looking into docker, and it seemed
interesting.  I think integrating the open-source stuff should be
relatively straightforward, MATLAB less so.  Pity, really.  I think if we
have a working architecture, we shouldn't mess too much with it.

When I get back home, we should release 5.1.2 with whatever is ready.  It's
time.

**Comment by jowr** [comment]
Yes, one option to keep in mind is to use a separate builder for the examples. They really do need a delicate setup since CoolProp has to be available to millions of applications in a million of ways. Otherwise, the docs build fine inside an image as do the Python binaries.
