### ISSUE TITLE
Property calls for R410A do not converge

### ISSUE THREAD

**Issue by bachc** [CoolProp/CoolProp#815]
I found some convergence issues for R410A:

from CoolProp.CoolProp import PropsSI
h_R410A=PropsSI('H','P', 1000000., 'D', 300., 'R410A')
PropsSI('P','H', h_R410A, 'D', 300., 'R410A')

Results in:
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    PropsSI('P','H', h_R410A, 'D', 300., 'R410A')
  File "CoolProp\CoolProp.pyx", line 216, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:25939)
  File "CoolProp\CoolProp.pyx", line 296, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:25740)
  File "CoolProp\CoolProp.pyx", line 185, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:24065)
ValueError: Inputs in Brent [200.000000,344.484343] do not bracket the root.  Function values are [-0.550313,-5.860497] : PropsSI("P","H",231809.3221,"D",300,"R410A")

The chosen statepoint is within the 2-phase dome at low quality (about 9%). Similar issues if T, Q, or S is selected as output. Not an issue for Water, R22, R134a, R1234yz, and Propane but did not do rigorous testing over the entire 2-phase dome.

**Comment by jowr** [comment]
Thanks for reporting the issue. R410A is a mixture and I would guess that the same error might occur with other pseude-pure fluids that use the same EOS. A temporary workaround might be to use the full mixture model if available: R410A = 0.5 R32 + 0.5 R125

**Comment by bachc** [comment]
Jorrit, thanks for the hint - do you know offhand how to use the full mixture model in CoolProp? Couldn't find it in the examples section (http://www.coolprop.org/coolprop/examples/examples.html).

Thanks!

**Comment by jowr** [comment]
http://www.coolprop.org/coolprop/HighLevelAPI.html#calling-refprop
but it only supports a limited selection of flash functions. `PD` and `HD` inputs are not supported yet...

**Comment by bachc** [comment]
Thanks!

**Comment by ibell** [comment]
I hadn't fully read your question.  The pseudo-pure EOS are not defined in
the two-phase region.  You are responsible for figuring out what you want
to do when you are inside the dome.  As @jowr says, inside the dome you
have to use the full mixture model, which unfortunately does not currently
include the inputs D,P.

**Comment by ibell** [comment]
And really, if you are going to use the full mixture model, you should use
the low-level interface: http://www.coolprop.org/coolprop/LowLevelAPI.html

**Comment by bachc** [comment]
Quick note - I checked with an older version of coolprop and it wasn't a problem. I'll see if I can check the exact version.

**Comment by ibell** [comment]
Yes, the old version of CoolProp had the "wrong" answer.  You have to use the full mixture model since the composition of neither liquid nor vapor are the same as the bulk composition in the two-phase region.
