### ISSUE TITLE
Issue with viscosity of R245FA

### ISSUE THREAD

**Issue by davideziviani** [CoolProp/CoolProp#816]
I was running few simulations with R245FA and I got several errors while calculating the viscosity. See below an example. I am currently using v5.1.0. 

PropsSI("V","T",389.5096358,"P",231049.0157,"R245fa")
 File "CoolProp\CoolProp.pyx", line 210, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:21548)
  File "CoolProp\CoolProp.pyx", line 290, in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:21349)
  File "CoolProp\CoolProp.pyx", line 179, in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:19674)
ValueError: Not able to get a solution : PropsSI("V","T",389.5096358,"P",231049.0157,"R245fa")

**Comment by ibell** [comment]
Unfortunately this is a known issue: #665

**Comment by davideziviani** [comment]
As a workaround, I just added a numerical artifact to slightly modify the P value until the solver moves on successfully.

**Comment by ibell** [comment]
I found a lot of other failures unfortunately.  I think I have a quite aggressive workaround that will replace corresponding states, but we shall see.

**Comment by davideziviani** [comment]
Alright Ian, let me know when you will make any changes.
