### ISSUE TITLE
Cool Prop does not converge (python)

### ISSUE THREAD

**Issue by lubryeli** [CoolProp/CoolProp#817]
Hello!
This part of my code:

--> 217  T_cond=round((T_cond1+dTcond_dt),3)
--> 218  p_sTcond=CP.Props('P','T',T_cond,'Q',0,'Water')

Gives me this error:
Maxwell solver did not converge after 30 iterations;  rhoL: 54854.38605842201 rhoV: 4.511070906527642 error: 8.04731e-010 dvL/vL: 7.4832e-015 dvV/vV: 1.1512e-014 pL: 12055.3 pV: 12055.3
: PropsSI("P","T",322.661,"Q",0,"Water") 

It works great in MS Excel for this temperature, it returns pressure 12,055 kPa.
I have downloaded CoolProp wrapper for Python yesterday, so I think I have the latest version.
I know that I should better use PropsSI now, but the code is old. I tried to change that but PropsSI gives the same error.
I work on 32 bit Windows now, but I have checked it also on 64 bit one - my code still doesn't work.
I would be very grateful for hints on what can I do to avoid this problem.

**Comment by jowr** [comment]
Which version of CoolProp are you using? I have no problem with the code you posted:
```Python
import CoolProp
CoolProp.__version__ # u'5.1.2dev'
CoolProp.__gitrevision__ # u'56cd2c3867707df4d3c587c238a8221b58a879a7'
import CoolProp.CoolProp as CP
CP.PropsSI("P","T",322.661,"Q",0,"Water") # 12055.323954541916
```

**Comment by lubryeli** [comment]
Thank you for your quick answer.
I am working with Enthought Canopy and I have installed CoolProp by using "pip install".
I am not sure which version I have, because I actually don't know how to check it.

**Comment by lubryeli** [comment]
I am using CoolProp version 5.1.1

**Comment by ibell** [comment]
I can confirm that this fails with 5.1.1 in 32-bit.

**Comment by lubryeli** [comment]
How can I update CoolProp to 5.1.2 Version? On pypi.python.org 5.1.1 is the latest version.

**Comment by jowr** [comment]
There is no version 5.1.2. I currently use the latest source code and that is 5.1.2dev. The example I showed ran on 64bit Windows, could this be a platform or bitness issue?

**Comment by ibell** [comment]
If you use the command at http://www.coolprop.dreamhosters.com/binaries/sphinx/coolprop/wrappers/Python/index.html#automatic-installation (the second one), it will install the development version.  Buyer beware !

**Comment by ibell** [comment]
32-bit 5.1.2dev works just fine, so go ahead and update using the link shown above and close this issue if it works for you.

**Comment by lubryeli** [comment]
It works! Thank you very much!
