### ISSUE TITLE
Add cmake option to generate Android .so library 

### ISSUE THREAD

**Issue by sabatind** [CoolProp/CoolProp#820]
I'd like to compile CoolProp for Android by modifying the CMAKE script to generate an .so file.  This is a slight variation of the existing java option, but requires the Android ndk be added to the toolchain .  Any assistance would be appreciated. 

Thank You.

**Comment by ibell** [comment]
Having done some reading, it seems the right solution is to auto-generate a
makefile for the CoolProp.so for npm-build and then run swig followed by
the android builder so that it builds for the correct architecture.

**Comment by ibell** [comment]
See the files added in 915416d47caf6b13a16f90be58c6a62db2a332fb

It builds for me following the instructions here: https://github.com/CoolProp/CoolProp/blob/915416d47caf6b13a16f90be58c6a62db2a332fb/Web/coolprop/wrappers/Android/index.rst

which will soon be viewable online in a better format at: http://www.coolprop.dreamhosters.com/binaries/sphinx/coolprop/wrappers/Android

**Comment by sabatind** [comment]
Thanks you for all of your effort.  A quick comment about the draft documentation.  The flag should be -DCOOLPROP_ANDROID_MODULE to be consistent with the current code.

I am compiling on a Windows machine and unfortunately it didn't build. I am using mingw32, but I had already managed to get it configured to properly compile for java using your suggestions from issue #608.  

Based on my experience compiling for java I added the generator flag to the cmake call:

cmake .. -DCOOLPROP_ANDROID_MODULE=ON -DNDK_PATH=C:/Users/Matthew/AppData/Local/Android/ndk -G "MinGW Makefiles"

and then I build with:
mingw32-make

Cmake looks like it runs fine, but as you see in the output attached below, it crashes on the build.  I would certainly prefer to compile this one Windows, but if there is not an obvious fix for this, I can transition to a Linux machine.  


C:\Users\Matthew\AndroidStudioProjects\CoolProps\CoolProp.sources\build>cmake .. -DCOOLPROP_ANDROID_MODULE=ON -DNDK_PATH=C:/Users/Matthew/AppData/Local/Android/ndk -G "MinGW Makefiles"
-- COOLPROP_INSTALL_PREFIX=C:/Users/Matthew/AndroidStudioProjects/CoolProps/CoolProp.sources/install_root
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe
-- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/TDM-GCC-64/bin/g++.exe
-- Check for working CXX compiler: C:/TDM-GCC-64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CoolProp version: 5.1.2dev
-- Found PythonInterp: C:/Python27/python.exe (found suitable version "2.7.10", minimum required is "2.7")
-- Found SWIG: C:/Users/Matthew/AppData/Local/Android/swigwin/swig.exe (found version "3.0.6")
-- WORKING_DIRECTORY=C:/Users/Matthew/AndroidStudioProjects/CoolProps/CoolProp.sources/build
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Matthew/AndroidStudioProjects/CoolProps/CoolProp.sources/build

C:\Users\Matthew\AndroidStudioProjects\CoolProps\CoolProp.sources\build>mingw32-make
Scanning dependencies of target generate_headers
Traceback (most recent call last):
  File "C:/Users/Matthew/AndroidStudioProjects/CoolProps/CoolProp.sources/dev/generate_headers.py", line 298, in <module>
    generate()
  File "C:/Users/Matthew/AndroidStudioProjects/CoolProps/CoolProp.sources/dev/generate_headers.py", line 283, in generate
    shutil.copy2(os.path.join(repo_root_path, 'externals','Catch','single_include','catch.hpp'),os.path.join(repo_root_path,'include','catch.hpp'))
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Matthew\\AndroidStudioProjects\\CoolProps\\CoolProp.sources\\externals\\Catch\\single_include\\catch.hpp'
CMakeFiles\generate_headers.dir\build.make:56: recipe for target 'CMakeFiles/generate_headers' failed
mingw32-make[2]: *** [CMakeFiles/generate_headers] Error 1
CMakeFiles\Makefile2:103: recipe for target 'CMakeFiles/generate_headers.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/generate_headers.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by ibell** [comment]
Funny, that should work.  I can fire up my windows machine and see what is
going on.  Maybe you haven't updated the externals?  What do you have in
externals/Catch directory relative to CoolProp root?

I'll update the docs.

**Comment by ibell** [comment]
Docs are updated in 79fa5178b33bd4d15bb23681296801d2ec34cd28

You should be able to call ``cmake --build .`` rather than ``mingw32-make``
(cmake --build . calls mingw32-make internally).  That way its the same
command on all platforms.

The generator comment for MinGW is a good one.  I should think about
updating the docs.

**Comment by sabatind** [comment]
Ian, 

It's empty! I assumed it was some Windows issue. I had just downloaded the CoolProp-master.zip from github to make sure I had the latest and I see it is empty in the zip. An earlier version I have has files in there. I'll try and run cmake on that version right now. 

Dan

**Comment by ibell** [comment]
Yes you need to check out using git, otherwise the externals are missing.
Or you could download all the sources as a zip (including externals) from :
http://www.coolprop.dreamhosters.com/binaries/source/

**Comment by sabatind** [comment]
It compiled! I'll post an update when I confirm it is working within the App.

**Comment by ibell** [comment]
Great!  Did you follow the instructions to the letter, or did you use the zip file?  Any other workarounds needed?

**Comment by sabatind** [comment]
I used the zip file.  

It wouldn't let me run cmake --build, it required a target directory.  I tried a bunch of combinations, but the only thing that I could get work was to move up one directory from the build directory and then run cmake --build build.   I tried to run cmake .. --build build within the build folder and it didn't seem to recognize I had included ".."  This just may be my inexperience with cmake. 

The only other thing I did not in the documentation was to change the name of the package in the CmakeLists.txt file.  

I wasn't able to get the library file to work yet, although I think it is a good build.  I just may have to change the target architecture.  That is something that is set in the Android.mk file.  I believe that means I would edit your Android.mk.template that lives in the wrappers/Android folder.  Is that correct?

**Comment by ibell** [comment]
I think we need to add a cmake variable for the arch that will get injected into the template.  What is the variable name we need to be setting in Android.mk?

With regards to cmake --build, if you'll note, there is a . at the end of the command; the . means "in this directory"

**Comment by ibell** [comment]
For now, why don't you modify the template to get things to work and then post the updated template?

**Comment by sabatind** [comment]
Ok.  I'll work with the template over the next few days and hopefully get something working I can post.  

As for the cmake command, I indeed missed the dot.  It works fine.

Thanks again for the help.

**Comment by sabatind** [comment]
I was able to successfully compile an .apk file and run it using the CoolProp library!  It turned out not to be a target architecture.  Actually, from what I have been reading, the default ARM architecture seems to be the best choice.  You might just want to include a mention in the documentation that the ndk-build options can be set in the Android.mk.template file (as that is very accessible) and direct them to ndk site (https://developer.android.com/ndk/guides/index.html) for a description of the variables.

It took a little digging to find out how to integrate the files into an Android Studio project.   If they are creating a separate android project (as I did) they will need to copy the files from the package directory (i.e. build/com/joe/smith/app) to the package directory in their project.  The build/libs/armeabi folder containing the .so file has to be copied to app/src/main/jniLibs of the Android Project (they will likely have to create the directory).

In the main activity of the Android Project they need to add:

static {
            System.loadLibrary("CoolProp");
        }

After that, they can call CoolProp functions as described in your CoolProp java documentation.  

I'd be glad to provide more info if needed.  Many, MANY thanks for your fast, precise and effective modifications.  I'll send a beta version for you to try when its finished in a few weeks.

**Comment by ibell** [comment]
Can you write this all up in the file in Web/coolprop/wrappers/Android?
That would be the best.  Thanks!

**Comment by sabatind** [comment]
A few days ago I checked out a local copy of the CoolProp repository, modified the index.rst file in the /Web/coolprop/wrappers/Android folder and committed the changes.  Please let me know if there is anything else I should do.

**Comment by ibell** [comment]
You need now to make a pull request with your new code.  Depends on your
git interface how you do that.  Alternatively, you could just do it in the
browser, github will walk you through it if you modify the file here:
https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/Android/index.rst

Github will ask whether you want to fork and generate a pull request as you
go.  For folks new to git, this is often what I recommend.  I can clean up
the formatting at the end.

**Comment by sabatind** [comment]
I finally managed to create a pull request.  I'd be happy to add detail or do any clean up.  Just let me know.

**Comment by ibell** [comment]
Did you see my comments on your PR?
