### ISSUE TITLE
Request: PropsSI Inputs of D and Q

### ISSUE THREAD

**Issue by dansteingart** [CoolProp/CoolProp#822]
it would be great if PropsSI could take a D and Q input to return values.  Current I can hack it by reversing over a range of P,T,H or S, and matching against D for a given Q, but it would be great not to have to do that.  

e.g.

Rather than
```python
D3 = 1/0.845
Ps = linspace(1e5,3e5,500)
Ds = PropsSI('D','P',Ps,'Q',1,'water')
DifD = min(abs(Ds-D3))
DifDS = list(abs(Ds-D3))
ind = DifDS.index(DifD)
P3 = Ps[ind]
```

```python
D3 = 1/0.845
P3 = PropsSI('P','D',D3,'Q',1,'water')
```

Thanks in advance.  I know the former example could be more pythonic, but the request still makes sense IMHO,

**Comment by ibell** [comment]
Can be done I think.  In fact I think it is possible at the low level but not currently at the high level.  I can make that change.

**Comment by dansteingart** [comment]
@ibell many thanks!
