### ISSUE TITLE
Documentation for use of static libraries is unclear

### ISSUE THREAD

**Issue by tianshuluo** [CoolProp/CoolProp#823]
I use g++ to compile the example code:
``` c++
#include "CoolProp.h"
#include <iostream>
using namespace CoolProp;
int main()
{
    // First type (slowest, due to most string processing, exposed in DLL)
    std::cout << PropsSI("Dmolar","T",298,"P",1e5,"Propane[0.5]&Ethane[0.5]") << std::endl; // Default backend is HEOS
    std::cout << PropsSI("Dmolar","T",298,"P",1e5,"HEOS::Propane[0.5]&Ethane[0.5]") << std::endl;
    //std::cout << PropsSI("Dmolar","T",298,"P",1e5,"REFPROP::Propane[0.5]&Ethane[0.5]") << std::endl;

    std::vector<double> z(2,0.5);
    // Second type (C++ only, a bit faster, allows for vector inputs and outputs)
	std::vector<std::string> fluids; fluids.push_back("Propane"); fluids.push_back("Ethane");
	std::vector<std::string> outputs; outputs.push_back("Dmolar");
	std::vector<double> T(1,298), p(1e5);
    std::cout << PropsSImulti(outputs,"T", T, "P", p, "", fluids, z)[0][0] << std::endl;
    std::cout << PropsSImulti(outputs,"T", T, "P", p, "HEOS", fluids, z)[0][0] << std::endl;
    //std::cout << PropsSImulti(outputs,"T", T, "P", p, "REFPROP", fluids, z)[0][0] << std::endl;
    
    return 1;
}
```
, got the message:'
home/lts/software/open_engineer/CoolProp.sources/build/libCoolProp.a(REFPROPMixtureBackend.cpp.o)：in function ‘getFunctionPointer(char const*, DLLNameManglingStyle)’中：
REFPROPMixtureBackend.cpp:(.text+0x8d3)：undefined reference to ‘dlsym’
/home/lts/software/open_engineer/CoolProp.sources/build/libCoolProp.a(REFPROPMixtureBackend.cpp.o)：in function ‘load_REFPROP(std::string&)’中：
REFPROPMixtureBackend.cpp:(.text+0x155e):undefined reference to ‘dlopen’
/home/lts/software/open_engineer/CoolProp.sources/build/libCoolProp.a(REFPROPMixtureBackend.cpp.o)：in function ‘CoolProp::REFPROPMixtureBackend::~REFPROPMixtureBackend()’中：
REFPROPMixtureBackend.cpp:(.text+0x1d59)：undefined reference to ‘dlclose’'

Can one bypass REFPROP?

**Comment by ibell** [comment]
You need to link with the dl library as was mentioned in the other issue (#207), which is why you see this error, even though you don't want to/plan to use REFPROP.  I will update the docs.

Basically you need to do something like:
```
g++ main.cpp -lCoolProp -ldl -I/home/belli/Code/CoolProp/include -L/home/belli/Code/CoolProp/build
```
Obviously modify paths as needed.

**Comment by tianshuluo** [comment]
I have not the librefprop.so. I don't want to use REFPROP. Does Coolprop depend on REFPROP? I have commented the code above relative to REFPROP.  Yesterday I have read the issue (#207), I have add the flag '-ldl'. I have stll got the error message above.

**Comment by ibell** [comment]
What is the full command line call you use to build main.cpp?  You can
build CoolProp without needing REFPROP, it is only at runtime that you need
to have REFPROP if you want to use it.

**Comment by ibell** [comment]
Also, what platform are you on?  Ubuntu? Something debian based?

**Comment by tianshuluo** [comment]
g++ -L/home/lts/software/open_engineer/CoolProp.sources/build -o bin/Debug/1 obj/Debug/main.o  -ldl  /home/lts/software/open_engineer/CoolProp.sources/build/libCoolProp.a
ubuntu. I don't want to use REFPROP definitely.

**Comment by ibell** [comment]
That's weird.  I'll try tonight, but that should definitely work.  What about playing with the order of -ldl and -lCoolProp?  Sometimes the order matters and I can never remember what is the right order.

**Comment by tianshuluo** [comment]
After I have changed the order of -ldl and -lCoolProp, there is no errors in the compilation. But after run executable I got this: 
40.8269
40.8269
Segmentation fault (core dumped)

**Comment by ibell** [comment]
2 issues in your code:
1) ``std::vector<double> T(1,298), p(1e5);`` should be ``std::vector<double> T(1,298), p(1,1e5);`` (you allocated a vector with 100000 elements instead of one-element vector with value 1000000 Pa)
2) line ``PropsSImulti(outputs,"T", T, "P", p, "", fluids, z)`` is your seg fault.  I need to fix this - it should not fail that way.  It should throw an exception.

**Comment by ibell** [comment]
Another issue in your code:
3) ``PropsSImulti(outputs,"T", T, "P", p, "", fluids, z)`` yields an empty vector, which you take the 0 index of - that is why you get the segfault.  You should check the length of the returned vector before indexing it.

**Comment by tianshuluo** [comment]
The code above comes from http://www.coolprop.org/coolprop/HighLevelAPI.html#c-sample-code

**Comment by ibell** [comment]
Interesting @tianshuluo .  I will fix that code!  Thanks for the report!

**Comment by tianshuluo** [comment]
Thank you for your work.

**Comment by tianshuluo** [comment]
After run the modified code:'
// Second type (C++ only, a bit faster, allows for vector inputs and outputs)
 	std::vector<std::string> fluids; fluids.push_back("Propane"); fluids.push_back("Ethane");
 	std::vector<std::string> outputs; outputs.push_back("Dmolar");
-	std::vector<double> T(1,298), p(1e5);
-    std::cout << PropsSImulti(outputs,"T", T, "P", p, "", fluids, z)[0][0] << std::endl;
+	std::vector<double> T(1,298), p(1,1e5);
+    std::cout << PropsSImulti(outputs,"T", T, "P", p, "", fluids, z)[0][0] << std::endl; // Default backend is HEOS
     std::cout << PropsSImulti(outputs,"T", T, "P", p, "HEOS", fluids, z)[0][0] << std::endl;
+    // Comment me out if REFPROP is not installed
     std::cout << PropsSImulti(outputs,"T", T, "P", p, "REFPROP", fluids, z)[0][0] << std::endl;
     
     return EXIT_SUCCESS;'
I got still the same error message'
40.8269
40.8269
Segmentation fault (core dumped)'.

**Comment by ibell** [comment]
Did you also update your C++ code from CoolProp?  I fixed a bug in the
AbstractState.cpp file.  The example works for me now.

**Comment by tianshuluo** [comment]
Yes, I updated my C++ code according to your advise. It seems that the function PropsSImulti could not work correctly.

**Comment by ibell** [comment]
But its not just your code that needs to be updated.  I fixed a bug in the
code called by PropsSImulti.  So you need to update all of CoolProp, by
checking out code with git or however you got the code in the first place

**Comment by tianshuluo** [comment]
According to your advise, I updated all of CoolProp using the scripts'git clone https://github.com/CoolProp/CoolProp --recursive'. The error occurs still.

**Comment by ibell** [comment]
Sounds like you are still not using the updated code somehow.  I don't know
how you build the project, or what operating system you use, but it should
work fine.  I'll provide a simple example when I get onto my laptop of the
entire workflow.

**Comment by tianshuluo** [comment]
I use ubuntu 14.04. According to http://www.coolprop.org/coolprop/wrappers/StaticLibrary/index.html#static-library, I updated all of CoolProp.

**Comment by ibell** [comment]
I have updated instructions here: http://www.coolprop.dreamhosters.com/binaries/sphinx/coolprop/wrappers/StaticLibrary/index.html#static-library

To update (without doing a complete checkout), you would go into the directory and do a 
```
git pull 
```

Can you please provide a complete description of how you are trying to build your program?  If you do a fresh checkout of CoolProp using the instructions above, add your main.cpp file, and compile into an executable, the example should work.  I have tested all the examples on OSX, and they work fine.  I think the problem is in your build system somewhere.  Did you recompile?

**Comment by tianshuluo** [comment]
Now the example code works fine. I use the codeblocks to build my program. But the libCoolProp.a is too large, its size reaches 147.0Mb.

**Comment by ibell** [comment]
Good to hear - what was the problem?  The hugeness of your static library
is probably because g++ is linking the entire C++ runtime into the static
library.  I noticed this on windows as well when I use mingw.  Can you
please file a separate issue about that and I will investigate?

**Comment by tianshuluo** [comment]
The problem was caused by Codeblocks. It retain my original option, so the the library option points to error location.

**Comment by ibell** [comment]
Ah ok.  Please go ahead and open that new issue anyway.
