### ISSUE TITLE
C-Sharp Wrapper AbstractState mole_fractions_liquid

### ISSUE THREAD

**Issue by vitcaro** [CoolProp/CoolProp#824]
**C-Sharp Wrapper AbstractState mole_fractions_liquid**
this function (mole_fractions_liquid) is of the type: 
SWIGTYPE_p_std__vectorT_CoolPropDbl_t
This type does not give back the required values.
If converted to the type  DoubleVector you can get values.

**ACTUAL CODE in c# wrapper:**
 public SWIGTYPE_p_std__vectorT_CoolPropDbl_t mole_fractions_liquid()
  {
    SWIGTYPE_p_std__vectorT_CoolPropDbl_t ret = new SWIGTYPE_p_std__vectorT_CoolPropDbl_t(CoolPropPINVOKE.AbstractState_mole_fractions_liquid(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CoolPropDbl_t mole_fractions_vapor() {
    SWIGTYPE_p_std__vectorT_CoolPropDbl_t ret = new SWIGTYPE_p_std__vectorT_CoolPropDbl_t(CoolPropPINVOKE.AbstractState_mole_fractions_vapor(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

**PROPOSED CODE:**
  public DoubleVector mole_fractions_liquid()
  {
          DoubleVector ret = new DoubleVector(CoolPropPINVOKE.AbstractState_mole_fractions_liquid(swigCPtr), true);
          if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
          return ret;
  }

  public DoubleVector mole_fractions_vapor()
  {
          DoubleVector ret = new DoubleVector(CoolPropPINVOKE.AbstractState_mole_fractions_vapor(swigCPtr), true);
          if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
          return ret;
  }
**Other types can have the same problem**
There are other types which do not give back the required values.
Classes which start with following letters:
**public class SWIGTYPE_p_......**
can have the same problem.

**Comment by ibell** [comment]
Yeah it is trying to manage a modifiable pointer, which is technically
correct, but not exactly what we want.  Probably best is to make those
functions const in the SWIG wrapper which will simplify the wrapper and
result in a copy.

**Comment by ibell** [comment]
Other examples of things that don't work?

**Comment by vitcaro** [comment]
I add following comment.
I do not know how SWIG is working, but I make following comments on the C# wrapper that is result of SWIG job.
A number of classes which start with following letters:
public class SWIGTYPE_p_......
are partially **dummy** classes:
they retrieve the pointer to the data, but they do not contain functions or propertyes to deliver these data to the wrapper user.
These classes should be made using as model the class "DoubleVector" contained in the C# wrapper.

**Comment by ibell** [comment]
That's correct, but from the standpoint of the wrapper, I think all the important functionality has been properly exposed to C#.  The mole fractions were particularly tricky, but I think I have that sorted.  If there are other things in the AbstractState that should work in a different way than they do, I would be interested to hear about it.  For now, I'm closing this issue.
