### ISSUE TITLE
CoolProp FORTRAN wrapper CMake compilation error in OSX

### ISSUE THREAD

**Issue by smyng91** [CoolProp/CoolProp#829]
Hello! I need some help compiling CoolProp FORTRAN wrapper on OSX El Capitan. I followed all the procedures listed in http://www.coolprop.org/coolprop/wrappers/FORTRAN/index.html#fortran95 to create a static library for FORTRAN 95/newer. However, I get the following error regarding CMake:

CMake Warning at CMakeLists.txt:144 (find_package):
By not providing "FindREQUIRED.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "REQUIRED",
but CMake did not find one.

Could not find a package configuration file provided by "REQUIRED" with any
of the following names:

REQUIREDConfig.cmake
required-config.cmake
Add the installation prefix of "REQUIRED" to CMAKE_PREFIX_PATH or set
"REQUIRED_DIR" to a directory containing one of the above files. If
"REQUIRED" provides a separate development package or SDK, be sure it has
been installed.

I am not an expert in FORTRAN or C++. I have gcc 5.2 (NOT CLANG) and gfortran 5.2 installed through macport.

Please help!
Thanks in advance,
Sam

**Comment by ibell** [comment]
So all is well?  What you saw is just a warning

**Comment by smyng91** [comment]
I did! I just commented that portion out in the CMakeList file.

Thanks!
Sam
