### ISSUE TITLE
Predefined mixtures fail for BICUBIC&REFPROP backend

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#831]
``` python
import CoolProp
pair = 'R407C.mix'
BICU = CoolProp.AbstractState('BICUBIC&REFPROP', pair)
BICU.update(CoolProp.QT_INPUTS, 1, 300)
print BICU.T()
```
throws ValueError

**Comment by mapipolo** [comment]
The issue I was describing earlier today is very similar, though I encountered exactly that issue earlier today while calculating T() after a bicubic update for a predefined mixture.

In response to the question in your email, I am indeed using the “.mix” predefined mixture models, and seem to have narrowed down the issue. The first six lines of code below work properly, but the last line fails with an AccessViolationException in AbstractState.update():

    state = AbstractState.factory("TTSE&REFPROP", "R407C");
    state.update(input_pairs.HmassP_INPUTS, 400800, 101325);
    state = AbstractState.factory("BICUBIC&REFPROP", "R407C");
    state.update(input_pairs.HmassP_INPUTS, 400800, 101325);
    state = AbstractState.factory("TTSE&REFPROP", "R407D.mix");
    state.update(input_pairs.HmassP_INPUTS, 400800, 101325);
    state = AbstractState.factory("BICUBIC&REFPROP", "R407D.mix");
    state.update(input_pairs.HmassP_INPUTS, 400800, 101325);

AccessViolationException occurred: A first chance exception of type 'System.AccessViolationException' occurred in FluidProps.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Detail:
System.AccessViolationException occurred
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=FluidProps
  StackTrace:
       at CoolPropPINVOKE.AbstractState_update(HandleRef jarg1, Int32 jarg2, Double jarg3, Double jarg4)
       at AbstractState.update(input_pairs input_pair, Double Value1, Double Value2) in ****\FluidProps\CoolProp\AbstractState.cs:line 120
  InnerException:

The only difference of course is bicubic vs. TTSE. That exception is typical of what’s going on with other refrigerants as well, such as R430A.mix and R410B.mix.

Using: C#, REFPROP 9.12, CoolProp nightly build.

**Comment by ibell** [comment]
I'll dig into this a bit and see what is going on.  Just a small bug somewhere.  Should be relatively easy to track down.  I can't promise a time-frame though.
