### ISSUE TITLE
Accessing low-level interface from fortran 90/95

### ISSUE THREAD

**Issue by smyng91** [CoolProp/CoolProp#834]
Hello!

I've been struggling a lot trying to access low-level interface from Fortran 90/95. I've read the documentation and the example as well, but I still do not get how to link the CoolPropLib.h (header) with Fortran main file. Is there any document I can follow? Based on what I've read so far, it is not a straightforward task to couple Fortran and C++. 

Please help!

Thanks in advance,
Sam

**Comment by ibell** [comment]
For the low-level interface, you need use the AbstractState_XXXX functions,
but they haven't been ported to Fortran as of yet.  It's pretty
straightforward.  You make a shim function with the proper name and
arguments, just like we did with the PropsSI function, and then compile
everything together.  Can you get the FORTRAN example building?

**Comment by smyng91** [comment]
Thanks for a quick response!

Yes. I was able to successfully build and run FORTRAN simple_example using the following:
    gfortran -c fortmyfunc.f90
    gcc -c -std=c++11 myfunc.cpp
    gfortran fortmyfunc.o myfunc.o -o main -lstdc++
    main
I would really appreciate if you could provide more detailed guidance, since I am just a beginner with Fortran and C++..(sorry about that). So far, I've been able to:

1. Compile CoolProp for FORTRAN to CoolPropLibs.a.
2. Able to access high-level interface from FORTRAN code.

What are the next procedures I need to follow in order to access the low-level interface from FORTRAN?


Thanks again!
Sam

**Comment by smyng91** [comment]
Hi!
How do you declare data type long (c++) in FORTRAN?

Thanks,
Sam

**Comment by ibell** [comment]
I *think* it depends on your platform.  According to this (https://gcc.gnu.org/onlinedocs/gfortran/LONG.html), I would guess INTEGER(4)

**Comment by smyng91** [comment]
Thank you ibell. I was able to successfully define the variable type (it was integer(kind=8) in my case, or just integer(c_long). Now I am facing an issue with the following step, after I obtain "handle" from AbstractStsate_factory (I've been following the example with Julia and C++):

 	call AbstractState_update(handle, input_pair, P, T)

Since AbstractSTate_update is a void function in C++, I've defined this function as a subroutine in FORTRAN-C++ interface as follows:

		SUBROUTINE AbstractState_update(inputPointer, inputType, prop1, prop2) BIND(C, NAME='AbstractState_update')
			use iso_c_binding
			integer(C_long) :: inputPointer
			integer(C_long) :: inputType
			real(C_DOUBLE), VALUE :: prop1
			real(C_DOUBLE), VALUE :: prop2
			
		END SUBROUTINE AbstractState_update

inputPonter and inputType have been obtained without any problem (I've actually output these values). Nonetheless, I am getting segmentation-invalid memory reference errors. 

Please help!
Thanks again!

Sam

**Comment by ibell** [comment]
I think the core issue is that you are missing some of the parameters: errcode, buffer, buffer_length.  Almost certainly that is the issue.  Otherwise it should all work.

``` c++
EXPORT_CODE void CONVENTION AbstractState_update(const long handle, 
                                                 const long input_pair, 
                                                 const double value1, 
                                                 const double value2, 
                                                 long *errcode, 
                                                 char *message_buffer, 
                                                 const long buffer_length);
```

**Comment by smyng91** [comment]
Thanks again ibell!

It works now!

One last question,
is there any analytical function that allows us to compute saturation derivatives, such as first_saturation_deriv()? Or do we have to do a numerical evaluation in FORTRAN?

Thank you!
Sam

**Comment by ibell** [comment]
That exists in the low-level interface already, see
http://www.coolprop.dreamhosters.com/binaries/sphinx/apidoc/CoolProp.CoolProp.html#CoolProp.CoolProp.AbstractState.first_saturation_deriv
, but it has not been wrapped in CoolPropLib.h.  If you would be interested
in this, please open an issue and I'll do it.

Also, please provide all your code for the FORTRAN interface, I'd like to
get that back in CoolProp.  Do you know how to modify code on github? You
could go to this file -
https://github.com/CoolProp/CoolProp/blob/master/wrappers/Fortran/detailed_example/cpinterface.f90
- and edit it which will generate a pull request.

**Comment by smyng91** [comment]
Thanks! I just opened an issue on adding the saturation_deriv() to CoolPropLib.h.

I'll also provide all my code.

Thanks again!
Sam

**Comment by ibell** [comment]
Other issues cover this issue, closing.
