### ISSUE TITLE
LabVIEW diagrams_coolprop.vi 

### ISSUE THREAD

**Issue by BenReish** [CoolProp/CoolProp#839]
The issue was found while trying to use the diagrams_coolprop.vi.  The stated vi will get into a continuous loop due to initialise_coolprop.vi returning Inf for all Fluid data elements.  I downloaded my copy from your site last week (Oct 7, 2015).  I think the real problem is in initialise_coolprop.vi.  It is not returning useful data in the fluid data array.  This seems to be a problem with the Props1 function call.  

I run LabVIEW 2015, 64 bit.

**Comment by jowr** [comment]
Thanks for reporting. I think @adesideri might be able to help. He has used CoolProp with LabVIEW recently and did not have any issues.

**Comment by adesideri** [comment]
@BenReish. In the last months I have been using a version from march 2015 of the LabVIEW wrapper and had no problem with the Props1 function call in the initialise_coolprop.vi . I have just made a small test with the latest version of the wrapper using the 32 bit dll and it looks like the Props1 function in the initilaize_coolprop.vi is broken and not able to return the fluid data array. Not sure how to fix that though... @jowr

**Comment by ibell** [comment]
@desideri , Is the Props1 function broken? Any idea where the problem comes
from?  Can you debug and figure out a set of inputs that cause failure?

**Comment by ibell** [comment]
bump - I don't have the ability to test Labview...

**Comment by ibell** [comment]
bump - What inputs cause failures?

**Comment by ibell** [comment]
bump

**Comment by BenReish** [comment]
I used Water with 0.8bar to 225 bar starting at 0deg C for that homework. We were to make a log (P) – h plot.  Initially, I missed that the LabVIEW wrapper came with a method for creating that plot, so I made my own which accessed the CoolProp Init and Calc functions repeatedly.  This method got around the bug that I reported.

 

After class when I turned in the homework, I heard from the other students that there was a built in vi from the CoolProp download for LabVIEW that did just this P-h plotting.  They had problems making it work.  I tried and figured out how I had gotten around the problem with my work.  Then I reported the issue after seeing that no data ever returned from the Props1 function. This then caused a continuous while loop.

 

But, now my evaluation copy of LABView is expired so I can’t open the vi to see what I used. So I don’t know that I changed from whatever the defaults were.

 

Ben Reish

**Comment by ibell** [comment]
Guess we'll close this for now until you have some more concrete bugs to report.

**Comment by ibell** [comment]
Do you get an error of some sort at initialization time?

**Comment by vskconsultants** [comment]
There is no error but critical temperature and minimum temperature are inf.
