### ISSUE TITLE
R1233zd(E) reference

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#841]
What is the data source for R1233zd(E)? Is it http://dx.doi.org/10.1021/acs.jced.5b00348? I think we should add the reference.

**Comment by ibell** [comment]
Yes I am nearly certain we are using exactly the values in that paper.  Can you please email me the paper so I can be 100% sure? Or if you wanted to check yourself, even better.  It would be good to update the reference.

**Comment by ibell** [comment]
@jowr - reminder to send me the paper

**Comment by ibell** [comment]
Evidently, not the same.  I'll update to be the same as McLinden paper.  I thought I had reviewed this one, but I guess not.
