### ISSUE TITLE
Wrong enthalpy calculation for SES36

### ISSUE THREAD

**Issue by tartieret** [CoolProp/CoolProp#842]
Hi,

Doing a simple calculation with Coolprop 5 (Python wrapper) for a turbine expansion. 

With the parameters, 
> fluid = 'SES36'
> p_in = 1572358  # Pa
> t_in = 417.20     # K

I got the enthalpy **h(t_in, p_in)  = 376 kJ/kg**

However, when computing the enthalpy at the turbine outlet with the following parameters :
> p_out = 316155 # Pa
> t_out = 380.24 # K

I got the enthalpy value **h(p_out, t_out) = 446 kJ/kg**, which is not correct since **it's higher than the inlet enthalpy.**

I compared the results with Coolprop version 4 and the EES wrapper and the problem disappears. There is also no problem using the same code and calling another thermodynamic library like REFPROP for SES36. Therefore I assume there is a problem in the enthalpy model for SES36 in Coolprop 5

Any idea what can be wrong ?

Thank you !

Thomas

**Comment by ibell** [comment]
Interesting.  I'll take a look.  Have you tried doing any plotting of Ph
plots or things like that?  Would provide useful info for debugging.

**Comment by tartieret** [comment]
![plot](https://cloud.githubusercontent.com/assets/15146307/10591746/ae60d862-766c-11e5-9a21-db7da2fcd4ef.png)

When I plot the specific enthalpy as a function of temperature, for pressure = p_in = 1572358 Pa, I get the plot above. We can see that the phase change occurs above 418 °K. 

However, if I ask Coolprop what is the saturation temperature for this pressure, I get 417.0°K.

**Comment by jowr** [comment]
Could this be related to SES36 being pseudo-pure? There might be something wrong with the reducing and the critical parameters. I have no idea what it could be though.

**Comment by ibell** [comment]
Probably it has something to do with this:
http://www.coolprop.dreamhosters.com/binaries/sphinx/fluid_properties/fluids/SES36.html#consistency-plots

I'll investigate.

**Comment by ibell** [comment]
It seems the problems occurs because the saturation curves (bubble- and dew-) for SES36 are not well constructed and for some temperatures (notably T_inlet), the bubble-point pressure is lower than the dew-point pressure.  Which makes CoolProp think the first point should be in the liquid and it searches there.

Unfortunately, the experimental VLE data situation for SES36 is quite poor, but I'll see what I can do.

**Comment by tartieret** [comment]
Thanks Ian.

Anyway, with SES36 we have seen significant discrepancies between the thermodynamic properties given by REFPROP / Coolprop and the data calculated by the Solvay Solkane software (http://solkane-refrigerants.software.informer.com/download/). The difference in latent heat value is significant for instance. According to Solvay, designs should be based on their solkane values. Our experimental data agree with that. I can send more detailed comparaison if you want. 

Do you think we could consider implementing in Coolprop the same EOS that is used by Solkane ? The reference is : http://link.springer.com/article/10.1007%2Fs10765-007-0178-y
I can send it to you by email.

**Comment by tartieret** [comment]
Also, their is no problem with previous version of Coolprop. Was there any change in version 5 that could have caused that ?

**Comment by davideziviani** [comment]
@ibell  I think that is the same paper I forwarded to you about SES36. I should recheck my calculations with the latest CoolProp version to see if any issues with experiments

**Comment by ibell** [comment]
Please see results from new version: http://nbviewer.ipython.org/github/CoolProp/CoolProp/blob/master/dev/Tickets/SES%20enthalpy.ipynb

Much better!

**Comment by tartieret** [comment]
good job, thanks !

2015-11-14 17:57 GMT-08:00 Ian Bell <notifications@github.com>:
