### ISSUE TITLE
failure in calculation enthalpy for water

### ISSUE THREAD

**Issue by arnaudcretot** [CoolProp/CoolProp#844]
Hello,

When I run this code  : 
Q = 0.02
T = 200. + 273.15 
 enthalpy = PropsSI('H', 'Q', Q, 'T', T, 'water') # J/kg
 T2 = PropsSI('T', 'Q', Q, 'H', enthalpy, 'water') # K
 print T, T2, enthalpy

I got this message : 

ValueError: PropsSI failed ungracefully :: inputs were:"T","Q",2.0000000000000000e-02,"H",8.9106600902347546e+05,"water"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

I think there is something not normal here.
Tank you for this great coolProp tool,

Arnaud

**Comment by ibell** [comment]
Yes, actually it should fail in a different way.  Enthalpy and quality are
not supported inputs because you can get multiple solutions for some
fluids.  You should get a message to that effect.

**Comment by arnaudcretot** [comment]
Ah ok I see,
I will solve my problem on another way,

Thanks a lot
