### ISSUE TITLE
Tabular calculations fail with message "Unable to bisect segmented vector slice..."

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#845]
In the course of trying to make our application work with CoolProp's tabular backend, I'm beginning to frequently encounter a certain error, and I don't know if it's a bug or simply a result of running up against the bounds of the tabulated data. The second line of code below...

    AbstractState state = AbstractState.factory("BICUBIC&REFPROP", "R438A.mix");
    state.update(input_pairs.PSmass_INPUTS, 2.28 * 100000, 1783);

... throws a ValueError on line 651 of CoolPropTools.h with the following message, the four numbers being rL, rML, rMR, and rR, respectively:

    Unable to bisect segmented vector slice; neither chunk contains the solution -132.571 -82.2441 0.231794 28.3221

The inputs seem reasonable: it should be a superheated vapor almost 2°C above the dew point. Smaller values for Smass also produce the exception, but the call succeeds for Smass >= 1786. Now, examining the code in CoolPropTools.h, it is apparent what this means on a technical level—the products (rR)(rMR) and (rL)(rML) do not have opposite signs—but what does it mean from my position as a developer using the tabular backend? If it isn't a bug, but rather is the result of running up against the bounds of the tabulated data, how would one make iterative calculations resilient to these errors? The limits on input variables are not exposed as far as I know.

I really appreciate your attention to the issues I've brought up with the tabular backend. Last weekend's fixes let me push ahead quite a bit.

**Comment by Astrinus** [comment]
I have encountered today the same issue trying with inputs P 1.8e5 Pa, Smass 1132 - 1138 J/kg/K, fluid R245fa. PropsSI works almost fine (points are in the twophase region and show an increase in temperature along this isobare).

**Comment by ibell** [comment]
Its between the saturation boundary and the first cell in the single-phase area which is why bisection fails.  I think there must be a solution for this, but I'll have to think a little bit.  Perhaps fall back to TTSE near saturation.

**Comment by mapipolo** [comment]
This exception occurs for both TTSE and bicubic. I should have made that clear. Since it is a predefined mixture, the only thing left to fall back on is NIST's DLL itself.

**Comment by ibell** [comment]
I mean in the CoolProp routines themselves.  I think we can be a bit more
intelligent.

**Comment by ibell** [comment]
Point #3 in the bisection is pretty close to the solution.  Probably close
enough.

**Comment by ibell** [comment]
I think I have fixed this issue.  Please see http://nbviewer.ipython.org/github/CoolProp/CoolProp/blob/master/dev/Tickets/Tabular%20near%20saturation.ipynb - we can get very close to saturation now without problems.

**Comment by ibell** [comment]
Please go ahead and test, and let me know.  I'm closing for now since I would like to release 5.1.2 in the next day or so, and I believe this is fixed.

**Comment by mapipolo** [comment]
Thanks, Ian. It looks good: I'm no longer encountering this issue in the latest nightly build. However, there is another issue that I will bring up in a separate thread.
