### ISSUE TITLE
Minimal pressure and maximal pressure for water, solution and brines

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#846]
Hello Ian,

For water, solution and brines, could you tell me how to get the maximal and minimal pressure ?
For your information, I didn't find any bugs or matters for HAPROPSI since the the last modification : I think it's very stable now.

Have a good day.
Sincerely,
PY

**Comment by pmanach** [comment]
Hello Ian,

I precise my demand (after some tests to try to understand my error calculation) : 
If I would like to test "Water" as pure liquid just below its Tmax (200°C), for example at 199.9°C, I've to use a minimal pressure to be over the saturation pressure.
How can I get this minimal pressure ?

**Comment by jowr** [comment]
I am not sure I understand the question, but could this be helpful assuming that you refer to the incompressible backend? 
```Python
import CoolProp.CoolProp as CP
fluid = "INCOMP::Water"
p_sat = CP.PropsSI("P","T",175+273.15,"Q",0.0,fluid)
h = CP.PropsSI("H","T",175+273.15,"P",p_sat+10,fluid)
print(h)
```

**Comment by pmanach** [comment]
Yes. You have well understood and the answer is OK!
