### ISSUE TITLE
Can a similar option to the option 'OTH' of the REFPROP function SETREF added to the function set_reference_stateS 

### ISSUE THREAD

**Issue by tianshuluo** [CoolProp/CoolProp#847]
If the operation can not be carried out, can one choose a alternative way?

**Comment by ibell** [comment]
Currently there is no way to do this,but I build the set_reference_stateD
function for this purpose.  In the interim, you can just calculate the
enthalpy and entropy at the reference state, and then subtract them from
the calculated enthalpy and entropy values (plus any constant offset you
would like to apply).

**Comment by tianshuluo** [comment]
But a thermodynamic state point can be specified only by temperature and molar density utilizing the function set_reference_stateD. I need to specify a thermodynamic state point by temperature and pressure. Can I use the following statement to carry the operation?
    shared_ptr<AbstractState> Water(AbstractState::factory("HEOS","Water"));
    Water->update(TP_INPUTS, 288.15,101325,); 
    dm=Water->rhomolar();
    set_reference_stateD  ( "Water", 288.15,dm,h0,s0) ;

**Comment by jowr** [comment]
Yes, that is one possibility.

**Comment by ibell** [comment]
Your example should work, you could also have used the high-level interface:
``` python
dm = PropsSI('Dmolar','T',288.15,'P',101325,'Water')
set_reference_stateD ( "Water", 288.15,dm,h0,s0) ;
```
Not sure why you want to change the reference state for water (it is pretty well standardized), but people want to do all kinds of crazy things :)
