### ISSUE TITLE
Impressible pure fluid at T = 273.15K

### ISSUE THREAD

**Issue by pmanach** [CoolProp/CoolProp#850]
For some incompressible pure fluid, it’s impossible to calculate enthalpy at T = 273.15°K.
The list of concerned fluids is : 
AS10, AS20, AS30, AS40, AS55, HY20, HY30, HY40, HY45, HY50, TVP1869, TY20,

**Comment by davideziviani** [comment]
If you take a look at this page http://coolprop.sourceforge.net/fluid_properties/Incompressibles.html  , under the section Thermodynamics of Incompr. fluids, there is a warning about not to use a temperature corresponding to the T_base because it would lead to errors. In your case, T_base = 273.15 K for all the fluids.

**Comment by jowr** [comment]
The warning actually refers to the reference state and not the direct calculation of properties. I do not have any problems with the temperature you refer to:
```Python 
import CoolProp.CoolProp as CP
fluids = ["AS10", "AS20", "AS30", "AS40", "AS55", "HY20", "HY30", "HY40", "HY45", "HY50", "TVP1869", "TY20"]
for fluid in fluids:
    print("{0}: h = {1} J/kg".format(fluid,CP.PropsSI("H","T",20+273.15,"P",10e6,"INCOMP::"+fluid)))
```
yields
```Python
AS10: h = 8622.72021844 J/kg
AS20: h = 8048.01337503 J/kg
AS30: h = 7714.13386819 J/kg
AS40: h = 7401.04414574 J/kg
AS55: h = 7040.89330445 J/kg
HY20: h = 7418.88016242 J/kg
HY30: h = 7046.03725883 J/kg
HY40: h = 6760.71955954 J/kg
HY45: h = 6623.40248299 J/kg
HY50: h = 6461.43402877 J/kg
TVP1869: h = 7126.94166257 J/kg
TY20: h = 7442.84122882 J/kg
```

**Comment by jowr** [comment]
Sorry, that was the wrong temperature, here is the correct one:
```Python
import CoolProp.CoolProp as CP
fluids = ["AS10", "AS20", "AS30", "AS40", "AS55", "HY20", "HY30", "HY40", "HY45", "HY50", "TVP1869", "TY20"]
for fluid in fluids:
    print("{0}: h = {1} J/kg".format(fluid,CP.PropsSI("H","T",0+273.15,"P",10e6,"INCOMP::"+fluid)))
AS10: h = -62577.0048351 J/kg
AS20: h = -57613.4081533 J/kg
AS30: h = -54264.5984495 J/kg
AS40: h = -52454.5373804 J/kg
AS55: h = -50092.1638242 J/kg
HY20: h = -52128.9817297 J/kg
HY30: h = -49060.9435303 J/kg
HY40: h = -46605.7292747 J/kg
HY45: h = -45382.8294611 J/kg
HY50: h = -43944.6295569 J/kg
TVP1869: h = -39931.9558454 J/kg
TY20: h = -53629.9091597 J/kg
```

**Comment by ibell** [comment]
So we can close this?  Or what?

**Comment by jowr** [comment]
What was the problem? Should we update the documentation?

**Comment by pmanach** [comment]
Hello Jorrit,
I don't have time enough to reproduce the problem. Sorry.I think I will able to try it again in a few weeks.

Date: Mon, 9 Nov 2015 00:21:25 -0800
