### ISSUE TITLE
Coolprop R448A, R449A or R450A

### ISSUE THREAD

**Issue by dizzux** [CoolProp/CoolProp#854]
Hi all,

is it possible to make  calculations for R448A, R450A and R449A without REFPROP. I don't have REFPROP license.
If you have an alternative solution 

Thanks.

**Comment by ibell** [comment]
Currently no, since we are missing interaction parameters for a couple of
the binary pairs in these mixtures (not published values).  Give me another
month or so and the new interaction parameters will be in CoolProp and
REFPROP.

**Comment by ibell** [comment]
I think most of those mixtures should be pretty ideal.  So you should be able to use linear mixing rules.  Here is an example of doing that for a Helium-Xenon mixture:
``` python
import CoolProp.CoolProp as CP
CAS_He = CP.get_fluid_param_string('Helium','CAS')
CAS_Xe = CP.get_fluid_param_string('Xe','CAS')
CP.apply_simple_mixing_rule(CAS_He, CAS_Xe, 'linear')
```

**Comment by mayersre** [comment]
The results from the builtin refprop/coolprop  models differ quite a bit with those provided by honeywell (R448A, R450A ). Pressures differ > 0.5 bar at 0°C , for RAC engineering a nogo. Same applies to R449A and dupont. The files for refprop (hmx.bnc) can be obtained from the manufacturers.

**Comment by ibell** [comment]
Interesting.  What data are you comparing against, and have you alerted
Eric Lemmon of refprop?  I have been involved in fitting new interaction
parameters for most of the binaries forming these mixtures and I would be
keen to have good data to compare against for a multi-component mixture.

**Comment by mayersre** [comment]
Hello Ian,

I compare recent low gwp replacement mixtures for R-134a.

Dupont R-449A
Honeywell R-450A and 448A


If you look into the hmx.bnc files from DP (Dupont) and HW (Honeywell)
you see
different Parameters. You can dowload Duprex and get the hmx.bnc for
Dupont directly from the software ... it is refprop basically. The HW
hmx.bnc is available if you ask Ankit Sethi ankit.sethi@honeywell.com.
I can send the complete one to you if you like.

I compared refprop with self created mixtures to data output with the
published
documents by DP and HW and found that they differ. I got Duprex and
diffed the files
which showed hmx.bnc differ. Then I mailed Ankit to get the HW version
too. I have
three versions of hmx.bnc now ... The mixture files do not differ from
my self created
ones as far as I have compared up to now. In data I compared what is on
the tables usually
temperature, pressure, density, enthalpy, entropy ... only a few
selected lines.
The School Tables now match the manufacturer data.

So the steam tables and diagrams for the school need to be run on different
refprop/hmx.bnc now ... that is why I like the refprop environment switch :)

I only showed my colleagues the difference so far and how to get the
right data.

best regards
Reiner

Details :
Naicker at Dupont
and
Honeywell Ryan Belinda at Honeywell

Duprex has these which are not in NIST/Refprop:
#hmx.bnc###############################
!
?R134A/R1234YF
?Naicker (2013)           Based on experimental data from Chien-Ping
Kao, Private communication via J. Hughes
811-97-2/754-12-1         KW0    0.996096  0.99401771   1.0328709  
0.9435635   0.0000000   0.0000000
                          TC1    0.0000000   0.0000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000   0.0000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R1234yf/R32                (R1234yf/R32)
?Naicker (9/12/2011)      Based on experimental data from Chien-Ping
Kao, Private communication via J. Hughes
754-12-1/75-10-5          KW0    1.005107   0.9445894   0.8898251  
1.1125273   0.0000000   0.0000000
                          TC1    0.0000000   0.0000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000   0.0000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R125/R1234YF
?Naicker (2013)           Based on Experimental data from Chien-Ping Kao
via J. Hughes
354-33-6/754-12-1         KW0    0.983231  0.99924695   1.1393739  
1.0000000   0.0000000   0.0000000
                          TC1    0.0000000   0.0000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000   0.0000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
Genetron uses these which are not in NIST/Refprop:
#hmx.bnc#############################
?R1234yf     /R134a
?Honeywell  - Ryan 17May2010
754-12-1    /811-97-2     LJ6   -9.5057300  0.00000000   0.0000000  
1.0000000   1.0000000   0.0000000
                          TC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R1234ze     /R134a
?Honeywell  - Belinda 14Nov2013
29118-24-9   /811-97-2    LJ6   -6.2782000  0.00000000   0.0000000  
1.0000000   1.0000000   0.0000000
                          TC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R1234ze     /R32
?Honeywell  - Ryan 1June2010
29118-24-9   /75-10-5     LJ6  -19.2806000  0.00000000   0.0000000  
1.0000000   1.0000000   0.0000000
                          TC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R125     /R1234ze
?Honeywell - Ryan Sept2010
354-33-6    /29118-24-9   LJ6    3.5990500  0.00000000   0.0000000  
1.0000000   1.0000000   0.0000000
                          TC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R1234yf     /R1234ze
?Honeywell  - Ryan 7May2010
754-12-1    /29118-24-9   LJ6  -11.0000000  0.00000000   0.0000000  
1.0000000   1.0000000   0.0000000
                          TC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R125     /R1234yf
?Honeywell  - Ryan 1June2010
354-33-6    /754-12-1     LJ6   -1.1131100  0.00000000   0.0000000  
1.0000000   1.0000000   0.0000000
                          TC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
!
?R32     /R1234yf
?Honeywell - Ryan 1June2010
75-10-5     /754-12-1     LJ6  -31.7963500  0.00000000   0.0000000  
1.0000000   1.0000000   0.0000000
                          TC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
                          VC1    0.0000000  0.00000000   0.0000000  
0.0000000   0.0000000   0.0000000
!

Am 05.11.2015 um 12:54 schrieb Ian Bell:
> Interesting. What data are you comparing against, and have you alerted
> Eric Lemmon of refprop? I have been involved in fitting new interaction
> parameters for most of the binaries forming these mixtures and I would be
> keen to have good data to compare against for a multi-component mixture.
