### ISSUE TITLE
Failure within MEX

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#855]
Updating from 5.1.1 to the latest 5.1.2dev breaks C++ SFunctions. [Fluid R245fa]
Using BICUBIC&HEOS backend, now I get an error complaining about `calc_conductivity_contributions()` not implemented.
Using HEOS, Matlab now dereferences a null pointer somewhere and then crashes.
I'm sorry I cannot give more details but debugging Matlab is really a pain.

**Comment by ibell** [comment]
Can you please provide some sample code demonstrating the problem?
Otherwise I have no idea where to start with debugging.

**Comment by Astrinus** [comment]
Could you wait for a while? I have rolled back to 5.1.1 for now, since we are a
bit in a hurry. I'll try to make a minimal example as soon as possible.

Il 28/10/2015 19:05, Ian Bell ha scritto:
> Can you please provide some sample code demonstrating the problem?
> Otherwise I have no idea where to start with debugging.
>

**Comment by ibell** [comment]
I'm in no rush, so take your time.

**Comment by Astrinus** [comment]
The problem disappeared in the meantime. Ghost bug?

**Comment by ibell** [comment]
Can you close the issue?

**Comment by Astrinus** [comment]
Ok. If it will reappear I'll reopen this issue.
