### ISSUE TITLE
Brine and solutions

### ISSUE THREAD

**Issue by spada9** [CoolProp/CoolProp#856]
Hi,
Is it possible to calculate properties of brine and solutions in Excel?
If yes, can you please give me an example of calling density for MEG-20% solution?
Thank you very much

**Comment by ibell** [comment]
Have you tried the sample spreadsheet for excel?  In there is an example of
doing exactly what you ask for.

Basically you need to put something like this in your cell:

=PropsSI("D","T",300,"P",101325,"INCOMP::MEG[0.5]")

**Comment by jowr** [comment]
What is wrong with cell C13 in the example file? You only need to change the `V` to `D`...

`=PropsSI("V","T",300,"P",101.325,"INCOMP::MEG[0.2]")`
becomes 
`=PropsSI("D","T",300,"P",101.325,"INCOMP::MEG[0.2]")`

**Comment by ibell** [comment]
There are also lots of documentation here:
http://www.coolprop.org/fluid_properties/Incompressibles.html

**Comment by jowr** [comment]
can this be closed?

**Comment by spada9** [comment]
thank you very much, I haven't seen that example file.
