### ISSUE TITLE
Using fluid Novec 649

### ISSUE THREAD

**Issue by LORENZOTOCCI** [CoolProp/CoolProp#857]
Hi guys,

I am developing an ORC code in Matlab using CoolProp as the organic fluid properties.
I would like to test the fluid Novec 649 which, from the CoolProp website, seems to be named Novec1230.
However, when trying to call it in the code, Matlab would warn that the fluid is not in the fluid library.
Does anyone know how to fix this problem?
Thanks
Lorenzo

**Comment by ibell** [comment]
Novec649 is implemented in CoolProp.  You should be able to use the fluid
name Novec649, but it was added recently so you will have to use the
nightly build rather than the version 5.1.1 release.

This should work in MATLAB when you are set up properly:

CoolProp.PropsSI('T','P',101325,'Q',0,'Novec69')

**Comment by LORENZOTOCCI** [comment]
That is what I suspected..I am using the 5.1.1 Coolprop version now.
Can you please send me the link where I can download the latest version?
Thanks a lot for your help
Lorenzo

**Comment by ibell** [comment]
http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#pre-compiled-binaries,
second link in the first paragraph

**Comment by LORENZOTOCCI** [comment]
Thank you Ian.
I downloaded it, placed it in my matlab folder but matlab is still not recognizing the fluid.
Any advice?
Lorenzo

**Comment by ibell** [comment]
Can you run the example matlab file?  What do you get?  Does it all work
properly? Perhaps you still have the old CoolProp on your MATLAB path?
Make sure to remove the old one, or remove its directory from the MATLAB
path.

**Comment by LORENZOTOCCI** [comment]
I get this message when I run the example...

Undefined function or variable 'CoolPropMATLAB_wrap'.
I tried to delete every coolprop version I had on my pc except for the latest version but I keep receiving this message when I run the example...
Lorenzo

**Comment by ibell** [comment]
What does your folder layout look like? Seems like path layout is wrong.

**Comment by LORENZOTOCCI** [comment]
Now it is working. My folder layout was, in fact wrong.
My only concern now is with the way you recall thermodynamic properties in the code.
Since now you use the statement "CoolProp.PropsSI" instead of "PropsSI", is there a faster way to fix it other than modifying manually every line of the code?
Thanks for your help
Lorenzo

**Comment by LORENZOTOCCI** [comment]
Also, why the thermal oils are not working anymore in this latest version?
Thanks
Lorenzo

**Comment by jowr** [comment]
How about hit 1 or 2 from :
https://www.google.dk/search?q=search+replace+matlab#q=find+and+replace+matlab+code+shortcut

What are thermal oils? Did you read the docs? Did you maybe use version 4 before?

**Comment by LORENZOTOCCI** [comment]
Yes I was using version 4 before. Thermal oil are listed among the incompressible fluids on the website (TVP1, T66, T72 etc.). 
What docs am I suppose to read to avoid basic questions?
Thanks
Lorenzo

**Comment by ibell** [comment]
Well, I guess start with www.coolprop.org, and I guess the places you
probably want to go are here:

http://www.coolprop.org/coolprop/HighLevelAPI.html#high-level-api

and

http://www.coolprop.org/fluid_properties/Incompressibles.html#pure

and for MATLAB, here:

http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#matlab
