### ISSUE TITLE
coolprop.org blocked - coolprop.sourceforge.net still working

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#860]
Recently, coolprop.org appeared on some black lists for servers that are not trustworthy. Does anyone have an idea what is going on? @Rod-Persky : Do you still own the domain? Where is it hosted?

**Comment by Rod-Persky** [comment]
Hi Jorrit,

I gave Ian the login details, I don't think we had an email setup. I can look into this but I don't know why this should be the case.

Kind Regards,
Rod

**Comment by jowr** [comment]
Thanks for the quick response. I do not think that this is related to email traffic, it seems that the IP somehow is associated with some other funny activities. I can see that you use a domain-cloaking service and maybe there are many domains hosted with the same IP and maybe one of them has been involved in some weird activity - who knows.

**Comment by Rod-Persky** [comment]
Hi Jorrit,

Looks like I’ve still got the login information. I think there is a ???@coolprop.org email address with google, but there is nothing special on the domain. The privacy is just so my personal details are not released on the whois. I’ve placed a screenshot of the DNS entries below, I will contact you on Skype.

**Comment by Rod-Persky** [comment]
Jorrit, could you indicate some of the locations that are blocked. We’ve had problems with hosting in some countries with shared hosting. My best suggestion to avoid this is to host the site on a ramnode / VPS instance with a ‘clean’ IP.

Please advise if I can be of further assistance.

Kind Regards,
Rod

**Comment by Rod-Persky** [comment]
@ibell did you want to have a chat over this one?

**Comment by jowr** [comment]
No worries, I do not have the time now. Could attach the images via the website? You cannot attachments in replies to github threads.

**Comment by ibell** [comment]
I can get to CoolProp.org on my phone...

**Comment by jowr** [comment]
It is no problem to get to the site. The problem is that the domain coolprop.org seems to appear on several blacklists. Some of the products sold via infoblox.com mark the site as not trustworthy, which is a problem for people in networks that use such services. 

I am quite sure that it is not the content that is the problem because coolprop.sourceforge.net does not appear on these lists.

**Comment by Rod-Persky** [comment]
I've pasted the DNS info below, I don't think there is much interesting there.

<img width="610" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/770327/11047163/cd67cc22-877c-11e5-8373-ae7e1e6f04c4.png">

**Comment by Rod-Persky** [comment]
It would be helpful to know why infoblox has indicated the site as unsafe.

**Comment by jowr** [comment]
Unfortunately, that information is not available to me... Did you consider removing the A-record? I am not an expert in DNS setup, but you might be able to simplify the setup by removing the A-record and the CVS record. If there is no A-record, the DNS system tries to resolve the CNAME, which then gives the correct IP. 

Why does coolprop.org not point to coolprop.sourceforge.net?

**Comment by Rod-Persky** [comment]
I followed the instructions on source forge for hosting projects http://sourceforge.net/p/forge/documentation/Custom%20VHOSTs/ but looks like it's changed since originally put together. I will update the records.

**Comment by jowr** [comment]
Note that the docs use vhost as a placeholder for the project name. You have to put in two entries: 
```
CNAME   coolprop.org       coolprop.sourceforge.net
CNAME   www.coolprop.org   www.coolprop.sourceforge.net
```
I still recommend to remove the CVS entry.

**Comment by ibell** [comment]
What's up with this issue?  I have yet to see any problems on my side.  Are there still unresolved issues?

**Comment by jowr** [comment]
Nothing changed. We are still blacklisted by Infoblox and coolprop.org is thus not accessible from networks that use Infoblox' security products, for example every machine in the *.dtu.dk and *.ipu.dk namespace.
It is not a big deal, but I am tired of receiving emails from students and colleagues telling me that our homepage is broken...

**Comment by Rod-Persky** [comment]
There is no reason for infoblox to have blacklisted the website. The only reason may be that the IP address is blocked because someone hosted a nasty on that IP address.

**Comment by jowr** [comment]
OK, let us close this for now.
