### ISSUE TITLE
Speed of Sound calculation in BICUBIC Tables

### ISSUE THREAD

**Issue by davidpasquale** [CoolProp/CoolProp#863]
Hi,
I get
ValueError: calc_speed_sound is not implemented for this backend
when I perfom the calculation os the speed of sound using Bicubic tables.
Thank you!

**Comment by ibell** [comment]
Sorry see my other comment.  It is implemented, you just need code from nightly instead of from 5.1.1.

**Comment by ibell** [comment]
Please close once you can use the nightly build and confirm it works.

**Comment by ibell** [comment]
Please reopen if you can't get it to work.
