### ISSUE TITLE
Enhancement factor

### ISSUE THREAD

**Issue by bru32** [CoolProp/CoolProp#864]
I think that the application of the enhancement factor in CoolProp may be incorrect.

From HAProps_Aux('f',300,101325,0.0),
I can see that the correct value is calculated.

This gives f=1.0043
(agrees with the table published by Gatley).

BUT, if I calculate it from the humidity definition, I get a different value.

wa = Ra f pv / (Rw (pa - f pv))

therefore
f = wa pa / (0.621945 + wa) / pv

where
  wa = HAPropsSI('W',   'P', 101325, 'T', 300, 'RH', 1.0)
  pv = HAPropsSI('P_w', 'P', 101325, 'T', 300, 'RH', 1.0)

this gives f=1.000
Looks like the enhancement factor is not actually used!

Ref:
  Don Gatley "Understanding Psychrometrics", 2nd ed.
  ASHRAE HOF 2009
  ASHRAE RP-1485 (FINAL REPORT)

# Here is my Python test code.
```
from CoolProp.CoolProp import HAProps_Aux, HAPropsSI

# check the value of f
f = HAProps_Aux('f', 300, 101325, 0.0)[0]
print 'f =', f, ' from HAProps_Aux'

# now calc f from humidity definition
wa = HAPropsSI('W',   'P', 101325, 'T', 300, 'RH', 1.0)
pv = HAPropsSI('P_w', 'P', 101325, 'T', 300, 'RH', 1.0)

f = wa*101325 / (0.621945+wa) / pv
print 'f = ', f, ' from  wa = Ra f pv / (Rw (pa - f pv))'
```

**Comment by ibell** [comment]
Actually I believe we are doing everything correctly, and I get things to work out as expected:

![untitled](https://cloud.githubusercontent.com/assets/1859947/11166179/305429f8-8ae7-11e5-8c4e-95846a686f06.png)

I think the issue is that you are using the partial pressure of water instead of the saturation pressure of pure water as in my example.

Here is my code block:
``` python
import CoolProp
p = 101325
T = 300
phi = 0.5
epsilon = 0.621945
p_ws = CoolProp.CoolProp.PropsSI('P','T',T,'Q',1,'Water')
W = CoolProp.CoolProp.HAPropsSI('W','T',T,'P',p,'R',phi)
f = W*p/(epsilon*(W/epsilon+1)*phi*p_ws)
f
```
