### ISSUE TITLE
Hide tabular generation outputs when debug_level=0

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#865]
In a user point of view, the outputs redirected to the standard output window are usually not necessary and can cause this generation to be quite slow (may be more marked on windows).
Wouldn’t it be more convenient to only display them if a debug_level>0 is involved?

I think this option is already built, but would need to change the true to false on this [line](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Tabular/TabularBackends.cpp#L193).

**Comment by ibell** [comment]
Good idea.  At one point it was like that, but evidently no longer.  I'll
fix that.
