### ISSUE TITLE
PropsSI fails to converge for enthalpy of 100% quality water

### ISSUE THREAD

**Issue by BenReish** [CoolProp/CoolProp#867]
ValueError: Maxwell solver did not converge after 30 iterations;  rhoL: 55346.42854667582 rhoV: 1.259102527774025 error: 5.05751e-009 dvL/vL: 8.43812e-015 dvV/vV: 2.25038e-014 pL: 3113 pV: 3113 : PropsSI("H","T",297.8463541,"Q",1,"Water")

Happens repeatedly around 300 K (I'v seen it fail near 330 K).  I am using Python 2.7 with CoolProp 5.1.1.

**Comment by ibell** [comment]
Hi! I think you need to use the 5.1.2dev version of CoolProp, we are about
to release 5.1.2, until we do, install the python wrapper by following the
instructions here:
http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html#automatic-installation
 You want the second one which installs from the development server.  We
relaxed the convergence tolerance which should help with this issue.

**Comment by BenReish** [comment]
That seems to work. Thanks for the quick response.
