### ISSUE TITLE
Fix fortran builds on buildbot

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#868]
@jowr, it seems the failures in this builder: http://www.coolprop.dreamhosters.com:8010/builders/Fortran-executable-osx-64bit-GCC-ExternC are due to a bug in gcc 4.9.  I updated my gcc to 5.2 using ``brew install gcc`` and now it builds the static library just fine.  Want to update the slave?  Should only take a few minutes I think.

**Comment by ibell** [comment]
Also, for the windows one, I suspect that your TDM-GCC is not including gfortran, and thus, when it calls gfortran it is using another gfortran on your computer?  Or something else?  When I use TDM-GCC on my computer and run exactly the steps shown in the slave, it works fine.

**Comment by jowr** [comment]
But the Windows one is called MinGW. I am quite sure that it also is MinGW that is used. I'll have a look.

**Comment by jowr** [comment]
I think OSX works now, but Windows still has some name mangling issues. Somehow the static library exports only `_propssi` and the binding to `PropsSI` does not work properly.
