### ISSUE TITLE
Fix javascript builder on buildbot

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#869]
@jowr, if you are going to take over the javascript builder on your machine, could you please update the environmental variables to get it building properly?  I'm readying for 5.1.2 release (finally), and we need to get the javascript builder to work again.

**Comment by jowr** [comment]
Just go ahead and remove my machine from the `master.cfg`. I played with the docker images and javascript was one of the test balloons. This should not keep us from releasing 5.1.2

**Comment by ibell** [comment]
Will do, thanks for the info.  What slave was it building on before?
