### ISSUE TITLE
Issues with Cp, Cv, u, and viscosity with QT_INPUTS where Q=0 or 1 (xxx&REFPROP backend)

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#871]
I'm using the latest nightly build to try to move forward on computing bubble point and dew point properties for mixtures. I begin by trying to find dew point properties for R438A at 244.3 K using TTSE and REFPROP:

    AbstractState stateTab = AbstractState.factory("TTSE&REFPROP", "R438A.mix");
    stateTab.update(input_pairs.QT_INPUTS, 1.0, 244.3);
    stateTab.umass() -> Exception: "Pointer to vector y is unset in is_inside"
    stateTab.cpmass() -> Exception: "Two-phase not possible for cpmolar currently"
    stateTab.viscosity() -> Exception: "muV is invalid"

I tried to work around these issues by moving the calculation point just to the right of the vapor dome, then using PT inputs to recalculate:

    AbstractState stateTab = AbstractState.factory("TTSE&REFPROP", "R438A.mix");
    stateTab.update(input_pairs.QT_INPUTS, 1.0, 244.3);
    stateTab.update(input_pairs.PT_INPUTS, stateTab.p(), stateTab.T() + 0.001);
    stateTab.umass() -> succeeds
    stateTab.cpmass() -> succeeds
    stateTab.viscosity() -> Exception: "Cell to TTSEBackend::evaluate_single_phase_transport must have four valid corners for now"

Using BICUBIC and REFPROP, the latter workaround often works to calculate all the properties at the dew point, but doesn't at other times. I seem to have less luck at the bubble point, as we see here:

    AbstractState stateTab = AbstractState.factory("BICUBIC&REFPROP", "R438A.mix");
    stateTab.update(input_pairs.QT_INPUTS, 0.0, 266.154);
    stateTab.umass() -> Exception: "Pointer to vector y is unset in is_inside"
    stateTab.cpmass() -> Exception: "Two-phase not possible for cpmolar currently"
    stateTab.viscosity() -> Exception: "muV is invalid"

And again trying the workaround:

    AbstractState stateTab = AbstractState.factory("BICUBIC&REFPROP", "R438A.mix");
    stateTab.update(input_pairs.QT_INPUTS, 0.0, 266.154);
    stateTab.update(input_pairs.PT_INPUTS, stateTab.p(), stateTab.T() - 0.001); -> Exception: "Cell is invalid and has no good neighbors for p = 422161 Pa, T= 266.819 K"

Using: C#, 11/16 nightly build

**Comment by ibell** [comment]
Fixed umass = hmass - p/rhomass, not sure what to do about cpmass at saturation, that's a trickier one.  Viscosity should be fixable too.

**Comment by ibell** [comment]
On second thought, with REFPROP this is a bit trickier since REFPROP doesn't offer the chance to evaluate transport properties as the phase envelope is constructed.  Might have to stick to the workaround for now.

**Comment by ibell** [comment]
Ok, got this working:
``` c++
std::vector<std::string> backends;
    backends.push_back("TTSE&REFPROP");
    backends.push_back("REFPROP");
    for (int i = 0; i<2; ++i){
        shared_ptr<CoolProp::AbstractState> stateTab(CoolProp::AbstractState::factory(backends[i], "R438A.mix"));
        stateTab->update(CoolProp::QT_INPUTS, 1.0, 244.3);
        std::cout << "umass: " << stateTab->umass() <<std::endl;
        std::cout << "cpmass: " << stateTab->cpmass() <<std::endl;
        std::cout << "cvmass: " << stateTab->cvmass() <<std::endl;
        std::cout << "viscosity: " << stateTab->viscosity() <<std::endl;
        std::cout << "conductivity: " << stateTab->conductivity() <<std::endl;
    }
```
yields
```
umass: 346586
cpmass: 803.382
cvmass: 688.494
viscosity: 1.01175e-005
conductivity: 0.00978884
umass: 346552
cpmass: 803.086
cvmass: 688.332
viscosity: 1.01175e-005
conductivity: 0.00978918
```
