### ISSUE TITLE
El Cap issues

### ISSUE THREAD

**Issue by murenrb** [CoolProp/CoolProp#872]
Hey CoolProp team,
I am not sure if this is the correct approach to take, but I have been having an issue that Jorrit has been helping with over on the librefprop github issues list. It appears that this issue may actually be a cool prop issue and not a librefprop issue. So I wanted to move it over to this list. 

The full conversation can be found at: https://github.com/jowr/librefprop.so/issues/35

The long of the short of it is that updating to El Cap somehow caused Refprop to no longer be usable by my CoolProp calls. At first I thought this was a librefprop issue and thus posted the issue on the other page. However, after updating gfortran librefprop is not currently working, but CoolProp still can't seem to call refprop. I have tried uninstalling and reinstalling coolprop, but that did not help. 

There appear to be folks using El Cap with librefprop via coolprop, so it seems like something that is particular to my machine. I just have no idea what it could be. It all worked fine right before I updated so there must have been some kind of system file change that moved where certain calls are looking. I just have no idea what those calls might be. 

Let me know if you have any thoughts, if we should just keep this discussion in the librefprop directory or if we should move this here permanently and close the librefprop version. 

Thanks!

**Comment by jowr** [comment]
Honestly, I have no idea. I recently installed librefprop and CoolProp from sources using the most recent HPC gcc and gfortran compilers and it works out of the box. That was on a clean El Capitan installation with only XCode and the command line tools installed after the OS installation. 

Did you upgrade your system? Is there anything the could keep CoolProp from getting to librefprop? How about folder and file permissions? I had some trouble with homebrew breaking permissions earlier.

**Comment by jowr** [comment]
So here is what worked for me:
```shell
# Prepare librefprop.so with fortran sources and fluid files
cd librefprop.so.git
make clean
make 
sudo make install
cd ../
curl -o conda.sh https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
chmod +x conda.sh
./conda.sh
${HOME}/miniconda2/bin/conda create -n CoolProp pip cython numpy scipy pandas matplotlib
source ${HOME}/miniconda2/bin/activate CoolProp
git clone --recursive https://github.com/coolprop/coolprop coolprop.git
cd coolprop.git/wrappers/Python
python setup.py install
cd ${HOME}
python -c "import CoolProp; print CoolProp.__version__"
python -c 'import CoolProp.CoolProp  as CP; print CP.PropsSI("T","Q",0,"P",1e5,"REFPROP::Water")'
```

**Comment by murenrb** [comment]
The problem is fixed! El Cap has a new feature called System Integrity Protection that apparently stops all programs from being able to change the root folder. When you install clean into El Cap this is all fine because it works out the permissions, but updating didn't work. Something like this. Honestly I don't really understand it. 

But the good news is you can disable it in the restore boot menu. After I did this everything worked. 

This is not really a great fix as not SIP is not running on my machine, but I don't really feel that exposed. Anyway, let me know if this makes sense.

**Comment by jowr** [comment]
Well, one thing more to remember for us. At least we have it documented in this issue...
