### ISSUE TITLE
Tabular data cannot be generated for R503.mix with xxx&REFPROP backend

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#874]
When attempting to generate tabular data for R503 using either the TTSE or bicubic & REFPROP backends, it seems that execution gets lost in the weeds somehow:

    AbstractState state = AbstractState.factory("BICUBIC&REFPROP", "R503.mix");

The CPU revs up and stays there indefinitely, but no console output is produced and no data files are ever generated.

Using: C#, 11/16 nightly build

**Comment by jowr** [comment]
Have you tried to enable the debugging output? CoolProp should tell you what it is doing...

**Comment by mapipolo** [comment]
Thanks for that--I had never used CoolProp's debug output. Here's what it's up to:

    AbstractState::factory(BICUBIC&REFPROP,[ R503.mix ])
    AbstractState::factory(REFPROP,[ R503.mix ])
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:270: Successfully loaded REFPROP fluid: R503.mix
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
    Table loading failed with error: Could not load tables
    Tabular directory size is 0 GB
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
    ***********************************************
     Single-Phase Table (R23&R13)
    ***********************************************
    x: -1.#IND y: -1.#IND
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
     HmolarPmolar: [PHFLSH error 242] dew point calculation did not converge:  [SATP error 148] iteration for saturation state did not
     converge; P =         NaN MPa.
    x: -1.#IND y: -1.#IND
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
     HmolarPmolar: [PHFLSH error 242] dew point calculation did not converge:  [SATP error 148] iteration for saturation state did not
     converge; P =         NaN MPa.
    x: -1.#IND y: -1.#IND
    ..\src\Backends\REFPROP\REFPROPMixtureBackend.cpp:207: The current fluid can be reused; R503.mix and R503.mix match
     HmolarPmolar: [PHFLSH error 242] dew point calculation did not converge:  [SATP error 148] iteration for saturation state did not
     converge; P =         NaN MPa.
    ...

It continued for some 10 minutes like this before I shut it down.

**Comment by ibell** [comment]
REFPROP failure it seems, not much we can do about that.

**Comment by ibell** [comment]
Sorry but this is a REFPROP bug, not a CoolProp bug, you'll have to contact Eric Lemmon at NIST.  There is nothing we can do unfortunately.
