### ISSUE TITLE
json property files with Python

### ISSUE THREAD

**Issue by bru32** [CoolProp/CoolProp#876]
I very much like the json data files and would like to evaluate these directly with Python.

Is there any Python sample code that reads these json files and does evaluation?
If not, which is the appropriate cpp file?

**Comment by jowr** [comment]
Hi, what about these files? 
https://github.com/CoolProp/CoolProp/blob/master/dev/clean_up_json.py
https://github.com/CoolProp/CoolProp/blob/master/dev/generate_headers.py

**Comment by bru32** [comment]
OK, thanks.  I did see these.  In particular, I'm looking to calculate properties directly from the json source files. This would involve reading the coefficients and the equation form. So, each of the equations need to be defined in the Python code.  I will give it a go and post my attempt.

**Comment by jowr** [comment]
OK, that sounds more advanced than the things we have done in Python. Good luck and I am looking forward to see what you come up with!

**Comment by thorade** [comment]
Here is some code for a very simple example. You'll have to adapt the pathes:

```python
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import os.path
import json

fluid = 'n-Butane'
jExt = '.json'
CPFluidDir = os.path.abspath(r'C:\Users\mthorade\Documents\git\CoolProp\dev\fluids')
fluidPath = os.path.join(CPFluidDir,fluid + jExt)
# print(fluidPath)

jD = json.load(open(fluidPath, 'r'))
print(jD['NAME'])
pS_r = jD['ANCILLARIES']['pS']['reducing_value']
TS_r = jD['ANCILLARIES']['pS']['T_r']
TSmin = jD['ANCILLARIES']['pS']['Tmin']
TSmax = jD['ANCILLARIES']['pS']['Tmax']
pSn = jD['ANCILLARIES']['pS']['n']
pSt = jD['ANCILLARIES']['pS']['t']

# Testing ancillary p=p(T)
nPoints = 10000
TS_sat = np.linspace(TSmin, TSmax, num=nPoints)
tauS = TS_r/TS_sat
ThetaS = 1-TS_sat/TS_r
pS_sat = np.empty(nPoints)
for idx in range(0,nPoints):
  pS_sat[idx] = pS_r*np.exp(tauS[idx]*sum(pSn*ThetaS[idx]**pSt))

plt.plot(TS_sat, pS_sat)
```

**Comment by thorade** [comment]
The equation (in this case for pS) ist not read from the json file. There sometimes is a field `description` that contains something like an equation, but is is only available for the ancillaries I believe. Especially for the complicated equations you will only have a field `type` and then somewhere in the C++ code there is some condition to use the corresponding equation.

**Comment by ibell** [comment]
What is your use case?  At the moment, we use CoolProp to do all the heavy
lifting, and I don't see an obvious reason why you would want to evaluate
properties from the JSON files yourself.  The JSON files are an internal
data structure, and are not guaranteed to be stable and you should not rely
on their form not changing.

That said, you are of course welcome to play with them and parse them, and
evaluate properties from them, but why not just use CoolProp?

**Comment by bru32** [comment]
thorade, thanks for the sample code. I managed to get some functions working.
Ian, you may have seen the refrigerant property curve fits done by Cleland. He published a few selected refrigerants.  I fitted his models to the whole Refprop 8 set of fluids and mixtures.  It is not as accurate as CoolProp and does not cover the whole range but for normal vapor compression system modelling is very fast and accurate enough.  Now, I see that you use rational functions.  So, my interest here is to experiment and compare your curve-fits to those of Cleland. (I also like to play with Python!)

**Comment by bru32** [comment]
Here is my initial Python code.

'''
CoolProp Fluids
Test fluids json files
Bruce Wernick, 12 Nov 2015
'''

import os
import json
import numpy as np


k0 = 273.15

def polyeval(a,x):
  'polynomial eval using Horner method'
  p=0.0
  for c in reversed(a):
    p = c + p * x
  return p

def rational_polynomial(a, b, x):
  'rational polynomial of A(x)/B(x)'
  return polyeval(a,x)/(polyeval(b,x))

def check_hL(dat):
  'calculate the hL curvefit from Tmin to Tmax'
  hL = dat['ANCILLARIES']['hL']
  type = hL['type']
  if type != 'rational_polynomial':
    print type
    return
  A = hL['A']
  B = hL['B']
  Tmin = hL['Tmin']
  Tmax = hL['Tmax']
  wa = dat['EOS'][0]['molar_mass']
  Tc = dat['STATES']['critical']['T']
  hs_anchor = dat['EOS'][0]['STATES']['hs_anchor']['hmolar']
  for i in range(60):
    t = Tmin + i*(Tmax-Tmin)/(60-1)
    print '%0.1f, %0.2f' % (t-k0, 1e-3*(rational_polynomial(A,B,t)+hs_anchor)/wa)


def keys(d, s):
  for k, v in d.items():
    if isinstance(v, dict):
      for w in keys(v, s):
        yield w
    else:
      if k == s:
        yield v

types = set()

path = 'CoolProp.sources/dev/fluids/'
for _, _, fnames in os.walk(path):
  # get all file names in path
  for fn in fnames:
    if os.path.splitext(fn)[1] == '.json':
      with open(path+fn, 'r') as fp:
        # load the json file
        dat = json.load(fp)
        # search for all "type" keys in dat
        for item in keys(dat, 'type'):
          types.add(item)
print 'Unique types in all refrigerant json files'
for item in types:
  print item

with open(path+'R22.json', 'r') as fp:
  dat = json.load(fp)
check_hL(dat)


It searches all the json files and extracts this short list of unique function names.

Simon
pV
polynomial_in_Theta
collision_integral_powers_of_Tstar
empirical
polynomial_in_Tr
polynomial
pL
rational_polynomial
rhoLnoexp
collision_integral
ECS
kinetic_theory
modified_Batschinski_Hildebrand
polynomial_and_exponential
simplified_Olchowy_Sengers
Rainwater-Friend
eta0_and_poly
powers_of_T
friction_theory
rhoV
powers_of_Tr
ratio_of_polynomials

So, to be able to do the calcs directly in Python, I would need to write functions for each of these.
I may not go this far but I will try the bub and dew pressure, temp and enthalpy.

By the way, I'm currently modelling a hybrid dx / evap cooler. For this, I use CoolProp PropsSI.

**Comment by ibell** [comment]
By the way, there is a polyval function in numpy that uses Horner's method
:
http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.polyval.html

**Comment by bru32** [comment]
Thanks, I did see that but I think it has the coefficients from high to low order.  Also, after reading the article of Eli Bendersky, I did a bit of experimenting with speeds and found that this was about as fast as you can get with standard Python.
http://eli.thegreenplace.net/2010/03/30/horners-rule-efficient-evaluation-of-polynomials

**Comment by ibell** [comment]
Yes, well you can always reverse the order of your coefficients :)  Almost
certainly numpy will be much faster than python, though you should test
that of course.

**Comment by thorade** [comment]
I believe no action from the developers is required in this issue.
Closing for now, feel free to reopen or file a new issue.
