### ISSUE TITLE
low-level interface MATLAB using shared library

### ISSUE THREAD

**Issue by EdoMacchi** [CoolProp/CoolProp#880]
Following the discussion on the forum "MATLAB wrapper performances" as agreed I will open this issue as a reminder for a sample code that shows how to use the low-level interface from the high-level interface from MATLAB (loading CoolProp as a shared library).

Thank you!

**Comment by ibell** [comment]
Can you please put together a MATLAB function using the new functions?  Just like the example that will be up here soon: http://www.coolprop.org/dev/coolprop/LowLevelAPI.html#access-from-high-level-interface

**Comment by EdoMacchi** [comment]
Right now I can prepare it but I cannot test it. Is it ok if I send it to you tomorrow morning?

**Comment by ibell** [comment]
Yes that is fine, there is no rush, but I'd appreciate your help.
