### ISSUE TITLE
Installation issue with Matlab wrapper on Windows 64bit

### ISSUE THREAD

**Issue by auredor** [CoolProp/CoolProp#881]
Hello, I've installed matlab wrapper 5.1.1 as per recommandation. Repository structure is the same and I added the path of folder and subfoler to Matlab. I did a try with the latest version as well.
However, It looks like functions are not known or some arguments are missing.

I triyed this :
CoolProp.PropsSI('T','P',101325,'Q',0,'Water') 
Undefined function or variable 'CoolPropMATLAB_wrap'.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(312,varargin{:});

I looked at the issue #806. The errors are very similar but my files are as per 
http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#pre-compiled-binaries

Thanks

**Comment by ibell** [comment]
Can you describe what you did to resolve the problem please?
