### ISSUE TITLE
Superheat and sub-cooling correction

### ISSUE THREAD

**Issue by bru32** [CoolProp/CoolProp#884]
I wonder if you folk have any experience with this problem?

You can calculate the compressor cooling and power with the ARI polynomial. This is based at certain specified reference conditions of SC and SH.

For different conditions of SC and SH, I use CoolProp to calculate points 1,2 and 3 of a simple cycle at both reference and design values of SC and SH. 
(1=suction, 2=discharge, 3=liquid)

Then, I calculate correction factors for duty and power as follows:
cooling: fc = (h2-h3)design / (h2-h3)ref
power: fp = [d1*(h2-h1)]design / [d1*(h2-h1)]ref

My factors are close but don't agree exactly with various compressor manufacturer software.

The only other information I have found on the subject is a 1994 article by Kevin Wu of Bristol Compressors.  Wu shows a plot of duty factor vs SH with SC as a parameter. But, as an example, if I use the Danfoss Foresee program, this doesn't seem to be correct.

Do you know how the duty of the ARI polynomial is corrected for different values of superheat and sub-cooling?

**Comment by thorade** [comment]
Are you referring to this article? http://docs.lib.purdue.edu/icec/972/
Adding a link to the correct article makes it easier for others to help you.

Using this issue tracker here, you will reach mainly the developers of the software. 
If you want to reach a broader audience, you can also try the Google Group for CoolProp Users:
https://groups.google.com/forum/#!forum/coolprop-users
This might also be adequate, as it seems to be an issue with some application, not an issue with CoolProp itself.

**Comment by ibell** [comment]
Bruce, this is far outside the scope of CoolProp, a better bet would be
ACHP, which I was also involved in: https://github.com/TSTK/ACHP
