### ISSUE TITLE
ALTERNATE_REFPROP_PATH ignored in low-level interface

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#886]
From @mayersre:

The low level interface does not listen to the ALTERNATE_REFPROP_PATH.
Can I somehow tell Coolprop where to look for refprop?

my example below looks into /refprop instead, I did strace on it with R407F.MIX

**Comment by ibell** [comment]
I think that commit might have fixed this issue.  Please confirm and close if it works now.

**Comment by mayersre** [comment]
If I create a lowercase copy of all files with uppercase names in fluids and mixtures it works now with this fix.

**Comment by ibell** [comment]
Weird.  That doesn't make sense to me.

You mean to say that if you have predefined mixtures like R410A.MIX it
doesn't work, but r410a.mix does with your alternate path?

**Comment by mayersre** [comment]
It is very wired

let me find some more facts around this issue then I send you some
strace outputs.

Reiner

Am 02.12.2015 um 16:13 schrieb Ian Bell:

**Comment by ibell** [comment]
Any update?

**Comment by mayersre** [comment]
By end of next week

Am 12.12.2015 um 05:26 schrieb Ian Bell:

**Comment by ibell** [comment]
I may have fixed a bug or two in the REFPROP backend.  I might have fixed
this issue, but that remains to be seen.

**Comment by mayersre** [comment]
Hi Ian,

this week I will be at the school and teach some guys from the UN. In
the evening
I will have time and I will run a new versio of my Diagram and Steam
table generator
and test it with the latest version in dev ...

I ported it nearly completely to the low level interface now

by thursday latest you should have some feedback from me.

Reiner

Am 13.12.2015 um 05:35 schrieb Ian Bell:

**Comment by ibell** [comment]
Any update?

**Comment by mayersre** [comment]
Yes,

could just reproduce some behaviour ...

observation (only Linux):
If you install in /opt/refprop, link all files in mixtures and fluids
from uppercase to lowercase
it seems to work. I tried on freshly installed ubuntu 14.04

as soon as you run it from anywhere else, case and path becomes an issue.

e.g. I set the
ALTERNATIVE_REFPROP_PATH='/home/mayers/git/kformaug/extern/rp_dupont/'
and Propsi something for R407F.MIX

It is a copy of /opt/refprop and there it works! Afterwards I remove or
unlink /opt/refprop to make
sure my files are taken from the right location
 
it searches in very wired ways for the propane fluid file

5.1.2dev
1a6be5d75aeaea98af09061a21200f525c38f63a

from strace output :
/home/mayers/git/kformaug/extern/rp_dupont/PROPANE
/home/mayers/git/kformaug/extern/rp_dupont/fluids\\PROPANE
/home/mayers/git/kformaug/extern/rp_dupont/PROPANE
/home/mayers/git/kformaug/extern/rp_dupont/fluids/PROPANE
5 x PROPANE
/opt/refprop/fluidsPROPANE
3 x \\refprop\\fluids\\PROPANE
... too many to show all here

so I reduce duplicates ...

$> strace python phdiagramm_v60.py 2>&1 | grep -i propane | grep 'open('
| wc -l
$> 1500

$> strace python phdiagramm_v60.py 2>&1 | grep -i propane | grep 'open('
| grep -i fld | wc -l
$> 384

$> strace python phdiagramm_v60.py 2>&1 | grep -i propane | grep 'open('
| grep -i fld | sort | uniq | wc -l
$> 64

so 1500 stat/open for the propane fluid file with/without extension or
ppf/fld
       384 stat/open for propane.fld sometimes 6 times repeated
uppercase/lowecase/combinations/path's
         64 stat/open unique calls for stat/open on propane.fld
uppercase/lowecase/combinations/path's

it just keeps looking into the wrong place, either a / is missing, a /
is too much or something else is wrong
PROPANE.FLD is in the desired place
/home/mayers/git/kformaug/extern/rp_dupont/fluids/PROPANE.FLD

That is as far as I got ...

Regards
Reiner

Here the 64 unique calls to open

open("c:/Program Files/Refprop/fluids/propane.fld", O_RDONLY) = -1
ENOENT (No such file or directory)
open("c:\\Program Files\\Refprop\\fluids\\propane.fld", O_RDONLY) = -1
ENOENT (No such file or directory)
open("c:/Program Files/Refprop/fluids/PROPANE.fld", O_RDONLY) = -1
ENOENT (No such file or directory)
open("c:\\Program Files\\Refprop\\fluids\\PROPANE.fld", O_RDONLY) = -1
ENOENT (No such file or directory)
open("c:/Program Files/Refprop/fluids/PROPANE.FLD", O_RDONLY) = -1
ENOENT (No such file or directory)
open("c:\\Program Files\\Refprop\\fluids\\PROPANE.FLD", O_RDONLY) = -1
ENOENT (No such file or directory)
open(":fluids:propane.fld", O_RDONLY)   = -1 ENOENT (No such file or
directory)
open("../fluids/propane.fld", O_RDONLY) = -1 ENOENT (No such file or
directory)
open("..\\fluids\\propane.fld", O_RDONLY) = -1 ENOENT (No such file or
directory)
open(":fluids:PROPANE.fld", O_RDONLY)   = -1 ENOENT (No such file or
directory)
open("../fluids/PROPANE.fld", O_RDONLY) = -1 ENOENT (No such file or
directory)
open("..\\fluids\\PROPANE.fld", O_RDONLY) = -1 ENOENT (No such file or
directory)
open(":fluids:PROPANE.FLD", O_RDONLY)   = -1 ENOENT (No such file or
directory)
open("../fluids/PROPANE.FLD", O_RDONLY) = -1 ENOENT (No such file or
directory)
open("..\\fluids\\PROPANE.FLD", O_RDONLY) = -1 ENOENT (No such file or
directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/c:/Program
Files/Refprop/fluids/propane.fld", O_RDONLY) = -1 ENOENT (No such file
or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\c:\\Program
Files\\Refprop\\fluids\\propane.fld", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/c:/Program
Files/Refprop/fluids/PROPANE.fld", O_RDONLY) = -1 ENOENT (No such file
or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\c:\\Program
Files\\Refprop\\fluids\\PROPANE.fld", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/c:/Program
Files/Refprop/fluids/PROPANE.FLD", O_RDONLY) = -1 ENOENT (No such file
or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\c:\\Program
Files\\Refprop\\fluids\\PROPANE.FLD", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/:fluids:propane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/../fluids/propane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\:fluids:propane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\..\\fluids\\propane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/fluids/PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/:fluids:PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/../fluids/PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\fluids\\PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\:fluids:PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\..\\fluids\\PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/:fluids:PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/../fluids/PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\fluids\\PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\:fluids:PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\..\\fluids\\PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/fluids/PROPANE.FLD",
O_RDONLY) = 6
open("/home/mayers/git/kformaug/extern/rp_dupont/opt/refprop/fluidspropane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/opt/refprop/fluidsPROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/opt/refprop/fluidsPROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/propane.fld", O_RDONLY)
= -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\propane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/PROPANE.fld", O_RDONLY)
= -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/PROPANE.FLD", O_RDONLY)
= -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/refprop/fluids/propane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\refprop\\fluids\\propane.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/refprop/fluids/PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\refprop\\fluids\\PROPANE.fld",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont/refprop/fluids/PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/mayers/git/kformaug/extern/rp_dupont\\refprop\\fluids\\PROPANE.FLD",
O_RDONLY) = -1 ENOENT (No such file or directory)
open("/opt/refprop/fluidspropane.fld", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("/opt/refprop/fluidsPROPANE.fld", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("/opt/refprop/fluidsPROPANE.FLD", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("propane.fld", O_RDONLY)           = -1 ENOENT (No such file or
directory)
open("PROPANE.fld", O_RDONLY)           = -1 ENOENT (No such file or
directory)
open("PROPANE.FLD", O_RDONLY)           = -1 ENOENT (No such file or
directory)
open("/refprop/fluids/propane.fld", O_RDONLY) = -1 ENOENT (No such file
or directory)
open("\\refprop\\fluids\\propane.fld", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("/refprop/fluids/PROPANE.fld", O_RDONLY) = -1 ENOENT (No such file
or directory)
open("\\refprop\\fluids\\PROPANE.fld", O_RDONLY) = -1 ENOENT (No such
file or directory)
open("/refprop/fluids/PROPANE.FLD", O_RDONLY) = -1 ENOENT (No such file
or directory)
open("\\refprop\\fluids\\PROPANE.FLD", O_RDONLY) = -1 ENOENT (No such
file or directory)

**Comment by ibell** [comment]
Ok, good, I will figure out what is up with this today.  I suspect its a small bug in where it looks for things.

**Comment by ibell** [comment]
Does this help?  If not, I can do some more debugging on my side.

**Comment by mayersre** [comment]
It is not properly trying a unix path still

this is how I use it Ben Thelens refprop interface in python :

class fluid_ll:
    #
    def __init__(self,RefName,ALTERNATIVE_REFPROP_PATH='/home/mayers/git/kformaug/extern/rp_dupont/'):
        #
        # Ahead of anything setup your refprop
        #
        REFPROP_LIB=ALTERNATIVE_REFPROP_PATH+"librefprop.so"
        source='REFPROP'
        if 'MIX' in RefName or 'mix' in RefName :
            self.Refname=RefName.split('.')[0]
        else :
            self.Refname=RefName
        self.ReferenceOfState='IIR'
        #
        self.DEBUG=True
        #
        rp.setpath(path=ALTERNATIVE_REFPROP_PATH)
        #
        if self.DEBUG : print('refprop_low_level self.Refname = {} '.format(self.Refname))
        self.prop = rp.setup(self.ReferenceOfState, self.Refname,)
        #

**Comment by mayersre** [comment]
it is underscore underscore init underscore underscore

**Comment by ibell** [comment]
I think what we need to do is to provide the complete path to each
component in the mixture if ALTERNATIVE_REFPROP_PATH is provided.
Otherwise, I am not sure that we can ensure that REFPROP will behave
properly.  I don't like this solution much, but it might be the only way.

**Comment by mayersre** [comment]
Is it possible to set a refprop environment before I fire up a coolprop instance
e.G: I fire up three different instances each one pointing to a different refprop?

**Comment by ibell** [comment]
I'm not sure that is possible, in fact within one process you can only load
one copy of a shared library (DLL).  If you load it again, you just get a
pointer to the original DLL.  It's based on the name of the file.  Your
better bet is to do the same with multiple processes.  That's what I've
done for fitting multiple mixtures in parallel with REFPROP.

**Comment by ibell** [comment]
I believe this issue is fixed.  I have used this code on windows, linux, and OSX, and it seems to work as it should in my testing.  Feel free to re-open/comment if it doesn't work for you..
