### ISSUE TITLE
 MSVCP100.dll and MSVCR100.dll dependency issue... 

### ISSUE THREAD

**Issue by acuiko** [CoolProp/CoolProp#889]
Hello,
I found the situation described in the issue #352 is not resolved (after upgrading to coolprop5?)

**Comment by jowr** [comment]
That is a surprise. The libraries should be compiled with the correct settings to remove such dependencies. Can you post an error message or more details?

**Comment by acuiko** [comment]
The error message is "dllnotfounexception". I get it on the fresh windows install. And I have two options to resolve, first is putting those 2 dlls in same folder, and another installing Microsoft Visual C++ 2010 Redistributable Package (x86). Without this coolprop doesnt work.

Also please check dependencywalker result, it clearly shows that these libraries are needed:
![coolprop](https://cloud.githubusercontent.com/assets/11881641/11590218/67b0bd0c-9a97-11e5-8a26-63301dd74eaa.png)

**Comment by ibell** [comment]
Aha - this is the c# DLL, not the "normal" dll.  You're right.
