### ISSUE TITLE
Binary data in the repository

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#890]
Hi all, 
Do you have an opinion on how to handle binary data in the repository? I just noticed that the latest commits by @thorade in the notebook folder consisted of one large file. Should we try to save notebooks as XML without the graphs or what do you think? The repository is about 40 MB at the moment and I am not sure how efficient binary diffs are, but it would be very nice to keep the repository as small as possible.

**Comment by thorade** [comment]
Sorry, I did not intend to commit binary files. My git tool (GitExtensions) showed me textual diffs for every commit, so I thought I was committing text.

**Comment by jowr** [comment]
You might be right. I am not a git magician, and maybe things are just fine. However, my git tool (SmartGit) does not show diffs and just says that the files contain binary data. 

If I am not mistaken, the notebooks are XML (text), but the embedded figures are binary. I normally delete the figures (clear the cells) before I commit a notebook. I think that saves some space, but the drawback is that you cannot see the graphs on, for example, nbviewer. 

Well, I do not have a clear idea about how to handle this. Does anyone have strong feelings regarding this topic?

**Comment by ibell** [comment]
.ipynb are actually json files, with the images embedded as HTML5 binary
code.  Some tools are not quite smart enough to figure out what is going on
with the files and think (incorrectly) that the entire file is binary.
TortoiseGit for instance is smart enough to do textual diffs, github isn't.

I'm of two minds on the whole embedding figures issue. 1) It is definitely
important to keep the size of the main repo to a reasonable level.  40 MB
is large, but ok for the complexity of the project.  2) nbviewer is a
really fantastic tool for viewing notebooks, and you lose the benefits if
the figures are not embedded.

**Comment by ibell** [comment]
Those two files add up to about 500 kb.  Which isn't too bad.  If it get much larger, I would propose you spin them off into another repo.

**Comment by thorade** [comment]
In the future, I will use notebooks without figures for all intermediate steps. Figures can then be added as needed once the notebooks reaches the final form.

**Comment by jowr** [comment]
Yes, I think this is a good compromise. Thanks for having open ears for such requests. Maybe we can try to remember this as some sort of a mutually agreed policy.
