### ISSUE TITLE
Errors that only appear in DLL

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#891]
Sometimes, the Halley solver overshoots and feeds a negative temperature to `HelmholtzEOSMixtureBackend::solver_rho_Tp_SRK` causing a division by zero error. Where should we fix this? In Halley or in SRK?

**Comment by ibell** [comment]
Hard to say - can you send me a minimal example please?

**Comment by jowr** [comment]
Yes, make a DLL and build the ph-tables for CO2. As soon as `j>71` in `CoolProp::SinglePhaseGriddedTableData::build(shared_ptr<CoolProp::AbstractState> &AS)` you will get to a point where Halley's second iteration in p and h causes a call to the PTFlash with T=-50, which then passes all the way through to the power function in the SRK guess value generator.

**Comment by jowr** [comment]
The call is `AS->update(input_pair, v1, v2);` with `HmolarP_INPUTS` and `v1=3522.3474962646915` and `v2=7379602.5760227237`

**Comment by ibell** [comment]
Hmm...  I'm pretty sure I built tables for CO2 yesterday and it was fine.
Is there something funny with your configuration?  There's also the open
ticket #883 that I can't replicate.

That said, I'll look tonight.

**Comment by jowr** [comment]
Yes, the thing is that everything works fine in a statically linked piece of code as in Python and friends, but as soon as I compile a DLL, something funny happens and the system becomes much more picky. 

Please also note that a divison by zero might be more difficult to handle than other exceptions: http://www.battersea-locksmith.co.uk/briefings/divByZeroInCpp.html

**Comment by ibell** [comment]
Oh, this only happens in a DLL?  That's much less enjoyable to debug :)

**Comment by ibell** [comment]
Hmm, can you debug into the dll and see where things are going wrong?  I
can, but I don't have much free time at the moment.

**Comment by jowr** [comment]
Yes, I can and that is where all the infor given above comes from. It is the Halley solver that passes a negative temperature to the SRK-density guess function. This then causes a division by zero issue which does **not** get caught by any of the try catch blocks. 

I wonder if all my issues are related to #893 since @bru32 also uses a DLL and I somehow have the feeling that there might be an issue with the DLLs.

**Comment by ibell** [comment]
Perhaps see http://stackoverflow.com/a/8226455

**Comment by ibell** [comment]
Also interesting would be to know what exception flag was used to build your DLL

**Comment by jowr** [comment]
Well, nothing special I think. I basically use CMake to generate the VisualStudio project and add a custom interface file instead of CoolPropLib.cpp. All the problems reported here refer to the latest master branch. A git pull is part of my workflow...

**Comment by ibell** [comment]
Can you give the complete set of build flags from your vs project generated
by cmake?

**Comment by ibell** [comment]
In #892 I have found it impossible on my computer to get the DLL to fail.

**Comment by jowr** [comment]
As mentioned in #892, this might be related to me calling the DLL from Delphi. I am still trying to gather more evidence.

**Comment by jowr** [comment]
This seems to be a Delphi issue, but it is also related to #877 .
