### ISSUE TITLE
ValueError exception with TTSE/Bicubic interpolation using REFPROP

### ISSUE THREAD

**Issue by rbozinoski** [CoolProp/CoolProp#895]
Using CoolProp(5.1.1) on Linux Mint 17; REFPROP 9.1 and 9.1208

I am running python 2.7 on the latest anaconda (2.4.1) with CoolProp (5.1.1). Following [this example](http://www.coolprop.org/coolprop/Tabular.html ) I tried to do tabular interpolation using REFPROP but I keep getting the following error:

**ValueError: PHI0dll function is not available in your version of REFPROP. Please upgrade**

Initially, a search for the above error pointed me to [this post](https://github.com/CoolProp/CoolProp/issues/830). It seemed like my problem was with my version of REFPROP, which was 9.1. Ian Bell was kind enough to point me to a more recent version (9.1208) which does contain the subroutine PHI0dll. I reinstalled REFPROP (9.1208) on my linux box and followed the latest instructions for [librefprop.so](https://github.com/jowr/librefprop.so). I tested librefprop.so as suggested by jowr using the *fortest* example shipped with librefprop.so and I got the same values as those posted. I also tested out the calling REFPROP through CoolProps *PropsSI* method and everything seems to checkout. It is only when I try to do a tabular interpolation do I get the above error message.

I'm not sure what I'm doing wrong? Also, I'm not sure if the problem is with CoolProp or with my build of librefprop.so or something else I'm not thinking of.

Can anyone offer any suggestions?

Thanks

**Comment by ibell** [comment]
Didn't realize you were on linux.  You'll need to rebuild with 9.12 FORTRAN sources, please email me at my NIST email, and I can send them to you.
