### ISSUE TITLE
Cp, Cv, speed_sound cannot be calculated with QT inputs (Q=0 or 1) and tabular backends

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#899]
Note: this issue may appear similar to #871, but the errors are different.

I'm using the 12/14 nightly build and noticed that Cp, Cv and acoustic velocity can't be calculated with the tabular backend for ammonia. It seems that this may be a new issue (possibly related to commits on #882?), because I'm fairly certain it was working earlier this autumn. All three of the property method calls in the sample code below fail with the message "Output variable for evaluatre is invalid," and no further information is printed to the console with debug level=10. This behavior persists for pure fluids using TTSE and bicubic, HEOS and REFPROP, and across the entire temperature spectrum from Tmin to Tmax. I have checked several refrigerants so far, including ammonia, R22 and propane.

    s = AbstractState.factory("BICUBIC&HEOS", "Ammonia");

    s.update(input_pairs.QT_INPUTS, 1, 263.706);
    s.cpmass();
    s.cvmass();
    s.speed_sound();
    
    s.update(input_pairs.QT_INPUTS, 0, 263.706);
    s.cpmass();
    s.cvmass();
    s.speed_sound();

I wrote the following C# testing code to see if there were any temperatures for which this error *didn't* occur, but it doesn't appear so:

    AbstractState s = AbstractState.factory("BICUBIC&HEOS", "R22");
    double tMax = s.Tmax();
    Console.Clear();
    for (int t = (int)(s.Tmin() + 2); t < (int)(tMax - 2); t++)
    {
    	try
    	{
    		s.update(input_pairs.QT_INPUTS, 1, t++);
    		s.cpmass();
    		s.cvmass();
    		s.speed_sound();
    		Console.WriteLine("Success for T=" + t);
    	}
    	catch (Exception e)
    	{
    		Console.WriteLine(e.Message);
    	}
    }

**Comment by mapipolo** [comment]
I haven't extensively tested this with mixtures and xxx&REFPROP, but the errors produced are different. I can say that with R410A, speed_sound() seems not to work for any temperature. (This may be expected—is speed_sound implemented for mixtures in tabular?)

**Comment by ibell** [comment]
I updated the cp,cv for saturation for mixtures, but not for pure fluids.
I can do that.

**Comment by ibell** [comment]
``` c++
shared_ptr<CoolProp::AbstractState> AS(CoolProp::AbstractState::factory("BICUBIC&HEOS", "AMMONIA"));
    AS->update(CoolProp::QT_INPUTS, 1, 263.706);
    std::cout << AS->cpmass() << std::endl;
    std::cout << AS->cvmass() << std::endl;
    std::cout << AS->speed_sound() << std::endl;
    AS->update(CoolProp::QT_INPUTS, 0, 263.706);
    std::cout << AS->cpmass() << std::endl;
    std::cout << AS->cvmass() << std::endl;
    std::cout << AS->speed_sound() << std::endl;
    std::cout << std::endl;
    AS.reset(CoolProp::AbstractState::factory("HEOS", "AMMONIA"));
    AS->update(CoolProp::QT_INPUTS, 1, 263.706);
    std::cout << AS->cpmass() << std::endl;
    std::cout << AS->cvmass() << std::endl;
    std::cout << AS->speed_sound() << std::endl;
    AS->update(CoolProp::QT_INPUTS, 0, 263.706);
    std::cout << AS->cpmass() << std::endl;
    std::cout << AS->cvmass() << std::endl;
    std::cout << AS->speed_sound() << std::endl;
```
yields
```
2548.98
1848.49
397.663
4566.43
2815.27
1598.13

2548.98
1848.49
397.663
4566.43
2815.27
1598.13
```

**Comment by ibell** [comment]
Same code, switching AMMONIA to R410A.mix and to REFPROP backends, now yields at 280 K:
```
1200.71
851.443
168.242
1558.29
894.075
526.573

1200.71
851.443
168.242
1558.23
894.079
527.145
```

**Comment by ibell** [comment]
I think this resolves the bulk of the issues.
