### ISSUE TITLE
ValueError: PropsSI failed ungracefully

### ISSUE THREAD

**Issue by pascaltobaly** [CoolProp/CoolProp#900]
ValueError: PropsSI failed ungracefully :: inputs were:"P","S",1.9046006877927346e+03,"Q",1.0000000000000000e+00,"CO2"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

**Comment by pascaltobaly** [comment]
also tried this
with same result

ValueError: PropsSI failed ungracefully :: inputs were:"T","S",1.9046006877927346e+03,"Q",1.0000000000000000e+00,"CO2"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

**Comment by ibell** [comment]
QS are not supported inputs, though the error message should be clearer.

**Comment by ibell** [comment]
This was fixed in 5.1.2
