### ISSUE TITLE
Using conda recipes

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#905]
@jowr - how do I use the conda packages that are being built?  Could you please update the docs for python?  I have some TravisCI builds for pdsim that need pretty recent CoolProp, and the build time for TravisCI is pretty slow if I have to recompile CoolProp too..

**Comment by jowr** [comment]
Check out 

https://conda.anaconda.org/coolprop

https://github.com/CoolProp/CoolProp/issues/707#issuecomment-120842992

`conda install -c https://conda.anaconda.org/coolprop coolprop`

Please note that I removed the conda builds from the bots to save some time - they are not updated regularly. 

Do you think we should put an effort into integrating the conda builds?

**Comment by ibell** [comment]
I can only speak for myself - for me it would be very useful. For instance, I have tests of PDSim running on TravisCI, and each time the tests run I have to compile both coolprop (which doesn't change), and pdsim, which does always have to be recompiled.  So it takes two times longer than it should.  For linux, wheels don't work, which otherwise would be the most convenient solution.

**Comment by ibell** [comment]
Perhaps I could force pip to grab a linux wheel which might do the job.

**Comment by jowr** [comment]
Can you do that on Linux as well? We could also make a new builder for conda or include a switch in the Python builders. I just think, that we should not integrate it into the CI mechanism.

**Comment by ibell** [comment]
Hmm that's right we don't currently build linux wheels.  But we could, and experiment with whether the architecture works.

**Comment by jowr** [comment]
There is some progress, but some of the builds are still broken...

**Comment by ibell** [comment]
Looks very promising.  Could you please email me the details of what we
will have to do in June to fix the token?  I'd rather know now than to have
to fight with it in a few months.

**Comment by jowr** [comment]
I think that one can only generate a token that is valid for a year. You basically have to ssh to the buildbot master and generate a new token, see http://docs.binstar.org/token_gen.html#how-to-generate-a-token . If you create and account on https://anaconda.org/, I can add you to the CoolProp group to access the repository.

**Comment by jowr** [comment]
I think I fixed the remaining builds, but the system is very fragile and slow. 

 - *Fragile*: Conda somehow checks the old binaries it has built before it builds new ones and this basically means that one broken package in your `conda-bld` folder screws up the whole process because it refuses to build new packages as long as there sits a single broken one. 

 - *Slow*: The normal Python builds take between 3 and 6 minutes on my machines and including the conda packages multiplies this time by a factor of 2.5 to 4. This is rather inconvenient, but I cannot get faster machines or reduce the load on the virtual builder nodes as they also have to do other things.

So far so good. As soon as the nightly build has completed without problems and the binaries for `5.1.3dev0` appear in https://anaconda.org/coolprop/labels/dev/history we can close this issue and keep our fingers crossed. In theory, I included conda in the release script, which means that the next release also should appear in https://anaconda.org/coolprop/labels/main/history.

**Comment by jowr** [comment]
It looks like the binstar upload fails regularly. This might be due to the process getting killed by our hoster, but I am not sure. I'll see what I can do to fix this.

**Comment by ibell** [comment]
I'm really appreciative of the time you are putting into getting the conda
builds working.  I think that will be helpful - especially for linux folks.

**Comment by jowr** [comment]
*drumroll* the release script runs in 1 minute...

**Comment by jowr** [comment]
OK, test please test on your OSX and Linux machines using: 
```
conda create -yq -n CPTEST python=2.7; source activate CPTEST; conda install -yq -c https://conda.binstar.org/coolprop/label/dev coolprop; python -c "import CoolProp; print(\"\\n\\nInstalled CoolProp version: \"+CoolProp.__version__)+\"\\n\\n\""; source deactivate; conda-env remove -yq -n CPTEST
conda create -yq -n CPTEST python=3.3; source activate CPTEST; conda install -yq -c https://conda.binstar.org/coolprop/label/dev coolprop; python -c "import CoolProp; print(\"\\n\\nInstalled CoolProp version: \"+CoolProp.__version__)+\"\\n\\n\""; source deactivate; conda-env remove -yq -n CPTEST
conda create -yq -n CPTEST python=3.4; source activate CPTEST; conda install -yq -c https://conda.binstar.org/coolprop/label/dev coolprop; python -c "import CoolProp; print(\"\\n\\nInstalled CoolProp version: \"+CoolProp.__version__)+\"\\n\\n\""; source deactivate; conda-env remove -yq -n CPTEST
```
... and on Windows you use:
```
conda create -yq -n CPTEST python=2.7 & activate CPTEST & conda install -yq -c https://conda.binstar.org/coolprop/label/dev coolprop & python -c "import CoolProp; print(""\n\nInstalled CoolProp version: ""+CoolProp.__version__)+""\n\n""" & deactivate & conda-env remove -yq -n CPTEST
conda create -yq -n CPTEST python=3.3 & activate CPTEST & conda install -yq -c https://conda.binstar.org/coolprop/label/dev coolprop & python -c "import CoolProp; print(""\n\nInstalled CoolProp version: ""+CoolProp.__version__)+""\n\n""" & deactivate & conda-env remove -yq -n CPTEST
conda create -yq -n CPTEST python=3.4 & activate CPTEST & conda install -yq -c https://conda.binstar.org/coolprop/label/dev coolprop & python -c "import CoolProp; print(""\n\nInstalled CoolProp version: ""+CoolProp.__version__)+""\n\n""" & deactivate & conda-env remove -yq -n CPTEST
```
... remember to test for 32bit and 64bit if possible.

**Comment by ibell** [comment]
On windows, it works for python 2.7 exactly as you wrote, but for python 3.3, I get errors like this:

```
    LOCKERROR: It looks like conda is already doing something.
    The lock C:\Miniconda\pkgs\.conda_lock-6380 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 1 seconds
```
If I break up the steps, it works.  Must not fully terminate before it begins the next step...

**Comment by jowr** [comment]
That looks like a local conda issue on your machine. Well, I am happy to hear that it works on Windows.

**Comment by ibell** [comment]
Yeah, seems good to me.  I'll try on OSX when I'm back at my apartment.

**Comment by ibell** [comment]
Aha.  On windows you want ``&&`` instead of ``&`` ;  otherwise it tries to run the commands before the previous terminates.  See http://stackoverflow.com/a/8055430/1360263

**Comment by ibell** [comment]
Also, the parentheses in the printing command(s) seem to be misplaced....

```
conda create -y -n CPTEST python=2.7 && activate CPTEST & conda install -y -c https://conda.binstar.org/coolprop/label/dev coolprop && python -c "import CoolProp; print(""\n\nInstalled CoolProp version: ""+CoolProp.__version__+""\n\n"")" && deactivate && conda-env remove -y -n CPTEST
conda create -y -n CPTEST python=3.3 && activate CPTEST & conda install -y -c https://conda.binstar.org/coolprop/label/dev coolprop && python -c "import CoolProp; print(""\n\nInstalled CoolProp version: ""+CoolProp.__version__+""\n\n"")" && deactivate && conda-env remove -y -n CPTEST
conda create -y -n CPTEST python=3.4 && activate CPTEST & conda install -y -c https://conda.binstar.org/coolprop/label/dev coolprop && python -c "import CoolProp; print(""\n\nInstalled CoolProp version: ""+CoolProp.__version__+""\n\n"")" && deactivate && conda-env remove -y -n CPTEST
```

**Comment by jowr** [comment]
OK, but does it work now?

**Comment by ibell** [comment]
On OSX, these work now:

```
conda create -y -n CPTEST python=2.7; source activate CPTEST; conda install -y -c https://conda.binstar.org/coolprop/label/dev coolprop; python -c "import CoolProp; print(\"\\n\\nInstalled CoolProp version: \"+CoolProp.__version__+\"\\n\\n\")"; source deactivate; conda-env remove -y -n CPTEST
conda create -y -n CPTEST python=3.3; source activate CPTEST; conda install -y -c https://conda.binstar.org/coolprop/label/dev coolprop; python -c "import CoolProp; print(\"\\n\\nInstalled CoolProp version: \"+CoolProp.__version__+\"\\n\\n\")"; source deactivate; conda-env remove -y -n CPTEST
conda create -y -n CPTEST python=3.4; source activate CPTEST; conda install -y -c https://conda.binstar.org/coolprop/label/dev coolprop; python -c "import CoolProp; print(\"\\n\\nInstalled CoolProp version: \"+CoolProp.__version__+\"\\n\\n\")"; source deactivate; conda-env remove -y -n CPTEST
```

Problems solved!  Thanks again!

**Comment by jowr** [comment]
Great good luck with your Jenkins / Travic CI builds for pdsim.
