### ISSUE TITLE
Failure to calculate mixtures where 0<Q<1 with HmassP inputs and tabular REFPROP backend: "vapor quality is not in (0,1)"

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#910]
The following code shows that for some conditions of mixtures, the state cannot be calculated with the REFPROP tabular backend (with either TTSE or bicubic), but can be calculated with the nontabular REFPROP backend. I'm using the January 4th nightly build, 32-bit, C#.

Example with R407C:

    stateTab = AbstractState.factory("BICUBIC&REFPROP", "R407C.mix");
    stateTab.specify_phase(phases.iphase_twophase);
    stateTab.update(input_pairs.HmassP_INPUTS, 240476.541, 751054.416); // throws exception: "vapor quality is not in (0,1)"
    stateTab.unspecify_phase();

    stateTab = AbstractState.factory("REFPROP", "R407C.mix");
    stateTab.update(input_pairs.HmassP_INPUTS, 240476.541, 751054.416);
    stateTab.Q(); // returns 0.13427993177100211

Example with R407F (same code, just change refrigerant and substitute h and p):

    h = 236858.632
    p = 433891.132
    >> q = 0.23135791062044447

With R438A:

    h = 235011.533
    p = 362643.065
    >> q = 0.25836320131570978

With R442A:

    h = 237573.654
    p = 438326.155
    >> q = 0.23323199049033866

With R448A:

    h = 239519.305
    p = 441278.284
    >> q = 0.23827476042647489

These are all real-world examples taken from calculations for our customers' screw compressor packages.

**Comment by ibell** [comment]
For mixtures, it is not possible to evaluate states between quality greater than 0 and less than 1.  In these cases, we have no way of determining the composition of the co-existing phases.  You're on your own to figure out how you want to handle it.

**Comment by ibell** [comment]
What you could do as an approximation is to calculate the enthalpies of saturated vapor and saturated liquid and use those to calculate the vapor quality.
