### ISSUE TITLE
CO2 Coolprop / Refprop Differences

### ISSUE THREAD

**Issue by khoopes** [CoolProp/CoolProp#912]
I am getting very similar values from Coolprop as I do from refprop for most fluid properties, but thermal conductivity is different for supercritcal CO2. As an example:

CO2 at 800K and 25MPa 

for density I get:
 
REFPROP: 158.651354083
CoolProp: 158.651354084
 
But for thermal conductivity I get:
 
REFPROP: 0.0625476430028
CoolProp: 0.0632988474079

Are these differences normal?

Thanks,

**Comment by jowr** [comment]
Have you checked the references? CoolProp and REFPROP might actually implement different correlations.

**Comment by ibell** [comment]
Yes CoolProp actually uses a more modern and more accurate formulation from Scalabrin (see http://www.coolprop.org/dev/fluid_properties/fluids/CarbonDioxide.html#references) than the older formulation used in REFPROP.  There's not a huge difference though.

**Comment by ibell** [comment]
Also, if you look at the consistency plots for CO2 (http://www.coolprop.org/fluid_properties/fluids/CarbonDioxide.html#refprop-validation-data), you see the differences are usually less than 1%, which is well within the uncertainty of the conductivity correlation (usually a few percent)
