### ISSUE TITLE
Coolprop calling refprop speed

### ISSUE THREAD

**Issue by khoopes** [CoolProp/CoolProp#913]
When using coolprop to call refprop it is significantly slower than calling refprop directly for 100 evaulations for thermal conductivity coolprop takes 17ms while coolprop calling refprop takes 2.631 seconds. Calling refprop directly (from the refprop wrapper for matlab) takes 35ms

Python Code:
```python
import CoolProp.CoolProp as CP
import time

t0 = time.time()
for k in range(0,100):
    L = CP.PropsSI('L','T',800,'P',25e6,'co2')
t1 = time.time()

print '\nCoolProp Executed in %g [ms]' % ((t1-t0)*1e3)

t0 = time.time()
for k in range(0,100):
    L = CP.PropsSI('L','T',800,'P',25e6,'REFPROP::co2')
t1 = time.time()

print '\nREFPROP Executed in %g [ms]' % ((t1-t0)*1e3)
```

MATLAB Code
```matlab
clear
clc

tic
for k = 1:100
    L = refpropm('L','T',800,'P',25e6/1e3,'co2');
end
toc
```

**Comment by paarfi** [comment]
For faster calculations, you should use the low-level interface.
http://www.coolprop.org/coolprop/LowLevelAPI.html

**Comment by mapipolo** [comment]
As paarfi said, you should be using the low-level interface to call into refprop. There's additional overhead inherent in using refprop that you're hit with every time you call PropsSI if using the high-level interface. If you use the low-level interface, you can preserve the AbstractState objects in memory and only have to deal with that computational overhead once.

**Comment by ibell** [comment]
Using the low-level interface:
``` python
import CoolProp
import time

t0 = time.time()
AS = CoolProp.AbstractState('HEOS','CO2')
for k in range(0,10000):
    AS.update(CoolProp.PT_INPUTS, 25e6, 800)
    AS.conductivity()
t1 = time.time()

print 'CoolProp Executed in %g [ms]' % ((t1-t0)*1e3)

t0 = time.time()
AS = CoolProp.AbstractState('REFPROP','CO2')
for k in range(0,10000):
    AS.update(CoolProp.PT_INPUTS, 25e6, 800)
    AS.conductivity()
t1 = time.time()

print 'REFPROP Executed in %g [ms]' % ((t1-t0)*1e3)
```
yields
```
CoolProp Executed in 225 [ms]
REFPROP Executed in 175 [ms]
```

**Comment by ibell** [comment]
Or a bit cleaner:
```
import CoolProp
import time

N = 10000

t0 = time.time()
AS = CoolProp.AbstractState('HEOS','CO2')
for k in range(0,N):
    AS.update(CoolProp.PT_INPUTS, 25e6, 800)
    AS.conductivity()
t1 = time.time()

print 'CoolProp Executed in %g [us/call]' % ((t1-t0)/N*1e6)

t0 = time.time()
AS = CoolProp.AbstractState('REFPROP','CO2')
for k in range(0,N):
    AS.update(CoolProp.PT_INPUTS, 25e6, 800)
    AS.conductivity()
t1 = time.time()

print 'REFPROP Executed in %g [us/call]' % ((t1-t0)/N*1e6)
```
yields
```
CoolProp Executed in 20.5 [us/call]
REFPROP Executed in 17.5 [us/call]
```

**Comment by khoopes** [comment]
This works well, thank you, I have switched to the low level interface.

I am still scratching my head however as to why the high level interface to REFPROP would be so much slower than the high level interface to CoolProp considering that the low level interface to REFPROP is faster than the low level interface to CoolProp.

**Comment by ibell** [comment]
There is a lot of initialization of REFPROP's internal state that happens every single time when you call into REFPROP from the high-level interface (calling of the SETFLD function).  As a result it is much slower, and so far as I can tell, there isn't an easy way of fixing that.
