### ISSUE TITLE
Maybe embed google groups in website

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#915]
See https://groups.google.com/forum/#!topic/sphinx-users/-k3HteNGu1o

**Comment by jowr** [comment]
Nice idea, but do you think that we can avoid iframes? From what I know, they tend to cause cross-site scripting alerts and should be avoided. But it has been a while since I worked with websites and  things might have changed in the meantime.

**Comment by ibell** [comment]
Hmm... maybe this isn't a brilliant idea...
