### ISSUE TITLE
isenthalpic flash of methane (natural gas) with aqueous ethylene glycol "impurity"

### ISSUE THREAD

**Issue by denfromufa** [CoolProp/CoolProp#919]
Is it possible to extract fluid temperature from isenthalpic flash of methane (natural gas) with aqueous ethylene glycol "impurity"?

**Comment by jowr** [comment]
I do not think so.

**Comment by denfromufa** [comment]
@jowr it is actually possible using REFPROP interface and some LinearNDInterpolator magic

**Comment by ibell** [comment]
Can you please provide an example of what you are talking about with the LinearNDInterpolator + REFPROP?

**Comment by denfromufa** [comment]
actually you do not even need LinearNDInterpolator if REFPROP solver is not failing:

```
rp=CP.AbstractState('REFPROP','water')
rp.update(CP.PT_INPUTS, p1, t1)
h12=rp.hmass()
rp.update(CP.HmassP_INPUTS, h12, p2)
t2=rp.T()
```

**Comment by ibell** [comment]
Is there anything to be done here?  Otherwise I am going to close this issue.
