### ISSUE TITLE
Cant find temperature at pressure and entropy

### ISSUE THREAD

**Issue by Tom0310** [CoolProp/CoolProp#920]
With coolprop in matlab, I try to compute the following.

Fluid='R1233ZD';

s_vap= CoolProp.PropsSI('S','P', 1.0317e+06,'Q', 1, fluid);
TT= CoolProp.PropsSI('T','P', 1.0317e+06,'S', 1750, fluid);
TT12= CoolProp.PropsSI('T','P', 1.0317e+06,'S', 1780, fluid);

TT12 is the value I need to calculate, this is copied from a large series of calculations, so computing the value with a step in between (via saturation line)  is not an easy option. This because the number is part of a large matrix with many different values.

The error is the following:
 s_vap =

   1.7865e+03

TT =

  372.6818

Warning: unable to solve 1phase PY flash with Tmin=372.682, Tmax=825 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Smolar [232.28 J/mol/K]
is below the minimum value of 233.12674721 J/mol/K 
Error using CoolPropMATLAB_wrap
Fatal error.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] = CoolPropMATLAB_wrap(314,varargin{:});

Error in plot_orc_coolp2 (line 6)
TT12= CoolProp.PropsSI('T','P', 1.0317e+06,'S', 1780, fluid)

The calculations left and right of the point I want to find do work, as showen. The only error i can think of is that Coolprop cant find points close to saturation line. Is there a solution for this problem.
I am using Matlab R2015a, Windows 7 64 bit and Coolprop 5.1.2

**Comment by ibell** [comment]
It does appear that R1234zd(E) does have a few small issues, but is mostly
good -
http://www.coolprop.org/dev/fluid_properties/fluids/R1233zd(E).html#consistency-plots
.   I think you might have just gotten unlucky with that point.  I'll
investigate.

**Comment by Tom0310** [comment]
![ps1](https://cloud.githubusercontent.com/assets/16686356/12319908/c854b9dc-baa5-11e5-9410-646bac0be9ad.png)
The red line is a representation of the points that fail for R1234zd(E). 
If I'll find more fluids with this error I will let you know. 
Thanks for your fast response. 
Good luck with your investigation, I hope you find the error.
