### ISSUE TITLE
GCC for Windows: is MinGW-w64 possibly the best choice?

### ISSUE THREAD

**Issue by EmiCas** [CoolProp/CoolProp#922]
Dear all,
this is more the summary of a search I made in the last week following some problems encountered with the usage of the fortran wrapper. I hope is the right place!

On the website was previously suggested to use MinGW in order to have GCC working under Windows. However, MinGW is stuck at GCC version 4.8 which has known issues with CoolProp's last versions.

I thus tried TDM-64 (which is now suggested in the website for the use with fortran) which is shipped with GCC 5.1 and it worked perfectly. Note that the installer (oddly) only allows to install the last version. Installing older ones is possible, though not very easy, by downloading the different files needed and composing them in the appropriate tree structure. However, I soon discovered that GCC 5.1 has an awful bug which practically prevent to open external files with gfortran, making the whole thing almost useless. This has been solved in successive GCC versions. However the TDM project seems less lively than MinGW-w64 (see in the following) and, furthermore, it uses the runtime libs of MinGW-w64, thus lagging necessarily behind in terms of developments. As the last remark, I experienced some small though annoying issues in the TDM implementation such as, e.g., globbing (e.g., the usage of wildcards like *.o to indicate all the files with extension .o) is not supported.

Finally, I tried with MinGW-w64 (https://sourceforge.net/projects/mingw-w64/files/), whose installer allows you to install different versions of GCC, up to the last one, i.e., the 5.3.1. With this I was able to compile CoolProp and use it with gfortran without problems. To conclude, my personal suggestion would be to point the windows users towards this solution!  

additional notes:
-http://www.coolprop.org/coolprop/wrappers/index.html still points to minGW
-"Coolprop online" tabs on the up and bottom navigation bars point to http://ibell.pythonanywhere.com/, while "Coolprop online" in the ToC points to http://www.coolprop.org/online/index.html 

I hope this helps

regards

**Comment by ibell** [comment]
@EmiCas You are most welcome to update the docs with your experience.  I don't use Mingw actively, and when I have had to do things with mingw, I have just used TDM-GCC and it has worked for my purposes. 

A pull request would be best.

**Comment by EmiCas** [comment]
ok great, I'll proceed with a pull request then!
regards
e

**Comment by EmiCas** [comment]
well....
maybe I was too optimistic here!
I had a look but did not figure out how I should exactly proceed with the pull request

help appreciated

e

**Comment by jowr** [comment]
Hm, what about https://help.github.com/articles/using-pull-requests/

**Comment by ibell** [comment]
Basically:
a) Make a fork of CoolProp
b) Pull the fork to your computer
c) Make the changes
d) Commit and push your changes to your fork on github
e) Make a pull request based on your fork.

**Comment by ibell** [comment]
Any update?

**Comment by EmiCas** [comment]
Hi there!
I planned to work on this in the weekend! 
have a nice day

emiliano

**Comment by ibell** [comment]
Any idea for the timeline on this?  I was thinking to add it to 5.1.3 release.

**Comment by ibell** [comment]
Bump?

**Comment by EmiCas** [comment]
Hi, I am trying to do what you suggested but without success up to now.

I made the fork and I clone it on a local folder. Now what I have is the Coolprop source, but I do not understand how to access the documentation which then forms the website somehow mysteriously for me.

Sorry

E

**Comment by ibell** [comment]
Ah ok, once you have checked out the sources, you want to modify the file
called Web/coolprop/wrappers/FORTRAN/index.rst.  Then push your changes to
your fork, and make a pull request. Once the PR is merged, the
documentation will auto-update.

It's painful the first few times, and then it gets easier.

See also this great WYSIWYG editor for restructured text files:
http://rst.ninjs.org

**Comment by EmiCas** [comment]
Perfect!
I proceed then

E

**Comment by EmiCas** [comment]
Dear Ian,
Check if what I did is correct!

Thanks

Emiliano

**Comment by ibell** [comment]
I see your PR on your fork, but that's not exactly right.  Please see my
comment on your fork PR.

**Comment by ibell** [comment]
Closed by #964
