### ISSUE TITLE
Use GERG models with REFPROP

### ISSUE THREAD

**Issue by denfromufa** [CoolProp/CoolProp#923]
```
rp=CP.AbstractState('REFPROP','Methane&Water')
rp.change_EOS(0,"GERG")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-111-dbfb8eabf6ad> in <module>()
----> 1 rp.change_EOS(1,"GERG")

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.change_EOS (CoolProp\CoolProp.cpp:10282)()

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.change_EOS (CoolProp\CoolProp.cpp:10181)()

ValueError: calc_change_EOS is not implemented for this backend
```

**Comment by ibell** [comment]
Interesting idea.  Do you feel confident enough in C++ to make the necessary changes?  It's not currently implemented.

**Comment by ibell** [comment]
You'll need to call ``GERG04dll`` and then ``SETUPdll``

**Comment by denfromufa** [comment]
I would prefer ctypes or cffi over c++, since this does not require
recompile.

**Comment by ibell** [comment]
Fair enough, but we are talking about CoolProp here which is the whole stack of c++ interfaces

**Comment by ibell** [comment]
I have a better idea for this issue - I am going to add a configuration variable that allows you to tell REFPROP to call GERG04dll right after loading the DLL.  That will yield your desired behavior.
