### ISSUE TITLE
Remap CoolPropDbl to double permanently

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#931]
@jowr @mikekaganski ,

I am thinking of removing all the long double functions everywhere and bring everything to just use doubles.  It would be a rather major change internally.  But I think it would make the code quite a bit faster since the compiler can use the intrinsics better.  Also, I find it extremely confusing to have some functions that want ``std::vector<double>`` and others that want ``std::vector<long double>``.

What do you guys think?

**Comment by jowr** [comment]
Go for it. I have not had any problems with truncation. :+1:

**Comment by ibell** [comment]
I know this is going to be an issue with VLE calculations with water due to
the complexity of its EOS.  I think a bit of testing would be appropriate
before committing this change.

**Comment by ibell** [comment]
I think this is going to happen.  I made the necessary changes in the CoolPropDbl_to_double branch.  There's a single macro that changes this behavior, and a single typedef in python land.  The only problems I have seen in the tests are a few composition derivatives not quite getting to tolerance.  Overall this seems like a safe change.
