### ISSUE TITLE
Memory access violation on mixture update at very low pressures using tabular backend

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#934]
This may not be a big deal, because the pressures involved are probably unrealistically low for any typical purpose, but since I found it I thought I would bring it up. I believe it happens with a few mixtures, but here we'll use R507:

    AbstractState s = AbstractState.factory("BICUBIC&REFPROP", "R507A.mix");
    s.update(input_pairs.PQ_INPUTS, 8800, 0);

Calling update with any pressure below about 9000 and either Q=0 or Q=1 causes an access violation exception (C#):

    System.AccessViolationException was unhandled
    ...
    Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

The trouble with this particular error is that it can't be caught and handled, so if perchance during some iteration the pressure falls below this threshold, it crashes everything. On the other hand, if we update with, say, PT inputs and very low pressure, we get a normal exception that can be handled:

    AbstractState s = AbstractState.factory("BICUBIC&REFPROP", "R507A.mix");
    s.update(input_pairs.PT_INPUTS, 8800, 300);

Exception thrown: "Input is weird; odd number of intersections found". This seems reasonable.

**Comment by ibell** [comment]
Probably this is because your phase envelope for this mixture doesn't get down to below 9000 Pa on the liquid side.  I'll investigate.

**Comment by mapipolo** [comment]
I see what you did with ed8fla9, but oddly the behavior upon running the above lines of code hasn't changed. I still get the same un-catchable access violation exception with Q=0 or 1. Using the January 24th nightly build here.

**Comment by ibell** [comment]
Hmm..  Same test fails in the same way?

**Comment by mapipolo** [comment]
Yes. I just copied and pasted the two lines of code above and ran them, getting the System.AccessViolationException on update(). Changed Q to 1, restarted and ran again, and got the same exception.

**Comment by mapipolo** [comment]
Just to be certain, I just redownloaded the latest nightly, copied to my project and rebuilt the solution. No change.

**Comment by ibell** [comment]
Argh.  I thought I had fixed this.  To be continued when I can find the
time.

**Comment by mapipolo** [comment]
No problem. It's not a huge roadblock at this point. Thank you for all the effort and dedication you put into this project.
