### ISSUE TITLE
Cannot use REFPROPMixtureBackend

### ISSUE THREAD

**Issue by uqtredd1** [CoolProp/CoolProp#938]
Hello CoolProp Team,

We are having trouble interfacing with the refprop library. I'm using CoolProp 5.1.2 via Python 2.7.11 64bit with Anaconda 2.4.1, and refprop 9.0 is installed in c:/program files. Some sample error logs are attached.

Many Thanks,

Tom

![coolprop_error1](https://cloud.githubusercontent.com/assets/16814152/12474602/1e22aea6-c068-11e5-9c40-e6b870eaee98.PNG)
![coolprop_error2](https://cloud.githubusercontent.com/assets/16814152/12474601/1e22c170-c068-11e5-8324-8179c49a5e58.PNG)
![coolprop_error3](https://cloud.githubusercontent.com/assets/16814152/12474603/1e281b2a-c068-11e5-82cf-97c6ee193449.PNG)

**Comment by jowr** [comment]
I think you should update your REFPROP version to 9.1. The error message should be clearer if this really is the problem.

**Comment by ibell** [comment]
First thing is to upgrade as Jorrit said (please email me at my personal email on the coolprop main page).  You probably don't have the 64-bit DLL for REFPROP, which is why it fails   I don't believe 9.0 came with the 64-bit DLL, but 9.1.1 does.

Fixing the error message for REFPROP and making it clearer why it failed (DLL, fluids, HMX.BNC, etc.) was on my list of things to do.

**Comment by ibell** [comment]
Bump.  Have you emailed me?

**Comment by jcmendezcarvajal** [comment]
This is almost 10 years old but still relevant. I have the same issue even though I installed REFPROP 10, in Windows. I checked the path env variable and REFPROP directory is added to the PATH.

**Comment by ibell** [comment]
Did you read the docs: http://www.coolprop.org/coolprop/REFPROP.html#refprop
? That's your starting point for all issues.

Beyond that, you need to provide a lot more information about what you
tried, operating system, etc.

**Comment by henningjp** [comment]
Make sure the Windows environment variable `RPprefix` is set to the top level REFPROP directory,
(typically, `C:\Program Files\REFPROP` on Windows, or some alternative location).  I think CoolProp uses this.
