### ISSUE TITLE
CoolProp returns "N/A" as REFPROP_name for R1234ze(Z), should return "R1234ZEZ"

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#940]
Instead of coding in parallel CoolProp and REFPROP fluid names, I'm using the built-in get_fluid_param_string method to fetch the REFPROP names if needed. I ran across one that seems to be missing:

    CoolProp.get_fluid_param_string("R1234ZE(Z)", "REFPROP_name"); // "N/A"
    AbstractState s = AbstractState.factory("REFPROP", "R1234ZEZ"); // fluid loads fine

Using 01/20 nightly build, Refprop 9.12.

**Comment by ibell** [comment]
That's what the REFPROP fluid file *will* be called, but it's not included
in the general distribution of REFPROP.  R1234ZE.FLD is actually
R1234ze(E), an unfortunate naming decision that is now impossible(ish) to
fix.

And yes, that is exactly what you should do - query CoolProp to get the
REFPROP name.

**Comment by mapipolo** [comment]
Interesting. For now I guess I will code in a handler for this specific case until it's included in the general distribution of REFPROP. Thank you.
