### ISSUE TITLE
CoolProp for SIMULINK

### ISSUE THREAD

**Issue by arashsk** [CoolProp/CoolProp#954]
Hello,

The following syntax can be successfully used in MATLAB environment:

CoolProp.PropsSI('T','P',101325,'Q',0,'Water')

The result is simply the saturation temperature of Water at 1 atm (in Kelvin)

I am trying to use the same syntax, but in SIMULINK environment, by simply using a "MATLAB function block" for which the inputs are two constant blocks (i.e. 101325 and 0) for P = 101325 and Q = 0

I get an error message as follow:
...
Only MATLAB files are supported for code generation. Unsupported file extension 'mexw64' for 'C:\Users\username\Documents\MATLAB\main\CoolPropMATLAB_wrap.mexw64'.
...

Does anyone know a resolution to this?

Thanks,

**Comment by ibell** [comment]
As the error message says, you can't call MEX functions from Simulink.  You might be able to call DLL using the loadlibrary function though.  This suggests it is possible: http://www.mathworks.com/examples/matlab/6385-calling-shared-libraries-from-simulink

You might want to look at this example: http://www.coolprop.org/dev/coolprop/wrappers/MATLAB/index.html#calling-low-level-interface-through-dll .  Get it working in MATLAB before embarking on Simulink.
