### ISSUE TITLE
TS/HS issues on OSX

### ISSUE THREAD

**Issue by ragnar2015** [CoolProp/CoolProp#956]
Hello,

I just installed python 2.7.11 on a Mac with OS X 10.9.5 (Maverick).
Also installed CoolProp 2.4.5 after using CoolProp 3.2 previously.

Coolprop imports into python with no errors.

I have a call to CoolProp.Props as follows:
tt_iter = CoolProp.CoolProp.Props('T','H',hval,'S',sval,fluid)  
According to 4.0.0 CoolProp documentation, H is KJ/kg and S is KJ/kg/K
T should return as deg Kelvin.

With:
hval = 4.221842e+02    (KJ/kg)
sval = 1.570949e+00         (KJ/kg/K)
fluid='co2'

CoolProp should return T~389.57 K

For reference: REFPROP returns T=389.57 F for the same H and S values and units above.

But I ran into this CoolProp error:
   
  File "CoolProp.pyx", line 229, in CoolProp.CoolProp.Props (build/temp.macosx-10.9-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:10955)
  File "CoolProp.pyx", line 324, in CoolProp.CoolProp.Props (build/temp.macosx-10.9-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:10350)
  File "CoolProp.pyx", line 225, in CoolProp.CoolProp.__Props_err2 (build/temp.macosx-10.9-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:9875)
ValueError: CoolProp error: Inputs in Brent [216.592000,248.694824] do not bracket the root.  Function values are [8234.327964,14875.948759] :: inputs were:"T","H",4.2218415582488927e+02,"S",1.5709497973539026e+00,"co2"

This error appears similar to a prior github issue: issue #439 dated Jan 29, 2015.

Is there a fix or workaround??

**Comment by ibell** [comment]
You should (almost) never give H,S directly, since you have the issue of the reference state for enthalpy and entropy to worry about (see https://github.com/CoolProp/CoolProp/blob/master/FAQ.md).  You should never make assumptions about what reference state is being used.

I'm pretty sure you don't appreciate how difficult H,S are as inputs.  There are two "solutions" to this problem:

a) You write your own solver to find T using PH as inputs to match the desired entropy (pretty simple).  Potentially as simple as this:
``` python
def f(T, P, s_given): 
    return Props('S','T',T,'P',P,'co2') - s_given
T = scipy.optimize.newton(f, T_guess, args = (P, s_given))
```
  This requires that you have a good guess for the temperature.  Which you might, I have no idea what you are doing, modeling wise.
b) You upgrade to 5.x, and file a new issue.  We are not doing any updates to the 4.x branch.

**Comment by ragnar2015** [comment]
Hi Ian,

I work in turbomachinery design and use CoolProp for "co2" properties. Following the H-S (Mollier) diagram, I use the T(H,S) call quite a bit. 

I do stay within CoolProp for H and S for the very reason that you cite: Enthalpy and entropy have reference states. 

Here is a simple example of use: If I have a compressible flow stagnation state(ie total) where velocity V=0 so Tt,Ht,St,Pt are known (subscript t is total). I can use S(P,T) for St and H(P,T) for Ht. All CoolProp calls.

Then I expand to a lower pressure Ps isentropically. If I impose a desired expanded velocity V then the static enthalpy Hs = Ht-V^2. I can then use Props function T(Hs,St) to solve for the static temperature Ts at Ps.

The T(H,S) function is the most direct way to find Ts. But if T(H,S) is numerically difficult in CoolProp then I sure would appreciate your guidance on the best way to proceed. Nobody knows CoolProp better than you, the developers.

**Comment by ragnar2015** [comment]
Ian, 
In CoolProp 4.2.5, what are the units for enthalpy and entropy?
Is it SI (J/kg) or kSI (kJ/kg) for enthalpy.

**Comment by ibell** [comment]
In Props function, H is in kJ/kg, S in kJ/kg/K
In PropsSI function, H is in J/kg, S is in J/kg/K

**Comment by jowr** [comment]
Documentation is available at http://www.coolprop.org/v4/

**Comment by ragnar2015** [comment]
Thanks Ian and Jorritt. 

BTW I took your advice and looked at Anaconda. I ended up installing miniconda (a mini install) that is more than a python distribution...is has "conda" that is an impressive package manager that allows easy creation and management of various virtual environments. It goes a lot deeper than that too as you know. Pretty slick and thanks!

So I created two environments (both python 2.7.11):
-the first with CoolProp 4.2.4       (NOT successful)
-the second with CoolProp 5.1.1 (successfull!)

The CoolProp 4.2.4 (from online anaconda.org) still required a pip install but that compile failed. 
I would like CoolProp 4.2.4 to work within conda for backward compatibility to my pre-CoolProp 5x code that used KSI units (example: kJ/kg). Is that a matter of your team precompiling CoolProp 4.2.4 for upload to  anaconda.org ?

**Comment by ibell** [comment]
Yes, anaconda/miniconda is a great system.  I use/love it.

With CoolProp 4.2.5 on windows, you shouldn't need any compilation. What
operating system are you on?  It should be as simple as doing this at the
terminal:

pip install CoolProp==4.2.5

**Comment by ragnar2015** [comment]
I am using OSX 10.9.5 (Maverick). On anaconda.org, there was a reference to CoolProp 4.2.4 so I tried that one and it failed to compile. So next,  I will try "pip install CoolProp==4.2.5".

**Comment by ibell** [comment]
Right, we don't have wheels for 4.2.5 on pypi.  I could upload a wheel for
4.2.5.   What version of python?

**Comment by ragnar2015** [comment]
With CoolProp 5.1.1 and Python 2.7.11, I still have that Brent bounds not bracketing root issue.
Here is the statement with inputs:
hval =451968.695249   # coolprop 5.1: h=J/kg
sval=1588.04203882    # coolprop 5.1: s=J/kg/K
 tt = CoolProp.CoolProp.PropsSI('T','H',hval,'S',sval,'co2')	

Here is the exception:
File "CoolProp/CoolProp.pyx", line 216, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:25933)
File "CoolProp/CoolProp.pyx", line 296, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:25734)
File "CoolProp/CoolProp.pyx", line 185, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:24059)
ValueError: Brent's method reached maximum number of steps of 100  : PropsSI("T","H",451968.6952,"S",1588.042039,"co2")

The input state is supercritical co2.  Any ideas?

**Comment by ibell** [comment]
Wheel for 4.2.5(ish) is up on pypi.  Can't compile for py3.3 or py3.4.  @jowr, can you help me with py33/py34?

**Comment by ibell** [comment]
I noticed there are some issues with CO2: http://www.coolprop.org/dev/fluid_properties/fluids/CarbonDioxide.html#consistency-plots 

I'll investigate.  TS is also having some issues, which is surprising.  Might be related to #953 , but hard to say.

**Comment by ragnar2015** [comment]
Regarding 4.2.5, I am using Python 2.7.11 per miniconda.

**Comment by ragnar2015** [comment]
Those consistency plots are interesting. There sure are a lot of red dots on that co2 TS diagram though.

**Comment by ibell** [comment]
Yeah, and TS is used to get the HS inputs.  So I first need to fix TS
inputs.  Let's see when I get a chance to fix that.

**Comment by ibell** [comment]
Weirdly this works fine on windows, but not on OSX.  Usually its the other way around.

**Comment by ragnar2015** [comment]
I really, really hope that the TS, HS issues get fixed in that red dot region of those carbon dioxide consistency charts. Coolprop5.1.1  has TS, HS convergence ??  issues below about 364K (that I know of) for supercritical co2.

**Comment by ibell** [comment]
Yes, but only on osx, and not in c++, which is hard to understand.  I'll
get to bottom of it

**Comment by jowr** [comment]
@ibell : I just tried to build from the latest sources, but without success. Building v4.2.6 from the master branch failed on OSX. I am going to dig into this later. It seems to work on Windows though, but we might want to run some tests before pushing a new 4.2.6 to PyPi.

**Comment by jowr** [comment]
Oups, fails on Windows as well.

**Comment by ragnar2015** [comment]
Just checking in. Have you found the cause of the H,S problem?

**Comment by ibell** [comment]
Not yet, hoping to have a chance to check it out tonight.  I haven't
forgotten.

**Comment by ragnar2015** [comment]
Hi Ian,
I see that you closed this issue. When will the H,S  or (T,S) fix be downloadable? via conda?

**Comment by ibell** [comment]
Via pip the binaries are automatically generated (you need the second call
so it downloads from our server):
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation

Conda is not actively supported at the moment.

**Comment by ragnar2015** [comment]
I created a new conda enviroment with python 2.7.11 and, per your recommendation above, installed the latest nightly build of coolprop   (5.1.3dev).

So far, I have not run into the original TS/HS Brent bracketing issue that started this github issue 956. Looks like you fixed things "under the hood"...I sure hope so. Congrats and thank you!

**Comment by ragnar2015** [comment]
Thanks again for the tip about Conda. It is a great way to manage python and coolprop updates!

**Comment by ibell** [comment]
Glad to hear everything is working for you!
