### ISSUE TITLE
Coolprop 5.1.1 to 5.1.2 Python wrappers

### ISSUE THREAD

**Issue by rddaz2013** [CoolProp/CoolProp#957]
With Ubuntu and Coolprop 5.1.1 IsoLine and Plots are working.
With Xubuntu and Coolprop 5.1.2 (pip install + compile) same code is not working. 

A 0.0.1 change breaks it? I hope not. At the moment I compile Coolprop 5.1.1 on the Xubuntu-Machine and report after that I it works again.

**Comment by ibell** [comment]
Minimal example of the failure please?

"is not working" doesn't help us to debug.

**Comment by rddaz2013** [comment]
That was a quick response. 
Yes you are right without example it is hard to track down the bug.

import matplotlib
matplotlib.rc('figure', facecolor='0.75')
import CoolProp
print('Coolprop Version: ',CoolProp.__version__)
from CoolProp.Plots import PropsPlot
from CoolProp.CoolProp import PropsSI
plt = PropsPlot('Acetone', 'Ts',Tmin=200, Tmax=600,units='SI',reciprocal_density=True)
#plt.set_axis_limits([-0.5, 1.5, 1, 2.5])
# Dampfgehalt
# plt.draw_isolines('Q', [0.1, 0.9])

#isobar
plt.draw_isolines('P', [35E5,1E5],num=2,rounding=True)
plt.draw_isolines('H', [6.5E5,6.4E5],num=2,rounding=True)
#plt.draw_isolines('D', [2, 600])

# Density of aceton at 35 bar and 125C [kg/m3]
print PropsSI('D', 'T', 398.15, 'P', 35e5, 'Acetone')
print PropsSI('T', 'H', 1500., 'P', 35e5, 'Acetone')
plt.show()

The the forced Coolprop 5.1.1 compile+install this sample works....with the 5.1.2 not.

**Comment by ibell** [comment]
see my edit to your issue, looks a bit nicer.

**Comment by ibell** [comment]
Hmm, consistency plots look good: http://www.coolprop.org/dev/fluid_properties/fluids/Acetone.html#consistency-plots

What error do you get?

**Comment by ibell** [comment]
@jowr?

**Comment by rddaz2013** [comment]
`('Coolprop Version: ', u'5.1.2')
Traceback (most recent call last):
  File "/home/rened/PycharmProjects/GasVent/Isoline.py", line 9, in <module>
    plt = PropsPlot('Acetone', 'Ts',Tmin=200, Tmax=600,units='SI',reciprocal_density=True)
  File "/home/rened/anaconda/lib/python2.7/site-packages/CoolProp/Plots/Plots.py", line 359, in __init__
    super(PropsPlot, self).__init__(fluid_name, graph_type, units=units, reciprocal_density=reciprocal_density, **kwargs)
  File "/home/rened/anaconda/lib/python2.7/site-packages/CoolProp/Plots/Plots.py", line 77, in __init__
    super(PropertyPlot, self).__init__(fluid_name, graph_type, **kwargs)
  File "/home/rened/anaconda/lib/python2.7/site-packages/CoolProp/Plots/Common.py", line 608, in __init__
    Base2DObject.__init__(self, graph_type[1], graph_type[0], state, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'units'`

**Comment by jowr** [comment]
That is weird, maybe @rddaz2013 can help me reviewing the recent changes to the Python wrapper: https://github.com/CoolProp/CoolProp/commits/master/wrappers/Python

**Comment by rddaz2013** [comment]
With 5.1.1 version i get this file unter ~\site-packages\CoolProp\Plots\Plots.py

https://gist.github.com/rddaz2013/f7efd141bfc9f2ce024c

that is not the plots.py File in the Github-repo !

**Comment by jowr** [comment]
What you ran into is no surprise since there were major changes from 5.1.1 to 5.1.2. Sorry to hear that it broke your code. I did not care much about documenting the changes because I thought that no one used the plotting functionality. 

Having said that, you might consider changing your code to work with the new package since it works better and has more functions and a nicer data structure. Again, sorry for breaking your code, but I think the new plottings functions are worth a try.

To see what else is on the list of changes for the plots in the future, please keep an eye on  #832 and #980.

**Comment by jowr** [comment]
A good way to see the recent changes is the file or folder history page available here: https://github.com/CoolProp/CoolProp/commits/master/wrappers/Python 
My changes from September / October 2015 got merged into the main branch before we release v5.1.2 and those changes are also responsible for breaking your scripts.

**Comment by jowr** [comment]
By the way, the new functions are documented in http://coolprop.sourceforge.net/apidoc/CoolProp.Plots.html#module-CoolProp.Plots

**Comment by rddaz2013** [comment]
Thx you both..

I look at the examples, perhaps I can contribute my own code. (only some examples)
After some rework

**Comment by jowr** [comment]
I finally managed to put the examples together, does this help you: http://www.coolprop.dreamhosters.com/binaries/sphinx/coolprop/python-plotting.html ?

**Comment by jowr** [comment]
@rddaz2013 is right, I broke his code - sorry for that. I think we discussed this issue for a long time now without much activity and I consider the documentation sufficient. Reopen if needed.
