### ISSUE TITLE
Coolprop with scilab

### ISSUE THREAD

**Issue by saha84** [CoolProp/CoolProp#958]
Hello,

I have two related problems, so please allow me to post them in the same issue.

- first issue:

In linux mint 17.1, I use CoolProp with scilab by this command: 

pyImport CoolProp.CoolProp

but, recently I changed to archlinux, I installed coolprop with this command (pip install CoolProp) and pims from atoms of scilab, but when i excute the first command I got this error:

-->pyImport CoolProp.CoolProp
  !--error 999 
pyImport: An error occured: Cannot load the module CoolProp.CoolProp
Python interpreter threw an exception:
exceptions.ImportError: No module named CoolProp.CoolProp

but with python from terminal it worked perfectly:

$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import CoolProp.CoolProp as CP
>>> CP.PropsSI('d(Hmass)/d(T)|P','P',101325,'T',300,'Water')
4180.6357765685725
>>> 

- The second issue: After getting stuck on the first issue, I tried to link the  libCoolProp.so with this command:

link('/home/mysession/libCoolProp.so', ['PropsSIScilab','HAPropsScilab'], 'c')

but I got this error:

link : problem with one of the entry point.

then, I tried to read the contents of the libCoolProp.so file with:

readelf -a libCoolProp.so

After exploring the contents, I haven't found any variable or function (I don't know what they are called) with those names: **PropsSIScilab **and **HAPropsScilab**, although there are **PropsSI** and **HAPropsSI**, so I changed the link command as follows:

link('/home/mysession/libCoolProp.so', ['PropsSI','HAProps'], 'c')

the execution worked without errors. then I created two functions as suggested in this link:

http://coolprop.sourceforge.net/coolprop/wrappers/Scilab/index.html

function [out]=Props(Output,Input1,Value1,Input2,Value2,Name)
  out = call("PropsSI",Output,1,"c",Input1,2,"c",Value1,3,"d",Input2,4,"c",Value2,5,"d",Name,6,"c","out",[1,1],7,"d")
endfunction

function [out]=HAProps(Output,Input1,Value1,Input2,Value2,Input3,Value3)
  out = call("HAPropsSI",Output,1,"c",Input1,2,"c",Value1,3,"d",Input2,4,"c",Value2,5,"d",Input3,6,"c",Value3,7,"d","out",[1,1],8,"d")
endfunction

But when testing, I got a wrong result:

--> [P1]=Props('P','T',373,'Q',1,'water')
 P1  =
 
    4.24D-314

I really appreciate any help you can provide.

"English is not my mother tongue; please excuse any errors on my part."

Best regards

**Comment by ibell** [comment]
For the first issue, my suspicion is that on your archlinux, "python" actually maps to a python 2.7 variant, into which CoolProp is not installed.  I don't know much about the scilab <-> python interfacing, but that's my guess.  Can you import standard libraries from your python installation?

For the second issue, the documentation is shockingly out-of-date.  Scilab is quite a poor language for interfacing with shared libraries.  It doesn't understand how to pass variables by value to a function in a shared library, which pretty much every other language does understand.  Which is why in version 4.2.x of CoolProp we added a function that took and returned all variables by reference PropsSIScilab and HAPropsSIScilab.

There is a fully-featured SWIG wrapper for scilab that will work with scilab v5.x, but only on linux.  I'll try to do some testing and update the docs today.  I think your best bet probably is to use the python <-> scilab interface.

**Comment by ibell** [comment]
Looks like PIMS is python 2.7 only: http://forge.scilab.org/index.php/p/pims/

**Comment by ibell** [comment]
Ok, I think the updates to the docs which will appear here will resolve all your issues: http://www.coolprop.org/dev/coolprop/wrappers/Scilab/index.html#scilab

Give it an hour or so.

**Comment by saha84** [comment]
Thank you for your support,

After searching in /usr/bin folder, I found that there are pyhon 2.7 in my system wich doesn't appear when executing 'python --version'. I will try to install coolprop for python 2.7 and I will post the result.

As for the second issue, the dll shared library work well with scilab in Windows OS

**Comment by ibell** [comment]
Probably on your system python is actually an alias to python3, though it
is hard to say.  To get PIMS to work, the default system python needs to be
a python 2.7.

Until the documentation appears online, you can also check out the
underlying markup, should be clear enough:
https://github.com/CoolProp/CoolProp/tree/master/Web/coolprop/wrappers/Scilab

**Comment by saha84** [comment]
Hello,

Great work, It worked perfectly with 'link' command.

I was looking for this solution for about half a year.

Thank you

**Comment by ibell** [comment]
You should have opened an issue 6 months ago :). Can't fix issues we don't
know about.

**Comment by saha84** [comment]
:-)

**Comment by saha84** [comment]
Hello,

About the 'sample.sce' file, I think that the last instruction 'ulink()' isn't necessary (or shouldn't be there) because it will unlink/unload the linked object.

Also, we could auto load the shared library at scilab starting by renaming the sample.sce file to scilab.ini and deplacing it to the scilab home directory which can be found by executing SCIHOME in the scilab console.

**Comment by ibell** [comment]
Do you want to make a pull request with this update to the documentation?
You can modify this file:
https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/Scilab/index.rst
using the online web interface.
