### ISSUE TITLE
Support mixtures with component mole fractions of zero

### ISSUE THREAD

**Issue by tianshuluo** [CoolProp/CoolProp#969]
ValueError: PropsSI failed ungracefully :: inputs were:"S","P",1.0132500000000000e+05,"T",2.8814999999999998e+02,"HEOS::Nitrogen[0.770375]&Oxygen[0.206696]&CarbonDioxide[0]&Water[0.0138572]&Argon[0.00907251]";

**Comment by ibell** [comment]
For the moment we can't handle mole fractions of zero, so remove CO2.

**Comment by tianshuluo** [comment]
Thank you

**Comment by jowr** [comment]
Is this mentioned in the docs? Maybe we should add it...

**Comment by ibell** [comment]
Actually, we can fix it.  I think I know how.  And then you can have zero
mole fractions, which is very convenient.

**Comment by mikekaganski** [comment]
Hello,
trying to reproduce this, I found that entropy for "Air" pseudo-fluid differs greatly from "Air.mix" (and corresponding Lemmon et al. mix) in 6.0.0:

PropsSI("S","P",101325,"T",288.15,"HEOS::Nitrogen[0.7812]&Oxygen[0.2096]&Argon[0.0092]")=6.82599660574707 kJ/(kg*K)
PropsSI("S","P",101325,"T",288.15,"Air.mix")=6.82599660574707 kJ/(kg*K)
PropsSI("S","P",101325,"T",288.15,"Air")=3.84616393747052 kJ/(kg*K)

I'm sorry if this is trivial and I just don't know something obvious, but is that normal?

**Comment by ibell** [comment]
Please see question #1:
https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

**Comment by mikekaganski** [comment]
Thank you! I just had an impression that in CoolProp itself, they are counted from the same baseline. Will know better! Thanks again for clarification!
