### ISSUE TITLE
Props1SI function missing in Mathematica wrapper on OSX

### ISSUE THREAD

**Issue by wahlenkus** [CoolProp/CoolProp#970]
Hi,
Is there a reason why the function Props1SI is not available in the Mathematica wrapper version on OSX.
Would be a nice addition to PropsSI and HAPropsSI.

Thanks for the effort!
Roman

**Comment by jowr** [comment]
Hi, you can always call `PropsSI` without inputs: `PropsSI("p_critical","",0,"",0,"R134a")` is the same as `Props1SI("R134a","p_critical")`. See also http://www.coolprop.org/coolprop/HighLevelAPI.html#table-of-string-inputs-to-propssi-function for more info.

**Comment by ibell** [comment]
Or, you could add the function to the wrapper and file a pull request!  I don't have the ability to test Mathematica currently.

**Comment by wahlenkus** [comment]
Thanks for the fast reply. jowr's answer will do it for me currently. Probably it would be good to find this hint somewhere in the documentation of coolprop as well. 
@ibell: I will try to support you with an updated wrapper for mathematica, but currently this can take some time ...
