### ISSUE TITLE
Can the build_phase_envelope routine implemented via high level interface?

### ISSUE THREAD

**Issue by tianshuluo** [CoolProp/CoolProp#972]
ValueError: phase envelope must be built : PropsSI("H","P",108343.4126,"S",7224.1301,"HEOS::Nitrogen[0.716910364611]&Oxygen[0.133803112059]&CarbonDioxide[0.126533499406]&Water[0.0175399314036]&Argon[0.00587302159783]")
There are is 'PS_INPUTS' keyword in low level interface for python

**Comment by ibell** [comment]
I think you want either PSmass_INPUTS or PSmolar_INPUTS.

**Comment by tianshuluo** [comment]
still show the same error message:ValueError: "phase envelope must be built "

**Comment by ibell** [comment]
Right, you have to use the low-level interface.  What are you calling
CoolProp from?

**Comment by tianshuluo** [comment]
I am calling CoolProp from python.The following is my script:
HEOS=CP.AbstractState("HEOS","Nitrogen&Oxygen&CarbonDioxide&Water&Argon")
HEOS.set_mole_fractions([0.714028201303,0.129873613512,0.133354647753,0.0177384595194,0.00570054407111])
HEOS.update(CP.PT_INPUTS,1037775.2096,1312.1530)
HEOS.smass()
7191.972276978251
HEOS.update(CP.PSmass_INPUTS,108343.4126,7191.9723)
PHSU flash for mixture
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp/AbstractState.pyx", line 70, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:11674)
  File "CoolProp/AbstractState.pyx", line 72, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:11563)
ValueError: phase envelope must be built

**Comment by ibell** [comment]
As it says, you need to build the phase envelope so it can figure out where
you are relative to saturation.  Check out:
http://www.coolprop.org/fluid_properties/Mixtures.html#phase-envelope

**Comment by tianshuluo** [comment]
The following picture shows the phase envelope
![test](https://cloud.githubusercontent.com/assets/7719765/13010484/046fb946-d1dd-11e5-8f13-b1ab251da619.png)
My operating points are far outside the saturation curve.

**Comment by ibell** [comment]
Right, but we need to build the phase envelope so that we know where it
is.  Otherwise flash calculations are difficult/impossible for mixtures.
