### ISSUE TITLE
get_parameter_information_string in CoolPropLib

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#974]
I think the catch definition is not fully consistent:
https://github.com/CoolProp/CoolProp/blob/master/src/CoolPropLib.cpp#L250

As I understood the function `CoolProp::get_parameter_index` will trigger the catch when the result is not a number, thus not giving the `parameter is invalid:` message.

So I tried this instead:
```C++
EXPORT_CODE long CONVENTION get_parameter_information_string(const char *param, char * Output, int n)
{
    int key = get_param_index(param);
    if (key >= 0){
		try{
            std::string s = CoolProp::get_parameter_information(key, Output);
            return str2buf(s, Output, n) ? 1 : 0;
        }
        catch(...){
			str2buf(format("No informations for parameter: %s", param), Output, n);
		}
    }
    else{
        str2buf(format("parameter is invalid: %s", param), Output, n);
    }
    return 0;
}
```
This gives better result when `param` is not valid.

Could I have an example of a  `param` `Output` couple? (So I can check if the output is correct when the `param` is valid).

When using `Dmolar` as `param`, the catch is triggered and the "No informations for parameter" I added is displayed.
Seems `std::string s = CoolProp::get_parameter_information(key, Output);` is not working properly.

(I'm adding some functions to the Julia wrapper and I prefer to test their correct behaviour).

**Comment by JonWel** [comment]
I found the problem: `std::string s = CoolProp::get_parameter_information(key, "long");` With "long", not Output.

I'm preparing the patch to fix this.

**Comment by mikekaganski** [comment]
JonWel commented on Feb 15:
> I found the problem: std::string s = CoolProp::get_parameter_information(key, "long"); With "long" instead of Output (which is the correct way to use this function).

This isn't "the correct way to use this function", "long" is just one of possible input. Before the commit, it was expected that the desirable output type will be passed through Output parameter. Now it unconditionally returns only one type of output, with no way to get IO, or units.

I imagine that this function (or the one that is called from it) could be modified to treat empty/invalid input as "long", but not this way when functionality is broken.

**Comment by JonWel** [comment]
@mikekaganski I don't remember much what happened when I read the description, but I agree with what you say.
(This is a bit pity to block a parameter to something constant instead of keeping the possibility to change it depending of the needs).
I'll have a look and update to a more general usage.

**Comment by ibell** [comment]
We should probably unbreak this function and add the ability to pass the
desired output again.  It might annoy one or two people with the backwards
incompatibility, but I think it is worth doing.

**Comment by JonWel** [comment]
I was thinking to keep the "old" function with `"long"` by default and adding a new export with the one where we can chose the type of output.
This way we don't break compatibility with the wrapper that would use the one input function, and we have the two input one for general usage.

@ibell does it suits you?

**Comment by mikekaganski** [comment]
Isn't it better to just have two wrappers for one function?

**Comment by mikekaganski** [comment]
One wrapper just always passes "long"

**Comment by JonWel** [comment]
So the first wrapper would stay:
```C++
EXPORT_CODE long CONVENTION get_parameter_information_string(const char *param, char * Output, int n)
{
    try{
        int key = CoolProp::get_parameter_index(param);
        std::string s = CoolProp::get_parameter_information(key, "long");
        return str2buf(s, Output, n) ? 1 : 0;
    }
    catch(...){
		str2buf(format("parameter is invalid: %s", param), Output, n);
	}
    return 0;
}
```
And the second to be:
```C++
EXPORT_CODE long CONVENTION get_parameter_information_string(const char *param, const char *info, char * Output, int n)
{
    try{
        int key = CoolProp::get_parameter_index(param);
        std::string s = CoolProp::get_parameter_information(key, info);
        return str2buf(s, Output, n) ? 1 : 0;
    }
    catch(...){
		str2buf(format("parameter is invalid: %s", param), Output, n);
	}
    return 0;
}
```

@ibell @mikekaganski Would this suit you?

**Comment by mikekaganski** [comment]
No, I meant that your Julia two wrappers will use this single correct one.
Doing what you suggest means changing existing code that depends on this API.

**Comment by JonWel** [comment]
@mikekaganski I was suggesting to have both export on the C++ file to allows backward compatibility in case some would use the precedent function.

You want to have only the second one in the C++ file?

**Comment by ibell** [comment]
Also, you can't export two functions with the same name in C, so two
functions is a no-go.

My preference is to just break backwards compatibility.  We've thus far
been quite good about it, and if we document it, not too many people should
complain.

**Comment by mikekaganski** [comment]
The backward compatibility is the real "old" function. The "fix" that Jon tries to keep is just a fes months old, but previous API was used long before.

What kind of backward incompatibility could arise since 6.0.0 release?

**Comment by JonWel** [comment]
> Also, you can't export two functions with the same name in C, so two functions is a no-go.

Oh, no overloading in C?
(I'm sorry, I know more about C++ than C)

**Comment by JonWel** [comment]
@mikekaganski You are right that I should have looked on how other wrappers use this function.

I was a bit misled having a variable used as an input and an output, and I considered by the name of this variable that it should be only an output, so modified to have a valid value for the input.

@ibell @mikekaganski At the end, which solution do we chose to have?
Tell me and I'll adapt the library files and the Julia wrapper (for the other wrappers, I fear I don't know them enough to be able to adapt them correctly).

**Comment by mikekaganski** [comment]
@JonWel Sorry for late reply - timezone difference :) I already voted for reverting the commit (maybe just correct the catch a little to always return "Parameter is invalid").

**Comment by JonWel** [comment]
@mikekaganski And sorry for the time before correction, I was waiting confirmation from Ian (who was probably wondering why I did not already did it).
#1093 should give the wanted correction.
