### ISSUE TITLE
Access to coexisting 2-phase densities for REFPROP backend

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#977]
For a `T,D`-flash calculation, I need access to the densities of the coexisting vapour and liquid phase. The `AbstractState` has the cached variables `_rhoLmolar` and `_rhoVmolar`, but they only appear in the `REFPROPMixtureBackend` and there they are commented out. There also seem to be no functions to access them. 

Am I missing something or is there no simple way to get these properties?

**Comment by ibell** [comment]
How about this:
http://www.coolprop.org/dev/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface
(18 & 19)

**Comment by jowr** [comment]
Thanks for the hint, I found those as well. My problem is that I need something that works for HEOS *and* REFPROP. Guess I'll have to implement it myself :smile:

**Comment by ibell** [comment]
Ah right, I had misunderstood your question.  You want it for the REFPROP
backend...

**Comment by jowr** [comment]
Actually for both HEOS and REFPROP - I did not mention it in the first place and simply assumed that you would read my mind.

**Comment by ibell** [comment]
Now I'm confused....  For HEOS it works just like in the example I linked.
Isn't that exactly what you want?  Or do you need it from the high-level
interface?

**Comment by ibell** [comment]
So, in summary, you are fine for HEOS, but need to implement the necessary
accessor function for REFPROP.  Correct?

**Comment by jowr** [comment]
Correct, the only thing that confused me, was that there is a function for HEOS and that there are `_rhoLmolar` and `_rhoVmolar`, which are only used in the REFPROP backend. 

**Solution:** Implement `saturated_liquid_keyed_output` and `saturated_vapor_keyed_output` for the REFPROP backend and remove `_rhoLmolar` and `_rhoVmolar` from the base class as they are only used in one backend.

**Comment by ibell** [comment]
I'm going to need a similar formulation for the cubic backend as well, but
I guess you can drop those variables from the base class.

**Comment by ibell** [comment]
Closed by #981
