### ISSUE TITLE
Cant find correct enthalpy at T and S in 2 phase area

### ISSUE THREAD

**Issue by Tom0310** [CoolProp/CoolProp#984]
I find all different kind of values when I am trying to find an enthalpy in the two phase region. 
In matlab the script looks as follows
using coolprop version 5.1.2.

fluid='water';
T_crit = CoolProp.Props1SI(fluid,'Tcrit');
T_min =  CoolProp.Props1SI(fluid,'Tmin');

h = CoolProp.PropsSI('H','T',450,'S', 4000, fluid)
p= CoolProp.PropsSI('P','T',450,'Q', 0, fluid)
xh = CoolProp.PropsSI('Q','P',p,'H', h, fluid)
xs = CoolProp.PropsSI('Q','P',p,'S', 4000, fluid)
T=T_min:(T_crit-T_min)/99:T_crit;

for i=1:length(T)
h_1(i) = CoolProp.PropsSI('H','T',T(i),'Q', 1, fluid);
h_0(i) = CoolProp.PropsSI('H','T',T(i),'Q', 0, fluid);
s_1(i) = CoolProp.PropsSI('S','T',T(i),'Q', 1, fluid);
s_0(i) = CoolProp.PropsSI('S','T',T(i),'Q', 0, fluid);
end
figure;
plot(h_0,T,h_1,T,h,450,'r-o')
figure;
plot(s_0,T,s_1,T,4000,450,'r-o')
figure;
plot(s_0,h_0,s_1,h_1,4000,h,'r-o')

The results from the point I am trying to find is the following:
h = 2.5559e+06
p = 9.3220e+05
xh = 0.8921
xs = 0.4202

and the plots look as in the picture, the point that is showen should be the same.
How can it be that at a Temperature ans entropy that are definitly in the two phase region, it finds and enthalpy that is out of this region? Is this a bug or am i making a horrible mistake?
![fault](https://cloud.githubusercontent.com/assets/16686356/13251907/548f2b88-da33-11e5-8354-8b4433b45b2f.png)

**Comment by ibell** [comment]
Have you tried with the development version of CoolProp?  We had some bugs
with TS and HS inputs that we have fixed.  Maybe that is what you see too.

I take it this is MATLAB, but what operating system?

**Comment by Tom0310** [comment]
No i havent, i will try it.
I am using windows 7 64-bit

**Comment by ibell** [comment]
Consistency plots seem fine: http://www.coolprop.org/dev/fluid_properties/fluids/Water.html#consistency-plots

**Comment by Tom0310** [comment]
Problems are indeed solved by using the development version.
Thanks for the help

**Comment by ibell** [comment]
Good, please close the issue then.
