### ISSUE TITLE
Air lookup in Excel v5.1.2

### ISSUE THREAD

**Issue by milesabarr** [CoolProp/CoolProp#986]
When I try =propssi("H", "P", 5000000, "S", propssi("S","H", 410082,"P",1807963,"Air"), "Air") in Excel it gives me this error:

"unable to solve 1phase PY flash with Tmin=59.749, Tmax=3000 due to error: Bad phase to solver_rho_Tp_SRK : PropsSI("H","P",5000000,"S",3006.040417,"Air")"

Miles

**Comment by ibell** [comment]
I fixed everything but the crazy high pressures
