### ISSUE TITLE
Contributor license agreements

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#988]
What about adding https://github.com/integrations/cla-assistant to CoolProp? Just to make sure that the code remains in the public domain and that no GPL'ed code goes viral.

**Comment by ibell** [comment]
Yes sure that seems fine with me.  Go for it!

**Comment by jowr** [comment]
I installed this CLA: https://gist.github.com/jowr/2e853c95357d39c5479a4e75b549a5dc 
Any objections?

**Comment by ibell** [comment]
No objections, looks good!
