### ISSUE TITLE
Running CoolProp with Excel for Mac 2016

### ISSUE THREAD

**Issue by ingojahn** [CoolProp/CoolProp#989]
Hi,

I know excel for mac 2016 isnt officially supported yet, but it is currently the only excel version I have access to...
Previously I had Coolprop running on the same computer with excel 2011 without any issues.

I have attempted to install CoolProp following the standard excel for mac 2011 instructions:
- create folder ~/lib/   (i.e. this is /user/lib/)  and I have copied libCoolProp.dylib
- I have downloaded CoolProp.xlam 
- I have selected CoolProp.xlam as an Add-in in Excel

When testing the code I get the following error message from excel:
**The most recent error number is 53. Its message text is: File not found: libCoolProp.dylib**

Is there a different location for the libCoolProp.dylib in excel 2016? 
Is there anywhere that I can check where excel is searching?

Thanks
Ingo

**Comment by ibell** [comment]
I suspect you are using the wrong path.  For me my path is
```
Ians-Mac-mini:scripts ian$ cd ~
Ians-Mac-mini:~ ian$ pwd
/Users/ian
```
and I would therefore put the shared library in ``/Users/ian/lib``

**Comment by ingojahn** [comment]
That is what I though initially. I have been trying changing the location, but no luck...
Here is what I get:

`Macintosh-4:~ ingojahn$ cd ~`
`Macintosh-4:~ ingojahn$ pwd`
`/Users/ingojahn`
`Macintosh-4:~ ingojahn$ cd lib`
`Macintosh-4:lib ingojahn$ ls`
`libCoolProp.dylib`
`Macintosh-4:lib ingojahn$ file libCoolProp.dylib `
`libCoolProp.dylib: Mach-O dynamically linked shared library i386`

Is it possible that Excel 2016 looks somewhere else? 
I have tried office support to find out where excel looks for the file, but no help from them.

**Comment by ibell** [comment]
You might also want to try one of the default search locations.  See for instance: http://blog.leshill.org/blog/2010/04/24/dynamic-load-paths-in-osx.html

Therefore you might want to add a different path to your ~/.bash_profile file.  E.G:

```
export DYLD_LIBRARY_PATH="/Users/ingojahn/lib:$DYLD_LIBRARY_PATH"
```

**Comment by ibell** [comment]
What operating system are you using?

**Comment by ibell** [comment]
I've been playing with Office 2016 on OSX 10.10, and I agree.  I cannot get it to work, and I can't understand why.

Things I have tried:
* Copying 32-bit dll to /usr/local as suggested here : https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html#//apple_ref/doc/uid/TP40002182-SW10
* Thinking that perhaps Office 2016 is now 64-bit, putting a 64-bit dll in the same location.  Also doesn't work.  Can't tell if Excel is 32-bit or 64-bit.
* Hardcoded path to dylib in xlam

**Comment by ingojahn** [comment]
I am running OSX 10.11 on a Mid 2011 MacBook Air. 
I also tried to ring office support. But they had no idea on what search path is used by Excel 2016.

For the moment my work-around is to do everything in python. But would be great to get excel capability to do some simple calcs and quick graphs.

**Comment by ibell** [comment]
Don't get me started, but python is so much superior to Excel for quick and dirty calcs and plotting.  I assume you are aware of matplotlib?

Excel 2016-wise, I don't know what is going on.  There are plenty of other potential things that could manifest in this behavior, I can try to dig a bit further and see if I get anywhere.  At this point, I'm not terribly optimistic.

**Comment by jowr** [comment]
For security reasons, Office 2016 applications seem to run in a sandbox. You simply cannot get out of without running AppleScript. Source: https://dev.office.com/blogs/VBA-improvements-in-Office-2016

**Comment by jowr** [comment]
It looks like there is a path that can be used to access the dylib files. Could any of you Mac users try to follow the instructions at http://www.rondebruin.nl/mac/mac034.htm ?

**Comment by ibell** [comment]
Hmm, that seemed promising, but that doesn't seem to fix the shared library loading.  It seems like it only works for "normal" files.

**Comment by ibell** [comment]
Still stuck.

**Comment by jowr** [comment]
What about installing the dylibs there and providing the full path in the macro?

**Comment by ibell** [comment]
Yup, that's precisely what I tried.  Not sure what the next step is.  I
would like to get this working with REFPROP too, so I am very interested in
finding a solution.

**Comment by ibell** [comment]
Bump.  Have any of you made any progress with this?

**Comment by ibell** [comment]
Bump.

**Comment by ibell** [comment]
I figured it out!!! Docs to follow, but here is the basic gist:

See http://www.rondebruin.nl/mac/mac034.htm

Setting up XLAM
---------------

1. Place XLAM file in ``/Users/${USER}/Library/Group Containers/UBF8T346G9.Office`` where ``${USER}`` should be replaced with your user name

2. Open Excel, go to Tools/Add-ins... .  In browse, go to the folder listed above with the ``BF8T346G9.Office`` in it. Select CoolProp.xlam.

3. Add this to a cell::

	=PropsSI("T","P",101325,"Q",0,"Water")

  make sure you get something like 373.1242958 K.

Setting environment variables at startup
----------------------------------------

1. Following http://apple.stackexchange.com/a/106814, save these contents as the file ``~/Library/LaunchAgents/my.startup.plist`` (obviously replace ``ihb`` with the appropriate user name) 

```
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
    <key>Label</key>
    <string>my.startup</string>
    <key>ProgramArguments</key>
    <array>
      <string>sh</string>
      <string>-c</string>
      <string>launchctl setenv DYLD_LIBRARY_PATH "/Users/ihb/Library/Group Containers/UBF8T346G9.Office"</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    </dict>
    </plist>
```

2. Log out and log back in

3. If you want to add additional paths to the terminal, you can add a line like this to your ``~/.bash_profile`` for instance to append paths to the ``DYLD_LIBRARY_PATH`` variable.  It calls launchctl to extract the DYLD_LIBRARY_PATH environment variable and prepends /another/path to it::

    export DYLD_LIBRARY_PATH="/another/path:`launchctl getenv DYLD_LIBRARY_PATH`"

**Comment by ibell** [comment]
Can anyone try the procedure for #1744 ?  That worked for one user, and I think we might be closing in on a working solution with Excel 2016 on Mac after several years :/

**Comment by hopalonghopper** [comment]
With the following tweaks mine is working in Excel 16.29 (office 365) on OSX:
No need to setup environment variables, just put the absolute path to the dylib inside each function declaration statement in Coolprop.xlam.

I also got the REFPROP backend to work by placing librefprop.dylib and the FLUIDS and MIXTURES folders inside ~/${USER}/lib

**Comment by HCSpin** [comment]
I have tried to follow these steps for Excel 2019 for Mac to no avail.  Do you know if there is a working solution for this version of Excel?
