### ISSUE TITLE
Inconsistent values for enthalpy of Ammonia in the vapor dome

### ISSUE THREAD

**Issue by bryanwweber** [CoolProp/CoolProp#991]
Hello,
I am computing an isentropic expansion of ammonia from a saturated vapor into the two-phase region. However, the values I get for the enthalpy are different depending if I manually calculate with the quality, or set the state with the temperature and entropy. However, the manually calculated quality and the quality from PropsSI are equal. I am using CoolProp 5.1.2 on Windows 7 x64, installed from pip in Python 3.5. Any help is appreciated. Thank you!

```
from CoolProp.CoolProp import PropsSI

T_1 = 322.039  # K
T_2 = 288.705  # K
Q_1 = 1.0
sub = 'NH3'

s_1 = PropsSI('S', 'T', T_1, 'Q', Q_1, sub)
s_2 = s_1
h_2a = PropsSI('H', 'T', T_2, 'S', s_2, sub)
Q_2a = PropsSI('Q', 'T', T_2, 'S', s_2, sub)

s_f = PropsSI('S', 'T', T_2, 'Q', 0.0, sub)
s_g = PropsSI('S', 'T', T_2, 'Q', 1.0, sub)
h_f = PropsSI('H', 'T', T_2, 'Q', 0.0, sub)
h_g = PropsSI('H', 'T', T_2, 'Q', 1.0, sub)
Q_2b = (s_2 - s_f)/(s_g - s_f)

print(Q_2b - Q_2a)
# 1.1102230246251565e-16

h_2b = h_f + Q_2b*(h_g - h_f)
print(h_2a - h_2b)
# 100280.16004404705
```

**Comment by ibell** [comment]
You need to use the development version, it should have fixed this bug.  I
guess you are using 5.1.2?

**Comment by bryanwweber** [comment]
Yes, I am. Good to know its fixed! Sorry if this was a duplicate!
