### ISSUE TITLE
Check double_equal in CPnumerics.h

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#995]
When building the ExternalMedia library (with VisualStudio 2010 and 2015), I'm having the error:
```C++
c:\users\johndoe\source\repos\externalmedia\externals\coolprop.git\include\CPnumerics.h(403): error C2589: '(': illegal token on right side of '::' (compiling source file Sources\solvermap.cpp)
c:\users\johndoe\source\repos\externalmedia\externals\coolprop.git\include\CPnumerics.h(403): error C2059: syntax error: '::' (compiling source file Sources\solvermap.cpp)
```
This correspond to the [line](https://github.com/CoolProp/CoolProp/blob/master/include/CPnumerics.h#L403):
```C++
inline bool double_equal(double a, double b){return std::abs(a - b) <= 1 * DBL_EPSILON * std::max(std::abs(a), std::abs(b));};
```
Of the file `include\CPnumerics.h`

(as discussed in https://github.com/CoolProp/ExternalMedia/issues/17 it may be a missing header needed for std::max or std::abs)

**Comment by ibell** [comment]
I compiled an executable for CoolProp using:

cmake ../.. -G "Visual Studio 10 2010 Win64" -DCOOLPROP_MAIN_MODULE=ON

and it compiled just fine.  Suggesting the problem is perhaps not actually
in CoolProp.

**Comment by JonWel** [comment]
The error is displayed when compiling `Sources\solvermap.cpp` from `ExternalMedia`.

This seems to make a problem with to the [function](https://github.com/CoolProp/ExternalMedia/blob/master/Projects/Sources/solvermap.cpp#L25):
```C++
BaseSolver *SolverMap::getSolver(const string &mediumName, const string &libraryName, const string &substanceName){
	// Get solver key from library and substance name
	string solverKeyString(solverKey(libraryName, substanceName));
	// Check whether solver already exists
	if (_solvers.find(solverKeyString) != _solvers.end())
		return _solvers[solverKeyString];
	// Create new solver if it doesn't exist
	// Test solver for compiler setup debugging
	if (libraryName.compare("TestMedium") == 0)
	  _solvers[solverKeyString] = new TestSolver(mediumName, libraryName, substanceName);
	
#if (FLUIDPROP == 1)
	// FluidProp solver
	else if (libraryName.find("FluidProp") == 0)
	  _solvers[solverKeyString] = new FluidPropSolver(mediumName, libraryName, substanceName);
#endif // FLUIDPROP == 1

#if (COOLPROP == 1)
	// CoolProp solver
	else if (libraryName.find("CoolProp") == 0)
	  _solvers[solverKeyString] = new CoolPropSolver(mediumName, libraryName, substanceName);
#endif // COOLPROP == 1

	else {
	  // Generate error message
	  char error[100];
	  sprintf(error, "Error: libraryName = %s is not supported by any external solver\n", libraryName.c_str());
	  errorMessage(error);
	}
	// Return pointer to solver
	return _solvers[solverKeyString];
};
```
Which has been last time modified in Jully, so way before the `CPnumerics.h` was even created.

So the error may not been shown in the right place.
The way to instantiate the `CoolProp state` has been changed from the CoolProp class to the shared pointer. Maybe this appears to cause a problem here (but then why not pointing the real problem and showing an other file ...)?

**Comment by ibell** [comment]
I think I might have fixed this one, please confirm and then close

**Comment by JonWel** [comment]
I still have the same error message.

I also check when reverting the change from the shared pointer to the Abstract Class, but I still have the same issue.
An other one also showed with the refprop_lib header:
```C++
e:\externalmediavisual\externals\coolprop.git\externals\refprop-headers\refprop_lib.h(522): error C2664: 'strcpy' : cannot convert parameter 1 from 'TCHAR [100]' to 'char *'
          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
e:\externalmediavisual\externals\coolprop.git\externals\refprop-headers\refprop_lib.h(525): error C2664: 'strcpy' : cannot convert parameter 1 from 'TCHAR [100]' to 'char *'
          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
  solvermap.cpp
e:\externalmediavisual\externals\coolprop.git\include\cpnumerics.h(405): error C2589: '(' : illegal token on right side of '::'
e:\externalmediavisual\externals\coolprop.git\include\cpnumerics.h(405): error C2059: syntax error : '::'
```

**Comment by ibell** [comment]
How can I test this compilation?

**Comment by JonWel** [comment]
The simplest is to download the [ExternalMedia git](https://github.com/CoolProp/ExternalMedia/tree/master/Projects) version and to run the  `BuildLib-Dymola-VS20xx.bat` corresponding to your visual studio, which should give the `CPnumerics.h` error.

**Comment by ibell** [comment]
Ah now I understand....  It is the classic MSVC problem of providing a
MACRO (Evil!) for min() and max().  The solution is to define the macro
NOMINMAX in BuildLib-VS.bat which kills this behavior. For example

set C_OPTS=/Ox /c /MP3 /fp:fast /MD /EHsc /DNOMINMAX

I couldn't figure out where to make my pull request against, so I'll let
you do it.  It builds now.

**Comment by ibell** [comment]
I also just fixed it by undefining the macro.  I think the problem comes from the cppformat library which doesn't define the NOMINMAX macro when including windows.h.  I'll file an issue
